Mezzo GA
microsoftgraph/microsoft-graph-docs pull request #10047
Opened 2020-09-24 22:29 UTC by davidmu1

2020-09-24 22:30 UTC, opbld31 commented
Docs Build status updates of commit _[876489f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/876489f3bf344341dad14691089cc75063b804a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-f9062e4b-ca2718be)
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-a84edfc1-ca2718be)
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-58449b93-ca2718be)
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-ca2718be)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-ca2718be)
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1e24bd98-ca2718be)
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-2e55b6ef-ca2718be)
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-0b26f239-ca2718be)
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-97221224-ca2718be)
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-f88d520f-ca2718be)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-ca2718be)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-ca2718be)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-ca2718be)
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="f9062e4b-ca2718be"></a>
### [api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the list of applications in this organization.' is duplicated in 'beta/api/application-list.md(3,14)', 'v1.0/api/application-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a84edfc1-ca2718be"></a>
### [api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get groups that this device is a direct member of. This operation is not transitive.' is duplicated in 'beta/api/device-list-memberof.md(3,14)', 'v1.0/api/device-list-memberof.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="58449b93-ca2718be"></a>
### [api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get groups that the device is a member of.' is duplicated in 'beta/api/device-list-trans [...]

2020-09-24 23:24 UTC, opbld32 commented
Docs Build status updates of commit _[13bb255](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13bb255a6eca0c917f164f6e8a25d606506584df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-f9062e4b-ccc5e930)
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-a84edfc1-ccc5e930)
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-58449b93-ccc5e930)
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-ccc5e930)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-ccc5e930)
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1e24bd98-ccc5e930)
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-2e55b6ef-ccc5e930)
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-0b26f239-ccc5e930)
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-97221224-ccc5e930)
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-f88d520f-ccc5e930)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-ccc5e930)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-ccc5e930)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-ccc5e930)
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="f9062e4b-ccc5e930"></a>
### [api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get the list of applications in this organization.' is duplicated in 'beta/api/application-list.md(3,14)', 'v1.0/api/application-list.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="a84edfc1-ccc5e930"></a>
### [api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get groups that this device is a direct member of. This operation is not transitive.' is duplicated in 'beta/api/device-list-memberof.md(3,14)', 'v1.0/api/device-list-memberof.md(3,14)'. NOTE: This Suggestion will become a Warning in late October, 2020.`````

<a id="58449b93-ccc5e930"></a>
### [api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Get groups that the device is a member of.' is duplicated in 'beta/api/device-list-trans [...]

2020-09-28 16:48 UTC, opbld33 commented
Docs Build status updates of commit _[d111460](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d111460d9d7b14304038de7ce3b540d6345f5012)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-cb49f271)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-cb49f271)
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1e24bd98-cb49f271)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-cb49f271)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-cb49f271)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-cb49f271)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-cb49f271)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-cb49f271"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'List memberOf' is duplicated with other articles: 'beta/api/connector-list-memberof.md(10,1), v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="d2f320e4-cb49f271"></a>
### [api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/con [...]

2020-09-28 17:23 UTC, opbld33 commented
Docs Build status updates of commit _[a04a37f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a04a37fdc7b8c65f0677195d22a199d640311cba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-971ce3d8)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-971ce3d8)
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1e24bd98-971ce3d8)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-971ce3d8)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-971ce3d8)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-971ce3d8)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-971ce3d8)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-971ce3d8"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'List memberOf' is duplicated with other articles: 'beta/api/connector-list-memberof.md(10,1), v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/ [...]

2020-09-28 17:26 UTC, opbld31 commented
Docs Build status updates of commit _[a04a37f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a04a37fdc7b8c65f0677195d22a199d640311cba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-f292051e)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-f292051e)
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1e24bd98-f292051e)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-f292051e)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-f292051e)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-f292051e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-f292051e)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-f292051e"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'List memberOf' is duplicated with other articles: 'beta/api/connector-list-memberof.md(10,1), v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/ [...]

2020-09-28 17:31 UTC, opbld34 commented
Docs Build status updates of commit _[abea05c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/abea05c299a8f56df9991e80d2977405e1e2d143)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-92de282a)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-92de282a)
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1e24bd98-92de282a)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-92de282a)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-92de282a)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-92de282a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-92de282a)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-92de282a"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'List memberOf' is duplicated with other articles: 'beta/api/connector-list-memberof.md(10,1), v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/ [...]

2020-10-02 21:25 UTC, opbld33 commented
Docs Build status updates of commit _[4efd561](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4efd5619493ad7bce2a9e0ad47240bff5f792c36)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4fa43d6d)

<a id="4fa43d6d"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010022125111189-10047%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Nt%2FQBJAwnaWZ3WpVUbxAnyAbxOSQvXWgHSJ7AINa6JE%3D&st=2020-10-02T21%3A20%3A35Z&se=2020-11-02T21%3A25%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-02 22:30 UTC, opbld30 commented
Docs Build status updates of commit _[c4d81da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4d81da9b3bf271959bae10d862031925a20fca5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-46ce5270)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-46ce5270)
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1e24bd98-46ce5270)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-46ce5270)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-46ce5270)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-46ce5270)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-46ce5270)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-46ce5270"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/con [...]

2020-10-04 03:31 UTC, millicentachieng commented on api-reference/v1.0/api/orgcontact-list-transitivememberof.md
> +GET https://graph.microsoft.com/v1.0/{id}/transitiveMemberOf
Should match what's under the **HTTP request** heading  `https://graph.microsoft.com/v1.0/contacts/{id}/transitiveMemberOf`

2020-10-22 00:17 UTC, Licantrop0 requested changes
Addressing issues in queries and other details.

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-transitivemembers.md
> +This method supports the [OData query parameters](/graph/query-parameters) to help customize the response, including `$search`, `$count`, and `$filter`. You can use `$search` on the **displayName** p
```suggestion
This method supports the [OData query parameters](/graph/query-parameters) to help customize the response, including `$search`, `$count`, and `$filter`. You can use `$search` on the **displayName** and **description** properties. When items are added or updated for this resource, they are specially indexed for use with the `$count` and `$search` query parameters. There can be a slight delay between when an item is added or updated and when it is available in the index.
```

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-transitivemembers.md
> +      "id": "11111111-2222-3333-4444-555555555555",
```suggestion
      "@odata.type": "#microsoft.graph.user",
      "id": "11111111-2222-3333-4444-555555555555",
```

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-transitivemembers.md
> +  "@odata.type": "microsoft.graph.directoryObject",
raw count not a directory object

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-transitivemembers.md
> +893
```suggestion
`893`
```

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-transitivemembers.md
> +  "@odata.type": "microsoft.graph.group",
```suggestion
  "@odata.type": "microsoft.graph.user",
```

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-transitivemembers.md
> +  "@odata.context":"https://graph.microsoft.com/v1.0/$metadata#groups(displayName,id)",
```suggestion
  "@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users(displayName,id)",
```

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-transitivemembers.md
> +      "mail": "group1@contoso.com",
```suggestion
     "displayName": "Joseph Price",
     "mail": "Joseph.Price@contoso.com",
```

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-transitivemembers.md
> +      "mailNickname": "Contoso1",
remove mailEnabled, mailNickname and securityEnabled: not relevant for User Object

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-members.md
> +      "mail":"AADContoso_Users@contoso.com",
```suggestion
      "mail":"Joseph.Price@contoso.com",
```

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-members.md
> +      "mailNickname":"AADContoso_Users",
remove mailEnabled, mailNickname and securityEnabled: not relevant for User Object

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-transitivemembers.md
> +      "displayName":"Contoso-tier Query Notification",
```suggestion
      "displayName":"Joseph Price",
```

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-transitivemembers.md
> +  "@odata.type": "microsoft.graph.group",
```suggestion
  "@odata.type": "microsoft.graph.user",
```

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-transitivemembers.md
> +  "@odata.context":"https://graph.microsoft.com/v1.0/$metadata#groups",
```suggestion
  "@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users",
```

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-transitivemembers.md
> +      "displayName":"AAD Contoso Users",
```suggestion
      "displayName":"Joseph Price",
```

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-transitivemembers.md
> +      "mail":"AADContoso_Users@contoso.com",
```suggestion
      "mail":"Joseph.Price@contoso.com",
```

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/group-list-transitivemembers.md
> +      "mailNickname":"AADContoso_Users",
remove mailEnabled, mailNickname and securityEnabled: not relevant for User Object

2020-10-22 00:17 UTC, Licantrop0 commented on api-reference/v1.0/api/serviceprincipal-list-memberof.md
> +This method supports the [OData query parameters](/graph/query_parameters) to help customize the response, including `$search`, `$count`, and `$filter`. OData cast is also enabled, for example, you c
```suggestion
This method supports the [OData query parameters](/graph/query_parameters) to help customize the response, including `$search`, `$count`, and `$filter`. OData cast is also enabled, for example, you can cast to get just the directoryRoles the user is a member of. You can use `$search` on the **displayName** and **description** properties. When items are added or updated for this resource, they are specially indexed for use with the `$count` and `$search` query parameters. There can be a slight delay between when an item is added or updated and when it is available in the index.
```

2020-10-23 17:42 UTC, opbld32 commented
Docs Build status updates of commit _[0b95954](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b9595426a44f0fd9667c0899c923cb01f83c72f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2ff7324e)

<a id="2ff7324e"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010231742119645-10047%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Bw871jnpUpBXpU7qD84Kz%2FgZuqfaEW1PlVFLswWtEjE%3D&st=2020-10-23T17%3A37%3A42Z&se=2020-11-23T17%3A42%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-23 17:43 UTC, opbld32 commented
Docs Build status updates of commit _[ed78c4b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed78c4b23cec809766336e3687249bb5284fc3fb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6e7ba98b)

<a id="6e7ba98b"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010231743089928-10047%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oF7I2mybEymU5Iv2mXPBebr5XZ%2F1wCZUja4Dj3FYjUQ%3D&st=2020-10-23T17%3A38%3A40Z&se=2020-11-23T17%3A43%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-23 17:43 UTC, opbld34 commented
Docs Build status updates of commit _[ed78c4b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed78c4b23cec809766336e3687249bb5284fc3fb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ae995f5b)

<a id="ae995f5b"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010231743191047-10047%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FiUMrRv%2Bw8n25s9Q%2Bdoc79eHkRTyF15NpWamCGwm%2F6Q%3D&st=2020-10-23T17%3A38%3A58Z&se=2020-11-23T17%3A43%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-23 17:52 UTC, opbld31 commented
Docs Build status updates of commit _[3dca6f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3dca6f75ea0a0fa296f7fa863259bf1d4e5edb55)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-77c1acba)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-77c1acba)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-77c1acba)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-77c1acba)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-77c1acba)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-77c1acba)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-77c1acba"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 16:29 UTC, opbld32 commented
Docs Build status updates of commit _[3dca6f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3dca6f75ea0a0fa296f7fa863259bf1d4e5edb55)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-c091c7a4)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-c091c7a4)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-c091c7a4)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-c091c7a4)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-c091c7a4)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-c091c7a4)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-c091c7a4"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 16:36 UTC, opbld34 commented
Docs Build status updates of commit _[989815c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/989815cf24e3966c7f25bd7273a4c4aac569cdb8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-687fc0cb)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-687fc0cb)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-687fc0cb)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-687fc0cb)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-687fc0cb)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-687fc0cb)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-687fc0cb"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 16:38 UTC, opbld31 commented
Docs Build status updates of commit _[632c1c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/632c1c1f1b93042a8f2eb41b1b536537414cb246)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-3e6ae1f6)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-3e6ae1f6)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-3e6ae1f6)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-3e6ae1f6)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-3e6ae1f6)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-3e6ae1f6)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-3e6ae1f6"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 16:41 UTC, opbld34 commented
Docs Build status updates of commit _[15b7d00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15b7d0006a90755e21eddf5a111362f7db8e7ab9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-4749036e)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-4749036e)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-4749036e)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-4749036e)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-4749036e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-4749036e)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-4749036e"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 16:55 UTC, opbld31 commented
Docs Build status updates of commit _[29e8859](https://github.com/microsoftgraph/microsoft-graph-docs/commits/29e88594fa0c0ed7cdc4aaa1effbca4cf84b39f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-f1d6efd1)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-f1d6efd1)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-f1d6efd1)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-f1d6efd1)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-f1d6efd1)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-f1d6efd1)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-f1d6efd1"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 16:57 UTC, opbld31 commented
Docs Build status updates of commit _[be713e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be713e166cd4eca5b9b0b2b2ad73f4ed99b8de1d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-13c81839)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-13c81839)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-13c81839)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-13c81839)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-13c81839)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-13c81839)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-13c81839"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 16:58 UTC, opbld31 commented
Docs Build status updates of commit _[be713e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be713e166cd4eca5b9b0b2b2ad73f4ed99b8de1d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-42a76c87)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-42a76c87)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-42a76c87)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-42a76c87)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-42a76c87)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-42a76c87)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-42a76c87"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 17:00 UTC, opbld33 commented
Docs Build status updates of commit _[a043372](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a04337253ec06dff881528c3c18dc56ff5798981)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-df996625)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-df996625)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-df996625)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-df996625)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-df996625)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-df996625)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-df996625"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 17:02 UTC, opbld32 commented
Docs Build status updates of commit _[7003fab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7003fab0f7c697b252401094cf87e1fac3b09b54)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-49e96f8e)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-49e96f8e)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-49e96f8e)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-49e96f8e)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-49e96f8e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-49e96f8e)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-49e96f8e"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 17:04 UTC, opbld33 commented
Docs Build status updates of commit _[981ee0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/981ee0def93dcefa74b8326aecd77a33f43e40e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-8c863cd6)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-8c863cd6)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-8c863cd6)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-8c863cd6)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-8c863cd6)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-8c863cd6)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-8c863cd6"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 17:06 UTC, opbld32 commented
Docs Build status updates of commit _[28df83e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/28df83e8ea0d0c3274685c43b2e523514ce1f6c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-bed65d01)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-bed65d01)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-bed65d01)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-bed65d01)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-bed65d01)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-bed65d01)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-bed65d01"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 17:07 UTC, opbld34 commented
Docs Build status updates of commit _[ff173c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff173c7435a567bfcb177444a62cf1378e5c5651)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-c2603b19)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-c2603b19)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-c2603b19)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-c2603b19)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-c2603b19)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-c2603b19)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-c2603b19"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 17:08 UTC, opbld30 commented
Docs Build status updates of commit _[e774278](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e77427855ff126e7f53a03de92e165eafee3810d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-ca3c0922)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-ca3c0922)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-ca3c0922)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-ca3c0922)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-ca3c0922)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-ca3c0922)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-ca3c0922"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 17:10 UTC, opbld34 commented
Docs Build status updates of commit _[7825877](https://github.com/microsoftgraph/microsoft-graph-docs/commits/782587797ab0ccdfc36fa725e25df2cbdde4a56a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-6df8117c)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-6df8117c)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-6df8117c)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-6df8117c)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-6df8117c)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-6df8117c)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-6df8117c"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 17:11 UTC, opbld30 commented
Docs Build status updates of commit _[14fc1e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14fc1e9dc24111b08a0a92b52ea77a5f643d1b1c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-ee1eff1c)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-ee1eff1c)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-ee1eff1c)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-ee1eff1c)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-ee1eff1c)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-ee1eff1c)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-ee1eff1c"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 17:13 UTC, opbld33 commented
Docs Build status updates of commit _[1ba238d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ba238dbbff81ddd55ebc32c6bdd93282a25ef82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-59ebe29b)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-59ebe29b)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-59ebe29b)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-59ebe29b)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-59ebe29b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-59ebe29b)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-59ebe29b"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 17:14 UTC, opbld32 commented
Docs Build status updates of commit _[c994690](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c99469054d2ac45c2212d3830d8f868736ccc34b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-53229246)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-53229246)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-53229246)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-53229246)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-53229246)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-53229246)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-53229246"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 17:16 UTC, opbld34 commented
Docs Build status updates of commit _[a67a406](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a67a4068e40291e2aaa1826cf04e72f3f57b6221)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-9535dfbf)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-9535dfbf)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-9535dfbf)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-9535dfbf)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-9535dfbf)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-9535dfbf)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-9535dfbf"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 17:18 UTC, opbld30 commented
Docs Build status updates of commit _[2347459](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2347459ef2c8553401e4240e4061f8e4092daf66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-c54066c2)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-c54066c2)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-c54066c2)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-c54066c2)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-c54066c2)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-c54066c2)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-c54066c2"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h [...]

2020-10-26 22:49 UTC, opbld31 commented
Docs Build status updates of commit _[73cca08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73cca08ed263100a54c444643d72a103955e3ad8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-58449b93-7989e60f)
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d33c49c4-7989e60f)
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-7989e60f)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-7989e60f)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-7989e60f)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-7989e60f)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-7989e60f)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-7989e60f)
[api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/beta/api/user-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&branch=pr-en-us-10047) (graph-rest-beta) |
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="58449b93-7989e60f"></a>
### [api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md)
 - **Line 38, Column 1**: **[Warning-[merge-conflict](https://aka.ms/merge-conflict)]** `````File contains merge conflict markers.`````
 - **Line 40, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '<<<<<<< HEAD
This method supports the OData query parameters to help customize the response, including , , and . OData cast is also ena [...]

2020-10-26 23:01 UTC, opbld34 commented
Docs Build status updates of commit _[daf5912](https://github.com/microsoftgraph/microsoft-graph-docs/commits/daf5912d39001988be9e7f13dbe1a0fc0c272d8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-5100e15e)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-5100e15e)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-5100e15e)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-5100e15e)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-5100e15e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-5100e15e)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-5100e15e"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21. [...]

2020-10-26 23:42 UTC, opbld30 commented
Docs Build status updates of commit _[c2d083e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2d083ee65122e3ce76b30a39f8ada8287d0dc44)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-77b1accb)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-77b1accb)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-77b1accb)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-77b1accb)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-77b1accb)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-77b1accb)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-77b1accb"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21. [...]

2020-10-27 16:51 UTC, opbld33 commented
Docs Build status updates of commit _[ff1e9c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff1e9c52399737556cb4615ae37d2cfa24c92797)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-cff7a0fa)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-cff7a0fa)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-cff7a0fa)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-cff7a0fa)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-cff7a0fa)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-cff7a0fa)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-cff7a0fa"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21. [...]

2020-10-27 17:26 UTC, opbld30 commented
Docs Build status updates of commit _[72fc5d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/72fc5d2550d5f8f4d2cc169b5f01e71f710b15d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-f893a44b)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-f893a44b)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-f893a44b)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-f893a44b)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-f893a44b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-f893a44b)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-f893a44b"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21. [...]

2020-10-27 17:36 UTC, opbld31 commented
Docs Build status updates of commit _[0b17b7d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b17b7d0584fe8241fb0ace9c63220a557653365)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-ff027a1b)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-ff027a1b)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-ff027a1b)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-ff027a1b)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-ff027a1b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-ff027a1b)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-ff027a1b"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21. [...]

2020-10-28 00:00 UTC, Licantrop0 approved these changes
few issues with metadata, but we can send it and fix later

2020-10-28 04:13 UTC, kksrivatsa approved these changes

2020-10-28 17:17 UTC, opbld31 commented
Docs Build status updates of commit _[84dbdfd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84dbdfd6e8d61f910c90fae36cfcab94be842a9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-dfc025e1)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-dfc025e1)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-dfc025e1)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-dfc025e1)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-dfc025e1)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-dfc025e1)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-dfc025e1"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21. [...]

2020-10-28 17:19 UTC, opbld34 commented
Docs Build status updates of commit _[84dbdfd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84dbdfd6e8d61f910c90fae36cfcab94be842a9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-3e45a962)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-3e45a962)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-3e45a962)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-3e45a962)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-3e45a962)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-3e45a962)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-3e45a962"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21. [...]

2020-10-28 18:00 UTC, opbld33 commented
Docs Build status updates of commit _[a210459](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a21045941eb6d1e308faa2517b3493093715471b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-4e2ddfab)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-4e2ddfab)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-4e2ddfab)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-4e2ddfab)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-4e2ddfab)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-4e2ddfab)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-4e2ddfab"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21. [...]

2020-10-28 18:20 UTC, davidmu1 commented on api-reference/v1.0/api/device-list-memberof.md
> +  "name": "get_a_count"
Not seeing a duplicate name in the file.

2020-10-28 18:20 UTC, opbld31 commented
Docs Build status updates of commit _[1b4b67f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b4b67fe172718b7440fb8ac1fe8d8daa124d143)_: 

:clock10: **Pending**: waiting for processors ([25](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 25 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-28 18:22 UTC, opbld32 commented
Docs Build status updates of commit _[1b4b67f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b4b67fe172718b7440fb8ac1fe8d8daa124d143)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-91167659)

<a id="91167659"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010281820501779-10047%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=esL7vOn2WYJDXZKixC%2BOY119i%2F5Rl4gOGn8sFZ%2FBYNE%3D&st=2020-10-28T18%3A17%3A09Z&se=2020-11-28T18%3A22%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 18:24 UTC, opbld34 commented
Docs Build status updates of commit _[1831eb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1831eb6a409f53c7835c82ac615936779b9b40b4)_: 

:clock10: **Pending**: waiting for processors ([17](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-28 18:25 UTC, opbld32 commented
Docs Build status updates of commit _[5d532c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d532c5f9003935ad7ccba0c8b1e83ee83e25689)_: 

:clock10: **Pending**: waiting for processors ([12](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-28 18:26 UTC, opbld34 commented
Docs Build status updates of commit _[a8bdeb0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8bdeb0d557d29754cbf2e8c6f02606957a9d7c6)_: 

:clock10: **Pending**: waiting for processors ([12](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-28 18:26 UTC, opbld32 commented
Docs Build status updates of commit _[1831eb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1831eb6a409f53c7835c82ac615936779b9b40b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-9a2eeeeb)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-9a2eeeeb)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-9a2eeeeb)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-9a2eeeeb)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-9a2eeeeb)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-9a2eeeeb)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-9a2eeeeb"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21. [...]

2020-10-28 18:27 UTC, opbld33 commented
Docs Build status updates of commit _[fe34e0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe34e0cd86efab6a12fb6a019aabcb5251564a8a)_: 

:clock10: **Pending**: waiting for processors ([8](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-28 18:27 UTC, opbld31 commented
Docs Build status updates of commit _[fe34e0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe34e0cd86efab6a12fb6a019aabcb5251564a8a)_: 

:clock10: **Pending**: waiting for processors ([8](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-28 18:27 UTC, opbld30 commented
Docs Build status updates of commit _[a8bdeb0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8bdeb0d557d29754cbf2e8c6f02606957a9d7c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-8e65cb23)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-8e65cb23)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-8e65cb23)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-8e65cb23)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-8e65cb23)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-8e65cb23)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-8e65cb23"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21. [...]

2020-10-28 18:30 UTC, opbld32 commented
Docs Build status updates of commit _[fe34e0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe34e0cd86efab6a12fb6a019aabcb5251564a8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-d0812c71)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-d0812c71)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-d0812c71)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-d0812c71)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-d0812c71)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-d0812c71)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-d0812c71"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21. [...]

2020-10-29 02:38 UTC, opbld31 commented
Docs Build status updates of commit _[6104235](https://github.com/microsoftgraph/microsoft-graph-docs/commits/610423529f8ae2627069b9d75e9b88520b4de11f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-b031eea3)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-b031eea3)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-b031eea3)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-b031eea3)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-b031eea3)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-b031eea3)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-b031eea3"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21. [...]

2020-10-29 02:42 UTC, opbld34 commented
Docs Build status updates of commit _[77faf95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/77faf95bb2bd593f7e77d60ba10f452e30278ba6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-cd996bb4)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-cd996bb4)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-cd996bb4)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-cd996bb4)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-cd996bb4)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-cd996bb4)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |

<a id="382df096-cd996bb4"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1), v1.0/api/orgcontact-list-memberof.md(10,1), v1.0/api/user-list-memberof.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21. [...]

2020-10-29 02:49 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | beta | Added support for `$count`, `$search`, and `$filter` query parameters for improving query capabilities to: <br><ul><li>[List applications](/graph/api/application-list?view=graph-r
@davidmu1 , I assume the version here should be v1.0, since the update is to v1.0 files?

2020-10-29 03:00 UTC, opbld34 commented
Docs Build status updates of commit _[12920b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12920b766ef2afa21a43cd84a90f44e06b0767fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-f331bc3a)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-f331bc3a)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-f331bc3a)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-f331bc3a)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-f331bc3a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-f331bc3a)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="382df096-f331bc3a"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1 [...]

2020-10-29 03:02 UTC, opbld31 commented
Docs Build status updates of commit _[0404284](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0404284f0cf25980b5ab53928a2aaa24ce379bf2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-45dcb980)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-45dcb980)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-45dcb980)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-45dcb980)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-45dcb980)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-45dcb980)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="382df096-45dcb980"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1 [...]

2020-10-29 03:10 UTC, opbld30 commented
Docs Build status updates of commit _[8289b7c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8289b7c6b589ce55c285d5d3ea2a78c2c59d356e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-3e43dfd2)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-3e43dfd2)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-3e43dfd2)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-3e43dfd2)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-3e43dfd2)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-3e43dfd2)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="382df096-3e43dfd2"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1 [...]

2020-10-29 03:11 UTC, opbld33 commented
Docs Build status updates of commit _[517d453](https://github.com/microsoftgraph/microsoft-graph-docs/commits/517d4539ecf9bfff4dea31534aba6f5d9d495493)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-382df096-dc00029f)
[api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-d2f320e4-dc00029f)
[api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-memberof.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-1395af63-dc00029f)
[api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-dc00029f)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) | [Details](#user-content-6f302778-dc00029f)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10047) | [Details](#user-content-de0bbbbb-dc00029f)
[api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/application-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-transitivemembers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-memberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-memberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/serviceprincipal-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/user-list-transitivememberof.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&branch=pr-en-us-10047) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="382df096-dc00029f"></a>
### [api-reference/v1.0/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/mezzo-v1-1/api-reference/v1.0/api/group-list-memberof.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List memberOf - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/group-list-memberof.md(2,8), v1.0/api/orgcontact-list-memberof.md(2,8), v1.0/api/user-list-memberof.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List memberOf' is duplicated with other articles: 'v1.0/api/group-list-memberof.md(10,1 [...]

2020-10-29 03:14 UTC, merged