Added subnamescape information for To Do Resources and API
microsoftgraph/microsoft-graph-docs pull request #10075
Opened 2020-09-28 11:35 UTC by bgaonkar

Updated the namespace information for To Do Resources and APIs.
Previously : Namespace: microsoft.graph
Current Change : Namespace: microsoft.graph.todo

2020-09-28 11:36 UTC, opbld31 commented
Docs Build status updates of commit _[ed7e45c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed7e45c1d1beb5f699dff537dea100037714f6b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-97437326-1779f401)
[api-reference/beta/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-list-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-list-lists?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotask-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/linkedresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/resources/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/todo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todo?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/resources/todotasklist.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/todotasklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotasklist?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |

<a id="97437326-1779f401"></a>
### [api-reference/beta/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotasklist-list-tasks.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'List tasks' is duplicated with other articles: 'beta/api/printtaskdefinition-list-tasks.md(10,1), beta/api/todotasklist-list-tasks.md(10,1), v1.0/api/plannerbucket-list-tasks.md(10,1), v1.0/api/planner-list-tasks.md(10,1), v1.0/api/plannerplan-list-tasks.md(10,1),...'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on [...]

2020-09-29 00:54 UTC, Lauragra approved these changes

2020-09-29 01:40 UTC, Lauragra requested changes
Removing approval because this PR is missing additional documentation for the subnamespace.

2020-09-29 01:52 UTC, Lauragra commented on api-reference/beta/api/todotasklist-delta.md
> -Namespace: microsoft.graph
Is this function getting removed?

2020-09-29 04:24 UTC, VasantTiwari approved these changes

2020-09-29 05:45 UTC, opbld34 commented
Docs Build status updates of commit _[783bebd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/783bebd731073e277962325284251c56cff75c9c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotask-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-ee1b3ac0-62e480a4)
[api-reference/beta/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotask-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-96268428-62e480a4)
[api-reference/beta/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-97437326-62e480a4)
[api-reference/beta/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-list-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-list-lists?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-post-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-post-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-post-lists?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todotasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/linkedresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/resources/todo-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/todo-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todo-overview?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/resources/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/todo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todo?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-10075) (g [...]

2020-09-29 07:20 UTC, opbld30 commented
Docs Build status updates of commit _[e40768b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e40768b670f809b81ea1dcab0a03bef579a3ccbb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-delete.md) | :x:Error | | [Details](#user-content-229b6938-2f21eb37)
[api-reference/beta/api/tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-delete.md) | :x:Error | | [Details](#user-content-0fa6f385-2f21eb37)
[api-reference/beta/api/tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-get.md) | :x:Error | | [Details](#user-content-f8d5e4a4-2f21eb37)
[api-reference/beta/api/tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-post-tasks.md) | :x:Error | | [Details](#user-content-3adc358f-2f21eb37)
[api-reference/beta/api/tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-update.md) | :x:Error | | [Details](#user-content-75f919d7-2f21eb37)
[api-reference/beta/api/todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todoapp-list-lists.md) | :x:Error | | [Details](#user-content-d928a91c-2f21eb37)
[api-reference/beta/api/todoapp-post-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todoapp-post-lists.md) | :x:Error | | [Details](#user-content-a4bc47e0-2f21eb37)
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/linkedresource.md) | :warning:Warning | | [Details](#user-content-7e051031-2f21eb37)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-2f21eb37)
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | | [Details](#user-content-a1580d42-2f21eb37)
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :warning:Warning | | [Details](#user-content-6851a216-2f21eb37)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :warning:Warning | | [Details](#user-content-f9c13677-2f21eb37)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :warning:Warning | | [Details](#user-content-58f4f899-2f21eb37)
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | | [Details](#user-content-beb03a48-2f21eb37)
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/user.md) | :warning:Warning | | [Details](#user-content-8fa18829-2f21eb37)
[api-reference/beta/api/task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-get.md) | :bulb:Suggestion | | [Details](#user-content-214ba32e-2f21eb37)
[api-reference/beta/api/task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-update.md) | :bulb:Suggestion | | [Details](#user-content-2766c006-2f21eb37)
[api-reference/beta/api/tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-list-tasks.md) | :bulb:Suggestion | | [Details](#user-content-78b63abd-2f21eb37)

<a id="229b6938-2f21eb37"></a>
### [api-reference/beta/api/task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-delete.md)
 - **Line 63, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/delete-task-csharp-snippets.md'.`````
 - **Line 67, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/delete-task-javascript-snippets.md'.`````
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/delete-task-objc-snippets.md'.`````

<a id="0fa6f385-2f21eb37"></a>
### [api-reference/beta/api/tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-delete.md)
 - **Line 63, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/delete-tasklist-csharp-snippets.md'.`````
 - **Line 67, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/delete-tasklist-javascript-snippets.md'.`````
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/delete-tasklist-objc-snippets.md'.`````

<a id="f8d5e4a4-2f21eb37"></a>
### [api-reference/beta/api/tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-get.md)
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-tasklist-csharp-snippets.md'.`````
 - **Line 70, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-tasklist-javascript-snippets.md'.`````
 - **Line 74, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-tasklist-objc-snippets.md'.`````

<a id="3adc358f-2f21eb37"></a>
### [api-reference/beta/api/tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/ad [...]

2020-09-29 07:34 UTC, opbld32 commented
Docs Build status updates of commit _[0f22d8b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f22d8b59b729aa30eeb61408b40ebaf53cabc00)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todoapp-list-lists.md) | :x:Error | | [Details](#user-content-d928a91c-cac7a38a)
[api-reference/beta/api/todoapp-post-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todoapp-post-lists.md) | :x:Error | | [Details](#user-content-a4bc47e0-cac7a38a)
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/linkedresource.md) | :warning:Warning | | [Details](#user-content-7e051031-cac7a38a)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-cac7a38a)
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | | [Details](#user-content-a1580d42-cac7a38a)
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :warning:Warning | | [Details](#user-content-6851a216-cac7a38a)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :warning:Warning | | [Details](#user-content-58f4f899-cac7a38a)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :warning:Warning | | [Details](#user-content-f9c13677-cac7a38a)
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | | [Details](#user-content-beb03a48-cac7a38a)
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/user.md) | :warning:Warning | | [Details](#user-content-8fa18829-cac7a38a)
[api-reference/beta/api/task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-get.md) | :bulb:Suggestion | | [Details](#user-content-214ba32e-cac7a38a)
[api-reference/beta/api/task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-update.md) | :bulb:Suggestion | | [Details](#user-content-2766c006-cac7a38a)
[api-reference/beta/api/tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-list-tasks.md) | :bulb:Suggestion | | [Details](#user-content-78b63abd-cac7a38a)

<a id="d928a91c-cac7a38a"></a>
### [api-reference/beta/api/todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todoapp-list-lists.md)
 - **Line 64, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-tasklist-csharp-snippets.md'.`````
 - **Line 68, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-tasklist-javascript-snippets.md'.`````
 - **Line 72, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-tasklist-objc-snippets.md'.`````

<a id="a4bc47e0-cac7a38a"></a>
### [api-reference/beta/api/todoapp-post-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todoapp-post-lists.md)
 - **Line 74, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/create-tasklist-from-lists-javascript-snippets.md'.`````
 - **Line 78, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/create-tasklist-from-lists-csharp-snippets.md'.`````
 - **Line 82, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/create-tasklist-from-lists-objc-snippets.md'.`````

<a id="7e051031-cac7a38a"></a>
### [api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/linkedresource.md)
 - **Line 16, Column 58**: **[Warning-file-not-found]** `````Invalid file link: './todotask.md'.`````
 - **Line 21, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/todotask-list-linkedresources.md'.`````
 - **Line 22, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/todotask-post-linkedresources.md'.`````

<a id="00685cff-cac7a38a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/toc.yml)
 - **Line 12439, Column 15**: **[Warning-file-not-found]** `````Invalid file link: 'resources/todotasklist.md'.`````
 - **Line 12442, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/todo-list-lists.md'.`````
 - **Line 12444, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/todo-post-lists.md'.`````
 - **Line 12446, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/todotasklist-get.md'.`````
 - **Line 12448, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/todotasklist-update.md'.`````
 - **Line 12450, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/todotasklist-delete.md'.`````
 - **Line 12452, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/todotasklist-delta.md'.`````
 - **Line 12458, Column 15**: **[Warning-file-not-found]** `````Invalid file link: 'resources/todotask.md'.`````
 - **Line 12461, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/todotasklist-list-tasks.md'.`````
 - **Line 12463, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/todotasklist-post-tasks.md'.`````
 - **Line 12465, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/todotask-get.md'.`````
 - **Line 12467, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/todotask-update.md'.`````
 - **Line 12469, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/todotask-del [...]

2020-09-29 07:44 UTC, opbld30 commented
Docs Build status updates of commit _[28cd7c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/28cd7c8430c8f3ff74d3fdaa8661b201e00c14c0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-f9c13677-f153d63f)
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-a1580d42-f153d63f)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-58f4f899-f153d63f)
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-6851a216-f153d63f)
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-beb03a48-f153d63f)
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-8fa18829-f153d63f)
[api-reference/beta/api/task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-214ba32e-f153d63f)
[api-reference/beta/api/task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2766c006-f153d63f)
[api-reference/beta/api/tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-78b63abd-f153d63f)
[api-reference/beta/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/ [...]

2020-09-29 09:28 UTC, opbld30 commented
Docs Build status updates of commit _[37c310d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37c310d9e61b4744f23a738d119ca07c23d44381)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-f9c13677-04470d38)
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-a1580d42-04470d38)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-58f4f899-04470d38)
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-6851a216-04470d38)
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-beb03a48-04470d38)
[api-reference/beta/api/task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-214ba32e-04470d38)
[api-reference/beta/api/task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2766c006-04470d38)
[api-reference/beta/api/tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-78b63abd-04470d38)
[api-reference/beta/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todoapp-l [...]

2020-09-29 10:29 UTC, opbld32 commented
Docs Build status updates of commit _[3fee4c3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fee4c32e85846fa6104ccedee3a91b94724b548)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-f9c13677-90c301ae)
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-a1580d42-90c301ae)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-58f4f899-90c301ae)
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-6851a216-90c301ae)
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-todoapp-list-lists.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-todoapp-list-lists?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-0248c649-90c301ae)
[api-reference/beta/api/todo-todoapp-post-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-todoapp-post-lists.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-todoapp-post-lists?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-f62024d0-90c301ae)
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-beb03a48-90c301ae)
[api-reference/beta/resources/todo-linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/todo-linkedresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todo-linkedresource?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-64c5106b-90c301ae)
[api-reference/beta/resources/todo-todoApp.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/todo-todoApp.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todo-todoapp?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-1714680a-90c301ae)
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-8fa18829-90c301ae)
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-90c301ae)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-90c301ae)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-90c301ae)
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/t [...]

2020-09-29 10:35 UTC, opbld30 commented
Docs Build status updates of commit _[16772b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16772b165dc9675364848a666794b5fc4682e52b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-f9c13677-a17b9347)
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-a1580d42-a17b9347)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-58f4f899-a17b9347)
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-6851a216-a17b9347)
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-todoapp-list-lists.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-todoapp-list-lists?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-0248c649-a17b9347)
[api-reference/beta/api/todo-todoapp-post-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-todoapp-post-lists.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-todoapp-post-lists?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-f62024d0-a17b9347)
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-beb03a48-a17b9347)
[api-reference/beta/resources/todo-linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/todo-linkedresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todo-linkedresource?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-64c5106b-a17b9347)
[api-reference/beta/resources/todo-todoApp.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/todo-todoApp.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todo-todoapp?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-1714680a-a17b9347)
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-8fa18829-a17b9347)
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-a17b9347)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-a17b9347)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-a17b9347)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-a17b9347)
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded |  [...]

2020-09-29 10:49 UTC, opbld31 commented
Docs Build status updates of commit _[633d524](https://github.com/microsoftgraph/microsoft-graph-docs/commits/633d52403c89898d0a86c28f09ca475dbf8e10f4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-f9c13677-228a76a6)
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-a1580d42-228a76a6)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-58f4f899-228a76a6)
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-6851a216-228a76a6)
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-beb03a48-228a76a6)
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-228a76a6)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-228a76a6)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-228a76a6)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-228a76a6)
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph- [...]

2020-09-30 05:16 UTC, opbld31 commented
Docs Build status updates of commit _[0aece31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0aece317275a75fc68eefe471aec03f6c1980750)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-f9c13677-868163c6)
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-a1580d42-868163c6)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-58f4f899-868163c6)
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-6851a216-868163c6)
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-beb03a48-868163c6)
[api-reference/beta/resources/linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/linkedresource.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/linkedresource?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-7e051031-868163c6)
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-868163c6)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-868163c6)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-868163c6)
[api-reference/beta/resources/todo-linkedresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/todo-linkedresource.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todo-linkedresource?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-64c5106b-868163c6)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-868163c6)
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en- [...]

2020-09-30 08:11 UTC, divyangana approved these changes

2020-09-30 08:15 UTC, opbld31 commented
Docs Build status updates of commit _[8c94732](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c94732eca48f4d48354d0cf7ccaad48884b18d1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-f9c13677-b6e85c6b)
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-a1580d42-b6e85c6b)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-58f4f899-b6e85c6b)
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-6851a216-b6e85c6b)
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-42f07d86-b6e85c6b)
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-beb03a48-b6e85c6b)
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-b6e85c6b)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-b6e85c6b)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-b6e85c6b)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-b6e85c6b)
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-bet [...]

2020-09-30 11:06 UTC, opbld32 commented
Docs Build status updates of commit _[f4c894e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4c894e05df1a57f44a5821595554674a51ce70f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-f9c13677-82800375)
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-a1580d42-82800375)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-58f4f899-82800375)
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-6851a216-82800375)
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-beb03a48-82800375)
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-82800375)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-82800375)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-82800375)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-82800375)
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph- [...]

2020-10-01 16:34 UTC, opbld33 commented
Docs Build status updates of commit _[bc5b2bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc5b2bcdd22f747d660396aaa156cb1ba398aa54)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-f9c13677-0a30dbe0)
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-a1580d42-0a30dbe0)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-58f4f899-0a30dbe0)
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-6851a216-0a30dbe0)
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-beb03a48-0a30dbe0)
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-0a30dbe0)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-0a30dbe0)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-0a30dbe0)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-0a30dbe0)
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph- [...]

2020-10-02 03:05 UTC, Lauragra commented on api-reference/beta/api/todo-task-delete.md
> +Deletes a [task](../resources/todo-task.md) object.
Change Deletes to Delete.

2020-10-02 03:06 UTC, Lauragra commented on api-reference/beta/api/todo-task-delta.md
>  Namespace: microsoft.graph
Update the namespace line here.

2020-10-02 03:10 UTC, Lauragra commented on api-reference/beta/resources/todo-linkedresource.md
> +|[List linkedResources](../api/todo-task-list-linkedresources.md)|[linkedResource](../resources/todo-linkedresource.md) collection|Get the linkedResources from the linkedResources navigation property
Global: The Type and Return type columns should use the fully qualified name for the types that are in the subnamespace.

2020-10-05 12:23 UTC, opbld33 commented
Docs Build status updates of commit _[fff888f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fff888f56e913855396c9570e941d3aa26d61c1e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-34f1bea2)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-34f1bea2)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-34f1bea2)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-34f1bea2)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-05 12:23 UTC, bgaonkar commented on api-reference/beta/resources/todo-linkedresource.md
> +|[List linkedResources](../api/todo-task-list-linkedresources.md)|[linkedResource](../resources/todo-linkedresource.md) collection|Get the linkedResources from the linkedResources navigation property
Should we use [todo linkedResource] instead of [linkedResource] and similarly change type for other resources?

2020-10-07 16:03 UTC, opbld32 commented
Docs Build status updates of commit _[41c24cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41c24cff1d99201d76f8b567d584fe2ae7a8fe95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-808ace7d)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-808ace7d)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-808ace7d)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-808ace7d)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 16:06 UTC, opbld31 commented
Docs Build status updates of commit _[212e579](https://github.com/microsoftgraph/microsoft-graph-docs/commits/212e579b28381e6c2bf51a73f063a61ecc702a9f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-f6522cb5)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-f6522cb5)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-f6522cb5)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-f6522cb5)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 22:10 UTC, opbld30 commented
Docs Build status updates of commit _[dc6cbf2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dc6cbf204096ec9e130754504773005412c2bf4f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-7a4700c2)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-7a4700c2)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-7a4700c2)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-7a4700c2)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 22:14 UTC, opbld33 commented
Docs Build status updates of commit _[57dd8d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57dd8d0cf84586c5e55a554575d772636f933810)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-da4518fd)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-da4518fd)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-da4518fd)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-da4518fd)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 22:16 UTC, opbld33 commented
Docs Build status updates of commit _[a0f1f12](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0f1f12e6be49208f424969e37a181c82b557155)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-f055d2d2)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-f055d2d2)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-f055d2d2)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-f055d2d2)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 22:17 UTC, opbld31 commented
Docs Build status updates of commit _[dee4e77](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dee4e77e7a15aa51d59be5f292abf15a51624611)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-efbf7c54)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-efbf7c54)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-efbf7c54)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-efbf7c54)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 22:18 UTC, opbld30 commented
Docs Build status updates of commit _[bbebe8c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bbebe8cad3cffe9c5079cb3c468b91b0f9e12937)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-d501af09)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-d501af09)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-d501af09)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-d501af09)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 22:22 UTC, opbld33 commented
Docs Build status updates of commit _[825600b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/825600b53f1994c77b94be2fa87f0b0ad5a6c2fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-cd409584)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-cd409584)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-cd409584)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-cd409584)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 22:27 UTC, opbld33 commented
Docs Build status updates of commit _[6a4dd21](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a4dd212040b4d6fabe8fa1c2d6e3f9481a84ec7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-1f54f1fe)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-1f54f1fe)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-1f54f1fe)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-1f54f1fe)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 22:29 UTC, opbld32 commented
Docs Build status updates of commit _[dc63d93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dc63d93ad76d23d2ce23d35a8332d087dd1f9ca9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-2a15df27)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-2a15df27)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-2a15df27)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-2a15df27)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 22:34 UTC, opbld33 commented
Docs Build status updates of commit _[c0f4963](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0f496364564f8a2bcf069fc0a9c4f1b6e1ecbaf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-19cdf635)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-19cdf635)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-19cdf635)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-19cdf635)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 22:36 UTC, opbld34 commented
Docs Build status updates of commit _[3e53aa6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e53aa617a0e3606ce8ed7446d36fd50edfe88e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-2ab27da6)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-2ab27da6)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-2ab27da6)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-2ab27da6)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 22:39 UTC, opbld33 commented
Docs Build status updates of commit _[3db5aab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3db5aab1deae979a7ae733a5fc01b3ee54144d0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-66d6ea25)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-66d6ea25)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-66d6ea25)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-66d6ea25)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 22:41 UTC, opbld30 commented
Docs Build status updates of commit _[dcc8957](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dcc8957423337f0a7d0d57638d25e4ea0339e05c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-eee3488c)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-eee3488c)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-eee3488c)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-eee3488c)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 22:43 UTC, opbld30 commented
Docs Build status updates of commit _[50c967c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50c967cf1e213013acfafdbd0b31b7c1d963d2ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-0150a0b7)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-0150a0b7)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-0150a0b7)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-0150a0b7)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 23:05 UTC, Lauragra commented on api-reference/beta/api/todo-todoapp-list-lists.md
> +description: "Get a list of the taskList objects and their properties."
Global for file names that include "todoapp": What does that refer to, and is it something that should be getting renamed?

2020-10-07 23:21 UTC, opbld34 commented
Docs Build status updates of commit _[d50f5c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d50f5c72de882b1d7e43eb41b86d63ed1ab72cc0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-8b66f981)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-8b66f981)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-8b66f981)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-8b66f981)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 23:22 UTC, opbld30 commented
Docs Build status updates of commit _[2eed6d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2eed6d974b53574aba5eb2d0a3372e35db00f3a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-251d7b8a)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-251d7b8a)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-251d7b8a)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-251d7b8a)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 23:24 UTC, opbld32 commented
Docs Build status updates of commit _[0349b5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0349b5cf90ae26627ea16ed0bb58a017c2e00b5f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-d3b229fd)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-d3b229fd)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-d3b229fd)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-d3b229fd)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 23:25 UTC, opbld34 commented
Docs Build status updates of commit _[ef128d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ef128d024da07421e2b7c81e1a291de967c0a24f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-9e606382)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-9e606382)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-9e606382)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-9e606382)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 23:27 UTC, opbld31 commented
Docs Build status updates of commit _[97ffbec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97ffbecc2198dd3588da114cdad3115f22fdc1fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/todo-task-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-2fe276a9-fb5d4192)
[api-reference/beta/api/todo-task-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-41090a49-fb5d4192)
[api-reference/beta/api/todo-tasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-list-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) | [Details](#user-content-87a3bdf5-fb5d4192)
[concepts/todo-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/concepts/todo-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/todo-concept-overview?branch=pr-en-us-10075) | [Details](#user-content-714f15c3-fb5d4192)
[api-reference/beta/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-linkedresource-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-task-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-task-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-task-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delete?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-delta?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-get?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-post-tasks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-post-tasks?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-tasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api-reference/beta/api/todo-tasklist-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-tasklist-update?view=graph-rest-beta&branch=pr-en-us-10075) (graph-rest-beta) |
[api-reference/beta/api/todo-todoapp-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/add_subnamespace_todo/api- [...]

2020-10-07 23:28 UTC, Lauragra commented on api-reference/beta/resources/todo-todoApp.md
>  # todo resource type
Should this file name be todo-todo?

2020-10-07 23:32 UTC, Lauragra commented on api-reference/beta/resources/user.md
> +|[List lists](../api/todo-todoapp-list-lists.md) | [taskList](todo-tasklist.md) collection | Get all the task lists in the user's mailbox. |
The type names should be fully qualified here as well.

2020-10-07 23:34 UTC, Lauragra requested changes
Please incorporate editorial comments. Also, you'll need to resolve the merge conflicts and include entries in the changelog.md and JSON files.

2020-10-08 05:00 UTC, bgaonkar commented on api-reference/beta/resources/todo-todoApp.md
>  # todo resource type
Yes as per the documentation all the resources related to this subnamespace start with todo-. The resource is todoApp, but it doesn't have any methods or API on it.

2020-10-08 15:56 UTC, Lauragra commented on api-reference/beta/resources/todo-todoApp.md
>  # todo resource type
Please clarify. The file name is todo-todoApp, but the title is "todo resource type". So is the name of the resource "todo", or "todoApp"? If the latter, the file name will need a lowercase a as we use all lowercase (not camel case) for file names.

Also, the resource topic currently lists methods. If this is an entity type, it should be exposed in the TOC; otherwise, please correct the errors.

2021-05-05 19:01 UTC, closed without merging