Conversationmember get
microsoftgraph/microsoft-graph-docs pull request #10086
Opened 2020-09-29 05:46 UTC by Mahesh2516

Creating a new pull request.

2020-09-29 05:47 UTC, opbld34 commented
Docs Build status updates of commit _[fa63889](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa638890e9720b12e14d8b16ac7f46de40c28079)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-get/api-reference/v1.0/api/conversationmember-get.md) | :x:Error | | [Details](#user-content-dbc813dc-23e6cc3c)

<a id="dbc813dc-23e6cc3c"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-get/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-conversation-member-csharp-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-conversation-member-javascript-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-conversation-member-objc-snippets.md'.`````
 - **Line 14, Column 76**: **[Warning-file-not-found]** `````Invalid file link: '../resources/chat.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009290546280839-10086%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kLQkmjvUh47u%2FEHFz469IjOIQ4T045WD2osber7%2B5a8%3D&st=2020-09-29T05%3A42%3A35Z&se=2020-10-30T05%3A47%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 05:54 UTC, opbld34 commented
Docs Build status updates of commit _[535b6c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/535b6c11dbce56f26b1344ff2d14eb3b4c39c6cc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-get/api-reference/v1.0/api/conversationmember-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10086) (>= graph-rest-1.0) | [Details](#user-content-dbc813dc-b89794f0)

<a id="dbc813dc-b89794f0"></a>
### [api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-get/api-reference/v1.0/api/conversationmember-get.md)
 - **Line 14, Column 76**: **[Warning-file-not-found]** `````Invalid file link: '../resources/chat.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009290552579511-10086%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2T7%2BkzKIEm%2BBRctesmdabYkhBbOhnCj8b4ZAix1T3n0%3D&st=2020-09-29T05%3A49%3A18Z&se=2020-10-30T05%3A54%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-30 00:20 UTC, Lauragra commented on api-reference/v1.0/api/conversationmember-get.md
> +# [HTTP](#tab/http)
Remove this H1 and the snippets links; those are the snippets for the beta content. When this PR his merged, the weeky automation pass will create the v1.0 snippets and add the snippet links in the topic.

2020-09-30 00:21 UTC, Lauragra requested changes
This PR will require an update to the v1.0 TOC file and the changelog to list the new operation.

2020-10-02 19:15 UTC, closed without merging

2020-10-02 19:21 UTC, laujan commented
Already in #9810 PR.