File change
microsoftgraph/microsoft-graph-docs pull request #10089
Opened 2020-09-29 07:59 UTC by Bhupesh12Hub

@angelgolfer-ms 

Could you please review and approve the PR

2020-09-29 08:01 UTC, opbld31 commented
Docs Build status updates of commit _[67cdbd7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67cdbd74f9b952d0226cebca512cc79ebc9afd84)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/responsestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/ResponseStatus/v1/api-reference/v1.0/resources/responsestatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/responsestatus?view=graph-rest-1.0&branch=pr-en-us-10089) (>= graph-rest-1.0) | [Details](#user-content-6b608bb1-aba05866)

<a id="6b608bb1-aba05866"></a>
### [api-reference/v1.0/resources/responsestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/ResponseStatus/v1/api-reference/v1.0/resources/responsestatus.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=master)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=master)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009290759558982-10089%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=coddwyuarrkvCcejIM2Io4bt93gu0i1Hs5vsGw4uDOg%3D&st=2020-09-29T07%3A56%3A50Z&se=2020-10-30T08%3A01%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 10:05 UTC, opbld33 commented
Docs Build status updates of commit _[07b49b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/07b49b4e7b39debc0bd83c9c01c80a265e74f707)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/responsestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/ResponseStatus/v1/api-reference/v1.0/resources/responsestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/responsestatus?view=graph-rest-1.0&branch=pr-en-us-10089) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009291004181279-10089%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=83VUsae2BZMm5ncQ6S%2Bzg26PHngUusMFeSkelDqbWjM%3D&st=2020-09-29T10%3A00%3A34Z&se=2020-10-30T10%3A05%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-02 16:24 UTC, opbld33 commented
Docs Build status updates of commit _[b29a8f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b29a8f5c97931a913370036e24f7bdb64eb3fea8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/responsestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/ResponseStatus/v1/api-reference/v1.0/resources/responsestatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/responsestatus?view=graph-rest-1.0&branch=pr-en-us-10089) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012021623166415-10089%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1wxzTNqhaF%2BCGyjXIxSDILtACRLumGki%2FSDGMehmXZM%3D&st=2020-12-02T16%3A19%3A37Z&se=2021-01-02T16%3A24%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-20 04:51 UTC, Harini84 commented
@Bhupesh12Hub 
Can you rename the title and summary to be specific to the change?

2021-01-26 01:46 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/responsestatus.md
> +| response | responseType   | The response type. Possible values are: `None`, `Organizer`, `TentativelyAccepted`, `Accepted`, `Declined`, `NotResponded`.<br> The value "none" is returned to identify
@Bhupesh12Hub , in line 20, please keep "The", as in "The possible values are..."
I think the boilerplate text that was generated before ("Possible values are...") was always incorrect, it's only in recent months that we made an effort to fix it. Grammatically, there should be the article "the" before "possible values".

2021-01-26 01:51 UTC, angelgolfer-ms requested changes
@Bhupesh12Hub , just one comment about grammar.
I assume @Harini84 also reviewed this change for correctness?
Please fix that grammar issue, consider my review complete for the v1 topic.

What about the responsestatus.md topic in beta? I'd imagine this update is applicable there too?

2021-05-05 19:01 UTC, closed without merging