Conversationmember add
microsoftgraph/microsoft-graph-docs pull request #10085
Opened 2020-09-29 05:42 UTC by Mahesh2516

Creating a pull request.

2020-09-29 05:44 UTC, opbld31 commented
Docs Build status updates of commit _[8d9705d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d9705d77551c4b03c1f68aa46eff2f65df37876)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-add/api-reference/v1.0/api/conversationmember-add.md) | :x:Error | | [Details](#user-content-6f6649a6-0773d5c9)

<a id="6f6649a6-0773d5c9"></a>
### [api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-add/api-reference/v1.0/api/conversationmember-add.md)
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/create-conversation-member-csharp-snippets.md'.`````
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/create-conversation-member-javascript-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/create-conversation-member-objc-snippets.md'.`````
 - **Line 18, Column 54**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````
 - **Line 18, Column 165**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009290543002686-10085%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kcx%2B6w7ne53vxSaQ9R6M1bSv08J%2F6%2FZYCFoeruMkAdw%3D&st=2020-09-29T05%3A39%3A04Z&se=2020-10-30T05%3A44%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 05:52 UTC, opbld33 commented
Docs Build status updates of commit _[310958d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/310958d5aca7be41f61c69f042f929dd83baddfb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-add/api-reference/v1.0/api/conversationmember-add.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-10085) (>= graph-rest-1.0) | [Details](#user-content-6f6649a6-67a79775)

<a id="6f6649a6-67a79775"></a>
### [api-reference/v1.0/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/conversationmember-add/api-reference/v1.0/api/conversationmember-add.md)
 - **Line 18, Column 54**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````
 - **Line 18, Column 165**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009290551229909-10085%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FN0OyE9ls1zK%2BkfqdNS378n%2FBYWRPSbChc9q%2FZQZCdI%3D&st=2020-09-29T05%3A47%3A42Z&se=2020-10-30T05%3A52%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-30 00:22 UTC, Lauragra commented on api-reference/v1.0/api/conversationmember-add.md
> +# [HTTP](#tab/http)
Remove the H1s and the snippet links - these will be added via automation.

2020-09-30 00:23 UTC, Lauragra requested changes
This PR will require an update to the v1.0 TOC file and an entry in the changelog. If this and the get operation PR are related, for the future, please add the files to a singe branch and create one PR, for more efficient processing.

2020-10-02 19:20 UTC, laujan commented
Already in #9810 PR.

2020-10-02 19:20 UTC, closed without merging