update import messages API
microsoftgraph/microsoft-graph-docs pull request #10097
Opened 2020-09-29 18:51 UTC by laujan

2020-09-29 18:51 UTC, opbld33 commented
Docs Build status updates of commit _[f1a13d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f1a13d51ba542435c10edceff86a6a9db827011a)_: 

:clock10: **Pending**: waiting for processors ([10](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-29 18:52 UTC, opbld30 commented
Docs Build status updates of commit _[f1a13d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f1a13d51ba542435c10edceff86a6a9db827011a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-77faef2a)

<a id="77faef2a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202009291851318084-10097%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=L5TjK7eCAKblVURBmIWEdGJoVtcvhs%2FIj4IzAZzhCYI%3D&st=2020-09-29T18%3A47%3A03Z&se=2020-10-30T18%3A52%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 18:53 UTC, opbld30 commented
Docs Build status updates of commit _[2cf77c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2cf77c7255693446a55ea2a2e2faa9a6627ebdf9)_: 

:clock10: **Pending**: waiting for processors ([13](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-29 18:54 UTC, opbld32 commented
Docs Build status updates of commit _[2cf77c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2cf77c7255693446a55ea2a2e2faa9a6627ebdf9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-7b257724-29cbfda4)
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-d15658ef-29cbfda4)
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-f9f68dc6-29cbfda4)
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-a83fbdf9-29cbfda4)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-29cbfda4)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-29cbfda4)

<a id="7b257724-29cbfda4"></a>
### [api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md)
 - **Line 5, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'lajanuar' is not a valid GitHub ID.`````

<a id="d15658ef-29cbfda4"></a>
### [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'lajanuar' is not a valid GitHub ID.`````

<a id="f9f68dc6-29cbfda4"></a>
### [api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'lajanuar' is not a valid GitHub ID.`````

<a id="a83fbdf9-29cbfda4"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'lajanuar' is not a valid GitHub ID.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-29cbfda4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-vi [...]

2020-09-29 18:57 UTC, opbld33 commented
Docs Build status updates of commit _[5b9a77b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b9a77b67c1116f5872836cee90c0ab48bf48306)_: 

:clock10: **Pending**: waiting for processors ([11](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-29 18:59 UTC, opbld32 commented
Docs Build status updates of commit _[5b9a77b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b9a77b67c1116f5872836cee90c0ab48bf48306)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-a83fbdf9-d81ad275)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-d81ad275)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-d81ad275)
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="a83fbdf9-d81ad275"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md)
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-d81ad275"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestio [...]

2020-09-29 19:01 UTC, opbld32 commented
Docs Build status updates of commit _[a579ebb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a579ebbfb276e683e044640dd19e9b10169875a3)_: 

:clock10: **Pending**: waiting for processors ([15](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-29 19:02 UTC, opbld32 commented
Docs Build status updates of commit _[a579ebb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a579ebbfb276e683e044640dd19e9b10169875a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-c55ed23d)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-c55ed23d)
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-c55ed23d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/a [...]

2020-10-05 20:40 UTC, animeshkundu commented on api-reference/beta/api/channel-post.md
>  ---
Need to add that examples for creating a channel for import.

2020-10-05 20:41 UTC, animeshkundu commented on api-reference/beta/api/team-post.md
>  doc_type: apiPageType
Need to add example for creating teams for Import

2020-10-05 20:46 UTC, animeshkundu commented
The /message and /message('')/replies api docs also need to be updated - api schema changes (optional properties) and examples of importing messages and replies. 

If this is already done, please ignore

2020-10-06 20:03 UTC, opbld30 commented
Docs Build status updates of commit _[8f5028b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f5028bdc19ad9b48bf71d66df14d8c91c8d1782)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-343787bb)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-343787bb)
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-343787bb"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 19, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=gr [...]

2020-10-09 22:56 UTC, opbld33 commented
Docs Build status updates of commit _[6fcff30](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6fcff301bec59c23033469f16eac46922d7af4db)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a2e41f5f)

<a id="a2e41f5f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010092255311734-10097%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2mksTk0K1qPJSvAsXNMAkYWinIAZysaRwK1gw7SlfiI%3D&st=2020-10-09T22%3A51%3A32Z&se=2020-11-09T22%3A56%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-09 22:59 UTC, opbld33 commented
Docs Build status updates of commit _[f3943a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3943a37cbad3063687475a1f505d46e924af12f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-c0b40466)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-c0b40466)
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-c0b40466"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2authenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessmicrosoftauthenticatorauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 38, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 59, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 68, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 68, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 68, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 68, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstalle [...]

2020-10-13 21:40 UTC, opbld34 commented
Docs Build status updates of commit _[cbcf0c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cbcf0c4b2f6c3ccdced78a8d78e1c13458844584)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-7b257724-998cc6f2)
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-d15658ef-998cc6f2)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-998cc6f2)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-998cc6f2)
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="7b257724-998cc6f2"></a>
### [api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md)
 - **Line 396, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="d15658ef-998cc6f2"></a>
### [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md)
 - **Line 768, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-998cc6f2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 54, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 61, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 69, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? [...]

2020-10-13 21:44 UTC, opbld30 commented
Docs Build status updates of commit _[4205453](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42054537d4e5f9dd913335c0215b5ec714813f0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-7b257724-12cf63d3)
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-d15658ef-12cf63d3)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-12cf63d3)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-12cf63d3)
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="7b257724-12cf63d3"></a>
### [api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md)
 - **Line 396, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="d15658ef-12cf63d3"></a>
### [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md)
 - **Line 768, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-12cf63d3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 54, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 61, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 69, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? [...]

2020-10-13 21:47 UTC, opbld30 commented
Docs Build status updates of commit _[5d52c7e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d52c7e8775a7bbd813609165477a5311d9b97e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-7b257724-3f380413)
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-d15658ef-3f380413)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-3f380413)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-3f380413)
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="7b257724-3f380413"></a>
### [api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md)
 - **Line 396, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="d15658ef-3f380413"></a>
### [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md)
 - **Line 768, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-3f380413"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 54, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 61, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 69, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? [...]

2020-10-13 21:49 UTC, opbld32 commented
Docs Build status updates of commit _[b899bd7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b899bd753708019d06d616946fbe9c0ca833170b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-7b257724-d508998d)
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-d15658ef-d508998d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-d508998d)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-d508998d)
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="7b257724-d508998d"></a>
### [api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md)
 - **Line 396, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="d15658ef-d508998d"></a>
### [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md)
 - **Line 768, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-d508998d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 54, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 61, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 69, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? [...]

2020-10-14 20:53 UTC, opbld32 commented
Docs Build status updates of commit _[0ce499f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ce499ff525e76ad0b56a939588145d33e1a6b16)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-b7371e05)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-b7371e05)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-b7371e05"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 54, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Sugges [...]

2020-10-14 20:58 UTC, opbld30 commented
Docs Build status updates of commit _[74d04ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74d04ff0f13960cce81c79e3f76f1a8a324bd39b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-89a8e2f9)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-89a8e2f9)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-89a8e2f9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 54, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Sugges [...]

2020-10-14 21:04 UTC, opbld33 commented
Docs Build status updates of commit _[30ad927](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30ad927b8b08970ffc778a43ed1599d10a1007e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-2be130a2)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-2be130a2)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-2be130a2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 54, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Sugges [...]

2020-10-14 21:35 UTC, opbld31 commented
Docs Build status updates of commit _[66d1812](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66d18127131dfc969e05f3f97dacf89e7a1b7e84)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-47f5e7cc)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-47f5e7cc)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-47f5e7cc"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 54, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Sugges [...]

2020-10-14 21:41 UTC, opbld30 commented
Docs Build status updates of commit _[44198e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/44198e3345aae4d84c418a17a10907abfe029f6c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-c49b1a13)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-c49b1a13)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-c49b1a13"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 54, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Sugges [...]

2020-10-14 22:14 UTC, opbld32 commented
Docs Build status updates of commit _[6f51632](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f516328f75f506016ceb01741b00b71d87b6a70)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-1ce5904b-953700b7)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-953700b7)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-953700b7)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="1ce5904b-953700b7"></a>
### [api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md)
 - **Line 160, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 257, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="de0bbbbb-953700b7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
  [...]

2020-10-14 22:56 UTC, opbld32 commented
Docs Build status updates of commit _[41576fc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41576fc0f5a556d1973ea722a0dab754c591c659)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-1ce5904b-93a1dfc8)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-93a1dfc8)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-93a1dfc8)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="1ce5904b-93a1dfc8"></a>
### [api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md)
 - **Line 160, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 257, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="de0bbbbb-93a1dfc8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
  [...]

2020-10-14 23:12 UTC, opbld33 commented
Docs Build status updates of commit _[a35439a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a35439ac2234265affec96ba1671180d01e2d180)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-1ce5904b-d71e81df)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-d71e81df)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-d71e81df)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="1ce5904b-d71e81df"></a>
### [api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md)
 - **Line 160, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 260, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="de0bbbbb-d71e81df"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 21, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 22, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 23, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 24, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
  [...]

2020-10-15 20:42 UTC, opbld33 commented
Docs Build status updates of commit _[1accf62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1accf62f9cd3b07d00a7da88621bd626ce29c56f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-1ce5904b-177437bf)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-177437bf)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-177437bf)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="1ce5904b-177437bf"></a>
### [api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md)
 - **Line 160, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 260, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="de0bbbbb-177437bf"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
  [...]

2020-10-15 22:38 UTC, opbld30 commented
Docs Build status updates of commit _[cf8136e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cf8136e04b20dcaaecead8396339862942b1667f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-1ce5904b-21f9b999)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-21f9b999)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-21f9b999)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="1ce5904b-21f9b999"></a>
### [api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md)
 - **Line 160, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Duplicate tab id: (http, 2).`````
 - **Line 160, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="de0bbbbb-21f9b999"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line [...]

2020-10-15 23:04 UTC, opbld34 commented
Docs Build status updates of commit _[4feb701](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4feb701c058aefc8749622dd5dc1264bdb0bb2c9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-1ce5904b-01365361)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-01365361)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-01365361)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="1ce5904b-01365361"></a>
### [api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md)
 - **Line 160, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 259, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="de0bbbbb-01365361"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
  [...]

2020-10-20 22:07 UTC, opbld31 commented
Docs Build status updates of commit _[8d93d4a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d93d4ac58526b3068538c5c11bd0b841de8b713)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-22 19:07 UTC, opbld31 commented
Docs Build status updates of commit _[31c61fb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31c61fb1e15b12b6e4326c9637ee27d8776fcd93)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-1ce5904b-6c0a4315)
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-1a435eb8-6c0a4315)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-6c0a4315)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-6c0a4315)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="1ce5904b-6c0a4315"></a>
### [api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md)
 - **Line 160, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 259, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="1a435eb8-6c0a4315"></a>
### [api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md)
 - **Line 149, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="de0bbbbb-6c0a4315"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Li [...]

2020-10-22 19:43 UTC, opbld32 commented
Docs Build status updates of commit _[19fbbd2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19fbbd2c0aae6fbf4bd2ed5d6113c134374de908)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-1a435eb8-445133ad)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-445133ad)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-445133ad)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="1a435eb8-445133ad"></a>
### [api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md)
 - **Line 149, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="de0bbbbb-445133ad"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view [...]

2020-10-22 19:48 UTC, opbld31 commented
Docs Build status updates of commit _[e4bd862](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4bd862d149eeb4e99af660709e9abcf8d1931d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-6b0d92b3)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-6b0d92b3)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-6b0d92b3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific ve [...]

2020-10-22 19:59 UTC, opbld32 commented
Docs Build status updates of commit _[ad50a17](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad50a17d17b4c4f272dcfd090f45509e84ef9aa9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-bba695ad)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-bba695ad)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-bba695ad"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific ve [...]

2020-10-22 21:58 UTC, opbld33 commented
Docs Build status updates of commit _[3213a2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3213a2b37a5e514a7c92331b03e821aa385bc0e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-5410905c)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-5410905c)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-5410905c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific ve [...]

2020-10-26 19:50 UTC, opbld30 commented
Docs Build status updates of commit _[b9808d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9808d511331dac799169939c93818d74d3bc008)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-6a1e20c3)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-6a1e20c3)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-6a1e20c3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a sp [...]

2020-10-26 19:59 UTC, laujan commented
Hi @Lauragra. Here is a link to the spec: [API Spec](https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding?path=/reviews/4251-microsoft-teams-apis-for-migration/api.md&_a=preview&version=GBmaster).

2020-10-26 21:25 UTC, opbld32 commented
Docs Build status updates of commit _[732fe2d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/732fe2d6df63d64cbd7549642a646f089a4e0215)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-6ae94761)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-6ae94761)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-6ae94761"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a sp [...]

2020-10-26 21:26 UTC, Lauragra commented on api-reference/beta/api/channel-completemigration.md
> +|Application | Teamwork.Migrate.All|
The permissions table is missing the two Delegated perms scenarios; please add.

2020-10-26 21:27 UTC, Lauragra commented on api-reference/beta/api/channel-completemigration.md
> +POST https://graph.microsoft.com/beta/teams/teamId/completeMigration
This example request doesn't match the syntax in the HTTP request section. Also, it's helpful to use actual IDs in examples; if you leave it generic, you should have the curly brackets to indicate that it's a placeholder.

2020-10-26 21:28 UTC, opbld34 commented
Docs Build status updates of commit _[830834b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/830834bec384c7770ce0ce7981a8c9ca11c5202f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-e67a5991)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-e67a5991)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-e67a5991"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a sp [...]

2020-10-26 21:30 UTC, Lauragra commented on api-reference/beta/api/channel-completemigration.md
> +## Tips and additional information
This is a non-standard H2 section, and our goal is for all API topics to have a consistent H2 structure. I recommend integrating this content into the H2 sections; i.e. you can call this out in the summary section.

2020-10-26 21:35 UTC, Lauragra commented on api-reference/beta/api/channel-completemigration.md
> +| Content-Type  | application/json. Required.  |
The request doesn't include a Content-type header so we can remove this row from the table.

2020-10-26 21:57 UTC, opbld31 commented
Docs Build status updates of commit _[b5fd73c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5fd73ce36803ff7d52e3d99aa3f314ea43600bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-8f53e3ce)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-8f53e3ce)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-8f53e3ce"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a sp [...]

2020-10-26 22:01 UTC, opbld34 commented
Docs Build status updates of commit _[d4057ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d4057ed92826cb2358e707cf7319ff91c6325001)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-70792274)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-70792274)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-70792274"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a sp [...]

2020-10-26 22:01 UTC, Lauragra commented on api-reference/beta/api/channel-post-message.md
> +POST https://graph.microsoft.com/beta/teams/teamId/channels/channelId/messages
Same comment here regarding the placeholder IDs.

2020-10-26 22:06 UTC, Lauragra commented on api-reference/beta/api/channel-post-message.md
> +POST https://graph.microsoft.com/beta/teams/teamId/channels/channelId/messages
Same comment regarding the placeholders.

2020-10-26 22:11 UTC, Lauragra commented on api-reference/beta/api/channel-post-messagereply.md
> +### Example: Import messages
Please update the previous example to be "Example 1:" and make this Example 2.

2020-10-26 22:14 UTC, opbld30 commented
Docs Build status updates of commit _[9c3e532](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c3e532b84c83c020934e1b0b0436868b21cb287)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-aa50405e)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-aa50405e)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-aa50405e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a sp [...]

2020-10-26 22:19 UTC, Lauragra commented on api-reference/beta/api/channel-post.md
> +#### Error Message
I'm not sure what's going on here because we're showing a successful request, right? Why are we showing an error message? This might be something to include in the response section; i.e., If the request is unsuccessful, a `400 Bad Request` error message is returned.

2020-10-26 23:28 UTC, opbld30 commented
Docs Build status updates of commit _[c128a02](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c128a0231217a366fb205533509bbd0111883c2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-8519cfa3)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-8519cfa3)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-8519cfa3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a sp [...]

2020-10-26 23:58 UTC, Lauragra commented on api-reference/beta/api/channel-completemigration.md
> +description: "End the message migration mode on the channel resource."
The description doesn't match the summary text. Also, we should define "migration mode". Should the description here be something like "Complete the migration of external messages by removing migration mode from a channel."

2020-10-27 00:09 UTC, Lauragra commented on api-reference/beta/api/team-completemigration.md
> +description: "End the message migration mode on the team resource."
Same comment here about the description/summary. We should define migration mode, and possibly the description should be "Complete the migration of a team by removing migration mode."

2020-10-27 00:10 UTC, Lauragra commented on api-reference/beta/api/team-completemigration.md
> +|Application | Teamwork.Migrate.All|
Add the delegated scenarios to the Permissions table.

2020-10-27 00:10 UTC, Lauragra commented on api-reference/beta/api/team-completemigration.md
> +| Content-Type  | application/json. Required.  |
Remove this row when there's no JSON request body.

2020-10-27 00:11 UTC, Lauragra commented on api-reference/beta/api/team-completemigration.md
> +# [HTTP](#tab/http)
Remove the HTTP H1 here; it gets added via the snippets automation.

2020-10-27 00:11 UTC, Lauragra commented on api-reference/beta/api/team-completemigration.md
> +POST https://graph.microsoft.com/beta/teams/teamId/completeMigration
Add a real ID (preferably) or if a placeholder ID, include in curly brackets.

2020-10-27 00:12 UTC, Lauragra commented on api-reference/beta/api/team-completemigration.md
> +## Tips and additional information
Incorporate this content into the other sections; probably you can explain this in the summary section.

2020-10-27 00:15 UTC, opbld34 commented
Docs Build status updates of commit _[8c19f9b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c19f9bf6984480358905201f2e8eeb664ed937a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-a069ad45)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-a069ad45)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-a069ad45"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a sp [...]

2020-10-27 00:21 UTC, opbld33 commented
Docs Build status updates of commit _[fdf4d1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fdf4d1d93931b7f3b61364af4ea4fca86104fc67)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-de20123c)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-de20123c)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-de20123c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a sp [...]

2020-10-27 00:23 UTC, opbld31 commented
Docs Build status updates of commit _[45c0329](https://github.com/microsoftgraph/microsoft-graph-docs/commits/45c032958e27d57b83596f62f412ecc455b2660d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-75bf1a7d)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-75bf1a7d)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-75bf1a7d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a sp [...]

2020-10-27 00:25 UTC, opbld32 commented
Docs Build status updates of commit _[7363ac9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7363ac9b549a583fc49574767c06aa5964eb8166)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-7a92d801)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-7a92d801)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="de0bbbbb-7a92d801"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a sp [...]

2020-10-27 00:25 UTC, Lauragra commented on concepts/changelog.md
> +### Teamwork
It doesn't look like you added a changelog entry here. Also, note that we now need to include an update to the workload JSON file in addition to the MD changelog file (the MD will be going away). Details here: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55053/Changelog

2020-10-27 00:29 UTC, Lauragra requested changes
Please respond to editorial comments. It will be worthwhile to look into moving the import topic currently in the Microsoft Teams content set into the Graph content set for better discovery/clarity. Some of the feedback on this PR might apply to the examples in that topic as well. For efficiency, if you publish Graph-related Teams content as part of the Microsoft Graph content set, it will help with consistency/content reviews/etc.

2020-10-27 00:33 UTC, opbld30 commented
Docs Build status updates of commit _[b9a80a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9a80a0fa5cf0b1a7111f3cc35ebc986c4dee59e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) | [Details](#user-content-2cbd94f1-2b1b5164)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-2b1b5164)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-2b1b5164)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |

<a id="2cbd94f1-2b1b5164"></a>
### [api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 99**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="de0bbbbb-2b1b5164"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-res [...]

2020-10-27 00:51 UTC, laujan commented on concepts/changelog.md
> +### Teamwork
Hi @Lauragra, which file is the workload JSON and how do I generate the `Id`?

2020-10-27 00:59 UTC, Lauragra commented on concepts/changelog.md
> +### Teamwork
You can just use an online GUID generator I assume to generate an ID. If you use the stub generator, the change JSON snippets is generated by the tool. This is the Teams workload file: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/changelog/Microsoft.Teams.Core.json.

2020-10-27 01:32 UTC, Lauragra commented on concepts/changelog-archive.md
> +|Addition|beta|Added support for **completeMigration** to the [channel](/graph/api/resources/channel?view=graph-rest-beta) and [team](/graph/api/resources/team?view=graph-rest-beta) resources|Additio
This is the wrong topic to update - you need to update changelog.md. Just ignore this file. The Teamwork entry should appear under October.

2020-10-27 01:37 UTC, Lauragra requested changes
Looks good, we just need the update to the JSON file for the changelog and we can merge.

2020-10-27 17:12 UTC, laujan commented on concepts/changelog.md
> +### Teamwork
Thanks!

2020-10-27 17:20 UTC, opbld31 commented
Docs Build status updates of commit _[7fa0eb8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7fa0eb8ed8c5280edf9b6be2779a743fadefd917)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-caaec4e0)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-caaec4e0)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-caaec4e0"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-vi [...]

2020-10-27 18:25 UTC, opbld33 commented
Docs Build status updates of commit _[fea64d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fea64d21cb44a127aaa6ceae37557b5b285c6415)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10097) | [Details](#user-content-de0bbbbb-ccee10a3)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10097) | [Details](#user-content-075040e5-ccee10a3)
[api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/accessreview-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta&branch=pr-en-us-10097) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-ccee10a3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/la-update-import-messages/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-vi [...]

2020-10-27 18:27 UTC, Lauragra approved these changes

2020-10-27 18:29 UTC, merged

2020-10-28 00:00 UTC, AkJo commented on concepts/permissions-reference.md
> +|:----------------|:------------------|:-------------|:-----------------------|:--------------|
This and others seem to a be dupe of entries that already exist in this file. Please check @laujan

2020-10-28 00:03 UTC, AkJo commented on api-reference/beta/api/team-post.md
> +* **createdDateTime** is correctly specified but the **channelCreationMode** instance attribute is missing or set to an invalid value.
teamCreationMode

2020-10-28 00:07 UTC, AkJo commented on concepts/changelog.md
> -|Addition|beta| Added the **createdDateTime** property to the [channel](/graph/api/resources/channel?view=graph-rest-beta) and [team](/graph/api/resources/team?view=graph-rest-beta) resources.|
Why are we removing this? Both of these properties are available in beta.

2020-10-28 00:15 UTC, AkJo commented on api-reference/beta/api/channel-post-message.md
> +> **Note**: No special permission scopes are required for this scenario because the request is part of **chatMessage**; scopes for **chatMessage** apply here as well.
This line is confusing. We should remove it.

2020-10-28 00:16 UTC, AkJo commented on api-reference/beta/api/channel-completemigration.md
> +Complete the message migration process by removing `migration mode` from a [channel](../resources/channel.md) in a team. `Migration mode` is a special state that prevents certain operations, like cre
like sending messages

2020-10-28 00:16 UTC, AkJo commented on api-reference/beta/api/channel-post-message.md
> +> **Note**: No special permission scopes are required for this scenario because the request is part of **chatMessage**; scopes for **chatMessage** apply here as well.
Please remove this line.

2020-10-28 00:18 UTC, AkJo commented on api-reference/beta/api/channel-post-message.md
> +      "contentType":"html",
This example is missing the illustration of createdDateTime and from fields being a must when importing messages.

Please update the example.

2020-10-28 00:20 UTC, AkJo commented on api-reference/beta/api/channel-post-messagereply.md
> +> **Note**: No special permission scopes are required for this scenario because the request is part of **chatMessage**; scopes for **chatMessage** apply here as well.
Please remove this, or replace this by: The permission scope Teamwork.Migrate.All is required for this scenario.

2020-10-28 00:20 UTC, AkJo commented on api-reference/beta/api/channel-post-message.md
> +> **Note**: No special permission scopes are required for this scenario because the request is part of **chatMessage**; scopes for **chatMessage** apply here as well.
or replace by: The permission scope Teamwork.Migrate.All is required for this scenario

2020-10-28 00:20 UTC, AkJo commented on api-reference/beta/api/channel-post-message.md
> +> **Note**: No special permission scopes are required for this scenario because the request is part of **chatMessage**; scopes for **chatMessage** apply here as well.
or replace by: The permission scope Teamwork.Migrate.All is required for this scenario

2020-10-28 01:04 UTC, AkJo commented on api-reference/beta/api/channel-post-message.md
> +> **Note**: No special permission scopes are required for this scenario because the request is part of **chatMessage**; scopes for **chatMessage** apply here as well.
@laujan

2020-10-28 18:11 UTC, laujan commented on concepts/permissions-reference.md
> +|:----------------|:------------------|:-------------|:-----------------------|:--------------|
Yes, repeated at line 499 - 504.