Add createUploadSession action to printDocument
microsoftgraph/microsoft-graph-docs pull request #10142
Opened 2020-10-01 18:04 UTC by nilakhan

2020-10-01 18:05 UTC, opbld33 commented
Docs Build status updates of commit _[463350a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/463350af6463a1f0518e25958d361f6b11b53c30)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10142) | [Details](#user-content-de0bbbbb-4e902905)

<a id="de0bbbbb-4e902905"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md)
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 43, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemoperationtype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsipackagetype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappnotification?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptruleoperationtype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryruleoperationtype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on  [...]

2020-10-12 23:45 UTC, opbld34 commented
Docs Build status updates of commit _[08990a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08990a729e5977974d25527cc78373abc420a2ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10142) | [Details](#user-content-de0bbbbb-5b8c6a9d)

<a id="de0bbbbb-5b8c6a9d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md)
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 54, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 69, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: ** [...]

2020-10-12 23:54 UTC, opbld33 commented
Docs Build status updates of commit _[b09a5a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b09a5a8a23b8efaf07ea32f66eed6bae3f79e756)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-ef280dda-e689771d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10142) | [Details](#user-content-de0bbbbb-e689771d)

<a id="ef280dda-e689771d"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-e689771d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md)
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 54, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 69, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set [...]

2020-10-13 00:27 UTC, opbld32 commented
Docs Build status updates of commit _[edfffce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/edfffce724a727f93bca5e4624ae12fa391506f3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-ef280dda-6407e51b)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-c60d9ccc-6407e51b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10142) | [Details](#user-content-de0bbbbb-6407e51b)

<a id="ef280dda-6407e51b"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c60d9ccc-6407e51b"></a>
### [api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-6407e51b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md)
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 54, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 69, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific [...]

2020-10-13 00:41 UTC, opbld30 commented
Docs Build status updates of commit _[7d6908a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d6908a6c22b8f458a06394731bd6c8dcb4b144d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-ef280dda-362acafb)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-c60d9ccc-362acafb)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-2b050484-362acafb)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10142) | [Details](#user-content-de0bbbbb-362acafb)

<a id="ef280dda-362acafb"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c60d9ccc-362acafb"></a>
### [api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2b050484-362acafb"></a>
### [api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-362acafb"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md)
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 54, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 69, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tr [...]

2020-10-13 00:43 UTC, opbld30 commented
Docs Build status updates of commit _[78db234](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78db2347b9db02fb25286956a8e4e6bf6d235c43)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-ef280dda-bc14ce36)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-c60d9ccc-bc14ce36)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-2b050484-bc14ce36)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10142) | [Details](#user-content-de0bbbbb-bc14ce36)

<a id="ef280dda-bc14ce36"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c60d9ccc-bc14ce36"></a>
### [api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2b050484-bc14ce36"></a>
### [api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-bc14ce36"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md)
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 54, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 69, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tr [...]

2020-10-13 00:45 UTC, opbld31 commented
Docs Build status updates of commit _[b8fab8f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8fab8f6964678c5c90b3be76e5adbea4086cbe7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-ef280dda-66cacf1a)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printercapabilities?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f87f60d8-66cacf1a)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-c60d9ccc-66cacf1a)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-2b050484-66cacf1a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10142) | [Details](#user-content-de0bbbbb-66cacf1a)

<a id="ef280dda-66cacf1a"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f87f60d8-66cacf1a"></a>
### [api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c60d9ccc-66cacf1a"></a>
### [api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2b050484-66cacf1a"></a>
### [api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="de0bbbbb-66cacf1a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md)
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 32, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 54, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific ver [...]

2020-10-13 00:49 UTC, opbld31 commented
Docs Build status updates of commit _[3a80a55](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a80a55f676ae5fc13fb235c4fe2cab25eefc563)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-9f8a4db4)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-9f8a4db4)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-9f8a4db4)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-9f8a4db4)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-9f8a4db4)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-9f8a4db4)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-9f8a4db4)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-9f8a4db4)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-9f8a4db4)

<a id="f3c207b5-9f8a4db4"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ef280dda-9f8a4db4"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f87f60d8-9f8a4db4"></a>
### [api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c60d9ccc-9f8a4db4"></a>
### [api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2b050484-9f8a4db4"></a>
### [api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="00685cff-9f8a4db4"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml)
 - **Line 1650, Column 19**: **[Warning-file-not-found]** `````Invalid file link: 'api/printer-resetdefaults.md'.`````

<a id="8794bed8-9f8a4db4"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````
 - **Line 27, Column 3**: **[Warning-file-not-found]** `````Invalid file link: '../api/printer-resetdefaults.md'.`````

<a id="344b83ed-9f8a4db4"></a>
### [api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````
 - **Line 155, Column 3**: **[Warning-file-not-found]** `````Invalid file link: '../api/printer-resetdefaults.md'.`````

<a id="de0bbbbb-9f8a4db4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md)
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will  [...]

2020-10-13 00:51 UTC, opbld32 commented
Docs Build status updates of commit _[df5aae9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df5aae901a2529bf2b41440da4a2221b688d8e05)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-8da1d5b1)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-8da1d5b1)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-8da1d5b1)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-8da1d5b1)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-8da1d5b1)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-8da1d5b1)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-8da1d5b1)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-8da1d5b1)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-8da1d5b1)

<a id="f3c207b5-8da1d5b1"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ef280dda-8da1d5b1"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f87f60d8-8da1d5b1"></a>
### [api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c60d9ccc-8da1d5b1"></a>
### [api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2b050484-8da1d5b1"></a>
### [api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="00685cff-8da1d5b1"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml)
 - **Line 1650, Column 19**: **[Warning-file-not-found]** `````Invalid file link: 'api/printer-resetdefaults.md'.`````

<a id="8794bed8-8da1d5b1"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````
 - **Line 27, Column 3**: **[Warning-file-not-found]** `````Invalid file link: '../api/printer-resetdefaults.md'.`````

<a id="344b83ed-8da1d5b1"></a>
### [api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````
 - **Line 155, Column 3**: **[Warning-file-not-found]** `````Invalid file link: '../api/printer-resetdefaults.md'.`````

<a id="de0bbbbb-8da1d5b1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md)
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will  [...]

2020-10-13 00:57 UTC, opbld33 commented
Docs Build status updates of commit _[1236edc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1236edc9d26e6ecf392f524425f1966f12fbbfb0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-04cde0b8)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-04cde0b8)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-04cde0b8)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-04cde0b8)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-04cde0b8)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-04cde0b8)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-04cde0b8)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-04cde0b8)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-04cde0b8)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-04cde0b8)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-04cde0b8)

<a id="f3c207b5-04cde0b8"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="381d3ed1-04cde0b8"></a>
### [api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ef280dda-04cde0b8"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f87f60d8-04cde0b8"></a>
### [api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c60d9ccc-04cde0b8"></a>
### [api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2b050484-04cde0b8"></a>
### [api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="00685cff-04cde0b8"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml)
 - **Line 1650, Column 19**: **[Warning-file-not-found]** `````Invalid file link: 'api/printer-resetdefaults.md'.`````

<a id="344b83ed-04cde0b8"></a>
### [api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````
 - **Line 155, Column 3**: **[Warning-file-not-found]** `````Invalid file link: '../api/printer-resetdefaults.md'.`````

<a id="8794bed8-04cde0b8"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/valida [...]

2020-10-13 00:58 UTC, opbld31 commented
Docs Build status updates of commit _[b863b2c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b863b2c93739f1b66b9b02d730cfde22980a7f02)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-7755635b)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-7755635b)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-7755635b)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-7755635b)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-7755635b)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-7755635b)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-7755635b)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-7755635b)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-7755635b)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-7755635b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-7755635b)

<a id="f3c207b5-7755635b"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="381d3ed1-7755635b"></a>
### [api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ef280dda-7755635b"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f87f60d8-7755635b"></a>
### [api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c60d9ccc-7755635b"></a>
### [api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2b050484-7755635b"></a>
### [api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="00685cff-7755635b"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml)
 - **Line 1650, Column 19**: **[Warning-file-not-found]** `````Invalid file link: 'api/printer-resetdefaults.md'.`````

<a id="8794bed8-7755635b"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````
 - **Line 27, Column 3**: **[Warning-file-not-found]** `````Invalid file link: '../api/printer-resetdefaults.md'.`````

<a id="344b83ed-7755635b"></a>
### [api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validat [...]

2020-10-13 01:00 UTC, opbld32 commented
Docs Build status updates of commit _[3898607](https://github.com/microsoftgraph/microsoft-graph-docs/commits/38986070e626f623d7b1a9a93e2d80c2b5f7c804)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-7d92e5ba)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-7d92e5ba)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-7d92e5ba)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-7d92e5ba)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-7d92e5ba)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-7d92e5ba)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-7d92e5ba)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-7d92e5ba)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-7d92e5ba)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-7d92e5ba)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-7d92e5ba)

<a id="f3c207b5-7d92e5ba"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="381d3ed1-7d92e5ba"></a>
### [api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ef280dda-7d92e5ba"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="563a1b8c-7d92e5ba"></a>
### [api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f87f60d8-7d92e5ba"></a>
### [api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c60d9ccc-7d92e5ba"></a>
### [api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2b050484-7d92e5ba"></a>
### [api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="00685cff-7d92e5ba"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml)
 - **Line 1650, Column 19**: **[Warning-file-not-found]** `````Invalid file link: 'api/printer-resetdefaults.md'.`````

<a id="344b83ed-7d92e5ba"></a>
### [api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.```` [...]

2020-10-13 01:05 UTC, opbld30 commented
Docs Build status updates of commit _[3dbacb8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3dbacb85df79a60d3ab29b952a3f27436bd5e452)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-ed7b8eaf)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-ed7b8eaf)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-ed7b8eaf)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-ed7b8eaf)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-ed7b8eaf)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-ed7b8eaf)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-ed7b8eaf)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-ed7b8eaf)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-ed7b8eaf)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-ed7b8eaf)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-ed7b8eaf)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-ed7b8eaf)

<a id="f3c207b5-ed7b8eaf"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="381d3ed1-ed7b8eaf"></a>
### [api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ef280dda-ed7b8eaf"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="563a1b8c-ed7b8eaf"></a>
### [api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f87f60d8-ed7b8eaf"></a>
### [api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c60d9ccc-ed7b8eaf"></a>
### [api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="cb1163c3-ed7b8eaf"></a>
### [api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2b050484-ed7b8eaf"></a>
### [api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="00685cff-ed7b8eaf"></a>
### [api-reference/beta/toc.yml](https:// [...]

2020-10-13 04:04 UTC, opbld34 commented
Docs Build status updates of commit _[e4eab38](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4eab38b55629c122ad610e8b5cdfceccf6a9faf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-e7088136)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-e7088136)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-e7088136)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-e7088136)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-e7088136)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-e7088136)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-e7088136)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-e7088136)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-e7088136)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-e7088136)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-e7088136)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-e7088136)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-e7088136)

<a id="f3c207b5-e7088136"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5c821ddc-e7088136"></a>
### [api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printjob-cancel-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printjob-cancel-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printjob-cancel-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="381d3ed1-e7088136"></a>
### [api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ef280dda-e7088136"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="563a1b8c-e7088136"></a>
### [api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f87f60d8-e7088136"></a>
### [api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-prin [...]

2020-10-13 04:06 UTC, opbld34 commented
Docs Build status updates of commit _[f25a218](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f25a21877f84de9e7811b4fffa7badc8003dcc45)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-2434d370)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-2434d370)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-2434d370)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-2434d370)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-2434d370)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-2434d370)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-2434d370)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-2434d370)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-2434d370)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-2434d370)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-2434d370)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-2434d370)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-2434d370)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-2434d370)

<a id="f3c207b5-2434d370"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5c821ddc-2434d370"></a>
### [api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printjob-cancel-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printjob-cancel-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printjob-cancel-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-2434d370"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="381d3ed1-2434d370"></a>
### [api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ef280dda-2434d370"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="563a1b8c-2434d370"></a>
### [api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md)
 [...]

2020-10-13 04:37 UTC, opbld34 commented
Docs Build status updates of commit _[3f4788c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f4788c08bf975a63795605990f67dd2142bb822)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-18e44e1e)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-18e44e1e)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-18e44e1e)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-18e44e1e)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-18e44e1e)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-18e44e1e)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-18e44e1e)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-18e44e1e)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-18e44e1e)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-18e44e1e)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-18e44e1e)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-18e44e1e)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-18e44e1e)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-18e44e1e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-18e44e1e)

<a id="f3c207b5-18e44e1e"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5c821ddc-18e44e1e"></a>
### [api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printjob-cancel-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printjob-cancel-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printjob-cancel-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-18e44e1e"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="381d3ed1-18e44e1e"></a>
### [api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="ef280dda-18e44e1e"></a>
### [api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main) [...]

2020-10-13 05:14 UTC, opbld32 commented
Docs Build status updates of commit _[75f5be2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/75f5be227c348f5e5df44783861750abb8fa8e17)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-3d9c69db)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-3d9c69db)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-3d9c69db)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-3d9c69db)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-3d9c69db)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-3d9c69db)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-3d9c69db)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-3d9c69db)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-3d9c69db)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-3d9c69db)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-3d9c69db)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-3d9c69db)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-3d9c69db)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-3d9c69db)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-3d9c69db)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-3d9c69db)

<a id="451a6abd-3d9c69db"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-3d9c69db"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5c821ddc-3d9c69db"></a>
### [api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printjob-cancel-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printjob-cancel-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printjob-cancel-ob [...]

2020-10-13 05:22 UTC, opbld31 commented
Docs Build status updates of commit _[a580825](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a58082535a028bbfdf55c7e6b447d31530aca938)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-fda456df)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-fda456df)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-fda456df)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-fda456df)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-fda456df)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-fda456df)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-fda456df)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-fda456df)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-fda456df)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-fda456df)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-fda456df)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-fda456df)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-fda456df)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-fda456df)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-fda456df)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-fda456df)

<a id="451a6abd-fda456df"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-fda456df"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5c821ddc-fda456df"></a>
### [api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printjob-cancel-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printjob-cancel-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printjob-cancel-ob [...]

2020-10-13 17:01 UTC, opbld30 commented
Docs Build status updates of commit _[93c83fc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/93c83fc47d4567062dc6127656732ac69cc68036)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-c0470266)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-c0470266)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-c0470266)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-c0470266)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-c0470266)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-c0470266)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-c0470266)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-c0470266)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-c0470266)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-c0470266)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-c0470266)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-c0470266)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-c0470266)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-c0470266)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-c0470266)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-c0470266)

<a id="451a6abd-c0470266"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-c0470266"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5c821ddc-c0470266"></a>
### [api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printjob-cancel-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printjob-cancel-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printjob-cancel- [...]

2020-10-14 05:28 UTC, opbld31 commented
Docs Build status updates of commit _[634ecdc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/634ecdc62eaf83b3b739075fe9b1a64da1e75ecf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-4bc0efbd)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-4bc0efbd)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-4bc0efbd)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-4bc0efbd)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-4bc0efbd)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-4bc0efbd)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-4bc0efbd)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-4bc0efbd)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-4bc0efbd)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-4bc0efbd)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-4bc0efbd)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-4bc0efbd)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-4bc0efbd)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-4bc0efbd)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-4bc0efbd)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-4bc0efbd)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-4bc0efbd)

<a id="451a6abd-4bc0efbd"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-4bc0efbd"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5c821ddc-4bc0efbd"></a>
### [api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printjob-cancel-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printjob-cancel-ja [...]

2020-10-15 18:19 UTC, opbld34 commented
Docs Build status updates of commit _[1a6e4ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a6e4ee726dc87dc8321f68e5ee346d3ab7bbab2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-1b294f3b)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-1b294f3b)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-1b294f3b)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-1b294f3b)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-1b294f3b)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-1b294f3b)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-1b294f3b)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-1b294f3b)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-1b294f3b)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-1b294f3b)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-1b294f3b)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-1b294f3b)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-1b294f3b)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-1b294f3b)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-1b294f3b)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-1b294f3b)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-1b294f3b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-1b294f3b)

<a id="451a6abd-1b294f3b"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-1b294f3b"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5c821ddc-1b294f3b"></a>
### [api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printjob-can [...]

2020-10-15 18:20 UTC, opbld30 commented
Docs Build status updates of commit _[56779d7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56779d72cdc080b03441d6f6a092604723ac543a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-68068ece)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-68068ece)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-68068ece)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-68068ece)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-68068ece)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-68068ece)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-68068ece)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-68068ece)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-68068ece)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-68068ece)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-68068ece)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-68068ece)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-68068ece)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-68068ece)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-68068ece)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-68068ece)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-68068ece)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-68068ece)

<a id="451a6abd-68068ece"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-68068ece"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5c821ddc-68068ece"></a>
### [api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printjob-can [...]

2020-10-15 18:29 UTC, opbld31 commented
Docs Build status updates of commit _[92e90a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92e90a660b9583bb2e8b89d372475f8b90ff872d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-a2d7fdb0)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-a2d7fdb0)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-a2d7fdb0)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-a2d7fdb0)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-a2d7fdb0)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-a2d7fdb0)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-a2d7fdb0)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-a2d7fdb0)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-a2d7fdb0)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-a2d7fdb0)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-a2d7fdb0)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-a2d7fdb0)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-a2d7fdb0)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-a2d7fdb0)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/toc.yml) | :warning:Warning | | [Details](#user-content-b329d26c-a2d7fdb0)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-a2d7fdb0)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-a2d7fdb0)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-a2d7fdb0)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-a2d7fdb0)

<a id="451a6abd-a2d7fdb0"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-a2d7fdb0"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5c821ddc-a2d7fdb0"></a>
### [api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md)
 - **Line 58, Column 1** [...]

2020-10-16 00:06 UTC, opbld30 commented
Docs Build status updates of commit _[7305602](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7305602b5bc161fcd573fe2b4b09fe62198eed65)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-9272816f)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-9272816f)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-9272816f)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-9272816f)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-9272816f)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-9272816f)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-9272816f)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-9272816f)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-9272816f)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-9272816f)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-9272816f)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-9272816f)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-9272816f)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-9272816f)
[concepts/universal-print-job-submission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-job-submission.md) | :warning:Warning | | [Details](#user-content-a11b9d2f-9272816f)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-9272816f)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-9272816f)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-9272816f)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-9272816f)

<a id="451a6abd-9272816f"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-9272816f"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5c821ddc-9272816f"></a>
### [api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/b [...]

2020-10-16 00:17 UTC, opbld31 commented
Docs Build status updates of commit _[74131f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74131f9180c346a3b4edfb292f75f0c5e039f3ec)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-5cdc734b)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-5cdc734b)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-5cdc734b)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-5cdc734b)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-5cdc734b)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-5cdc734b)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-5cdc734b)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-5cdc734b)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-5cdc734b)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-5cdc734b)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-5cdc734b)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-5cdc734b)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-5cdc734b)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-5cdc734b)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-5cdc734b)
[concepts/universal-print-job-submission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-job-submission.md) | :warning:Warning | | [Details](#user-content-a11b9d2f-5cdc734b)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-5cdc734b)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-5cdc734b)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-5cdc734b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-5cdc734b)

<a id="451a6abd-5cdc734b"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-5cdc734b"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=mai [...]

2020-10-16 00:19 UTC, opbld30 commented
Docs Build status updates of commit _[59243c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/59243c2bfb3856aa85b2a6f3ea4bd738fe313d0d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-e0347662)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-e0347662)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-e0347662)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-e0347662)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-e0347662)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-e0347662)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-e0347662)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-e0347662)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-e0347662)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-e0347662)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-e0347662)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-e0347662)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-e0347662)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-e0347662)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/toc.yml) | :warning:Warning | | [Details](#user-content-b329d26c-e0347662)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-e0347662)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-e0347662)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-e0347662)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-e0347662)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-e0347662)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-e0347662)

<a id="451a6abd-e0347662"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-e0347662"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaul [...]

2020-10-16 00:20 UTC, opbld31 commented
Docs Build status updates of commit _[cceed90](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cceed90827f6baa1cd5c3eff29266cf556039fd2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-42c1872d)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-42c1872d)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-42c1872d)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-42c1872d)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-42c1872d)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-42c1872d)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-42c1872d)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-42c1872d)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-42c1872d)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-42c1872d)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-42c1872d)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-42c1872d)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-42c1872d)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-42c1872d)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-42c1872d)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-42c1872d)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-42c1872d)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-42c1872d)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-42c1872d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-42c1872d)

<a id="451a6abd-42c1872d"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-42c1872d"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main) [...]

2020-10-16 01:02 UTC, opbld31 commented
Docs Build status updates of commit _[d1a5989](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1a5989a2efe7cb35cd2051de60894808295d6b8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-88c28c77)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-88c28c77)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-88c28c77)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-88c28c77)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-88c28c77)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-88c28c77)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-88c28c77)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-88c28c77)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-88c28c77)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-88c28c77)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-88c28c77)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-88c28c77)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-88c28c77)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-88c28c77)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-88c28c77)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-88c28c77)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-88c28c77)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-88c28c77)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-88c28c77)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-88c28c77)

<a id="451a6abd-88c28c77"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-88c28c77"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main) [...]

2020-10-16 01:04 UTC, opbld34 commented
Docs Build status updates of commit _[b885cc8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b885cc8aad7fd71833d5782e07e2942218bf84e9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-21a679af)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-21a679af)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-21a679af)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-21a679af)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-21a679af)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-21a679af)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-21a679af)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-21a679af)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-21a679af)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-21a679af)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-21a679af)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-21a679af)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-21a679af)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-21a679af)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-21a679af)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-21a679af)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-21a679af)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-21a679af)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-21a679af)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-21a679af)

<a id="451a6abd-21a679af"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-21a679af"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main) [...]

2020-10-16 01:05 UTC, opbld31 commented
Docs Build status updates of commit _[f40b2ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f40b2ae354d4f9b0fa18f89e0d98e5b318c1de94)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-0e816abd)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-0e816abd)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-0e816abd)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-0e816abd)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-0e816abd)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-0e816abd)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-0e816abd)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-0e816abd)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-0e816abd)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-0e816abd)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-0e816abd)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-0e816abd)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-0e816abd)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-0e816abd)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-0e816abd)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-0e816abd)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-0e816abd)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-0e816abd)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-0e816abd)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-0e816abd)

<a id="451a6abd-0e816abd"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-0e816abd"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main) [...]

2020-10-16 01:17 UTC, opbld31 commented
Docs Build status updates of commit _[fd15ce7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fd15ce7399f1b9da5c8c91e92cebba726073d09d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-7e9076b1)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-7e9076b1)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-7e9076b1)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-7e9076b1)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-7e9076b1)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-7e9076b1)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-7e9076b1)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-7e9076b1)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-7e9076b1)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-7e9076b1)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-7e9076b1)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-7e9076b1)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-7e9076b1)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-7e9076b1)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-7e9076b1)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-7e9076b1)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-7e9076b1)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-7e9076b1)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-7e9076b1)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-7e9076b1)

<a id="451a6abd-7e9076b1"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-7e9076b1"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main) [...]

2020-10-16 01:22 UTC, opbld30 commented
Docs Build status updates of commit _[83efbe4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83efbe470a9d721c4e9df70662ba41bcc452e5c0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-a2409229)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-a2409229)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-a2409229)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-a2409229)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-a2409229)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-a2409229)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-a2409229)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-a2409229)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-a2409229)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-a2409229)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-a2409229)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-a2409229)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-a2409229)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-a2409229)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-a2409229)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-a2409229)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-a2409229)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-a2409229)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-a2409229)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-a2409229)

<a id="451a6abd-a2409229"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-a2409229"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printer-restorefactorydefaults-javascript-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printer-restorefactorydefaults-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main) [...]

2020-10-16 05:04 UTC, opbld33 commented
Docs Build status updates of commit _[27ba24e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27ba24e334f422653b487cc019069cf75c2894e1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-a600a2d2)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-a600a2d2)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-a600a2d2)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-a600a2d2)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-a600a2d2)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-a600a2d2)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-a600a2d2)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-a600a2d2)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-a600a2d2)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-a600a2d2)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-a600a2d2)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-a600a2d2)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-a600a2d2)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-a600a2d2)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-a600a2d2)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-a600a2d2)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-a600a2d2)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-a600a2d2)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-a600a2d2)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-a600a2d2)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-a600a2d2)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-a600a2d2)

<a id="451a6abd-a600a2d2"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-a600a2d2"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/s [...]

2020-10-16 05:05 UTC, opbld32 commented
Docs Build status updates of commit _[8722f44](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8722f44bcd4696307e86e8a28244e88695313a5c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-e49f5b37)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-e49f5b37)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-e49f5b37)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-e49f5b37)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-e49f5b37)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-e49f5b37)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-e49f5b37)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-e49f5b37)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-e49f5b37)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-e49f5b37)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-e49f5b37)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-e49f5b37)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-e49f5b37)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-e49f5b37)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-e49f5b37)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-e49f5b37)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-e49f5b37)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-e49f5b37)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-e49f5b37)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-e49f5b37)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-e49f5b37)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-e49f5b37)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-e49f5b37)

<a id="451a6abd-e49f5b37"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-e49f5b37"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/cshar [...]

2020-10-16 15:47 UTC, opbld34 commented
Docs Build status updates of commit _[4c4775d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c4775dbe4cd863f367270070874b4b6923870ce)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-da41c9d0)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-da41c9d0)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-da41c9d0)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-da41c9d0)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-da41c9d0)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-da41c9d0)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-da41c9d0)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-da41c9d0)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-da41c9d0)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-da41c9d0)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-da41c9d0)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-da41c9d0)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-da41c9d0)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-da41c9d0)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-da41c9d0)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-da41c9d0)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-da41c9d0)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-da41c9d0)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-da41c9d0)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-da41c9d0)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-da41c9d0)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-da41c9d0)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-da41c9d0)

<a id="451a6abd-da41c9d0"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-da41c9d0"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/cshar [...]

2020-10-16 15:48 UTC, opbld34 commented
Docs Build status updates of commit _[0f95ee8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f95ee8505249e720b4626e50842c4bf8e17c9f7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-5519c646)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-5519c646)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-5519c646)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-5519c646)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-5519c646)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-5519c646)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-5519c646)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-5519c646)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-5519c646)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-5519c646)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-5519c646)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-5519c646)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-5519c646)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-5519c646)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-5519c646)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-5519c646)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-5519c646)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-5519c646)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-5519c646)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-5519c646)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-00685cff-5519c646)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-5519c646)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-5519c646)

<a id="451a6abd-5519c646"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-5519c646"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/cshar [...]

2020-10-16 15:55 UTC, opbld32 commented
Docs Build status updates of commit _[e872ac9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e872ac9384220702516aaabc2ddb63c424a97f83)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-b55010ce)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-b55010ce)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-b55010ce)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-b55010ce)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-b55010ce)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-b55010ce)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-b55010ce)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-b55010ce)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-b55010ce)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-b55010ce)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-b55010ce)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-b55010ce)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-b55010ce)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-b55010ce)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-b55010ce)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-b55010ce)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-b55010ce)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-b55010ce)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-b55010ce)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-b55010ce)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-b55010ce)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-b55010ce)

<a id="451a6abd-b55010ce"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-b55010ce"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 16:59 UTC, opbld32 commented
Docs Build status updates of commit _[1865f06](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1865f069d972d7bf3b345d4406b962ae6b7bc467)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-27493bdc)

<a id="27493bdc"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010161658468172-10142%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fVo8JfM49qF1g6HLbS5%2BprqyMKItmvofYktkylaDnqQ%3D&st=2020-10-16T16%3A54%3A13Z&se=2020-11-16T16%3A59%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 17:02 UTC, opbld30 commented
Docs Build status updates of commit _[de951b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de951b0f62116ce4caa2cb07b3e730563b6c6e18)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-93a78220)

<a id="93a78220"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010161702221361-10142%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sHLJJoWUF8J5%2F8J0g5fxr6JIKvikr3bKGwKRfZdR02Y%3D&st=2020-10-16T16%3A57%3A47Z&se=2020-11-16T17%3A02%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 17:05 UTC, opbld34 commented
Docs Build status updates of commit _[7b60cb7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b60cb70d4d5bcd0169d7f724525d812ae8f8712)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c2548c7a)

<a id="c2548c7a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010161705229249-10142%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zVorDQvPqT2VdTsy6GXcrCaKkzaQ26lXqIlUT7eBg%2FA%3D&st=2020-10-16T17%3A00%3A47Z&se=2020-11-16T17%3A05%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 17:22 UTC, opbld34 commented
Docs Build status updates of commit _[6a8cac8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a8cac87c7c6de9e94b4f262e0031d64db94b903)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-ae13dfb9)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-ae13dfb9)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-ae13dfb9)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-ae13dfb9)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-ae13dfb9)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-ae13dfb9)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-ae13dfb9)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-ae13dfb9)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-ae13dfb9)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-ae13dfb9)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-ae13dfb9)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-ae13dfb9)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-ae13dfb9)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-ae13dfb9)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-ae13dfb9)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-ae13dfb9)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-ae13dfb9)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-ae13dfb9)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-ae13dfb9)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-ae13dfb9)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-ae13dfb9)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-ae13dfb9)

<a id="451a6abd-ae13dfb9"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-ae13dfb9"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 18:52 UTC, braedenp-msft requested changes

2020-10-16 18:52 UTC, braedenp-msft commented on api-reference/beta/api/printdocument-createuploadsession.md
> +As part of the response, this action returns an upload URL that you can use in subsequent sequential `PUT` queries. Request headers for each `PUT` operation let you specify the exact range of bytes t
Recommend using passive voice here "can be used"

2020-10-16 18:52 UTC, braedenp-msft commented on api-reference/beta/api/printdocument-createuploadsession.md
> +>The **uploadUrl** property returned as part of the **uploadSession** response object is an opaque URL for subsequent `PUT` queries to upload byte ranges of the file. It contains the appropriate auth
nit: recommend "change"

2020-10-16 18:52 UTC, braedenp-msft commented on api-reference/beta/api/printer-post-jobs.md
> +Rest of the fields including job and document IDs are set automatically during resource creation.
Recommend "All other fields"

2020-10-16 18:52 UTC, braedenp-msft commented on api-reference/beta/api/printer-list-jobs.md
> +# List printJobs for printer
I like the additional clarity here!

Recommend "for a printer". Same in `printer-post-jobs.md`, `printershare-list-jobs.md`.

2020-10-16 18:52 UTC, braedenp-msft commented on api-reference/beta/resources/printdocumentuploadproperties.md
> +Represents information for print document upload
Recommend something like "Describes the document that is being uploaded."

2020-10-16 18:52 UTC, braedenp-msft commented on api-reference/beta/resources/printjob.md
> +|redirectedFrom|Edm.String|Contains source job url, if the job has been redirected from another printer.|
Recommend "Contains **the**". Same for next line.

2020-10-16 18:52 UTC, braedenp-msft commented on api-reference/beta/resources/printjob.md
> +|redirectedFrom|Edm.String|Contains source job url, if the job has been redirected from another printer.|
URL is an acronym so it should be capitalized. Same for rest of file.

2020-10-16 18:52 UTC, braedenp-msft commented on api-reference/beta/resources/uploadsession.md
> +Represents information for an iterative process to upload large files to OneDrive, OneDrive for Business, or SharePoint document libraries, or to Outlook [event](event.md) and [message](message.md) i
Recommend the below for consistency:
> or to Universal Print [printDocument](printDocument.md) items

Alternatively you could also refactor this sentence into a bulleted list for better readability, like so:
> Represents information for an iterative process to upload large files to:
> * OneDrive
> * OneDrive for Business
> * SharePoint document libraries
> * Outlook [event](event.md) and [message](message.md) items as attachments
> * Universal Print [printDocument](printDocument.md) items

2020-10-16 18:52 UTC, braedenp-msft commented on concepts/upload-data-to-upload-session.md
> +# Upload data to the upload session
Recommend: "Upload data to **an** upload session"

2020-10-16 18:52 UTC, braedenp-msft commented on concepts/upload-data-to-upload-session.md
> +---
Maybe a quick overview at the top to help readers understand how this process fits into the overall printing flow? Something like:

> Printing a document using Universal Print is done by [creating a print job](/graph/api/printer-post-jobs?view=graph-rest-beta), [uploading a document](/graph/api/printdocument-createuploadsession?view=graph-rest-beta), and then [starting the print job](/graph/api/printjob-startprintjob?view=graph-rest-beta). This walkthrough covers the second step, uploading a document, which starts with creating an upload session.

2020-10-16 18:52 UTC, braedenp-msft commented on concepts/upload-data-to-upload-session.md
> +To upload the file, or a portion of the file, your app makes a PUT request to the uploadUrl value received in the [createUploadSession](/graph/api/printdocument-createuploadsession?view=graph-rest-be
Recommend "To upload **a** file, or a portion of **a** file"

2020-10-16 18:52 UTC, braedenp-msft commented on concepts/upload-data-to-upload-session.md
> +# Upload data to the upload session
This is a _great_ walkthrough, including error handling 👏

2020-10-16 18:54 UTC, braedenp-msft commented
@nilakhan Make sure to also update the `changelog.json` file according to new guidance.

2020-10-16 19:02 UTC, opbld31 commented
Docs Build status updates of commit _[012e42d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/012e42ddc2d2bb1c7e7e3cf39dd7ac3cb7648f67)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-d82c939e)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-d82c939e)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-d82c939e)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-d82c939e)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-d82c939e)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-d82c939e)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-d82c939e)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-d82c939e)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-d82c939e)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-d82c939e)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-d82c939e)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-d82c939e)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-d82c939e)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-d82c939e)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-d82c939e)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-d82c939e)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-d82c939e)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-d82c939e)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-d82c939e)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-d82c939e)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-d82c939e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-d82c939e)

<a id="451a6abd-d82c939e"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-d82c939e"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 19:03 UTC, opbld31 commented
Docs Build status updates of commit _[3d7c1b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d7c1b265d19e1bade237f4938d6cd06ddbc8a3a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-c3bd0de7)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-c3bd0de7)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-c3bd0de7)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-c3bd0de7)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-c3bd0de7)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-c3bd0de7)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-c3bd0de7)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-c3bd0de7)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-c3bd0de7)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-c3bd0de7)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-c3bd0de7)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-c3bd0de7)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-c3bd0de7)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-c3bd0de7)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-c3bd0de7)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-c3bd0de7)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-c3bd0de7)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-c3bd0de7)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-c3bd0de7)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-c3bd0de7)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-c3bd0de7)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-c3bd0de7)

<a id="451a6abd-c3bd0de7"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-c3bd0de7"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 19:04 UTC, opbld32 commented
Docs Build status updates of commit _[caafae2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/caafae2f28cdcbe2ca2088d23115157d6259f7b1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-174605c8)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-174605c8)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-174605c8)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-174605c8)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-174605c8)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-174605c8)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-174605c8)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-174605c8)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-174605c8)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-174605c8)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-174605c8)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-174605c8)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-174605c8)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-174605c8)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-174605c8)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-174605c8)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-174605c8)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-174605c8)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-174605c8)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-174605c8)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-174605c8)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-174605c8)

<a id="451a6abd-174605c8"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-174605c8"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 19:08 UTC, opbld34 commented
Docs Build status updates of commit _[b4d4144](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4d4144efc831e8493c41c9f3a462685bd52b5de)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-cae0f190)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-cae0f190)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-cae0f190)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-cae0f190)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-cae0f190)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-cae0f190)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-cae0f190)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-cae0f190)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-cae0f190)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-cae0f190)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-cae0f190)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-cae0f190)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-cae0f190)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-cae0f190)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-cae0f190)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-cae0f190)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-cae0f190)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-cae0f190)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-cae0f190)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-cae0f190)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-cae0f190)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-cae0f190)

<a id="451a6abd-cae0f190"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-cae0f190"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 19:33 UTC, opbld32 commented
Docs Build status updates of commit _[f7552cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7552cc8fe20d065db72987da9807200977042d1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-199d03d5)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-199d03d5)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-199d03d5)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-199d03d5)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-199d03d5)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-199d03d5)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-199d03d5)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-199d03d5)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-199d03d5)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-199d03d5)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-199d03d5)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-199d03d5)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-199d03d5)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-199d03d5)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-199d03d5)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-199d03d5)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-199d03d5)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-199d03d5)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-199d03d5)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-199d03d5)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-199d03d5)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-199d03d5)

<a id="451a6abd-199d03d5"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-199d03d5"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 19:35 UTC, opbld31 commented
Docs Build status updates of commit _[fdcc6c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fdcc6c79e3bce01b79f8b28e97686996988edc07)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-43d92276)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-43d92276)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-43d92276)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-43d92276)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-43d92276)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-43d92276)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-43d92276)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-43d92276)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-43d92276)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-43d92276)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-43d92276)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-43d92276)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-43d92276)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-43d92276)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-43d92276)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-43d92276)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-43d92276)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-43d92276)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-43d92276)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-43d92276)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-43d92276)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-43d92276)

<a id="451a6abd-43d92276"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-43d92276"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 19:36 UTC, opbld34 commented
Docs Build status updates of commit _[404f6c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/404f6c2784c0a39204f903593c46b82743c3152e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-44b50969)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-44b50969)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-44b50969)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-44b50969)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-44b50969)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-44b50969)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-44b50969)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-44b50969)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-44b50969)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-44b50969)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-44b50969)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-44b50969)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-44b50969)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-44b50969)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-44b50969)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-44b50969)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-44b50969)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-44b50969)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-44b50969)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-44b50969)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-44b50969)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-44b50969)

<a id="451a6abd-44b50969"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-44b50969"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 19:37 UTC, opbld34 commented
Docs Build status updates of commit _[22d19ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22d19ffd6abe5e34fec961e0e9645d6d28065f62)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-772d1131)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-772d1131)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-772d1131)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-772d1131)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-772d1131)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-772d1131)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-772d1131)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-772d1131)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-772d1131)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-772d1131)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-772d1131)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-772d1131)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-772d1131)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-772d1131)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-772d1131)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-772d1131)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-772d1131)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-772d1131)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-772d1131)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-772d1131)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-772d1131)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-772d1131)

<a id="451a6abd-772d1131"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-772d1131"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 19:41 UTC, opbld32 commented
Docs Build status updates of commit _[0005645](https://github.com/microsoftgraph/microsoft-graph-docs/commits/00056457dc1138b196ea651b81a43d6674ab9a19)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-ede13994)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-ede13994)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-ede13994)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-ede13994)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-ede13994)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-ede13994)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-ede13994)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-ede13994)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-ede13994)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-ede13994)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-ede13994)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-ede13994)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-ede13994)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-ede13994)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-ede13994)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-ede13994)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-ede13994)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-ede13994)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-ede13994)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-ede13994)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-ede13994)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-ede13994)

<a id="451a6abd-ede13994"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-ede13994"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 19:42 UTC, opbld31 commented
Docs Build status updates of commit _[1ae08bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ae08bf7f8322dcfffa7a3a420ba990930a62d3f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-87290b6b)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-87290b6b)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-87290b6b)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-87290b6b)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-87290b6b)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-87290b6b)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-87290b6b)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-87290b6b)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-87290b6b)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-87290b6b)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-87290b6b)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-87290b6b)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-87290b6b)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-87290b6b)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-87290b6b)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-87290b6b)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-87290b6b)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-87290b6b)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-87290b6b)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-87290b6b)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-87290b6b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-87290b6b)

<a id="451a6abd-87290b6b"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-87290b6b"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 20:26 UTC, opbld32 commented
Docs Build status updates of commit _[d42639d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d42639db0d4f7e394b3eb64bc19e09b0a7c03452)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-6464394d)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-6464394d)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-6464394d)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-6464394d)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-6464394d)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-6464394d)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-6464394d)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-6464394d)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-6464394d)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-6464394d)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-6464394d)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-6464394d)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-6464394d)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-6464394d)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-6464394d)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-6464394d)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-6464394d)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-6464394d)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-6464394d)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-6464394d)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-6464394d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-6464394d)

<a id="451a6abd-6464394d"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-6464394d"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 20:30 UTC, nilakhan commented on concepts/upload-data-to-upload-session.md
> +# Upload data to the upload session
Thanks!
I would attribute much to existing documentation by OneDrive :)

2020-10-16 20:31 UTC, opbld34 commented
Docs Build status updates of commit _[7f68382](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f68382dd35f7018989e33bd402978d77c85b1d1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-893445dd)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-893445dd)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-893445dd)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-893445dd)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-893445dd)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-893445dd)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-893445dd)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-893445dd)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-893445dd)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-893445dd)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-893445dd)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-893445dd)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-893445dd)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-893445dd)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-893445dd)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-893445dd)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-893445dd)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-893445dd)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-893445dd)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-893445dd)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-893445dd)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-893445dd)

<a id="451a6abd-893445dd"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-893445dd"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 20:32 UTC, opbld30 commented
Docs Build status updates of commit _[77018bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/77018bd4f22a8deae6d230416f137feb5262369f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-57d37362)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-57d37362)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-57d37362)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-57d37362)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-57d37362)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-57d37362)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-57d37362)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-57d37362)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-57d37362)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-57d37362)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-57d37362)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-57d37362)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-57d37362)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-57d37362)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-57d37362)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-57d37362)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-57d37362)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-57d37362)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-57d37362)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-57d37362)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-57d37362)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-57d37362)

<a id="451a6abd-57d37362"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-57d37362"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 20:55 UTC, opbld34 commented
Docs Build status updates of commit _[c45487a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c45487a10702c4435f1985b31ed08a6a37d12d68)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-df0440f2)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-df0440f2)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-df0440f2)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-df0440f2)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-df0440f2)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-df0440f2)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-df0440f2)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-df0440f2)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-df0440f2)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-df0440f2)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-df0440f2)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-df0440f2)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-df0440f2)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-df0440f2)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-df0440f2)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-df0440f2)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-df0440f2)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-df0440f2)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-df0440f2)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-df0440f2)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-df0440f2)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-df0440f2)

<a id="451a6abd-df0440f2"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-df0440f2"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-16 22:50 UTC, braedenp-msft approved these changes

2020-10-17 00:42 UTC, opbld33 commented
Docs Build status updates of commit _[d3e1f18](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d3e1f18f817b863d46fa4f3818b8c1f1eb4cb60c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-86965393)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-86965393)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :x:Error | | [Details](#user-content-5c821ddc-86965393)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-86965393)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-86965393)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-86965393)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-86965393)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-86965393)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-86965393)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-86965393)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-86965393)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-86965393)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-86965393)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-86965393)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-86965393)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-86965393)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-86965393)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-86965393)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-86965393)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-86965393)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-86965393)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-86965393)

<a id="451a6abd-86965393"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-86965393"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** ````` [...]

2020-10-17 02:13 UTC, opbld31 commented
Docs Build status updates of commit _[9cc257d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9cc257ddd3341bef0de417cf6038940559a80670)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :x:Error | | [Details](#user-content-451a6abd-602596bf)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :x:Error | | [Details](#user-content-f3c207b5-602596bf)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-15ab79d6-602596bf)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-704888e3-602596bf)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | | [Details](#user-content-b618ef5d-602596bf)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | | [Details](#user-content-d5ab36ae-602596bf)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :warning:Warning | | [Details](#user-content-5c821ddc-602596bf)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | | [Details](#user-content-f07dfc2b-602596bf)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | | [Details](#user-content-381d3ed1-602596bf)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-ef280dda-602596bf)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-563a1b8c-602596bf)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-7b15df6f-602596bf)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | | [Details](#user-content-8794bed8-602596bf)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-f87f60d8-602596bf)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | | [Details](#user-content-7f5e5d16-602596bf)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-c60d9ccc-602596bf)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | | [Details](#user-content-cb1163c3-602596bf)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-2b050484-602596bf)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | | [Details](#user-content-2ec827c4-602596bf)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/upload-data-to-upload-session.md) | :warning:Warning | | [Details](#user-content-3e780b05-602596bf)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-344b83ed-602596bf)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-602596bf)

<a id="451a6abd-602596bf"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 97, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printdocument-createuploadsession-csharp-snippets.md'.`````
 - **Line 101, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/printdocument-createuploadsession-javascript-snippets.md'.`````
 - **Line 105, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/printdocument-createuploadsession-objc-snippets.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f3c207b5-602596bf"></a>
### [api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md)
 - **Line 58, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/printer-restorefactorydefaults-csharp-snippets.md'.`````
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)] [...]

2020-10-17 02:15 UTC, opbld32 commented
Docs Build status updates of commit _[861d016](https://github.com/microsoftgraph/microsoft-graph-docs/commits/861d016d7d487b45e2c6579ec75d03d09ce71bf6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-451a6abd-d93fda43)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-15ab79d6-d93fda43)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-704888e3-d93fda43)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-restorefactorydefaults?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f3c207b5-d93fda43)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-b618ef5d-d93fda43)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-d5ab36ae-d93fda43)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-5c821ddc-d93fda43)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f07dfc2b-d93fda43)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobconfiguration?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-381d3ed1-d93fda43)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-ef280dda-d93fda43)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-563a1b8c-d93fda43)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocumentuploadproperties?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7b15df6f-d93fda43)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-8794bed8-d93fda43)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printercapabilities?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f87f60d8-d93fda43)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printershare?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7f5e5d16-d93fda43)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-c60d9ccc-d93fda43)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-cb1163c3-d93fda43)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-2b050484-d93fda43)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-concept-overview?branch=pr-en-us-10142) | [Details](#user-content-2ec827c4-d93fda43)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-n [...]

2020-10-17 02:18 UTC, opbld30 commented
Docs Build status updates of commit _[b35dc7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b35dc7f0d65226bb91497144c7d52fbfc319173d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-451a6abd-f003863c)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-15ab79d6-f003863c)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-704888e3-f003863c)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-restorefactorydefaults?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f3c207b5-f003863c)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-b618ef5d-f003863c)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-d5ab36ae-f003863c)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-5c821ddc-f003863c)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f07dfc2b-f003863c)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobconfiguration?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-381d3ed1-f003863c)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-ef280dda-f003863c)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-563a1b8c-f003863c)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocumentuploadproperties?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7b15df6f-f003863c)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-8794bed8-f003863c)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printercapabilities?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f87f60d8-f003863c)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printershare?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7f5e5d16-f003863c)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-c60d9ccc-f003863c)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-cb1163c3-f003863c)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-2b050484-f003863c)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-concept-overview?branch=pr-en-us-10142) | [Details](#user-content-2ec827c4-f003863c)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-n [...]

2020-10-17 02:19 UTC, opbld34 commented
Docs Build status updates of commit _[1e726d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e726d1780656d1bb70054ae5585003de76dfe60)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-451a6abd-6215dc4d)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-15ab79d6-6215dc4d)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-704888e3-6215dc4d)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-restorefactorydefaults?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f3c207b5-6215dc4d)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-b618ef5d-6215dc4d)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-d5ab36ae-6215dc4d)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-5c821ddc-6215dc4d)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f07dfc2b-6215dc4d)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobconfiguration?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-381d3ed1-6215dc4d)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-ef280dda-6215dc4d)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-563a1b8c-6215dc4d)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocumentuploadproperties?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7b15df6f-6215dc4d)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-8794bed8-6215dc4d)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printercapabilities?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f87f60d8-6215dc4d)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printershare?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7f5e5d16-6215dc4d)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-c60d9ccc-6215dc4d)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-cb1163c3-6215dc4d)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-2b050484-6215dc4d)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-concept-overview?branch=pr-en-us-10142) | [Details](#user-content-2ec827c4-6215dc4d)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-n [...]

2020-10-17 02:21 UTC, opbld31 commented
Docs Build status updates of commit _[6bdadaa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6bdadaa598fae94f67e25ca9d192f2e070af785c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-451a6abd-0b8d78d8)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-15ab79d6-0b8d78d8)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-704888e3-0b8d78d8)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-restorefactorydefaults?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f3c207b5-0b8d78d8)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-b618ef5d-0b8d78d8)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-d5ab36ae-0b8d78d8)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-5c821ddc-0b8d78d8)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f07dfc2b-0b8d78d8)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobconfiguration?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-381d3ed1-0b8d78d8)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-ef280dda-0b8d78d8)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-563a1b8c-0b8d78d8)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocumentuploadproperties?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7b15df6f-0b8d78d8)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-8794bed8-0b8d78d8)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printercapabilities?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f87f60d8-0b8d78d8)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printershare?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7f5e5d16-0b8d78d8)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-c60d9ccc-0b8d78d8)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-cb1163c3-0b8d78d8)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-2b050484-0b8d78d8)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-concept-overview?branch=pr-en-us-10142) | [Details](#user-content-2ec827c4-0b8d78d8)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-n [...]

2020-10-17 02:22 UTC, opbld33 commented
Docs Build status updates of commit _[ed90e4e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed90e4e10a92b593bec1993017639ea961145a5c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-451a6abd-51ddd31e)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-15ab79d6-51ddd31e)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-704888e3-51ddd31e)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-restorefactorydefaults?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f3c207b5-51ddd31e)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-b618ef5d-51ddd31e)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-d5ab36ae-51ddd31e)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-5c821ddc-51ddd31e)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f07dfc2b-51ddd31e)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobconfiguration?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-381d3ed1-51ddd31e)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-ef280dda-51ddd31e)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-563a1b8c-51ddd31e)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocumentuploadproperties?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7b15df6f-51ddd31e)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-8794bed8-51ddd31e)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printercapabilities?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f87f60d8-51ddd31e)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printershare?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7f5e5d16-51ddd31e)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-c60d9ccc-51ddd31e)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-cb1163c3-51ddd31e)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-2b050484-51ddd31e)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-concept-overview?branch=pr-en-us-10142) | [Details](#user-content-2ec827c4-51ddd31e)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-n [...]

2020-10-17 02:28 UTC, opbld31 commented
Docs Build status updates of commit _[feb1c79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/feb1c7945829b607d84fc8ab6348b2a42dd8505c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-451a6abd-0a076711)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-15ab79d6-0a076711)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-704888e3-0a076711)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-restorefactorydefaults?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f3c207b5-0a076711)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-b618ef5d-0a076711)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-d5ab36ae-0a076711)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-5c821ddc-0a076711)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f07dfc2b-0a076711)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobconfiguration?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-381d3ed1-0a076711)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-ef280dda-0a076711)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-563a1b8c-0a076711)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocumentuploadproperties?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7b15df6f-0a076711)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-8794bed8-0a076711)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printercapabilities?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f87f60d8-0a076711)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printershare?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7f5e5d16-0a076711)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-c60d9ccc-0a076711)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-cb1163c3-0a076711)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-2b050484-0a076711)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/concepts/universal-print-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-concept-overview?branch=pr-en-us-10142) | [Details](#user-content-2ec827c4-0a076711)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-n [...]

2020-10-17 02:31 UTC, opbld30 commented
Docs Build status updates of commit _[0974972](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09749728fc20d68148ba6820be54616dd70d0404)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-451a6abd-886efa25)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-15ab79d6-886efa25)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-704888e3-886efa25)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-restorefactorydefaults?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f3c207b5-886efa25)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-b618ef5d-886efa25)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-d5ab36ae-886efa25)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-5c821ddc-886efa25)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f07dfc2b-886efa25)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobconfiguration?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-381d3ed1-886efa25)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-ef280dda-886efa25)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-563a1b8c-886efa25)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocumentuploadproperties?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7b15df6f-886efa25)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-8794bed8-886efa25)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printercapabilities?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f87f60d8-886efa25)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerdefaults?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-344b83ed-886efa25)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printershare?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7f5e5d16-886efa25)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-c60d9ccc-886efa25)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-cb1163c3-886efa25)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-2b050484-886efa25)
[concepts/universal-print-concept-overview.md](https://github.com/microsof [...]

2020-10-17 02:34 UTC, opbld32 commented
Docs Build status updates of commit _[e8d092a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8d092adae334d579dbe5fed7e7d9d2a69a4fc43)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-451a6abd-93766fb4)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-15ab79d6-93766fb4)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-704888e3-93766fb4)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-restorefactorydefaults?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f3c207b5-93766fb4)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-b618ef5d-93766fb4)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-d5ab36ae-93766fb4)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-5c821ddc-93766fb4)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f07dfc2b-93766fb4)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobconfiguration?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-381d3ed1-93766fb4)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-ef280dda-93766fb4)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-563a1b8c-93766fb4)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocumentuploadproperties?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7b15df6f-93766fb4)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-8794bed8-93766fb4)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printercapabilities?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f87f60d8-93766fb4)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerdefaults?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-344b83ed-93766fb4)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printershare?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7f5e5d16-93766fb4)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-c60d9ccc-93766fb4)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-cb1163c3-93766fb4)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-2b050484-93766fb4)
[concepts/universal-print-concept-overview.md](https://github.com/microsof [...]

2020-10-17 02:35 UTC, opbld33 commented
Docs Build status updates of commit _[328e1b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/328e1b6e624a88422ffd7fa919a481b02696c8a6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-451a6abd-e6f6005f)
[api-reference/beta/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-15ab79d6-e6f6005f)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-704888e3-e6f6005f)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printer-restorefactorydefaults.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-restorefactorydefaults?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f3c207b5-e6f6005f)
[api-reference/beta/api/printershare-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-list-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-list-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-b618ef5d-e6f6005f)
[api-reference/beta/api/printershare-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printershare-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-post-jobs?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-d5ab36ae-e6f6005f)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-cancel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-5c821ddc-e6f6005f)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f07dfc2b-e6f6005f)
[api-reference/beta/resources/printJobConfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printJobConfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobconfiguration?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-381d3ed1-e6f6005f)
[api-reference/beta/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printconnector.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printconnector?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-ef280dda-e6f6005f)
[api-reference/beta/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocument.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-563a1b8c-e6f6005f)
[api-reference/beta/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printdocumentuploadproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printdocumentuploadproperties?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7b15df6f-e6f6005f)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-8794bed8-e6f6005f)
[api-reference/beta/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printercapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printercapabilities?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-f87f60d8-e6f6005f)
[api-reference/beta/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerdefaults.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerdefaults?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-344b83ed-e6f6005f)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printershare.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printershare?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-7f5e5d16-e6f6005f)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-c60d9ccc-e6f6005f)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-cb1163c3-e6f6005f)
[api-reference/beta/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-nilakhan-uploadsession/api-reference/beta/resources/printjobstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjobstatus?view=graph-rest-beta&branch=pr-en-us-10142) (graph-rest-beta) | [Details](#user-content-2b050484-e6f6005f)
[concepts/universal-print-concept-overview.md](https://github.com/microsof [...]

2020-10-20 01:50 UTC, Lauragra commented on api-reference/beta/api/printer-restorefactorydefaults.md
> +Restore a [printer](../resources/printer.md)'s settings to the default settings.
I revised this introduction because "factory" settings doesn't make sense in this context.

2020-10-20 01:52 UTC, Lauragra commented on api-reference/beta/api/printershare-list-jobs.md
> +# [C#](#tab/csharp)
Are these the right snippets? I think we need to delete the snippets and have the automation regenerate them.

2020-10-20 01:56 UTC, Lauragra commented on api-reference/beta/api/printershare-post-jobs.md
> +# [JavaScript](#tab/javascript)
Same question here regarding the snippets.

2020-10-20 17:55 UTC, Lauragra commented on concepts/upload-data-to-upload-session.md
> +title: "Upload documents using the Microsoft Graph Universal Print API"
H1 titles should include important keywords for search. I updated this title to clarify the intent and add the keyword.

2020-10-20 18:00 UTC, nilakhan commented on api-reference/beta/api/printer-restorefactorydefaults.md
> +Restore a [printer](../resources/printer.md)'s settings to the default settings.
"defaults" is a property on printer. 
This action does not restore all printer settings. 
It only restores printer's "defaults" property. 
Another way to describe this can be: 
"deletes printer defaults provided by admin, to restore factory defaults".

@braedenp-msft  what are your thoughts on this?

2020-10-20 18:01 UTC, nilakhan commented on api-reference/beta/api/printershare-list-jobs.md
> +# [C#](#tab/csharp)
Agreed. 
How, do we regenerate them using automation?

2020-10-20 18:02 UTC, nilakhan commented on concepts/upload-data-to-upload-session.md
> +title: "Upload documents using the Microsoft Graph Universal Print API"
ok. thanks!

2020-10-20 18:13 UTC, nilakhan commented on api-reference/beta/api/printershare-list-jobs.md
> +# [C#](#tab/csharp)
I have deleted these snippets right now

2020-10-20 18:14 UTC, nilakhan commented on api-reference/beta/api/printershare-post-jobs.md
> +# [JavaScript](#tab/javascript)
I have deleted these snippets right now

2020-10-22 03:48 UTC, Lauragra approved these changes

2020-10-22 04:24 UTC, merged