Graph Connector System Limits
microsoftgraph/microsoft-graph-docs pull request #10158
Opened 2020-10-02 22:04 UTC by rsamai

Added system limits for developers to plan their source and ingestion

2020-10-02 22:05 UTC, opbld32 commented
Docs Build status updates of commit _[70d96a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70d96a5d0e7b616962d0aa667e52a319b9814cd0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-index-manage-limits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/graphconnector-systemlimits/concepts/search-index-manage-limits.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-limits?branch=pr-en-us-10158) | [Details](#user-content-dcb3a6a6-6ae720e5)

<a id="dcb3a6a6-6ae720e5"></a>
### [concepts/search-index-manage-limits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/graphconnector-systemlimits/concepts/search-index-manage-limits.md)
 - **Line 12, Column 0**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010022204285560-10158%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bspEMXCxXZioFwwhmsfxUK0GffiAFiWaeg6D0LXHOvc%3D&st=2020-10-02T22%3A00%3A41Z&se=2020-11-02T22%3A05%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-03 22:16 UTC, opbld31 commented
Docs Build status updates of commit _[71e55ba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/71e55ba4b34c6aa052d2c0390bfa86e7cb17f8a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-index-manage-limits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/graphconnector-systemlimits/concepts/search-index-manage-limits.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-index-manage-limits?branch=pr-en-us-10158) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011032214410875-10158%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=W4JRBvUo3ERQAhguaZqRollERSLIC%2BIsM1WirHmV3Kw%3D&st=2020-11-03T22%3A11%3A07Z&se=2020-12-04T22%3A16%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-03 22:16 UTC, rsamai commented
@jasonjoh The first table looks correct on my Preview in VS Code, but it's not rendering in the Preview link. Can you please help me with that? 
![image](https://user-images.githubusercontent.com/24214524/98046518-317b2a80-1ddf-11eb-93c9-4f011433889d.png)

2020-11-07 02:53 UTC, angelgolfer-ms commented on concepts/search-index-manage-limits.md
> +author: "rsamai"
Line 5:
@rsamai , would you confirm with @snlraju-msft who your team would like to put in the "author" field of the connector API docs?
The "author" field does not necessarily reflect the individual who created the topic content initially. The Github name in that field is the contact point for any customer issues for that API set/workload in Microsoft Graph; there is a bot that automatically assigns issues opened against that topic to that name. So in general, there should be one person for a workload. I see that some of the connectors topics have @snlraju-msft, and this one has your Github name.

2020-11-07 04:39 UTC, angelgolfer-ms commented on concepts/search-index-manage-limits.md
> +# Connection System Limits in the Microsoft Graph
Line 10:
In general, please use sentence case for any title, including topic titles. That's per Microsoft writing style guide: https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25357
I suggest the title "Microsoft Graph connectors system limits".
Your topic as is hasn't even mentioned the feature name.

2020-11-07 04:50 UTC, angelgolfer-ms commented on concepts/search-index-manage-limits.md
> +## Connection limits
Before introducing the limits, please add a topic sentence to set up clearer expectations what these limits are. Most  conceptual topics should not start with a second level section header without even an intro paragraph.

2020-11-07 05:17 UTC, angelgolfer-ms commented on concepts/search-index-manage-limits.md
> +| **10 connections**         | Max number of connections per Microsoft 365 tenant                     |
GLOBAL:
When doing professional documentation, please use complete sentences and include a period to the end of each sentence.
Please do not use acronyms, like "max" for "maximum".

In the context of this topic, for each limit, please include the context where the limit matters, for example, referencing the resource or API name where applicable. This would help your audience to directly apply what they learn here to what they will need to do. You want your audience to benefit from your docs without having to make a lot of guesses.

Because this is a concept topic, it's ok to assume that some audience may be business decision makers who do high level planning, and are not exactly developers, and so when linking to API names, it's ok to use natural language in the link text with a link going to an API topic.

For example, line 14: 
Please rewrite as:
```
"The maximum number of [connections](/graph/api/resources/externalconnection?view=graph-rest-beta&preserve-view=true) per Microsoft 365 tenant."
```
Notice I'm showing here how to link from a concept topic to a reference topic. This type of link is called a site-relative link, as explained here: https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master#links-to-articles-in-other-repos-or-docsets
Link this way when the source and destination of the link is not both in the conceptual section, nor both in the reference section.
Please rewrite

2020-11-07 05:19 UTC, angelgolfer-ms commented on concepts/search-index-manage-limits.md
> +| **70 GB**      |Max byte size of a connection      |
Line 15:
I'll use this line as another example to illustrate the last comment. Please rewrite the description as:
```
"The maximum number of [items](/graph/api/resources/externalitem?view=graph-rest-beta&preserve-view=true) per connection."
```

2020-11-07 05:57 UTC, angelgolfer-ms commented on concepts/search-index-manage-limits.md
> +
Line 23:
I'll use this description as another example to show how to provide a fuller context that would help the audience understand where this limit comes in. 

```
"The maximum number of properties that can be defined in a [schema](/graph/api/resources/schema?view=graph-rest-beta&preserve-view=true), characterizing the data ingested through a connection."
```

2020-11-07 06:02 UTC, angelgolfer-ms commented on concepts/search-index-manage-limits.md
> +
Line 30:
```
"The maximum length of the ID string of an [external group](/graph/api/resources/externalgroup?view=graph-rest-beta&preserve-view=true). Must be unique within a connection. Only alpha-numeric characters are supported."
```
Notice the fix to "a connection" and the hyphen for alpha-numeric.

2020-11-07 06:05 UTC, angelgolfer-ms commented on concepts/search-index-manage-limits.md
> +<br/><br/>
Line 31:
Please explain what you mean by "group administration APIs". You can link to the API set, or give an example of an API and link to it. As is, the description is too vague and broad, and not helpful.

2020-11-07 06:06 UTC, angelgolfer-ms commented on concepts/search-index-manage-limits.md
> +| **4 items/sec (250 MB/hour)**         | Ingestion throughput                     |
Line 38:
"The throughput limit to ingest items through a connection."

2020-11-07 06:34 UTC, angelgolfer-ms commented on concepts/search-index-manage-limits.md
> +| **N/A**      |Max size of a property      |
Line 39:
This limit is especially important to convey to customers, and you need to provide a fuller context so that a developer can understand exactly which API this limit applies to.
Please rewrite:
```
"The maximum size of an item; this limit applies to the request body when [ingesting and indexing an item](/graph/api/externalconnection-put-items?view=graph-rest-beta&preserve-view=true)."
```

2020-11-07 08:47 UTC, angelgolfer-ms commented on concepts/search-index-manage-limits.md
> +- [Review the Graph Connectors API reference](/graph/api/resources/indexing-api-overview?view=graph-rest-beta&preserve-view=true)
Lines 46 and 47:
Please swap the two lines, to order the learning experience starting from a conceptual overview and then progressing to read about the API.

For line 47:
Please use lower case for "connectors". It's not a branded name, so per the capitalization guidelines I mentioned above, the term should be lower case.

For line 46:
We haven't exposed the indexing API as the connectors API anywhere else in the docs.
Also, in general, FYI, if you need to refer to Microsoft Graph, you cannot just say "Graph". "Microsoft Graph" is a branded name and just referring to it as "Graph" weakens the brand. 
Please change that line/ link text to:
"Use Microsoft Graph connectors to index external data sources"

2020-11-07 09:04 UTC, angelgolfer-ms requested changes
@rsamai ,thanks for drafting this topic. My overall comments are as follows:

- The descriptions in this draft are terse. Like I commented in an earlier PR of yours, please remember to use complete sentences and follow the capitalization guidelines for Microsoft. If you have questions on my comments pertaining to creating professional-looking docs, I'll be glad to explain. Hopefully you'll be able to apply similar standards in your future PRs.

- Please provide enough context to the description of each limit. As you will be adding this topic to the conceptual section in the table of contents, some customers reading this content may not be as familiar with the API.

2020-12-04 02:13 UTC, merged