Created chat-get-allmessages
microsoftgraph/microsoft-graph-docs pull request #10174
Opened 2020-10-05 11:56 UTC by v-rodriguezd

Created chat-get-allmessages and added details from work item 1212884

2020-10-05 11:58 UTC, opbld31 commented
Docs Build status updates of commit _[1b370d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b370d84d710ab249e10782a33339f635746cfd9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-b0fad787)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-b0fad787"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 25**: **[Warning-file-not-found]** `````Invalid file link: 'chat-get-allmessages.md'.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set [...]

2020-10-05 20:00 UTC, opbld30 commented
Docs Build status updates of commit _[62a4371](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62a43714e83ca4851f2b94eb350746d01febc7d8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-f09980c8)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-f09980c8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 25**: **[Warning-file-not-found]** `````Invalid file link: 'chat-get-allmessages.md'.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set [...]

2020-10-05 20:05 UTC, opbld31 commented
Docs Build status updates of commit _[d2e06de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2e06de9257a24daf98d730b2b88914b56f6da2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-d309439f)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-d309439f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/ap [...]

2020-10-05 20:09 UTC, laujan reviewed
I approve but awaiting feedback from the PM.

2020-10-07 05:10 UTC, opbld33 commented
Docs Build status updates of commit _[97cfa88](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97cfa886556756c0f5dda3aad1b592d61debc85e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-ee172799)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-ee172799"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 19, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resource [...]

2020-10-09 04:11 UTC, opbld32 commented
Docs Build status updates of commit _[5b6c492](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b6c49271b43d20008bce40371b35a4e457bdaae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-b63b647d)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-b63b647d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps- [...]

2020-10-09 05:21 UTC, opbld33 commented
Docs Build status updates of commit _[7d16776](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d16776853b184b8d1976fe2e8df38339e24b6ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-1c2a953c)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-1c2a953c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 127, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/administrativeunit?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 133, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/continuousAccessEvaluationPolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 140, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailappusageversionsusercount?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 146, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalconnection?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 147, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalgroup?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 148, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalgroupmember?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 160, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 161, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 162, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 162, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 178, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordsinglesignonsettings?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 178, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 184, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 191, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 207, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/print-list-printers?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 207, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 207, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 207, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-delete?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 207, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-allowedgroups?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 207, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-allowedusers?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 207, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-post-allowedgroups?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 207, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-post-allowedusers?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 207, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific vers [...]

2020-10-09 06:03 UTC, opbld30 commented
Docs Build status updates of commit _[c93af89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c93af890413b5858c5edbae8d8b7067d385fb9d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-67834f69)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-67834f69"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 236, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-windowsmalwarestatecount?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 271, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportRoot-getM365AppUserDetail?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 272, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportRoot-getM365AppUserCounts?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 273, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportRoot-getM365AppPlatformUserCounts?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 279, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatMessageHostedContent?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 280, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatMessageHostedContent?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 281, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatMessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 282, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 284, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 285, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 285, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 286, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-post?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 287, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-post-members?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 287, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 293, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todotask?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 293, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todotasklist?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 293, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/linkedresource?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 294, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outlooktask?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 294, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outlooktaskfolder?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 294, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outlooktaskgroup?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 302, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 302, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/eventmessagerequest?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 303, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? I [...]

2020-10-10 00:07 UTC, Lauragra commented on api-reference/beta/api/chat-get-allmessages.md
> +> [!Important]
This is a repeat of the text in the Include file; please delete.

2020-10-10 00:09 UTC, Lauragra commented on api-reference/beta/api/chat-get-allmessages.md
> +Retrieve all 1:1, group chats, meeting chats and Private channel messages the user is involved in.
Change "Private" channel to lowercase, private. The description should include mention of the resource, i.e. "Get all [chats] that a user is a participant in, including individual and group chats, meeting chats, and private channel messages."

2020-10-10 00:10 UTC, Lauragra commented on api-reference/beta/api/chat-get-allmessages.md
> +GET https://graph.microsoft.com/beta/users/{id}/chats/allMessages
In the HTTP request section we just show the syntax, not the full request URL (which is shown in the example).

2020-10-10 00:11 UTC, Lauragra commented on api-reference/beta/api/chat-get-allmessages.md
> +GET https://graph.microsoft.com/beta/users/{id}/chats/allMessages?$top=50&$filter=lastModifiedDateTime gt 2020-06-04T18:03:11.591Z and lastModifiedDateTime lt 2020-06-05T21:00:09.413Z
This looks like something is in the wrong place. It looks like you're showing an example of a request that includes query parameters? Please introduce the example and use the tick marks to set it off as an example.

2020-10-10 00:35 UTC, Lauragra commented on api-reference/beta/api/chat-get-allmessages.md
> +If successful, this method returns a `200 OK` response code and a list of [chatmessages](../resources/chatmessage.md) in the response body.
chatmessages -> chatMessages

2020-10-10 00:39 UTC, Lauragra commented on api-reference/beta/resources/chatmessage.md
> +|[1:1 and group chat messages](../api/chat-get-allmessages.md)| [chatMessage](../resources/chatmessage.md)| Retrieve all 1:1, group chats, meeting chats and Private channel messages. |
You need the verb here; also please update the description per the revision to the method topic description.

2020-10-10 00:39 UTC, Lauragra commented on concepts/changelog.md
> +|Addition|beta|Added the **allowInvitesFrom** property to the [authorizationPolicy](/graph/api/resources/authorizationpolicy?view=graph-rest-beta&preserve-view=true) resource.|
Please undo all the changes in this file except for the new Teamwork entry.

2020-10-10 00:41 UTC, opbld34 commented
Docs Build status updates of commit _[3fa2903](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fa29036a8bbd8f1f66210edc06fa5f7268825e3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3e5083f7)

<a id="3e5083f7"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010100040453387-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sLV9zgfLK9iAw%2B5eXCwnsrUzJJwL0l0VGKbTjJsQYTM%3D&st=2020-10-10T00%3A36%3A04Z&se=2020-11-10T00%3A41%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-10 00:41 UTC, Lauragra commented on api-reference/beta/api/chat-get-allmessages.md
> +# [HTTP](#tab/http)
Remove this and all the SDK snippets - the correct ones will get added via automation.

2020-10-10 00:43 UTC, Lauragra requested changes
Please see editorial comments. Also, can you please point me to the CSDL/API.md file associated with this PR?

2020-10-12 04:57 UTC, opbld34 commented
Docs Build status updates of commit _[f6acd96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6acd96e85be06220c072012d9b92ad5ed8cbed5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-1a32c847)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-1a32c847"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 59, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resou [...]

2020-10-12 05:44 UTC, opbld33 commented
Docs Build status updates of commit _[15ebebb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15ebebb3a3b9ff1392c3382a2ede65379c771abc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-161cbeaf)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-161cbeaf"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 59, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resou [...]

2020-10-12 06:00 UTC, opbld33 commented
Docs Build status updates of commit _[ce94e81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ce94e8176428322e562282987f30a44008f0a3db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-748c0a5a)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-748c0a5a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 59, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resou [...]

2020-10-12 06:09 UTC, opbld31 commented
Docs Build status updates of commit _[9dc7b90](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9dc7b9073f7c735938b5c0f47eed0d6382debe0c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-da175d3d)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-da175d3d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 59, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resou [...]

2020-10-12 06:28 UTC, opbld30 commented
Docs Build status updates of commit _[817a9bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/817a9bf01ab7866c3da05b3905d35c9dde17915c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-6c3eadef)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-6c3eadef"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 59, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resou [...]

2020-10-12 06:39 UTC, opbld31 commented
Docs Build status updates of commit _[22c4e0b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22c4e0bf7b0cc3d3581c142cfa67b0469a39d33a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-f474ed45)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-f474ed45"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 51, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 53, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 59, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resou [...]

2020-10-12 06:48 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +> [!Important]
Resolved

2020-10-12 06:48 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +Retrieve all 1:1, group chats, meeting chats and Private channel messages the user is involved in.
Resolved

2020-10-12 06:48 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +GET https://graph.microsoft.com/beta/users/{id}/chats/allMessages
Resolved

2020-10-12 06:48 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +GET https://graph.microsoft.com/beta/users/{id}/chats/allMessages?$top=50&$filter=lastModifiedDateTime gt 2020-06-04T18:03:11.591Z and lastModifiedDateTime lt 2020-06-05T21:00:09.413Z
Resolved

2020-10-12 06:49 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +If successful, this method returns a `200 OK` response code and a list of [chatmessages](../resources/chatmessage.md) in the response body.
Resolved

2020-10-12 06:49 UTC, v-rodriguezd commented on api-reference/beta/resources/chatmessage.md
> +|[1:1 and group chat messages](../api/chat-get-allmessages.md)| [chatMessage](../resources/chatmessage.md)| Retrieve all 1:1, group chats, meeting chats and Private channel messages. |
Resolved

2020-10-12 06:49 UTC, v-rodriguezd commented on concepts/changelog.md
> +|Addition|beta|Added the **allowInvitesFrom** property to the [authorizationPolicy](/graph/api/resources/authorizationpolicy?view=graph-rest-beta&preserve-view=true) resource.|
Resolved

2020-10-12 06:50 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +# [HTTP](#tab/http)
Hi Laura as per your inputs I have made the changes in the optional query parameters section we have removed "https://graph.microsoft.com/beta/" and SDK snippets. Please confirm?

2020-10-12 18:56 UTC, salakhani reviewed
Can you please replace name with some other name?

2020-10-13 04:34 UTC, opbld31 commented
Docs Build status updates of commit _[2520f25](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2520f254875f9d442f517282cae366b9e0195f94)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-b6c64719)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-b6c64719"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 59, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32loba [...]

2020-10-13 04:35 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +                    "displayName": "Avinash Ravi",
Resolved

2020-10-13 04:35 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +                "content": "<div>\n<blockquote itemscope=\"\" itemtype=\"http://schema.skype.com/Reply\" itemid=\"1600457867820\">\n<strong itemprop=\"mri\" itemid=\"8:orgid:0de69e5e-2da8-4cf2-821f-5
Resolved

2020-10-15 03:22 UTC, Lauragra commented
> Please see editorial comments. Also, can you please point me to the CSDL/API.md file associated with this PR?
> Hi @Lauragra: Here is a link to a [Word doc](https://teams.microsoft.com/l/file/4875A555-4392-441B-9E62-D4E1AD6F239C?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&fileType=docx&objectUrl=https%3A%2F%2Fmicrosoft-my.sharepoint-df.com%2Fpersonal%2Fvikramju_microsoft_com%2FDocuments%2FInformation%20Protection%2FExport%20content%20with%20the%20Microsoft%20Teams%20Export%20APIs.docx&baseUrl=https%3A%2F%2Fmicrosoft-my.sharepoint-df.com%2Fpersonal%2Fvikramju_microsoft_com&serviceName=p2p&threadId=19:76a07f03-e0e8-4b78-80c1-c47f65fa4019_c3a658a7-dbdb-48dd-8b8a-813e9ef574cf@unq.gbl.spaces&messageId=1601597262503) provided by the PM. Does that help?

I don't seem to have access to that file. Can you give me access? Thanks.

2020-10-15 03:25 UTC, opbld30 commented
Docs Build status updates of commit _[237cfee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/237cfee22ee87ade1f6cff4c65ba0c6d29c3d3ef)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3aeff293)

<a id="3aeff293"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010150325116799-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WQ%2F14VG0TBsRouptVErlEvzAR6xWunBeuP7ACLTpS3M%3D&st=2020-10-15T03%3A20%3A40Z&se=2020-11-15T03%3A25%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-15 04:49 UTC, opbld32 commented
Docs Build status updates of commit _[cc3040d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc3040de2dbb0eaf54b3064976fd5ca683cff2ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-6686c1b4)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-6686c1b4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 80, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 81, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 81, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 81, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 81, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32loba [...]

2020-10-16 05:05 UTC, opbld34 commented
Docs Build status updates of commit _[56da3e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56da3e87d0a671721bb1a22bcd4cbf0d7204d97b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-904de353)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-904de353"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 80, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 81, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 81, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 81, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 81, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32loba [...]

2020-10-17 00:11 UTC, opbld31 commented
Docs Build status updates of commit _[c9e4e78](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9e4e78ccf9efe9c0ce92e52a36443669ce46df6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-78f845a0)
[api-reference/beta/api/chat-get-allmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-get-allmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-allmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-78f845a0"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 80, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 81, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 81, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 81, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 81, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32loba [...]

2020-10-19 21:00 UTC, AkJo commented on api-reference/beta/api/chat-get-allmessages.md
> +GET /users/{id}/chats/allMessages
/users/{id}/chats/getAllMessages

2020-10-19 21:01 UTC, AkJo commented on api-reference/beta/api/chat-get-allmessages.md
> +GET /users/{id}/chats/allMessages?$top=50&$filter=lastModifiedDateTime gt 2020-06-04T18:03:11.591Z and lastModifiedDateTime lt 2020-06-05T21:00:09.413Z
/users/{id}/chats/getAllMessages?$top=50&$filter=....

2020-10-19 21:01 UTC, AkJo commented on api-reference/beta/api/chat-get-allmessages.md
> +GET https://graph.microsoft.com/beta/users/{id}/chats/allMessages
Please update all reference to "allMessages" with "getAllMessages"

2020-10-19 21:02 UTC, AkJo commented on api-reference/beta/api/chat-get-allmessages.md
> +    "@odata.nextLink": "https://graph.microsoft.com/beta/users/8b081ef6-4792-4def-b2c9-c363a1bf41d5/chats/allMessages?$skip=10",
getAllMessages

2020-10-19 21:03 UTC, AkJo commented on api-reference/beta/resources/chatmessage.md
> +|[Get all chats](../api/chat-get-allmessages.md)| [chatMessage](../resources/chatmessage.md)| Get all chats that a user is a participant in, including individual and group chats, meeting chats, and p
Get all chat messages

2020-10-19 21:05 UTC, AkJo commented on api-reference/beta/resources/chatmessage.md
> +|[Get all chats](../api/chat-get-allmessages.md)| [chatMessage](../resources/chatmessage.md)| Get all chats that a user is a participant in, including individual and group chats, meeting chats, and p
"Get **messages from all chats** that a user is a participant in, including one-on-one chats, group chats and meeting chats"

2020-10-19 21:07 UTC, AkJo commented on api-reference/beta/api/chat-get-allmessages.md
> +title: "Get allChatMessages"
"Get all chat messages"

2020-10-19 21:08 UTC, AkJo commented on api-reference/beta/api/chat-get-allmessages.md
> +Get all [chats](../resources/chatmessage.md) that a user is a participant in, including individual and group chats, meeting chats, and private channel messages.
Get all messages from all [chats](../resources/chatmessage.md) that a user is a participant in, including one-on-one chats, group chats and meeting chats.

2020-10-19 21:08 UTC, AkJo commented on api-reference/beta/api/chat-get-allmessages.md
> +# Get allChatMessages
# GetAllChatMessages

2020-10-19 21:09 UTC, AkJo commented on api-reference/beta/api/chat-get-allmessages.md
> +description: "Get all chats that a user is a participant in."
Get messages from all chats that a user is a participant in.

2020-10-19 21:10 UTC, AkJo commented on concepts/changelog.md
> +|Addition|Beta|Add the [Get allChatMessages](/graph/api/chat-get-allmessages) method to the [chatMessage](/graph/api/resources/chatmessage?view=graph-rest-beta) resource.|
Add the [GetAllChatMessages](/graph/api/chat-get-allmessages) method to the [chat](/graph/api/resources/chat?view=graph-rest-beta) collection resource.|

2020-10-19 21:33 UTC, Lauragra commented on api-reference/beta/api/chat-get-allmessages.md
> +title: "Get allChatMessages"
Per our file naming and topic title guidance, the file name should be chat-getallmessages, and the title and H1 should be "chat: getAllMessages".

2020-10-20 06:23 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +GET /users/{id}/chats/allMessages
Resolved

2020-10-20 06:24 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +GET /users/{id}/chats/allMessages?$top=50&$filter=lastModifiedDateTime gt 2020-06-04T18:03:11.591Z and lastModifiedDateTime lt 2020-06-05T21:00:09.413Z
Resolved

2020-10-20 06:24 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +GET https://graph.microsoft.com/beta/users/{id}/chats/allMessages
Resolved

2020-10-20 06:25 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +    "@odata.nextLink": "https://graph.microsoft.com/beta/users/8b081ef6-4792-4def-b2c9-c363a1bf41d5/chats/allMessages?$skip=10",
Resolved

2020-10-20 06:25 UTC, v-rodriguezd commented on api-reference/beta/resources/chatmessage.md
> +|[Get all chats](../api/chat-get-allmessages.md)| [chatMessage](../resources/chatmessage.md)| Get all chats that a user is a participant in, including individual and group chats, meeting chats, and p
Resolved

2020-10-20 06:26 UTC, v-rodriguezd commented on api-reference/beta/resources/chatmessage.md
> +|[Get all chats](../api/chat-get-allmessages.md)| [chatMessage](../resources/chatmessage.md)| Get all chats that a user is a participant in, including individual and group chats, meeting chats, and p
Resolved

2020-10-20 06:27 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +title: "Get allChatMessages"
Resolved

2020-10-20 06:28 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +Get all [chats](../resources/chatmessage.md) that a user is a participant in, including individual and group chats, meeting chats, and private channel messages.
Resolved

2020-10-20 06:28 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +# Get allChatMessages
Resolved

2020-10-20 06:28 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +description: "Get all chats that a user is a participant in."
Resolved

2020-10-20 06:29 UTC, v-rodriguezd commented on concepts/changelog.md
> +|Addition|Beta|Add the [Get allChatMessages](/graph/api/chat-get-allmessages) method to the [chatMessage](/graph/api/resources/chatmessage?view=graph-rest-beta) resource.|
Resolved

2020-10-20 06:30 UTC, v-rodriguezd commented on api-reference/beta/api/chat-get-allmessages.md
> +title: "Get allChatMessages"
Resolved

2020-10-20 07:22 UTC, AkJo commented on api-reference/beta/api/chat-getallmessages.md
> +Content-length: 201
Please try using some other random number than 347 or any other numbers that do no map to HTTP status codes. 

While reading at a glance, the 201 threw me off for a moment - thinking that this was the response code.

2020-10-20 07:22 UTC, AkJo commented on api-reference/beta/resources/chatmessage.md
> +|[Get all chat messages](../api/chat-getallmessages.md)| [chatMessage](../resources/chatmessage.md)| Get messages from all chats that a user is a participant in, including one-on-one chats, group cha
[chatMessage](../resources/chatmessage.md) collection

2020-10-20 07:57 UTC, v-rodriguezd commented on api-reference/beta/api/chat-getallmessages.md
> +Content-length: 201
Resolved

2020-10-20 08:04 UTC, v-rodriguezd commented on api-reference/beta/resources/chatmessage.md
> +|[Get all chat messages](../api/chat-getallmessages.md)| [chatMessage](../resources/chatmessage.md)| Get messages from all chats that a user is a participant in, including one-on-one chats, group cha
Resolved

2020-10-22 00:12 UTC, opbld32 commented
Docs Build status updates of commit _[2629c5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2629c5fa9f6b97db456acc80fb58b17c54371f19)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-b749c4bf)
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-b749c4bf"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateaccountsummary?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategorysummary?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateconfiguration?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatestatesummary?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macosassociateddomainsitem?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-androidforwork-androiddeviceownerenrollmenttokentype?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributevaluetype?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatebehavior?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategory?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatescheduletype?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-device [...]

2020-10-22 00:14 UTC, laujan reviewed
@AkJo @salakhani is this PR approved?

2020-10-22 04:45 UTC, opbld30 commented
Docs Build status updates of commit _[da659da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da659da35a87cb1a1344f75059d420c657760038)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-4c8f67b6)
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-4c8f67b6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjobstatus?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjobstatus?view=graph-rest-beta`````
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustom [...]

2020-10-28 04:56 UTC, opbld31 commented
Docs Build status updates of commit _[c623521](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c623521d0dff69334fdb1881e05c92aa922d3ede)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-05807cc7)
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-05807cc7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 59, C [...]

2020-10-28 07:03 UTC, opbld30 commented
Docs Build status updates of commit _[37b0f08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37b0f0805eed58baa24b4209126677fc3bdff364)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-c8b5b631)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-c8b5b631"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you m [...]

2020-10-28 07:08 UTC, opbld30 commented
Docs Build status updates of commit _[75930f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/75930f9cae269dfa35b356b146639cf4e46b6099)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-b85226f1)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-b85226f1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph [...]

2020-10-28 07:14 UTC, opbld33 commented
Docs Build status updates of commit _[4d522ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d522ed6dcb1e97a7573b14b8b84e6eb86f84ffa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-42a9c382)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-42a9c382"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph [...]

2020-10-28 07:20 UTC, opbld32 commented
Docs Build status updates of commit _[66d8bbe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66d8bbe236f92a34fce999d516e987b86cd3d4be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-7dec0334)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-7dec0334"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph [...]

2020-10-29 06:38 UTC, opbld32 commented
Docs Build status updates of commit _[61fa6d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61fa6d39f52dacc9b9d1b53c0eec32c9db0b125c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-5319219a)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-5319219a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph [...]

2020-10-29 06:50 UTC, opbld33 commented
Docs Build status updates of commit _[f82bccf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f82bccfe53f1e309d738f079302b7a6871112e30)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-39008800)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-39008800"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph [...]

2020-10-29 07:03 UTC, opbld33 commented
Docs Build status updates of commit _[0189e77](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0189e775f44ab78586b00cdab1e8b55a54c3581f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-56395d6f)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-56395d6f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph [...]

2020-10-29 07:27 UTC, opbld30 commented
Docs Build status updates of commit _[8c7a7cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c7a7cbf20fdef31f61f2f1a8bf96da798be8e06)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-9d1f3221)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-9d1f3221"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph [...]

2020-10-29 07:29 UTC, opbld31 commented
Docs Build status updates of commit _[3f78144](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f78144cf3f115cb08b6254a66ec9f2b4560b79a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-32a5b293)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-32a5b293"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph [...]

2020-11-02 08:12 UTC, opbld32 commented
Docs Build status updates of commit _[966db98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/966db986b7477b60247f3f55869198adcca69dae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-8f9c1f2d)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-8f9c1f2d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[S [...]

2020-11-02 09:56 UTC, opbld30 commented
Docs Build status updates of commit _[e37e980](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e37e980d8679a06c72ff3a9c42869082490cb8c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-bd0b6955)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-bd0b6955"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[S [...]

2020-11-03 04:10 UTC, opbld30 commented
Docs Build status updates of commit _[a3d3496](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a3d34962442ec88fd5008ed121a3a72757350c40)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-adf3439d)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-adf3439d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view [...]

2020-11-05 02:20 UTC, Lauragra commented on api-reference/beta/api/channel-getallmessages.md
> +GET https://graph.microsoft.com/beta/teams/0e05a7e4-a48d-4615-b0b7-c7494da9ce68/channels/getAllMessages
The HTTP request section doesn't show the full URL or example values, just the HTTP syntax.

2020-11-05 02:22 UTC, Lauragra commented on api-reference/beta/api/channel-getallmessages.md
> +```
You are missing two H2 sections: Optional query parameters, and Request body. Please add. If you use the stub generator tool, it should create topics with all the required sections included.

2020-11-05 02:23 UTC, Lauragra commented on api-reference/beta/api/channel-getallmessages.md
> +GET https://graph.microsoft.com/beta/teams/0e05a7e4-a48d-4615-b0b7-c7494da9ce68/channels/allMessages?$top=2
The example has `allMessages` but should be `getAllMessages`, right?

2020-11-05 02:24 UTC, Lauragra commented on api-reference/beta/api/channel-getallmessages.md
> +If successful, this method returns a `200 OK` response code.
You need to mention that it also returns all the messages in the channel.

2020-11-05 02:24 UTC, Lauragra commented on api-reference/beta/api/chat-getallmessages.md
> +# GetAllChatMessages
chat: getAllMessages

2020-11-05 02:26 UTC, Lauragra commented on concepts/changelog.md
> +|Addition|beta|Added the **customDialerAppPro
Please revert this change - looks like a line break added in the wrong place?

2020-11-05 02:30 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | beta | Added the [getAllMessages](/graph/api/chat-getallmessages?view=graph-rest-beta) method to the [chat](/graph/api/resources/chat?view=graph-rest-beta)  resource.|
Please also add entries to the Microsoft.Teams.Core.json file for these changes.

2020-11-05 02:30 UTC, opbld32 commented
Docs Build status updates of commit _[99a4d05](https://github.com/microsoftgraph/microsoft-graph-docs/commits/99a4d0500333cfedbbbab23fcbef16620b7abe66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-28bdf22d)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-28bdf22d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you  [...]

2020-11-05 02:32 UTC, Lauragra requested changes
Please see editorial feedback and incorporate. Also, we are still missing team-getallmessages; are you planning to add a topic for that?

2020-11-05 04:24 UTC, v-rodriguezd commented on api-reference/beta/api/channel-getallmessages.md
> +GET https://graph.microsoft.com/beta/teams/0e05a7e4-a48d-4615-b0b7-c7494da9ce68/channels/allMessages?$top=2
Resolved

2020-11-05 04:24 UTC, v-rodriguezd commented on api-reference/beta/api/channel-getallmessages.md
> +If successful, this method returns a `200 OK` response code.
Resolved

2020-11-05 04:28 UTC, opbld31 commented
Docs Build status updates of commit _[1c810c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c810c8d36a0b862a1eb74e498204016c3fb240a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-eadd7244)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-eadd7244"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you  [...]

2020-11-05 04:30 UTC, v-rodriguezd commented on api-reference/beta/api/chat-getallmessages.md
> +# GetAllChatMessages
Resolved

2020-11-05 04:31 UTC, opbld32 commented
Docs Build status updates of commit _[992b843](https://github.com/microsoftgraph/microsoft-graph-docs/commits/992b8439b2803d335ae95aeb554342e4759b15fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-c363df27)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-c363df27"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you  [...]

2020-11-05 04:31 UTC, v-rodriguezd commented on concepts/changelog.md
> +|Addition|beta|Added the **customDialerAppPro
Hi Laura I did not make this change, please suggest

2020-11-05 04:42 UTC, v-rodriguezd commented on api-reference/beta/api/channel-getallmessages.md
> +GET https://graph.microsoft.com/beta/teams/0e05a7e4-a48d-4615-b0b7-c7494da9ce68/channels/getAllMessages
Resolved. Is it correct? Please let me know what to include.

2020-11-05 04:44 UTC, opbld34 commented
Docs Build status updates of commit _[ebcc628](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ebcc62809cf4827bdb25404b4ae6e907a1bc3d6c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-e202421f)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-e202421f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you  [...]

2020-11-05 04:48 UTC, v-rodriguezd commented on api-reference/beta/api/channel-getallmessages.md
> +```
@Lauragra please suggest what to include in the Optional query parameters, and Request body sections

2020-11-05 04:52 UTC, opbld30 commented
Docs Build status updates of commit _[ab371ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab371ed4f3025db1e5ae0bab9edb0a15d1e50c8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-46b4a37e)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |

<a id="de0bbbbb-46b4a37e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you  [...]

2020-11-05 05:09 UTC, v-rodriguezd commented on concepts/changelog.md
> +| Addition | beta | Added the [getAllMessages](/graph/api/chat-getallmessages?view=graph-rest-beta) method to the [chat](/graph/api/resources/chat?view=graph-rest-beta)  resource.|
Resolved.

2020-11-05 05:10 UTC, opbld33 commented
Docs Build status updates of commit _[4118913](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41189136b47ee74f5cb5bd3ed3da83c0875ff0e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-16ad326f)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-16ad326f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean  [...]

2020-11-06 01:18 UTC, opbld34 commented
Docs Build status updates of commit _[c97235e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c97235e62a655440a00c07758ad9f49bd8d6b096)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-4865187b)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-4865187b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````D [...]

2020-11-06 01:19 UTC, Lauragra commented on api-reference/beta/api/channel-getallmessages.md
> +GET /teams/{id}/channels/getAllMessages?$filter=lastModifiedDateTime ge '2020-04-01' and lastModifiedDateTime le '2020-04-02'
Why does the HTTP request section here show the use of the $filter parameter? In the next section we state that OData query parameters are not supported. Please reconcile.

2020-11-06 01:20 UTC, opbld33 commented
Docs Build status updates of commit _[6959e2a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6959e2afda3dd952dc628c0685be53c6a22ade04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-ae38def3)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-ae38def3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````D [...]

2020-11-06 01:20 UTC, Lauragra commented on api-reference/beta/api/channel-getallmessages.md
> +GET https://graph.microsoft.com/beta/teams/0e05a7e4-a48d-4615-b0b7-c7494da9ce68/channels/getAllMessages?$top=2
This example also uses a query parameter.

2020-11-06 01:22 UTC, opbld33 commented
Docs Build status updates of commit _[71e3431](https://github.com/microsoftgraph/microsoft-graph-docs/commits/71e3431e76d701f7174a118c514e20a43feb2aca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-5353f2fb)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-5353f2fb"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````D [...]

2020-11-06 01:24 UTC, opbld31 commented
Docs Build status updates of commit _[8b87f62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b87f62985f8b157d434f09fe4e1d5c6895025c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-eae9d65f)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-eae9d65f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````D [...]

2020-11-06 01:26 UTC, opbld34 commented
Docs Build status updates of commit _[cf98a87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cf98a87254ae6a70a6a598773e522201e08e4979)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-42c5aae0)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-42c5aae0"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````D [...]

2020-11-06 01:31 UTC, opbld32 commented
Docs Build status updates of commit _[d2e26c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2e26c9ec3505c1aca2893b6d0cc1af3d64fbf52)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-f7c1d184)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-f7c1d184"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````D [...]

2020-11-06 01:33 UTC, opbld30 commented
Docs Build status updates of commit _[36de88e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/36de88e182c99b807c89b9dcdb17b6a3a62640a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-7b54c3e6)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-7b54c3e6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````D [...]

2020-11-06 01:34 UTC, Lauragra commented
@AkJo , @nkramer , @laujan , is this PR really ready to merge? I don't see a getAllMessages function on the channel resource in the beta metadata. I do see one on the team resource that we don't currently have an API topic for. Does it need to be part of this PR? Please clarify.

2020-11-06 01:36 UTC, Lauragra requested changes
I have a question regarding support for query parameters on channel-getAllMessages; please take a look. I also still need to verify that the channel function is/will be available and why we aren't documenting the missing function for the team resource type.

2020-11-06 03:07 UTC, v-rodriguezd commented on api-reference/beta/api/channel-getallmessages.md
> +GET https://graph.microsoft.com/beta/teams/0e05a7e4-a48d-4615-b0b7-c7494da9ce68/channels/getAllMessages?$top=2
Resolved

2020-11-06 03:08 UTC, v-rodriguezd commented on api-reference/beta/api/channel-getallmessages.md
> +GET /teams/{id}/channels/getAllMessages?$filter=lastModifiedDateTime ge '2020-04-01' and lastModifiedDateTime le '2020-04-02'
Resolved

2020-11-06 03:09 UTC, opbld32 commented
Docs Build status updates of commit _[30bd1d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30bd1d50590324f7fae95660a51deb3627146529)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-98f30095)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-98f30095"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````D [...]

2020-11-06 03:22 UTC, v-rodriguezd commented on api-reference/beta/api/channel-getallmessages.md
> +GET /teams/{id}/channels/getAllMessages?$filter=lastModifiedDateTime ge '2020-04-01' and lastModifiedDateTime le '2020-04-02'
Resolved

2020-11-06 03:22 UTC, v-rodriguezd commented on api-reference/beta/api/channel-getallmessages.md
> +GET https://graph.microsoft.com/beta/teams/0e05a7e4-a48d-4615-b0b7-c7494da9ce68/channels/getAllMessages?$top=2
Resolved

2020-11-06 03:54 UTC, Lauragra commented
@v-rodriguezd , this looks good now, pending my question about the function on the channel and team resources. Still holding off merging until we reach resolution.

2020-11-06 04:23 UTC, opbld34 commented
Docs Build status updates of commit _[d65bd9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d65bd9c72ab21f7fcc4e5f8f3587860f8bb57556)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-8da9e825-f98711ce)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-f98711ce)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="8da9e825-f98711ce"></a>
### [api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md)
 - **Line 64, Column 1**: **[Suggestion-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-f98711ce"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to [...]

2020-11-06 04:24 UTC, v-rodriguezd commented
> I have a question regarding support for query parameters on channel-getAllMessages; please take a look. I also still need to verify that the channel function is/will be available and why we aren't documenting the missing function for the team resource type.

Hi Laura there is a reference to Get all channel messages in the channel.md file if this is what you are referring to. Also Created new file team-getallmessages.md but need content for Example Response section.

2020-11-06 04:34 UTC, Lauragra commented
> > I have a question regarding support for query parameters on channel-getAllMessages; please take a look. I also still need to verify that the channel function is/will be available and why we aren't documenting the missing function for the team resource type.
> 
> Hi Laura there is a reference to Get all channel messages in the channel.md file if this is what you are referring to. Also Created new file team-getallmessages.md but need content for Example Response section.

I'm referring to the fact that I don't see a getAllMessages function defined for type channel in the live metadata. Either that function hasn't shipped yet, or the documentation is inaccurate. Thank you for adding the team topic.

2020-11-06 06:00 UTC, opbld32 commented
Docs Build status updates of commit _[ca29b07](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ca29b079321321073bd022cb8a2124138e1a572f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-3187ced7)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-3187ced7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintu [...]

2020-11-06 06:09 UTC, opbld30 commented
Docs Build status updates of commit _[8cf3590](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8cf3590a30147a9347d7a1d62dc10ab4818b2f2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-3cce7fe1)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-3cce7fe1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean  [...]

2020-11-06 06:11 UTC, opbld33 commented
Docs Build status updates of commit _[a103041](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a103041a6269d97fd41d4bb22dc26d011d698b97)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-146b67c1)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-146b67c1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean  [...]

2020-11-06 06:13 UTC, opbld32 commented
Docs Build status updates of commit _[cd7b33d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd7b33d3f834d162426f0b1ed024b42ecf57deb3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-98fa86c9)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-98fa86c9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? I [...]

2020-11-06 06:18 UTC, opbld34 commented
Docs Build status updates of commit _[b4e01f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4e01f22ef6479740ebbe3b2dce4a8baadbf113a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-3a3056d7)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-3a3056d7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? I [...]

2020-11-06 06:26 UTC, opbld30 commented
Docs Build status updates of commit _[b4be470](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4be4709c47ec094e2e11b89021137a4faf3ee36)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-ddab8618)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-ddab8618"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? I [...]

2020-11-06 06:49 UTC, opbld30 commented
Docs Build status updates of commit _[070aa52](https://github.com/microsoftgraph/microsoft-graph-docs/commits/070aa5227c8f1d4185ac71e3c57b229358b0c515)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-f97ab5a3)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-f97ab5a3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? I [...]

2020-11-06 06:59 UTC, opbld30 commented
Docs Build status updates of commit _[278ba3b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/278ba3b995e2f0d3b5ffa1b8a422f9b64935ed90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-286166fc)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-286166fc"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? I [...]

2020-11-06 08:22 UTC, AkJo commented
> @AkJo , @nkramer , @laujan , is this PR really ready to merge? I don't see a getAllMessages function on the channel resource in the beta metadata. I do see one on the team resource that we don't currently have an API topic for. Does it need to be part of this PR? Please clarify.

@Lauragra , it is in the publish pipeline. AGS deployments are running behind.

It is part of the exercise to rename the "allMessages" function to "getAllMessages" throughout our schema.

2020-11-06 08:26 UTC, AkJo commented
> I have a question regarding support for query parameters on channel-getAllMessages; please take a look. I also still need to verify that the channel function is/will be available and why we aren't documenting the missing function for the team resource type.

@Lauragra 

Team-GetAllMessages is not hooked up to anything today. It is just a stub in the schema to allow setting up of change notifications. That is why it has no page for it.

We could create a mostly empty page that cross references to this page:

https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0

We would put down something like:
This resource is used to create webhooks to get notifications for all messages across all teams in an organization.
And then have a link to the page above.

2020-11-06 08:27 UTC, AkJo commented
Also, please dont merge until you get an ACK from me, but we should keep it in a ready to merge state.

2020-11-06 09:25 UTC, opbld34 commented
Docs Build status updates of commit _[0de5a44](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0de5a44c943b4db464b250581f4f98cb0e4f5938)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-95224f88)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-95224f88"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? I [...]

2020-11-06 09:30 UTC, v-rodriguezd commented
> > > I have a question regarding support for query parameters on channel-getAllMessages; please take a look. I also still need to verify that the channel function is/will be available and why we aren't documenting the missing function for the team resource type.
> > 
> > 
> > Hi Laura there is a reference to Get all channel messages in the channel.md file if this is what you are referring to. Also Created new file team-getallmessages.md but need content for Example Response section.
> 
> I'm referring to the fact that I don't see a getAllMessages function defined for type channel in the live metadata. Either that function hasn't shipped yet, or the documentation is inaccurate. Thank you for adding the team topic.



> > I have a question regarding support for query parameters on channel-getAllMessages; please take a look. I also still need to verify that the channel function is/will be available and why we aren't documenting the missing function for the team resource type.
> 
> @Lauragra
> 
> Team-GetAllMessages is not hooked up to anything today. It is just a stub in the schema to allow setting up of change notifications. That is why it has no page for it.
> 
> We could create a mostly empty page that cross references to this page:
> 
> https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0
> 
> We would put down something like:
> This resource is used to create webhooks to get notifications for all messages across all teams in an organization.
> And then have a link to the page above.

Resolved

2020-11-06 16:44 UTC, Lauragra commented on api-reference/beta/api/team-getallmessages.md
> +This resource is used to create webhooks to get notifications for all messages across all teams in an organization. Please refer [Webhooks](../resources/webhooks.md)
Please add the actual content to this topic.

2020-11-06 16:47 UTC, Lauragra commented
> > @AkJo , @nkramer , @laujan , is this PR really ready to merge? I don't see a getAllMessages function on the channel resource in the beta metadata. I do see one on the team resource that we don't currently have an API topic for. Does it need to be part of this PR? Please clarify.
> 
> @Lauragra , it is in the publish pipeline. AGS deployments are running behind.
> 
> It is part of the exercise to rename the "allMessages" function to "getAllMessages" throughout our schema.

Okay. Generally we don't publish docs before APIs are available, so I'll remove the Ready to merge label from this PR. Please set it again when the channel function is released.

2020-11-06 17:08 UTC, Lauragra commented
> Also, please dont merge until you get an ACK from me, but we should keep it in a ready to merge state.

FYI, our process is to not set **ready to merge** on a PR until the APIs are actually in the pipeline or live. So I set this back to **do not merge**. When the new function is officially merged, you can set it back to notify me to publish.

2020-11-09 06:09 UTC, v-rodriguezd commented on api-reference/beta/api/team-getallmessages.md
> +This resource is used to create webhooks to get notifications for all messages across all teams in an organization. Please refer [Webhooks](../resources/webhooks.md)
Hi Anand @AkJo can you let me know if any other detail needs to be added to team-getallmessages method?

2020-11-09 06:44 UTC, AkJo commented
> > > @AkJo , @nkramer , @laujan , is this PR really ready to merge? I don't see a getAllMessages function on the channel resource in the beta metadata. I do see one on the team resource that we don't currently have an API topic for. Does it need to be part of this PR? Please clarify.
> > 
> > 
> > @Lauragra , it is in the publish pipeline. AGS deployments are running behind.
> > It is part of the exercise to rename the "allMessages" function to "getAllMessages" throughout our schema.
> 
> Okay. Generally we don't publish docs before APIs are available, so I'll remove the Ready to merge label from this PR. Please set it again when the channel function is released.

That is fine. My directions was more for the content editor that we should be keep the PR in a 'ready-to-go' state while waiting for schema changes to go live.

2020-11-09 06:47 UTC, AkJo commented on api-reference/beta/api/team-getallmessages.md
> +title: "team: getAllMessages"
Technically, this should be "teams: getAllMessages"

The getAllMessages is bound to the teams collection and not to a singular team.

2020-11-09 06:47 UTC, AkJo commented on api-reference/beta/api/team-getallmessages.md
> +# team: getAllMessages
teams: getAllmessages

2020-11-09 06:48 UTC, AkJo commented on api-reference/beta/api/team-getallmessages.md
> +This resource is used to create webhooks to get notifications for all messages across all teams in an organization. Please refer [Webhooks](../resources/webhooks.md)
@v-rodriguezd , please add a See also section that references this page:
https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0

There is no other content to add for this page.

2020-11-09 06:52 UTC, AkJo commented on api-reference/beta/api/chat-getallmessages.md
> +title: "chat: getAllMessages"
Technically, this should be "chats: getAllMessages"

The getAllMessages is bound to the chats collection and not to a singular chat.

Please update the filename as well.

2020-11-09 06:52 UTC, AkJo commented on api-reference/beta/api/channel-getallmessages.md
> +title: "channel: getAllMessages"
Technically, this should be "channels: getAllMessages"

The getAllMessages is bound to the channels collection and not to a singular channel.

Please update the filename as well.

2020-11-09 07:08 UTC, opbld34 commented
Docs Build status updates of commit _[39eb45e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39eb45ee548cfb02ffa6946668eac60a2cb6f229)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-7aec005b-55cc2d5b)
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-a83fbdf9-55cc2d5b)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-00685cff-55cc2d5b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-55cc2d5b)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7aec005b-55cc2d5b"></a>
### [api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0`````

<a id="a83fbdf9-55cc2d5b"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md)
 - **Line 39, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-getallmessages.md'.`````

<a id="00685cff-55cc2d5b"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml)
 - **Line 12278, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/team-getallmessages.md'.`````

<a id="de0bbbbb-55cc2d5b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/ [...]

2020-11-09 07:10 UTC, opbld32 commented
Docs Build status updates of commit _[5dabb6a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5dabb6a8a350819ffe3b3dc90d59402e56b0cb41)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-7aec005b-81fb9910)
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-a83fbdf9-81fb9910)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-00685cff-81fb9910)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-81fb9910)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7aec005b-81fb9910"></a>
### [api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0`````

<a id="a83fbdf9-81fb9910"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md)
 - **Line 39, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-getallmessages.md'.`````

<a id="00685cff-81fb9910"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml)
 - **Line 12278, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/team-getallmessages.md'.`````

<a id="de0bbbbb-81fb9910"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/ [...]

2020-11-09 07:13 UTC, opbld34 commented
Docs Build status updates of commit _[5a1f533](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a1f533071493c5678d2747dfd54f107a2fc09cb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-7aec005b-43082f4f)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-00685cff-43082f4f)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-43082f4f)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7aec005b-43082f4f"></a>
### [api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0`````

<a id="00685cff-43082f4f"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml)
 - **Line 12278, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/team-getallmessages.md'.`````

<a id="de0bbbbb-43082f4f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link [...]

2020-11-09 07:15 UTC, opbld31 commented
Docs Build status updates of commit _[3f59268](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f592687cc466e1fc058d36e70ecb3830785fdaa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-7aec005b-aba7fd8e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-aba7fd8e)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7aec005b-aba7fd8e"></a>
### [api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0`````

<a id="de0bbbbb-aba7fd8e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph- [...]

2020-11-09 07:16 UTC, v-rodriguezd commented on api-reference/beta/api/team-getallmessages.md
> +title: "team: getAllMessages"
Resolved

2020-11-09 07:16 UTC, opbld30 commented
Docs Build status updates of commit _[31fe6a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31fe6a0f1e4d629ae6b029e5f815acc7c51d5ccc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-7aec005b-b81db822)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-b81db822)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7aec005b-b81db822"></a>
### [api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0`````

<a id="de0bbbbb-b81db822"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teams-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph [...]

2020-11-09 07:16 UTC, v-rodriguezd commented on api-reference/beta/api/team-getallmessages.md
> +# team: getAllMessages
Resolved

2020-11-09 07:17 UTC, opbld31 commented
Docs Build status updates of commit _[43dc48e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/43dc48e5f6ea6eb65b784b8bd1aed96d01e385bf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-7aec005b-1dbd4abb)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-1dbd4abb)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7aec005b-1dbd4abb"></a>
### [api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0`````

<a id="de0bbbbb-1dbd4abb"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teams-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph [...]

2020-11-09 07:22 UTC, opbld32 commented
Docs Build status updates of commit _[9df3c50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9df3c501ac2ed644ae6642d2d93321ce1ea66be8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-7aec005b-275e9e68)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-97ee62ac-275e9e68)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-00685cff-275e9e68)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-275e9e68)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7aec005b-275e9e68"></a>
### [api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0`````

<a id="97ee62ac-275e9e68"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md)
 - **Line 36, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-getallmessages.md'.`````

<a id="00685cff-275e9e68"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml)
 - **Line 12398, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chat-getallmessages.md'.`````

<a id="de0bbbbb-275e9e68"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teams-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to th [...]

2020-11-09 07:24 UTC, opbld31 commented
Docs Build status updates of commit _[ee74549](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee745491ce324a6b48e4d71d9c01c5c5ce2aec4b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-7aec005b-23d50a12)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-00685cff-23d50a12)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-23d50a12)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7aec005b-23d50a12"></a>
### [api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0`````

<a id="00685cff-23d50a12"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml)
 - **Line 12398, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chat-getallmessages.md'.`````

<a id="de0bbbbb-23d50a12"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teams-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to  [...]

2020-11-09 07:27 UTC, opbld31 commented
Docs Build status updates of commit _[3d0afd9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d0afd95f782558f1a685260b7bd07040bd79c9b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-7aec005b-26e80630)
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-f9f68dc6-26e80630)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-00685cff-26e80630)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-26e80630)
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7aec005b-26e80630"></a>
### [api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0`````

<a id="f9f68dc6-26e80630"></a>
### [api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md)
 - **Line 39, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-getallmessages.md'.`````

<a id="00685cff-26e80630"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml)
 - **Line 12360, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-getallmessages.md'.`````
 - **Line 12398, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chat-getallmessages.md'.`````

<a id="de0bbbbb-26e80630"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teams-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[S [...]

2020-11-09 07:29 UTC, opbld33 commented
Docs Build status updates of commit _[4ad9117](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ad9117a05f2cd5ebb6befaaa50e09e238d712f9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-7aec005b-fdb2f97b)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-00685cff-fdb2f97b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-fdb2f97b)
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7aec005b-fdb2f97b"></a>
### [api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0`````

<a id="00685cff-fdb2f97b"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml)
 - **Line 12360, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-getallmessages.md'.`````
 - **Line 12398, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chat-getallmessages.md'.`````

<a id="de0bbbbb-fdb2f97b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teams-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingPar [...]

2020-11-09 07:30 UTC, opbld32 commented
Docs Build status updates of commit _[13d9207](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13d920707fd69732cbf070bc177366b3054528ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-7aec005b-23c087aa)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-00685cff-23c087aa)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-23c087aa)
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7aec005b-23c087aa"></a>
### [api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0`````

<a id="00685cff-23c087aa"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml)
 - **Line 12360, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-getallmessages.md'.`````
 - **Line 12398, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chat-getallmessages.md'.`````

<a id="de0bbbbb-23c087aa"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chat-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teams-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingPar [...]

2020-11-09 07:31 UTC, v-rodriguezd commented on api-reference/beta/api/channel-getallmessages.md
> +title: "channel: getAllMessages"
Resolved

2020-11-09 07:31 UTC, opbld34 commented
Docs Build status updates of commit _[93d22ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/93d22ae172f38ed2b35bc4663201173744e134af)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-7aec005b-ab3b9f78)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-00685cff-ab3b9f78)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-ab3b9f78)
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7aec005b-ab3b9f78"></a>
### [api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0`````

<a id="00685cff-ab3b9f78"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml)
 - **Line 12360, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-getallmessages.md'.`````
 - **Line 12398, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chat-getallmessages.md'.`````

<a id="de0bbbbb-ab3b9f78"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chats-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channels-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teams-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingP [...]

2020-11-09 07:32 UTC, v-rodriguezd commented on api-reference/beta/api/chat-getallmessages.md
> +title: "chat: getAllMessages"
Resolved

2020-11-09 07:33 UTC, opbld33 commented
Docs Build status updates of commit _[befe982](https://github.com/microsoftgraph/microsoft-graph-docs/commits/befe98275795ff54372d4c9aab3ec3c176adecef)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-7aec005b-36e6b63b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-36e6b63b)
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7aec005b-36e6b63b"></a>
### [api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0`````

<a id="de0bbbbb-36e6b63b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chats-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channels-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teams-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?v [...]

2020-11-09 07:42 UTC, opbld31 commented
Docs Build status updates of commit _[5b4815a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b4815a0eb54ee4b7f426886d4cccc7cb6807d5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-9b9ebe69)
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-9b9ebe69"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chats-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channels-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teams-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specif [...]

2020-11-10 09:40 UTC, opbld31 commented
Docs Build status updates of commit _[02a22f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02a22f8669384bb34fa0874b74aa94c98162eebc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-795310cd)
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-795310cd"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/chats-getallmessages?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channels-getallmessages?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teams-getallmessages?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specifi [...]

2020-11-12 06:34 UTC, opbld32 commented
Docs Build status updates of commit _[4fb04a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4fb04a869e2c103daf1ed03ceea19f7db23afb99)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9efdd8ba)

<a id="9efdd8ba"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011120633461335-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vdK%2FT9QRcITLD3b74SryKbaND%2FFkC9Kl13G3R%2FbspVg%3D&st=2020-11-12T06%3A29%3A48Z&se=2020-12-13T06%3A34%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 21:42 UTC, opbld31 commented
Docs Build status updates of commit _[b006289](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0062890fc2d3444cf1597760d15e6dc89a7c1ef)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-f9f68dc6-2e05fada)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-97ee62ac-2e05fada)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-00685cff-2e05fada)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-2e05fada)
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) | [Details](#user-content-2cb6e14f-2e05fada)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="f9f68dc6-2e05fada"></a>
### [api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md)
 - **Line 39, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channels-getallmessages.md'.`````

<a id="97ee62ac-2e05fada"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md)
 - **Line 36, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chats-getallmessages.md'.`````

<a id="00685cff-2e05fada"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml)
 - **Line 12457, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channels-getallmessages.md'.`````
 - **Line 12495, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chats-getallmessages.md'.`````

<a id="de0bbbbb-2e05fada"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 420, Column 1**: **[Warning-[merge-conflict](https://aka.ms/merge-conflict)]** `````File contains merge conflict markers.`````
 - **Line 421, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '| Change type | Version   | Description                          |
| :-------------- | :------------ | :--------------------------------------- |
| Addition | beta | Added the b2cIdentityUserFlow entity for managing user flows in an Azure Active Directory B2C tenant. |
| Addition | beta | Added the b2xIdentityUserFlow entity for managing self-service sign up user flows in an Azure Active Directory tenant. |
<<<<<<< HEAD') are not allowed. You can only have one top-level heading.
`````

<a id="2cb6e14f-2e05fada"></a>
### [concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md)
 - **Line 46, Column 46**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#october-2020' in 'changelog.md', did you mean '#october-2016'?`````
 - **Line 73, Column 41**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#october-2020' in 'changelog.md', did you mean '#october-2016'?`````
 - **Line 76, Column 8**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#october-2020' in 'changelog.md', did you mean '#october-2016'?`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011122140091114-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bSwyoNWR0eTUf8fwgOZum1XU0JQ7nQeJ%2FVZYwkBk18M%3D&st=2020-11-12T21%3A37%3A14Z&se=2020-12-13T21%3A42%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-o [...]

2020-11-12 21:59 UTC, opbld33 commented
Docs Build status updates of commit _[acf8f96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/acf8f96a628a0cb3982e2050a07852abcc0a5efc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) | [Details](#user-content-2cb6e14f-cfae42b5)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |

<a id="2cb6e14f-cfae42b5"></a>
### [concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md)
 - **Line 47, Column 46**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#october-2020' in 'changelog.md', did you mean '#october-2016'?`````
 - **Line 74, Column 41**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#october-2020' in 'changelog.md', did you mean '#october-2016'?`````
 - **Line 77, Column 8**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#october-2020' in 'changelog.md', did you mean '#october-2016'?`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011122157491435-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OCRkDrajmPy28Xx8pbErKbw94dXscDvnj397au5Cc%2F4%3D&st=2020-11-12T21%3A54%3A04Z&se=2020-12-13T21%3A59%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-14 00:49 UTC, opbld32 commented
Docs Build status updates of commit _[f3fae95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3fae9536b6b24ccd2b5710b6c1778239c805ea7)_: 

:clock10: **Pending**: waiting for processors ([20](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 20 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-14 00:55 UTC, opbld34 commented
Docs Build status updates of commit _[2aea665](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2aea665265320d5ac5f4faaa0ad75be316dfd240)_: 

:clock10: **Pending**: waiting for processors ([31](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 31 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-14 01:08 UTC, opbld33 commented
Docs Build status updates of commit _[aed8e9d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aed8e9d1e0fc82a0eb0b2ef8c945268bc128b469)_: 

:clock10: **Pending**: waiting for processors ([82](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 82 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-15 02:56 UTC, opbld33 commented
Docs Build status updates of commit _[f3fae95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3fae9536b6b24ccd2b5710b6c1778239c805ea7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-52391b22)

<a id="52391b22"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011140049341633-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2lr%2FdFlzCLUFLKcxVvbiA6uypUkUAmpwHIVsDVqO5bs%3D&st=2020-11-15T02%3A51%3A39Z&se=2020-12-16T02%3A56%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 04:52 UTC, opbld32 commented
Docs Build status updates of commit _[2469e14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2469e1442e7bd4599ae7799710778f843f60d437)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-7d5960fa)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

<a id="de0bbbbb-7d5960fa"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011160451178071-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BGYcnLrW8mfwqHr2heZIPEge1wVQmB4giANebbz7%2FMg%3D&st=2020-11-16T04%3A47%3A35Z&se=2020-12-17T04%3A52%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 07:45 UTC, opbld34 commented
Docs Build status updates of commit _[46d247c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46d247c9cb49b91da69dc2aac2a5f66cd9f041b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-5a0d7931)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

<a id="de0bbbbb-5a0d7931"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/organizationalbrandingproperties?view=graph-rest-beta&preservetrue-view=`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011160744473598-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RBjzHovh7JLkT9RuCjKfxraqiymiG9dBn%2FNSaV7VH%2Fo%3D&st=2020-11-16T07%3A40%3A56Z&se=2020-12-17T07%3A45%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 07:53 UTC, opbld31 commented
Docs Build status updates of commit _[0ff7fd0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ff7fd0dc9bc1bd9e0157e4fe149a38e46d74dbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011160751102464-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gw5SwLZhAoxT%2F6EitC5oZASs5CvfEnWF8UoDrlO2rNE%3D&st=2020-11-16T07%3A48%3A10Z&se=2020-12-17T07%3A53%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 19:04 UTC, nkramer commented on concepts/changelog.md
> +|Addition|beta|Added the **allowInvitesFrom** property to the [authorizationPolicy](/graph/api/resources/authorizationpolicy?view=graph-rest-beta&preserve-view=true) resource.|
Doesn't look like it.

2020-11-17 19:05 UTC, nkramer commented on api-reference/beta/resources/chatmessage.md
> -|**1:1 and group chat messages**| | |
Don't delete that.

2020-11-18 04:08 UTC, v-rodriguezd commented on api-reference/beta/resources/chatmessage.md
> -|**1:1 and group chat messages**| | |
Resolved

2020-11-18 04:09 UTC, opbld33 commented
Docs Build status updates of commit _[a2f38c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2f38c934c846638847309788848494088c2037b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-72ae5724)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

<a id="de0bbbbb-72ae5724"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-onboarding-devicecomanagementauthorityconfiguration?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationcategory?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingcollectiondefinition?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingdefinition?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicy?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicyassignment?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsetting?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettingdefinition?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettinggroupcollectiondefinition?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettinggroupdefinition?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsimplesettingcollectiondefinition?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsimplesettingdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingcollectioninstance?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettinginstance?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingvalue?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specifi [...]

2020-11-18 19:00 UTC, opbld33 commented
Docs Build status updates of commit _[4889e02](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4889e02d5cab035d77c55069d389e62176ebec43)_: 

:clock10: **Pending**: waiting for processors ([27](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 27 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-18 19:02 UTC, opbld34 commented
Docs Build status updates of commit _[4889e02](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4889e02d5cab035d77c55069d389e62176ebec43)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-a83fbdf9-48a86a28)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-00685cff-48a86a28)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-48a86a28)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

<a id="a83fbdf9-48a86a28"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md)
 - **Line 39, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teams-getallmessages.md'.`````

<a id="00685cff-48a86a28"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml)
 - **Line 12413, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teams-getallmessages.md'.`````

<a id="de0bbbbb-48a86a28"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-onboarding-devicecomanagementauthorityconfiguration?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationcategory?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingcollectiondefinition?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingdefinition?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicy?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicyassignment?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsetting?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettingdefinition?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettinggroupcollectiondefinition?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettinggroupdefinition?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsimplesettingcollectiondefinition?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsimplesettingdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingcollec [...]

2020-11-19 03:22 UTC, v-rodriguezd commented on concepts/changelog.md
> +|Addition|beta|Added the **allowInvitesFrom** property to the [authorizationPolicy](/graph/api/resources/authorizationpolicy?view=graph-rest-beta&preserve-view=true) resource.|
I did not understand should I remove "&preserve-view=true" from the changelog.

2020-11-19 03:51 UTC, v-rodriguezd commented on concepts/changelog.md
> +|Addition|beta|Added the **allowInvitesFrom** property to the [authorizationPolicy](/graph/api/resources/authorizationpolicy?view=graph-rest-beta&preserve-view=true) resource.|
> I did not understand should I remove "&preserve-view=true" from the changelog.

Should I remove it from all changelog entries. I have a backup copy of the file. I can change it back. Thank you.

2020-11-20 02:14 UTC, Lauragra commented on concepts/changelog.md
> +|Addition|beta|Added the **allowInvitesFrom** property to the [authorizationPolicy](/graph/api/resources/authorizationpolicy?view=graph-rest-beta&preserve-view=true) resource.|
> > I did not understand should I remove "&preserve-view=true" from the changelog.
> 
> Should I remove it from all changelog entries? Thank you.

Please do not remove the &preserve-view=true parameter from the links.

2020-11-20 04:39 UTC, opbld34 commented
Docs Build status updates of commit _[128d280](https://github.com/microsoftgraph/microsoft-graph-docs/commits/128d28074d345e03f26117d52356b52d02331ffb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-00685cff-d9c6eea3)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

<a id="00685cff-d9c6eea3"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml)
 - **Line 12409, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teams-getallmessages.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011200438178210-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HJtK97Wg7b7qgxi9Z83JigMbGYia3oYVih1P1g063cI%3D&st=2020-11-20T04%3A34%3A45Z&se=2020-12-21T04%3A39%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 04:42 UTC, opbld34 commented
Docs Build status updates of commit _[c308da9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c308da93420b7e4de268a22378600e86d0087039)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011200440598106-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OSb1rLPJiwlAUlmaCY3zsFRF0iITJ7jmJUoZIENA%2FoU%3D&st=2020-11-20T04%3A37%3A19Z&se=2020-12-21T04%3A42%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 05:41 UTC, opbld33 commented
Docs Build status updates of commit _[6a54e6a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a54e6ae59377a6a4173fcaa3af404a7d00f6393)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011200539454171-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rLas5tJs0Tk5fALbB2VngikGp1w%2FAzyxymL4JALF%2FbM%3D&st=2020-11-20T05%3A36%3A03Z&se=2020-12-21T05%3A41%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 05:42 UTC, opbld34 commented
Docs Build status updates of commit _[ec0561a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec0561a8db6deca3c089907eb0e5aab50dfdc70c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011200540160531-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=H4kQ8aRIoZafWH7xEgCLA%2BaE0FzF6%2BgF3iJNKWXsC8I%3D&st=2020-11-20T05%3A37%3A43Z&se=2020-12-21T05%3A42%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 06:13 UTC, opbld30 commented
Docs Build status updates of commit _[aa63829](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa63829e9ced17256afcfb707afc747ff6786f8e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011200612200216-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=poXnp61JWLCu51S2xiKFKnWJq6sA4Vd8mzTXkrs%2BEpw%3D&st=2020-11-20T06%3A08%3A42Z&se=2020-12-21T06%3A13%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 06:18 UTC, opbld32 commented
Docs Build status updates of commit _[e562ac2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e562ac2fabc0a7401945c2061e2f9c9dc54c259a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011200616569319-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MBU7vx1I7vLTLASp2iDrKjOPkJIUS6TmtMI%2FNwD%2BnUc%3D&st=2020-11-20T06%3A13%3A45Z&se=2020-12-21T06%3A18%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 06:23 UTC, v-rodriguezd commented on concepts/changelog.md
> +|Addition|beta|Added the **allowInvitesFrom** property to the [authorizationPolicy](/graph/api/resources/authorizationpolicy?view=graph-rest-beta&preserve-view=true) resource.|
> > > I did not understand should I remove "&preserve-view=true" from the changelog.
> > 
> > 
> > Should I remove it from all changelog entries? Thank you.
> 
> Please do not remove the &preserve-view=true parameter from the links.

Noted Thank you.

2020-11-23 06:02 UTC, opbld32 commented
Docs Build status updates of commit _[8c7ad8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c7ad8a0b982ecac1443f19d1159a1c9b33e2fb9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscoverycase-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/ediscoverycase-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-post?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-f03fc281-2467fd92)
[api-reference/beta/api/ediscoverycase-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/ediscoverycase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-update?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-6bb5760f-2467fd92)
[api-reference/beta/api/educationalactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/educationalactivity-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-get?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-e82c98d3-2467fd92)
[api-reference/beta/api/educationalactivity-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/educationalactivity-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-update?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-c8045151-2467fd92)
[api-reference/beta/api/ediscoverycase-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/ediscoverycase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-list?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-686f0a31-2467fd92)
[api-reference/beta/api/ediscoverycase-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/ediscoverycase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-delete?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-0cf87949-2467fd92)
[api-reference/beta/api/educationalactivity-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/educationalactivity-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-delete?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-591908b5-2467fd92)
[api-reference/beta/api/ediscoverycase-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/ediscoverycase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-get?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-07b05d2b-2467fd92)
[api-reference/v1.0/api/driveitem-restore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/v1.0/api/driveitem-restore.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-restore?view=graph-rest-1.0&branch=pr-en-us-10174) (>= graph-rest-1.0) | [Details](#user-content-6b881ac2-2467fd92)
[api-reference/beta/api/itemphone-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/itemphone-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itemphone-update?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-46c5807d-2467fd92)
[api-reference/beta/api/languageproficiency-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/languageproficiency-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/languageproficiency-get?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-97109511-2467fd92)
[api-reference/beta/api/organizationsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/organizationsettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationsettings-get?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-e0a26c07-2467fd92)
[api-reference/beta/api/itemphone-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/itemphone-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itemphone-delete?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-8477caa6-2467fd92)
[api-reference/beta/api/itempublication-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/itempublication-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itempublication-get?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-fa65ab22-2467fd92)
[api-reference/beta/api/personannotation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/personannotation-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/personannotation-delete?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-3dec620d-2467fd92)
[api-reference/beta/api/personannotation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/personannotation-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/personannotation-update?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-6f7da3b8-2467fd92)
[api-reference/beta/api/itempublication-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/itempublication-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itempublication-update?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-8c4f5685-2467fd92)
[api-reference/beta/api/profile-post-emails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/profile-post-emails.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profile-post-emails?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-38299d34-2467fd92)
[api-reference/beta/api/personresponsibility-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/personresponsibility-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/personresponsibility-get?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-12fba2a9-2467fd92)
[api-reference/beta/api/personaward-get.md](htt [...]

2020-11-26 06:25 UTC, opbld33 commented
Docs Build status updates of commit _[9019fe0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9019fe0431221858c968603b6eb0922ccbea58e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011260623418815-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=64d4O3MA1tg2SSfrM7t5wy1AkGwDiHDBD7uQ5DROunM%3D&st=2020-11-26T06%3A20%3A13Z&se=2020-12-27T06%3A25%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-26 09:09 UTC, opbld33 commented
Docs Build status updates of commit _[7712c87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7712c87f5811552285544f295a5ff26175285872)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011260907437540-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ujJ5kpNp2fp2YTnN0RNO%2B5Als5GX24qH0RFtyvKx3TU%3D&st=2020-11-26T09%3A03%3A59Z&se=2020-12-27T09%3A08%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-30 19:47 UTC, laujan commented
Hi @AkJo. Can we merge this PR?

2020-12-01 05:25 UTC, opbld32 commented
Docs Build status updates of commit _[ef35d75](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ef35d75c07aaf96b516fca57fb9503b74bf1caec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-87317b90)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

<a id="de0bbbbb-87317b90"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participantInfo?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012010524354088-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=a85zb2DPY%2FHckASYAj7golike1DT05tn8z%2Br60qjFAE%3D&st=2020-12-01T05%3A20%3A52Z&se=2021-01-01T05%3A25%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-01 05:26 UTC, Lauragra commented on api-reference/beta/api/chat-getallmessages.md
> +|Application | Chat.Read.All |
All permissions tables need to include the three rows - this table is missing Delegated (work or school account) and Delegated (personal Microsoft account). Please add.

2020-12-01 05:29 UTC, opbld34 commented
Docs Build status updates of commit _[fb67a42](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb67a4212f08e5c564052cff6d3f48fad3bff423)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-0623e4a3)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

<a id="de0bbbbb-0623e4a3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participantInfo?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012010528224039-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BTYOonvFDkXgwRmWfKOWKTy1ET6C7ySrnxSgzleDt1w%3D&st=2020-12-01T05%3A24%3A51Z&se=2021-01-01T05%3A29%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-01 05:31 UTC, opbld34 commented
Docs Build status updates of commit _[024d7fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/024d7fa7cdadc85a1713fbc66ecbb7f56cee3c8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-98a8c43b)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

<a id="de0bbbbb-98a8c43b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participantInfo?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012010530203257-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CLLbxq63IdbH0A0vG6coTIGvMCyN6NLjkyILzwedgHo%3D&st=2020-12-01T05%3A26%3A43Z&se=2021-01-01T05%3A31%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-01 05:33 UTC, opbld31 commented
Docs Build status updates of commit _[024d7fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/024d7fa7cdadc85a1713fbc66ecbb7f56cee3c8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-07ab5029)
[api-reference/beta/api/channel-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channel-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chat-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chat-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/team-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/team-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

<a id="de0bbbbb-07ab5029"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participantInfo?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012010530305508-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tOfGETUPLc4srERnQKeh51b8IjwnLW%2FEf59ZugEZmys%3D&st=2020-12-01T05%3A28%3A00Z&se=2021-01-01T05%3A33%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-01 05:34 UTC, Lauragra commented on api-reference/beta/api/team-getallmessages.md
> +This resource is used to create webhooks to get notifications for all messages across all teams in an organization. Please refer [Webhooks](../resources/webhooks.md).
This description is not clear. This is a function, not a resource type. According to the webhooks topic that this is linking to, this function gets "Changes to chat messages in all channels in all teams". Please clarify.

2020-12-01 05:36 UTC, Lauragra commented on api-reference/beta/resources/team.md
> +|[Get all team messages](../api/team-getallmessages.md) | [team](team.md) | Get all messages from teams that a user is a participant in.|
We're linking to the team-getallmessages function here but that function topic content does not match the description.

2020-12-01 06:19 UTC, KirtiPereira commented on api-reference/beta/api/chat-getallmessages.md
> +|Application | Chat.Read.All |
Hi @laujan, @AkJo - The information provided was as follows. 

![image](https://user-images.githubusercontent.com/70375155/100704160-03333f80-33cb-11eb-82df-0416b593ee0c.png)

Kindly clarify if for Delegated (work or school account) and Delegated (personal Microsoft account).
Thank you.

2020-12-01 07:50 UTC, KirtiPereira commented on api-reference/beta/api/team-getallmessages.md
> +This resource is used to create webhooks to get notifications for all messages across all teams in an organization. Please refer [Webhooks](../resources/webhooks.md).
Hi @laujan, @AkJo - kindly confirm if I can update as suggested by Laura. The current content is as per input below.

![image](https://user-images.githubusercontent.com/70375155/100711160-e69d0480-33d6-11eb-91f1-80d9d42f1f89.png)

Thank you.

2020-12-01 10:13 UTC, KirtiPereira commented on api-reference/beta/resources/team.md
> +|[Get all team messages](../api/team-getallmessages.md) | [team](team.md) | Get all messages from teams that a user is a participant in.|
@laujan, @AkJo - Will update the description post confirmation on the above comment for team-getallmessages.md file content.
Thank you.

2020-12-03 08:08 UTC, AkJo commented on api-reference/beta/api/channel-getallmessages.md
> +title: "channel: getAllMessages"
I do not see the suggested change. 

The file is still named incorrectly as 'channel-getallmessages' instead of 'channels-getallmessages'.

2020-12-03 08:10 UTC, AkJo commented on api-reference/beta/api/channel-getallmessages.md
> +Retrieve all [messages](../resources/chatmessage.md) in a [team](../resources/team.md) [channel](../resources/channel.md) including text, audio, and video conversations.
Retrieve all [messages](../resources/chatmessage.md)  across all [channels](../resources/channel.md) in a [team](../resources/team.md) including text, audio, and video conversations.

2020-12-03 08:11 UTC, AkJo commented on api-reference/beta/api/channel-getallmessages.md
> +            "@odata.id": "https://graph.microsoft.com/beta/teams/ab5332ba-6dd9-46d3-ade5-5c61a2f148b2/channels/19%3A72409da00b014de5ba2d2bef4a44db09%40thread.tacv2/messages/1580768557513",
Please fix indentation.

2020-12-03 08:12 UTC, AkJo commented on api-reference/beta/api/chat-getallmessages.md
> +title: "chat: getAllMessages"
I still dont see the suggested changes applied to title and file name.

2020-12-03 08:13 UTC, AkJo commented on api-reference/beta/api/chat-getallmessages.md
> +|Application | Chat.Read.All |
@KirtiPereira , the API is supported in the application context, but you will still need to list down the rows for Delegated (work or school account) and Delegated (personal Microsoft account) and specify 'Not supported' for each of them.

2020-12-03 08:14 UTC, AkJo commented on api-reference/beta/api/team-getallmessages.md
> +title: "team: getAllMessages"
Same comment here.

2020-12-03 08:28 UTC, AkJo commented on api-reference/beta/api/team-getallmessages.md
> +This resource is used to create webhooks to get notifications for all messages across all teams in an organization. Please refer [Webhooks](../resources/webhooks.md).
Sure. The text can be updated to 

"This function is used to create webhooks to get change notifications for all messages across all channels across all teams in an organization. Please refer to [Webhooks](../resources/webhooks.md)."

2020-12-03 08:32 UTC, AkJo commented on api-reference/beta/api/channel-getallmessages.md
> +description: "Retrieve all messages in a team channel."
Retrieve all messages across all channels in a team.

2020-12-03 08:32 UTC, AkJo commented on api-reference/beta/resources/channel.md
> +|[Create chatMessage in a channel](../api/channel-post-message.md) | [chatMessage](../resources/chatmessage.md) | Send a message to a channel. |
None of these changes should be happening in this file. 


The only change in this file in this PR should be an addition:

|[Get all channel messages](../api/channels-getallmessages.md)|[channel](channel.md) collection | Get all messages from all channels in a team. |

2020-12-03 08:34 UTC, AkJo commented on api-reference/beta/resources/team.md
> +|[Get all team messages](../api/team-getallmessages.md) | [team](team.md) | Get all messages from teams that a user is a participant in.|
teams-getallmessages.md

2020-12-03 08:35 UTC, AkJo commented on api-reference/beta/api/team-getallmessages.md
> +description: "Get messages from teams that a user is a participant in."
"Get all messages from all channels across all teams in the organization"

2020-12-03 08:38 UTC, AkJo commented on api-reference/beta/resources/team.md
> +|[Get all team messages](../api/team-getallmessages.md) | [team](team.md) | Get all messages from teams that a user is a participant in.|
"Get all messages from all channels across all teams in the organization"

OR

"Created webhooks to get all messages from all channels across all teams in the organization"

The detail that this can be used for only creating webhook can be left out in this table view and surfaced only in the teams-getallmessages.md page. I do not have a strong preference for either.

2020-12-03 08:39 UTC, AkJo commented on api-reference/beta/toc.yml
> +          href: api/conversationmember-add.md
None of these changes should be happening.


The only change in this PR should be restricted to x-getallmessages.md

2020-12-03 08:39 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: Get all team messages
Get messages across all teams

2020-12-03 08:40 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: Get all channel messages
Get messages across all channels

2020-12-03 08:40 UTC, AkJo commented on api-reference/beta/toc.yml
> +          href: api/channel-getallmessages.md
channels

2020-12-03 08:40 UTC, AkJo commented on api-reference/beta/toc.yml
> +          href: api/team-getallmessages.md
teams

2020-12-03 08:41 UTC, AkJo commented on concepts/changelog.md
> +| Addition | beta | Added the [getAllMessages](/graph/api/chat-getallmessages?view=graph-rest-beta&preserve-view=true) method to the [chatmessage](/graph/api/resources/chatmessage?view=graph-rest-bet
chat

2020-12-03 08:41 UTC, AkJo commented on concepts/changelog.md
> +| Addition | beta | Added the [getAllMessages](/graph/api/chat-getallmessages?view=graph-rest-beta&preserve-view=true) method to the [chatmessage](/graph/api/resources/chatmessage?view=graph-rest-bet
chat

2020-12-03 08:42 UTC, AkJo commented on concepts/changelog.md
> +|Addition|beta|Added resource types [accessReviewApplyAction](/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&preserve-view=true), [accessReviewInstance](/graph/api/resources/access
Not sure what is going on over here. But ideally, these should not have been touched.

2020-12-03 08:50 UTC, AkJo commented on changelog/Microsoft.Teams.Core.json
> +            "Description": "Added the [getAllMessages](https://docs.microsoft.com/en-us/graph/api/chat-getallmessages?view=graph-rest-beta) method to the [chatmessage](https://docs.microsoft.com/en-u
chat

2020-12-03 08:57 UTC, AkJo commented on api-reference/beta/resources/chatmessage.md
> +|[Get all chat messages](../api/chat-getallmessages.md)| [chatMessage](../resources/chatmessage.md) collection| Get messages from all chats that a user is a participant in, including one-on-one chats
Technically, this entry belongs in the chat.md file since the function has been added to the chat resource.

2020-12-03 09:56 UTC, AkJo commented on api-reference/beta/api/chat-getallmessages.md
> +|Application | Chat.Read.All |
Chat.Read.All, Chat.ReadWrite.All

2020-12-03 10:12 UTC, KirtiPereira commented on api-reference/beta/resources/chatmessage.md
> +|[Get all chat messages](../api/chat-getallmessages.md)| [chatMessage](../resources/chatmessage.md) collection| Get messages from all chats that a user is a participant in, including one-on-one chats
Moved the entry to chat.md.

2020-12-03 10:46 UTC, KirtiPereira commented on api-reference/beta/resources/team.md
> +|[Get all team messages](../api/team-getallmessages.md) | [team](team.md) | Get all messages from teams that a user is a participant in.|
Have taken the first description "Get all messages from all channels across all teams in the organization.".

2020-12-03 11:03 UTC, KirtiPereira commented on api-reference/beta/toc.yml
> +          href: api/conversationmember-add.md
Removed the following from the beta "toc.yml".
 "Add a member" "Remove a member from a channel", and "Update the role of a member in channel"

2020-12-03 11:21 UTC, KirtiPereira commented on concepts/changelog.md
> +|Addition|beta|Added resource types [accessReviewApplyAction](/graph/api/resources/accessreviewapplyaction?view=graph-rest-beta&preserve-view=true), [accessReviewInstance](/graph/api/resources/access
Agree, it should not be touched. This is related to conflict resolution.

2020-12-03 13:33 UTC, opbld33 commented
Docs Build status updates of commit _[0b82fb3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b82fb3574eef93283e9f057494fe34dce21a632)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-638d8d81)
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

<a id="de0bbbbb-638d8d81"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 14, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Changelog for Microsoft Graph'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012031138206636-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yGyMJMwKa8ekJcNdeeR%2FQTiLTe7ZdtwbCnmoZk0n80s%3D&st=2020-12-03T13%3A28%3A42Z&se=2021-01-03T13%3A33%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-03 13:36 UTC, opbld30 commented
Docs Build status updates of commit _[b4f1793](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4f1793541569da4636ff7cd056abfd6736faa84)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-fcec592b)
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

<a id="de0bbbbb-fcec592b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 14, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Changelog for Microsoft Graph'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012031334009033-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vs0OoELS%2BuHwZBYxqsL8yD6Q51xeRPxNaNKUWY%2BxYiI%3D&st=2020-12-03T13%3A31%3A14Z&se=2021-01-03T13%3A36%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-03 20:53 UTC, laujan commented
Hi @Lauragra. This PR is ready-to-merge?

2020-12-03 21:20 UTC, AkJo commented on api-reference/beta/api/chats-getallmessages.md
> +GET https://graph.microsoft.com/beta/users/{id}/chats/getAllMessages
Please do not use place holder values in examples.


https://graph.microsoft.com/beta/users/8b081ef6-4792-4def-b2c9-c363a1bf41d5/chats/getAllMessages

2020-12-03 21:21 UTC, AkJo commented on api-reference/beta/resources/channel.md
> +|[Get files folder](../api/driveitem-get.md)| [driveItem](driveitem.md) | Retrieves the details of the SharePoint folder where the files for the channel are stored. |
Same comment as before. Why are we introducing these additions and creating duplicates that are not related to this PR?

2020-12-03 21:22 UTC, AkJo commented on concepts/changelog.md
> +| Addition | beta | Added the [getAllMessages](/graph/api/chats-getallmessages?view=graph-rest-beta&preserve-view=true) method to the [chat](/graph/api/resources/chat?view=graph-rest-beta&preserve-vi
resource collection.

2020-12-03 21:22 UTC, AkJo commented on concepts/changelog.md
> +| Addition | beta | Added the [getAllMessages](/graph/api/channels-getallmessages?view=graph-rest-beta&preserve-view=true) method to the [channel](/graph/api/resources/channel?view=graph-rest-beta&pr
resource collection.

2020-12-03 21:22 UTC, AkJo commented on concepts/changelog.md
> +| Addition | beta | Added the [getAllMessages](/graph/api/teams-getallmessages?view=graph-rest-beta&preserve-view=true) method to the [team](/graph/api/resources/team?view=graph-rest-beta&preserve-vi
resource collection.

2020-12-03 21:23 UTC, AkJo commented on changelog/Microsoft.Teams.Core.json
> +            "Description": "Added the [getAllMessages](https://docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta) method to the [team](https://docs.microsoft.com/en-us/grap
type collection.

2020-12-03 21:23 UTC, AkJo commented on changelog/Microsoft.Teams.Core.json
> +            "Description": "Added the [getAllMessages](https://docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta) method to the [channel](https://docs.microsoft.com/en-u
type collection.

2020-12-03 21:23 UTC, AkJo commented on changelog/Microsoft.Teams.Core.json
> +            "Description": "Added the [getAllMessages](https://docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta) method to the [chat](https://docs.microsoft.com/en-us/grap
type collection.

2020-12-04 00:40 UTC, Lauragra commented on api-reference/beta/api/teams-getallmessages.md
> +This function is used to create webhooks to get change notifications for all messages across all teams in an organization. Please refer to [Webhooks](../resources/webhooks.md).
Please apply the standard structure for API topics here and explain how this function is used for change notifications. Also, the cross-reference should likely point to this topic, which covers subscribing to messages across all channels: https://docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage.

2020-12-04 04:47 UTC, KirtiPereira commented on api-reference/beta/resources/channel.md
> +|[Get files folder](../api/driveitem-get.md)| [driveItem](driveitem.md) | Retrieves the details of the SharePoint folder where the files for the channel are stored. |
These entries were there when I started working on this PR. Removed them.

2020-12-04 07:01 UTC, KirtiPereira commented on api-reference/beta/api/teams-getallmessages.md
> +This function is used to create webhooks to get change notifications for all messages across all teams in an organization. Please refer to [Webhooks](../resources/webhooks.md).
@AkJo - Please confirm on the changes suggested above w.r.t. cross-reference.

Have updated the file as per the standard structure for API topics. Can these sections be empty? If not please provide inputs for the sections as listed below.
- Any change in / additional description of the API?
- Permissions for teams-getallmessages API would be as follows?
![image](https://user-images.githubusercontent.com/70375155/101129618-f1020d00-3627-11eb-8873-3e21fc0f294c.png)
- Also, would require inputs on the HTTP request and Example sections. 

Thank you.

2020-12-04 07:17 UTC, opbld31 commented
Docs Build status updates of commit _[677dc11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/677dc1190a244e20f9c4ab07380b9bd6cac4857f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/teams-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/teams-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teams-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012040715185556-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WrqS0%2F3s968O%2FzWivcOOzp2Ym%2FYoomrTqG4QcOoop7k%3D&st=2020-12-04T07%3A12%3A58Z&se=2021-01-04T07%3A17%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 14:29 UTC, opbld32 commented
Docs Build status updates of commit _[38300a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/38300a582334fb5c467c436a94d38dc7029f1c73)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-a83fbdf9-2a9e1759)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-00685cff-2a9e1759)
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

<a id="a83fbdf9-2a9e1759"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md)
 - **Line 40, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teams-getallmessages.md'.`````

<a id="00685cff-2a9e1759"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml)
 - **Line 12474, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teams-getallmessages.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012041427320267-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3c%2F7qko4uvvEy2UOHxLKpX%2FRgQZXFDXxx0ciMxUGTEU%3D&st=2020-12-04T14%3A23%3A59Z&se=2021-01-04T14%3A28%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 14:33 UTC, opbld32 commented
Docs Build status updates of commit _[ea259f4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea259f4698651728da86cf1a025ee83d2d9b0f08)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-a83fbdf9-4cfb8909)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) | [Details](#user-content-00685cff-4cfb8909)
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

<a id="a83fbdf9-4cfb8909"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/team.md)
 - **Line 40, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teams-getallmessages.md'.`````

<a id="00685cff-4cfb8909"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml)
 - **Line 12474, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teams-getallmessages.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012041431589642-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=k9cup5wJQsH%2F%2BfIGF3PolFvIb4u76eLlPHZWxzCHR1s%3D&st=2020-12-04T14%3A28%3A24Z&se=2021-01-04T14%3A33%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 19:03 UTC, opbld31 commented
Docs Build status updates of commit _[3e48dc7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e48dc7b3b761ad6a628052df2ace4bfc1d7a665)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012041901506820-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=u06uElxaPBPz6O0KanowqyXHHanViXJWQ%2B2WIJJkpCw%3D&st=2020-12-04T18%3A58%3A08Z&se=2021-01-04T19%3A03%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 19:57 UTC, AkJo commented on api-reference/beta/resources/channel.md
> +|[Complete migration](../api/channel-completemigration.md)|[channel](channel.md)| Removes thee migration mode from the channel and makes the channel available to users to post and read messages.|
nit: It there any reason why this is being moved up in the list of rows? It just feel odds that we are talking about messages, and then abruptly stick this line in about migration?

2020-12-04 20:07 UTC, opbld34 commented
Docs Build status updates of commit _[ba75f1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba75f1e52d7b1efe245f455b115159a44d9a5e42)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012042005170985-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=L5rMD0OmpUf3urjY4kkonSVCWEanrLfWJi75wY1dnOE%3D&st=2020-12-04T20%3A02%3A11Z&se=2021-01-04T20%3A07%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 20:15 UTC, laujan commented
Hi @Lauragra. Anand recommended that we delete the non-conforming page, and he has signed off on the PR. Ready-to-merge?

2020-12-07 10:04 UTC, opbld30 commented
Docs Build status updates of commit _[f04e6b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f04e6b5658569b82c3fe7a76760506d8506dd6f4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071002456112-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UaY3ptA%2FSlScMmFPj1z8hos3QkRLMjtwP7Fey3dVN6Q%3D&st=2020-12-07T09%3A59%3A09Z&se=2021-01-07T10%3A04%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 18:53 UTC, laujan commented
Hi @Lauragra. This is ready-to-merge. 🙂

2020-12-08 01:20 UTC, AkJo commented on api-reference/beta/resources/channel.md
> +|[Complete migration](../api/channel-completemigration.md)|[channel](channel.md)| Removes thee migration mode from the channel and makes the channel available to users to post and read messages.|
typo

2020-12-08 01:34 UTC, Lauragra approved these changes

2020-12-08 01:37 UTC, opbld32 commented
Docs Build status updates of commit _[8cee0a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8cee0a10af409c48121d0f7c08733b4fd611b41a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-eb05de1b)
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

<a id="de0bbbbb-eb05de1b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080136171746-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sctE2EXBqDQX3zKauJG%2BDP4d39NGJwAOO%2FlOt6q3j7M%3D&st=2020-12-08T01%3A32%3A55Z&se=2021-01-08T01%3A37%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 01:39 UTC, opbld30 commented
Docs Build status updates of commit _[8b6e26d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b6e26dc00a8fd25d6d84d30d34cd1d9923395d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10174) | [Details](#user-content-de0bbbbb-a7a372e1)
[api-reference/beta/api/channels-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/channels-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/api/chats-getallmessages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channels-getallmessages?view=graph-rest-beta&branch=pr-en-us-10174) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-10174) |

<a id="de0bbbbb-a7a372e1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/v-rodriguezd-1212884ExportMessagesAPI/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080137024673-10174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eqIOPqyKkK2ogSZc6AL8zeV3UmRxsJkGFnbwcscbBCY%3D&st=2020-12-08T01%3A34%3A11Z&se=2021-01-08T01%3A39%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 02:39 UTC, merged