$filter for companyName + v1.0 docs for Advanced Queries on /users
microsoftgraph/microsoft-graph-docs pull request #10184
Opened 2020-10-05 18:48 UTC by YannickRe

Marked companyName as available for $filter (since it works in Graph Explorer)

Brought the documentation about Advanced Queries on /user from /beta to /v1.0 page, since it is now officially supported according to https://developer.microsoft.com/en-us/office/blogs/microsoft-graph-advanced-queries-for-directory-objects-are-now-generally-available/?WT.mc_id=M365-MVP-5003400

2020-10-05 18:49 UTC, opbld33 commented
Docs Build status updates of commit _[ad58a1a](https://github.com/YannickRe/microsoft-graph-docs/commits/ad58a1ab8955a2213eff20f3a60aa8f520e00000)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-list.md) | :x:Error | | [Details](#user-content-630f74a8-3c91b90c)
[api-reference/v1.0/resources/user.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | | [Details](#user-content-6f302778-3c91b90c)

<a id="630f74a8-3c91b90c"></a>
### [api-reference/v1.0/api/user-list.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-list.md)
 - **Line 271, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-count-only-csharp-snippets.md'.`````
 - **Line 275, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-count-only-javascript-snippets.md'.`````
 - **Line 279, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-count-only-objc-snippets.md'.`````
 - **Line 320, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-a-count-csharp-snippets.md'.`````
 - **Line 324, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-a-count-javascript-snippets.md'.`````
 - **Line 328, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-a-count-objc-snippets.md'.`````
 - **Line 382, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-wa-count-csharp-snippets.md'.`````
 - **Line 386, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-wa-count-javascript-snippets.md'.`````
 - **Line 390, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-wa-count-objc-snippets.md'.`````
 - **Line 261, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 310, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 372, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'List users - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/educationroot-list-users.md(2,8), v1.0/api/intune-shared-user-list.md(2,8), v1.0/api/user-list.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'List users' is duplicated with other articles: 'v1.0/api/educationroot-list-users.md(10,1), v1.0/api/intune-shared-user-list.md(10,1), v1.0/api/user-list.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="6f302778-3c91b90c"></a>
### [api-reference/v1.0/resources/user.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/resources/user.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'user resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-shared-user.md(2,8), v1.0/resources/user.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'user resource type' is duplicated with other articles: 'v1.0/resources/intune-shared-user.md(10,1), v1.0/resources/user.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010051848379059-10184%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xGwMikA1QKMXvEaa%2BTaNjJr43lgxadI5f8DvuylYsZA%3D&st=2020-10-05T18%3A44%3A45Z&se=2020-11-05T18%3A49%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=7 [...]

2020-10-05 19:01 UTC, opbld30 commented
Docs Build status updates of commit _[c1fcba6](https://github.com/YannickRe/microsoft-graph-docs/commits/c1fcba66dc3d1da7f02fff417b8eddd60a6eec5b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-dfa3467d)
[api-reference/v1.0/resources/user.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) | [Details](#user-content-6f302778-dfa3467d)
[api-reference/beta/resources/user.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10184) (graph-rest-beta) |
[api-reference/v1.0/includes/snippets/csharp/get-a-count-csharp-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/csharp/get-a-count-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-count-only-csharp-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/csharp/get-count-only-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-wa-count-csharp-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/csharp/get-wa-count-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-a-count-javascript-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/javascript/get-a-count-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-count-only-javascript-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/javascript/get-count-only-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-wa-count-javascript-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/javascript/get-wa-count-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-a-count-objc-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/objc/get-a-count-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-count-only-objc-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/objc/get-count-only-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-wa-count-objc-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/objc/get-wa-count-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |

<a id="630f74a8-dfa3467d"></a>
### [api-reference/v1.0/api/user-list.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-list.md)
 - **Line 261, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 310, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 372, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'List users - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/educationroot-list-users.md(2,8), v1.0/api/intune-shared-user-list.md(2,8), v1.0/api/user-list.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'List users' is duplicated with other articles: 'v1.0/api/educationroot-list-users.md(10,1), v1.0/api/intune-shared-user-list.md(10,1), v1.0/api/user-list.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="6f302778-dfa3467d"></a>
### [api-reference/v1.0/resources/user.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/resources/user.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=master)]** `````Title 'user resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-shared-user.md(2,8), v1.0/resources/user.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=master)]** `````H1 'user resource type' is duplicated with other articles: 'v1.0/resources/intune-shared-user.md(10,1), v1.0/resources/user.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010051900067952-10184%5Cw [...]

2020-10-05 21:00 UTC, Lauragra commented
@krbain , please review and approve.

2020-10-20 20:51 UTC, opbld31 commented
Docs Build status updates of commit _[666b2ed](https://github.com/YannickRe/microsoft-graph-docs/commits/666b2edc466d5d052161cd6fe4bd5236bf861b03)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-6f744542)
[api-reference/v1.0/resources/user.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) | [Details](#user-content-6f302778-6f744542)
[api-reference/beta/resources/user.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10184) (graph-rest-beta) |
[api-reference/v1.0/includes/snippets/csharp/get-a-count-csharp-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/csharp/get-a-count-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-count-only-csharp-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/csharp/get-count-only-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-wa-count-csharp-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/csharp/get-wa-count-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-a-count-javascript-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/javascript/get-a-count-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-count-only-javascript-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/javascript/get-count-only-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-wa-count-javascript-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/javascript/get-wa-count-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-a-count-objc-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/objc/get-a-count-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-count-only-objc-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/objc/get-count-only-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-wa-count-objc-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/objc/get-wa-count-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |

<a id="630f74a8-6f744542"></a>
### [api-reference/v1.0/api/user-list.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-list.md)
 - **Line 261, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 310, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 372, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List users - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/educationroot-list-users.md(2,8), v1.0/api/intune-shared-user-list.md(2,8), v1.0/api/user-list.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List users' is duplicated with other articles: 'v1.0/api/educationroot-list-users.md(10,1), v1.0/api/intune-shared-user-list.md(10,1), v1.0/api/user-list.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="6f302778-6f744542"></a>
### [api-reference/v1.0/resources/user.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/resources/user.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'user resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-shared-user.md(2,8), v1.0/resources/user.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'user resource type' is duplicated with other articles: 'v1.0/resources/intune-shared-user.md(10,1), v1.0/resources/user.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202049575150-10184%5Cworkflow [...]

2020-10-20 21:42 UTC, angelgolfer-ms commented on api-reference/v1.0/api/user-list.md
> +# [C#](#tab/csharp)
Lines 270-282:
In general, when adding new examples, please exclude these lines, so that the snippets tool can auto-generate the necessary snippets. This comment applies to the few examples in this PR.
If you have specific input for how the language-specific snippets should be, I can loop in @andrueastman for you to directly communicate.

2020-10-20 22:09 UTC, angelgolfer-ms commented on api-reference/v1.0/api/user-list.md
> +This method supports the [OData Query Parameters](/graph/docs/concepts/query_parameters) to help customize the response, including `$search`, `$count`, and `$filter`. You can use `$search` on the **d
Line 34:
Using (/graph/query-parameters) is a "site-relative" link which is the way prescribed by the publishing platform to link from a reference topic to a concept topic. Please change that back.

2020-10-20 22:11 UTC, YannickRe commented on api-reference/v1.0/api/user-list.md
> +This method supports the [OData Query Parameters](/graph/docs/concepts/query_parameters) to help customize the response, including `$search`, `$count`, and `$filter`. You can use `$search` on the **d
@angelgolfer-ms thank you for your time reviewing this, but seems like it is wasted effort as this is a duplicate of #10047

2020-10-20 22:17 UTC, angelgolfer-ms requested changes
@YannickRe , thank you for the PR and updating the v1 docs based on the beta docs!
Please take a look at my couple of minor comments.
If you have specific input about the snippets generated for beta, then please communicate with the referenced snippets generator owner. Otherwise, you can just delete the snippets lines and the new snippet files in this PR. After the PR is published, the weekly snippet generator pass will take care of inserting the corresponding snippet examples.

2020-10-20 22:25 UTC, YannickRe commented
@angelgolfer-ms thank you for your time reviewing this, but seems like it is wasted effort as this is a duplicate of #10047

I don't work for Microsoft and have no knowledge of all of what you said above 🙂. I do not know the snippet owner, I don't understand the snippet generator and how all this stuff works from manual and automated stuff.

I've been bitten by this repository before, and without clear contribution guidelines, it feels like I'm flying blind every time I try to contribute something here. I looked at CONTRIBUTING.md and WIKI, it describes nothing about your linking style or the snippet stuff. I have to adhere to standards that I don't know about.
If it is larger than just fixing a typo, it doesn't feel like it is worth my time/effort and I better "put my limited keystrokes to something else". (paraphrasing Scott Hanselman).

2020-10-21 07:32 UTC, opbld31 commented
Docs Build status updates of commit _[a80b103](https://github.com/YannickRe/microsoft-graph-docs/commits/a80b103291821a7f5b4441ea30a54bb4980966e8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-293b7576)
[api-reference/v1.0/resources/user.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) | [Details](#user-content-6f302778-293b7576)
[api-reference/beta/resources/user.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10184) (graph-rest-beta) |
[api-reference/v1.0/includes/snippets/csharp/get-a-count-csharp-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/csharp/get-a-count-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-count-only-csharp-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/csharp/get-count-only-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-wa-count-csharp-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/csharp/get-wa-count-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-a-count-javascript-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/javascript/get-a-count-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-count-only-javascript-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/javascript/get-count-only-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-wa-count-javascript-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/javascript/get-wa-count-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-a-count-objc-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/objc/get-a-count-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-count-only-objc-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/objc/get-count-only-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-wa-count-objc-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/objc/get-wa-count-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |

<a id="630f74a8-293b7576"></a>
### [api-reference/v1.0/api/user-list.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-list.md)
 - **Line 261, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 310, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 372, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List users - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/educationroot-list-users.md(2,8), v1.0/api/intune-shared-user-list.md(2,8), v1.0/api/user-list.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List users' is duplicated with other articles: 'v1.0/api/educationroot-list-users.md(10,1), v1.0/api/intune-shared-user-list.md(10,1), v1.0/api/user-list.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="6f302778-293b7576"></a>
### [api-reference/v1.0/resources/user.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/resources/user.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'user resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-shared-user.md(2,8), v1.0/resources/user.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'user resource type' is duplicated with other articles: 'v1.0/resources/intune-shared-user.md(10,1), v1.0/resources/user.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010210730468692-10184%5Cworkflow [...]

2020-10-21 07:55 UTC, opbld32 commented
Docs Build status updates of commit _[5affcd4](https://github.com/YannickRe/microsoft-graph-docs/commits/5affcd4d25020f9582f947c76c03bb31d7d367ff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-cf9ae079)
[api-reference/v1.0/api/user-update.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) | [Details](#user-content-93805f46-cf9ae079)
[api-reference/v1.0/resources/user.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) | [Details](#user-content-6f302778-cf9ae079)
[api-reference/beta/api/user-update.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/beta/api/user-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&branch=pr-en-us-10184) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10184) (graph-rest-beta) |
[api-reference/v1.0/includes/snippets/csharp/get-a-count-csharp-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/csharp/get-a-count-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-count-only-csharp-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/csharp/get-count-only-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-wa-count-csharp-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/csharp/get-wa-count-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-a-count-javascript-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/javascript/get-a-count-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-count-only-javascript-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/javascript/get-count-only-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-wa-count-javascript-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/javascript/get-wa-count-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-a-count-objc-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/objc/get-a-count-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-count-only-objc-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/objc/get-count-only-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-wa-count-objc-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/objc/get-wa-count-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |

<a id="630f74a8-cf9ae079"></a>
### [api-reference/v1.0/api/user-list.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-list.md)
 - **Line 261, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 310, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 372, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List users - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/educationroot-list-users.md(2,8), v1.0/api/intune-shared-user-list.md(2,8), v1.0/api/user-list.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List users' is duplicated with other articles: 'v1.0/api/educationroot-list-users.md(10,1), v1.0/api/intune-shared-user-list.md(10,1), v1.0/api/user-list.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="93805f46-cf9ae079"></a>
### [api-reference/v1.0/api/user-update.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update user - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/intune-shared-user [...]

2020-10-21 07:58 UTC, opbld34 commented
Docs Build status updates of commit _[527df50](https://github.com/YannickRe/microsoft-graph-docs/commits/527df509bb22189af229c0a8ff6e1984832a1c90)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) | [Details](#user-content-630f74a8-c3be0353)
[api-reference/v1.0/api/user-update.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) | [Details](#user-content-93805f46-c3be0353)
[api-reference/v1.0/resources/user.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) | [Details](#user-content-6f302778-c3be0353)
[api-reference/beta/api/user-update.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/beta/api/user-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&branch=pr-en-us-10184) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10184) (graph-rest-beta) |
[api-reference/v1.0/includes/snippets/csharp/get-a-count-csharp-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/csharp/get-a-count-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-count-only-csharp-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/csharp/get-count-only-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-wa-count-csharp-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/csharp/get-wa-count-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-a-count-javascript-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/javascript/get-a-count-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-count-only-javascript-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/javascript/get-count-only-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-wa-count-javascript-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/javascript/get-wa-count-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-a-count-objc-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/objc/get-a-count-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-count-only-objc-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/objc/get-count-only-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-wa-count-objc-snippets.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/includes/snippets/objc/get-wa-count-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&branch=pr-en-us-10184) (>= graph-rest-1.0) |

<a id="630f74a8-c3be0353"></a>
### [api-reference/v1.0/api/user-list.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-list.md)
 - **Line 261, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 310, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 372, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List users - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/educationroot-list-users.md(2,8), v1.0/api/intune-shared-user-list.md(2,8), v1.0/api/user-list.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List users' is duplicated with other articles: 'v1.0/api/educationroot-list-users.md(10,1), v1.0/api/intune-shared-user-list.md(10,1), v1.0/api/user-list.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="93805f46-c3be0353"></a>
### [api-reference/v1.0/api/user-update.md](https://github.com/YannickRe/microsoft-graph-docs/blob/update-docs-for-advanced-queries-on-users/api-reference/v1.0/api/user-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update user - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/intune-shared-user [...]

2020-11-18 09:10 UTC, YannickRe commented
Closing since a this is a (more limited) duplicate of #10047 which has been merged.

2020-11-18 09:10 UTC, closed without merging