1149664 tabs api for chats and meetings (beta)
microsoftgraph/microsoft-graph-docs pull request #10199
Opened 2020-10-06 20:54 UTC by laujan

2020-10-06 20:55 UTC, opbld33 commented
Docs Build status updates of commit _[cd43899](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd438996699d5f532235fafa5b033800026ef3ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-5000eae2-0e4ffc7e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-0e4ffc7e)
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="5000eae2-0e4ffc7e"></a>
### [api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md)
 - **Line 77, Column 1**: **[Suggestion-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=master)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-0e4ffc7e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 19, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific  [...]

2020-10-07 05:24 UTC, opbld33 commented
Docs Build status updates of commit _[40871e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40871e407d3fc1dca39815b0cfce39a2c85ecdaf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-53fe4f6a)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-53fe4f6a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 19, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to li [...]

2020-10-07 05:41 UTC, opbld31 commented
Docs Build status updates of commit _[c3a18e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3a18e1e3a4cba125b0e5b8dee405e1417eaf212)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-9886cce5)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-9886cce5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 19, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to li [...]

2020-10-09 05:51 UTC, opbld34 commented
Docs Build status updates of commit _[c2ef6ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2ef6ea582bdce3cca8f34514947197498dc86e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-65986832)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-65986832"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 47, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 50, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 63, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-10-14 03:05 UTC, Lauragra commented on api-reference/beta/api/teamstab-chat-create.md
> +POST https://graph.microsoft.com/beta/chats/19:75a0894119a0468caee5811901a75ffd@thread.tacv2/tabs
The syntax here doesn't match the syntax in the HTTP request section. Also, the example is missing the HTML comments for API Doctor validation, and the response is set to Ignored. Please include the required comments so we can validate the examples.

2020-10-14 03:06 UTC, opbld31 commented
Docs Build status updates of commit _[f4929e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4929e6524007e5b429fde2aaecebd337e6631f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-e136812d)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-e136812d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 59, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so [...]

2020-10-14 03:06 UTC, Lauragra commented on api-reference/beta/api/teamstab-chat-delete.md
> +<!-- {
Why are you setting the request to ignored?

2020-10-15 05:17 UTC, opbld30 commented
Docs Build status updates of commit _[f619495](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f619495df7c11c9c7d3153885252f9de0e5c49de)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-16178910)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-16178910"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 21, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '| Change type | Version   | Description                          |
| :-------------- | :------------ | :--------------------------------------- |
|Addition|Beta|Added List chat, Get tab chat, Create tab chat, Delete tab chat, and Update tab chat. Also updated the resource file teamsTab|') are not allowed. You can only have one top-level heading.
`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tru [...]

2020-10-15 06:16 UTC, opbld30 commented
Docs Build status updates of commit _[a5f641a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5f641abbfd5808d761a89c1bf871cab919f4798)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-bd0703ae)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-bd0703ae"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 21, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '| Change type | Version   | Description                          |
| :-------------- | :------------ | :--------------------------------------- |
|Addition|Beta|Added List chat, Get tab chat, Create tab chat, Delete tab chat, and Update tab chat. Also updated the resource file teamsTab|') are not allowed. You can only have one top-level heading.
`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set] [...]

2020-10-15 06:50 UTC, opbld33 commented
Docs Build status updates of commit _[fb3055e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb3055eabd2c7b1c0ea3f5c8e16252a0ea3d19b3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-0cda8ba1)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-0cda8ba1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 21, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '| Change type | Version   | Description                          |
| :-------------- | :------------ | :--------------------------------------- |
|Addition|Beta|Added List chat, Get tab chat, Create tab chat, Delete tab chat, and Update tab chat. Also updated the resource file teamsTab|') are not allowed. You can only have one top-level heading.
`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set] [...]

2020-10-15 09:38 UTC, opbld30 commented
Docs Build status updates of commit _[57cca17](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57cca17ea7aa1e8caaea8e33a917ed5c08683126)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-4992550f)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-4992550f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 21, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '| Change type | Version   | Description                          |
| :-------------- | :------------ | :--------------------------------------- |
|Addition|Beta|Added List chat, Get tab chat, Create tab chat, Delete tab chat, and Update tab chat. Also updated the resource file teamsTab|') are not allowed. You can only have one top-level heading.
`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set] [...]

2020-10-15 09:41 UTC, opbld34 commented
Docs Build status updates of commit _[da312ba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da312ba8bbe08ba98610627c3f1f4c7cf1620eb3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-95076fe5)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-95076fe5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 21, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '| Change type | Version   | Description                          |
| :-------------- | :------------ | :--------------------------------------- |
|Addition|Beta|Added List chat, Get tab chat, Create tab chat, Delete tab chat, and Update tab chat. Also updated the resource file teamsTab|') are not allowed. You can only have one top-level heading.
`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set] [...]

2020-10-15 09:44 UTC, opbld32 commented
Docs Build status updates of commit _[9b80892](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b80892a786fab3623a8db0f0975a79459536dad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-aa2ad893)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-aa2ad893"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-15 09:46 UTC, opbld30 commented
Docs Build status updates of commit _[dfa2421](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dfa2421cb15b2d117fd4d172505d2bd0846de310)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-8367d40b)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-8367d40b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-15 10:04 UTC, opbld31 commented
Docs Build status updates of commit _[628f2e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/628f2e43e466e2145f8ccf64d1b644c517eac92d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-95ca43b8)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-95ca43b8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-15 10:12 UTC, opbld32 commented
Docs Build status updates of commit _[da25c93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da25c93aacb0e503a755b6af572ace7074b20146)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-177f9586)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-177f9586"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-15 10:20 UTC, opbld33 commented
Docs Build status updates of commit _[3bb206b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3bb206b01bf58dc9089d73cdd45e2c440f5697a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-42d8a661)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-42d8a661"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-15 12:28 UTC, opbld33 commented
Docs Build status updates of commit _[df0ce97](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df0ce97b173909c348d3ddd6d3048e26ed821699)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-49d20c9f)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-49d20c9f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-15 12:54 UTC, opbld33 commented
Docs Build status updates of commit _[8976706](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89767068e8e93e3df89cd10b3b49bc295e7025f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-b97f00b3-3a99691e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-3a99691e)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="b97f00b3-3a99691e"></a>
### [api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md)
 - **Line 22, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 31, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-3a99691e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph- [...]

2020-10-15 12:57 UTC, opbld34 commented
Docs Build status updates of commit _[f22f584](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f22f5841dfab0874923f92539bc9cd384d6d9d04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-4fee49e3)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-4fee49e3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-15 13:07 UTC, opbld30 commented
Docs Build status updates of commit _[4c91e99](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c91e99876538925e0dbdbc44ee5288becbdecb9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-a02c6c64)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-a02c6c64"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-15 13:10 UTC, opbld30 commented
Docs Build status updates of commit _[80f3a2e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80f3a2ea24486f7fe4b6a91e511318b95e092b3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-190c783d)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-190c783d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-15 15:54 UTC, opbld32 commented
Docs Build status updates of commit _[b3f46c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3f46c5c369251e1225af8375106e7f97809aca2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-78952b38)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-78952b38"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-16 09:11 UTC, opbld32 commented
Docs Build status updates of commit _[a851d12](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a851d123de8bd93a2f4c3b77d9fa3dadbf0c005b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-0223541a)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-0223541a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-16 09:14 UTC, opbld30 commented
Docs Build status updates of commit _[2b95381](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b953819b93509572bd4cef0632b9d8868756d2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-69dcf305)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-69dcf305"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-16 09:25 UTC, opbld32 commented
Docs Build status updates of commit _[59ad4ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/59ad4cab93dcbf2440d4043cd19e9643ac641017)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-18d61923)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-18d61923"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-16 09:33 UTC, opbld30 commented
Docs Build status updates of commit _[96347db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96347dbe36ff8ddb2adb7c7e33282f7304a8543f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-018eab31)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-018eab31"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-16 09:42 UTC, opbld33 commented
Docs Build status updates of commit _[996db41](https://github.com/microsoftgraph/microsoft-graph-docs/commits/996db416d67ace83b60c868e63ba8b0fe2248c34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-d867c13b)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-d867c13b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-16 09:48 UTC, opbld31 commented
Docs Build status updates of commit _[d249bec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d249becbf9395669057e496845b1230455ae356e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-e453ee0e)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-e453ee0e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-16 09:52 UTC, opbld30 commented
Docs Build status updates of commit _[ad7a0b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad7a0b4bfd2a6e2493bfea22c4d86f94dd51135c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-2f5743ca)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-2f5743ca"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-16 09:55 UTC, opbld32 commented
Docs Build status updates of commit _[a4276a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a4276a1e176d2427d0f28d198dd056310634c7e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-68381304)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-68381304"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-16 09:59 UTC, opbld31 commented
Docs Build status updates of commit _[0266ae7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0266ae7236afbfab3b50df93ae53c128c621a65f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-f4377ac4)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-f4377ac4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-16 10:03 UTC, opbld34 commented
Docs Build status updates of commit _[9b52281](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b5228150a5fcc8f356ff67445e2c310dd3f853d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-b9582e1c)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-b9582e1c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Sugges [...]

2020-10-27 12:39 UTC, Rajeshwari-v commented on api-reference/beta/api/teamstab-chat-create.md
> +POST https://graph.microsoft.com/beta/chats/19:75a0894119a0468caee5811901a75ffd@thread.tacv2/tabs
Example added

2020-10-27 21:10 UTC, opbld34 commented
Docs Build status updates of commit _[8cdd320](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8cdd3205150567d4f43092f564522f44212f2c6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-4e27af34)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |

<a id="de0bbbbb-4e27af34"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-se [...]

2020-10-27 21:41 UTC, opbld33 commented
Docs Build status updates of commit _[0442e66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0442e66d40d14a564b0eeb5eae55d80b13abccc9)_: 

:clock10: **Pending**: waiting for processors ([7](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-27 21:43 UTC, opbld33 commented
Docs Build status updates of commit _[0442e66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0442e66d40d14a564b0eeb5eae55d80b13abccc9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-07047cce)
[api-reference/beta/api/teamstab-chat-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-create?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-07047cce"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not [...]

2020-10-27 21:51 UTC, laujan commented
Hi @Lauragra this is ready to merge, please!

2020-10-27 22:23 UTC, laujan commented
Please review @AkJo. Thanks!

2020-10-27 23:05 UTC, AkJo commented on api-reference/beta/api/teamstab-chat-get.md
> +  "@odata.context": "https://localhost:8200/beta/$metadata#chats/{chatId}/tabs/{tabId}",
Not only does the example has defects, it belongs on the 'list tabs in chat' page.

2020-10-27 23:05 UTC, AkJo commented on api-reference/beta/api/teamstab-chat-list.md
> +description: "Retrieve the list of tabs in the specified chat within a team. "
"Retrieve the list of tabs in the specified chat"

2020-10-27 23:05 UTC, AkJo commented on api-reference/beta/api/teamstab-chat-list.md
> +Retrieve the list of [tabs](../resources/teamstab.md) in the specified [chat](../resources/chat.md) within a [team](../resources/team.md).
Remove.

2020-10-27 23:05 UTC, AkJo commented on api-reference/beta/api/teamstab-chat-list.md
> +|Delegated  | TeamsTab.Read.All, TeamsTab.ReadWrite.All |Allows read of existing teamsTab in the chat. None give access to the content inside the tabs.|
Equivalent comment about permissions.

2020-10-27 23:06 UTC, AkJo commented on api-reference/beta/api/teamstab-chat-list.md
> +> **Note**: The Automation now has an update. It will add another tab, Notes, to every meeting chat when the meeting begins. The Automation lists all the tabs, and adds the ones that are missing. The
Please remove.

2020-10-27 23:06 UTC, AkJo commented on api-reference/beta/api/teamstab-chat-update.md
> +|Delegated  | TeamsTab.Create, TeamsTab.ReadWrite.All  |Allows write of the new teamsTab to the chat. TeamsTab.Create does not grant the ability to read, modify or delete tabs after they are created,
Same feedback.

2020-10-27 23:07 UTC, AkJo commented on api-reference/beta/api/teamstab-chat-update.md
> +HTTP/1.1 200 OK
This example is a repetition of the previous example.

2020-10-27 23:08 UTC, AkJo commented on api-reference/beta/api/teamstab-chat-list.md
> +### Example : List tabs in a Teams chat
How is this example any different from the one above?

2020-10-27 23:09 UTC, AkJo commented on api-reference/beta/resources/teamstab.md
> +|[Update tab channel](../api/teamstab-update.md) | [teamsTab](teamstab.md) | Updates the tab properties.|
Updates the properties of a tab in a channel.

2020-10-27 23:09 UTC, AkJo commented on api-reference/beta/resources/teamstab.md
> +|[Update tab chat](../api/teamstab-chat-update.md) | [teamsTab](teamstab.md) | Updates the tab properties.|
Updates the properties of a tab in a chat.

2020-10-27 23:10 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: List tabs channel
List tabs in a channel

2020-10-27 23:10 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: Get tab channel
in a channel

2020-10-27 23:10 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: Add tab channel
in a channel

2020-10-27 23:10 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: Update tab channel
in a channel

2020-10-27 23:11 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: List tabs chat
List tabs in a chat

2020-10-27 23:11 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: Get tab chat
in a chat

2020-10-27 23:11 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: Create tab chat
in a chat

2020-10-27 23:11 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: Update tab chat
in a chat

2020-10-27 23:11 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: Delete tab chat
in a chat

2020-10-27 23:11 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: Delete tab channel
from a channel

2020-10-27 23:16 UTC, AkJo commented on api-reference/beta/resources/teamstab.md
> +|[Update tab channel](../api/teamstab-update.md) | [teamsTab](teamstab.md) | Updates the tab properties.|
What does "List tabs channel" mean?
Please update the text in this entire column.


List tabs in channel
Get tab in channel

.....

List tabs in chat

...

Delete tab from chat

2020-10-28 07:29 UTC, opbld34 commented
Docs Build status updates of commit _[1383957](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1383957e9c5c6301431fb4c40ccc08dc342d1662)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-50d43004)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-50d43004)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-50d43004)
[api-reference/beta/api/teamstab-chat-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-50d43004"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-chat-create.md'.`````

<a id="00685cff-50d43004"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-create.md'.`````

<a id="de0bbbbb-50d43004"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph [...]

2020-10-28 07:38 UTC, opbld30 commented
Docs Build status updates of commit _[071cac8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/071cac80c9adfe9e0b2b9018d45fe700ded122a8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-cae18941)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-cae18941)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-cae18941)
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-cae18941"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-chat-create.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-chat-delete.md'.`````

<a id="00685cff-cae18941"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-create.md'.`````
 - **Line 12475, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-delete.md'.`````

<a id="de0bbbbb-cae18941"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/pri [...]

2020-10-28 07:49 UTC, opbld30 commented
Docs Build status updates of commit _[021057f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/021057f25b570cc0bc8f71d7bf860dbc29e75557)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-3eadda3d)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-3eadda3d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-3eadda3d)
[api-reference/beta/api/teamstab-chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-3eadda3d"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-chat-create.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-chat-delete.md'.`````

<a id="00685cff-3eadda3d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-create.md'.`````
 - **Line 12475, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-delete.md'.`````

<a id="de0bbbbb-3eadda3d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/pri [...]

2020-10-28 08:02 UTC, opbld34 commented
Docs Build status updates of commit _[092513b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/092513b7b26f0261ce178b228b69f428707bff1a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-17ff2c1a)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-17ff2c1a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-17ff2c1a)
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-17ff2c1a"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-chat-get.md'.`````
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-chat-create.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-chat-delete.md'.`````

<a id="00685cff-17ff2c1a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12469, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-get.md'.`````
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-create.md'.`````
 - **Line 12475, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-delete.md'.`````

<a id="de0bbbbb-17ff2c1a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-10-28 08:04 UTC, opbld32 commented
Docs Build status updates of commit _[de52753](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de5275344eaaf6d064597ef320c5c1693b6482a8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-c19a62e8)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-c19a62e8)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-c19a62e8)
[api-reference/beta/api/teamstab-chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-c19a62e8"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-chat-get.md'.`````
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-chat-create.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-chat-delete.md'.`````

<a id="00685cff-c19a62e8"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12469, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-get.md'.`````
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-create.md'.`````
 - **Line 12475, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-delete.md'.`````

<a id="de0bbbbb-c19a62e8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-10-28 08:19 UTC, opbld33 commented
Docs Build status updates of commit _[696a180](https://github.com/microsoftgraph/microsoft-graph-docs/commits/696a180ee9ddff19f9bdb3ae10a11c35fd9111b5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-26d3666f)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-26d3666f)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-26d3666f)
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-26d3666f"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-chat-list.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-chat-get.md'.`````
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-chat-create.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-chat-delete.md'.`````

<a id="00685cff-26d3666f"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12467, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-list.md'.`````
 - **Line 12469, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-get.md'.`````
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-create.md'.`````
 - **Line 12475, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-delete.md'.`````

<a id="de0bbbbb-26d3666f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /gr [...]

2020-10-28 08:33 UTC, opbld34 commented
Docs Build status updates of commit _[3834918](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3834918846fa106488fcf2e6886023f79960ded1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-88928de6)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-88928de6)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-88928de6)
[api-reference/beta/api/teamstab-chat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-chat-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-chat-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-88928de6"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 31, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update-chat.md'.`````

<a id="00685cff-88928de6"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12467, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-list.md'.`````
 - **Line 12469, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-get.md'.`````
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-create.md'.`````
 - **Line 12475, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-delete.md'.`````

<a id="de0bbbbb-88928de6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]* [...]

2020-10-28 08:36 UTC, opbld33 commented
Docs Build status updates of commit _[311a14c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/311a14c1acd00fcea0a484cb5a45380f59c36669)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-9d5b1e30)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-9d5b1e30)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="00685cff-9d5b1e30"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12467, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-list.md'.`````
 - **Line 12469, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-get.md'.`````
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-create.md'.`````
 - **Line 12473, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-update.md'.`````
 - **Line 12475, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-chat-delete.md'.`````

<a id="de0bbbbb-9d5b1e30"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific vers [...]

2020-10-28 08:55 UTC, opbld33 commented
Docs Build status updates of commit _[2fec5e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2fec5e25bd09543e01d5ba7176dd6cd25f58c2c5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-f684e982)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-f684e982)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="00685cff-f684e982"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12457, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-list-channel.md'.`````
 - **Line 12459, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-get-channel.md'.`````
 - **Line 12461, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-add-channel.md'.`````
 - **Line 12463, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-update-channel.md'.`````
 - **Line 12465, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-delete-channel.md'.`````

<a id="de0bbbbb-f684e982"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a s [...]

2020-10-28 08:58 UTC, opbld33 commented
Docs Build status updates of commit _[d97091e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d97091e15c94032fafe5b7d6e2694cf7c8403f7f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-e50e2e6c)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-e50e2e6c)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-e50e2e6c)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-e50e2e6c)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-e50e2e6c"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 22, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````

<a id="00685cff-e50e2e6c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12459, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-get-channel.md'.`````
 - **Line 12461, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-add-channel.md'.`````
 - **Line 12463, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-update-channel.md'.`````
 - **Line 12465, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-delete-channel.md'.`````

<a id="7d8afd84-e50e2e6c"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````

<a id="de0bbbbb-e50e2e6c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 [...]

2020-10-28 09:00 UTC, opbld31 commented
Docs Build status updates of commit _[d8ab69b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8ab69bde97d8ef3b066e825332e839638ad73d8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-9bd13865)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-9bd13865)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-9bd13865)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-9bd13865)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-9bd13865"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 22, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````

<a id="00685cff-9bd13865"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12461, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-add-channel.md'.`````
 - **Line 12463, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-update-channel.md'.`````
 - **Line 12465, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-delete-channel.md'.`````

<a id="7d8afd84-9bd13865"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````

<a id="de0bbbbb-9bd13865"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to  [...]

2020-10-28 09:04 UTC, opbld31 commented
Docs Build status updates of commit _[cbd5d1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cbd5d1d96dabca3d11ef0ca5464edd4dd160569d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-b19330f1)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-b19330f1)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-b19330f1)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-b19330f1)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-b19330f1"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 22, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````

<a id="00685cff-b19330f1"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12463, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-update-channel.md'.`````
 - **Line 12465, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-delete-channel.md'.`````

<a id="7d8afd84-b19330f1"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````

<a id="de0bbbbb-b19330f1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/re [...]

2020-10-28 09:06 UTC, opbld32 commented
Docs Build status updates of commit _[d385473](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d3854731753ca79773d57c87f75a27f7707b556c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-cec184bc)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-cec184bc)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-cec184bc)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-cec184bc)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-cec184bc"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 22, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="00685cff-cec184bc"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12463, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-update-channel.md'.`````

<a id="7d8afd84-cec184bc"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 23, Column 176**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="de0bbbbb-cec184bc"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to t [...]

2020-10-28 09:08 UTC, opbld30 commented
Docs Build status updates of commit _[7faf5d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7faf5d117ce10a183ef68b113e2006e8c86dc2c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-3e10806b)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-3e10806b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-3e10806b)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-3e10806b"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 22, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````
 - **Line 26, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````

<a id="7d8afd84-3e10806b"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````
 - **Line 23, Column 176**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="de0bbbbb-3e10806b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If [...]

2020-10-28 09:09 UTC, opbld33 commented
Docs Build status updates of commit _[d7825f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d7825f3461cbdfdd75e2b6a14e2f9ff5b65cb875)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-6f4d68fe)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-6f4d68fe)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7d8afd84-6f4d68fe"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````
 - **Line 23, Column 176**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="de0bbbbb-6f4d68fe"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodC [...]

2020-10-28 10:07 UTC, opbld30 commented
Docs Build status updates of commit _[75de87f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/75de87fdf89e27ea0f526924f6a3d9a8e79b7e62)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-f6d8648e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-f6d8648e)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7d8afd84-f6d8648e"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````
 - **Line 23, Column 176**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="de0bbbbb-f6d8648e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodC [...]

2020-10-28 10:24 UTC, opbld32 commented
Docs Build status updates of commit _[3c36584](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c36584ca2a81bf97ee40f71723777e3872cb45e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-b113d9eb)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-b113d9eb)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7d8afd84-b113d9eb"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````
 - **Line 23, Column 176**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="de0bbbbb-b113d9eb"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodC [...]

2020-10-28 10:26 UTC, opbld32 commented
Docs Build status updates of commit _[0efdfdb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0efdfdb4615a19f030147ba85f5831e27aeb359f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-473ce8b7)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-473ce8b7)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7d8afd84-473ce8b7"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````
 - **Line 23, Column 176**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="de0bbbbb-473ce8b7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodC [...]

2020-10-28 10:30 UTC, opbld32 commented
Docs Build status updates of commit _[8a94e8c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a94e8c3edbc6b42d9d85d8d005175073ceef07c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-35a79acd)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-35a79acd)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7d8afd84-35a79acd"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````
 - **Line 23, Column 176**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="de0bbbbb-35a79acd"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodC [...]

2020-10-28 10:40 UTC, opbld30 commented
Docs Build status updates of commit _[8d699d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d699d2f329cae00ec36685193d10e0c2c537d87)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-74d0cfd4)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-74d0cfd4)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7d8afd84-74d0cfd4"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````
 - **Line 23, Column 176**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="de0bbbbb-74d0cfd4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodC [...]

2020-10-28 10:52 UTC, opbld31 commented
Docs Build status updates of commit _[d7d85ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d7d85ea3c9cc6e53a1b000a911873146aa002370)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-0044ceb8)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-0044ceb8)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7d8afd84-0044ceb8"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````
 - **Line 23, Column 176**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="de0bbbbb-0044ceb8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodC [...]

2020-10-28 10:56 UTC, opbld30 commented
Docs Build status updates of commit _[c213290](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c21329033c69b01c9934b66e8717e20941cc6457)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-d8269556)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-d8269556)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7d8afd84-d8269556"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````
 - **Line 23, Column 176**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="de0bbbbb-d8269556"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodC [...]

2020-10-28 10:59 UTC, opbld33 commented
Docs Build status updates of commit _[21fc68d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21fc68d46f44934fd3e2412883e062e38273d649)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-320e5bbe)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-320e5bbe)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7d8afd84-320e5bbe"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````
 - **Line 23, Column 176**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="de0bbbbb-320e5bbe"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodC [...]

2020-10-28 11:03 UTC, opbld30 commented
Docs Build status updates of commit _[a9b6525](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a9b6525b284d25fe18788299baf0696835c0d82c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-8cdbef0b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-8cdbef0b)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7d8afd84-8cdbef0b"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````
 - **Line 23, Column 176**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="de0bbbbb-8cdbef0b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodC [...]

2020-10-28 16:13 UTC, opbld33 commented
Docs Build status updates of commit _[3dd698d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3dd698db57da4e087dd01d8cd6d7c262f44c2b7e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-d6d33da9)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-d6d33da9)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="7d8afd84-d6d33da9"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list.md'.`````
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````
 - **Line 23, Column 176**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="de0bbbbb-d6d33da9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodC [...]

2020-10-29 09:06 UTC, opbld34 commented
Docs Build status updates of commit _[04fd669](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04fd669366babecec7636ead7fe0b1d864ab7b6b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-87dbf305)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-87dbf305)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-87dbf305)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-87dbf305)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-87dbf305"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 22, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list-channel.md'.`````

<a id="00685cff-87dbf305"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-list-channel.md'.`````

<a id="7d8afd84-87dbf305"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 107**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get.md'.`````
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````
 - **Line 23, Column 176**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="de0bbbbb-87dbf305"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific versi [...]

2020-10-29 09:08 UTC, opbld32 commented
Docs Build status updates of commit _[e89d45d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e89d45dace706b835a320a99e584955de8bf23f8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-eed11152)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-eed11152)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-eed11152)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-eed11152)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-eed11152"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 22, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list-channel.md'.`````
 - **Line 23, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get-channel.md'.`````

<a id="00685cff-eed11152"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-list-channel.md'.`````
 - **Line 12473, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-get-channel.md'.`````

<a id="7d8afd84-eed11152"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````
 - **Line 23, Column 176**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete.md'.`````

<a id="de0bbbbb-eed11152"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line [...]

2020-10-29 09:10 UTC, opbld33 commented
Docs Build status updates of commit _[01bb68e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01bb68ea8cbf9138352c25b05515ebf31677f9d8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-652384a8)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-652384a8)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-652384a8)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-652384a8)
[api-reference/beta/api/teamstab-add-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-652384a8"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 22, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list-channel.md'.`````
 - **Line 23, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get-channel.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete-channel.md'.`````

<a id="00685cff-652384a8"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-list-channel.md'.`````
 - **Line 12473, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-get-channel.md'.`````
 - **Line 12479, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-delete-channel.md'.`````

<a id="7d8afd84-652384a8"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 73**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add.md'.`````
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````

<a id="de0bbbbb-652384a8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserv [...]

2020-10-29 09:11 UTC, opbld34 commented
Docs Build status updates of commit _[7fc9c2d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7fc9c2df600da6752a02179a5b5b6f26b9a1ef08)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-71fa7a13)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-71fa7a13)
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-7d8afd84-71fa7a13)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-71fa7a13)
[api-reference/beta/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-channel?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-71fa7a13"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 22, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list-channel.md'.`````
 - **Line 23, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get-channel.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add-channel.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete-channel.md'.`````

<a id="00685cff-71fa7a13"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-list-channel.md'.`````
 - **Line 12473, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-get-channel.md'.`````
 - **Line 12475, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-add-channel.md'.`````
 - **Line 12479, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-delete-channel.md'.`````

<a id="7d8afd84-71fa7a13"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teams-api-overview.md)
 - **Line 23, Column 139**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update.md'.`````

<a id="de0bbbbb-71fa7a13"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion [...]

2020-10-29 09:13 UTC, opbld30 commented
Docs Build status updates of commit _[5b2756f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b2756f127a35fe191d7e729f44740845d0edd29)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-523a6cc5)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-523a6cc5)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-523a6cc5)
[api-reference/beta/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-523a6cc5"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 22, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list-channel.md'.`````
 - **Line 23, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get-channel.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-add-channel.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete-channel.md'.`````
 - **Line 26, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update-channel.md'.`````

<a id="00685cff-523a6cc5"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-list-channel.md'.`````
 - **Line 12473, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-get-channel.md'.`````
 - **Line 12475, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-add-channel.md'.`````
 - **Line 12477, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-update-channel.md'.`````
 - **Line 12479, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-delete-channel.md'.`````

<a id="de0bbbbb-523a6cc5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the  [...]

2020-10-29 09:14 UTC, opbld31 commented
Docs Build status updates of commit _[82c6e87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82c6e872d5f5f825b4916856a3b6bb4bb86bcc6a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-180d7958)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-180d7958)
[api-reference/beta/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="00685cff-180d7958"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-list-channel.md'.`````
 - **Line 12473, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-get-channel.md'.`````
 - **Line 12475, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-add-channel.md'.`````
 - **Line 12477, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-update-channel.md'.`````
 - **Line 12479, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-delete-channel.md'.`````

<a id="de0bbbbb-180d7958"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve- [...]

2020-10-29 09:20 UTC, opbld34 commented
Docs Build status updates of commit _[fc02e28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc02e28fa64d761756ae9d92509039ac1de270ab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-9f3af76a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-9f3af76a)
[api-reference/beta/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="00685cff-9f3af76a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-list-channel.md'.`````
 - **Line 12473, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-get-channel.md'.`````
 - **Line 12475, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-add-channel.md'.`````
 - **Line 12477, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-update-channel.md'.`````
 - **Line 12479, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-delete-channel.md'.`````

<a id="de0bbbbb-9f3af76a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve- [...]

2020-10-29 09:22 UTC, opbld32 commented
Docs Build status updates of commit _[fba1b9f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fba1b9f691275a5a99396d2d47fa2887f87739ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-18430c8f)
[api-reference/beta/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-18430c8f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Colu [...]

2020-10-29 12:22 UTC, opbld31 commented
Docs Build status updates of commit _[44f0861](https://github.com/microsoftgraph/microsoft-graph-docs/commits/44f08618535547eeba113475cbb167cea8e07cd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-d161368c)
[api-reference/beta/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-d161368c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Colu [...]

2020-10-30 04:05 UTC, opbld32 commented
Docs Build status updates of commit _[6bfdb1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6bfdb1ee8d3aa9703ac9660fbad3b8fff622c22d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-e78ca00f)
[api-reference/beta/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-e78ca00f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Colu [...]

2020-10-30 07:50 UTC, opbld34 commented
Docs Build status updates of commit _[68eb532](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68eb5324ab833c7f30a81b6d8ee83981550ae3ec)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-dd0571a2-df845282)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-df845282)
[api-reference/beta/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="dd0571a2-df845282"></a>
### [api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md)
 - **Line 17, Column 39**: **[Warning-file-not-found]** `````Invalid file link: '../api/chatappinstallation-add.md'.`````

<a id="de0bbbbb-df845282"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** ```` [...]

2020-10-30 08:46 UTC, opbld34 commented
Docs Build status updates of commit _[c0b27d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0b27d94ad5dfa113d3ad8f25c7a9200f718c10e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-f5ae4d5f)
[api-reference/beta/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-f5ae4d5f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Colu [...]

2020-10-30 09:13 UTC, opbld32 commented
Docs Build status updates of commit _[dc58061](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dc58061f91c168531278dc2efc2809262fa3ffb4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-1b6d64bb)
[api-reference/beta/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-1b6d64bb"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Colu [...]

2020-10-30 09:46 UTC, opbld33 commented
Docs Build status updates of commit _[ec223b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec223b11ccd5021afe2955d62047a85092c7cf93)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-d9e72cb1)
[api-reference/beta/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-d9e72cb1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Colu [...]

2020-10-30 09:57 UTC, opbld34 commented
Docs Build status updates of commit _[f8d67cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8d67cdbe5a1694126381ed3f337fec16339793f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-26e7967c)
[api-reference/beta/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-26e7967c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Colu [...]

2020-11-02 03:48 UTC, opbld32 commented
Docs Build status updates of commit _[b9a7936](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9a7936e0bbdd4801e5374bee8e648a029fd3cbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-b173ffdb)
[api-reference/beta/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-b173ffdb"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-03 03:49 UTC, opbld30 commented
Docs Build status updates of commit _[7f43390](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f433908733b62aa0bbba8546e43a3fb061b733d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-0c27d8c8)
[api-reference/beta/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-0c27d8c8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a speci [...]

2020-11-04 09:07 UTC, AkJo commented on api-reference/beta/api/teamstab-add.md
> -description: "Adds (pins) a tab to the specified channel within a team. "
'within a team' was fine here. Channels are within a team.

2020-11-04 09:08 UTC, AkJo commented on api-reference/beta/api/teamstab-add.md
> -Adds (pins) a [tab](../resources/teamstab.md) to the specified [channel](../resources/channel.md) within a [team](../resources/team.md).
Same

2020-11-04 09:08 UTC, AkJo commented on api-reference/beta/api/teamstab-add.md
> +POST /channels/{id}/tabs/{id}
Channels are within a team.

The correct path is POST /teams/{id}/channels/{id}/tabs

2020-11-04 09:09 UTC, AkJo commented on api-reference/beta/api/teamstab-add.md
> -description: "Adds (pins) a tab to the specified channel within a team. "
Please revert all the changes in this file.

2020-11-04 09:10 UTC, opbld31 commented
Docs Build status updates of commit _[cf53630](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cf536306ecf14d6f13e06dc8b88c52ac2843a6e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-50ac101b)
[api-reference/beta/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-50ac101b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a speci [...]

2020-11-04 09:28 UTC, opbld34 commented
Docs Build status updates of commit _[b3677b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3677b857df012540978cce043e0080cb594145f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-0750edbf)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-0750edbf"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprin [...]

2020-11-04 09:31 UTC, opbld33 commented
Docs Build status updates of commit _[7aba174](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7aba17405ce46c55cfd3722458fe1678f71e6f6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-d70e0680)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-d70e0680"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did y [...]

2020-11-04 09:34 UTC, opbld31 commented
Docs Build status updates of commit _[710f0fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/710f0fec760a8ddbe1e9b2918371e46c54974554)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-9dc2327a)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-9dc2327a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did y [...]

2020-11-04 09:55 UTC, opbld31 commented
Docs Build status updates of commit _[46c068d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46c068d44e210bee78f8c10bc4c2c5d9a95fd4ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-ec761711)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-ec761711"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=grap [...]

2020-11-04 09:57 UTC, opbld34 commented
Docs Build status updates of commit _[3a13022](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a130220d77f854e91245660384b879d9d32068a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-bbdb130f)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-bbdb130f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? I [...]

2020-11-04 09:59 UTC, opbld30 commented
Docs Build status updates of commit _[dc8f275](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dc8f275ee96a970d8a9f8379db04a15e53c87cbe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-f1f43a06)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-f1f43a06"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=grap [...]

2020-11-05 12:18 UTC, opbld32 commented
Docs Build status updates of commit _[2edb7b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2edb7b1518162c2b652c984ed64e1d26c29f78df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-03270ab3)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-03270ab3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=grap [...]

2020-11-05 12:31 UTC, opbld31 commented
Docs Build status updates of commit _[525def1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/525def1b59ea6192d80c9f2bb5b8c8d13b56da5e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-6b996c8e)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-6b996c8e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=grap [...]

2020-11-09 11:52 UTC, opbld32 commented
Docs Build status updates of commit _[997b901](https://github.com/microsoftgraph/microsoft-graph-docs/commits/997b90131bd19679ca8c23477a4d0403b96e6202)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-24bc9c85)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-24bc9c85"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest [...]

2020-11-09 12:15 UTC, opbld34 commented
Docs Build status updates of commit _[184422c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/184422c87bea7a29ef57092ece25a0499e1be0ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-e6c3da35)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-e6c3da35"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest [...]

2020-11-09 12:19 UTC, opbld33 commented
Docs Build status updates of commit _[0d7d3fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d7d3fed142bdd7297933a3e63172f96bb68728d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-9d5ddfa7)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-9d5ddfa7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest [...]

2020-11-09 12:23 UTC, opbld34 commented
Docs Build status updates of commit _[604c6ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/604c6ed1dcef01f1406e1c0816229b462349d900)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-b0774481)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-b0774481"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest [...]

2020-11-09 12:31 UTC, opbld32 commented
Docs Build status updates of commit _[47797e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/47797e186bfcd559025d4a8c13e7040d5bec11fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-90b0bd25)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-90b0bd25"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest [...]

2020-11-09 12:42 UTC, opbld30 commented
Docs Build status updates of commit _[837b5fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/837b5fa310648c338bbd9eb98088e910106ddfb2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-44df6871)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-44df6871"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest [...]

2020-11-09 12:49 UTC, opbld34 commented
Docs Build status updates of commit _[3658799](https://github.com/microsoftgraph/microsoft-graph-docs/commits/36587999148c7b888b376ee28f91d8baffa53f41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-cec64795)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-cec64795"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest [...]

2020-11-09 12:53 UTC, opbld32 commented
Docs Build status updates of commit _[d702853](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d702853e4b884d50cd90e78f2af3efa675dc3bd8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-9c812bdc)
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-list-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-list-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-list-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-9c812bdc"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest [...]

2020-11-10 06:19 UTC, opbld33 commented
Docs Build status updates of commit _[6e68f0a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e68f0aa3f2c107129bfd5433dcb8218c2bce674)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-6126c82e)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-6126c82e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-6126c82e)
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-6126c82e"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list-chat.md'.`````

<a id="00685cff-6126c82e"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12469, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-list-chat.md'.`````

<a id="de0bbbbb-6126c82e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line  [...]

2020-11-10 06:20 UTC, opbld32 commented
Docs Build status updates of commit _[6cce9ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6cce9eae2e14b963cf7f3a335c8082cf9d1c77ba)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b7fcc8b6)

<a id="b7fcc8b6"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011100619404783-10199%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8YVld3mJH0wu4lkQE4yg0%2BJDj3sdcCjNwobPDkF7y5I%3D&st=2020-11-10T06%3A15%3A04Z&se=2020-12-11T06%3A20%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 06:23 UTC, opbld31 commented
Docs Build status updates of commit _[225e064](https://github.com/microsoftgraph/microsoft-graph-docs/commits/225e064fb5e8308cfdcda89ac6a064901faae5f7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-72371f37)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-72371f37)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-72371f37)
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-delete-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-delete-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-delete-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-72371f37"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list-chat.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get-chat.md'.`````

<a id="00685cff-72371f37"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12469, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-list-chat.md'.`````
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-get-chat.md'.`````

<a id="de0bbbbb-72371f37"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: [...]

2020-11-10 06:26 UTC, opbld34 commented
Docs Build status updates of commit _[381e43e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/381e43e851be9429136bacc2fef34b3505b3536f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-5481045a)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-5481045a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-5481045a)
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-5481045a"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list-chat.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get-chat.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete-chat.md'.`````

<a id="00685cff-5481045a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12469, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-list-chat.md'.`````
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-get-chat.md'.`````
 - **Line 12477, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-delete-chat.md'.`````

<a id="de0bbbbb-5481045a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: [...]

2020-11-10 06:29 UTC, opbld33 commented
Docs Build status updates of commit _[8e68185](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e6818512a83d84e8e362f4ed854c980fc0f4cec)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-ff41592a)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-ff41592a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-ff41592a)
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-ff41592a"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-list-chat.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-get-chat.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-delete-chat.md'.`````
 - **Line 31, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamstab-update-chat.md'.`````

<a id="00685cff-ff41592a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12469, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-list-chat.md'.`````
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-get-chat.md'.`````
 - **Line 12475, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-update-chat.md'.`````
 - **Line 12477, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-delete-chat.md'.`````

<a id="de0bbbbb-ff41592a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Colu [...]

2020-11-10 06:32 UTC, opbld30 commented
Docs Build status updates of commit _[7a1838a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a1838afbd6b37f81487ac61b34145e231dd8677)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-c8931ddc)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-c8931ddc)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-c8931ddc)
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-c8931ddc"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-create-tabs.md'.`````

<a id="00685cff-c8931ddc"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12469, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-list-chat.md'.`````
 - **Line 12471, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-get-chat.md'.`````
 - **Line 12475, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-update-chat.md'.`````
 - **Line 12477, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/teamstab-delete-chat.md'.`````

<a id="de0bbbbb-c8931ddc"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the U [...]

2020-11-10 06:41 UTC, opbld34 commented
Docs Build status updates of commit _[5d72a8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d72a8a0d88243d06de27371d67ccf0f8b4fd471)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-5d44927d)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-5d44927d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-5d44927d)
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-5d44927d"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-create-tabs.md'.`````

<a id="00685cff-5d44927d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12473, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chat-create-tabs.md'.`````

<a id="de0bbbbb-5d44927d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve [...]

2020-11-10 06:45 UTC, opbld32 commented
Docs Build status updates of commit _[7f2eef7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f2eef78ccf190f2ed3756943a842bab1757b249)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-29baed74)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-29baed74)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-29baed74)
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-29baed74"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-create-tabs.md'.`````

<a id="00685cff-29baed74"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12473, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chat-create-tabs.md'.`````

<a id="de0bbbbb-29baed74"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve [...]

2020-11-10 06:52 UTC, opbld32 commented
Docs Build status updates of commit _[6b290c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b290c6917fd1f32b7a6bb34656222663f76391a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-420cf5e9-cab9c8bd)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) | [Details](#user-content-00685cff-cab9c8bd)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-cab9c8bd)
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-create-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-create-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-create-chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="420cf5e9-cab9c8bd"></a>
### [api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md)
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-create-tabs.md'.`````

<a id="00685cff-cab9c8bd"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml)
 - **Line 12473, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chat-create-tabs.md'.`````

<a id="de0bbbbb-cab9c8bd"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve [...]

2020-11-10 07:03 UTC, opbld33 commented
Docs Build status updates of commit _[fcb67ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fcb67ec085b1278f99d19073d63aa438b2572e5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-422a5c85)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-422a5c85"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view [...]

2020-11-10 07:41 UTC, opbld33 commented
Docs Build status updates of commit _[f657339](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f65733970b0898f0b4eb74d9fa2fb6bb40efecb4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-52816480)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-52816480"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view [...]

2020-11-10 08:06 UTC, opbld34 commented
Docs Build status updates of commit _[18edbbb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/18edbbb119915588d3c3f550e776bead28a4085e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-3cd62c2e)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-3cd62c2e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view [...]

2020-11-10 08:07 UTC, opbld31 commented
Docs Build status updates of commit _[fbe846f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fbe846f0e72c696307f8d292dc6b057bef99f6ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-0d2c574a)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-0d2c574a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view [...]

2020-11-10 08:54 UTC, opbld34 commented
Docs Build status updates of commit _[de5dde9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de5dde9ac3619fd478604b4726897f7e1b9f9a4d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-0523052c)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-0523052c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view [...]

2020-11-10 08:56 UTC, opbld30 commented
Docs Build status updates of commit _[daff95c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/daff95cdebbb13e932af340e55f622c4b525d0a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-f9a572b6)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-f9a572b6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view [...]

2020-11-10 09:14 UTC, opbld32 commented
Docs Build status updates of commit _[89619c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89619c402c987cafec713d848ad95a6cf4b36644)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-4805bd3d)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-4805bd3d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tru [...]

2020-11-10 12:16 UTC, opbld34 commented
Docs Build status updates of commit _[9f9ab98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f9ab981f056b7f18eabcf702f26aa7c352886f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-8ecf49bb)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-8ecf49bb"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true [...]

2020-11-10 12:22 UTC, opbld33 commented
Docs Build status updates of commit _[3c0e873](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c0e87370195bd08e92015f3ff8acab000cadd74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-24360ba7)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-24360ba7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true [...]

2020-11-10 12:23 UTC, opbld33 commented
Docs Build status updates of commit _[295be41](https://github.com/microsoftgraph/microsoft-graph-docs/commits/295be41562f2af56c4b03356be9cfea626ef0d30)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-45fcba28)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-45fcba28"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true [...]

2020-11-11 04:15 UTC, opbld32 commented
Docs Build status updates of commit _[2ce1ab9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ce1ab99e1728cef57440ea617686359b3763d83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-21a6024d)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-21a6024d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true [...]

2020-11-11 04:19 UTC, opbld33 commented
Docs Build status updates of commit _[82742ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82742ceda035447a7f6891632a80869ae59fa67b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-5534ddf5)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-5534ddf5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true [...]

2020-11-11 10:15 UTC, opbld33 commented
Docs Build status updates of commit _[102c514](https://github.com/microsoftgraph/microsoft-graph-docs/commits/102c5144800281384378cb335f75a061afb79ee8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-2233c02c)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-2233c02c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true [...]

2020-11-11 13:03 UTC, opbld30 commented
Docs Build status updates of commit _[b05b43e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b05b43ee1118422e21a9730eab73648514038787)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-8ff1503e)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-8ff1503e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true [...]

2020-11-12 04:13 UTC, opbld32 commented
Docs Build status updates of commit _[c08792f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c08792f2d86be541970fe77c4f006a3b4bd6a424)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3a9d95a8)

<a id="3a9d95a8"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011120413097362-10199%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=o8ajFMj2nJHUY1kQmc3jNkvKHkLs4dxKIwcAXSkR9h0%3D&st=2020-11-12T04%3A08%3A37Z&se=2020-12-13T04%3A13%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 05:17 UTC, opbld32 commented
Docs Build status updates of commit _[a28f1a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a28f1a99d79b33c175f9ebfc7ed5e7e5116be54b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-041514af)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-041514af"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 3388, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '|Change type|Version|Description|
|:---|:---|:---|
|Addition|beta|Added new entities:<br/>androidWorkProfileCompliancePolicy<br/>easEmailProfileConfigurationBase<br/>mobileAppIntentAndState<br/>mobileAppTroubleshootingEvent<br/>unsupportedDeviceConfiguration<br/>windowsKioskConfiguration<br/>|
|Addition|beta|Added new complex types:<br/>managedDeviceCleanupSettings<br/>mobileAppIntentAndStateDetail<br/>mobileAppTroubleshootingAppPolicyCreationHistory<br/>mobileAppTroubleshootingAppStateHistory<br/>mobileAppTroubleshootingAppTargetHistory<br/>mobileAppTroubleshootingAppUpdateHistory<br/>mobileAppTroubleshootingDeviceCheckinHistory<br/>mobileAppTroubleshootingHistoryItem<br/>unsupportedDeviceConfigurationDetail<br/>windowsAutoPilotEnrollmentSettings<br/>windowsKioskActiveDirectoryGroup<br/>windowsKioskAppBase<br/>windowsKioskAppConfiguration<br/>windowsKioskAutologon<br/>windowsKioskAzureADGroup<br/>windowsKioskAzureADUser<br/>windowsKioskDesktopApp<br/>windowsKioskLocalGroup<br/>windowsKioskLocalUser<br/>windowsKioskMultipleApps<br/>windowsKioskProfile<br/>windowsKioskSingleUWPApp<br/>windowsKioskUser<br/>windowsKioskUWPApp<br/>windowsKioskVisitor<br/>|
|Addition|beta|Added new enum types:<br/>defenderScheduleScanDay<br/>defenderSubmitSamplesConsentType<br/>domainNameSource<br/>localSecurityOptionsSmartCardRemovalBehaviorType<br/>mobileAppActionType<br/>mobileAppIntent<br/>roleAssignmentScopeType<br/>usernameSource<br/>windowsDeviceUsageType<br/>|
|Addition|beta|Added the setDeviceName<br/>action on managedDevice |
|Deletion|beta|Removed the following entities:<br/>depEnrollmentProfile<br/>enrollmentProfile<br/>importedAppleDeviceIdentity<br/>importedAppleDeviceIdentityResult<br/>|
|Deletion|beta|Removed the following complex types:<br/>managementCertificateWithThumbprint<br/>|
|Deletion|beta|Removed the following enum types:<br/>depTokenType<br/>discoverySource<br/>iTunesPairingMode<br/>|
Deletion|beta|Removed the importAppleDeviceIdentityList action on importedAppleDeviceIdentity collection |
|Deletion|beta|Removed the updateDeviceProfileAssignment action on enrollmentProfile |
|Deletion|beta|Removed the setDefaultProfile action on enrollmentProfile |
|Deletion|beta|Removed the shareForSchoolDataSyncService action on depOnboardingSetting |
|Deletion|beta|Removed the unshareForSchoolDataSyncService action on depOnboardingSetting |
|Deletion|beta|Removed the exportMobileConfig](/graph/api/intune_corpenrollment_enrollmentprofile_exportmobileconfig?view=graph-rest-beta) function on enrollmentProfile |
|Addition|beta|Added the userDomainNameSource and customDomainName properties to the androidEasEmailProfileConfiguration entity|
|Addition|beta|Added the workProfileBlockCamera and workProfileBlockCrossProfileContactsSearch properties to the androidForWorkGeneralDeviceConfiguration entity|
|Addition|beta|Added the workProfileBlo [...]

2020-11-17 08:58 UTC, opbld33 commented
Docs Build status updates of commit _[8e73247](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e7324763915ecda047b80907e1f77bf7dac7842)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-cfc138cf)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-cfc138cf"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 3388, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '|Change type|Version|Description|
|:---|:---|:---|
|Addition|beta|Added new entities:<br/>androidWorkProfileCompliancePolicy<br/>easEmailProfileConfigurationBase<br/>mobileAppIntentAndState<br/>mobileAppTroubleshootingEvent<br/>unsupportedDeviceConfiguration<br/>windowsKioskConfiguration<br/>|
|Addition|beta|Added new complex types:<br/>managedDeviceCleanupSettings<br/>mobileAppIntentAndStateDetail<br/>mobileAppTroubleshootingAppPolicyCreationHistory<br/>mobileAppTroubleshootingAppStateHistory<br/>mobileAppTroubleshootingAppTargetHistory<br/>mobileAppTroubleshootingAppUpdateHistory<br/>mobileAppTroubleshootingDeviceCheckinHistory<br/>mobileAppTroubleshootingHistoryItem<br/>unsupportedDeviceConfigurationDetail<br/>windowsAutoPilotEnrollmentSettings<br/>windowsKioskActiveDirectoryGroup<br/>windowsKioskAppBase<br/>windowsKioskAppConfiguration<br/>windowsKioskAutologon<br/>windowsKioskAzureADGroup<br/>windowsKioskAzureADUser<br/>windowsKioskDesktopApp<br/>windowsKioskLocalGroup<br/>windowsKioskLocalUser<br/>windowsKioskMultipleApps<br/>windowsKioskProfile<br/>windowsKioskSingleUWPApp<br/>windowsKioskUser<br/>windowsKioskUWPApp<br/>windowsKioskVisitor<br/>|
|Addition|beta|Added new enum types:<br/>defenderScheduleScanDay<br/>defenderSubmitSamplesConsentType<br/>domainNameSource<br/>localSecurityOptionsSmartCardRemovalBehaviorType<br/>mobileAppActionType<br/>mobileAppIntent<br/>roleAssignmentScopeType<br/>usernameSource<br/>windowsDeviceUsageType<br/>|
|Addition|beta|Added the setDeviceName<br/>action on managedDevice |
|Deletion|beta|Removed the following entities:<br/>depEnrollmentProfile<br/>enrollmentProfile<br/>importedAppleDeviceIdentity<br/>importedAppleDeviceIdentityResult<br/>|
|Deletion|beta|Removed the following complex types:<br/>managementCertificateWithThumbprint<br/>|
|Deletion|beta|Removed the following enum types:<br/>depTokenType<br/>discoverySource<br/>iTunesPairingMode<br/>|
Deletion|beta|Removed the importAppleDeviceIdentityList action on importedAppleDeviceIdentity collection |
|Deletion|beta|Removed the updateDeviceProfileAssignment action on enrollmentProfile |
|Deletion|beta|Removed the setDefaultProfile action on enrollmentProfile |
|Deletion|beta|Removed the shareForSchoolDataSyncService action on depOnboardingSetting |
|Deletion|beta|Removed the unshareForSchoolDataSyncService action on depOnboardingSetting |
|Deletion|beta|Removed the exportMobileConfig](/graph/api/intune_corpenrollment_enrollmentprofile_exportmobileconfig?view=graph-rest-beta) function on enrollmentProfile |
|Addition|beta|Added the userDomainNameSource and customDomainName properties to the androidEasEmailProfileConfiguration entity|
|Addition|beta|Added the workProfileBlockCamera and workProfileBlockCrossProfileContactsSearch properties to the androidForWorkGeneralDeviceConfiguration entity|
|Addition|beta|Added the workProfileBlo [...]

2020-11-17 09:04 UTC, opbld31 commented
Docs Build status updates of commit _[e5f49e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e5f49e1dc824d90e425347aa3b0e7b5d0d946a98)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-7609d72a)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-7609d72a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 3388, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '|Change type|Version|Description|
|:---|:---|:---|
|Addition|beta|Added new entities:<br/>androidWorkProfileCompliancePolicy<br/>easEmailProfileConfigurationBase<br/>mobileAppIntentAndState<br/>mobileAppTroubleshootingEvent<br/>unsupportedDeviceConfiguration<br/>windowsKioskConfiguration<br/>|
|Addition|beta|Added new complex types:<br/>managedDeviceCleanupSettings<br/>mobileAppIntentAndStateDetail<br/>mobileAppTroubleshootingAppPolicyCreationHistory<br/>mobileAppTroubleshootingAppStateHistory<br/>mobileAppTroubleshootingAppTargetHistory<br/>mobileAppTroubleshootingAppUpdateHistory<br/>mobileAppTroubleshootingDeviceCheckinHistory<br/>mobileAppTroubleshootingHistoryItem<br/>unsupportedDeviceConfigurationDetail<br/>windowsAutoPilotEnrollmentSettings<br/>windowsKioskActiveDirectoryGroup<br/>windowsKioskAppBase<br/>windowsKioskAppConfiguration<br/>windowsKioskAutologon<br/>windowsKioskAzureADGroup<br/>windowsKioskAzureADUser<br/>windowsKioskDesktopApp<br/>windowsKioskLocalGroup<br/>windowsKioskLocalUser<br/>windowsKioskMultipleApps<br/>windowsKioskProfile<br/>windowsKioskSingleUWPApp<br/>windowsKioskUser<br/>windowsKioskUWPApp<br/>windowsKioskVisitor<br/>|
|Addition|beta|Added new enum types:<br/>defenderScheduleScanDay<br/>defenderSubmitSamplesConsentType<br/>domainNameSource<br/>localSecurityOptionsSmartCardRemovalBehaviorType<br/>mobileAppActionType<br/>mobileAppIntent<br/>roleAssignmentScopeType<br/>usernameSource<br/>windowsDeviceUsageType<br/>|
|Addition|beta|Added the setDeviceName<br/>action on managedDevice |
|Deletion|beta|Removed the following entities:<br/>depEnrollmentProfile<br/>enrollmentProfile<br/>importedAppleDeviceIdentity<br/>importedAppleDeviceIdentityResult<br/>|
|Deletion|beta|Removed the following complex types:<br/>managementCertificateWithThumbprint<br/>|
|Deletion|beta|Removed the following enum types:<br/>depTokenType<br/>discoverySource<br/>iTunesPairingMode<br/>|
Deletion|beta|Removed the importAppleDeviceIdentityList action on importedAppleDeviceIdentity collection |
|Deletion|beta|Removed the updateDeviceProfileAssignment action on enrollmentProfile |
|Deletion|beta|Removed the setDefaultProfile action on enrollmentProfile |
|Deletion|beta|Removed the shareForSchoolDataSyncService action on depOnboardingSetting |
|Deletion|beta|Removed the unshareForSchoolDataSyncService action on depOnboardingSetting |
|Deletion|beta|Removed the exportMobileConfig](/graph/api/intune_corpenrollment_enrollmentprofile_exportmobileconfig?view=graph-rest-beta) function on enrollmentProfile |
|Addition|beta|Added the userDomainNameSource and customDomainName properties to the androidEasEmailProfileConfiguration entity|
|Addition|beta|Added the workProfileBlockCamera and workProfileBlockCrossProfileContactsSearch properties to the androidForWorkGeneralDeviceConfiguration entity|
|Addition|beta|Added the workProfileBlo [...]

2020-11-17 09:11 UTC, opbld32 commented
Docs Build status updates of commit _[56433eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56433eb6e6d6359c9b931b749b5840ed4ad67c7a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-88a0e507)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-88a0e507"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 3388, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '|Change type|Version|Description|
|:---|:---|:---|
|Addition|beta|Added new entities:<br/>androidWorkProfileCompliancePolicy<br/>easEmailProfileConfigurationBase<br/>mobileAppIntentAndState<br/>mobileAppTroubleshootingEvent<br/>unsupportedDeviceConfiguration<br/>windowsKioskConfiguration<br/>|
|Addition|beta|Added new complex types:<br/>managedDeviceCleanupSettings<br/>mobileAppIntentAndStateDetail<br/>mobileAppTroubleshootingAppPolicyCreationHistory<br/>mobileAppTroubleshootingAppStateHistory<br/>mobileAppTroubleshootingAppTargetHistory<br/>mobileAppTroubleshootingAppUpdateHistory<br/>mobileAppTroubleshootingDeviceCheckinHistory<br/>mobileAppTroubleshootingHistoryItem<br/>unsupportedDeviceConfigurationDetail<br/>windowsAutoPilotEnrollmentSettings<br/>windowsKioskActiveDirectoryGroup<br/>windowsKioskAppBase<br/>windowsKioskAppConfiguration<br/>windowsKioskAutologon<br/>windowsKioskAzureADGroup<br/>windowsKioskAzureADUser<br/>windowsKioskDesktopApp<br/>windowsKioskLocalGroup<br/>windowsKioskLocalUser<br/>windowsKioskMultipleApps<br/>windowsKioskProfile<br/>windowsKioskSingleUWPApp<br/>windowsKioskUser<br/>windowsKioskUWPApp<br/>windowsKioskVisitor<br/>|
|Addition|beta|Added new enum types:<br/>defenderScheduleScanDay<br/>defenderSubmitSamplesConsentType<br/>domainNameSource<br/>localSecurityOptionsSmartCardRemovalBehaviorType<br/>mobileAppActionType<br/>mobileAppIntent<br/>roleAssignmentScopeType<br/>usernameSource<br/>windowsDeviceUsageType<br/>|
|Addition|beta|Added the setDeviceName<br/>action on managedDevice |
|Deletion|beta|Removed the following entities:<br/>depEnrollmentProfile<br/>enrollmentProfile<br/>importedAppleDeviceIdentity<br/>importedAppleDeviceIdentityResult<br/>|
|Deletion|beta|Removed the following complex types:<br/>managementCertificateWithThumbprint<br/>|
|Deletion|beta|Removed the following enum types:<br/>depTokenType<br/>discoverySource<br/>iTunesPairingMode<br/>|
Deletion|beta|Removed the importAppleDeviceIdentityList action on importedAppleDeviceIdentity collection |
|Deletion|beta|Removed the updateDeviceProfileAssignment action on enrollmentProfile |
|Deletion|beta|Removed the setDefaultProfile action on enrollmentProfile |
|Deletion|beta|Removed the shareForSchoolDataSyncService action on depOnboardingSetting |
|Deletion|beta|Removed the unshareForSchoolDataSyncService action on depOnboardingSetting |
|Deletion|beta|Removed the exportMobileConfig](/graph/api/intune_corpenrollment_enrollmentprofile_exportmobileconfig?view=graph-rest-beta) function on enrollmentProfile |
|Addition|beta|Added the userDomainNameSource and customDomainName properties to the androidEasEmailProfileConfiguration entity|
|Addition|beta|Added the workProfileBlockCamera and workProfileBlockCrossProfileContactsSearch properties to the androidForWorkGeneralDeviceConfiguration entity|
|Addition|beta|Added the workProfileBlo [...]

2020-11-17 09:20 UTC, opbld30 commented
Docs Build status updates of commit _[e683943](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e683943b09bc9aabbae0330c751fb91d7c76a19d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-0d52ab22)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-0d52ab22"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 3388, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '|Change type|Version|Description|
|:---|:---|:---|
|Addition|beta|Added new entities:<br/>androidWorkProfileCompliancePolicy<br/>easEmailProfileConfigurationBase<br/>mobileAppIntentAndState<br/>mobileAppTroubleshootingEvent<br/>unsupportedDeviceConfiguration<br/>windowsKioskConfiguration<br/>|
|Addition|beta|Added new complex types:<br/>managedDeviceCleanupSettings<br/>mobileAppIntentAndStateDetail<br/>mobileAppTroubleshootingAppPolicyCreationHistory<br/>mobileAppTroubleshootingAppStateHistory<br/>mobileAppTroubleshootingAppTargetHistory<br/>mobileAppTroubleshootingAppUpdateHistory<br/>mobileAppTroubleshootingDeviceCheckinHistory<br/>mobileAppTroubleshootingHistoryItem<br/>unsupportedDeviceConfigurationDetail<br/>windowsAutoPilotEnrollmentSettings<br/>windowsKioskActiveDirectoryGroup<br/>windowsKioskAppBase<br/>windowsKioskAppConfiguration<br/>windowsKioskAutologon<br/>windowsKioskAzureADGroup<br/>windowsKioskAzureADUser<br/>windowsKioskDesktopApp<br/>windowsKioskLocalGroup<br/>windowsKioskLocalUser<br/>windowsKioskMultipleApps<br/>windowsKioskProfile<br/>windowsKioskSingleUWPApp<br/>windowsKioskUser<br/>windowsKioskUWPApp<br/>windowsKioskVisitor<br/>|
|Addition|beta|Added new enum types:<br/>defenderScheduleScanDay<br/>defenderSubmitSamplesConsentType<br/>domainNameSource<br/>localSecurityOptionsSmartCardRemovalBehaviorType<br/>mobileAppActionType<br/>mobileAppIntent<br/>roleAssignmentScopeType<br/>usernameSource<br/>windowsDeviceUsageType<br/>|
|Addition|beta|Added the setDeviceName<br/>action on managedDevice |
|Deletion|beta|Removed the following entities:<br/>depEnrollmentProfile<br/>enrollmentProfile<br/>importedAppleDeviceIdentity<br/>importedAppleDeviceIdentityResult<br/>|
|Deletion|beta|Removed the following complex types:<br/>managementCertificateWithThumbprint<br/>|
|Deletion|beta|Removed the following enum types:<br/>depTokenType<br/>discoverySource<br/>iTunesPairingMode<br/>|
Deletion|beta|Removed the importAppleDeviceIdentityList action on importedAppleDeviceIdentity collection |
|Deletion|beta|Removed the updateDeviceProfileAssignment action on enrollmentProfile |
|Deletion|beta|Removed the setDefaultProfile action on enrollmentProfile |
|Deletion|beta|Removed the shareForSchoolDataSyncService action on depOnboardingSetting |
|Deletion|beta|Removed the unshareForSchoolDataSyncService action on depOnboardingSetting |
|Deletion|beta|Removed the exportMobileConfig](/graph/api/intune_corpenrollment_enrollmentprofile_exportmobileconfig?view=graph-rest-beta) function on enrollmentProfile |
|Addition|beta|Added the userDomainNameSource and customDomainName properties to the androidEasEmailProfileConfiguration entity|
|Addition|beta|Added the workProfileBlockCamera and workProfileBlockCrossProfileContactsSearch properties to the androidForWorkGeneralDeviceConfiguration entity|
|Addition|beta|Added the workProfileBlo [...]

2020-11-17 09:31 UTC, opbld30 commented
Docs Build status updates of commit _[e066434](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e066434548e9958dd9086f3023dcebe918e03096)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-0e7926dc)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-0e7926dc"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 154, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 154, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 155, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - [...]

2020-11-17 09:37 UTC, opbld31 commented
Docs Build status updates of commit _[193f79c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/193f79c4ba93d6a45b374283b5bb73c6d38b7422)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-bcac16a9)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-bcac16a9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 154, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 154, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 155, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - [...]

2020-11-17 10:21 UTC, opbld32 commented
Docs Build status updates of commit _[4a83bf2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a83bf25babf0e7718a481b6c108d0e7047cd920)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-26219389)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-26219389"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 154, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 154, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 155, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - [...]

2020-11-18 04:53 UTC, opbld33 commented
Docs Build status updates of commit _[a70f0b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a70f0b907c2e6874715bb231985b297769f85151)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-22c44c33)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-22c44c33"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-onboarding-devicecomanagementauthorityconfiguration?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationcategory?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingcollectiondefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicy?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicyassignment?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsetting?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettingdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettinggroupcollectiondefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettinggroupdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link t [...]

2020-11-18 05:38 UTC, opbld31 commented
Docs Build status updates of commit _[0ee043d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ee043d1ce8a96682473ae427e22f8afc8be9336)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-6cac42a4)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-6cac42a4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-onboarding-devicecomanagementauthorityconfiguration?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationcategory?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingcollectiondefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicy?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicyassignment?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsetting?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettingdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettinggroupcollectiondefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettinggroupdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link t [...]

2020-11-18 09:53 UTC, opbld32 commented
Docs Build status updates of commit _[534117c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/534117c653a48f8cf2ff83c01733bff63e22944d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-5744d8ea)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-5744d8ea"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-onboarding-devicecomanagementauthorityconfiguration?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationcategory?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingcollectiondefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicy?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicyassignment?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsetting?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettingdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettinggroupcollectiondefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettinggroupdefinition?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link t [...]

2020-11-19 03:23 UTC, Lauragra commented on api-reference/beta/api/chat-create-tabs.md
> +---
Please update the filename to change create to post, for consistency with our file naming guidelines.

2020-11-19 03:25 UTC, Lauragra commented on api-reference/beta/api/chat-create-tabs.md
> +description: "Creates (pins) a tab to the specified chat. Adds a scrum board tab in the meeting chat by using Graph APIs. "
The description and summary statement should consistent use the imperative verb form "create.

2020-11-19 03:25 UTC, Lauragra commented on api-reference/beta/api/chat-create-tabs.md
> +# Create a tab to the specified chat
Title attribute and H1 should match, "Create tab in chat".

2020-11-19 03:26 UTC, Lauragra commented on api-reference/beta/api/chat-create-tabs.md
> +The corresponding app must already be installed in the chat.Link document for adding apps to chat.
The last sentence about the Link - why is that there? Should there be a cross-reference?

2020-11-19 03:26 UTC, Lauragra commented on api-reference/beta/api/chat-create-tabs.md
> +#### Permissions
Permissions is always an H2 section (##). If you use the stub generator tool to output your files, it will add all the required sections and boilerplate text.

2020-11-19 03:27 UTC, Lauragra commented on api-reference/beta/api/chat-create-tabs.md
> +|Delegated  | TeamsTab.Create, TeamsTab.ReadWrite.All  |
The permissions table is not consistent; please update per all API topics.

2020-11-19 03:28 UTC, Lauragra commented on api-reference/beta/api/chat-create-tabs.md
> +POST /chats/{chatId}/tabs
Global: Ideally, examples use real IDs rather than placeholders. Examples also use the full URL, as opposed to the syntax as per the HTTP request section.

2020-11-19 03:30 UTC, Lauragra commented on api-reference/beta/api/chat-create-tabs.md
> +### Example : Create tabs in a Teams chat
When you have multiple examples, under the single H2 Examples, add H3s for each example, and preface each with Example {n}: {description}. So the previous example becomes Example 1, this is Example 2. Then the Request and Response sections are H4s under each example.

2020-11-19 03:33 UTC, Lauragra commented on api-reference/beta/api/chat-create-tabs.md
> +The following example shows a request to create all chats.
Is this the right description? Does this create tabs in a chat? Also, how is this example different than the previous?

2020-11-19 03:35 UTC, Lauragra commented on api-reference/beta/api/chat-create-tabs.md
> +  "name": "create-tab in chat"
FYI, I always see these names separated with underscores, not with spaces in them. I recommend being consistent here in case it leads to issues with API Doctor later. Also, if you do have two examples in this topic, you'll want to give each a unique name.

2020-11-19 03:39 UTC, Lauragra commented on api-reference/beta/api/chat-delete-tabs.md
> +---
Delete operations are performed on the entity, not the nav property, so per our file naming guidelines, this file name should be teamstab-delete.

2020-11-19 03:40 UTC, Lauragra commented on api-reference/beta/api/chat-delete-tabs.md
> +title: "Delete tab from chat"
Title/H1 should be "Delete teamsTab".

2020-11-19 03:41 UTC, Lauragra commented on api-reference/beta/api/chat-delete-tabs.md
> +Removes (unpins) a tab from the specified [chat](../resources/chat.md).
Use imperative - Remove (unpin).

2020-11-19 03:42 UTC, Lauragra commented on api-reference/beta/api/chat-delete-tabs.md
> +|Delegated  |TeamsTab.ReadWrite.All  |
Update the permissions table.

2020-11-19 03:43 UTC, Lauragra commented on api-reference/beta/api/chat-delete-tabs.md
> +The following is an example of the response. Note: The response object shown here may be truncated for brevity. All of the properties will be returned from an actual call.
Remove the second sentence - this note (which is old boilerplate text) doesn't apply when there is no response body.

2020-11-19 03:44 UTC, Lauragra commented on api-reference/beta/api/chat-delete-tabs.md
> +## Example
I have the same feedback on the Examples section as per the previous, not sure why there are two and if the intent is to illustrate different things. You can likely just use the second example since it already uses the full URL.

2020-11-19 03:46 UTC, Lauragra commented on api-reference/beta/api/chat-delete-tabs.md
> +DELETE /chats/19:75a0894119a0468caee5811901a75ffd@thread.tacv2/tabs/{id}
Whatever example or examples you use in the topic need to show the full URL. This one has a real ID so probably better to use.

2020-11-19 03:48 UTC, Lauragra commented on api-reference/beta/api/chat-get-tabs.md
> +---
Filename - teamstab-get. Title/H1 - Get teamsTab.

2020-11-19 03:50 UTC, Lauragra commented on api-reference/beta/api/chat-get-tabs.md
> +Retrieve the properties and relationships of the specified [tab](../resources/teamstab.md) inside a chat. Get a specific Scrum Board tab in a Teams chat using the displayName of the tab. To verify if
What is the thinking behind the text about the Scrum Board? Are you describing some type of example?

2020-11-19 03:50 UTC, Lauragra commented on api-reference/beta/api/chat-get-tabs.md
> +|Delegated  | TeamsTab.Create, TeamsTab.ReadWrite.All  |
Update the permissions table.

2020-11-19 03:51 UTC, Lauragra commented on api-reference/beta/api/chat-get-tabs.md
> +This method supports the `$select` and `$expand` [OData query parameters](/graph/query-parameters) to help customize the response.
Does it also support $filter, per the text in the summary section?

2020-11-19 03:52 UTC, Lauragra commented on api-reference/beta/api/chat-get-tabs.md
> +## Example
Same feedback about the duplicate examples here and the inconsistent structure.

2020-11-19 03:52 UTC, opbld34 commented
Docs Build status updates of commit _[285a442](https://github.com/microsoftgraph/microsoft-graph-docs/commits/285a44290e22555b22a0206701259dcac2b68933)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-35161f29)
[api-reference/beta/api/chat-create-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-create-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-create-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-35161f29"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 186, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 186, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 187, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 188, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 189, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 189, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 189, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 189, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 189, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 189, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 189, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 190, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 190, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - [...]

2020-11-19 03:53 UTC, Lauragra commented on api-reference/beta/api/chat-create-tabs.md
> +author: "nkramer"
Do you want to put your name as author or is everything still assigned to Nick?

2020-11-19 03:57 UTC, Lauragra commented on api-reference/beta/api/chat-list-tabs.md
> +|Delegated  | TeamsTab.Create, TeamsTab.ReadWrite.All  |
Update table.

2020-11-19 03:57 UTC, Lauragra commented on api-reference/beta/api/chat-list-tabs.md
> +This method supports the $filter, $select, and $expand [OData query parameters](/graph/query-parameters) to help customize the response.
Please format query parameters with tic marks (`).

2020-11-19 03:58 UTC, Lauragra commented on api-reference/beta/api/chat-list-tabs.md
> +## Example
Same feedback regarding the examples.

2020-11-19 04:00 UTC, Lauragra commented on api-reference/beta/api/chat-update-tabs.md
> +title: "Update tab in chat "
Filename should be teamstab-update. Topic title should be Update teamsTab.

2020-11-19 04:00 UTC, Lauragra commented on api-reference/beta/api/chat-update-tabs.md
> +Update the properties of the specified [tab](../resources/teamstab.md) in chat.
in chat -> in a chat in both sentences.

2020-11-19 04:00 UTC, Lauragra commented on api-reference/beta/api/chat-update-tabs.md
> +|:--------------------|:---------------------------------|
Update table.

2020-11-19 04:01 UTC, Lauragra commented on api-reference/beta/api/chat-update-tabs.md
> +| Content-Type  | application/json  |
Add that the Content-type header is required.

2020-11-19 04:01 UTC, Lauragra commented on api-reference/beta/api/chat-update-tabs.md
> +## Example
Same feedback regarding the Examples.

2020-11-19 15:02 UTC, KirtiPereira commented on api-reference/beta/api/chat-delete-tabs.md
> +---
A file with the name teamstab-delete.md already exists in beta and v1.0. 
The file was initially named as "teamstab-chat-delete" but was changed to "chat-delete-tabs" after recommendation from the SME.
Please suggest if need to rename as "teamstab-delete-chat" or "teamstab-chat-delete".  Will need to rename all the related files to follow the convention.

2020-11-19 15:31 UTC, KirtiPereira commented on api-reference/beta/api/chat-get-tabs.md
> +---
A file with the name teamstab-get.md already exists in beta and v1.0.
The file was initially named as "teamstab-chat-get" but was changed to "chat-get-tabs" after recommendation from the SME.
Please suggest if need to rename as "teamstab-get-chat" or "teamstab-chat-get". Will need to rename all the related files to follow the convention.

Updated Title/H1 of the comment.

2020-11-20 01:00 UTC, Lauragra commented on api-reference/beta/api/teamstab-get.md
> +title: "Get tab in channel"
This topic should remain teamstab-get, and per my comment earlier, it should include the syntax for getting a tab from both a chat and a channel. This is consistent with our file naming guidelines. The title/H1 should be Get teamsTab. We don't need two separate topics for Get, Delete, and Update for the nav property on the chat and channel resources.

2020-11-20 01:00 UTC, Lauragra commented on api-reference/beta/api/teamstab-update.md
> +title: "Update tab in channel"
Same comment here, this topic can cover the update scenario for both chat and channel.

2020-11-20 01:01 UTC, Lauragra commented on api-reference/beta/resources/teamstab.md
> +A teamsTab is a [tab](../resources/teamstab.md) that's pinned (attached) to a [channel](channel.md) and a [chat](chat.md).
No need to repeat the resource name; the description can be "Represents a tab that's pinned to a channel or a chat." I assume it should be or, not and, since the tab can be pinned to either place?

2020-11-20 01:02 UTC, Lauragra commented on api-reference/beta/resources/teamstab.md
> +|[List tabs in channel](../api/teamstab-list.md) | [teamsTab](teamstab.md) | Lists tabs pinned to a channel.|
You will need to update the list of methods. Only List and Create operations should be specific to the nav property of the individual resources; the Get, Update, and Delete operations can be general to both.

2020-11-20 01:03 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: List tabs in channel
Please adjust the TOC entries accordingly as well.

2020-11-20 01:04 UTC, Lauragra commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the **createdDateTime** property to the [channel](https://docs.microsoft.com/graph/api/resources/channel?view=graph-rest-beta) and [team](https://docs.microsoft.com/gr
Please keep the en-us in the URLs; that is required for links published to the developer site (the filterable changelog renders on the Graph dev site, not on Docs).

2020-11-20 01:04 UTC, Lauragra commented on changelog/Microsoft.Teams.Core.json
> +          "ChangedApiName": "chat-list-tabs, chat-get-tabs, chat-create-tabs, chat-delete-tabs, chat-update-tabs, teamstab",
The changed API name can just be chat, for simplicity.

2020-11-20 01:05 UTC, Lauragra commented on changelog/Microsoft.Teams.Core.json
> +          "Id": "58fde3b2-9416-4226-a260-6405935ff290",
The date of the new changelist item should be November, or whenever we plan to publish this PR (might slip to December).

2020-11-20 01:06 UTC, Lauragra commented on concepts/changelog.md
> +>>>>>>> origin
Looks like a bad merge conflict resolution?

2020-11-20 01:06 UTC, Lauragra commented on concepts/changelog.md
> +|Addition|beta|Added support for **completeMigration** to the [channel](/graph/api/resources/channel?view=graph-rest-beta) and [team](/graph/api/resources/team?view=graph-rest-beta) resources|
Are all these changes related to this PR? For the ones specific to this PR, they should be listed under November (or December) in the changelog.md file.

2020-11-20 01:07 UTC, Lauragra requested changes
Please resolve editorial comments.

2020-11-20 01:08 UTC, Lauragra commented
@laujan , @KirtiPereira , I see comments that I made on this PR yesterday marked as resolved, but I don't see the fixes in the files. Did you commit any updates based on my comments?

2020-11-20 01:15 UTC, Lauragra commented on api-reference/beta/api/chat-get-tabs.md
> +---
Please see my comments on the teamstab-get topic. That topic should cover the scenarios for chat and channel. For reference, see our CDK guidance about topic titles and file names: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55061/File-naming, https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55080/ToC-and-topic-title.

2020-11-20 01:15 UTC, Lauragra commented on api-reference/beta/api/chat-delete-tabs.md
> +---
Please see my additional comments on the PR.

2020-11-20 13:29 UTC, opbld33 commented
Docs Build status updates of commit _[4f71636](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f71636f4f6055060c1831ae89901db109186b62)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-0177120b)
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-0177120b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 186, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 186, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 187, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Line 188, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 189, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 189, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 189, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 189, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 189, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 189, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 189, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 190, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 190, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-beta`````
 - **Lin [...]

2020-11-20 13:54 UTC, opbld32 commented
Docs Build status updates of commit _[38d9e5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/38d9e5cebe99d9b4400ce34fa8fcb59802411110)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-36d42bdd)
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-36d42bdd"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011201352452139-10199%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1hmT8tNUH4233yc5In3ec8ZcBhH8g0%2BHsdeCtB0QZoI%3D&st=2020-11-20T13%3A49%3A05Z&se=2020-12-21T13%3A54%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 14:04 UTC, KirtiPereira commented on concepts/changelog.md
> +|Addition|beta|Added support for **completeMigration** to the [channel](/graph/api/resources/channel?view=graph-rest-beta) and [team](/graph/api/resources/team?view=graph-rest-beta) resources|
Updated the Changelog. Have kept the details under November for now. If PR gets pushed out to next month, will update the details accordingly.

2020-11-24 13:26 UTC, KirtiPereira commented on api-reference/beta/resources/teamstab.md
> +A teamsTab is a [tab](../resources/teamstab.md) that's pinned (attached) to a [channel](channel.md) and a [chat](chat.md).
@AkJo - please confirm if we are still going with the merging of the three files as suggested by Laura in her comments or if they will be separate files?
Keep **chat-post-tabs** and **chat-list-tabs** files but merge the other three as listed below. 	
        chat-update-tabs >> teamstab-update 
	chat-get-tabs >> teamstab-get 
	chat-delete-tabs >> teamstab-delete
Have shared the query with you on Teams channel as well.
Thank you.

2020-11-24 13:48 UTC, opbld32 commented
Docs Build status updates of commit _[a16a860](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a16a860c77e418d8374e55029d3654429db690e0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-656b24ac)

<a id="656b24ac"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011241347324236-10199%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sT50e3DlgjMmJXxtFiop3dFWnBYUPHE%2FY%2FG5zac%2FlKI%3D&st=2020-11-24T13%3A43%3A44Z&se=2020-12-25T13%3A48%3A44Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-24 14:11 UTC, opbld34 commented
Docs Build status updates of commit _[4f60569](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f60569fd8f47c13f2e7a56d31098ce80b2d9fec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011241408491783-10199%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Azfl2agJH3UaACD%2FEX9ciof9NF9FCOIFywINWGNw%2B58%3D&st=2020-11-24T14%3A06%3A10Z&se=2020-12-25T14%3A11%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-30 08:46 UTC, opbld30 commented
Docs Build status updates of commit _[86d24b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/86d24b35dfd5506c241b1d780be1b75872f0c490)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011300845209341-10199%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=n%2FjZDUo8QICOvdMzAXndGhBC21e3UsmhUgJDBFDiyO8%3D&st=2020-11-30T08%3A41%3A45Z&se=2020-12-31T08%3A46%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-01 01:36 UTC, nkramer commented on concepts/changelog.md
> +|Addition|beta|Added [create](/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&preserve-view=true), [delete](/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta
Why are we changing anything here?

2020-12-01 03:43 UTC, KirtiPereira commented on concepts/changelog.md
> +|Addition|beta|Added [create](/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&preserve-view=true), [delete](/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta
Moved the details related to this PR under December 2020 section.
![image](https://user-images.githubusercontent.com/70375155/100694610-73cf6180-33b5-11eb-9036-0ca1991c2a3e.png)

2020-12-04 09:48 UTC, opbld32 commented
Docs Build status updates of commit _[cab9363](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cab936396f453676b89983be5002a12bc5256876)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-29880d4f)
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-29880d4f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 104, Column 1**: **[Warning-[merge-conflict](https://aka.ms/merge-conflict)]** `````File contains merge conflict markers.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012040947004421-10199%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=m5tco4b1nG3wPwHsFBc4R%2BJInE5%2FY7TQ8QetPNX4LEA%3D&st=2020-12-04T09%3A43%3A46Z&se=2021-01-04T09%3A48%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 10:32 UTC, opbld33 commented
Docs Build status updates of commit _[277a1e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/277a1e8bdccdb707cebd43e39d33436bc41d801a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012041031031983-10199%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=l2gdlEHzQXdKvS%2BRsfO0aZhoy8zTdCAB9wBUhMmIyNw%3D&st=2020-12-04T10%3A27%3A33Z&se=2021-01-04T10%3A32%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 10:42 UTC, KirtiPereira commented on api-reference/beta/api/chat-create-tabs.md
> +author: "nkramer"
No change.

2020-12-04 11:09 UTC, opbld32 commented
Docs Build status updates of commit _[9855177](https://github.com/microsoftgraph/microsoft-graph-docs/commits/98551773b168e85315e723e4e5d09a92f511a37f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012041107431660-10199%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Bnu%2B8w8uskM0KmWRqEAlz9A3yXdw3QWtc%2Be7nu6fWts%3D&st=2020-12-04T11%3A04%3A06Z&se=2021-01-04T11%3A09%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 19:52 UTC, laujan commented
Hi @AkJo. Will you please review for an engineering sign off? Thank you!

2020-12-07 13:50 UTC, opbld34 commented
Docs Build status updates of commit _[4096327](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4096327b203049a23bacd1565cea20e37ae5d51e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071349171322-10199%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JBRtw3eulOgLr5869FKvp6mWbjpoOHeERe7Y16%2B%2FzXE%3D&st=2020-12-07T13%3A45%3A56Z&se=2021-01-07T13%3A50%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 08:30 UTC, opbld32 commented
Docs Build status updates of commit _[02e2bbd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02e2bbdde61857ac003119c7e238b1f8f11252ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) | [Details](#user-content-de0bbbbb-f53eb1f4)
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-f53eb1f4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080829171121-10199%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2ReI8TYgMDc38nUwAS2Vm4OwhwrFi1hEH04%2BoRSF%2BeU%3D&st=2020-12-08T08%3A25%3A52Z&se=2021-01-08T08%3A30%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 08:33 UTC, opbld32 commented
Docs Build status updates of commit _[be89878](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be89878e161a7f82daae2b82583ef8f019225f9b)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-08 08:35 UTC, opbld31 commented
Docs Build status updates of commit _[be89878](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be89878e161a7f82daae2b82583ef8f019225f9b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/chat-update-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/chat-update-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-update-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/api/teamstab-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10199) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1149664-Tabs-API-for-chats-and-meetings-(beta)/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10199) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080833506366-10199%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MTTTMxqNP7cTjGUygtUavWgtTHWnXQlLhpXpbL%2FTDDI%3D&st=2020-12-08T08%3A30%3A21Z&se=2021-01-08T08%3A35%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-12 01:12 UTC, closed without merging