Adds missing docs for permissionGrantPolicyIdsAssignedToDefaultUserRole
microsoftgraph/microsoft-graph-docs pull request #10211
Opened 2020-10-07 13:16 UTC by psignoret

2020-10-07 13:17 UTC, opbld33 commented
Docs Build status updates of commit _[7a394ab](https://github.com/psignoret/microsoft-graph-docs/commits/7a394ab921a7be3ff7fe0f725d0493e761e4fec8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-update?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) | [Details](#user-content-b5c1731a-e168a513)
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/resources/authorizationpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) | [Details](#user-content-0dc43e3a-e168a513)
[concepts/changelog.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10211) | [Details](#user-content-de0bbbbb-e168a513)
[api-reference/beta/api/authorizationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-get?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |

<a id="b5c1731a-e168a513"></a>
### [api-reference/beta/api/authorizationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-update.md)
 - **Line 58, Column 355**: **[Warning-file-not-found]** `````Invalid file link: 'permissiongrantpolicy.md'.`````
 - **Line 304, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Duplicate tab id: (http, 2).`````
 - **Line 304, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 336, Column 123**: **[Warning-file-not-found]** `````Invalid file link: '../resources/permissiongrantpolicy.md'.`````

<a id="0dc43e3a-e168a513"></a>
### [api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/resources/authorizationpolicy.md)
 - **Line 39, Column 355**: **[Warning-file-not-found]** `````Invalid file link: 'permissiongrantpolicy.md'.`````
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-beta&tabs=http NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-e168a513"></a>
### [concepts/changelog.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Wa [...]

2020-10-07 13:26 UTC, opbld32 commented
Docs Build status updates of commit _[226477c](https://github.com/psignoret/microsoft-graph-docs/commits/226477c8a3e57a313172daf5ec037810d6480a5b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-update?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) | [Details](#user-content-b5c1731a-46d0c45e)
[concepts/changelog.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10211) | [Details](#user-content-de0bbbbb-46d0c45e)
[api-reference/beta/api/authorizationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-get?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |

<a id="b5c1731a-46d0c45e"></a>
### [api-reference/beta/api/authorizationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-update.md)
 - **Line 304, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 340, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="de0bbbbb-46d0c45e"></a>
### [concepts/changelog.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column  [...]

2020-10-07 13:48 UTC, opbld32 commented
Docs Build status updates of commit _[4014930](https://github.com/psignoret/microsoft-graph-docs/commits/4014930dc779860c15ff723dc99cc604cb5c24df)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authorizationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-update?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) | [Details](#user-content-b5c1731a-a2171658)
[concepts/changelog.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10211) | [Details](#user-content-de0bbbbb-a2171658)
[api-reference/beta/api/authorizationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-get?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |

<a id="b5c1731a-a2171658"></a>
### [api-reference/beta/api/authorizationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-update.md)
 - **Line 304, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 340, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="de0bbbbb-a2171658"></a>
### [concepts/changelog.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column  [...]

2020-10-07 13:58 UTC, opbld32 commented
Docs Build status updates of commit _[26eaf3d](https://github.com/psignoret/microsoft-graph-docs/commits/26eaf3d9b682ee65e60bdfb3277cc119a2602375)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10211) | [Details](#user-content-de0bbbbb-81eed552)
[api-reference/beta/api/authorizationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-get?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |
[api-reference/beta/api/authorizationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-update?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |

<a id="de0bbbbb-81eed552"></a>
### [concepts/changelog.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tr [...]

2020-10-07 21:12 UTC, opbld33 commented
Docs Build status updates of commit _[96bdb11](https://github.com/psignoret/microsoft-graph-docs/commits/96bdb1117a6788f9b7151ea9a7317fa660d74582)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-90d1853f)

<a id="90d1853f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010072112284160-10211%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pLHwIZE0cnDCYJuXdlfwja8LPt%2B9R%2F0o2T%2BPb7QnRM0%3D&st=2020-10-07T21%3A07%3A54Z&se=2020-11-07T21%3A12%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-07 21:27 UTC, Lauragra requested changes
Please resolve the merge conflict - is that related to the preserve parameter PR that I just merged? Also, please add a JSON changelog entry to this as well. Otherwise, good to go.

2020-10-07 22:07 UTC, opbld31 commented
Docs Build status updates of commit _[86eba20](https://github.com/psignoret/microsoft-graph-docs/commits/86eba20c0133c03eee416337893f2a6393e01be0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10211) | [Details](#user-content-de0bbbbb-7d89d00d)
[api-reference/beta/api/authorizationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-get?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |
[api-reference/beta/api/authorizationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-update?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |

<a id="de0bbbbb-7d89d00d"></a>
### [concepts/changelog.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tr [...]

2020-10-07 22:17 UTC, opbld30 commented
Docs Build status updates of commit _[a6146e1](https://github.com/psignoret/microsoft-graph-docs/commits/a6146e1c40835abee5561a26a54c8486376329c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10211) | [Details](#user-content-de0bbbbb-9fde018c)
[api-reference/beta/api/authorizationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-get?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |
[api-reference/beta/api/authorizationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-update?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-9fde018c"></a>
### [concepts/changelog.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest- [...]

2020-10-07 22:17 UTC, psignoret commented
@Lauragra OK, added JSON changelog entry as well.

2020-10-07 22:44 UTC, Lauragra approved these changes

2020-10-08 12:54 UTC, opbld32 commented
Docs Build status updates of commit _[3e299e1](https://github.com/psignoret/microsoft-graph-docs/commits/3e299e185f49808765d667e1a905a7bbc235284e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10211) | [Details](#user-content-de0bbbbb-e6ac22c5)
[api-reference/beta/api/authorizationpolicy-get.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-get?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |
[api-reference/beta/api/authorizationpolicy-update.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/api/authorizationpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authorizationpolicy-update?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |
[api-reference/beta/resources/authorizationpolicy.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/api-reference/beta/resources/authorizationpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authorizationpolicy?view=graph-rest-beta&branch=pr-en-us-10211) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-e6ac22c5"></a>
### [concepts/changelog.md](https://github.com/psignoret/microsoft-graph-docs/blob/phsignor-authzpolicy-consent/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest- [...]

2020-10-08 16:21 UTC, merged