Authentication events policy docs for user flow invocation
microsoftgraph/microsoft-graph-docs pull request #10224
Opened 2020-10-08 01:27 UTC by jkdouglas

2020-10-08 01:29 UTC, opbld34 commented
Docs Build status updates of commit _[2810852](https://github.com/microsoftgraph/microsoft-graph-docs/commits/28108525d5c181444764b579d63aab383db21c5f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-2c5a1d87-1fac5f9b)
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-2deb2b80-1fac5f9b)
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-fd652214-1fac5f9b)
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-bad94fcd-1fac5f9b)
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-e6be38b0-1fac5f9b)
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-a60a7d6e-1fac5f9b)
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-fd345cc3-1fac5f9b)
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-21c8eb62-1fac5f9b)
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

<a id="2c5a1d87-1fac5f9b"></a>
### [api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="2deb2b80-1fac5f9b"></a>
### [api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=master)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="fd652214-1fac5f9b"></a>
### [api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md)
 - **Line 54, Column 11**: **[Warning-file-not-found]** `````Invalid file link: '..resources/b2xidentityuserflow.md'.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create onSignupStart - Microsoft Graph beta' is duplicated in: 'beta/api/authenticationeventspolicy-post-onsignupstart.md(2,8), beta/api/authenticationeventspolicy-put-on [...]

2020-10-08 20:07 UTC, saraswatshantanu commented on api-reference/beta/resources/authenticationeventspolicy.md
> +Authentication events are used to invoke user flows at specific points in the authentication flow. When creating authentication events, you are enabling a specific application to be associated with a
Let's say: By assigning invokeUserFlowActions to authentication events, you are enabling a specific application to be ....

Essentially, we need to mention that invokeUserFlowAction is what enables self service sign up. There might be other types of actions in the future that might be for some other purpose.

2020-10-08 20:07 UTC, saraswatshantanu commented on api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md
> +Create a new authenticationAction object.
PUT here is not creating an object. It is changing an existing (identified by {id}) object.

2020-10-08 20:07 UTC, saraswatshantanu commented on api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md
> +POST https://graph.microsoft.com/beta/identity/events/onSignupStart
PUT instead of POST

2020-10-08 20:10 UTC, jkdouglas commented on api-reference/beta/resources/invokeuserflowaction.md
> +  "userFlow": "String"
For the resource files, yes.

2020-10-12 20:56 UTC, jkdouglas commented on api-reference/beta/resources/authenticationeventspolicy.md
> +Authentication events are used to invoke user flows at specific points in the authentication flow. When creating authentication events, you are enabling a specific application to be associated with a
Reworded the description to be more clear that invokeUserFlowAction is one type of authentication event.

2020-10-12 20:58 UTC, opbld32 commented
Docs Build status updates of commit _[4af344c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4af344c9c887e79a5f3222b513dd84615565f4e7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-2c5a1d87-d0648a63)
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-2deb2b80-d0648a63)
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-fd652214-d0648a63)
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-bad94fcd-d0648a63)
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-e6be38b0-d0648a63)
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-a60a7d6e-d0648a63)
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

<a id="2c5a1d87-d0648a63"></a>
### [api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="2deb2b80-d0648a63"></a>
### [api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="fd652214-d0648a63"></a>
### [api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md)
 - **Line 54, Column 11**: **[Warning-file-not-found]** `````Invalid file link: '..resources/b2xidentityuserflow.md'.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create onSignupStart - Microsoft Graph beta' is duplicated in: 'beta/api/authenticationeventspolicy-post-onsignupstart.md(2,8), beta/api/authenticationeventspolicy-put-onsignupstart.md(2,8)'. Titles must be unique within a docset.`````
 - [...]

2020-10-12 21:04 UTC, opbld32 commented
Docs Build status updates of commit _[4c470f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c470f98aed5610177af7ec24354d06a080e853f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-fd652214-38dd9ecd)
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-bad94fcd-38dd9ecd)
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-e6be38b0-38dd9ecd)
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

<a id="fd652214-38dd9ecd"></a>
### [api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md)
 - **Line 54, Column 11**: **[Warning-file-not-found]** `````Invalid file link: '..resources/b2xidentityuserflow.md'.`````

<a id="bad94fcd-38dd9ecd"></a>
### [api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md)
 - **Line 54, Column 11**: **[Warning-file-not-found]** `````Invalid file link: '..resources/b2xidentityuserflow.md'.`````

<a id="e6be38b0-38dd9ecd"></a>
### [api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md)
 - **Line 54, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '..resources/b2xidentityuserflow.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010122103372326-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wlU%2FAi257yo7A1XinrwHOauOuvw3ZlFH2tMv1catdHI%3D&st=2020-10-12T20%3A59%3A56Z&se=2020-11-12T21%3A04%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?searc [...]

2020-10-12 21:06 UTC, opbld33 commented
Docs Build status updates of commit _[22f79a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22f79a8478df3746f897fc5a4f4d5ffe52f81ece)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-fd652214-b13f7410)
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-bad94fcd-b13f7410)
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-e6be38b0-b13f7410)
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

<a id="fd652214-b13f7410"></a>
### [api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md)
 - **Line 54, Column 11**: **[Warning-file-not-found]** `````Invalid file link: '..resources/b2xidentityuserflow.md'.`````

<a id="bad94fcd-b13f7410"></a>
### [api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md)
 - **Line 54, Column 11**: **[Warning-file-not-found]** `````Invalid file link: '..resources/b2xidentityuserflow.md'.`````

<a id="e6be38b0-b13f7410"></a>
### [api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md)
 - **Line 54, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '..resources/b2xidentityuserflow.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010122103580939-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rbo97UJfUuC6sXYTeUJ8PO7aa5Wk58iAaRmVmjtuLlM%3D&st=2020-10-12T21%3A01%3A20Z&se=2020-11-12T21%3A06%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search= [...]

2020-10-12 21:08 UTC, opbld34 commented
Docs Build status updates of commit _[ddf1f22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ddf1f225913e630343a772365eb86fc8ce717be8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010122106554787-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Gtzr8t1EXlfeckJLvkp%2BdfbrT9ZIbdoCYAYw5QTupS0%3D&st=2020-10-12T21%3A03%3A16Z&se=2020-11-12T21%3A08%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-14 19:27 UTC, opbld34 commented
Docs Build status updates of commit _[aa41dbf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa41dbfaa1dc405d21e7afa2abaa08437301f5c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010141925491367-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=e1X7NgCHg7raPy0qIqlUVt6LfnITB9Q%2FHy9ziGkgwRY%3D&st=2020-10-14T19%3A22%3A13Z&se=2020-11-14T19%3A27%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-14 19:34 UTC, opbld33 commented
Docs Build status updates of commit _[b995922](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b995922c85c0f1bd893e4ad78c144c717b1ba1d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010141932590681-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4gITTcUiC6wlsp4k%2FTFY3ZxDTovOyvNmZXLQZezss40%3D&st=2020-10-14T19%3A29%3A18Z&se=2020-11-14T19%3A34%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-14 19:54 UTC, opbld33 commented
Docs Build status updates of commit _[699e31b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/699e31b143cea18eaf183a6f36372bae60161d15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010141953286245-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DIAUVfPXlAzFTv9PnOFd9mM%2Faz4T9YOAPq9GF%2FP6gkI%3D&st=2020-10-14T19%3A49%3A52Z&se=2020-11-14T19%3A54%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-15 03:35 UTC, Lauragra commented on api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md
> +**Note:** The response object shown here might be shortened for readability.
Remove this note when the response does not contain any content.

2020-10-15 03:35 UTC, Lauragra commented on api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md
> +Delete an [authenticationAction](../resources/authenticationaction.md) object.
Is this the right description? What is getting deleted with this operation?

2020-10-15 15:28 UTC, jkdouglas commented on api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md
> +**Note:** The response object shown here might be shortened for readability.
Fixed

2020-10-15 15:29 UTC, opbld30 commented
Docs Build status updates of commit _[bcd9b43](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bcd9b438f0bd9ac9e70b78573097e80c6b455fd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010151528298359-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3KO5gJ4NawHN6XY%2FIXptSatxwzzbVXuOYgge0I5Wy%2BE%3D&st=2020-10-15T15%3A24%3A37Z&se=2020-11-15T15%3A29%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-15 18:52 UTC, opbld32 commented
Docs Build status updates of commit _[1087804](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1087804f5ed261fa9193f6a7ca4bdc467aed4f59)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010151850479070-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zraQKtU%2FfpMD4rlFwGAvrscdlR%2FpdpWSByrv%2BqVCXTQ%3D&st=2020-10-15T18%3A47%3A09Z&se=2020-11-15T18%3A52%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 15:38 UTC, opbld32 commented
Docs Build status updates of commit _[5cb4c82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5cb4c823e737cae89976b406ef2d699b9e8c5a6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010161537392849-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=awkWqe1SoMemvQ1024QaQ%2FJhJr%2FAOL6BrtScLxFrAqo%3D&st=2020-10-16T15%3A33%3A58Z&se=2020-11-16T15%3A38%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 15:48 UTC, opbld33 commented
Docs Build status updates of commit _[22a0424](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22a0424eb32f33ee8d2dd6d1e808946c534788e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010161547173866-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yXR%2FzbMNcLd9eup2GYpW1Mix6tcPpe5MfTNf%2FzKlzG8%3D&st=2020-10-16T15%3A43%3A28Z&se=2020-11-16T15%3A48%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 16:20 UTC, opbld34 commented
Docs Build status updates of commit _[ecd99bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ecd99bdccd22fcbdd8e58fe8635963e8f4310a84)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010161618537920-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1%2Bo%2ByOTrR5rnkITwypl%2FW1EqzZrMN7pMXoTf86iBQiE%3D&st=2020-10-16T16%3A15%3A09Z&se=2020-11-16T16%3A20%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 16:24 UTC, opbld30 commented
Docs Build status updates of commit _[da27f2f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da27f2f3e01bbceb85447f6014a9af753f8c000c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010161623239806-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rk7taFKRE1P6VgGtA57QH%2FDTZQG2WDHZGnxiK8bpw7s%3D&st=2020-10-16T16%3A19%3A42Z&se=2020-11-16T16%3A24%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 16:30 UTC, opbld32 commented
Docs Build status updates of commit _[2022130](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20221305defa627057f23e00923d929602009d07)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010161629179938-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2nDHmMD8adLMLF%2FrACbqp22PwWhTocLl6nE0rWDSEFc%3D&st=2020-10-16T16%3A25%3A40Z&se=2020-11-16T16%3A30%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 16:35 UTC, opbld33 commented
Docs Build status updates of commit _[c9ad9e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9ad9e3a09d4aaebdd96f1c73234725429371c9e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010161633465758-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4hMefeKa0ZXkNVBBEo4gttTtYGflFCc177sDxArZv10%3D&st=2020-10-16T16%3A30%3A02Z&se=2020-11-16T16%3A35%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 16:42 UTC, saraswatshantanu requested changes

2020-10-16 16:42 UTC, saraswatshantanu commented on api-reference/beta/resources/invokeuserflowaction.md
> +  "userFlow": "String"
I just noticed here that the userFlow should be an object and not a string. It should be represented like your other examples:
    "userFlow": {
        "id": "B2X_1_Partner"
    }

2020-10-16 16:42 UTC, saraswatshantanu commented on api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md
> +        ]
Shouldn't this one have userFlow as well?

2020-10-16 16:45 UTC, opbld30 commented
Docs Build status updates of commit _[22c1112](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22c11122491314c7f13c50760db9b40df2b3c586)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010161644372055-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gFtQWA9vK0N7drMSWNsz6x0vO0IQMeL9F7XDBTEaUj0%3D&st=2020-10-16T16%3A40%3A57Z&se=2020-11-16T16%3A45%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 16:46 UTC, jkdouglas commented on api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md
> +        ]
Good catch. Fixed

2020-10-16 16:46 UTC, jkdouglas commented on api-reference/beta/resources/invokeuserflowaction.md
> +  "userFlow": "String"
Good catch. Fixed

2020-10-16 16:46 UTC, saraswatshantanu approved these changes
Looks good from engineering

2020-10-16 16:49 UTC, opbld34 commented
Docs Build status updates of commit _[ad21271](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad212712aebd5342c820c93de2cd4c72afccc1d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010161647561203-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hbJttvzpzDeFK5EVylHvv17u8iHmH7CA3ZmCw7kIXGk%3D&st=2020-10-16T16%3A44%3A21Z&se=2020-11-16T16%3A49%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 17:56 UTC, opbld30 commented
Docs Build status updates of commit _[e9268f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e9268f84f70cc3966a02adc92ed799d293cfdd6c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010161755369024-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9lJLg82HJHpsjZGtRA%2FrJO4x%2FCMjHTgMZCIAwfmN4Wc%3D&st=2020-10-16T17%3A51%3A50Z&se=2020-11-16T17%3A56%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 21:40 UTC, opbld32 commented
Docs Build status updates of commit _[80c2f82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80c2f8298c2bfe2988cec3e13aeba4371a131f05)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010162138449065-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CBb0VU4sEOU6aDQfTESUXFJ4CnA2U%2BJK0r4Dy0Xoop8%3D&st=2020-10-16T21%3A35%3A03Z&se=2020-11-16T21%3A40%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 21:46 UTC, opbld31 commented
Docs Build status updates of commit _[f334821](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3348213b575788ae6e26daf609103b783bdaf2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010162144540079-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YWubsRwaiLiv2gxAih23AVxHlzi6AEl%2BrT2lk2pqVSU%3D&st=2020-10-16T21%3A41%3A18Z&se=2020-11-16T21%3A46%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 20:19 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md
> +title: "Get onSignupStart"
I think this should be "Get authenticationAction"

2020-10-20 20:20 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md
> +# Get onSignupStart
```suggestion
# Get authenticationAction
```

2020-10-20 20:25 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md
> +description: "Remove an authenticationAction from an authenticationEventsPolicy."
This seems kind of confusing when you look at the name of the file and the title. It seems like the user could get confused about /onSignupStart/{id}, when the description is referring to an authenticationAction. Is it going to be easy for the user to equate onSignupStart to authenticationAction?

2020-10-20 20:30 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md
> +description: "Read the properties and relationships of an authenticationAction object."
Same question, is the user going to be able to make the connection between /onSignupStart/{id} and an authenticationAction object?

2020-10-20 20:33 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md
> +|priority|Int32|The priority of the action which is used for determining one out of multiple applicable actions.|
```suggestion
|priority|Int32|The priority of the action that is used for determining one out of multiple applicable actions.|
```

2020-10-20 20:34 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md
> +|sourceFilter|[authenticationSourceFilter](../resources/authenticationsourcefilter.md)|Filter based on the source of the authentication which is used to determine whether the action is executed or no
```suggestion
|sourceFilter|[authenticationSourceFilter](../resources/authenticationsourcefilter.md)|Filter based on the source of the authentication that is used to determine whether the action is executed or not.|
```

2020-10-20 20:34 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md
> +|userFlow|[b2xIdentityUserFlow](../resources/b2xidentityuserflow.md)|The reference to the user flow object that will be invoked in this action.|
```suggestion
|userFlow|[b2xIdentityUserFlow](../resources/b2xidentityuserflow.md)|The reference to the user flow object that is invoked in this action.|
```

2020-10-20 20:36 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md
> +---
I think this should be update, not put.

2020-10-20 20:37 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md
> +title: "Replace onSignupStart"
This should be Update, not Replace.

2020-10-20 20:43 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md
> +The following table shows the properties that are required when you create the [invokeUserFlowAction](../resources/invokeuserflowaction.md).
I think this might also be another mapping problem for a user. The file name, title, and description refer to onSignupStart, authenticationAction, and invokeUserFlowAction. Is the user going to know the relationship of these when looking at this page?

2020-10-20 20:44 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md
> +|priority|Int32|The priority of the action which is used for determining one out of multiple applicable actions.|
```suggestion
|priority|Int32|The priority of the action that is used to determine one out of multiple applicable actions.|
```

2020-10-20 20:45 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md
> +# Replace onSignupStart
Update onSignupStart

2020-10-20 20:46 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md
> +|sourceFilter|[authenticationSourceFilter](../resources/authenticationsourcefilter.md)|Filter based on the source of the authentication which is used to determine whether the action is executed or no
```suggestion
|sourceFilter|[authenticationSourceFilter](../resources/authenticationsourcefilter.md)|Filter based on the source of the authentication that is used to determine whether the action is executed.|
```

2020-10-20 20:46 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md
> +|userFlow|[b2xIdentityUserFlow](../resources/b2xidentityuserflow.md)|The reference to the user flow object that will be invoked in this action.|
```suggestion
|userFlow|[b2xIdentityUserFlow](../resources/b2xidentityuserflow.md)|The reference to the user flow object that is invoked in this action.|
```

2020-10-20 20:51 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md
> +Read the properties and relationships of an [authenticationAction](../resources/authenticationaction.md) object.
What is the relationship between an onSignupStart object and an authenticationAction object?

2020-10-20 20:56 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md
> +description: "Get the authenticationAction resources from the onSignupStart navigation property."
This endpoint makes me assume that I am dealing with an onSignupStart object: /onSignupStart/{id}. I've never seen a get method described this way. In the example response it looks like an onSignupStart object is being listed with a collection of invokeUserFlowAction objects.

2020-10-20 20:58 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md
> +description: "Create a new authenticationAction object."
Why do the title and the description say different things are being created?

2020-10-20 20:59 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md
> +description: "Replace an authenticationAction object."
The title and description should not appear to be saying different things.

2020-10-20 21:01 UTC, davidmu1 commented on api-reference/beta/resources/authenticationaction.md
> +|[List onSignupStart](../api/authenticationeventspolicy-list-onsignupstart.md)|[authenticationAction](../resources/authenticationaction.md) collection|Get the authenticationAction resources from the
```suggestion
|[List onSignupStart](../api/authenticationeventspolicy-list-onsignupstart.md)|[authenticationAction](../resources/authenticationaction.md) collection|Get the authenticationActions from the onSignupStart object.|
```

2020-10-20 21:02 UTC, davidmu1 commented on api-reference/beta/resources/authenticationaction.md
> +|priority|Int32|The priority of the action which is used for determining one out of multiple applicable actions.|
```suggestion
|priority|Int32|The priority of the action that is used to determine one out of multiple applicable actions.|
```

2020-10-20 21:03 UTC, davidmu1 commented on api-reference/beta/resources/authenticationaction.md
> +|sourceFilter|[authenticationSourceFilter](../resources/authenticationsourcefilter.md)|Filter based on the source of the authentication which is used to determine whether the action is executed or no
```suggestion
|sourceFilter|[authenticationSourceFilter](../resources/authenticationsourcefilter.md)|Filter based on the source of the authentication that is used to determine whether the action is executed.|
```

2020-10-20 21:04 UTC, davidmu1 commented on api-reference/beta/resources/authenticationsourcefilter.md
> +Filter based on the source of the authentication which is used to determine whether the action is executed or not.
```suggestion
Filter based on the source of the authentication that is used to determine whether the action is executed.
```

2020-10-20 21:04 UTC, davidmu1 commented on api-reference/beta/resources/authenticationsourcefilter.md
> +|includeApplications|String collection|Applications to include. These applications will trigger the associated action when used as the client application in the authentication flow.|
```suggestion
|includeApplications|String collection|Applications to include. These applications trigger the associated action when used as the client application in the authentication flow.|
```

2020-10-20 21:05 UTC, davidmu1 commented on api-reference/beta/resources/invokeuserflowaction.md
> +|priority|Int32|The priority of the action which is used for determining one out of multiple applicable actions. Inherited from [authenticationAction](../resources/authenticationaction.md)|
```suggestion
|priority|Int32|The priority of the action that is used to determine one out of multiple applicable actions. Inherited from [authenticationAction](../resources/authenticationaction.md)|
```

2020-10-20 21:05 UTC, davidmu1 commented on api-reference/beta/resources/invokeuserflowaction.md
> +|sourceFilter|[authenticationSourceFilter](../resources/authenticationsourcefilter.md)|Filter based on the source of the authentication which is used to determine whether the action is executed or no
```suggestion
|sourceFilter|[authenticationSourceFilter](../resources/authenticationsourcefilter.md)|Filter based on the source of the authentication that is used to determine whether the action is executed. Inherited from [authenticationAction](../resources/authenticationaction.md)|
```

2020-10-20 21:06 UTC, davidmu1 commented on api-reference/beta/resources/invokeuserflowaction.md
> +|userFlow|[b2xIdentityUserFlow](../resources/b2xidentityuserflow.md)|The user flow that will be invoked if this action is executed.|
```suggestion
|userFlow|[b2xIdentityUserFlow](../resources/b2xidentityuserflow.md)|The user flow that is invoked if this action is executed.|
```

2020-10-20 21:06 UTC, davidmu1 commented on api-reference/beta/toc.yml
>            - name: Authentication flows policy
Don't forget your changelog entry.

2020-11-10 20:57 UTC, opbld34 commented
Docs Build status updates of commit _[dbc9bfc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dbc9bfc4d4fe0a3c6924b8c848cd36fa9f60c67e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011102056429683-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jAOqjTlZJ5EmuXpyGTVSuJs3z%2B5ALTlIXW%2BpW769DbM%3D&st=2020-11-10T20%3A52%3A52Z&se=2020-12-11T20%3A57%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 20:59 UTC, opbld30 commented
Docs Build status updates of commit _[ce43daa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ce43daa7cd281b32ecedfc11bc4401248b75c715)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011102057438840-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tV%2BXM6ZlP7HpN93Ajlim6stAkRee2pJbB2hUosL8qKc%3D&st=2020-11-10T20%3A54%3A18Z&se=2020-12-11T20%3A59%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 21:00 UTC, opbld30 commented
Docs Build status updates of commit _[2ef5ff0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ef5ff016835dd063fe495dc04c8b4f50e96b6bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011102058083764-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MjBSYdipExQ00nYTCKUXXrbnnOhuXCUQF%2F0bw7NrR80%3D&st=2020-11-10T20%3A55%3A42Z&se=2020-12-11T21%3A00%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 21:02 UTC, opbld34 commented
Docs Build status updates of commit _[2e7898c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e7898c877d0fc8a732a09ebbfe27cb9b4a2b438)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-delete-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get-authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get-authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-update-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-update-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-delete-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011102100152462-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=40%2BqohGVejXLk7wz1LFN90F%2BzPFkwxRlcJj6Rpp3EPk%3D&st=2020-11-10T20%3A57%3A07Z&se=2020-12-11T21%3A02%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 23:41 UTC, opbld31 commented
Docs Build status updates of commit _[43eeae7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/43eeae77b032a7bd688799f01d18b675a0a9de9c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-21c8eb62-3010eb11)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-create?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-00685cff-3010eb11)
[api-reference/beta/api/authenticationaction-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-create?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-list?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationaction-remove.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-remove.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-remove?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationaction-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

<a id="21c8eb62-3010eb11"></a>
### [api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/authenticationeventspolicy-list-onsignupstart.md'.`````
 - **Line 21, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/authenticationeventspolicy-post-onsignupstart.md'.`````
 - **Line 22, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/authenticationeventspolicy-update-onsignupstart.md'.`````
 - **Line 23, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/authenticationeventspolicy-get-authenticationaction.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/authenticationeventspolicy-delete-onsignupstart.md'.`````

<a id="00685cff-3010eb11"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml)
 - **Line 10037, Column 19**: **[Warning-file-not-found]** `````Invalid file link: 'api/authenticationeventspolicy-list-onsignupstart.md'.`````
 - **Line 10039, Column 19**: **[Warning-file-not-found]** `````Invalid file link: 'api/authenticationeventspolicy-get-authenticationaction.md'.`````
 - **Line 10041, Column 19**: **[Warning-file-not-found]** `````Invalid file link: 'api/authenticationeventspolicy-post-onsignupstart.md'.`````
 - **Line 10043, Column 19**: **[Warning-file-not-found]** `````Invalid file link: 'api/authenticationeventspolicy-update-onsignupstart.md'.`````
 - **Line 10045, Column 19**: **[Warning-file-not-found]** `````Invalid file link: 'api/authenticationeventspolicy-delete-onsignupstart.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011102339080884-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=W0oEp1veubyG%2FQUhOs%2Bn2kmNvPH7r7PzeYxK8vWTKk0%3D&st=2020-11-10T23%3A36%3A20Z&se=2020-12-11T23%3A41%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft. [...]

2020-11-10 23:49 UTC, opbld33 commented
Docs Build status updates of commit _[02ea276](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02ea276816c925f378cc7ee176700dee76a18d53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationaction-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-create?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-list?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationaction-remove.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-remove.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-remove?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationaction-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-create?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011102348411467-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cfef6YWblNR9gzmSt6Yz1k5dfp9%2BTgnPt0OTxhMW9jg%3D&st=2020-11-10T23%3A44%3A54Z&se=2020-12-11T23%3A49%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 23:02 UTC, opbld30 commented
Docs Build status updates of commit _[2bc23ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2bc23ab72af8efdc67962482dde86d9dfe6d9dcc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationaction-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-create?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationaction-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-list?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationaction-remove.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-remove.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-remove?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationaction-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-create?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011122301344090-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kr1zGvx9N2ghwDgOy%2FgNb27Rn5DHqHWuRiID8gqLWO0%3D&st=2020-11-12T22%3A57%3A54Z&se=2020-12-13T23%3A02%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 08:58 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationeventspolicy.md
> +
Based on the CSDL you sent me on 11/5, authenticationEventsPolicy relates to the rest of the authentication APIs by being the type of a new nav property called "events" of the identityContainer type. The "identity" _segment_ that appears in the query URL of this set of APIs, or of the user flow APIs, is a singleton of the identityContainer type.
For these reasons, you or your team should have documented identityContainer. There's a hole in the docs if the docs don't explain where "identity" as a _segment_ comes from, other than that there's a complex type also called "identity" which IS documented and therefore adds to the confusion in the docs.

(I might have actually brought this up the last time I reviewed some user flow PR of yours...)

Nonetheless, based on the api.md file you sent me, perhaps I can suggest the top description section for identitycontainer.md:
```
Represents a container for authentication-related resources in Microsoft Graph.

**identityContainer** is the type for the **identity** singleton which surfaces as the `identity` segment when querying resources defined for authentication, such as user flows and authentication events. For example:
- To get a specific user flow:
  ```
  GET https://graph.microsoft.com/beta/identity/userFlows/{id}
  ```

- To get the actions of an authentication event:
  ```
  GET https://graph.microsoft.com/beta/identity/events?$expand=onSignupStart
  ```
```

2020-11-13 09:14 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationeventspolicy.md
> +
Do you still have the set of stub topics somewhere that was output from the topic generation? If you do, the generated topic would help you fill out the rest of the identitycontainer.md topic. Basically, you should include the Properties section which includes the id property, the JSON representation section which is trivial, the Relationships section that includes all the nav properties meant to be exposed, and the Methods section that contain the "list" and "create" operations for each of the nav properties, if supported. If you don't have the generated identitycontainer.md anymore, you can look at profile.md as an example. That profile entity also contains only a bunch of nav properties, 1 property "id"; slightly different is it defines a GET method for profile, but identityContainer doesn't define any methods of its own, I suppose?

2020-11-13 09:26 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationeventspolicy.md
> +|[Get events](../api/authenticationeventspolicy-get.md)|[authenticationEventsPolicy](../resources/authenticationeventspolicy.md)|Read the properties and relationships of an [authenticationEventsPolic
Line 20:
The Method column should read "Get authenticationEventsPolicy".
Based on your api.md file, I'd suggest the Description column to say something more helpful, like "Get the authentication events defined by policy for the tenant". (Please review for technical accuracy; my understanding is based on the api.md.)
Please also apply the same description as the top summary description in authenticationeventspolicy-get.md.
The generated description is generic, it basically reflects what in general a GET operation does, regardless of the entity that the GET operation applies to.

2020-11-13 09:29 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationeventspolicy-get.md
> +Read the properties and relationships of an [authenticationEventsPolicy](../resources/authenticationeventspolicy.md) object.
Line 14:
I suggest a more helpful description "Get the authentication events that are supported and defined by policy for the tenant."

2020-11-13 09:36 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationeventspolicy.md
> +|[List authenticationActions](../api/authenticationaction-list.md)|[authenticationAction](../resources/authenticationaction.md) collection|Get the authenticationAction objects for a specific authenti
Line 21:
The Method column should read "List onSignupStart".
I think this is a generation bug which I have in the last couple of weeks tracked and talked to the generation tool engineer about. If you refer to this CDK topic: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55080/ToC-and-topic-title
you'd see the pattern for the topic title of a "list" operation topic is "List {nav property name}".

2020-11-13 09:38 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationeventspolicy.md
> +|[List authenticationActions](../api/authenticationaction-list.md)|[authenticationAction](../resources/authenticationaction.md) collection|Get the authenticationAction objects for a specific authenti
For the Description column, since this is specific to the onSignupStart event, it should say "Get the collection of authenticationAction resources for the onSignupStart event." 
Is that correct?

2020-11-13 09:44 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationaction-list.md
> +# List authenticationActions
Line 10:
The topic title should be "List onSignupStart".

2020-11-13 09:46 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationaction-list.md
> +
This file should be renamed as authenticationeventspolicy-list-onsignupstart.md.

2020-11-13 09:48 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationaction-list.md
> +Get the authenticationAction resources from the onSignupStart event.
Line 14:
I suggest providing more context to the description to make it more helpful, such as "Get the collection of authenticationAction resources supported by the onSignupStart event."

2020-11-13 10:07 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationeventspolicy.md
> +|[Create authenticationAction](../api/authenticationaction-create.md)|[authenticationAction](../resources/authenticationaction.md)|Create a new authenticationAction object.|
Line 22:
Under the Method column, the filename being linked to should be authenticationeventspolicy-post-onsignupstart.md.md.

2020-11-13 10:08 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationaction-create.md
> +
This filename should be authenticationeventspolicy-post-onsignupstart.md.md.

2020-11-13 10:10 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationeventspolicy.md
> +|[Create authenticationAction](../api/authenticationaction-create.md)|[authenticationAction](../resources/authenticationaction.md)|Create a new authenticationAction object.|
Line 22:
For the Description column, would a description like "Create a new authenticationAction object for the onSignupStart event." be correct? 
If so, it would give a bit more context to this particular "create" operation.

2020-11-13 10:12 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationaction-create.md
> +Create a new authenticationAction object.
Line 14:
Would a description like "Create a new authenticationAction object for the onSignupStart event." be correct?
If so, that would provide a bit more context to this "create" operation than the generic, generated description.

2020-11-13 10:21 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationaction-create.md
> +|userFlow|String|The identifier of the [b2xIdentityUserFlow](../resources/b2xidentityuserflow.md) object that will be invoked in this action.|
Line 54:
userFlow is a nav property of invokeUserFlowAction (base type of which is authenticationAction).
Can you confirm if indeed the create operation for invokeUserFlowAction allows initializing a nav property in the same call? (That's relatively uncommon in the Graph API.)

2020-11-13 10:27 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationaction-create.md
> +|userFlow|String|The identifier of the [b2xIdentityUserFlow](../resources/b2xidentityuserflow.md) object that will be invoked in this action.|
On more thought and after looking at the authenticationaction-update.md topic which also includes the userFlow nav property as a property that can be updated, I have a question:
With this nav property being assign-able and updateable, why is it not defined as a property and instead a nav property?

2020-11-13 10:30 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationaction-update.md
> +|userFlow|String|The identifier of the [b2xIdentityUserFlow](../resources/b2xidentityuserflow.md) object that will be invoked in this action.|
Line 54:
Note my question as brought up in the create operation - is the nav property userFlow updateable as part of the PATCH for its parent resource invokeUserFlowAction? Why is userFlow defined as a relationship and not as a property  instead?

2020-11-13 10:36 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationaction-remove.md
> +Remove an [authenticationAction](../resources/authenticationaction.md) from an [authenticationEventsPolicy](../resources/authenticationeventspolicy.md).
Line 14:
Based on api.md and how authenticationEventsPolicy is defined in the CSDL (it can have more than one nav property that represents an "event", each of which is a collection of actions), would it be more accurate to describe this operation as "Deletes an authenticationAction from an event supported by an authenticationEventsPolicy"?

2020-11-13 10:40 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationaction-remove.md
> +# Remove authenticationAction
Line 10:
Based on how the only type of event onSignupStart is defined as a nav property of authenticationEventsPolicy:
<NavigationProperty Name="onSignupStart" Type="Collection(Microsoft.Cpim.Api.DataModels.authenticationAction)" ContainsTarget="true"/>
specifying ContainsTarget="true", the verb to use here should be "Delete", not "Remove".

Please change the topic title to "Delete authenticationAction".

2020-11-13 10:44 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationeventspolicy.md
> +|[Remove authenticationAction](../api/authenticationaction-remove.md)|None|Remove an [authenticationAction](../resources/authenticationaction.md) object.|
Lines 23-25:
For consistency, please don't include these rows in the Methods table for authenticationEventsPolicy.
The Methods table of authenticationEventsPolicy can include the "list" and "create" operations related to a nav property. But we shouldn't include the "get", "update", "delete" topics for the type of the nav property (in this case authenticationAction) in the Methods table of authenticationEventsPolicy. 

These 3 operations should be included in only the Methods table of authenticationAction.

2020-11-13 10:45 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationaction.md
> +|[Remove authenticationAction](../api/authenticationaction-remove.md)|None|Remove an [authenticationAction](../resources/authenticationaction.md) object.|
Line 24:
The Method column should say "Delete authenticationAction".

2020-11-13 10:48 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationaction-remove.md
> +---
This file name should be authenticationaction-delete.md.

2020-11-13 10:49 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationaction.md
> +|[List authenticationActions](../api/authenticationaction-list.md)|[authenticationAction](../resources/authenticationaction.md) collection|Get the authenticationAction objects for a specific authenti
Lines 20-21:
Please update the Method column topic title, link destination, and the Description column description, per my comments in what you currently call authenticationaction-list.md, and authentication-create.md. (Note I have commented there to rename those 2 filenames accordingly.)

2020-11-13 10:50 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationaction.md
> +|[Remove authenticationAction](../api/authenticationaction-remove.md)|None|Remove an [authenticationAction](../resources/authenticationaction.md) object.|
Line 24:
The Description column should also be consistent and say "Delete an ..."

2020-11-13 10:58 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md
> +Create a new authenticationAction object.
PUT is typically "update the specified (authenticationAction) object is it already exists, create it otherwise as specified". Does this PUT action do the same?

2020-11-13 11:06 UTC, angelgolfer-ms commented on api-reference/beta/resources/invokeuserflowaction.md
> +Inherits from [authenticationAction](../resources/authenticationaction.md).
Line 16:
Perhaps you can further clarify that authenticationAction is an abstract resource? Hopefully that can help clarify for customers, re David's comment how customers could possibly figure out why the "create", "update", "put" operations of authenticationAction would include the userFlow property in the request body section.

Something like:
"Inherits from the abstract base type authenticationAction."

2020-11-13 11:11 UTC, angelgolfer-ms requested changes
Hi @jkdouglas , I think I have reviewed all the files in this PR with the exception of the TOC. I'll comment on the TOC tomorrow.
Please take a look at my comments.

2020-11-16 20:50 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationeventspolicy.md
> +
Line 14:
The description as is doesn't contain a summary description for the resource. Instead we have a paragraph leaving the reader to make out what this resource is. Based on what I have learned from the api.md and CSDL, may I suggest a summary description like this:
"A policy that defines events in an authentication pipeline, with each event further defining the appropriate actions."

FYI in general, each resource, operation, action, or function topic should always start with a summary description.

2020-11-16 22:48 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationaction-get.md
> +Read the properties and relationships of an [authenticationAction](../resources/authenticationaction.md) object.
Line 14:
Can I suggest a description that ties in better with this API design:
"Get the specified action defined for an event in the authentication pipeline."

The description as is right now only describes in general, what getting a resource, any resource, means, and doesn't help explain and put this operation in the context of this API. I think the suggested description would help educate your customers how a policy, event, action all tie together.

2020-11-16 22:49 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationaction.md
> +|[Remove authenticationAction](../api/authenticationaction-remove.md)|None|Remove an [authenticationAction](../resources/authenticationaction.md) object.|
Line 23:
Per my comment in the authentication-get.md topic, please update the description to be the same:
"Get the specified action defined for an event in the authentication pipeline."

2020-11-16 23:01 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationeventspolicy-get.md
> +Read the properties and relationships of an [authenticationEventsPolicy](../resources/authenticationeventspolicy.md) object.
Sorry, changing my suggestion:
"Get the policy that defines the authentication events supported by the authentication pipeline of a tenant."

2020-11-16 23:02 UTC, opbld31 commented
Docs Build status updates of commit _[70f06f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70f06f248a8ea00740d0c805b04f1b727f5ec249)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-00685cff-7a803226)
[api-reference/beta/api/authenticationaction-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationaction-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationaction-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationaction-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationaction-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-put-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowaction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowaction?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

<a id="00685cff-7a803226"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml)
 - **Line 10039, Column 19**: **[Warning-file-not-found]** `````Invalid file link: 'api/authenticationaction-list.md'.`````
 - **Line 10043, Column 19**: **[Warning-file-not-found]** `````Invalid file link: 'api/authenticationaction-create.md'.`````
 - **Line 10047, Column 19**: **[Warning-file-not-found]** `````Invalid file link: 'api/authenticationaction-remove.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011162259527056-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RG%2BDjdmMUyJRbswIIt20C6VYeg1JFyvdB8cO8X6x8Ug%3D&st=2020-11-16T22%3A57%3A00Z&se=2020-12-17T23%3A02%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 23:10 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationeventspolicy-get.md
> +
Is the following type of request still supported by your API?
It's in the api.md file, "Use case: List all authentication events and their assigned actions".

Since you're exposing only the onSignupStart event, the request would be to get the specified event of a policy and expand on the supported actions:

GET https://graph.microsoft.com/beta/identity/events?$expand=onSignupStart

2020-11-16 23:23 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationeventspolicy-get.md
> +
If it's supported, where is it documented in this PR?

I think if it's supported, it should be documented in this operation.

To do that:
Please add an H2 "Optional query parameters" section. 
You can say "This method supports the `$expand` query parameter to get the actions that the specified events support. See an example."
Then link to a second example in this topic that you'll add, that would show the following request, and a response similar to that in the api.md file, except only for the one event onSignupStart:
GET https://graph.microsoft.com/beta/identity/events?$expand=onSignupStart

2020-11-16 23:29 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationeventspolicy-get.md
> +
As suggested above, if your API still supports something like this:
GET https://graph.microsoft.com/beta/identity/events?$expand=onSignupStart

Then please add a second example.
The second example should have an H3 section title like "Example 2: Get the policy and expand the specified authentication event to show the actions the event supports."
For this first example, you'd then disambiguate what it does by adding an H3 section title: "Example 1: Get the policy that defines the events supported in the authentication pipeline."
Them bump the existing H3 section titles one level down to H4, like what you have done in other method topics like authenticationaction-get.md.

2020-11-16 23:44 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationaction-get.md
> +
After line 98:
Can I suggest adding a sentence that better explains what this example does:
"The following example lists the actions defined for the onSignupStart event, and for each action, expands the user flow that is invoked."

2020-11-16 23:49 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationaction-update.md
> +Update the properties of an authenticationAction object.
Line 14:
Can we add some context to this description, such as:
"Update the specified action defined for an event in the authentication pipeline."

2020-11-16 23:51 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationaction.md
> +|[Update authenticationAction](../api/authenticationaction-update.md)|[authenticationAction](../resources/authenticationaction.md)|Update the properties of an authenticationAction object.|
Line 22:
Per my comment in authentication-action.md, can we update the description to give some more context, for example:
"Update the specified action defined for an event in the authentication pipeline."

2020-11-16 23:51 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationaction.md
> +|[Get authenticationAction](../api/authenticationaction-get.md)|[authenticationAction](../resources/authenticationaction.md)|Read the properties and relationships of an authenticationAction object.|
Line 23:
Per my comment in authenticationaction-get.md, can we update the description to give some more context, for example:
"Get the specified action defined for an event in the authentication pipeline."

2020-11-17 01:22 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md
> +Create a new authenticationAction object.
BTW, if this operation is indeed "update specified object if exists, create it otherwise", then I think the filename should be   authenticationaction-put.md.

@jkdouglas , I don't suppose the stub topic generator generated this topic (PUT is not typical in the set of CRUD it generates), did it?

2020-11-17 01:25 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationeventspolicy-put-onsignupstart.md
> +POST https://graph.microsoft.com/beta/identity/events/onSignupStart
Line 17:
Is that request query missing an {id} at the end, to specify the authenticationAction object?

2020-11-17 02:51 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationeventspolicy.md
> +|[Get authenticationEventsPolicy](../api/authenticationeventspolicy-get.md)|[authenticationEventsPolicy](../resources/authenticationeventspolicy.md)|Get the authentication events that are supported a
Line 20:
"Get the policy that defines the supported events for the authentication pipeline of the tenant."

2020-11-17 03:08 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationeventspolicy-get.md
> +Get the authentication events that are supported and defined by policy for the tenant.
@jkdouglas , I know I have gone over this before and am providing a slightly different suggestion, again. I apologize for the churn. I don't think the last description I provided is worded with a consistent approach. I think the following is better:
"Get the policy that defines the supported events for the authentication pipeline of the tenant."

This just reflects how some people struggle with this design, "events" being a nav property of identityContainer, and defined to be of type authenticationEventsPolicy, which by that name should represent a "policy". And then in turn, authenticationEventsPolicy contains currently one nav property named like an event - onSignupStart - which is a collection of action objects.
IMHO, if that "events" nav property of identityContainer is renamed as "policy", let that "policy" define one or more events like onSignupStart... that the policy supports for that tenant, and let each such event be a collection of actions, that's more intuitive.
Well, regardless whether the nav property is called "events" or "policy", IMO we should still refer authenticationEventsPolicy as a "policy" (which has a policy id), with supported events defined as nav properties.

2020-11-17 03:36 UTC, angelgolfer-ms commented on api-reference/beta/resources/authenticationaction.md
> +|[Delete authenticationAction](../api/authenticationaction-delete.md)|None|Delete an authenticationAction from an event supported by an authenticationEventsPolicy.|
Line 24:
Please change the description to:
"Delete the specified action defined for the onSignupStart event in the authentication pipeline."

2020-11-17 03:37 UTC, angelgolfer-ms commented on api-reference/beta/api/authenticationaction-delete.md
> +Delete an [authenticationAction](../resources/authenticationaction.md) from an event supported by an [authenticationEventsPolicy](../resources/authenticationeventspolicy.md).
Line 14:
Sorry, please change the description to:
"Delete the specified action defined for the onSignupStart event in the authentication pipeline."

2020-11-17 06:01 UTC, angelgolfer-ms requested changes
Hi @jkdouglas , per my earlier chat with you, please find a few more comments for this PR. I also sent in email a suggestion for the TOC. Please take a look.

2020-12-07 20:18 UTC, jkdouglas commented on api-reference/beta/api/authenticationeventspolicy-get.md
> +
I thought about it and it does not make sense to have a GET on this policy and expand onSignUpStart when you could just use the API to list onSignUpStart with events/onsignupstart. Removed the info for GET authenticationEventsPolicy.

2020-12-07 21:17 UTC, opbld30 commented
Docs Build status updates of commit _[bf11af5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf11af5f5963103e152e6fe15ed68ccfc4532cd7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-a60a7d6e-3e34a8a3)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) | [Details](#user-content-00685cff-3e34a8a3)
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

<a id="a60a7d6e-3e34a8a3"></a>
### [api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md)
 - **Line 16, Column 14**: **[Warning-file-not-found]** `````Invalid file link: '../resources/invokeuserflowaction.md'.`````

<a id="00685cff-3e34a8a3"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml)
 - **Line 10152, Column 21**: **[Warning-file-not-found]** `````Invalid file link: 'api/authenticationlistener-list.md'.`````
 - **Line 10160, Column 21**: **[Warning-file-not-found]** `````Invalid file link: 'authenticationlistener-put.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012072115559753-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=g%2Fqd84pRW4%2Bb2abyLV%2Ft2PkpMAIi61zx6NF8NTyqhW4%3D&st=2020-12-07T21%3A12%3A21Z&se=2021-01-07T21%3A17%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com [...]

2020-12-07 21:51 UTC, opbld32 commented
Docs Build status updates of commit _[06779be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06779be9d428730580be27154d11d6917a3e3f5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012072150154526-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eISxyKvlTMK2muXH%2FETTJTGwnXzn%2FKKb5XbhRPtPaYE%3D&st=2020-12-07T21%3A46%3A40Z&se=2021-01-07T21%3A51%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 21:56 UTC, opbld32 commented
Docs Build status updates of commit _[4fcb90f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4fcb90f88d4119f291d92918f248c0398a386c71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012072155017625-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JbLkF7y6%2BINjJtoUfgXePMGBhkQq7zGKdncXZUu%2F81A%3D&st=2020-12-07T21%3A51%3A32Z&se=2021-01-07T21%3A56%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 22:11 UTC, opbld34 commented
Docs Build status updates of commit _[5bea52d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5bea52da84684a14276bbcdeda99b6b4959f2d56)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012072210159803-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w7rR8FBt%2FPjqv61AGKoeWELZzSFtyrO5U5sYzVWe184%3D&st=2020-12-07T22%3A06%3A28Z&se=2021-01-07T22%3A11%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 22:25 UTC, opbld31 commented
Docs Build status updates of commit _[c229a5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c229a5d151c5717820108042e384560754993ed3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012072223570884-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BolMAX7A927EzVggQOkwrQWMNl6UvA1S1q%2BXq8u9H3A%3D&st=2020-12-07T22%3A20%3A28Z&se=2021-01-07T22%3A25%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 14:57 UTC, opbld31 commented
Docs Build status updates of commit _[432a499](https://github.com/microsoftgraph/microsoft-graph-docs/commits/432a4995730f3ae83b5584a8fcb97a9fbc575310)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-553f36ed)
[api-reference/beta/api/authenticationeventspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-553f36ed"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012081456316490-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jrPr9kqi2Z4ZHcw1nbUSJFNgdGe7bvogWDCl9jng4Lw%3D&st=2020-12-08T14%3A52%3A46Z&se=2021-01-08T14%3A57%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 00:25 UTC, opbld31 commented
Docs Build status updates of commit _[035f013](https://github.com/microsoftgraph/microsoft-graph-docs/commits/035f013106d62b37054893e152b814f7316dd778)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cc086bbc)

<a id="cc086bbc"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150025279710-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mgTq56iddNGRYhRlIckBJCWV0vZKNlGKA7HyUVSr%2Bx8%3D&st=2020-12-15T00%3A20%3A48Z&se=2021-01-15T00%3A25%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 00:33 UTC, opbld34 commented
Docs Build status updates of commit _[67c525d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67c525dec051a8c708289b3d636b607dac99da44)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-5ad2d5d7)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-5ad2d5d7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 63, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 125, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 126, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 126, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150032084609-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6wevNazdt3FR7iHLxZdD3A9UnmsVKt6ku5%2BLYQrDrQU%3D&st=2020-12-15T00%3A28%3A21Z&se=2021-01-15T00%3A33%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a [...]

2020-12-15 00:50 UTC, opbld30 commented
Docs Build status updates of commit _[5727ad8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5727ad8c6685f3bb123f69b9029f9e5fa20f49d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-94e8a154)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-94e8a154"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 63, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 125, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 126, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 126, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150049082367-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cKt6phrfziC4XbwJbKr32howBxZiKleisTNBf8NLq5I%3D&st=2020-12-15T00%3A45%3A26Z&se=2021-01-15T00%3A50%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a h [...]

2020-12-15 12:07 UTC, nickgmicrosoft submitted a review, later dismissed

2020-12-15 12:07 UTC, nickgmicrosoft commented on api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md
> +Create a new authenticationListener object for the onSignUpStart event.
Since there's only invokeUserFlowListener for this event, and since the corresponding example request and documentation point specifically to the b2xuserflow relationship property, would it be better to replace 'Create a new authenticationListener" with "Create a new invokeUserFlowListener..."? Same for all of the LIST+CRUD operation docs.

2020-12-15 17:21 UTC, opbld30 commented
Docs Build status updates of commit _[2570cfc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2570cfc1eb74a7efaca3b2b2f83a371400ffb7c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-331f0dc8)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-331f0dc8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151720453036-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ASaOoCyhbfuQx3dh%2FqAx2eYkmtGaxvGJfix5agvLjOU%3D&st=2020-12-15T17%3A16%3A56Z&se=2021-01-15T17%3A21%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a [...]

2020-12-15 17:23 UTC, opbld30 commented
Docs Build status updates of commit _[dc35cfe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dc35cfe3fe81926e5fc767a3ca8fd49b45cd6b9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-c054d8f9)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-c054d8f9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151722074957-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Bl2MMFrFmC%2FFlpLbYKi9siyCpP5lGJBy32buoXWuc7Y%3D&st=2020-12-15T17%3A18%3A37Z&se=2021-01-15T17%3A23%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the  [...]

2020-12-15 17:24 UTC, jkdouglas commented on api-reference/beta/resources/authenticationeventspolicy.md
> +## Methods
Based on how the API is defined in the CSDL (with containsTarget=true), this is how you document it. The doc writers helped me understand this and document it properly.

2020-12-15 17:25 UTC, opbld34 commented
Docs Build status updates of commit _[9d8b531](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d8b5319ace37c4dbbe17167efac362ce8980e08)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-0856a848)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-0856a848"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151723166883-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=D6IihW6IIhZyg8OJh0u90AM8J0yLxlsVAnxC%2FKj3JBs%3D&st=2020-12-15T17%3A19%3A58Z&se=2021-01-15T17%3A24%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a [...]

2020-12-15 17:26 UTC, opbld32 commented
Docs Build status updates of commit _[9d8b531](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d8b5319ace37c4dbbe17167efac362ce8980e08)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-6deb0e99)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-6deb0e99"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151723056218-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=byxZS2NJY88p6vma8FHZwPcOKyyaePYaKjm4Rg75yWE%3D&st=2020-12-15T17%3A21%3A30Z&se=2021-01-15T17%3A26%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a h [...]

2020-12-15 17:52 UTC, opbld34 commented
Docs Build status updates of commit _[67c0f58](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67c0f58cd36b63df3f78e5b54b3859ac66a02ef6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-4d66729f)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-4d66729f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151751305775-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1k0LW%2FnG8YdS9BXIl2HA3ONfn5GH26S1P06bG6o4Hhk%3D&st=2020-12-15T17%3A47%3A52Z&se=2021-01-15T17%3A52%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a [...]

2020-12-15 18:28 UTC, opbld33 commented
Docs Build status updates of commit _[d2418ba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2418baf843ea4854584cf566368d4938ef9aeb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-f99b5715)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-f99b5715"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151827307426-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=giFiaxtZY4ECgy%2BnJAMuftZZJkMh4I8bmm%2Blk7%2BAQXw%3D&st=2020-12-15T18%3A23%3A53Z&se=2021-01-15T18%3A28%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See th [...]

2020-12-15 23:06 UTC, opbld30 commented
Docs Build status updates of commit _[c8b166a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8b166a75e624dd006ad5dcb4c325f2a6a67eb6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-01d593a1)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-01d593a1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012152305245723-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BzhPPaBnIYvlSOu9vaFk1xnRuPSMBZq6QUVxm0ZAV44%3D&st=2020-12-15T23%3A01%3A44Z&se=2021-01-15T23%3A06%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a [...]

2020-12-16 02:01 UTC, opbld32 commented
Docs Build status updates of commit _[490e875](https://github.com/microsoftgraph/microsoft-graph-docs/commits/490e875f70062c69a24eff28657106c70aabc64d)_: 

:clock10: **Pending**: waiting for processors ([8](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-16 02:03 UTC, opbld34 commented
Docs Build status updates of commit _[490e875](https://github.com/microsoftgraph/microsoft-graph-docs/commits/490e875f70062c69a24eff28657106c70aabc64d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-eb2abcd2)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-eb2abcd2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160201446525-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BN54bvBTO0J%2BE0bjF5nlQvfi5JUI%2Fr8wdwX3L1fUJBs%3D&st=2020-12-16T01%3A58%3A10Z&se=2021-01-16T02%3A03%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See th [...]

2020-12-17 19:48 UTC, opbld34 commented
Docs Build status updates of commit _[6e9ac64](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e9ac64619530450ff8bd1d11eacdb984db5e55f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-cddcbd8d)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-cddcbd8d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 104, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 110, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/channelModerationSettings2?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 82, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? [...]

2020-12-17 22:38 UTC, opbld32 commented
Docs Build status updates of commit _[686301f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/686301f93d45b6f30eb9086ff2e87cc82f2325d7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-b7494392)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-b7494392"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 104, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 110, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/channelModerationSettings2?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 82, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? [...]

2020-12-17 22:48 UTC, opbld33 commented
Docs Build status updates of commit _[0f55c76](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f55c76de8ab55295186015458d959fd46bd3c5b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-8ab4e64e)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-8ab4e64e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 104, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 110, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/channelModerationSettings2?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 82, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? [...]

2020-12-17 23:30 UTC, opbld33 commented
Docs Build status updates of commit _[dab6886](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dab6886c13885a6f7e9d4d3f92f43cb300f631aa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-82c182c1)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-82c182c1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 104, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 110, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/channelModerationSettings2?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 82, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? [...]

2020-12-17 23:41 UTC, opbld34 commented
Docs Build status updates of commit _[65fc5ba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65fc5ba14b19c963b67b48c50064e4829e61192f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-7ccf9b76)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-7ccf9b76"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 104, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 110, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/channelModerationSettings2?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 82, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? [...]

2020-12-17 23:47 UTC, opbld31 commented
Docs Build status updates of commit _[b6a32a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b6a32a6b45f8ac8c76711bcaf03bf73cb0020ac9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) | [Details](#user-content-de0bbbbb-2d6c0af1)
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-2d6c0af1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md)
 - **Line 104, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 110, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/channelModerationSettings2?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 82, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 157, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? [...]

2020-12-18 17:37 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md
> +Get the collection of authenticationListener resources supported by the onSignupStart event. The onSignUpStart event supports the following listener types:
If there is only one item in a list, it can probably be better described as a sentence:

The onSignUpStart event supports the [invokeUserFlowListener](../resources/invokeuserflowlistener.md) listener type.

2020-12-18 17:38 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
If you say "supports some of", you need to specify the parameters that are supported otherwise the user has to guess.

2020-12-18 17:39 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md
> +#### Request
Add sentence: The following is an example of the request.

2020-12-18 17:39 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md
> +#### Response
Add sentence: The following is an example of the response.

2020-12-18 17:40 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md
> +#### Request
Add sentence: The following is an example of the request.

2020-12-18 17:40 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md
> +#### Response
Add sentence: The following is an example of the response.

2020-12-18 17:49 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md
> +Create a new authenticationListener object for the onSignUpStart event.
It is confusing. I think from looking at what is here that you are creating an invokeUserFlowListener object, so should probably make it clear in the page and title,. Not sure what the advantage is for the user to include authenticationListener.

2020-12-18 17:53 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md
> +|priority|Int32|The priority of the action that is used to determine one out of multiple applicable actions.|
I don't really understand this description, are users going to? What actions are being referred to? Is there a limited range of priority?

2020-12-18 17:56 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md
> +### Request
Add sentence: The following is an example of the request.

2020-12-18 17:56 UTC, davidmu1 commented on api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md
> +### Response
Add sentence: The following is an example of the response.

2020-12-18 17:56 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-delete.md
> +### Request
Add sentence: The following is an example of the request.

2020-12-18 17:57 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-delete.md
> +### Response
Add sentence: The following is an example of the response.

2020-12-18 17:57 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Shouldn't say "some" without listing what they are.

2020-12-18 17:58 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-get.md
> +#### Request
Add sentence: The following is an example of the request.

2020-12-18 17:58 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-get.md
> +#### Response
Add sentence: The following is an example of the response.

2020-12-18 17:58 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-get.md
> +#### Request
Add sentence: The following is an example of the request.

2020-12-18 17:58 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-get.md
> +#### Response
Add sentence: The following is an example of the response.

2020-12-18 18:00 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-get.md
> +    "Error: get_authenticationlistener_invokeuserflowlistener/userFlow/userFlowTypeVersion:\r\n      Expected type Single but actual was Int64. Property: userFlowTypeVersion, actual value: '1'"
Is it required to have this in here twice? Please make a note of this situation and come back after the new year to correct.

2020-12-18 18:01 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-get.md
> +    "Error: get_authenticationlistener_invokeuserflowlistener/userFlow/userFlowTypeVersion:\r\n      Expected type Single but actual was Int64. Property: userFlowTypeVersion, actual value: '1'"
It would be good to explore the resolution of these errors with the API Doctor team. It is not good to have error suppression in the docs.

2020-12-18 18:02 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-put.md
> +title: "Put authenticationListener"
Create authenticationListener

2020-12-18 18:02 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-put.md
> +# Put authenticationListener
Create authenticationListener

2020-12-18 18:03 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-put.md
> +|priority|Int32|The priority of the action that is used to determine one out of multiple applicable actions.|
This description is confusing. Not sure what actions are being referred to.

2020-12-18 18:03 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-put.md
> +### Request
Add sentence: The following is an example of the request.

2020-12-18 18:03 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-put.md
> +### Response
Add sentence: The following is an example of the response.

2020-12-18 18:04 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-update.md
> +description: "Update the specified listener defined for an event in the authentication pipeline."
```suggestion
description: "Update the listener defined for an event in the authentication pipeline."
```

2020-12-18 18:04 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-update.md
> +Update the specified [authenticationListener](../resources/authenticationlistener.md) defined for an event in the authentication pipeline.
```suggestion
Update the [authenticationListener](../resources/authenticationlistener.md) defined for an event in the authentication pipeline.
```

2020-12-18 18:05 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-update.md
> +### Request
Add sentence: The following is an example of the request.

2020-12-18 18:05 UTC, davidmu1 commented on api-reference/beta/api/authenticationlistener-update.md
> +### Response
Add sentence: The following is an example of the response.

2020-12-18 18:22 UTC, jkdouglas commented on api-reference/beta/api/authenticationlistener-put.md
> +title: "Put authenticationListener"
As discussed on Teams, ignoring this comment

2020-12-18 18:22 UTC, jkdouglas commented on api-reference/beta/api/authenticationlistener-put.md
> +# Put authenticationListener
As discussed on Teams, ignoring this comment

2020-12-18 18:22 UTC, opbld33 commented
Docs Build status updates of commit _[3324f9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3324f9c2a15ab63828925d2ccd9881d4ec7c749d)_: 

:clock10: **Pending**: waiting for processors ([9](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-18 18:22 UTC, opbld32 commented
Docs Build status updates of commit _[3324f9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3324f9c2a15ab63828925d2ccd9881d4ec7c749d)_: 

:clock10: **Pending**: waiting for processors ([10](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-18 18:22 UTC, opbld31 commented
Docs Build status updates of commit _[37238c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37238c602da3d541f5034cab914bb749007c5d94)_: 

:clock10: **Pending**: waiting for processors ([10](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-18 18:23 UTC, opbld33 commented
Docs Build status updates of commit _[37238c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37238c602da3d541f5034cab914bb749007c5d94)_: 

:clock10: **Pending**: waiting for processors ([10](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-18 18:23 UTC, opbld32 commented
Docs Build status updates of commit _[3324f9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3324f9c2a15ab63828925d2ccd9881d4ec7c749d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012181822256024-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=s81dLZKQgWadXt%2B%2BPI1otrkre02ok5G2WBpFoMoxd4w%3D&st=2020-12-18T18%3A18%3A36Z&se=2021-01-18T18%3A23%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-18 18:24 UTC, opbld31 commented
Docs Build status updates of commit _[3324f9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3324f9c2a15ab63828925d2ccd9881d4ec7c749d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012181822362053-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xctMRdr44EVTjoy%2F6Nw4E3pgObfivHdh0hYYuIhmcRQ%3D&st=2020-12-18T18%3A19%3A47Z&se=2021-01-18T18%3A24%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-18 18:41 UTC, jkdouglas commented on api-reference/beta/api/authenticationlistener-get.md
> +    "Error: get_authenticationlistener_invokeuserflowlistener/userFlow/userFlowTypeVersion:\r\n      Expected type Single but actual was Int64. Property: userFlowTypeVersion, actual value: '1'"
I have made a note and will investigate in January when we return from the holidays.

2020-12-18 18:56 UTC, opbld33 commented
Docs Build status updates of commit _[1d3ec45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d3ec45e95ee4cd2827e0da31c42952f494a29e9)_: 

:clock10: **Pending**: waiting for processors ([16](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-18 18:57 UTC, opbld31 commented
Docs Build status updates of commit _[1d3ec45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d3ec45e95ee4cd2827e0da31c42952f494a29e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012181856242105-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=h6DGqmRqAc9T1Qi%2BIVXPlViAaaWL5oQNqq6J555UABU%3D&st=2020-12-18T18%3A52%3A48Z&se=2021-01-18T18%3A57%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-18 21:08 UTC, davidmu1 approved these changes

2020-12-18 21:10 UTC, jkdouglas commented
Marking 'ready to merge' after getting sign off from @davidmu1

2020-12-19 00:10 UTC, opbld31 commented
Docs Build status updates of commit _[666bbae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/666bbaed2156d7cb2d896af3c656fb4514a8125a)_: 

:clock10: **Pending**: waiting for processors ([39](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 39 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-19 00:11 UTC, opbld31 commented
Docs Build status updates of commit _[666bbae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/666bbaed2156d7cb2d896af3c656fb4514a8125a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190010067813-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U3JDX%2BI0PywVJZ0QOxwEfEGFcqbFWOaj6FRCzakRHuA%3D&st=2020-12-19T00%3A06%3A18Z&se=2021-01-19T00%3A11%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 02:57 UTC, Lauragra commented on api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md
> +
Please add the missing beta disclaimer to all new topics.

2020-12-19 03:19 UTC, opbld31 commented
Docs Build status updates of commit _[b4cd27d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4cd27dc71a01488fa78d841dbc58e328e56e644)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-477cd429)

<a id="477cd429"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190318427742-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CQRhaXLAH9wSVorGmmSgHtmo38TSeg6zKNAL2ntwymI%3D&st=2020-12-19T03%3A14%3A14Z&se=2021-01-19T03%3A19%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 03:29 UTC, opbld32 commented
Docs Build status updates of commit _[ce89b94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ce89b94022d7d3c48c97ddc7b50eb5441c034fcb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-list-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationeventspolicy-post-onsignupstart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-post-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-delete?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-get?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-put.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-put.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-put?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/api/authenticationlistener-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/api/authenticationlistener-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationlistener-update?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationeventspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationeventspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationeventspolicy?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/authenticationsourcefilter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/authenticationsourcefilter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationsourcefilter?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/resources/invokeuserflowlistener.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/resources/invokeuserflowlistener.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/invokeuserflowlistener?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationeventspolicy-list-onsignupstart?view=graph-rest-beta&branch=pr-en-us-10224) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jodougla-authenticationEventsPolicy/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10224) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190328092312-10224%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uyMwb5AJDJo%2FWgkVKBFjNWw1a6YlXHytinqH%2FqDJctI%3D&st=2020-12-19T03%3A24%3A21Z&se=2021-01-19T03%3A29%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 03:31 UTC, merged