isDefaultCalendar Property added to v1
microsoftgraph/microsoft-graph-docs pull request #10256
Opened 2020-10-11 14:04 UTC by Bhupesh12Hub

@angelgolfer-ms ,

Please review the PR.
Thanks

2020-10-11 14:05 UTC, opbld31 commented
Docs Build status updates of commit _[b906794](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b906794f4d6895974f0431e2552471546ed5f6e6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-66b0987e)

<a id="66b0987e"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010111404396835-10256%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ko1%2FK6mB7PYhf18Z%2FDkIj8BnLeckUYmaedpfDArnl%2Fo%3D&st=2020-10-11T14%3A00%3A40Z&se=2020-11-11T14%3A05%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-11 14:22 UTC, opbld31 commented
Docs Build status updates of commit _[e70bead](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e70bead7541c43274bee9b17ec160a14f96280ab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/formatprotection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/formatprotection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/formatprotection-get?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-601687eb-68708b69)
[api-reference/beta/api/icon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/icon-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/icon-get?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-81bfe83c-68708b69)
[api-reference/beta/api/nameditem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/nameditem-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-get?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-d56d118c-68708b69)
[api-reference/beta/api/nameditem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/nameditem-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-list?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-5c5f4029-68708b69)
[api-reference/beta/api/permission-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/permission-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-46c92772-68708b69)
[api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-40a02138-68708b69)
[api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-2aa2f409-68708b69)
[api-reference/beta/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/print-list-printers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-printers?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-14bacc66-68708b69)
[api-reference/beta/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/print-post-shares.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-post-shares?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-04604c27-68708b69)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-1e948d74-68708b69)
[api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-e4decd48-68708b69)
[api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-3d2fafe2-68708b69)
[api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-9d3eafd4-68708b69)
[api-reference/beta/api/printer-delete-alloweduser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/printer-delete-alloweduser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-delete-alloweduser?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-e0530a19-68708b69)
[api-reference/beta/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/printer-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-delete?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-da39a705-68708b69)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-8b03a81b-68708b69)
[api-reference/beta/api/printer-getcapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/printer-getcapabilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-getcapabilities?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-8eb2b0ee-68708b69)
[api-reference/beta/api/printer-list-allowedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/printer-list-allowedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-list-allowedgroups?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-c0eadfe2-68708b69)
[api-reference/beta/api/printer-list-allowedusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/printer-list-allowedusers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-list-allowedusers?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-dd3b5cd2-68708b69)
[api-reference/beta/api/printer-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/printer-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-list-connectors?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details [...]

2020-10-11 15:55 UTC, opbld30 commented
Docs Build status updates of commit _[945c64f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/945c64f6420e4dfe235d227b51f5c87343e940ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10256) | [Details](#user-content-de0bbbbb-26aa8f2c)
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |

<a id="de0bbbbb-26aa8f2c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md)
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendar?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 41, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 42, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 48, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 49, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 55, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-mobileappinstalltimesettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappassignmentsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappinstallexperience?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsiinformation?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapppowershellscriptrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappproductcoderule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprestartsettings?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappreturncode?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 56, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapprule?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-shared-runasaccounttype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappfilesystemoperationtype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappmsipackagetype?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobappnotification?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - ** [...]

2020-10-20 08:23 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/calendar.md
>    "name": "string",
Just adding the property to the parent resource topic is not sufficient. You also need to check if the property is updateable (if do, you should add it to the "Request body" section in the PATCH topic), and add the property to existing examples as part of the response payload in v1. See this CDK topic: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55086/Promote-beta-documentation-to-GA?anchor=collect-and-update-content

As a start, you can always search in VS Code where the property is referenced in beta, do the similar in v1, and then step back and review if there's any other topic that should include the property.

2020-10-20 08:28 UTC, angelgolfer-ms commented on concepts/changelog.md
> +### Calendar
Why did you replace the pre-existing section?

Also, you need to update the corresponding changelog json file. I forwarded an earlier email from @Lauragra regarding the current changelog process. Please double-check if you're included in the distribution group so that you won't miss similar emails in the future. Please also follow the ongoing process.

2020-10-20 08:29 UTC, angelgolfer-ms requested changes
@Bhupesh12Hub, please see my comments and incorporate the feedback accordingly.

2020-11-26 13:59 UTC, opbld31 commented
Docs Build status updates of commit _[74b10af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74b10af7f3308b09e5ccbe69f31eb0746f102297)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f414f0a8)

<a id="f414f0a8"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011261359018939-10256%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Sh9p8qA7vrpznA%2FlUAVSn3tv4YzsdOa3BBThq7zi7uU%3D&st=2020-11-26T13%3A54%3A20Z&se=2020-12-27T13%3A59%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-26 14:13 UTC, opbld30 commented
Docs Build status updates of commit _[865965f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/865965fdcaf139e1880278383a9e5b13c978958a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/activities-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/activities-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/activities-list?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-5ba57854-767fff5a)
[api-reference/beta/api/driveitem-restore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/driveitem-restore.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-restore?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-1fe644aa-767fff5a)
[api-reference/beta/api/ediscoverycase-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/ediscoverycase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-delete?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-0cf87949-767fff5a)
[api-reference/beta/api/ediscoverycase-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/ediscoverycase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-list?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-686f0a31-767fff5a)
[api-reference/beta/api/ediscoverycase-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/ediscoverycase-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-post?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-f03fc281-767fff5a)
[api-reference/beta/api/ediscoverycase-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/ediscoverycase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-update?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-6bb5760f-767fff5a)
[api-reference/beta/api/educationalactivity-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/educationalactivity-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-delete?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-591908b5-767fff5a)
[api-reference/beta/api/educationalactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/educationalactivity-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-get?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-e82c98d3-767fff5a)
[api-reference/beta/api/educationalactivity-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/educationalactivity-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-update?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-c8045151-767fff5a)
[api-reference/beta/api/filter-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/filter-apply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/filter-apply?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-9902448c-767fff5a)
[api-reference/beta/api/filter-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/filter-clear.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/filter-clear?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-57baf092-767fff5a)
[api-reference/beta/api/formatprotection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/formatprotection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/formatprotection-get?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-601687eb-767fff5a)
[api-reference/beta/api/formatprotection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/formatprotection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/formatprotection-update?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-e8edf6d1-767fff5a)
[api-reference/beta/api/inferenceclassification-list-overrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/inferenceclassification-list-overrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassification-list-overrides?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-b0b224dc-767fff5a)
[api-reference/beta/api/inferenceclassification-post-overrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/inferenceclassification-post-overrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassification-post-overrides?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-c371ea37-767fff5a)
[api-reference/beta/api/inferenceclassificationoverride-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/inferenceclassificationoverride-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassificationoverride-delete?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-54061903-767fff5a)
[api-reference/beta/api/inferenceclassificationoverride-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/inferenceclassificationoverride-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassificationoverride-update?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-2c6a0928-767fff5a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10256) | [Details](#user-content-de0bbbbb-767fff5a)
[api-reference/beta/api/intune-shared-devicemanagementscript-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/intune-shared-devicemanagementscript-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-shared-devicemanagementscript-update?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-784cd7ca-767fff5a)
[api-reference/beta/api/printjob-startprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/fe [...]

2020-11-26 14:15 UTC, opbld32 commented
Docs Build status updates of commit _[6d15df6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d15df646523505e8d4cbd85796390a78847bfe8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10256) | [Details](#user-content-de0bbbbb-b3dfa2cc)
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |

<a id="de0bbbbb-b3dfa2cc"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md)
 - **Line 210, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendar?view=graph-rest-1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011261412369354-10256%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uGUGeQddcg4uigHNTaLHjNNAGc9kfCXtJbiA9kYd85U%3D&st=2020-11-26T14%3A09%3A59Z&se=2020-12-27T14%3A14%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-26 15:12 UTC, opbld34 commented
Docs Build status updates of commit _[825f4ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/825f4ec4ad2ac0c82c505aed38d348e19423c609)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/ediscoverycase-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/ediscoverycase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-delete?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-0cf87949-723d7fc1)
[api-reference/beta/api/ediscoverycase-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/ediscoverycase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-list?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-686f0a31-723d7fc1)
[api-reference/beta/api/ediscoverycase-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/ediscoverycase-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-post?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-f03fc281-723d7fc1)
[api-reference/beta/api/ediscoverycase-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/ediscoverycase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-update?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-6bb5760f-723d7fc1)
[api-reference/beta/api/educationalactivity-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/educationalactivity-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-delete?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-591908b5-723d7fc1)
[api-reference/beta/api/educationalactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/educationalactivity-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-get?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-e82c98d3-723d7fc1)
[api-reference/beta/api/educationalactivity-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/educationalactivity-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-update?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) | [Details](#user-content-c8045151-723d7fc1)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10256) | [Details](#user-content-de0bbbbb-723d7fc1)
[api-reference/beta/api/activities-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/activities-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/activities-list?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) |
[api-reference/beta/api/driveitem-restore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/driveitem-restore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-restore?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) |
[api-reference/beta/api/filter-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/filter-apply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/filter-apply?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) |
[api-reference/beta/api/filter-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/filter-clear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/filter-clear?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) |
[api-reference/beta/api/formatprotection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/formatprotection-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/formatprotection-get?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) |
[api-reference/beta/api/formatprotection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/formatprotection-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/formatprotection-update?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) |
[api-reference/beta/api/inferenceclassification-list-overrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/inferenceclassification-list-overrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassification-list-overrides?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) |
[api-reference/beta/api/inferenceclassification-post-overrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/inferenceclassification-post-overrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassification-post-overrides?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) |
[api-reference/beta/api/inferenceclassificationoverride-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/inferenceclassificationoverride-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassificationoverride-delete?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) |
[api-reference/beta/api/inferenceclassificationoverride-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/inferenceclassificationoverride-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/inferenceclassificationoverride-update?view=graph-rest-beta&branch=pr-en-us-10256) (graph-rest-beta) |
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |

<a id="0cf87949-723d7fc1"></a>
### [api-reference/beta/api/ediscoverycase-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/beta/api/ediscoverycase-delete.md)
 - **Line 7, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'compliance'.`````

<a id="686f0a31-723d7fc1"></a>
### [api-reference/beta/api/ediscoverycase-list.md](https://gith [...]

2020-11-26 15:22 UTC, opbld32 commented
Docs Build status updates of commit _[6a29269](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a29269f2e872df71fafd2c11bdc34e1bc4d6056)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10256) | [Details](#user-content-de0bbbbb-2ef8c3ec)
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |

<a id="de0bbbbb-2ef8c3ec"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md)
 - **Line 210, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendar?view=graph-rest-1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011261520242935-10256%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qrkXeJcn5NEtJe1uLoNTRGkXSmnsLUSP%2FXKW2RTw5CQ%3D&st=2020-11-26T15%3A17%3A01Z&se=2020-12-27T15%3A22%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-26 16:20 UTC, opbld32 commented
Docs Build status updates of commit _[9b210a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b210a37b6ad50dc75c00b71a279af22f5214198)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10256) | [Details](#user-content-de0bbbbb-9218af93)
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |

<a id="de0bbbbb-9218af93"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendar?view=graph-rest-1.0`````
 - **Line 216, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 217, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 218, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 219, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta`````
 - **Line 220, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta`````
 - **Line 220, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta`````
 - **Line 220, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011261618443143-10256%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rkFJk6O06m16O1F4bUwMJSRBexq%2FTjYR9x6Oe2P0TEU%3D&st=2020-11-26T16%3A15%3A21Z&se=2020-12-27T16%3A20%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-03 09:22 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Addition | beta | Added new action to retrieve an [onlineMeeting](/graph/api/resources/onlinemeeting?view=graph-rest-beta&preserve-view=true) by JoinWebUrl.|
Can you make sure that the Cloud communications table includes a third table row that has the description:
"Added the platformId property to the participantInfo resource."
You can check the changelog.md file on the live site to make sure add the third row, and don't inadvertently update the table with one less row.

2020-12-03 09:24 UTC, angelgolfer-ms commented on concepts/changelog.md
>  ### Calendar
Line 120:
Please remove this section title!

2020-12-03 09:25 UTC, angelgolfer-ms commented on concepts/changelog.md
>  ## November 2020
Now it's December, please move your changelog item to the December section in changelog.md.

2020-12-03 09:25 UTC, angelgolfer-ms commented on concepts/changelog.md
>  ## November 2020
Please also make sure you update the corresponding changelog json file for this update.

2020-12-03 09:29 UTC, angelgolfer-ms requested changes
@Bhupesh12Hub , it seems that since my last review, the only update you have made is in the changelog.md file.
Can you please address the main review comment from my last review: https://github.com/microsoftgraph/microsoft-graph-docs/pull/10256#discussion_r508304834

2020-12-04 04:43 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Addition | v1.0 | Added the **isDefaultCalendar** property to the [calendar](/graph/api/resources/calendar?view=graph-rest-1.0) entity.
Line 20 and GLOBAL:
Please note that in general, when you create a "site-relative" link and include the query parameter ?view, you now need to include preserve-view=true. This requirement applies to all existing site-relative links in the topic too, not just new links. Ignoring this requirement would trigger a build warning, You can find more info here:
https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master#links-to-articles-in-other-repos-or-docsets
https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master#links-to-specific-versions

So for the site-relative links you have in line 20, I suggest you either add preserve-view=true, or, simply drop ?view=graph-rest-1.0. When you drop ?view=graph-rest-1.0, OPS would just default to the v1 version, which is the intended purpose in this case.

2020-12-16 08:37 UTC, opbld32 commented
Docs Build status updates of commit _[bd6102d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd6102d56039731fbb3762720445f621fb00a6b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10256) | [Details](#user-content-de0bbbbb-ac0361b5)
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |

<a id="de0bbbbb-ac0361b5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendar?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 74, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 298, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 299, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 300, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 301, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta`````
 - **Line 302, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta`````
 - **Line 302, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta`````
 - **Line 302, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160836219892-10256%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4%2FIthkqdciIk%2B7prvFRwSkmjLANjZ4chPTuk4TAKqcE%3D&st=2020-12-16T08%3A32%3A57Z&se=2021-01-16T08%3A37%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 16:25 UTC, opbld33 commented
Docs Build status updates of commit _[ef82872](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ef828724c6402ab3e453e95e8f41661aa0feae5a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10256) | [Details](#user-content-de0bbbbb-4b35cf59)
[api-reference/v1.0/api/calendar-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/api/calendar-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/api/calendar-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-update?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-4b35cf59"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendar?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 74, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 296, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 297, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 298, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 299, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta`````
 - **Line 300, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta`````
 - **Line 300, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta`````
 - **Line 300, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012161623282062-10256%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TXBT7GyIUsaRJ6eR3N1IMBC0e0QYCXf9QHV4lANm%2F%2Bk%3D&st=2020-12-16T16%3A20%3A04Z&se=2021-01-16T16%3A25%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 16:26 UTC, Bhupesh12Hub commented on concepts/changelog.md
> +| Addition | beta | Added new action to retrieve an [onlineMeeting](/graph/api/resources/onlinemeeting?view=graph-rest-beta&preserve-view=true) by JoinWebUrl.|
done

2020-12-16 16:27 UTC, Bhupesh12Hub commented on concepts/changelog.md
>  ### Calendar
Done

2020-12-16 16:27 UTC, Bhupesh12Hub commented on concepts/changelog.md
>  ## November 2020
Done, added changelog json.

2020-12-16 16:31 UTC, Bhupesh12Hub commented on api-reference/v1.0/resources/calendar.md
>    "name": "string",
Done.

2020-12-17 17:19 UTC, Bhupesh12Hub commented
@angelgolfer-ms, i have resolved the feedback, if everything is good to go we can push the PR to merge state.

@Lauragra @Harini84

2020-12-19 03:09 UTC, angelgolfer-ms commented on concepts/changelog.md
@Bhupesh12Hub , but you didn't fix the site-relative link in line 20, per my previous comment (https://github.com/microsoftgraph/microsoft-graph-docs/pull/10256#discussion_r535831888)!

Did you have a question about the why or the how?

2020-12-19 04:45 UTC, opbld32 commented
Docs Build status updates of commit _[27ca8d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27ca8d292770de27817213fb1ac5105ec6d26235)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d48175b8)

<a id="d48175b8"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190445072652-10256%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NGZfn7fwxBmkmTHNRdaV101BwnMb%2B%2FuyB2hlVzOXziQ%3D&st=2020-12-19T04%3A40%3A24Z&se=2021-01-19T04%3A45%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 05:01 UTC, opbld32 commented
Docs Build status updates of commit _[15eda3e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15eda3ed0d594922a47094b99507044f6311c5c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/api/calendar-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/api/calendar-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-update?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10256) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190500158402-10256%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xGwKK%2F1SZbfkRKHgNKFnxw3MPkkhZW%2BDn3yduizyffA%3D&st=2020-12-19T04%3A56%3A33Z&se=2021-01-19T05%3A01%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 05:03 UTC, opbld33 commented
Docs Build status updates of commit _[ef32b3c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ef32b3ca881e759a71b230e221945bf97a8dd5e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/api/calendar-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/api/calendar-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-update?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190500280274-10256%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hFVONATXsHYcLudLlccT%2FVEWaKsKucJQA%2F2vbwayGrQ%3D&st=2020-12-19T04%3A58%3A14Z&se=2021-01-19T05%3A03%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 05:09 UTC, opbld31 commented
Docs Build status updates of commit _[bdd7cf2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bdd7cf2f006eb18029c6e51284acbc1979218a8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10256) | [Details](#user-content-de0bbbbb-c2daa6ce)
[api-reference/v1.0/api/calendar-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/api/calendar-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/api/calendar-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-update?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-c2daa6ce"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calendar?view=graph-rest-1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190507449306-10256%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=I9KI3fFSfdD0y6sdyLaLjgwg39%2F1jac6XJ8sDs41RJ8%3D&st=2020-12-19T05%3A04%3A08Z&se=2021-01-19T05%3A09%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 05:11 UTC, opbld34 commented
Docs Build status updates of commit _[c432f87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c432f87498fd892dddb5a9f897b7610c459f055c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/api/calendar-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |
[api-reference/v1.0/api/calendar-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/api/calendar-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-update?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/api-reference/v1.0/resources/calendar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0&branch=pr-en-us-10256) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/isDefaultCalendar/v1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10256) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190510259731-10256%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P1zdNDGPKoC68gu6L7im0yG%2FEOTGZYygIiuJLLgMJak%3D&st=2020-12-19T05%3A06%3A53Z&se=2021-01-19T05%3A11%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 05:16 UTC, merged

2020-12-19 05:18 UTC, angelgolfer-ms commented on concepts/changelog.md
> @Bhupesh12Hub , hm, you didn't fix the site-relative link in line 20, per my previous comment ([#10256 (comment)](https://github.com/microsoftgraph/microsoft-graph-docs/pull/10256#discussion_r535831888)).
> 
> Did you have a question about the why or the how?

@Bhupesh12Hub , FYI since today is the last day to publish this year, I fixed the link and merged this PR. Do take a look if you understand what to do with site-relative links in general.

2020-12-19 05:20 UTC, angelgolfer-ms commented
@Bhupesh12Hub , as commented, I resolved the merge conflict and fixed the link in changelog.md, so to catch publishing before the end of today (for the year). Please make sure you understand what to do with site-relative links in general, and let me know if you have questions.