To Do v1.0 docs
microsoftgraph/microsoft-graph-docs pull request #10254
Opened 2020-10-10 19:40 UTC by avijityadav

2020-10-10 19:42 UTC, opbld32 commented
Docs Build status updates of commit _[ab815ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab815aecbf634b7d12aafd8f2a8055c16577a26d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-delete.md) | :x:Error | | [Details](#user-content-691ac2c7-99ace33c)
[api-reference/v1.0/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-get.md) | :x:Error | | [Details](#user-content-3c1d8b1a-99ace33c)
[api-reference/v1.0/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-update.md) | :x:Error | | [Details](#user-content-7e0f2321-99ace33c)
[api-reference/v1.0/api/todo-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-list-lists.md) | :x:Error | | [Details](#user-content-2eefedc3-99ace33c)
[api-reference/v1.0/api/todo-post-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-post-lists.md) | :x:Error | | [Details](#user-content-e74a3852-99ace33c)
[api-reference/v1.0/api/todotask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotask-delete.md) | :x:Error | | [Details](#user-content-f22ff400-99ace33c)
[api-reference/v1.0/api/todotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotask-get.md) | :x:Error | | [Details](#user-content-98f88cea-99ace33c)
[api-reference/v1.0/api/todotask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotask-list-linkedresources.md) | :x:Error | | [Details](#user-content-4f25d1ac-99ace33c)
[api-reference/v1.0/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotask-post-linkedresources.md) | :x:Error | | [Details](#user-content-d0fd3877-99ace33c)
[api-reference/v1.0/api/todotask-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotask-update.md) | :x:Error | | [Details](#user-content-1a2c0cbe-99ace33c)
[api-reference/v1.0/api/todotasklist-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-delete.md) | :x:Error | | [Details](#user-content-d6cb6714-99ace33c)
[api-reference/v1.0/api/todotasklist-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-get.md) | :x:Error | | [Details](#user-content-a4e0b08f-99ace33c)
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-list-tasks.md) | :x:Error | | [Details](#user-content-1784746a-99ace33c)
[api-reference/v1.0/api/todotasklist-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-post-tasks.md) | :x:Error | | [Details](#user-content-fd1b7069-99ace33c)
[api-reference/v1.0/api/todotasklist-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-update.md) | :x:Error | | [Details](#user-content-d4b53ff3-99ace33c)
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | | [Details](#user-content-beb03a48-99ace33c)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | | [Details](#user-content-afc51dc4-99ace33c)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | | [Details](#user-content-6f302778-99ace33c)
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/delta-query-overview.md) | :bulb:Suggestion | | [Details](#user-content-2447e7b4-99ace33c)
[concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/extensibility-overview.md) | :bulb:Suggestion | | [Details](#user-content-801b437d-99ace33c)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/overview-major-services.md) | :bulb:Suggestion | | [Details](#user-content-f985040c-99ace33c)

<a id="691ac2c7-99ace33c"></a>
### [api-reference/v1.0/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-delete.md)
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/delete-linkedresource-csharp-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/delete-linkedresource-javascript-snippets.md'.`````
 - **Line 70, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/delete-linkedresource-objc-snippets.md'.`````

<a id="3c1d8b1a-99ace33c"></a>
### [api-reference/v1.0/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-get.md)
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-linkedresource-csharp-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-linkedresource-javascript-snippets.md'.`````
 - **Line 70, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-linkedresource-objc-snippets.md'.`````

<a id="7e0f2321-99ace33c"></a>
### [api-reference/v1.0/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-update.md)
 - **Line 78, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-linkedresource-javascript-snippets.md'.`````
 - **Line 82, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-linkedresource-csharp-snippets.md'. [...]

2020-10-12 16:08 UTC, opbld34 commented
Docs Build status updates of commit _[15b2fec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15b2fec26af27f5e89ca8f25ed95484bb0f99e7c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) | [Details](#user-content-beb03a48-543683e1)
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-1784746a-543683e1)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-afc51dc4-543683e1)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-6f302778-543683e1)
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/delta-query-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-10254) | [Details](#user-content-2447e7b4-543683e1)
[concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/extensibility-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-overview?branch=pr-en-us-10254) | [Details](#user-content-801b437d-543683e1)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-10254) | [Details](#user-content-f985040c-543683e1)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/v1.0/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-list-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-list-lists?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-post-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-post-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-post-lists?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delta?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-linkedresources?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedreso [...]

2020-10-16 02:58 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/opentypeextension.md
> +| [Task list](todotasklist.md)  | GA ||
In line 91 of this topic, please also update the description for the create operation, by adding the following:
[post](post.md), [todoTask](todotask.md), or [todoTaskList](todotasklist.md)

Looks like group post has been missing all along there, so please include the post entity as well while you're at it.

2020-10-16 03:10 UTC, angelgolfer-ms commented on concepts/delta-query-overview.md
> +| Task lists (preview)                                           | [delta](/graph/api/todotasklist-delta) function of the [todoTaskList](/graph/api/resources/todotasklist) resource
Lines 127 and 128: 
Please also remove the 2 instances of "(preview)" in the first column of the table.

2020-10-16 03:13 UTC, angelgolfer-ms commented on concepts/todo-concept-overview.md
> -| List all the task lists | GET https://graph.microsoft.com/beta/me/todo/lists |
Line 9:
Please remove the "(preview)" in the topic title.

2020-10-16 03:27 UTC, angelgolfer-ms commented on concepts/todo-concept-overview.md
> +- [To Do API in Microsoft Graph](/graph/api/resources/todo-overview?view=graph-rest-1.0)
Line 40:
Please just drop the last part of the link, i.e., ?view=graph-rest-1.0.
FYI the DevRel team (which owns docs.microsoft.com) recently changed the way to include ?view in a link; you'd need to include an additional preserve-view parameter in the link. Without specifying ?view and a version already works for your case since your API is GA-ing, so let's just do that.
See this topic for more info about linking: https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master#links-to-specific-versions

2020-10-16 06:26 UTC, angelgolfer-ms commented on concepts/delta-query-overview.md
> +| Task lists (preview)                                           | [delta](/graph/api/todotasklist-delta) function of the [todoTaskList](/graph/api/resources/todotasklist) resource
Also, I just noticed in line 190, there's a sentence that says:
"... For Outlook entities (message, mailFolder, event, contact, contactFolder), the upper limit is not fixed;..."
Can you see if todoTask and todoTaskList fall into the same category, and if so, include these 2 entities in that sentence, and if not, make clarification there?

2020-10-16 06:47 UTC, angelgolfer-ms commented on api-reference/v1.0/api/todotasklist-delta.md
> +The following example shows how to make a single **delta** function call, and limit the maximum number of **todoTaskList** in the response body to 2.
I just noticed that since in this topic, we only show one delta function call as an example, we should show the initial call (which always needs to take place no matter whether there are any changes to track and whether a subsequent call is necessary).
So please make the following changes in this v1 topic, and do the similar in the beta topic:
Line 69:
Please say "... how to make an initial **delta** function call,..."

In line 78:
Remove the last part of the query URL, just show in line 78
GET https://graph.microsoft.com/v1.0/me/todo/lists/delta

2020-10-16 06:54 UTC, angelgolfer-ms commented on api-reference/v1.0/api/opentypeextension-post-opentypeextension.md
> +POST /users/{id|userPrincipalName}/todo/lists/{id}/extensions
Lines 73 and 74:
Can you please swap the two lines, showing the syntax for task list first, followed by the syntax for task?
That order would be consistent with lines 49-50, and also consistent with the order of the task list and task resources in the TOC.

Please also do that same in the beta topic.
Consistency in order helps customers to learn.

2020-10-16 07:02 UTC, angelgolfer-ms commented on api-reference/v1.0/api/todotasklist-delta.md
> +### HTTP Request
Please delete line 75.

Please do the same in the beta topic.

2020-10-16 10:27 UTC, avijityadav commented on api-reference/v1.0/resources/opentypeextension.md
> +| [Task list](todotasklist.md)  | GA ||
Added

2020-10-16 10:36 UTC, avijityadav commented on concepts/delta-query-overview.md
> +| Task lists (preview)                                           | [delta](/graph/api/todotasklist-delta) function of the [todoTaskList](/graph/api/resources/todotasklist) resource
Added todoTask and todoTaskList with outlook entities after discussing with @bgaonkar

2020-10-16 10:36 UTC, avijityadav commented on concepts/todo-concept-overview.md
> +- [To Do API in Microsoft Graph](/graph/api/resources/todo-overview?view=graph-rest-1.0)
Removed ?view=graph-rest-1.0

2020-10-16 10:37 UTC, avijityadav commented on api-reference/v1.0/api/opentypeextension-post-opentypeextension.md
> +POST /users/{id|userPrincipalName}/todo/lists/{id}/extensions
Yes, swapped it to make it consistent. Thanks for the feedback.

2020-10-16 10:37 UTC, avijityadav commented on api-reference/v1.0/api/todotasklist-delta.md
> +### HTTP Request
Done.

2020-10-16 10:44 UTC, avijityadav commented on concepts/todo-concept-overview.md
> -| List all the task lists | GET https://graph.microsoft.com/beta/me/todo/lists |
Removed it.

2020-10-16 14:32 UTC, avijityadav commented on api-reference/v1.0/api/todotasklist-delta.md
> +The following example shows how to make a single **delta** function call, and limit the maximum number of **todoTaskList** in the response body to 2.
Made the change.

2020-10-16 14:38 UTC, opbld32 commented
Docs Build status updates of commit _[0eaf560](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0eaf560b56542035df189e5e972ed55b1dd65419)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) | [Details](#user-content-beb03a48-d5934882)
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-1784746a-d5934882)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/opentypeextension.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-afc51dc4-d5934882)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-6f302778-d5934882)
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/delta-query-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-10254) | [Details](#user-content-2447e7b4-d5934882)
[concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/extensibility-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-overview?branch=pr-en-us-10254) | [Details](#user-content-801b437d-d5934882)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-10254) | [Details](#user-content-f985040c-d5934882)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/v1.0/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-list-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-list-lists?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-post-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-post-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-post-lists?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotask-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delta?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todotask-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotask-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ [...]

2020-10-17 01:58 UTC, angelgolfer-ms commented on api-reference/v1.0/api/todotask-delta.md
> +To track changes in the **todoTask** resources in a **todoTaskList**, you would make one or more **delta** function calls to get the set
Lines 74-78:
FYI similar to my comment in the example for todotasklist-delta.md, I made a change here to give better context why there's a deltaToken in this example request. I applied that update to both the v1 and beta topics.

2020-10-17 02:57 UTC, angelgolfer-ms commented on api-reference/v1.0/api/todotask-list-linkedresources.md
> +Get the linkedResources from the linkedResources navigation property.
Line 13:
FYI I made this description more helpful, in both the v1 and beta versions.
A new customer landing in this topic by search would have no idea what a linkedResource does.

2020-10-17 05:52 UTC, angelgolfer-ms commented on api-reference/v1.0/api/todotask-post-linkedresources.md
> +Create a new **linkedResource** object.
Line 13:
FYI I also added some context to this description so that customers landing on this page from search has an idea what a linkedResource is for.
I updated the beta topic as well.

2020-10-17 06:00 UTC, opbld34 commented
Docs Build status updates of commit _[f60c2de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f60c2dea16c989b7e2bece29399dcb2e9cda2dad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) | [Details](#user-content-beb03a48-78240d55)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-afc51dc4-78240d55)
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-1784746a-78240d55)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-6f302778-78240d55)
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/delta-query-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-10254) | [Details](#user-content-2447e7b4-78240d55)
[concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/extensibility-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-overview?branch=pr-en-us-10254) | [Details](#user-content-801b437d-78240d55)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-10254) | [Details](#user-content-f985040c-78240d55)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/v1.0/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-list-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-list-lists?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-post-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-post-lists.md [...]

2020-10-17 06:02 UTC, opbld33 commented
Docs Build status updates of commit _[73db23d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73db23d5b5a8e94b950c82bea4bc45bb933e474f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) | [Details](#user-content-beb03a48-ce25a2bc)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-afc51dc4-ce25a2bc)
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-1784746a-ce25a2bc)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-6f302778-ce25a2bc)
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/delta-query-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-10254) | [Details](#user-content-2447e7b4-ce25a2bc)
[concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/extensibility-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-overview?branch=pr-en-us-10254) | [Details](#user-content-801b437d-ce25a2bc)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-10254) | [Details](#user-content-f985040c-ce25a2bc)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/v1.0/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-list-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-list-lists?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-post-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-post-lists.md [...]

2020-10-17 07:16 UTC, opbld33 commented
Docs Build status updates of commit _[1647123](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1647123c80832e75d0c8e192fc20788733ce4a92)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) | [Details](#user-content-beb03a48-e89ed2f1)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-afc51dc4-e89ed2f1)
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-1784746a-e89ed2f1)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-6f302778-e89ed2f1)
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/delta-query-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-10254) | [Details](#user-content-2447e7b4-e89ed2f1)
[concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/extensibility-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-overview?branch=pr-en-us-10254) | [Details](#user-content-801b437d-e89ed2f1)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-10254) | [Details](#user-content-f985040c-e89ed2f1)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/v1.0/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-list-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-list-lists?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-post-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-post-lists.md [...]

2020-10-17 07:38 UTC, angelgolfer-ms commented on concepts/todo-concept-overview.md
> -| List all the task lists | GET https://graph.microsoft.com/beta/me/todo/lists |
Oh, didn't notice this yesterday - please also remove "(preview)" from the TOC title of todo-concept-overview.md.

2020-10-17 07:47 UTC, angelgolfer-ms reviewed
@avijityadav , thanks for incorporating feedback from yesterday so quickly.
Please take a look at some clarifications I made to a few descriptions overlooked in the first release.
Also, as feedback for you:
- There's one TOC issue to fix, per my comment from today.
- Would you like to add a sub-node for todoTask under the "Users" node in each of the v1 and beta reference, just like the"Mail" sub-node or "Calendar" sub-node?

2020-10-20 11:01 UTC, opbld30 commented
Docs Build status updates of commit _[348f0b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/348f0b016c90f6846f3015014c0a858b051d6d0f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) | [Details](#user-content-beb03a48-b7d6a304)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-afc51dc4-b7d6a304)
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-1784746a-b7d6a304)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-6f302778-b7d6a304)
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/delta-query-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-10254) | [Details](#user-content-2447e7b4-b7d6a304)
[concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/extensibility-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-overview?branch=pr-en-us-10254) | [Details](#user-content-801b437d-b7d6a304)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-10254) | [Details](#user-content-f985040c-b7d6a304)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/v1.0/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-list-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todo-list-lists?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-post-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-post-lists.md [...]

2020-10-20 23:31 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/user.md
> +|[Create todoTasklist](../api/todo-post-lists.md) | [todoTaskList](todotasklist.md) | Create a To Do task list in the user's mailbox. |
FYI, per our internal Teams chat, I suggested we should include the list and create operations for task as well. I went ahead to add them to the Methods table in the user entity topic, for both v1 and beta. Please take a look on the staging site.
We also overlooked marking the deprecated Outlook task entry points in the Methods table of the beta user entity topic. I followed the deprecation guidance (https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/73842/Deprecate-docs?anchor=deprecate-content-for-a-method) and took care of that in the beta user entity topic.

2020-10-20 23:43 UTC, opbld30 commented
Docs Build status updates of commit _[abc54f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/abc54f5a752fcb6693ad2702de434a37a9d863d8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) | [Details](#user-content-beb03a48-7c960f6e)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-afc51dc4-7c960f6e)
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-1784746a-7c960f6e)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-6f302778-7c960f6e)
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/delta-query-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-10254) | [Details](#user-content-2447e7b4-7c960f6e)
[concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/extensibility-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-overview?branch=pr-en-us-10254) | [Details](#user-content-801b437d-7c960f6e)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-10254) | [Details](#user-content-f985040c-7c960f6e)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/v1.0/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-list-lists.md) | :white_c [...]

2020-10-20 23:43 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +      - name: To-do tasks
Per our discussion on Teams, I exposed the create and list operations for task as well under the Users node. I did that for both beta and v1.

2020-10-20 23:54 UTC, opbld31 commented
Docs Build status updates of commit _[1d882e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d882e0b7d04e23d4f79d6d6b09c6b2ff423a1f4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) | [Details](#user-content-beb03a48-e77e594f)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-afc51dc4-e77e594f)
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-1784746a-e77e594f)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-6f302778-e77e594f)
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/delta-query-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-10254) | [Details](#user-content-2447e7b4-e77e594f)
[concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/extensibility-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-overview?branch=pr-en-us-10254) | [Details](#user-content-801b437d-e77e594f)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-10254) | [Details](#user-content-f985040c-e77e594f)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/v1.0/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-list-lists.md) | :white_c [...]

2020-10-21 04:24 UTC, opbld32 commented
Docs Build status updates of commit _[a6438fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a6438fd5024362490bfaf21a39dfa50b8fbea33b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) | [Details](#user-content-beb03a48-9814bb9a)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-afc51dc4-9814bb9a)
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-1784746a-9814bb9a)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-6f302778-9814bb9a)
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/delta-query-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-10254) | [Details](#user-content-2447e7b4-9814bb9a)
[concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/extensibility-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-overview?branch=pr-en-us-10254) | [Details](#user-content-801b437d-9814bb9a)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-10254) | [Details](#user-content-f985040c-9814bb9a)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/v1.0/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-list-lists.md) | :white_c [...]

2020-10-21 04:25 UTC, opbld33 commented
Docs Build status updates of commit _[e66ccd0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e66ccd0dd71a94a533e7b2af344132842a88c50b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) | [Details](#user-content-beb03a48-5a394452)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-afc51dc4-5a394452)
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-1784746a-5a394452)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-6f302778-5a394452)
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/delta-query-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-10254) | [Details](#user-content-2447e7b4-5a394452)
[concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/extensibility-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-overview?branch=pr-en-us-10254) | [Details](#user-content-801b437d-5a394452)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-10254) | [Details](#user-content-f985040c-5a394452)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/v1.0/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-list-lists.md) | :white_c [...]

2020-10-21 04:38 UTC, opbld30 commented
Docs Build status updates of commit _[80d1bb4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80d1bb457a10a91555bd7b73ee8644392761a150)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) | [Details](#user-content-beb03a48-13382815)
[api-reference/v1.0/resources/opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-afc51dc4-13382815)
[api-reference/v1.0/api/todotasklist-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todotasklist-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-1784746a-13382815)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) | [Details](#user-content-6f302778-13382815)
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/delta-query-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-10254) | [Details](#user-content-2447e7b4-13382815)
[concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/extensibility-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/extensibility-overview?branch=pr-en-us-10254) | [Details](#user-content-801b437d-13382815)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-10254) | [Details](#user-content-f985040c-13382815)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-list-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-list-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-list-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotask-post-linkedresources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotask-post-linkedresources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotask-post-linkedresources?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/api/todotasklist-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/api/todotasklist-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/todotasklist-delta?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10254) (graph-rest-beta) |
[api-reference/v1.0/api/linkedresource-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/linkedresource-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/linkedresource-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-delete?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-post-opentypeextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/opentypeextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-1.0&branch=pr-en-us-10254) (>= graph-rest-1.0) |
[api-reference/v1.0/api/todo-list-lists.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/avijityadav-todo-v1/api-reference/v1.0/api/todo-list-lists.md) | :white_c [...]

2020-10-21 04:54 UTC, angelgolfer-ms requested changes
@avijityadav , I have finished the updates to the TOC under the Users node, and in the Methods table of the user entity, as discussed in Teams. The remaining item is adding to the changelog that we're GA-ing the to-do tasks API. I added you to an email with Lauragra, can you please follow up with her on that? 

After completing the changelog updates, I think the PR is good to publish.

2020-10-21 18:03 UTC, Lauragra commented on concepts/changelog.md
> +|Addition|v1.0|Added the [todo](https://docs.microsoft.com/en-us/graph/api/resources/todo?view=graph-rest-1.0) resource type|
For the Markdown file, please use relative links, so remove the "https://docs.microsoft.com/en-us" part. Also please add a period to the end of the sentences.

2020-10-21 18:39 UTC, avijityadav commented on concepts/changelog.md
> +|Addition|v1.0|Added the [todo](https://docs.microsoft.com/en-us/graph/api/resources/todo?view=graph-rest-1.0) resource type|
Fixed it.

2020-10-23 04:12 UTC, angelgolfer-ms commented on changelog/Microsoft.Todo.json
> +          "Id":"ed2954cb-1392-11eb-baa1-5b13c31fb2cd",
Lines 85-92 is a repetition of lines 69-76.
Lines 93-100 is a repetition of lines 77-84.
So lines 85-92, and 93-100 should not be there.
@Lauragra, what is the process to fix this and get the changelog.md regenerated? Can you please follow up? Avijit and their team need the PR to be published in the next day; please sync with him as there's a time zone difference.
The rest of the PR is ready for publishing.

2020-10-23 05:49 UTC, angelgolfer-ms commented on changelog/Microsoft.Todo.json
> +          "Id":"ed2954cb-1392-11eb-baa1-5b13c31fb2cd",
So I decided to remove the repeated lines for the delta functions in the changelog.md file, and leave the repeated lines in this JSON file for folks to debug. Since the JSON file is not customer facing, I'll leave it as is for the time being through publishing. I expect James to get back to confirm where the bug is and if there's any action item on the docs side.

2020-10-23 05:51 UTC, angelgolfer-ms approved these changes
I removed the repeated lines in changelog.md for the two delta functions for todoTaskList and todoTask, so that there's only one line for each.
I also alerted folks to verify if there's a bug somewhere in the tool. So for this PR, I think as soon as Avijit sets it to Ready to merge, we can publish.

2020-10-28 18:13 UTC, angelgolfer-ms approved these changes
Thanks for removing the 2 sets of duplicated changelog JSON lines for the two delta functions; looks good!

2020-10-28 18:15 UTC, merged