People API Changes
microsoftgraph/microsoft-graph-docs pull request #10267
Opened 2020-10-12 15:44 UTC by PeterNjorogeMS

There have a been a few changes in the People API that have been done. I have gone through the doc to remove items that we don't support like Searching for people using topic and changes to the diagram to explain different people search scenarios. 

I also edited the people-example page to make a few changes to ensure the information is fresh and relevant to the changes. Example, removed instances where skype and social media have been mentioned. 

I have not touched the Working With section of the doc.

2020-10-12 15:45 UTC, opbld31 commented
Docs Build status updates of commit _[3ac738a](https://github.com/PeterNjorogeMS/microsoft-graph-docs/commits/3ac738a5f5f86cf0de99906845e8a4a1f3c667bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) | [Details](#user-content-1d7938a4-6940c689)
[concepts/images/social-intel-concept-overview-data-update2020.png](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/images/social-intel-concept-overview-data-update2020.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) |
[concepts/people-example.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/people-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/people-example?branch=pr-en-us-10267) |

<a id="1d7938a4-6940c689"></a>
### [concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md)
 - **Line 31, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/person?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/insights-list-trending?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 80, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 80, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 109, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/social-overview?view=graph-rest-beta#help-users-balance-work-and-life NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 110, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profile?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010121544205878-10267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Upqk9Zkx4OlpTRvR0Wbl0WMYt8x3loDHkIdFF0Lr2R0%3D&st=2020-10-12T15%3A40%3A40Z&se=2020-11-12T15%3A45%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 10:58 UTC, PeterNjorogeMS commented
@simonhult @yinaa I am not sure who helps with Merging/reviewing submitted PRs. I made some changes to the People API documentation and I don't see any movement here, Kindly assist.

2020-10-20 04:50 UTC, angelgolfer-ms commented on concepts/social-intel-concept-overview.md
@PeterNjorogeMS , regarding the new image:
(1) Can you please size it down by 30-40%, considering the sparse content and the proportions to other images in the topic? You can see the layout with the new image on the staging site: https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267

(2) If you decide to use an employee's picture, you should please refer to the CELA recommendations to complete the person/property release form. The CELA info is here: https://microsoft.sharepoint.com/sites/CELAWeb-Copyrights-Trademarks-And-Patents/SitePages/copyrights-third-party-content-using-photographs-in-advertising-products.aspx

Alternatively, you can keep the original profile picture - I think that one was an approved stock photo. More photos on Brand Central (https://microsoft.sharepoint.com/teams/BrandCentral/).

2020-10-20 04:54 UTC, angelgolfer-ms commented on concepts/people-example.md
> +By default, Microsoft Graph serves mailbox-only results, which are your saved contacts or people you are most likely to interact with. To retrieve organizational wide directory results, specify a HTT
Line 475:
Please change to "To retrieve organization-wide directory results, specify an HTTP header, as shown".
Please note the article before "HTTP" is "an", not "a", as a viewer reads "HTTP" as "H-T-T-P", and verbalizing 'H' begins with a vowel.

2020-10-20 05:10 UTC, angelgolfer-ms commented on concepts/people-example.md
> +The following request gets the people most relevant to another person in the signed-in user's organization as described in <a href="#working-with-feature-implementation">Working With </a>feature. Thi
Line 693:
FYI I rephrased the few references to "working with", fixed the punctuation of the section title in line 951, and the way you link to that section. In docs, we use relative links, not HTML links.
Please take a look at the staged topic: https://review.docs.microsoft.com/en-us/graph/people-example?branch=pr-en-us-10267

2020-10-20 05:15 UTC, angelgolfer-ms requested changes
@PeterNjorogeMS , thank you for your PR. Please take a look at my comments and incorporate them accordingly.

2020-10-20 05:17 UTC, opbld34 commented
Docs Build status updates of commit _[13fc1c8](https://github.com/PeterNjorogeMS/microsoft-graph-docs/commits/13fc1c80fdf313a5945c07fe5651bf6eff1b18a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) | [Details](#user-content-1d7938a4-a15ac8bb)
[concepts/images/social-intel-concept-overview-data-update2020.png](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/images/social-intel-concept-overview-data-update2020.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) |
[concepts/people-example.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/people-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/people-example?branch=pr-en-us-10267) |

<a id="1d7938a4-a15ac8bb"></a>
### [concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md)
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/person?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/insights-list-trending?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 80, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 80, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 109, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/social-overview?view=graph-rest-beta#help-users-balance-work-and-life NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 110, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profile?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010200516327760-10267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZLnf8bfFhBI4kgxMzGUSkM5mTT49es13DgW%2B8lRinyQ%3D&st=2020-10-20T05%3A12%3A54Z&se=2020-11-20T05%3A17%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 09:32 UTC, opbld32 commented
Docs Build status updates of commit _[9bf6168](https://github.com/PeterNjorogeMS/microsoft-graph-docs/commits/9bf6168d4e308f90379c0eff485e578fdbea98c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) | [Details](#user-content-1d7938a4-9bfc5138)
[concepts/images/social-intel-concept-overview-data-update2020-1.png](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/images/social-intel-concept-overview-data-update2020-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) |
[concepts/people-example.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/people-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/people-example?branch=pr-en-us-10267) |

<a id="1d7938a4-9bfc5138"></a>
### [concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md)
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/person?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/insights-list-trending?view=graph-rest-1.0`````
 - **Line 80, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0`````
 - **Line 80, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0`````
 - **Line 109, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/social-overview?view=graph-rest-beta#help-users-balance-work-and-life`````
 - **Line 110, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profile?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280931125978-10267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8t0tP8JCLrn7B2ujUXqW3jzjvhDzEXdpmAtwFfoqk%2BA%3D&st=2020-10-28T09%3A27%3A35Z&se=2020-11-28T09%3A32%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 09:48 UTC, opbld31 commented
Docs Build status updates of commit _[9408067](https://github.com/PeterNjorogeMS/microsoft-graph-docs/commits/9408067d1bbb06bb8c777c177ed3eb513983e1a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) | [Details](#user-content-1d7938a4-d3434f23)
[concepts/images/social-intel-concept-overview-data-update2020-1.png](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/images/social-intel-concept-overview-data-update2020-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) |
[concepts/people-example.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/people-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/people-example?branch=pr-en-us-10267) |

<a id="1d7938a4-d3434f23"></a>
### [concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md)
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/person?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/insights-list-trending?view=graph-rest-1.0`````
 - **Line 80, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0`````
 - **Line 80, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0`````
 - **Line 109, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/social-overview?view=graph-rest-beta#help-users-balance-work-and-life`````
 - **Line 110, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profile?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280946401806-10267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sBpI0QLS3E7axdegqOnQz9ILphKfi5HGG6ZJgf8Hedo%3D&st=2020-10-28T09%3A43%3A12Z&se=2020-11-28T09%3A48%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 09:57 UTC, PeterNjorogeMS commented
@angelgolfer-ms I have added the changes as requested.

2020-10-29 12:48 UTC, opbld31 commented
Docs Build status updates of commit _[f6c9926](https://github.com/PeterNjorogeMS/microsoft-graph-docs/commits/f6c9926e461d65438353d436a575cfd752c18120)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) | [Details](#user-content-1d7938a4-a1d202e6)
[concepts/images/social-intel-concept-overview-data-update2020-1.png](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/images/social-intel-concept-overview-data-update2020-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) |
[concepts/people-example.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/people-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/people-example?branch=pr-en-us-10267) |

<a id="1d7938a4-a1d202e6"></a>
### [concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md)
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/person?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/insights-list-trending?view=graph-rest-1.0`````
 - **Line 80, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0`````
 - **Line 80, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0`````
 - **Line 109, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/social-overview?view=graph-rest-beta#help-users-balance-work-and-life`````
 - **Line 110, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profile?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010291246595689-10267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Rx9NjnVNW%2FGM2F2J7eRCeJg7WNJXl82KkJSEoNaGFbE%3D&st=2020-10-29T12%3A43%3A23Z&se=2020-11-29T12%3A48%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-29 23:19 UTC, angelgolfer-ms commented on concepts/people-example.md
> +The following request gets the people most relevant to another person in the signed-in user's organization as described in <a href="#working-with-feature-implementation">Working With </a>feature. Thi
Huh, I just noticed, the updates in the commit I referred to in my last comment are not currently displayed!
Commit: https://github.com/microsoftgraph/microsoft-graph-docs/pull/10267/commits/13fc1c80fdf313a5945c07fe5651bf6eff1b18a1

Since it's just editorial in nature, I am going ahead to repeat the updates in this PR.

2020-10-30 02:09 UTC, opbld34 commented
Docs Build status updates of commit _[9a7efdc](https://github.com/PeterNjorogeMS/microsoft-graph-docs/commits/9a7efdcaa72fd786f7599d86ecf29f51a62ad212)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) | [Details](#user-content-1d7938a4-de80f138)
[concepts/images/social-intel-concept-overview-data-update2020-1.png](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/images/social-intel-concept-overview-data-update2020-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) |
[concepts/people-example.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/people-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/people-example?branch=pr-en-us-10267) |

<a id="1d7938a4-de80f138"></a>
### [concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md)
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/person?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/insights-list-trending?view=graph-rest-1.0`````
 - **Line 80, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0`````
 - **Line 80, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0`````
 - **Line 109, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/social-overview?view=graph-rest-beta#help-users-balance-work-and-life`````
 - **Line 110, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profile?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010300208192250-10267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Tfvks2zP1Azv0y7PNyVSHy1MtnWqNXSZFc1UvZcb%2BCI%3D&st=2020-10-30T02%3A04%3A41Z&se=2020-11-30T02%3A09%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-30 02:23 UTC, opbld32 commented
Docs Build status updates of commit _[9bac9fa](https://github.com/PeterNjorogeMS/microsoft-graph-docs/commits/9bac9fa8e315499a8557dca188eaf627e6c271bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) | [Details](#user-content-1d7938a4-2de2ba0d)
[concepts/images/social-intel-concept-overview-data-update2020-1.png](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/images/social-intel-concept-overview-data-update2020-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) |
[concepts/people-example.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/people-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/people-example?branch=pr-en-us-10267) |

<a id="1d7938a4-2de2ba0d"></a>
### [concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md)
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/person?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/insights-list-trending?view=graph-rest-1.0`````
 - **Line 80, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0`````
 - **Line 80, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0`````
 - **Line 109, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/social-overview?view=graph-rest-beta#help-users-balance-work-and-life`````
 - **Line 110, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profile?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010300221588016-10267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JP8iokFPOd82G3KPu%2FVS2NA5ub2QGLi8%2BRxOHNTocXQ%3D&st=2020-10-30T02%3A18%3A28Z&se=2020-11-30T02%3A23%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-30 02:24 UTC, opbld33 commented
Docs Build status updates of commit _[f7e2192](https://github.com/PeterNjorogeMS/microsoft-graph-docs/commits/f7e21928b41193923a70497a0afa9bdb0be0e1e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) | [Details](#user-content-1d7938a4-e16de22f)
[concepts/images/social-intel-concept-overview-data-update2020-1.png](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/images/social-intel-concept-overview-data-update2020-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-10267) |
[concepts/people-example.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/people-example.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/people-example?branch=pr-en-us-10267) |

<a id="1d7938a4-e16de22f"></a>
### [concepts/social-intel-concept-overview.md](https://github.com/PeterNjorogeMS/microsoft-graph-docs/blob/2020-10-08-PeterNjorogeMS/concepts/social-intel-concept-overview.md)
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/person?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-trending?view=graph-rest-1.0`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/insights-list-trending?view=graph-rest-1.0`````
 - **Line 80, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-used?view=graph-rest-1.0`````
 - **Line 80, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/insights-shared?view=graph-rest-1.0`````
 - **Line 109, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/social-overview?view=graph-rest-beta#help-users-balance-work-and-life`````
 - **Line 110, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profile?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010300222100655-10267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w%2F7vXLaewXvFBuB8QkzM4tAI%2FMeR18dmrUyWUyWITC4%3D&st=2020-10-30T02%3A19%3A54Z&se=2020-11-30T02%3A24%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-30 02:30 UTC, merged

2020-10-30 02:39 UTC, angelgolfer-ms commented
> @angelgolfer-ms I have added the changes as requested.

Hi @PeterNjorogeMS , thanks for the updates. I also had to repeat my earlier commit, somehow the changes were no longer on this branch when I looked again today.
Since this PR is to update docs to reflect current behavior of the API, I reviewed one more time and went ahead to merge the PR to master. The content should be refreshed within the next day on the live site.

Since this is the first time I had worked with you, just an FYI, if the docs are to reflect API behavior that is to be released, then the author (you) coordinates the publishing. If such cases, please refer to this topic for the publishing workflow: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55055/Content-workflow

Thanks again for the doc updates!