Rajeshwari 1149658gaprivatechannelapi
microsoftgraph/microsoft-graph-docs pull request #10261
Opened 2020-10-12 07:48 UTC by Rajeshwari-v

Added membership in properties section and relationship section in channel.md file. Please review.

2020-10-12 07:49 UTC, opbld32 commented
Docs Build status updates of commit _[1c174e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c174e434a282209864ef79e3b9a9a0f1eed01c6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-23ef15d6)

<a id="2d408648-23ef15d6"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 38, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010120748366203-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9X5LnXGISNrXsft4WTylNsf77KqKeVDzOMGfII0mMek%3D&st=2020-10-12T07%3A44%3A55Z&se=2020-11-12T07%3A49%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-14 07:29 UTC, opbld34 commented
Docs Build status updates of commit _[ceee2c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ceee2c7b9513f707c4cf792c073b2e5372619870)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-856bf804)

<a id="2d408648-856bf804"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 26, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list.md'.`````
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add.md'.`````
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete.md'.`````
 - **Line 43, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010140727314043-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UrUpQQ7B%2BaHqkkrjOVVBldnNj8jJ37AtLkTUuQecuio%3D&st=2020-10-14T07%3A23%3A59Z&se=2020-11-14T07%3A28%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-14 08:22 UTC, opbld30 commented
Docs Build status updates of commit _[14974fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14974fd8676b745b5a0439309f80127cb9028950)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-afeb3685)

<a id="afeb3685"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010140822099051-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vc7FlODzzZrhC4n4z7WGt2DBSVTKeecZxrqiwmRHo5Q%3D&st=2020-10-14T08%3A17%3A35Z&se=2020-11-14T08%3A22%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-14 12:12 UTC, opbld34 commented
Docs Build status updates of commit _[5685e5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5685e5f226669ecb73c95c53cb92cb83713e6420)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9a9e0495)

<a id="9a9e0495"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010141211583818-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vjpBHwv%2BGoo0%2F%2BzTpdjPqGHN08rSZqKAvoEC4uZ1KOg%3D&st=2020-10-14T12%3A07%3A30Z&se=2020-11-14T12%3A12%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-14 12:15 UTC, opbld30 commented
Docs Build status updates of commit _[8606718](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8606718350d0ca2540bf5e0b27a8d963307d35ad)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cdecce5a)

<a id="cdecce5a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010141215123457-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yGu4RzMKOdmzYQHb1afxCoZd%2Ba7uyQ6KFt8u%2BCDB7pI%3D&st=2020-10-14T12%3A10%3A37Z&se=2020-11-14T12%3A15%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-14 12:23 UTC, opbld31 commented
Docs Build status updates of commit _[4f42ee5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f42ee5659d07634c623f13f32513c4bb79b0d25)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-ca7b04d2)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-ca7b04d2)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-ca7b04d2)

<a id="2d408648-ca7b04d2"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 26, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list.md'.`````
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add.md'.`````
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete.md'.`````
 - **Line 43, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````

<a id="77cfd98e-ca7b04d2"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4861, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-create.md'.`````
 - **Line 4865, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update.md'.`````
 - **Line 4869, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-list.md'.`````
 - **Line 4871, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-get.md'.`````
 - **Line 4873, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-add.md'.`````
 - **Line 4875, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-update.md'.`````
 - **Line 4877, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-delete.md'.`````

<a id="de0bbbbb-ca7b04d2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 51**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-list'.`````
 - **Line 20, Column 89**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-post'.`````
 - **Line 20, Column 129**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-get'.`````
 - **Line 20, Column 164**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-patch'.`````
 - **Line 20, Column 204**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-delete'.`````
 - **Line 20, Column 245**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list'.`````
 - **Line 20, Column 301**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get'.`````
 - **Line 20, Column 354**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add'.`````
 - **Line 20, Column 407**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update'.`````
 - **Line 20, Column 466**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete'.`````
 - **Line 20, Column 537**: **[Warning-file-not-found]** `````Invalid file link: '../resources/channel'.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you m [...]

2020-10-15 05:17 UTC, opbld33 commented
Docs Build status updates of commit _[ac182e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ac182e13a117657cdb59cd261bd88b7b09e34a80)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-9dc5df66)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-9dc5df66)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-9dc5df66)

<a id="2d408648-9dc5df66"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 26, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list.md'.`````
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add.md'.`````
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete.md'.`````
 - **Line 43, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````

<a id="77cfd98e-9dc5df66"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4861, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-create.md'.`````
 - **Line 4865, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update.md'.`````
 - **Line 4869, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-list.md'.`````
 - **Line 4871, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-get.md'.`````
 - **Line 4873, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-add.md'.`````
 - **Line 4875, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-update.md'.`````
 - **Line 4877, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-delete.md'.`````

<a id="de0bbbbb-9dc5df66"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '| Change type | Version | Description |
|:---|:---|:---|
|Addition|v1.0|Added the members in methods table List channels, Create channel,  Get channel, Update channel, Delete channel, List channel members, Get channel member, Add channel member, Update channel member, Delete channel member, and updated channel resource type.|') are not allowed. You can only have one top-level heading.
`````
 - **Line 23, Column 51**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-list'.`````
 - **Line 23, Column 89**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-post'.`````
 - **Line 23, Column 129**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-get'.`````
 - **Line 23, Column 164**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-patch'.`````
 - **Line 23, Column 204**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-delete'.`````
 - **Line 23, Column 245**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list'.`````
 - **Line 23, Column 301**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get'.`````
 - **Line 23, Column 354**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add'.`````
 - **Line 23, Column 407**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update'.`````
 - **Line 23, Column 466**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete'.`````
 - **Line 23, Column 537**: **[Warning-file-not-found]** `````Invalid file link: '../resources/channel'.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view- [...]

2020-10-15 05:33 UTC, opbld34 commented
Docs Build status updates of commit _[b3f3e60](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3f3e60b4ef7bd71f0784c3a2f90025d93829cfb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-5085c0ac)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-5085c0ac)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-5085c0ac)

<a id="2d408648-5085c0ac"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 26, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list.md'.`````
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add.md'.`````
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete.md'.`````
 - **Line 43, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````

<a id="77cfd98e-5085c0ac"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4863, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-create.md'.`````
 - **Line 4867, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update.md'.`````
 - **Line 4871, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-list.md'.`````
 - **Line 4873, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-get.md'.`````
 - **Line 4875, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-add.md'.`````
 - **Line 4877, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-update.md'.`````
 - **Line 4879, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-delete.md'.`````

<a id="de0bbbbb-5085c0ac"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '| Change type | Version | Description |
|:---|:---|:---|
|Addition|v1.0|Added the members in methods table List channels, Create channel,  Get channel, Update channel, Delete channel, List channel members, Get channel member, Add channel member, Update channel member, Delete channel member, and updated channel resource type.|') are not allowed. You can only have one top-level heading.
`````
 - **Line 23, Column 51**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-list'.`````
 - **Line 23, Column 89**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-post'.`````
 - **Line 23, Column 129**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-get'.`````
 - **Line 23, Column 164**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-patch'.`````
 - **Line 23, Column 204**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-delete'.`````
 - **Line 23, Column 245**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list'.`````
 - **Line 23, Column 301**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get'.`````
 - **Line 23, Column 354**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add'.`````
 - **Line 23, Column 407**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update'.`````
 - **Line 23, Column 466**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete'.`````
 - **Line 23, Column 537**: **[Warning-file-not-found]** `````Invalid file link: '../resources/channel'.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view- [...]

2020-10-15 05:40 UTC, opbld32 commented
Docs Build status updates of commit _[327f815](https://github.com/microsoftgraph/microsoft-graph-docs/commits/327f815a791f6550d2c5348f519e671919a75cc1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-3d56bf98)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-3d56bf98)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-3d56bf98)

<a id="2d408648-3d56bf98"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 26, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list.md'.`````
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add.md'.`````
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete.md'.`````
 - **Line 43, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````

<a id="77cfd98e-3d56bf98"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4871, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-list.md'.`````
 - **Line 4873, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-get.md'.`````
 - **Line 4875, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-add.md'.`````
 - **Line 4877, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-update.md'.`````
 - **Line 4879, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-delete.md'.`````

<a id="de0bbbbb-3d56bf98"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '| Change type | Version | Description |
|:---|:---|:---|
|Addition|v1.0|Added the members in methods table List channels, Create channel,  Get channel, Update channel, Delete channel, List channel members, Get channel member, Add channel member, Update channel member, Delete channel member, and updated channel resource type.|') are not allowed. You can only have one top-level heading.
`````
 - **Line 23, Column 51**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-list'.`````
 - **Line 23, Column 89**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-post'.`````
 - **Line 23, Column 129**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-get'.`````
 - **Line 23, Column 164**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-patch'.`````
 - **Line 23, Column 204**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-delete'.`````
 - **Line 23, Column 245**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list'.`````
 - **Line 23, Column 301**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get'.`````
 - **Line 23, Column 354**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add'.`````
 - **Line 23, Column 407**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update'.`````
 - **Line 23, Column 466**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete'.`````
 - **Line 23, Column 537**: **[Warning-file-not-found]** `````Invalid file link: '../resources/channel'.`````
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, [...]

2020-10-15 05:52 UTC, opbld34 commented
Docs Build status updates of commit _[98ee71d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/98ee71d861cb7da6fbb2c1e41e430e30607bfe0c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-1df5ce54)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-1df5ce54)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-1df5ce54)

<a id="2d408648-1df5ce54"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 26, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list.md'.`````
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add.md'.`````
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete.md'.`````
 - **Line 43, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````

<a id="77cfd98e-1df5ce54"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4871, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-list.md'.`````
 - **Line 4873, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-get.md'.`````
 - **Line 4875, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-add.md'.`````
 - **Line 4877, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-update.md'.`````
 - **Line 4879, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-delete.md'.`````

<a id="de0bbbbb-1df5ce54"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 80, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp? [...]

2020-10-16 06:16 UTC, opbld32 commented
Docs Build status updates of commit _[d00b0c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d00b0c61be45e06f5db0698e8c5801a76973ce79)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-77aef4c4)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-77aef4c4)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-77aef4c4)

<a id="2d408648-77aef4c4"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 26, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list.md'.`````
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add.md'.`````
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete.md'.`````
 - **Line 43, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````

<a id="77cfd98e-77aef4c4"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4871, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-list.md'.`````
 - **Line 4873, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-get.md'.`````
 - **Line 4875, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-add.md'.`````
 - **Line 4877, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-update.md'.`````
 - **Line 4879, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-delete.md'.`````

<a id="de0bbbbb-77aef4c4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 80, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp? [...]

2020-10-16 06:37 UTC, opbld31 commented
Docs Build status updates of commit _[f424e2a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f424e2af190c03ab3657505c066da50a5736c8bf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-3cd2c212)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-3cd2c212)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-3cd2c212)

<a id="2d408648-3cd2c212"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 26, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list.md'.`````
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add.md'.`````
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete.md'.`````
 - **Line 43, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````

<a id="77cfd98e-3cd2c212"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4914, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-list.md'.`````
 - **Line 4916, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-get.md'.`````
 - **Line 4918, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-add.md'.`````
 - **Line 4920, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-update.md'.`````
 - **Line 4922, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-delete.md'.`````

<a id="de0bbbbb-3cd2c212"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 80, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp? [...]

2020-10-16 06:40 UTC, opbld33 commented
Docs Build status updates of commit _[7796905](https://github.com/microsoftgraph/microsoft-graph-docs/commits/77969056b3a59f7e7ea63a7d543fb0646aefd426)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-d559e4b6)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-d559e4b6)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-d559e4b6)

<a id="2d408648-d559e4b6"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 26, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list.md'.`````
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-add.md'.`````
 - **Line 29, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-update.md'.`````
 - **Line 30, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-delete.md'.`````
 - **Line 43, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````

<a id="77cfd98e-d559e4b6"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4914, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-list.md'.`````
 - **Line 4916, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-get.md'.`````
 - **Line 4918, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-add.md'.`````
 - **Line 4920, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-update.md'.`````
 - **Line 4922, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/conversationmember-delete.md'.`````

<a id="de0bbbbb-d559e4b6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 33, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 35, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 46, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 52, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 64, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 65, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 80, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp? [...]

2020-10-21 22:16 UTC, opbld32 commented
Docs Build status updates of commit _[3da2243](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3da2243e427b55bc0af4196973565c75b521d8a7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-4999368c)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-4999368c)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="2d408648-4999368c"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 4, Column 9**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 43, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````
 - **Line 1, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="de0bbbbb-4999368c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateaccountsummary?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategorysummary?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateconfiguration?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatestatesummary?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macosassociateddomainsitem?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-androidforwork-androiddeviceownerenrollmenttokentype?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributevaluetype?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatebehavior?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategory?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &pr [...]

2020-10-21 22:25 UTC, opbld34 commented
Docs Build status updates of commit _[63920f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63920f5814514065a81b94d69aee51570669a11c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-b0769286)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-b0769286)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="2d408648-b0769286"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 4, Column 9**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 43, Column 17**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#channelmembershiptype-values' in 'v1.0/resources/enums.md'.`````
 - **Line 1, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="de0bbbbb-b0769286"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateaccountsummary?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategorysummary?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateconfiguration?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatestatesummary?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macosassociateddomainsitem?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-androidforwork-androiddeviceownerenrollmenttokentype?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributevaluetype?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatebehavior?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategory?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &pr [...]

2020-10-21 22:38 UTC, opbld33 commented
Docs Build status updates of commit _[15f9d61](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15f9d612a07b2e6287b8bef493483db228d2dd1d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-9dcf9455)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-9dcf9455)
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="2d408648-9dcf9455"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 4, Column 9**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="de0bbbbb-9dcf9455"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateaccountsummary?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategorysummary?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateconfiguration?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatestatesummary?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macosassociateddomainsitem?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-androidforwork-androiddeviceownerenrollmenttokentype?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributevaluetype?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatebehavior?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-d [...]

2020-10-21 22:40 UTC, opbld31 commented
Docs Build status updates of commit _[9b83116](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b831169e6ec902c6d53c3184fb2d35d44532d9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-dda5fe1b)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-dda5fe1b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateaccountsummary?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategorysummary?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateconfiguration?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatestatesummary?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macosassociateddomainsitem?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-androidforwork-androiddeviceownerenrollmenttokentype?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributevaluetype?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatebehavior?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategory?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatescheduletype?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatestate?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/intune-devices [...]

2020-10-21 22:42 UTC, opbld31 commented
Docs Build status updates of commit _[4ced752](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ced752871dcd13c10f5c00142dc804d545f3035)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-d5016aa0)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-d5016aa0"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateaccountsummary?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategorysummary?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateconfiguration?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatestatesummary?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macosassociateddomainsitem?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-androidforwork-androiddeviceownerenrollmenttokentype?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributevaluetype?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatebehavior?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategory?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatescheduletype?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatestate?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/intune-devices [...]

2020-10-21 23:26 UTC, laujan submitted a review, later dismissed

2020-10-22 03:06 UTC, Lauragra commented on concepts/changelog.md
> -|Addition|v1.0|Added [JSON batching](json-batching.md) support. Internal request limit set to 20.|
Why are you deleting these old changelog entries? Please restore them. Also, what if anything did you intend to add to the changelog file?

2020-10-22 03:09 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +        - name: List channel members
Why are we using List channel members for the TOC entry when it links to the List conversationMember topic? The conversationMember operations are exposed under Conversation member in the TOC. Can you please clarify your intent?

2020-10-22 03:16 UTC, Lauragra commented on api-reference/v1.0/resources/channel.md
> +|[List channel members](../api/conversationmember-list.md)| [conversationMember](conversationmember.md) collection| List the members of a channel. |
It's a little confusing when we name the operation "List channel members" and we link to a topic called "List conversationMember". Suggest maybe using generic names for the operation, per the comment below about the TOC entries. The summary statement mentions that the operation will list conversation members in a chat or channel, but the HTTP request section only shows chats. Is that accurate?

2020-10-22 03:17 UTC, Lauragra commented on api-reference/v1.0/resources/channel.md
> +|membershipType|[channelMembershipType](enums.md#channelmembershiptype-values)|The type of the channel. Can be set during creation and cannot be changed. Default: standard.|
Please remove the link to the enums topic. We don't link to that. Just list the type, and in the JSON representation, list the type as string.

2020-10-22 03:17 UTC, Lauragra commented on api-reference/v1.0/resources/channel.md
> +  "membershipType": "channelMembershipType",
List the type as string for enums.

2020-10-22 03:19 UTC, Lauragra requested changes
Please respond to content review comments.

2020-10-22 05:10 UTC, opbld30 commented
Docs Build status updates of commit _[3582f1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3582f1bd12cd64b276fa44e01c41f3aa97f513d1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fdaa807a)

<a id="fdaa807a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010220510205611-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vxel6M11EqRtJotgfLq3BHufHTsrhTF7%2BS4C0ExQz2o%3D&st=2020-10-22T05%3A05%3A46Z&se=2020-11-22T05%3A10%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-22 07:39 UTC, AkJo commented on api-reference/v1.0/toc.yml
> +        - name: List channel members
@Lauragra converastionMember is the base type that is used to represent members of a channel (and other things in other scenarios). 

I am unable to see the final result of this PR change, so I will explain what should happen:

The "List channel members' entry in the TOC should take the user to a dedicated page for "List channel members" that should look something like the page below. 



![image](https://user-images.githubusercontent.com/25969716/96840015-c3a62a80-13fe-11eb-9878-18e630ae7703.png)

The delete/get/update channel members should be along equivalent lines.

I do not have a strong preference for calling it "List channel members" or "List members" as long as either of the entries appear under the Channel node in the TOC.

2020-10-22 07:42 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +|[List channel members](../api/conversationmember-list.md)| [conversationMember](conversationmember.md) collection| List the members of a channel. |
@Lauragra , please refer to my other comment.

2020-10-22 07:43 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +|membershipType|String|The type of the channel. Can be set during creation and cannot be changed. Values: standard, private, unknownFutureValue. Default: standard.|
This is not a string.  This is an enum. Please make sure that there is a hyperlink to this enum.

<EnumType Name="channelMembershipType">
<Member Name="standard" Value="0"/>
<Member Name="private" Value="1"/>
<Member Name="unknownFutureValue" Value="2"/>
</EnumType>

2020-10-22 07:44 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +  "membershipType": "string",
Not a string

2020-10-22 07:45 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +|membershipType|String|The type of the channel. Can be set during creation and cannot be changed. Values: standard, private, unknownFutureValue. Default: standard.|
Please use whatever notation is used for enums.

2020-10-22 07:48 UTC, AkJo commented on api-reference/v1.0/resources/enums.md
> +| unknownFutureValue | 2     |
Please add a third column for description. 

standard : Channel inherits the list of members of the parent team.
private: Channel can have members that are a subset of all the members on the parent team.

2020-10-22 08:20 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +  "membershipType": "string",
Please use whatever notation is used for enums.

2020-10-22 10:15 UTC, opbld32 commented
Docs Build status updates of commit _[e7c12e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7c12e6eb4fa7f82f8f1570c1b4308917f55d6c1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e65670d8)

<a id="e65670d8"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010221014425891-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=o9VC0bd3NkJunDDkEe2rhkR2vlHcJ7nny836%2BpHfntQ%3D&st=2020-10-22T10%3A10%3A09Z&se=2020-11-22T10%3A15%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-22 10:22 UTC, opbld31 commented
Docs Build status updates of commit _[3f8f2c3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f8f2c3c784ed55ace8d646fed7da4236f71ff4d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-dcb59016)

<a id="dcb59016"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010221021517659-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=K%2FTUnrCy57U%2F%2BW4fyNtxAKhziF0MRJAyeooADXpe9hQ%3D&st=2020-10-22T10%3A17%3A15Z&se=2020-11-22T10%3A22%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-22 21:06 UTC, Lauragra commented on api-reference/v1.0/resources/channel.md
> +  "membershipType": "string",
@AkJo , @Rajeshwari-v , please see our guidance for documenting enums. In the JSON representation, we show them as type string. We also don't link to the enums.md file. There are several options for how to document enums. https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55059/Enumerations

2020-10-22 21:10 UTC, Lauragra commented on api-reference/v1.0/resources/enums.md
> +| unknownFutureValue | 2     |
Our guidance is not to list values and descriptions in the enums.md file. Please list the values in the resource topic. If further description is warranted, add an H3 to the Properties section.

2020-10-22 21:13 UTC, opbld31 commented
Docs Build status updates of commit _[5e15fe8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e15fe868ba92caab8a0bca01cd0968d3c87eb8b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-31710190)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-31710190"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjobstatus?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjobstatus?view=graph-rest-beta`````
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph [...]

2020-10-22 21:16 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +        - name: List channel members
@AkJo , are you able to view the preview site here? https://review.docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-10261 If so, let me know if this appears to match the experience you are expecting?

2020-10-22 21:19 UTC, Lauragra commented on api-reference/v1.0/resources/channel.md
> +|[List channel members](../api/conversationmember-list.md)| [conversationMember](conversationmember.md) collection| List the members of a channel. |
@AkJo , can you let us know if the topic is missing HTTP syntax for channel?

2020-10-22 21:20 UTC, Lauragra commented on api-reference/v1.0/resources/channel.md
> +|membershipType|String|The type of the channel. Can be set during creation and cannot be changed. Values: standard, private, unknownFutureValue. Default: standard.|
Include the enum name in the type column but without a link. In the JSON representation, list the type as string.

2020-10-22 21:23 UTC, Lauragra commented on api-reference/v1.0/resources/channel.md
> +|membershipType|[channelMembershipType](../resources/enums.md#channelmembershiptype-values)|The type of the channel. Can be set during creation and cannot be changed. Default: standard.
Please remove the link to the enums file.

2020-10-23 05:55 UTC, AkJo commented on api-reference/v1.0/toc.yml
> +        - name: List channel members
Thanks for sharing the link. 

Yep, the contents of the page are not right. 

That page should talk only about channel. We need a dedicated page devoted to list members in a channel, adding members to a channel and so on.

2020-10-23 06:09 UTC, AkJo commented on api-reference/v1.0/toc.yml
> +        - name: List channel members
I am expecting to see 4 additional files in this PR:

channel-conversationmember-add.md  
channel-conversationmember-remove.md
channel-conversationmember-update.md
channel-conversationmember-get.md
channel-conversationmember-list.md

(or a different naming convention like channel-add-conversationmember, and so on - whichever is convention that is being used)

PS: This is along the lines of teamsAppInstallation for a user or a team. We need a separate page for the separate APIs.
![image](https://user-images.githubusercontent.com/25969716/96962128-088f9700-14bb-11eb-85f5-e05dfb4c4be7.png)

2020-10-23 06:16 UTC, AkJo commented on api-reference/v1.0/toc.yml
> +        - name: List channel members
The new entries in the TOC should map to the new files I enumerated above.

2020-10-23 08:06 UTC, opbld33 commented
Docs Build status updates of commit _[50a7d57](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50a7d5717eb98b67591274fb306b2613c7fe3321)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-b4f33c06)
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-b4f33c06"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjobstatus?view=graph-rest-beta`````
 - **Line 63, Column [...]

2020-10-23 08:59 UTC, opbld33 commented
Docs Build status updates of commit _[26124f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26124f27a4907f5cda0bd91d3d0012858a29393e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-9883c7f4)
[api-reference/v1.0/api/channel-conversationmember-list](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-list) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-9883c7f4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta [...]

2020-10-23 09:02 UTC, opbld32 commented
Docs Build status updates of commit _[235befe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/235befe2c6cc036709d28f863aba45b73bf1e883)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-6c64c308)
[api-reference/v1.0/api/channel-conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-6c64c308"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 61, Column 1**: **[Suggestion- [...]

2020-10-23 09:11 UTC, opbld33 commented
Docs Build status updates of commit _[d9f55d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9f55d99e30d383c7bb1030f63db724c6b184ac9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-45359629-8fec9fa7)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-8fec9fa7)
[api-reference/v1.0/api/channel-conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="45359629-8fec9fa7"></a>
### [api-reference/v1.0/api/channel-conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-add.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Add conversationMember to a channel.' is duplicated in 'v1.0/api/channel-conversationmember-add.md(3,14)', 'v1.0/api/conversationmember-add.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-8fec9fa7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve- [...]

2020-10-23 09:23 UTC, opbld30 commented
Docs Build status updates of commit _[1ce8411](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ce84118ef67ab54ec86293c2e5e4a4e1d6e3d7f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-45359629-f7f21281)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-f7f21281)
[api-reference/v1.0/api/channel-conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="45359629-f7f21281"></a>
### [api-reference/v1.0/api/channel-conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-add.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Add conversationMember to a channel.' is duplicated in 'v1.0/api/channel-conversationmember-add.md(3,14)', 'v1.0/api/conversationmember-add.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-f7f21281"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to th [...]

2020-10-23 09:32 UTC, opbld34 commented
Docs Build status updates of commit _[de37ec4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de37ec4dba908f9bc867121d60e1226bfd14b69f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-45359629-6cbede05)
[api-reference/v1.0/api/channel-conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-960f2b54-6cbede05)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-6cbede05)
[api-reference/v1.0/api/channel-conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="45359629-6cbede05"></a>
### [api-reference/v1.0/api/channel-conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-add.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Add conversationMember to a channel.' is duplicated in 'v1.0/api/channel-conversationmember-add.md(3,14)', 'v1.0/api/conversationmember-add.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="960f2b54-6cbede05"></a>
### [api-reference/v1.0/api/channel-conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete conversationMember from a channel.' is duplicated in 'v1.0/api/channel-conversationmember-delete.md(3,14)', 'v1.0/api/conversationmember-delete.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete conversationMember' is duplicated with other articles: 'v1.0/api/channel-conversationmember-delete.md(10,1), v1.0/api/conversationmember-delete.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-6cbede05"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/pr [...]

2020-10-23 10:18 UTC, AkJo commented on api-reference/v1.0/toc.yml
> +        - name: List channel members
@Rajeshwari-v , Sorry, I know this is different from what I just told you, but I think that the more appropriate file name would be
channel-members-add.md
channel-members-remove.md
channel-members-update.md
channel-members-get.md
channel-members-list.md

"Members', here, is the 'name' of the property  and not the 'type' of the property. 

I realized this would be the more scalable approach because in the future you can easily have two different properties of the same type. For example: 
channels could have 
<NavigationProperty Name="members" Type="Collection(graph.conversationMember)" ContainsTarget="true"/>
<NavigationProperty Name="bannedMembers" Type="Collection(graph.conversationMember)" ContainsTarget="true"/>

In that case, if your file was named after the 'type' and not the 'property' name, you would have a filename conflict when you tried to create a new file dedicated to bannedMembers. To not have a conflict, you would need a naming scheme like below:

channel-members-add.md
channel-bannedmembers-add.md 
and so on.

2020-10-23 10:19 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +|[List channel members](../api/conversationmember-list.md)| [conversationMember](conversationmember.md) collection| List the members of a channel. |
@Lauragra , I am afraid that it is not clear what is being asked for me here. What do you mean by 'HTTP syntax'?

2020-10-23 10:35 UTC, opbld31 commented
Docs Build status updates of commit _[9e64723](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e6472341b5b48906c8c6d6144d477f3673550ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-45359629-256cea41)
[api-reference/v1.0/api/channel-conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-960f2b54-256cea41)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-256cea41)
[api-reference/v1.0/api/channel-conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="45359629-256cea41"></a>
### [api-reference/v1.0/api/channel-conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-add.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Add conversationMember to a channel.' is duplicated in 'v1.0/api/channel-conversationmember-add.md(3,14)', 'v1.0/api/conversationmember-add.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="960f2b54-256cea41"></a>
### [api-reference/v1.0/api/channel-conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete conversationMember from a channel.' is duplicated in 'v1.0/api/channel-conversationmember-delete.md(3,14)', 'v1.0/api/conversationmember-delete.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete conversationMember' is duplicated with other articles: 'v1.0/api/channel-conversationmember-delete.md(10,1), v1.0/api/conversationmember-delete.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-256cea41"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/pr [...]

2020-10-23 10:37 UTC, opbld34 commented
Docs Build status updates of commit _[3c903bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c903bccd6c8184ce52d125eb9bab88eb2dc7a75)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-45359629-dd00999a)
[api-reference/v1.0/api/channel-conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-960f2b54-dd00999a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-dd00999a)
[api-reference/v1.0/api/channel-conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="45359629-dd00999a"></a>
### [api-reference/v1.0/api/channel-conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-add.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Add conversationMember to a channel.' is duplicated in 'v1.0/api/channel-conversationmember-add.md(3,14)', 'v1.0/api/conversationmember-add.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="960f2b54-dd00999a"></a>
### [api-reference/v1.0/api/channel-conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete conversationMember from a channel.' is duplicated in 'v1.0/api/channel-conversationmember-delete.md(3,14)', 'v1.0/api/conversationmember-delete.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete conversationMember' is duplicated with other articles: 'v1.0/api/channel-conversationmember-delete.md(10,1), v1.0/api/conversationmember-delete.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-dd00999a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/pr [...]

2020-10-23 11:16 UTC, opbld32 commented
Docs Build status updates of commit _[291e83d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/291e83da9fc3e26f0641d442b7a500386675d4b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-7d8b524e)
[api-reference/v1.0/api/channel-conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-45359629-7d8b524e)
[api-reference/v1.0/api/channel-conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-960f2b54-7d8b524e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-7d8b524e)
[api-reference/v1.0/api/channel-conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="2d408648-7d8b524e"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 32, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-conversationmember-list.md'.`````

<a id="45359629-7d8b524e"></a>
### [api-reference/v1.0/api/channel-conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-add.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Add conversationMember to a channel.' is duplicated in 'v1.0/api/channel-conversationmember-add.md(3,14)', 'v1.0/api/conversationmember-add.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="960f2b54-7d8b524e"></a>
### [api-reference/v1.0/api/channel-conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete conversationMember from a channel.' is duplicated in 'v1.0/api/channel-conversationmember-delete.md(3,14)', 'v1.0/api/conversationmember-delete.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete conversationMember' is duplicated with other articles: 'v1.0/api/channel-conversationmember-delete.md(10,1), v1.0/api/conversationmember-delete.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-7d8b524e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]* [...]

2020-10-23 11:23 UTC, opbld33 commented
Docs Build status updates of commit _[b823f18](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b823f18a090a3d60b26a587a72636eba0ae6ab37)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-3d6edbef)
[api-reference/v1.0/api/channel-conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-960f2b54-3d6edbef)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-3d6edbef)
[api-reference/v1.0/api/channel-conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="2d408648-3d6edbef"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 32, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-conversationmember-list.md'.`````
 - **Line 33, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-conversationmember-add.md'.`````

<a id="960f2b54-3d6edbef"></a>
### [api-reference/v1.0/api/channel-conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete conversationMember from a channel.' is duplicated in 'v1.0/api/channel-conversationmember-delete.md(3,14)', 'v1.0/api/conversationmember-delete.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete conversationMember' is duplicated with other articles: 'v1.0/api/channel-conversationmember-delete.md(10,1), v1.0/api/conversationmember-delete.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-3d6edbef"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view= [...]

2020-10-23 11:25 UTC, opbld32 commented
Docs Build status updates of commit _[1f5af3f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f5af3f4882cd53e49eade3deea65ab212db345a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-224000e2)
[api-reference/v1.0/api/channel-conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-960f2b54-224000e2)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-224000e2)
[api-reference/v1.0/api/channel-member-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-conversationmember-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="2d408648-224000e2"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 32, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-conversationmember-list.md'.`````
 - **Line 33, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-conversationmember-add.md'.`````
 - **Line 34, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-conversationmember-update.md'.`````

<a id="960f2b54-224000e2"></a>
### [api-reference/v1.0/api/channel-conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-conversationmember-delete.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Delete conversationMember from a channel.' is duplicated in 'v1.0/api/channel-conversationmember-delete.md(3,14)', 'v1.0/api/conversationmember-delete.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete conversationMember' is duplicated with other articles: 'v1.0/api/channel-conversationmember-delete.md(10,1), v1.0/api/conversationmember-delete.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-224000e2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-prese [...]

2020-10-23 11:30 UTC, opbld33 commented
Docs Build status updates of commit _[2c98dff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c98dff8bea1f9a563530610ffe2dd895dfd2a4d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-14080641)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-14080641)
[api-reference/v1.0/api/channel-member-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="2d408648-14080641"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 32, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-conversationmember-list.md'.`````
 - **Line 33, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-conversationmember-add.md'.`````
 - **Line 34, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-conversationmember-update.md'.`````
 - **Line 35, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-conversationmember-delete.md'.`````

<a id="de0bbbbb-14080641"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /gra [...]

2020-10-23 11:31 UTC, opbld32 commented
Docs Build status updates of commit _[50719cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50719cf41b2ec5a920c88094458652db08c4a127)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-e02eedb5)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-e02eedb5)
[api-reference/v1.0/api/channel-member-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="2d408648-e02eedb5"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 32, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-conversationmember-list.md'.`````
 - **Line 33, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-conversationmember-add.md'.`````
 - **Line 34, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-conversationmember-update.md'.`````
 - **Line 35, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-conversationmember-delete.md'.`````

<a id="de0bbbbb-e02eedb5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /gra [...]

2020-10-23 11:36 UTC, opbld34 commented
Docs Build status updates of commit _[fee0cb8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fee0cb875afba09ba1450be38bfd389bb3aca58d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-3f5567b3)
[api-reference/v1.0/api/channel-member-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-3f5567b3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did y [...]

2020-10-23 11:52 UTC, opbld34 commented
Docs Build status updates of commit _[5efa815](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5efa8154f309d71ab05f48c34a038f235f278c8e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-996fea30)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-996fea30)
[api-reference/v1.0/api/channel-member-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-member-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="2d408648-996fea30"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-member-list.md'.`````

<a id="de0bbbbb-996fea30"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-vi [...]

2020-10-23 11:53 UTC, opbld31 commented
Docs Build status updates of commit _[ffd580f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ffd580f5aad16534cf3dd9ec57ea6c9785bbc7cc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-d92cad00)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-d92cad00)
[api-reference/v1.0/api/channel-member-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-member-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-member-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="2d408648-d92cad00"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 27, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-member-list.md'.`````
 - **Line 28, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/channel-member-add.md'.`````

<a id="de0bbbbb-d92cad00"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL [...]

2020-10-23 11:55 UTC, opbld31 commented
Docs Build status updates of commit _[072ddf5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/072ddf53d333e650de0fa951451e3fcb75cb4a58)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-3e153e39)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-3e153e39"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set] [...]

2020-10-23 11:57 UTC, opbld31 commented
Docs Build status updates of commit _[a0be9e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0be9e9e76dcd557f314a3d10cf595bc9a14e70f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-2758be25)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-2758be25"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set] [...]

2020-10-23 12:11 UTC, opbld33 commented
Docs Build status updates of commit _[fa52a9e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa52a9e360a0194869553b79f0fdf6a5fbf56872)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-41b04c57)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-41b04c57"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 118, Column 27**: **[Warning-file-not-found]** `````Invalid file link: 'graph/api/channel-members-list'.`````
 - **Line 118, Column 88**: **[Warning-file-not-found]** `````Invalid file link: 'graph/api/channel-members-add'.`````
 - **Line 118, Column 147**: **[Warning-file-not-found]** `````Invalid file link: 'graph/api/channel-members-update'.`````
 - **Line 118, Column 225**: **[Warning-file-not-found]** `````Invalid file link: 'graph/api/channel-members-delete'.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Lin [...]

2020-10-23 12:14 UTC, opbld30 commented
Docs Build status updates of commit _[8786849](https://github.com/microsoftgraph/microsoft-graph-docs/commits/87868494a9e02a1fc74501a770b511de349e7d62)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-b155a64b)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-b155a64b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 118, Column 27**: **[Warning-file-not-found]** `````Invalid file link: 'graph/api/channel-members-list'.`````
 - **Line 118, Column 88**: **[Warning-file-not-found]** `````Invalid file link: 'graph/api/channel-members-add'.`````
 - **Line 118, Column 149**: **[Warning-file-not-found]** `````Invalid file link: 'graph/api/channel-members-update'.`````
 - **Line 118, Column 227**: **[Warning-file-not-found]** `````Invalid file link: 'graph/api/channel-members-delete'.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Lin [...]

2020-10-23 12:17 UTC, opbld31 commented
Docs Build status updates of commit _[e398dd1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e398dd1df03bc220b44e9b3dbf80226d48593bbb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-4cb245a6)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-4cb245a6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set] [...]

2020-10-24 02:26 UTC, Lauragra commented on api-reference/v1.0/resources/channel.md
> +|[List channel members](../api/conversationmember-list.md)| [conversationMember](conversationmember.md) collection| List the members of a channel. |
> @Lauragra , I am afraid that it is not clear what is being asked for me here. What do you mean by 'HTTP syntax'?

Sorry, I was referring to the HTTP request section in the topic.

2020-10-24 02:28 UTC, Lauragra commented
@Rajeshwari-v , @laujan , I set this PR back to Do not merge. Please set to Ready to merge after Anand has reviewed and approved the updated based on his feedback. Thanks.

2020-10-24 02:30 UTC, Lauragra commented on api-reference/v1.0/resources/channel.md
> +|membershipType|channelMembershipType|The type of the channel. Can be set during creation and cannot be changed. Default: standard.standard : Channel inherits the list of members of the parent team.
FYI, for properties of type enum, we put the enum name in the Type column but we don't link to enums.md. In the JSON representation, we list as type string.

2020-10-24 02:31 UTC, opbld33 commented
Docs Build status updates of commit _[049ffba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/049ffba678fdc79a156e3742f20e2372378b0a8c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-dada62c5)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-dada62c5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-24 02:33 UTC, opbld33 commented
Docs Build status updates of commit _[0c66d37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c66d37789ca0075b7e67cf30ce2033e0e452c98)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-9e4b3c21)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-9e4b3c21"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-24 02:48 UTC, AkJo commented on api-reference/v1.0/api/channel-members-add.md
> +|Delegated (work or school account)| ChannelMember.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All |
v1 version of these APIs will support only ChannelMember.ReadWrite.All.

Please remove Group.ReadWrite.All, Directory.ReadWrite.All

2020-10-24 02:49 UTC, AkJo commented on api-reference/v1.0/api/channel-members-add.md
> +|Application| ChannelMember.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All |
Group.ReadWrite.All, Directory.ReadWrite.All

2020-10-24 02:50 UTC, AkJo commented on api-reference/v1.0/api/channel-members-add.md
> +  "user@odata.bind": "https://graph.microsoft.com/v1.0/users/8b081ef6-4792-4def-b2c9-c363a1bf41d5"
Please replace with

"https://graph.microsoft.com/v1.0/users('8b081ef6-4792-4def-b2c9-c363a1bf41d5')"

2020-10-24 02:53 UTC, AkJo commented on api-reference/v1.0/api/channel-members-add.md
> +```
Please add one more sample. 

Here is a request to add a member with "owner" role to the  channel.

### Request

Here is an example of the request.

<!-- {
  "blockType": "request",
  "name": "create_member_with_owner_role"
} -->
```http
POST https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/members/
content-type: application/json
content-length: 26
{
  "@odata.type": "#microsoft.graph.aadUserConversationMember",
  "roles": ["owner"],
  "user@odata.bind": "https://graph.microsoft.com/v1.0/users/8b081ef6-4792-4def-b2c9-c363a1bf41d5"
   "https://graph.microsoft.com/v1.0/users('8b081ef6-4792-4def-b2c9-c363a1bf41d5')"

}
```

### Response

Here is an example of the response.

>**Note:** The response object shown here might be shortened for readability. All the properties will be returned from an actual call.
<!-- {
  "blockType": "response",
  "truncated": true,
  "name": "create_member",
  "@odata.type": "microsoft.graph.conversationMember"
} -->
```http
HTTP/1.1 201 Created
Content-type: application/json
Content-length: 468
{
  "@odata.context": "https://graph.microsoft.com/V1.0/$metadata#teams('ece6f0a1-7ca4-498b-be79-edf6c8fc4d82')/channels('19%3A56eb04e133944cf69e603c5dac2d292e%40thread.skype')/members/microsoft.graph.aadUserConversationMember/$entity",
  "@odata.type": "#microsoft.graph.aadUserConversationMember",
  "id": "8b081ef6-4792-4def-b2c9-c363a1bf41d5",
  "roles": ["owner"],
  "displayName": "John Doe",
  "userId": "8b081ef6-4792-4def-b2c9-c363a1bf41d5",
  "email": null
}
```

2020-10-24 02:53 UTC, AkJo commented on api-reference/v1.0/api/channel-members-add.md
> +Here is an example of the request.
Here is an example of the request to add a basic member to the channel.

2020-10-24 02:55 UTC, AkJo commented on api-reference/v1.0/api/channel-members-list.md
> +|Delegated (work or school account)|ChannelMember.Read.All, ChannelMember.ReadWrite, Group.Read.All, Group.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All|
Please remove all Group.* and Directory.* permissions.

2020-10-24 02:56 UTC, AkJo commented on api-reference/v1.0/api/channel-members-list.md
> +|Application|Member.Read.Group*, ChannelMember.Read.All, ChannelMember.ReadWrite.All, Group.Read.All, Group.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All |
Please remove all permissions except:
 ChannelMember.Read.All, ChannelMember.ReadWrite.All

2020-10-24 02:56 UTC, AkJo commented on api-reference/v1.0/api/channel-members-update.md
> +|Delegated (work or school account)|ChannelMember.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All. |
Please remove all Group/Directory permissions.

2020-10-24 02:56 UTC, AkJo commented on api-reference/v1.0/api/channel-members-update.md
> +|Application|ChannelMember.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All. |
Please remove all Group/Directory permissions.

2020-10-24 02:58 UTC, AkJo commented on api-reference/v1.0/api/channel-members-update.md
> +Here is an example of the request.
Here is an example of the request to apply the "owner" role to an existing member of a channel.

2020-10-24 02:59 UTC, AkJo commented on api-reference/v1.0/api/channel-members-delete.md
> +DELETE https://graph.microsoft.com/V1.0/channels/{id}/members/{id}
In all your examples, please ensure that camelcasing is being used:

"v1.0"

2020-10-24 02:59 UTC, AkJo commented on api-reference/v1.0/api/channel-members-list.md
> +title: "List member from a channel"
List members of a channel

2020-10-24 02:59 UTC, AkJo commented on api-reference/v1.0/api/channel-members-list.md
> +description: "List member from a channel."
List members of a channel

2020-10-24 02:59 UTC, AkJo commented on api-reference/v1.0/api/channel-members-list.md
> +# List member from a channel
List members of a channel

2020-10-24 03:03 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +|[List members in a channel](../api/channel-members-list.md) | [conversationMember](conversationmember.md) collection | Get the list of conversation members in a channel.|
Why are these not appearing at separate rows?

![image](https://user-images.githubusercontent.com/25969716/97066485-c2920c00-156a-11eb-89b1-569e46f987ea.png)

2020-10-24 03:04 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +|[Add a member to a channel](../api/channel-members-add.md) | [conversationMember](conversationmember.md) | Add conversation members to a channel a new channel. Only supported for `channelType` of `p
Add conversation members to a channel.

2020-10-24 03:04 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +|[Update the role of a member in a channel](../api/channel-members-update.md) | [conversationMember](conversationmember.md) | Update properties of the channel. Only supported for `channelType` of `pr
Update the properties of a member of the channel.

2020-10-24 03:05 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +|[List members in a channel](../api/channel-members-list.md) | [conversationMember](conversationmember.md) collection | Get the list of conversation members in a channel.|
Please remove the term 'conversation'

2020-10-24 03:05 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +|[Delete a member from a channel](../api/channel-members-delete.md) | None | Delete a conversation member from a channel. Only supported for `channelType` of `private`.|
Please remove the term 'conversation'

2020-10-24 03:06 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +|[Delete a member from a channel](../api/channel-members-delete.md) | None | Delete a conversation member from a channel. Only supported for `channelType` of `private`.|
Only supported for channel with `membershipType' of `private`.|

2020-10-24 03:06 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +|membershipType|channelMembershipType|The type of the channel. Can be set during creation and cannot be changed. Possible values are: `Default` - Channel inherits the list of members of the parent te
Possible values are: `Standard`

2020-10-24 03:12 UTC, AkJo commented on api-reference/v1.0/toc.yml
> -          href: api/channel-post-messages.md
Why are these being removed? Please add them back.

2020-10-24 03:17 UTC, AkJo commented on api-reference/v1.0/toc.yml
> +          href: api/channel-members-delete.md
@Lauragra , is the filenaming convention {verb}-{propertyName}.md or {propertyName}.{verb}.md.

Basically, should this be
channel-members-delete.md
or 
channel-delete-members.md

I see examples of both conventions in this file.

2020-10-27 05:18 UTC, opbld33 commented
Docs Build status updates of commit _[8b8f4f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b8f4f8ba11361742334ca944d766a226966de3d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-2705aaf8)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-2705aaf8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-27 05:45 UTC, opbld31 commented
Docs Build status updates of commit _[a001eea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a001eea272b41f8c034da09651d7a7a57b530469)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-d576700d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-d576700d)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="2d408648-d576700d"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 18, Column 1**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-d576700d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Col [...]

2020-10-27 06:08 UTC, Rajeshwari-v commented on api-reference/v1.0/api/channel-members-list.md
> +|Delegated (work or school account)|ChannelMember.Read.All, ChannelMember.ReadWrite, Group.Read.All, Group.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All|
Done

2020-10-27 06:35 UTC, opbld31 commented
Docs Build status updates of commit _[0f1d849](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f1d849a9ef198309f6e4a3cd8f8e072f7231dfe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-2d408648-f86db4c0)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-f86db4c0)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="2d408648-f86db4c0"></a>
### [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md)
 - **Line 18, Column 1**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-f86db4c0"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Col [...]

2020-10-27 06:43 UTC, opbld30 commented
Docs Build status updates of commit _[79c4db4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/79c4db4cd326864a0eb447d03a185288e2b42700)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-160cc9e1)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-160cc9e1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-27 06:53 UTC, opbld33 commented
Docs Build status updates of commit _[3721f3c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3721f3c0caacff2977a46655cb346e95bd04bb7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-ff049d54)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-ff049d54"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-27 07:21 UTC, opbld30 commented
Docs Build status updates of commit _[b1940cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b1940ccb3633f461c3a9c08886d119e3d5293682)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-6dcd23c3)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-6dcd23c3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-27 07:28 UTC, opbld34 commented
Docs Build status updates of commit _[c849b1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c849b1b5fe4fdaddc9a3f6bae7978d1e71f7d2ed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-f438b8f7)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-f438b8f7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-27 07:29 UTC, opbld31 commented
Docs Build status updates of commit _[f01b7fb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f01b7fbc81d3e0d10c5a3c0230d5e97138a1c16d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-1031d9f8)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-1031d9f8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-27 07:31 UTC, opbld31 commented
Docs Build status updates of commit _[9fa0fbf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9fa0fbf8fdac44802d5778e05727fe53082a5f33)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-f2dfe9e4)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-f2dfe9e4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-27 07:59 UTC, opbld34 commented
Docs Build status updates of commit _[adf347f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/adf347fe9a742e4a272d96e0e38f28c740c2ec20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-b09446f5)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-b09446f5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-27 10:10 UTC, opbld31 commented
Docs Build status updates of commit _[22dac40](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22dac401236d5a436e3c6a79a695aad136b71dad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-683ae1de)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-683ae1de"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-27 10:15 UTC, opbld33 commented
Docs Build status updates of commit _[32dbf9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32dbf9c28da34374ed963c609280988cd36bddae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-1645dd8d)
[api-reference/v1.0/api/channel-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-delete?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-list?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-members-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-members-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-update?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-members-add?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-1645dd8d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-27 15:51 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +          href: api/channel-members-delete.md
@AkJo In this example it should be channel-delete-members. Please refer to our file naming guidelines: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55061/File-naming.

2020-10-28 12:07 UTC, opbld34 commented
Docs Build status updates of commit _[3437562](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34375620a4d98fb38276804548a486629445c727)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0426d3e0)

<a id="0426d3e0"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010281206333373-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0vmSHGtxzDX9ejTwbhjs82Pd2IdXXVPBcK1lidmXk9k%3D&st=2020-10-28T12%3A02%3A01Z&se=2020-11-28T12%3A07%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 12:08 UTC, opbld33 commented
Docs Build status updates of commit _[be7f8d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be7f8d3c09dfcd4477a8d53cb6cdd0893ff801ce)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0149fbff)

<a id="0149fbff"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010281208116443-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uNMkTRbRgTsf6Sx1k7bL3XOTmUtQDy8KeA6cwfewL4I%3D&st=2020-10-28T12%3A03%3A38Z&se=2020-11-28T12%3A08%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 12:09 UTC, opbld34 commented
Docs Build status updates of commit _[c3e9aca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3e9aca91680402120e1b30fc29ec0ae0a81441e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5f567054)

<a id="5f567054"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010281209253231-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4tEINO%2FE3sATtozC8ZPWQii3jhtI9UOpuDC2Z%2BauB4M%3D&st=2020-10-28T12%3A04%3A53Z&se=2020-11-28T12%3A09%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 12:10 UTC, opbld34 commented
Docs Build status updates of commit _[b26ee14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b26ee1418585e1d3f0413153c290fa6812e51458)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-97b39fad)

<a id="97b39fad"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010281210240943-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZnprkNbr5xbXt0M1Rxw%2FRBEQQjNKQQKwyHmarFx5W1Q%3D&st=2020-10-28T12%3A05%3A50Z&se=2020-11-28T12%3A10%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 12:12 UTC, opbld30 commented
Docs Build status updates of commit _[7b8daf4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b8daf4c88c4ebd37dd5b96e80df13f524a83c48)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-54f13e35)

<a id="54f13e35"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010281212257528-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RRsWlrLbx7krcNhcL03KGIkkDc4FO42jykTSNrHj0sM%3D&st=2020-10-28T12%3A07%3A52Z&se=2020-11-28T12%3A12%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 12:16 UTC, opbld33 commented
Docs Build status updates of commit _[51daf7d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/51daf7d83c622dcb39b58bc43a87b246d959f63b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d8a3a405)

<a id="d8a3a405"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010281216249345-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ILLQ8pJyJcn77B%2F5KGwBjbSbsnDztUlZAk4chKutOWE%3D&st=2020-10-28T12%3A11%3A50Z&se=2020-11-28T12%3A16%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 12:19 UTC, opbld31 commented
Docs Build status updates of commit _[5fdf4a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5fdf4a0b4d552a3192fa781b1aae0873b53f0c7e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-77d894e2)

<a id="77d894e2"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010281218487318-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=G1kYfhVcKVOufrw9AjHxwVO%2BYqbBbuLPBDzRa9cWdTc%3D&st=2020-10-28T12%3A14%3A16Z&se=2020-11-28T12%3A19%3A16Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-29 07:13 UTC, opbld32 commented
Docs Build status updates of commit _[a518aba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a518abad733410ea84ef16b9e966e81b878a46cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-34317fa4)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-34317fa4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-29 07:18 UTC, opbld30 commented
Docs Build status updates of commit _[d5f37a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5f37a8486eeb6089fd264b745cb82ccf240e00e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-c9822ee6)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-c9822ee6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-29 07:24 UTC, opbld34 commented
Docs Build status updates of commit _[4fb3afd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4fb3afd15797e4b34fecd6410768e6284b8b9fea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-070f7ec9)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-070f7ec9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-29 07:42 UTC, opbld33 commented
Docs Build status updates of commit _[6d8a331](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d8a33116385948942657986957d5018ff706502)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-bdd7aa2a)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-bdd7aa2a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-29 08:08 UTC, opbld30 commented
Docs Build status updates of commit _[5f2d17d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f2d17db963ef020aaece61726c90760db03b668)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-407b3aa8)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-407b3aa8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-29 08:21 UTC, opbld34 commented
Docs Build status updates of commit _[c884eb8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c884eb8006dccff7b1b1b1023007243283dc186f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-f22cb144)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-f22cb144"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-29 08:39 UTC, opbld31 commented
Docs Build status updates of commit _[7a8bb9f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a8bb9f6e0a744382bae1e15c9274862d054ee51)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-de3c2e97)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-de3c2e97"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-29 09:59 UTC, opbld32 commented
Docs Build status updates of commit _[494205e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/494205ee4d0c675756768b81c64977563639f226)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-8b9c5359)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-8b9c5359"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-29 10:18 UTC, opbld34 commented
Docs Build status updates of commit _[14f75ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14f75caf7d8336edd8b0f340668e3a79011bf43e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-6a4c6adb)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-6a4c6adb"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-29 10:26 UTC, opbld31 commented
Docs Build status updates of commit _[0d1307e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d1307eabf937a4cc8b0d6df77d077f4e989019d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-93d842d6)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-93d842d6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-29 10:35 UTC, opbld33 commented
Docs Build status updates of commit _[8de4b72](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8de4b726c8112295f2aa5950d3c320b5301fab8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-d47fadcb)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-d47fadcb"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-29 11:37 UTC, opbld30 commented
Docs Build status updates of commit _[ec53025](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec53025144d4ded2566dee4abb63ae7ba0362cbe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-9fb5684a)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-9fb5684a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-29 11:45 UTC, opbld33 commented
Docs Build status updates of commit _[7a06736](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a06736508c3e49c549ef49b3ac901e582aa112f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-3c7faf92)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-3c7faf92"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-29 11:48 UTC, opbld33 commented
Docs Build status updates of commit _[ab9bb40](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab9bb4042798e42762ca067111f863ad42eaab77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-caaca3d6)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-caaca3d6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-30 08:51 UTC, opbld32 commented
Docs Build status updates of commit _[637bbf6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/637bbf6387ee90a68f19078bd357d5060698756b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-01d02e58)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-01d02e58"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-30 10:04 UTC, opbld33 commented
Docs Build status updates of commit _[72f4421](https://github.com/microsoftgraph/microsoft-graph-docs/commits/72f44216369505fb8ca0c3ff60db1cfa8772869d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-2ebed122)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-2ebed122"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-10-30 10:21 UTC, opbld32 commented
Docs Build status updates of commit _[8f67374](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f673748e42d1faa90c4e50bfe44d0d2c2b1f9d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-7f689652)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-7f689652"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-11-02 03:38 UTC, opbld32 commented
Docs Build status updates of commit _[27a9c6a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27a9c6a5557b81466ad6142bf77d554ef1ff325f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-eed78d58)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-eed78d58"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/ [...]

2020-11-03 03:51 UTC, opbld30 commented
Docs Build status updates of commit _[28c7dd6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/28c7dd6794c367c0c09824ce3d926274f02c00e1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-2e15c7f6)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-2e15c7f6)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-2e15c7f6"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4949, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 4949, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-message.md'.`````
 - **Line 4972, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-2e15c7f6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserv [...]

2020-11-03 05:09 UTC, opbld33 commented
Docs Build status updates of commit _[63c2c4b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63c2c4b206ae29d9dae1269666a2e3495ce7a0a1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-dde6dc4a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-dde6dc4a)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-dde6dc4a"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4949, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 4949, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-message.md'.`````
 - **Line 4972, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-dde6dc4a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserv [...]

2020-11-03 05:26 UTC, opbld32 commented
Docs Build status updates of commit _[6fccaae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6fccaae57610e1b93717ea96da6fe709e76445d8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-3728caaf)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-3728caaf)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-3728caaf"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4949, Column 11**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 4949, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-message.md'.`````
 - **Line 4972, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-3728caaf"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserv [...]

2020-11-03 10:58 UTC, opbld30 commented
Docs Build status updates of commit _[4e502f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e502f964be958b3f95aaa56e413737de32a3026)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-eb4b8837)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-eb4b8837)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-eb4b8837"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-eb4b8837"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean [...]

2020-11-04 09:41 UTC, AkJo commented on api-reference/v1.0/api/channel-add-members.md
> +
Please add a line. 

This operation is allowed only for channels with membershipType of 'private'.

2020-11-04 09:43 UTC, AkJo commented on api-reference/v1.0/api/channel-delete-members.md
> +
This operation is allowed only for channels with membershipType of 'private'.

2020-11-04 09:45 UTC, AkJo commented on api-reference/v1.0/api/channel-list-members.md
> +Retrieve a [conversationMember](../resources/conversationmember.md) from a [channel](../resources/channel.md).
Please remember:

A list API returns ALL items.

A get API returns a single element.

This document is about the list API.

2020-11-04 09:45 UTC, AkJo commented on api-reference/v1.0/api/channel-list-members.md
> +Retrieve a [conversationMember](../resources/conversationmember.md) from a [channel](../resources/channel.md).
Retrieve [conversationMember]s(../resources/conversationmember.md) from a [channel]

2020-11-04 09:46 UTC, AkJo commented on api-reference/v1.0/api/channel-list-members.md
> +GET /channels/{id}/members/{id}
GET /channels/{id}/members

2020-11-04 09:46 UTC, AkJo commented on api-reference/v1.0/api/channel-list-members.md
> +GET https://graph.microsoft.com/v1.0/channels/{id}/members/{id}
GET https://graph.microsoft.com/v1.0/channels/{id}/members

2020-11-04 09:50 UTC, AkJo commented on api-reference/v1.0/api/channel-list-members.md
> +
Please put down a response that shows collection. 



    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#teams('2ab9c796-2902-45f8-b712-7c5a63cf41c4')/channels('19%3A20bc1df46b1148e9b22539b83bc66809%40thread.skype')/members",
    "@odata.count": 2,
    "value": [
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "id": "MmFiOWM3OTYtMjkwMi00NWY4LWI3MTItN2M1YTYzY2Y0MWM0IyNlZWY5Y2IzNi0wNmRlLTQ2OWItODdjZC03MGY0Y2JlMzJkMTQ=",
            "roles": [],
            "displayName": "Joe Self",
            "userId": "eef9cb36-06de-469b-87cd-70f4cbe32d14",
            "email": "jself@teamsip.onmicrosoft.com"
        },
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "id": "MmFiOWM3OTYtMjkwMi00NWY4LWI3MTItN2M1YTYzY2Y0MWM0IyNiMzI0NmY0NC1jMDkxLTQ2MjctOTZjNi0yNWIxOGZhMmM5MTA=",
            "roles": [
                "owner"
            ],
            "displayName": "Anagha Kothurwar",
            "userId": "b3246f44-c091-4627-96c6-25b18fa2c910",
            "email": "ankothur@teamsip.onmicrosoft.com"
        }
   ]
}

2020-11-04 09:52 UTC, AkJo commented on api-reference/v1.0/api/channel-update-members.md
> +Update the role of a [conversationMember](../resources/conversationmember.md) in a [channel](../resources/channel.md).
Please add a line.

This operation is allowed only for channels with membershipType of 'private'.

2020-11-04 10:00 UTC, AkJo commented on api-reference/v1.0/toc.yml
>          - name: Get files folder
You will have one more entry in the toc

Get member in channel
api/channel-get-members.md

This document would be dedicated to getting a single member of a channel.

GET /teams/id/channels/id/members/id

2020-11-04 10:01 UTC, AkJo commented on concepts/changelog.md
> -|Addition|v1.0|Added new entities:<br/>[androidCompliancePolicy](/graph/api/resources/intune-deviceconfig-androidcompliancepolicy?view=graph-rest-1.0)<br/>[androidCustomConfiguration](/graph/api/reso
Please ensure that you have undone all these deletions.

Changes to the changelog file are always additive. You should not be deleting anything from them.

2020-11-04 10:02 UTC, AkJo commented on concepts/changelog.md
> +|Addition|beta|Added the **channelCreationMode** property to the [channel](/graph/api/resources/channel?view=graph-rest-beta) resource.|
You are not adding any of these as part of this PR. Why are you adding changelog entries for them here then?

2020-11-04 10:04 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +|[Update the role of a member in a channel](../api/channel-update-members.md) | [conversationMember](conversationmember.md) | Update the properties of a member of the channel. Only supported for chan
Add one more row for 'Get a member in a channel'

2020-11-04 10:05 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +|membershipType|channelMembershipType|The type of the channel. Can be set during creation and cannot be changed. Possible values are 'standard' - Channel inherits the list of members of the parent te
Possible values are:

2020-11-04 10:06 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +|membershipType|channelMembershipType|The type of the channel. Can be set during creation and cannot be changed. Possible values are 'standard' - Channel inherits the list of members of the parent te
You have different kind of quotes around `standard` vs `private`. Please be consistent.

2020-11-04 10:07 UTC, opbld32 commented
Docs Build status updates of commit _[de7aa78](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de7aa7829f440a7755c830705932274fb3655dc8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-52686b70)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-52686b70)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-52686b70"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-52686b70"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean [...]

2020-11-04 10:08 UTC, AkJo commented on api-reference/v1.0/toc.yml
> +          href: api/channel-delete-members.md
I think the general convention is to skip articles in the toc entry names to keep the string short.

List members of channel
Add member to channel
Update role of member in channel
Delete member from channel

2020-11-04 10:08 UTC, opbld32 commented
Docs Build status updates of commit _[2bef441](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2bef441e45dedc5d6a3131b7773967c788563814)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-a435367f)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-a435367f)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-a435367f"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-a435367f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean [...]

2020-11-04 10:11 UTC, opbld33 commented
Docs Build status updates of commit _[a2e9cfe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a2e9cfefc1b2e9165f1bbd9de7643e1544724304)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-64f5edb0)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-64f5edb0)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-64f5edb0"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-64f5edb0"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean [...]

2020-11-04 10:18 UTC, opbld30 commented
Docs Build status updates of commit _[8dab378](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8dab3788f32fa1f6378d9e67e54c24c483acdf3c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-ba53ff97)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-ba53ff97)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-ba53ff97"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-ba53ff97"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean [...]

2020-11-04 10:20 UTC, opbld33 commented
Docs Build status updates of commit _[37a43de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37a43de51e381bfda1f2290d0c4a392235252f32)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-346e1004)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-346e1004)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-346e1004"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-346e1004"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean [...]

2020-11-04 10:49 UTC, opbld33 commented
Docs Build status updates of commit _[25d4967](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25d49679192845adda1bb12306a4d883ec1add40)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-66aa9f47)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-66aa9f47)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-66aa9f47"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-66aa9f47"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/repor [...]

2020-11-04 11:02 UTC, opbld33 commented
Docs Build status updates of commit _[cfda607](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cfda60736953e21c289c9dc893fa4f76d05f69e4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-c3651caf)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-c3651caf)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-c3651caf"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-c3651caf"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/repor [...]

2020-11-04 11:11 UTC, opbld32 commented
Docs Build status updates of commit _[2f007f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2f007f9009e4f32b0f62fa5aa2852824e57e642d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-d31149ee)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-d31149ee)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-d31149ee"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4973, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-d31149ee"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/repor [...]

2020-11-04 13:28 UTC, opbld33 commented
Docs Build status updates of commit _[e901cf9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e901cf91600c90e41e7588fac9c3766719fff763)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-85beac18)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-85beac18)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-85beac18"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4973, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-85beac18"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/repor [...]

2020-11-05 03:01 UTC, Lauragra commented on api-reference/v1.0/api/channel-add-members.md
> +  "roles": [],
Why is the roles value blank in this example? If the member is not an owner, is there no value?

2020-11-05 03:01 UTC, opbld31 commented
Docs Build status updates of commit _[002ca8f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/002ca8fcc8216e7326f944356c0762612e6b9a60)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-165bc9b5)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-165bc9b5)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-165bc9b5"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4973, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-165bc9b5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/repor [...]

2020-11-05 03:05 UTC, opbld31 commented
Docs Build status updates of commit _[75bc06b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/75bc06b6fea9a0c748f47d711e3881a1cb80980c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-ec1fcd77)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-ec1fcd77)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-ec1fcd77"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4973, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-ec1fcd77"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/repor [...]

2020-11-05 03:06 UTC, opbld30 commented
Docs Build status updates of commit _[cca6b72](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cca6b723b5a0906284f60fe3b5f2a9c61aa780d8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-bcf1ddbb)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-bcf1ddbb)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-bcf1ddbb"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4973, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-bcf1ddbb"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/repor [...]

2020-11-05 03:09 UTC, opbld32 commented
Docs Build status updates of commit _[db6caa7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db6caa7916fc10581a23aa2acf2dccc5d6896732)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-6ae46bcf)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-6ae46bcf)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-6ae46bcf"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4973, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-6ae46bcf"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/repor [...]

2020-11-05 03:12 UTC, opbld34 commented
Docs Build status updates of commit _[c4043ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4043ad3e0c176d1ae43abddcdf960f1a32c9702)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-c7960069)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-c7960069)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-c7960069"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4973, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-c7960069"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/repor [...]

2020-11-05 03:14 UTC, Lauragra requested changes
Please revert the change that deletes most of the changelog. Also, you'll need to add an update to the Microsoft.Teams.Core.json file with the changelog entry.

2020-11-05 03:14 UTC, opbld32 commented
Docs Build status updates of commit _[f2dfe88](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2dfe886e3931b9bbd68bc66b0ef0c68a828d13a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-e6689f1d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-e6689f1d)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-e6689f1d"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4973, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-e6689f1d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/repor [...]

2020-11-05 03:18 UTC, Lauragra requested changes
We seem to be adding these new operations to v1.0 but we don't have comparable files in beta. Did we miss documenting the operations in beta? Please reconcile the discrepancy. APIs always release to beta first before they are promoted to v1.0.

2020-11-05 05:45 UTC, opbld32 commented
Docs Build status updates of commit _[ca28ee4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ca28ee4e8cfc2d49f572b75136419462f55db075)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-2e7e772f)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-2e7e772f)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-2e7e772f"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4973, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-2e7e772f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/repor [...]

2020-11-05 07:05 UTC, opbld33 commented
Docs Build status updates of commit _[bddf87d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bddf87da7f7e216fd2dfd5e8951e4524ee4c8af4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-ff7fc7f4)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-ff7fc7f4)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-ff7fc7f4"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4973, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-ff7fc7f4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/repor [...]

2020-11-05 20:27 UTC, opbld34 commented
Docs Build status updates of commit _[cc7f7c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc7f7c2fb8c09e0bbd337cf4d4222c994a4331b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-68219bd4)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-68219bd4)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-68219bd4"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-68219bd4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/repor [...]

2020-11-06 08:40 UTC, AkJo commented on api-reference/v1.0/api/channel-get-members.md
> +    {
This API is supposed to return a single element.

You are indexing into a specific element in the members collection.
/channels/id/**members/id**


This is what a response would look like:

{
  "@odata.context": "https://graph.microsoft.com/V1.0/$metadata#teams('ece6f0a1-7ca4-498b-be79-edf6c8fc4d82')/channels('19%3A56eb04e133944cf69e603c5dac2d292e%40thread.skype')/members/microsoft.graph.aadUserConversationMember/$entity",
  "@odata.type": "#microsoft.graph.aadUserConversationMember",
  "id": "8b081ef6-4792-4def-b2c9-c363a1bf41d5",
  "roles": ["owner"],
  "displayName": "John Doe",
  "userId": "8b081ef6-4792-4def-b2c9-c363a1bf41d5",
  "email": null
}

Please update the sample.

2020-11-06 08:43 UTC, AkJo commented on api-reference/v1.0/api/channel-add-members.md
> +POST /channels/{id}/members/{id}
POST /teams/{id}/channels/{id}/members/{id}

2020-11-06 08:44 UTC, AkJo commented on api-reference/v1.0/api/channel-add-members.md
> +POST /channels/{id}/members/{id}
There is no valid path GET "channels/id/members/id"

Members are contained inside a channel which is contained inside a team.

The valid path is /teams/{id}/channels/{id}/members/{id}

Why is this mistake repeated over and over in each doc?

2020-11-06 08:45 UTC, AkJo commented on api-reference/v1.0/api/channel-add-members.md
> +POST https://graph.microsoft.com/v1.0/channels/{id}/members/{id}
POST https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/members/{id}

2020-11-06 08:46 UTC, AkJo commented on api-reference/v1.0/api/channel-delete-members.md
> +DELETE /channels/{id}/members/{id}
/teams/{id}/channels/{id}/members/{id}

2020-11-06 08:47 UTC, AkJo commented on api-reference/v1.0/api/channel-add-members.md
> +POST https://graph.microsoft.com/v1.0/channels/{id}/members/{id}
https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/members

2020-11-06 08:52 UTC, AkJo commented
> We seem to be adding these new operations to v1.0 but we don't have comparable files in beta. Did we miss documenting the operations in beta? Please reconcile the discrepancy. APIs always release to beta first before they are promoted to v1.0.

@Lauragra , the data is already in beta but under a different and poorly name file. But, fair point about the inconsitency.

@Rajeshwari-v , as part of this PR, please make a copy/identical edit under the beta path for all the files in this PR.

You will update the toc in beta to mirror what we are doing for v1.

2020-11-06 09:15 UTC, opbld33 commented
Docs Build status updates of commit _[88588b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88588b0566ed66a24d5c56ba318bbc6592759266)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-7185c419)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-7185c419)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-7185c419"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-7185c419"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did  [...]

2020-11-06 09:18 UTC, opbld32 commented
Docs Build status updates of commit _[24ab791](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24ab791927a5dce4eaff9e1c7f21374697ca0df1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-98a1c22d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-98a1c22d)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-98a1c22d"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-98a1c22d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did  [...]

2020-11-06 09:24 UTC, opbld32 commented
Docs Build status updates of commit _[b073725](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b07372507fb5acd8daefd02efce8ecb571462118)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-ee956955)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-ee956955)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-ee956955"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-ee956955"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did  [...]

2020-11-06 09:29 UTC, opbld33 commented
Docs Build status updates of commit _[c2b87c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2b87c241cf33b483d1d599bedcd66dc18413cb4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-85e20934)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-85e20934)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-85e20934"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-85e20934"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did  [...]

2020-11-06 09:32 UTC, opbld32 commented
Docs Build status updates of commit _[1f1d7a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f1d7a9e3a5008736c823f151c4bac1d813c913b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-101f1728)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-101f1728)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-101f1728"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-101f1728"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did  [...]

2020-11-06 09:43 UTC, opbld32 commented
Docs Build status updates of commit _[a06df33](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a06df33add34af7bddbf0e63468c76ab78b5eb7c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-9bedf62f)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-9bedf62f)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-9bedf62f"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-9bedf62f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did  [...]

2020-11-06 10:25 UTC, opbld33 commented
Docs Build status updates of commit _[e0e12c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e0e12c5a9a7aa3405db2f94ac21421cc9c6920b7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-80c4229d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-80c4229d)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-80c4229d"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-80c4229d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did  [...]

2020-11-06 10:26 UTC, opbld31 commented
Docs Build status updates of commit _[f6e6c0e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6e6c0e6f34e31e2907c86b45871f13055be0844)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-1ba2f01f)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-1ba2f01f)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-1ba2f01f"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-1ba2f01f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did  [...]

2020-11-06 10:28 UTC, opbld34 commented
Docs Build status updates of commit _[66aa0ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66aa0ed31795a98c614701b4096c43258ce39813)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-d7703ed6)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-d7703ed6)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-d7703ed6"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-d7703ed6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did  [...]

2020-11-06 10:29 UTC, opbld33 commented
Docs Build status updates of commit _[e901525](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e901525b2db44b47d51f8685753d3255c8f40ff4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-5725c9d5)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-5725c9d5)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-5725c9d5"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-5725c9d5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did  [...]

2020-11-06 10:31 UTC, opbld34 commented
Docs Build status updates of commit _[146fe2e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/146fe2e109f072246e9572c610567e4321979cdd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-3d71fcbe)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-3d71fcbe)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-3d71fcbe"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-3d71fcbe"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did  [...]

2020-11-06 10:32 UTC, opbld33 commented
Docs Build status updates of commit _[0b89724](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b89724c86c3f00abae6359f00db34f94e123763)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-80e9e00c)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-80e9e00c)
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-80e9e00c"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-80e9e00c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did  [...]

2020-11-06 10:44 UTC, opbld33 commented
Docs Build status updates of commit _[f49c8a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f49c8a469fad61bef27f46dcbc844d275c656cc0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-c45b0df3)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-c45b0df3)
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-c45b0df3"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-c45b0df3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/ap [...]

2020-11-06 11:13 UTC, AkJo requested changes

2020-11-06 11:13 UTC, AkJo commented on api-reference/v1.0/api/channel-add-members.md
> +POST /teams/{id}/channels/{id}/members/{id}
When you are adding member, you are posting to the "members" **collection**, and not to an individual element in the collection. 

The  correct url will be
POST /teams/{id}/channels/{id}/members

2020-11-06 11:13 UTC, AkJo commented on api-reference/v1.0/api/channel-add-members.md
> +POST https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/members/{id}
POST https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/members

2020-11-06 11:13 UTC, AkJo commented on api-reference/v1.0/api/channel-add-members.md
> +POST https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/members/{id}
POST https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/members

2020-11-06 11:13 UTC, AkJo commented on api-reference/v1.0/toc.yml
> +          href: api/channel-add-members.md
Also, please ensure that all these files exist and entries in the toc exist under the /beta path as well. 

If not then, please make identical updates to the beta section as well.

2020-11-06 11:58 UTC, opbld33 commented
Docs Build status updates of commit _[2f0d4bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2f0d4bf1bdb36ee06e5cffbdb9f755d88932d55f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-b50b9c5d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-b50b9c5d)
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-b50b9c5d"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-b50b9c5d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: [...]

2020-11-06 12:04 UTC, opbld32 commented
Docs Build status updates of commit _[230e8fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/230e8fefa7936b814f557fa6a32f45850ddfaeed)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-b2c2f2d0)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-b2c2f2d0)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-b2c2f2d0"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-b2c2f2d0"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL [...]

2020-11-06 12:06 UTC, opbld34 commented
Docs Build status updates of commit _[23728de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23728dea1f5b7d52f9e9d15b6589fd6f0c9e2b38)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-191e2043)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-191e2043)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-191e2043"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-191e2043"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL [...]

2020-11-06 12:09 UTC, opbld31 commented
Docs Build status updates of commit _[f001fb2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f001fb28983ff48bf59b03866a04312ed54519e6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-567bd24a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-567bd24a)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-567bd24a"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-567bd24a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, [...]

2020-11-06 12:11 UTC, opbld32 commented
Docs Build status updates of commit _[b42bc5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b42bc5dfaafc104a02c49abb98e8a4dcf1c9e964)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-36be1462)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-36be1462)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-36be1462"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-36be1462"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean t [...]

2020-11-06 12:14 UTC, opbld31 commented
Docs Build status updates of commit _[9fbc987](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9fbc9875169682612d595abcc48e9b50993b1d97)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-8f06154b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-8f06154b)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-8f06154b"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-8f06154b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/re [...]

2020-11-06 13:09 UTC, opbld33 commented
Docs Build status updates of commit _[3e4b307](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e4b30736a22c70de76b113fd7daea9eb389107f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-1c275a2f)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-1c275a2f)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-1c275a2f"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-1c275a2f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/re [...]

2020-11-06 13:53 UTC, opbld31 commented
Docs Build status updates of commit _[4666369](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4666369457b6a7e95656737f1593c07c6d0b555e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-167f6352)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-167f6352)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-167f6352"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-167f6352"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/re [...]

2020-11-06 13:57 UTC, opbld33 commented
Docs Build status updates of commit _[106c754](https://github.com/microsoftgraph/microsoft-graph-docs/commits/106c754e39951296d4a5b2730a326e04a2d31e90)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-bc0687de)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-bc0687de)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-bc0687de"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-bc0687de"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/re [...]

2020-11-06 15:05 UTC, opbld33 commented
Docs Build status updates of commit _[13ba3a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13ba3a6eca2970a5592e8779f4efb60e2ea0a3cf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-c3a87ac3)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-77cfd98e-c3a87ac3)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-c3a87ac3)

<a id="00685cff-c3a87ac3"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml)
 - **Line 556, Column 6**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="77cfd98e-c3a87ac3"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-messages.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-c3a87ac3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 63, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 64, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 65, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 66, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources [...]

2020-11-06 22:27 UTC, AkJo commented on api-reference/v1.0/resources/channel.md
> +|[List members of a channel](../api/channel-list-members.md) | [conversationMember](conversationmember.md) collection | Get the list of members in a channel.|
Some of this is a repetition of line 28 to 32. Either overwrite the previous entries or delete them.

2020-11-06 22:29 UTC, AkJo commented on api-reference/v1.0/toc.yml
>          - name: Add a member to a channel
These entries are acting as duplicates now. Please remove them.

Please always check whether a new additions that you are making are a duplication of existing entries on the same file.

2020-11-06 22:29 UTC, AkJo commented on api-reference/v1.0/toc.yml
> -          href: api/channel-post.md
Why is this being deleted?

2020-11-06 22:35 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: Add  member to  channel
extra space?

2020-11-06 22:38 UTC, AkJo commented on api-reference/beta/toc.yml
> +          href: api/conversationmember-delete.md
These are redundant when you compare them to analogous entries made in 567 to 571. Please remove them

2020-11-06 22:40 UTC, AkJo commented on api-reference/v1.0/toc.yml
>          - name: Add a member to a channel
Line 4951 to 4956

2020-11-08 04:28 UTC, opbld32 commented
Docs Build status updates of commit _[c8b208a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8b208a51b574956c5d777607718e69455f280a6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4127510d)

<a id="4127510d"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011080427593445-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NriaF7GmzOSfeTkYvSvbEDYhrniH5EbUAGHSx717cAw%3D&st=2020-11-08T04%3A23%3A23Z&se=2020-12-09T04%3A28%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-08 05:12 UTC, opbld32 commented
Docs Build status updates of commit _[9ffc21f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ffc21f50ca1135227730496e9c7e2f13812323c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-196aebe4)

<a id="196aebe4"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011080512229296-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ayOfEujfh0eQ6SixOSG0EKMc1W0%2B5AfEWZwF2k%2Bg%2BLI%3D&st=2020-11-08T05%3A07%3A44Z&se=2020-12-09T05%3A12%3A44Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-08 05:17 UTC, opbld30 commented
Docs Build status updates of commit _[a0ed06b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0ed06b1f1d207b400cfe95489b0384003045c06)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b953d1e5)

<a id="b953d1e5"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011080517324709-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LwBw18EHFAWYZ7AwQB80TNZ8JO5PWx7qii6V4BvtAhg%3D&st=2020-11-08T05%3A12%3A52Z&se=2020-12-09T05%3A17%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-08 05:27 UTC, opbld31 commented
Docs Build status updates of commit _[fd1d9ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fd1d9ecc331e3642dcfe2c25e4cd680bd27c6e5d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f0d87bbc)

<a id="f0d87bbc"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011080527252927-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tr80RY84VYwDplneyGEL11c6l9Ez%2BsX3ZE8zEUbR84k%3D&st=2020-11-08T05%3A22%3A45Z&se=2020-12-09T05%3A27%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-08 05:28 UTC, opbld30 commented
Docs Build status updates of commit _[d1e6a6f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1e6a6fc4b119e09ef310b57fbd6d881560dd3fc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2d5d4a51)

<a id="2d5d4a51"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011080528119490-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BGORLv2zNWqibPtDsg75ah1%2BlLDkfSNUaYo7oPLUL4w%3D&st=2020-11-08T05%3A23%3A41Z&se=2020-12-09T05%3A28%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-08 05:43 UTC, opbld34 commented
Docs Build status updates of commit _[11dd76f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11dd76f85d83f21f9ce4090c163ff06b79e24f67)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-a4b70899)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-a4b70899)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-a4b70899"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4953, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-a4b70899"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/re [...]

2020-11-08 05:52 UTC, opbld32 commented
Docs Build status updates of commit _[ee04c16](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee04c16140a648bc5cb858a402b5878d2627d148)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-0b74f3ad)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-0b74f3ad)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-0b74f3ad"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4953, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-0b74f3ad"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/re [...]

2020-11-08 06:21 UTC, opbld32 commented
Docs Build status updates of commit _[1cba554](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1cba55478d7b1a43b7c0699b40c1bcad15662a1c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-a1a32739)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-a1a32739)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="77cfd98e-a1a32739"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml)
 - **Line 4953, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-a1a32739"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?vi [...]

2020-11-08 06:26 UTC, opbld31 commented
Docs Build status updates of commit _[74ad2e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/74ad2e6eb63628d912b01204c47d776a41ebde61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-6b0a8b2e)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-6b0a8b2e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to  [...]

2020-11-08 07:06 UTC, AkJo commented on api-reference/beta/resources/channel.md
> -|[Get message delta](../api/chatmessage-delta.md)  | [chatMessage](../resources/chatmessage.md) | Get incremental messages in a channel. |
Why is this being deleted?

2020-11-08 07:06 UTC, AkJo commented on api-reference/beta/resources/channel.md
> -|[List channel messages](../api/channel-list-messages.md)  | [chatMessage](../resources/chatmessage.md) | Get messages in a channel |
Why is this being deleted?

2020-11-08 07:06 UTC, AkJo commented on api-reference/beta/resources/channel.md
> -|[Create chatMessage in a channel](../api/channel-post-message.md) | [chatMessage](../resources/chatmessage.md) | Send a message to a channel. |
Why is this being deleted?

2020-11-08 07:06 UTC, AkJo commented on api-reference/beta/resources/channel.md
> -|[Complete migration](../api/channel-completemigration.md)|[channel](channel.md)| Removes thee migration mode from the channel and makes the channel available to users to post and read messages.|
Why are these being deleted?

2020-11-08 07:09 UTC, AkJo commented on concepts/changelog.md
> -|Addition|beta|Added support for **completeMigration** to the [channel](/graph/api/resources/channel?view=graph-rest-beta) and [team](/graph/api/resources/team?view=graph-rest-beta) resources.
Why is this being deleted?

2020-11-08 07:10 UTC, AkJo commented on api-reference/v1.0/toc.yml
> +      - name: Get changes to messages (example)F
What is this?

2020-11-08 07:14 UTC, AkJo commented on api-reference/v1.0/toc.yml
> +          href: /graph/teams-list-all-teams?context=graph/api/1.0
What is this? I do not see any mention of this in our currently published docs - neither in beta nor v1

https://docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta

2020-11-08 07:15 UTC, AkJo commented on api-reference/v1.0/toc.yml
> -          href: api/channel-get-message.md
Why are these entries being deleted?

2020-11-09 04:12 UTC, Rajeshwari-v commented on api-reference/beta/resources/channel.md
> -|[Get message delta](../api/chatmessage-delta.md)  | [chatMessage](../resources/chatmessage.md) | Get incremental messages in a channel. |
This file exist in chatmessage.md file already in v1.0 and thought it wouldn't be appropriate if chatmessage related file exist in channel resource file.  Just to make beta in sync with v1.0, deleted the entry. Please advise if any further changes required

2020-11-09 04:15 UTC, opbld31 commented
Docs Build status updates of commit _[dbcce0e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dbcce0e2e3e6a9764d8c77f8adad54dd0b526119)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-db94d9bc)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-db94d9bc"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to  [...]

2020-11-09 04:27 UTC, Rajeshwari-v commented on api-reference/beta/resources/channel.md
> -|[List channel messages](../api/channel-list-messages.md)  | [chatMessage](../resources/chatmessage.md) | Get messages in a channel |
Same as above

2020-11-09 04:30 UTC, Rajeshwari-v commented on api-reference/v1.0/toc.yml
> +      - name: Get changes to messages (example)F
Haven't done this

2020-11-09 04:33 UTC, Rajeshwari-v commented on api-reference/v1.0/toc.yml
> +          href: /graph/teams-list-all-teams?context=graph/api/1.0
Haven't done this

2020-11-09 04:34 UTC, Rajeshwari-v commented on api-reference/v1.0/toc.yml
> -          href: api/channel-get-message.md
These are present in chatmessage resource entries.

2020-11-09 06:01 UTC, opbld34 commented
Docs Build status updates of commit _[5868f8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5868f8a89d234b353c8beda5581c44e538a02ba7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-1c96f9b4)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-1c96f9b4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to  [...]

2020-11-09 07:01 UTC, opbld30 commented
Docs Build status updates of commit _[13c8d46](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13c8d4678f847cfb3b4ef434074f21177ab53aa4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-fd5fccc9)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-fd5fccc9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to  [...]

2020-11-09 07:29 UTC, opbld31 commented
Docs Build status updates of commit _[5bbbd13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5bbbd13564963bafeb3634df14a051d4bd763736)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-f78f49f4)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |

<a id="de0bbbbb-f78f49f4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-beta`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to  [...]

2020-11-09 07:32 UTC, Rajeshwari-v commented on api-reference/beta/resources/channel.md
> -|[Create chatMessage in a channel](../api/channel-post-message.md) | [chatMessage](../resources/chatmessage.md) | Send a message to a channel. |
These files not present in v1.0

2020-11-09 09:38 UTC, opbld30 commented
Docs Build status updates of commit _[6a627f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a627f3faf2f45744458d6dd8c2e5c9777cd5485)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-8759987c)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-8759987c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-09 09:47 UTC, opbld32 commented
Docs Build status updates of commit _[26d462d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26d462d5696c4749d6e8efe987c724f8c1fff7e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-122aa8c3)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-122aa8c3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-09 09:51 UTC, opbld31 commented
Docs Build status updates of commit _[138e691](https://github.com/microsoftgraph/microsoft-graph-docs/commits/138e69134c79240c1d34052426d6d639151ca97a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-c7544a46)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-c7544a46"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-09 10:09 UTC, opbld33 commented
Docs Build status updates of commit _[a95e6fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a95e6fe79aede035a2be6817f382332d808c56aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-f0ae2931)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-f0ae2931"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-10 04:44 UTC, opbld34 commented
Docs Build status updates of commit _[eee4b87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eee4b875210721c846ecef90e2f674d36dac6130)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-ca41e949)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-ca41e949"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-10 10:11 UTC, opbld34 commented
Docs Build status updates of commit _[54d331a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/54d331a2bcb29ce0c80fd3a33f9ee58898cd074b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-fefdf60a)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-fefdf60a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-11 06:42 UTC, opbld30 commented
Docs Build status updates of commit _[7e03735](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e03735f888c2346e13122cffa1a75a51737c563)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-9a97876d)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-9a97876d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-11 06:48 UTC, opbld30 commented
Docs Build status updates of commit _[9b8ec9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b8ec9ca0bb919b44784bbb8305fdef5192ee984)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-24155435)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-24155435"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-11 06:53 UTC, opbld34 commented
Docs Build status updates of commit _[476f53f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/476f53f21226ca73d1ba5e7a223fc651beb14c44)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9b9c20f5)

<a id="9b9c20f5"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011110652423114-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=345Z3NYkpCw9jRkEoLnlTOM6Hk38yoLYeMK27H74NNY%3D&st=2020-11-11T06%3A48%3A22Z&se=2020-12-12T06%3A53%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-11 06:59 UTC, opbld30 commented
Docs Build status updates of commit _[d1d92ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1d92ce016ce2b243d299e5f99612808f2023e92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-3360ad8c)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-3360ad8c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-11 07:14 UTC, opbld33 commented
Docs Build status updates of commit _[d404dfa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d404dfaac91f7fa6828f9dd0087d434dbfabbad7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-9f613cdb)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-9f613cdb"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-11 07:16 UTC, opbld33 commented
Docs Build status updates of commit _[b9be60d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9be60d19c5da7b3b4aab8c3e7ed44e94dff3341)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-cfd3f12f)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-cfd3f12f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-11 07:17 UTC, opbld30 commented
Docs Build status updates of commit _[01bc1a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01bc1a9ad85b9d61392bdb324874a5974f6b9466)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-c212f8db)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-c212f8db"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-11 07:27 UTC, opbld30 commented
Docs Build status updates of commit _[926e54a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/926e54a7251e30c594a39f9bfdcac695d2b52ab0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-e3752000)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-e3752000"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-11 09:07 UTC, opbld34 commented
Docs Build status updates of commit _[89ae56a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89ae56ad373c1fe70f19370810d89cbd3189ce7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-1ba46e79)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-1ba46e79"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-11 09:08 UTC, opbld32 commented
Docs Build status updates of commit _[75e517a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/75e517ad7a78f4131f15142015491731b8c6bd84)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-b6254b0c)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-b6254b0c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-11 09:13 UTC, opbld34 commented
Docs Build status updates of commit _[8b1e5d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b1e5d485e791ec8dd51400ba2aeca337d4f3a0e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-0fd9cd44)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-0fd9cd44"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-11 09:26 UTC, opbld31 commented
Docs Build status updates of commit _[e95e8cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e95e8cc9108c8ec658646f3c6b4c60d65f06b550)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-9d4fe99f)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-9d4fe99f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-update-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-delete-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spe [...]

2020-11-11 09:45 UTC, opbld34 commented
Docs Build status updates of commit _[119cda6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/119cda6fddd42a2589b5c8efbd6528f3a66f05b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-5067010a)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-5067010a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-add-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: / [...]

2020-11-11 10:00 UTC, opbld34 commented
Docs Build status updates of commit _[e101245](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1012458e757f579b5dd998376913e7dbdf2566c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-d7001c00)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-d7001c00"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-get-members?view=graph-rest-beta`````
 - **Line 2 [...]

2020-11-11 10:03 UTC, opbld34 commented
Docs Build status updates of commit _[087c90f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/087c90fef6aa3a5ebd6a312d04193f1525f29993)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-3dd85368)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-3dd85368"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** [...]

2020-11-11 10:08 UTC, opbld31 commented
Docs Build status updates of commit _[4660551](https://github.com/microsoftgraph/microsoft-graph-docs/commits/466055187e6e489572b6bb909f6e91eee11c3f05)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-e1b6b480)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-e1b6b480"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** [...]

2020-11-16 09:34 UTC, opbld33 commented
Docs Build status updates of commit _[d9ddbdd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9ddbdd51d32e79e74ef473a5265d648254607f2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9e75abc0)

<a id="9e75abc0"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011160933488968-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cy0tUq0Hx83yYXgJDdW10%2FG5z5oISEYV97%2F%2BPKodLjk%3D&st=2020-11-16T09%3A29%3A09Z&se=2020-12-17T09%3A34%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 09:37 UTC, opbld30 commented
Docs Build status updates of commit _[40fd9c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40fd9c9cd2f187b007024a56530872c129f99e10)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6b86d82c)

<a id="6b86d82c"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011160936535307-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SVBjhJGPV5kVLd4EaKhEpOEZzp%2BdzaeK00MtB8gQ9bI%3D&st=2020-11-16T09%3A32%3A57Z&se=2020-12-17T09%3A37%3A57Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 09:38 UTC, opbld33 commented
Docs Build status updates of commit _[1eae3af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1eae3af003c2df72170814fe0d141579bd99946b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d4b9ad72)

<a id="d4b9ad72"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011160937320337-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=csV0HDBGzy2pyj8G2j8%2BrTuJx15KckMn1q7TLVZtxfU%3D&st=2020-11-16T09%3A33%3A21Z&se=2020-12-17T09%3A38%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 09:40 UTC, opbld34 commented
Docs Build status updates of commit _[eae79f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eae79f9e5391eb02c36ca96245fc874cd9014e92)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1ea66e49)

<a id="1ea66e49"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011160940299018-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P0GXJ2PTvyPuzjyJ4tIXilo%2Fo9kExMaNdUpa%2BsgRn4g%3D&st=2020-11-16T09%3A35%3A51Z&se=2020-12-17T09%3A40%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 09:41 UTC, opbld30 commented
Docs Build status updates of commit _[d2f677a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2f677a16b540c5ed73bf79a76a924cc524ed863)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ab49d415)

<a id="ab49d415"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011160941016804-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8BwZ02gmmCQCQfCEmJREB1HAPhq%2BVw5PET6qFpeBv5k%3D&st=2020-11-16T09%3A36%3A23Z&se=2020-12-17T09%3A41%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 09:44 UTC, opbld34 commented
Docs Build status updates of commit _[1c294fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c294fdf880a89d58a58a3c95fe401c05ae29427)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c1cd138f)

<a id="c1cd138f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011160943137694-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q0gNPBctCmdcBuJYRBhQPJm3ZvV%2BgzndProyrAYXwck%3D&st=2020-11-16T09%3A39%3A17Z&se=2020-12-17T09%3A44%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 09:44 UTC, opbld30 commented
Docs Build status updates of commit _[80fffa0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80fffa097bb79a8bc1eb6daf741f1ce0b7fe43cf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e76cf90d)

<a id="e76cf90d"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011160943279959-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sKXeFO6bRcAuIQ71t5bzHR8e2iPJ32apgEAEkc%2B%2F1%2F4%3D&st=2020-11-16T09%3A39%3A38Z&se=2020-12-17T09%3A44%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 09:45 UTC, opbld32 commented
Docs Build status updates of commit _[5f0780f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f0780f15c4efae2873558876f461d70c5a000d6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-36b60abb)

<a id="36b60abb"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011160945263535-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Kq%2FbzbbUJ2pSbnAB9XHUJ%2Bzodg7%2FEw%2FFCq4oe%2FVVw8E%3D&st=2020-11-16T09%3A40%3A45Z&se=2020-12-17T09%3A45%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 09:46 UTC, opbld34 commented
Docs Build status updates of commit _[09ec61b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09ec61b12e6ea84ffccf17720513618562fd7be9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5553a0ba)

<a id="5553a0ba"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011160945390011-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sjfuBpagp%2F4axkOqrs6bavU89mxnKx%2FGYTpQWOIFvi4%3D&st=2020-11-16T09%3A41%3A10Z&se=2020-12-17T09%3A46%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 11:43 UTC, opbld31 commented
Docs Build status updates of commit _[88e4216](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88e42162b7271ad5009f47705fdec1f81f8540ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-2f95d263)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-2f95d263"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Di [...]

2020-11-17 03:22 UTC, opbld34 commented
Docs Build status updates of commit _[5500b3f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5500b3f37a22cbd39778640a8c487d2912a06e6e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-4926cf1d)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-4926cf1d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Di [...]

2020-11-17 03:23 UTC, Lauragra commented on api-reference/beta/api/channel-add-members.md
> +POST https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/members
This is a beta topic but the request and response examples are using v1.0. Please update to use beta.

2020-11-17 03:24 UTC, Lauragra commented on api-reference/beta/api/channel-add-members.md
> +POST https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/members
v1.0 -> beta

2020-11-17 03:24 UTC, Lauragra commented on api-reference/beta/api/channel-delete-members.md
> +DELETE https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/members/{id}
Same here - the examples should use /beta.

2020-11-17 03:26 UTC, Lauragra commented on api-reference/beta/api/channel-list-members.md
> +GET https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/members
Global: Please review all examples and update them to use beta.

2020-11-17 03:29 UTC, opbld30 commented
Docs Build status updates of commit _[6c577ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6c577ce273e446aa80f350ba63905cd230d5f163)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-dc2264a8)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-dc2264a8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Di [...]

2020-11-17 03:31 UTC, opbld31 commented
Docs Build status updates of commit _[c8bf559](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8bf559509799e06be76239580034f6c08ce1488)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-898b53de)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-898b53de"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Di [...]

2020-11-17 03:33 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | v1.0 | Added [List members of channel](/graph/api/channel-list-members?view=graph-rest-v1.0), [Get member of channel](/graph/api/channel-get-members?view=graph-rest-v1.0) [Add member to
Why do we have two separate tables for Teamwork? Please combine into one table. Also, please add an update to the Microsoft.Teams.Core.json file for the updates. All changes currently must be included in both the MD and JSON changelog files.

2020-11-17 03:35 UTC, Lauragra requested changes
Please address remaining open comments.

2020-11-17 04:06 UTC, opbld32 commented
Docs Build status updates of commit _[0b43cc9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b43cc9fae74d3b912ea3ab47b163892a759c66c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-a5669fcd)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-a5669fcd"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Di [...]

2020-11-17 04:08 UTC, opbld33 commented
Docs Build status updates of commit _[9dfde68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9dfde68ae3f49a5f8498578b63c5446490af4c5b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-b97b7552)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-b97b7552"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Di [...]

2020-11-17 04:10 UTC, opbld32 commented
Docs Build status updates of commit _[afede94](https://github.com/microsoftgraph/microsoft-graph-docs/commits/afede94c79cf7fa8d53e33a34e58164c65821f3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-98cc4061)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-98cc4061"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Di [...]

2020-11-17 04:12 UTC, opbld31 commented
Docs Build status updates of commit _[ee5ec53](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee5ec53239a9d614ba0bc3fc626af7b451a41d5d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-a6994fc5)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-a6994fc5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Di [...]

2020-11-17 04:33 UTC, opbld34 commented
Docs Build status updates of commit _[37d419e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37d419e27527b78ebc180b64840e8227823f3f29)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-6bffe5a5)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-6bffe5a5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Di [...]

2020-11-17 06:32 UTC, opbld32 commented
Docs Build status updates of commit _[0f7395d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f7395ded30da68f78ef79f95de993ab4ea959ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-3f3f4591)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-3f3f4591"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Di [...]

2020-11-17 07:27 UTC, opbld30 commented
Docs Build status updates of commit _[8e7860a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e7860ac6d4f6f05fc917d0b40f56ff5a75b5253)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-4d031f9f)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-4d031f9f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Di [...]

2020-11-17 07:33 UTC, Rajeshwari-v commented on concepts/changelog.md
> +| Addition | v1.0 | Added [List members of channel](/graph/api/channel-list-members?view=graph-rest-v1.0), [Get member of channel](/graph/api/channel-get-members?view=graph-rest-v1.0) [Add member to
One entry (beta) comes under Teamwork-November 2020.
Another entry (v1.0) comes under Teamwork-October 2020.
Updated both changelogs

2020-11-17 19:31 UTC, laujan commented
Hi @Lauragra. Can this be merged today? Thank you!

2020-11-17 19:49 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | v1.0 | Added [List members of channel](/graph/api/channel-list-members?view=graph-rest-v1.0), [Get member of channel](/graph/api/channel-get-members?view=graph-rest-v1.0) [Add member to
For the changelog entries, we include them in the month we publish the docs. If we're publishing the docs in November, they should be in one table in the applicable month. That's for customer discoverability, as they won't necessarily know to go back to a previous month to check for updates. Does that make sense?

2020-11-17 19:58 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | v1.0 | Added [List members of channel](/graph/api/channel-list-members?view=graph-rest-v1.0), [Get member of channel](/graph/api/channel-get-members?view=graph-rest-v1.0) [Add member to
Please also ensure that the month/date in the changelog.md file is consistent with that listed in the JSON file.

2020-11-17 19:59 UTC, opbld33 commented
Docs Build status updates of commit _[53289fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/53289fdbcef1327939c35bc0a7116c2b06398ebb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-39fb46d6)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-39fb46d6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-onboarding-devicecomanagementauthorityconfiguration?view=graph-rest-beta`````
 - **Line 43, Column 1**: [...]

2020-11-17 20:02 UTC, opbld30 commented
Docs Build status updates of commit _[d5a4131](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5a413137bee1d247f3850c9a98d85916a1f6e2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-9f068b59)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-9f068b59"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-onboarding-devicecomanagementauthorityconfiguration?view=graph-rest-beta`````
 - **Line 43, Column 1**: [...]

2020-11-18 04:14 UTC, opbld30 commented
Docs Build status updates of commit _[f22f200](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f22f2000783dd55a2b3a2da9453f21693bf18d01)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-31fc1316)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-31fc1316"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-onboarding-devicecomanagementauthorityconfiguration?view=graph-rest-beta`````
 - **Line 49, Column 1**: [...]

2020-11-18 04:14 UTC, Rajeshwari-v commented on concepts/changelog.md
> +| Addition | v1.0 | Added [List members of channel](/graph/api/channel-list-members?view=graph-rest-v1.0), [Get member of channel](/graph/api/channel-get-members?view=graph-rest-v1.0) [Add member to
Updated both changelogs as per comments

2020-11-18 04:22 UTC, opbld34 commented
Docs Build status updates of commit _[58756c3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58756c3a35ce74b79a4267a1591e6ff60877a3f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-0310a80b)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-0310a80b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-onboarding-devicecomanagementauthorityconfiguration?view=graph-rest-beta`````
 - **Line 49, Column 1**: [...]

2020-11-20 03:58 UTC, Lauragra commented on api-reference/beta/api/channel-add-members.md
> +Add a [conversationMember](../resources/conversationmember.md) to a [channel](../resources/channel.md). This operation is allowed only for channels with membershipType of `private`.
How is this topic different than the existing file: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-add.md

2020-11-20 04:00 UTC, Lauragra commented on api-reference/beta/api/channel-delete-members.md
> +title: "Delete member from channel"
Why are you adding files that appear to be duplicated?

2020-11-20 04:01 UTC, Lauragra commented on api-reference/beta/api/channel-get-members.md
> +title: "Get member of channel"
Already covered in existing file: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-get.md

2020-11-20 04:04 UTC, Lauragra commented on api-reference/beta/api/channel-update-members.md
> +# Update member in channel
Content appears to be covered in existing topic: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-update.md

2020-11-20 04:06 UTC, Lauragra commented on api-reference/v1.0/api/channel-add-members.md
> +title: "Add member to channel"
Same comment as per the beta files - files exist in v1.0 that cover the same content.

2020-11-20 20:07 UTC, opbld33 commented
Docs Build status updates of commit _[9d4977b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d4977b2a7279ced3d888747d0618ec54037eb5b)_: 

:clock10: **Pending**: waiting for processors ([33](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 33 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-20 20:07 UTC, opbld32 commented
Docs Build status updates of commit _[9d4977b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d4977b2a7279ced3d888747d0618ec54037eb5b)_: 

:clock10: **Pending**: waiting for processors ([33](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 33 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-20 20:09 UTC, opbld33 commented
Docs Build status updates of commit _[17fc686](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17fc686dce1c3bb558566df8e2f09cf526ba7627)_: 

:clock10: **Pending**: waiting for processors ([30](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 30 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-20 20:09 UTC, opbld31 commented
Docs Build status updates of commit _[17fc686](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17fc686dce1c3bb558566df8e2f09cf526ba7627)_: 

:clock10: **Pending**: waiting for processors ([30](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 30 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-20 20:09 UTC, opbld33 commented
Docs Build status updates of commit _[9d4977b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d4977b2a7279ced3d888747d0618ec54037eb5b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-3a5c02c5)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-3a5c02c5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Di [...]

2020-11-20 20:12 UTC, opbld34 commented
Docs Build status updates of commit _[17fc686](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17fc686dce1c3bb558566df8e2f09cf526ba7627)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-1df90fe8)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-1df90fe8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Di [...]

2020-11-20 20:14 UTC, opbld34 commented
Docs Build status updates of commit _[17fc686](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17fc686dce1c3bb558566df8e2f09cf526ba7627)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-7a351dc6)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-7a351dc6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 22:12 UTC, opbld33 commented
Docs Build status updates of commit _[4f96d42](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f96d42a560686d4cb8de16de00d3c61d96c7fb2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-7992fb1f)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-7992fb1f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 22:14 UTC, opbld34 commented
Docs Build status updates of commit _[f5ab97b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5ab97b549654d4676773cf24cfa72e42bad4b8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-bcfc1294)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-bcfc1294"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 22:16 UTC, opbld32 commented
Docs Build status updates of commit _[f5ab97b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5ab97b549654d4676773cf24cfa72e42bad4b8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-c41de6ba)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-c41de6ba"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 22:18 UTC, opbld30 commented
Docs Build status updates of commit _[8c7786f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c7786fd2d3710fbf513e3363f7f8609641a0218)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-c0c605c3)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-c0c605c3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 22:20 UTC, opbld31 commented
Docs Build status updates of commit _[8c7786f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c7786fd2d3710fbf513e3363f7f8609641a0218)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-cbd1b572)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-cbd1b572"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 22:21 UTC, opbld31 commented
Docs Build status updates of commit _[9a6c0cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a6c0cf2f567e7aba2f6e125a99599d29bf59df6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-d93d2fcd)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-d93d2fcd"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 22:23 UTC, opbld33 commented
Docs Build status updates of commit _[9a6c0cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a6c0cf2f567e7aba2f6e125a99599d29bf59df6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-d7e723e9)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-d7e723e9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 22:42 UTC, opbld34 commented
Docs Build status updates of commit _[672f0a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/672f0a767d85b70de6a1bfa5ef439c6f69c7084e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-75e21cca)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-75e21cca"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 22:44 UTC, opbld32 commented
Docs Build status updates of commit _[6a8a125](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a8a1257c403784d4eda85a178eb8d96a6e04165)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-b43bae7d)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-b43bae7d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 22:45 UTC, opbld31 commented
Docs Build status updates of commit _[6a8a125](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a8a1257c403784d4eda85a178eb8d96a6e04165)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-33b468aa)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-33b468aa"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 22:47 UTC, opbld30 commented
Docs Build status updates of commit _[3748708](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3748708efb0196c5cab903da43d79e233c254ebc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-a4024d4e)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-a4024d4e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 22:48 UTC, opbld33 commented
Docs Build status updates of commit _[dd897d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd897d276957c803e81b051a24305cf6809015fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-0f448cdd)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-0f448cdd"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 22:50 UTC, opbld32 commented
Docs Build status updates of commit _[732db20](https://github.com/microsoftgraph/microsoft-graph-docs/commits/732db2083862f80ba3136fc4da909684ee0c698b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-2ae68bc3)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-2ae68bc3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 22:58 UTC, opbld32 commented
Docs Build status updates of commit _[499b2a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/499b2a7146391c5dcf17e54e39f39138489990c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-d22fb082)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-d22fb082"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 23:01 UTC, opbld34 commented
Docs Build status updates of commit _[0f1e22a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f1e22a6f2ac1474490659684a2b9a8ac9612b0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-1cf0fe65)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-1cf0fe65"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 23:03 UTC, opbld33 commented
Docs Build status updates of commit _[0f1e22a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f1e22a6f2ac1474490659684a2b9a8ac9612b0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-dc4984f4)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-dc4984f4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 23:17 UTC, opbld32 commented
Docs Build status updates of commit _[2cae373](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2cae3732765712954d6aa06958f401f3cc624b5a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-c1b298ec)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-c1b298ec"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 23:18 UTC, opbld32 commented
Docs Build status updates of commit _[e27d0b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e27d0b547c84a5ce477424720d1302de3630fd11)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-7038156a)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-7038156a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 23:41 UTC, opbld32 commented
Docs Build status updates of commit _[7483e54](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7483e541514c4eacc1c4c429fbd5eb2067e18d38)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-12d90140)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-12d90140"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 23:43 UTC, opbld33 commented
Docs Build status updates of commit _[7483e54](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7483e541514c4eacc1c4c429fbd5eb2067e18d38)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-b543dadf)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-b543dadf"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 23:46 UTC, opbld34 commented
Docs Build status updates of commit _[89dcf88](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89dcf88a6dbd04b677bdcf1cd167e416cfbddb26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-5912dbab)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-5912dbab"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 23:52 UTC, opbld33 commented
Docs Build status updates of commit _[744fb9f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/744fb9fdfc407cf67e0558c83eafed76b4185bc4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-fe4dd6b1)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-fe4dd6b1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-20 23:54 UTC, opbld32 commented
Docs Build status updates of commit _[c2f3470](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2f3470bfa7ff38699d30ce121cbf95253239cc1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) | [Details](#user-content-de0bbbbb-03238afd)
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-03238afd"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md)
 - **Line 76, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-list-members?view=graph-rest-beta`````
 - **Line 77, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-21 00:02 UTC, opbld32 commented
Docs Build status updates of commit _[aeba2a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aeba2a724912a1db3b70abd1e28689a4af660bea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-beta&branch=pr-en-us-10261) (graph-rest-beta) |
[api-reference/v1.0/api/channel-add-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-add-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-update-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/channel-update-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-update-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/conversationmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/conversationmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmember-get?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-add-members?view=graph-rest-1.0&branch=pr-en-us-10261) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rajeshwari-1149658gaprivatechannelapi/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10261) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011210000190009-10261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Rq3DLDrv%2FBfrXO2qwuU6DQ2aOGiDIq21EmnfxMSa8%2BI%3D&st=2020-11-20T23%3A57%3A17Z&se=2020-12-22T00%3A02%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review [...]

2020-11-21 00:08 UTC, Lauragra approved these changes

2020-11-21 00:09 UTC, merged