Fixed issues in TOC.
microsoftgraph/microsoft-graph-docs pull request #10273
Opened 2020-10-12 23:39 UTC by Lauragra

2020-10-12 23:40 UTC, opbld32 commented
Docs Build status updates of commit _[c22371b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c22371b89babfe0aead5eb1ece478c1b334dbacd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-TOCfix/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-7408e429)

<a id="00685cff-7408e429"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-TOCfix/api-reference/beta/toc.yml)
 - **Line 9984, Column 13**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010122339309922-10273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VF%2Fw0oUXZIL%2FfPtIKgqOwAfaZmLAIVtaPNEO8kbpd6U%3D&st=2020-10-12T23%3A35%3A34Z&se=2020-11-12T23%3A40%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-12 23:50 UTC, opbld32 commented
Docs Build status updates of commit _[5bd5a3f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5bd5a3fa3b86dead062bfec5be9f1825d3cfdfc4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-TOCfix/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10273) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010122349291276-10273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Th%2FPtY4odz7gYRUwburaZfd487WnqfIBQlUatsbKYxQ%3D&st=2020-10-12T23%3A45%3A38Z&se=2020-11-12T23%3A50%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-13 00:01 UTC, opbld31 commented
Docs Build status updates of commit _[809a7e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/809a7e22ef4f7a3490ced9fff821a6aa7240e7c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-TOCfix/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10273) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010122359404256-10273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KxY8y%2BE4rGOwMlI74oV8NMDJ01cb7GfsafyCjddN5KM%3D&st=2020-10-12T23%3A56%3A10Z&se=2020-11-13T00%3A01%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-13 00:13 UTC, opbld31 commented
Docs Build status updates of commit _[6cb933c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6cb933c1f89ca7895b5a706c69c048b83fbc8856)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-TOCfix/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-3f4d7247)

<a id="00685cff-3f4d7247"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-TOCfix/api-reference/beta/toc.yml)
 - **Line 9947, Column 19**: **[Error-yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010130012250512-10273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c37VMXm2R85UooB%2BI78UThxBlJO0PLL3LooSfVofpu0%3D&st=2020-10-13T00%3A08%3A29Z&se=2020-11-13T00%3A13%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-13 00:15 UTC, opbld34 commented
Docs Build status updates of commit _[17abf30](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17abf3036904d1e43c2b88ad68eed08cb9c9e17a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-TOCfix/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-a4003ec4)

<a id="00685cff-a4003ec4"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-TOCfix/api-reference/beta/toc.yml)
 - **Line 9953, Column 13**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010130014527018-10273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=q1q6XQuwpnD%2FW58vgEIEMXkwXdgrgEkW5%2B4eCYxOL2E%3D&st=2020-10-13T00%3A10%3A54Z&se=2020-11-13T00%3A15%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-13 00:20 UTC, opbld32 commented
Docs Build status updates of commit _[f364340](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3643406850a581d5a6b1de20e21963ceb81b414)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-TOCfix/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10273) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010130019279228-10273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jHd1rkejqDmihJo60xr8PYdDtlm5DSaSmHERECiwnls%3D&st=2020-10-13T00%3A15%3A40Z&se=2020-11-13T00%3A20%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-13 14:59 UTC, davidmu1 approved these changes

2020-10-13 15:53 UTC, mmcla commented on api-reference/beta/toc.yml
> -          - name: B2B Authentication methods
@Lauragra - something's still amiss here. I've written out the correct yml below. The B2B and B2C sections are confusing - B2C seems to be dealing with a policy, not auth method management, and the B2B section is redundant. I've reached out to @namkedia since she made the changes earlier to see what the intent was, but I can see us removing B2B altogether and moving B2C policy to its own section in the TOC. 

```
- name: Authentication methods
  href: resources/authenticationmethods-overview.md
  items:
  - name: FIDO2 security keys
    href: resources/fido2authenticationmethod.md
    items:
    - name: List
      href: api/fido2authenticationmethod-list.md
    - name: Get
      href: api/fido2authenticationmethod-get.md
    - name: Delete
      href: api/fido2authenticationmethod-delete.md
  - name: Microsoft Authenticator Passwordless Phone Sign-In
    href: resources/passwordlessmicrosoftauthenticatorauthenticationmethod.md
    items:
    - name: List
      href: api/passwordlessmicrosoftauthenticatorauthenticationmethod-list.md
    - name: Get
      href: api/passwordlessmicrosoftauthenticatorauthenticationmethod-get.md
    - name: Delete
      href: api/passwordlessmicrosoftauthenticatorauthenticationmethod-delete.md
  - name: Phone
    href: resources/phoneauthenticationmethod.md
    items:
    - name: List
      href: api/authentication-list-phonemethods.md
    - name: Get
      href: api/phoneauthenticationmethod-get.md
    - name: Update
      href: api/phoneauthenticationmethod-update.md
    - name: Delete
      href: api/phoneauthenticationmethod-delete.md
    - name: Add
      href: api/authentication-post-phonemethods.md
    - name: Enable SMS sign-in
      href: api/phoneauthenticationmethod-enablesmssignin.md
    - name: Disable SMS sign-in
      href: api/phoneauthenticationmethod-disablesmssignin.md
  - name: Email
    href: resources/emailauthenticationmethod.md
    items:
    - name: List
      href: api/emailauthenticationmethod-list.md
    - name: Get
      href: api/emailauthenticationmethod-get.md
    - name: Update
      href: api/emailauthenticationmethod-update.md
    - name: Delete
      href: api/emailauthenticationmethod-delete.md
    - name: Add
      href: api/emailauthenticationmethod-post.md
  - name: Password
    href: resources/passwordauthenticationmethod.md
    items:
    - name: List
      href: api/authentication-list-passwordmethods.md
    - name: Get
      href: api/passwordauthenticationmethod-get.md
    - name: Reset
      href: api/passwordauthenticationmethod-resetpassword.md
    - name: Get operation status
      href: api/authenticationoperation-get.md
```

2020-10-13 15:54 UTC, mmcla requested changes
Still some errors - see my comment in the doc for details (I've left provisional code as well).

2020-10-13 20:14 UTC, mmcla commented on api-reference/beta/toc.yml
> -          - name: B2B Authentication methods
@Lauragra - I synced with @namkedia today; we agreed the above is correct, but we also need to find a home for the B2C auth methods policy. We're not sure if it should be a subsection of the other Auth methods policy or if it should stand on its own under IAM.

2020-10-16 00:22 UTC, opbld32 commented
Docs Build status updates of commit _[e216b6f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e216b6f90c3ad5220d028ca21c69bb71486d0782)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-TOCfix/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10273) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010160021289613-10273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rnWs067v0OwHAWfc0APMhgUjRCelVAQovCGk%2Bx4qTbM%3D&st=2020-10-16T00%3A17%3A48Z&se=2020-11-16T00%3A22%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 23:25 UTC, opbld34 commented
Docs Build status updates of commit _[f9cff04](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9cff04357ef44682e2d26b0f2b8cd6032e1ae28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/lauragra-TOCfix/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10273) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010162323452192-10273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yXxnCri7q4TRFHZA%2BuSgz9RQRrZkKfvIk0Tmw9f7vpY%3D&st=2020-10-16T23%3A20%3A03Z&se=2020-11-16T23%3A25%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 23:27 UTC, merged