Backfilled documentation for meeting role
microsoftgraph/microsoft-graph-docs pull request #10277
Opened 2020-10-13 05:00 UTC by frankpeng7

Backfilled documentation for meeting role which is missing in [this PR](https://github.com/microsoftgraph/microsoft-graph-docs/pull/9630)

2020-10-13 05:01 UTC, frankpeng7 commented on api-reference/beta/resources/meetingparticipants.md
> +Question to @jsandoval-msft: according to Graph Review results we are deprecating "producers" and "contributors" and using "role" inside "attendees"/"organizer" to differentiate the role of meeting p
@jsandoval-msft can you help clarify this?

2020-10-13 05:01 UTC, opbld30 commented
Docs Build status updates of commit _[1b41ebf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b41ebf4f958443efab36533f9557c4b36c9cf65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/resources/meetingparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/resources/meetingparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingparticipantinfo?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/resources/meetingparticipants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/resources/meetingparticipants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingparticipants?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010130500258210-10277%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Giw6yxRifNx1%2BAmwUPB6UPrRieJNNiTZUJcNyYH%2BfTc%3D&st=2020-10-13T04%3A56%3A50Z&se=2020-11-13T05%3A01%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-13 20:26 UTC, jsandoval-msft commented on api-reference/beta/resources/meetingparticipants.md
> +Question to @jsandoval-msft: according to Graph Review results we are deprecating "producers" and "contributors" and using "role" inside "attendees"/"organizer" to differentiate the role of meeting p
@frankpeng7, if it's not used I'd bias toward deprecating it to minimize confusion in the interface. When you say "in most cases they are null", what are the cases where they would not be null?

2020-10-13 23:34 UTC, frankpeng7 commented on api-reference/beta/resources/meetingparticipants.md
> +Question to @jsandoval-msft: according to Graph Review results we are deprecating "producers" and "contributors" and using "role" inside "attendees"/"organizer" to differentiate the role of meeting p
@jsandoval-msft so if the user is querying a broadcast meeting/live event with the meeting ID generated, the producers and contributors' info will go in those two properties (instead of going in attendee and role marked as "producer"/"contributor"

2020-10-14 02:41 UTC, Lauragra commented on api-reference/beta/resources/onlinemeeting.md
> +>**Note**: If the value of **allowedPresenters** is `roleIsPresenter`, you must specify **role** for each attendee.
I'm not sure this is clear - what is **role** referring to?

2020-10-14 02:41 UTC, opbld34 commented
Docs Build status updates of commit _[e15a15a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e15a15a17d8260789ed159f369c7da047ee3c1dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/resources/meetingparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/resources/meetingparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingparticipantinfo?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/resources/meetingparticipants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/resources/meetingparticipants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingparticipants?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010140240283616-10277%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SVgi4wDNTOWmFODN29bqPp0P6%2FXrDj8hSIGFLH%2FMO38%3D&st=2020-10-14T02%3A36%3A49Z&se=2020-11-14T02%3A41%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-14 02:42 UTC, Lauragra commented on api-reference/beta/resources/meetingparticipants.md
> +Question to @jsandoval-msft: according to Graph Review results we are deprecating "producers" and "contributors" and using "role" inside "attendees"/"organizer" to differentiate the role of meeting p
Please remove this. As a best practice, don't include internal comments/questions within the text of the topic.

2020-10-14 02:45 UTC, opbld30 commented
Docs Build status updates of commit _[4f0022b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f0022b57cc7a44b7a7be80ea4c6af2bf3858876)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/resources/meetingparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/resources/meetingparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingparticipantinfo?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/resources/meetingparticipants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/resources/meetingparticipants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingparticipants?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010140244147251-10277%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZBmWAU4HFCWvywkY156cKp17pjBqm7dO7vCKMfM61js%3D&st=2020-10-14T02%3A40%3A40Z&se=2020-11-14T02%3A45%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-14 02:50 UTC, opbld31 commented
Docs Build status updates of commit _[6d59070](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d59070c486c1946cd443805c4d87a2531b3a1f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/resources/meetingparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/resources/meetingparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingparticipantinfo?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/resources/meetingparticipants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/resources/meetingparticipants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingparticipants?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010140249266562-10277%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zct7ruHXueTCAGh8utsvzXAWCU2SxRA4LuH3aSWR4n8%3D&st=2020-10-14T02%3A45%3A58Z&se=2020-11-14T02%3A50%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-14 02:51 UTC, Lauragra requested changes
Please take a look at comments; thanks!

2020-10-14 02:52 UTC, opbld31 commented
Docs Build status updates of commit _[411caa5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/411caa54869744b309305b3186d5bd8561c8913c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/resources/meetingparticipantinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/resources/meetingparticipantinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingparticipantinfo?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/resources/meetingparticipants.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/resources/meetingparticipants.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingparticipants?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/meeting-role/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10277) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010140250513161-10277%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ahBzZIDtLlvla3O9TvzogGV5lu1oaCVKLcfiCBrFkfw%3D&st=2020-10-14T02%3A47%3A24Z&se=2020-11-14T02%3A52%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-14 02:52 UTC, Lauragra requested changes
Please include an update to the changelog for the new property. You'll need to update the MD file and the JSON file.

2020-10-14 17:34 UTC, jsandoval-msft commented on api-reference/beta/resources/meetingparticipants.md
> +Question to @jsandoval-msft: according to Graph Review results we are deprecating "producers" and "contributors" and using "role" inside "attendees"/"organizer" to differentiate the role of meeting p
I am aware of one large partner that is using Live Events, let me ping the PM managing the relationship to make sure they are not using this field for anything.

2020-10-14 20:17 UTC, jsandoval-msft commented on api-reference/beta/resources/meetingparticipants.md
> +Question to @jsandoval-msft: according to Graph Review results we are deprecating "producers" and "contributors" and using "role" inside "attendees"/"organizer" to differentiate the role of meeting p
I've notified our partner contact, and clarified that there is no change from current behavior.

2020-10-14 20:17 UTC, jsandoval-msft approved these changes

2020-10-20 18:19 UTC, frankpeng7 commented on api-reference/beta/resources/onlinemeeting.md
> +>**Note**: If the value of **allowedPresenters** is `roleIsPresenter`, you must specify **role** for each attendee.
it's referring to the **role** property in **meetingParticipantInfo**. I've updated this to make it easier to read

2020-10-21 00:13 UTC, Lauragra approved these changes

2020-10-21 00:17 UTC, merged