CreateLink Api
microsoftgraph/microsoft-graph-docs pull request #10286
Opened 2020-10-13 22:50 UTC by learafa

adding docs for createLink api changes

2020-10-13 22:52 UTC, opbld32 commented
Docs Build status updates of commit _[17b611a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17b611af8260c2e94445bf93cbcc8771353692d2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10286) | [Details](#user-content-de0bbbbb-a3b280e7)
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |

<a id="de0bbbbb-a3b280e7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/concepts/changelog.md)
 - **Line 20, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/listItem-createLink?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/listItem?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/listItem-createLink?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 20, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/listItem?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 26, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 27, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 28, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 29, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/authorizationpolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/b2cauthenticationmethodspolicy?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-get?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 30, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/b2cauthenticationmethodspolicy-update?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/delegatedpermissionclassification?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 45, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 57, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 58, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 59, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 60, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 66, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-get-file?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 67, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-list-jobs?view=graph-rest-beta NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-apps-win32lobapp?view=graph-rest-1.0 NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 74, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/a [...]

2020-10-13 22:54 UTC, learafa commented
TODO: Merge listitem-createlink and driveitem-createlink to one file.

2021-01-27 23:20 UTC, opbld34 commented
Docs Build status updates of commit _[17b611a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17b611af8260c2e94445bf93cbcc8771353692d2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-654fe656)

<a id="654fe656"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101272319341644-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7rq8wLEgv4iuKCYRU0J279cv%2FlU%2FCqvCNIKvIkhYwBU%3D&st=2021-01-27T23%3A15%3A43Z&se=2021-02-27T23%3A20%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 23:55 UTC, opbld33 commented
Docs Build status updates of commit _[c2e9e27](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2e9e27f3f5a4e50c015ca8e7539e89244b33c35)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101272353574903-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4In8BJwMQVXJZH%2FXS5y1UVXgc6ninKuiyb0kiYhwNFg%3D&st=2021-01-27T23%3A50%3A29Z&se=2021-02-27T23%3A55%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-29 20:36 UTC, opbld33 commented
Docs Build status updates of commit _[efb1818](https://github.com/microsoftgraph/microsoft-graph-docs/commits/efb181855fc756502550a6a5f8aabe1f3410e612)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104292035372159-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8klVjiS%2BOy1m5qHxai6Z4ZOfm2cszUwWO33lAkrgmlg%3D&st=2021-04-29T20%3A31%3A55Z&se=2021-05-30T20%3A36%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-29 20:51 UTC, opbld34 commented
Docs Build status updates of commit _[70c4c05](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70c4c05ac3c0dfa240805b900661e0eb159e1e32)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104292050372003-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KgRHCGE2mDiECNk%2BJ4unKyJ%2BgWJj3mFogdaw8LY8g6M%3D&st=2021-04-29T20%3A46%3A52Z&se=2021-05-30T20%3A51%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-29 21:05 UTC, opbld32 commented
Docs Build status updates of commit _[877397d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/877397da0a2b3d24b8c4a43eb01263a7809a4951)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104292103511921-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1Lsdp8Oi8icFFogmOIzS%2FsV49pZ7tYYAdmG9fA6YMtg%3D&st=2021-04-29T21%3A00%3A07Z&se=2021-05-30T21%3A05%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-29 21:11 UTC, opbld32 commented
Docs Build status updates of commit _[9394df0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9394df024f4e7300da89ee5afc0fa1f67c8d5256)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104292110228158-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jqWQBGSwGQXyQ1cmGF6I7BrtFj61xx5YU5lJnisOhxE%3D&st=2021-04-29T21%3A06%3A39Z&se=2021-05-30T21%3A11%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-29 21:16 UTC, opbld31 commented
Docs Build status updates of commit _[0b8a5e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b8a5e3219d0922be5d65709dbd464edb3af42c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104292115044582-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FZiKd9K1T44UAPjM56LPc0XVR%2BpSF51w%2BFM4yHxj0lE%3D&st=2021-04-29T21%3A11%3A18Z&se=2021-05-30T21%3A16%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-10 23:12 UTC, BarryShehadeh requested changes

2021-05-10 23:12 UTC, BarryShehadeh commented on api-reference/beta/resources/listitem.md
> +[CreateLink]: ../api/listitem-createlink.md
You need to update the [toc](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml) of listItems to include CreateLink.

2021-05-11 21:11 UTC, BarryShehadeh approved these changes

2021-05-28 01:02 UTC, opbld31 commented
Docs Build status updates of commit _[5d44a23](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d44a231b48c5700a0c8fa4794a020ec7fbf61eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280100566928-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RL47gDaDKpguuUGY6MI9Nk%2BLQCVfqef9W98fOBUmJC8%3D&st=2021-05-28T00%3A57%3A47Z&se=2021-06-28T01%3A02%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 02:12 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-createlink.md
> +|type|String|Optional.The password of the sharing link that is set by the creator.|
Please fix the description. It looks like you described the password instead of the type :)

2021-05-28 02:26 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-createlink.md
> +| adminDefault   | Creates the admin-allowed default link to the DriveItem. Only available in OneDrive for Business and SharePoint. The policy is enforced for the organization by the admin |
Lines 74 and 75: Can we use an easier term instead of admin-allowed? It can be difficult for unexperienced readers. 
For example: "Creates a link for administrator use only", or "Creates a link with permissions delimited by the administrator of the organization".

A description that explains in simple words what the feature is about. Please let me read your comments.

2021-05-28 02:29 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-createlink.md
>  The following example requests a sharing link to be created for the DriveItem specified by {itemId} in the user's OneDrive.
Please include an h3 header after line 93 with:
Example 1: Create a link to share a drive item

2021-05-28 02:30 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-createlink.md
>  The following example requests a sharing link to be created for the DriveItem specified by {itemId} in the user's OneDrive.
Since we are using more than 1 example, please use h4 for the Request and Response sections inside examples.

2021-05-28 02:33 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-createlink.md
>  POST /me/drive/items/{itemId}/createLink
Please use real looking IDs in the examples.

We try to use placeholders in the HTTP request section, but real looking IDs in the examples. When you do, please include the sampleKeys parameter in the API Doctor block. Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor?anchor=json-element-descriptions

2021-05-28 02:42 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-createlink.md
> +* If both scope and type are not provided, a readily available link is provided based on the callers ability on the item and policy is enforced for the organization.
Can we re-phrase this line with simple words? For example:
If both scope and type are not provided, a read-only (?) link is generated for the drive item. 

May I please clarify the purpose of the line? I may be able to provide a better suggestion to improve this line.

2021-05-28 02:43 UTC, isvargasmsft commented on api-reference/beta/api/listitem-createlink.md
> +description: "You can use createLink action to share a ListItem via a sharing link."
Please use listItem in camel caps.

2021-05-28 02:43 UTC, isvargasmsft commented on api-reference/beta/api/listitem-createlink.md
> +You can use **createLink** action to share a [ListItem](../resources/listitem.md) via a sharing link.
Please use camel caps in listItem.

2021-05-28 02:54 UTC, isvargasmsft commented on api-reference/beta/api/listitem-createlink.md
> +The **createLink** action will create a new sharing link if the specified link type doesn't already exist for the calling application.
Please use present tense to describe the method. For example:
This method creates a new link to share a listItem. If the **listItem** already has a link with the same type, the method returns an error message.

2021-05-28 02:58 UTC, isvargasmsft commented on api-reference/beta/api/listitem-createlink.md
> +ListItem resources inherit sharing permissions from their ancestors.
1. The phrase "inherit sharing permissions" is difficult to understand for non-native readers.
2. I am not sure if using the word "ancestors" in this context represents a D&I issue. Can we use parent folders instead?
3. When we mention a resource, entity, method, name in a UI or such, please include the reference link the first time and **bold** the subsequent mentions.

2021-05-28 03:11 UTC, isvargasmsft commented on api-reference/beta/api/listitem-createlink.md
> +|type|String|Optional.The password of the sharing link that is set by the creator.|
Please fix the description. Include the description for type instead of the password.

2021-05-28 03:16 UTC, isvargasmsft commented on api-reference/beta/api/listitem-createlink.md
> +| adminDefault   | Creates the admin-allowed default link to the ListItem. Only available in OneDrive for Business and SharePoint. The policy is enforced for the organization by the admin |
Please keep lines 73 and 74 consistent with the fix from my [previous comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/10286/files#r641155950) in the other doc.

2021-05-28 03:24 UTC, isvargasmsft commented on api-reference/beta/api/listitem-createlink.md
> +The following example requests a sharing link to be created for the DriveItem specified by {itemId} in the user's OneDrive.
Let's use the proper format for the Examples section. 
Please use imperatives in the example titles and, since we are sharing more than 1 example, please use this format:

##Examples
### Example 1: Create a link to share a listItem. 
#### Request 
Here the example
### Response 
Here the response
### Example 2: Create a link to share a listItem only with people in your organization.

etc

2021-05-28 03:24 UTC, isvargasmsft commented on api-reference/beta/api/listitem-createlink.md
> +The following example requests a sharing link to be created for the DriveItem specified by {itemId} in the user's OneDrive.
That is:
H2 for Examples
H3 for Example 1: title
H4 for Request and Response

2021-05-28 03:31 UTC, isvargasmsft commented on api-reference/beta/api/listitem-createlink.md
> +* If both scope and type are not provided, a readily available link is provided based on the callers ability on the item and policy is enforced for the organization.
Please keep this line consistent with the fix in the other doc. See [my previous comment](https://github.com/microsoftgraph/microsoft-graph-docs/pull/10286/files#r641170561) for reference.

2021-05-28 03:48 UTC, isvargasmsft commented on changelog/Microsoft.FileServices.json
> +          "Target": "createLink, driveItem"
1. ChangedApiName should be type. 
2. Please rephrase the description for effiency: Changed the **type** property in [createLink] (link) method from required to optional.
3. Target accepts just 1 value, createLink in this case. 

Please follow the example 8 here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-examples

2021-05-28 03:53 UTC, isvargasmsft commented on changelog/Microsoft.FileServices.json
> +          "ChangedApiName": "listItem,createLink",
1. I think ApiChange is method in this case, since we are adding a new method, not a new resource. 
2. Please enter only one API element for each record to support proper filtering, createLink in this case. 
Guidelines here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-properties

2021-05-28 03:55 UTC, isvargasmsft commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [CreateLink-beta](https://docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta) method on a [listItem](https://docs.microsoft.com/en-us/gra
For the description: I have to confirm whether adding a method works similar to adding a resource. In the meantime, please follow the [guidelines](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-properties) and the example 8 [here](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-examples).

2021-05-28 03:56 UTC, isvargasmsft commented on changelog/Microsoft.FileServices.json
> +          "Target": "createLink, listItem"
Please use a single value in Target. Please let me confirm whether it is createLink (the method being added) or listItem (the resource that will own the method). 
@Lauragra what do you think?

2021-05-28 04:00 UTC, isvargasmsft commented on changelog/Microsoft.FileServices.json
> +    "WorkloadArea": "Files, Sites and lists",
WorkloadArea: please enter a single value here as well. Sites and lists in this case. 
Since this update covers 2 workload areas, I'd recommend creating 2 separate changelists.

2021-05-28 04:04 UTC, isvargasmsft requested changes
@learafa thank you very much for your work in this PR. Very nice job. 

In summary: 
1. Please use simple words and terms, easy to understand for unexperienced readers and non-native readers. 
2. In the description and the first line we try to keep it as simple as possible, using fewer words to describe the purpose of the document. 
3. Please fix the structure of the Examples section.
4. Please follow the guidelines regarding the changelog entries. 

Please feel free to ping me on the side if you have any questions. 

Kind regards, 

Isaac Vargas

2021-05-28 16:02 UTC, k-tsoi commented on api-reference/beta/api/driveitem-createlink.md
>  POST /me/drive/items/{itemId}/createLink
I don't believe this needs keyProperty as this is not an entity type

2021-06-01 17:47 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +          "Target": "createLink, driveItem"
Yes, both the ChangeApiName and the Target values here should be driveItem.

2021-06-01 17:48 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +          "ChangedApiName": "listItem,createLink",
The change is happening on listItem, correct? I think that's what you want to list for ChangedApiName.

2021-06-01 17:57 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +          "Description": "Changed **type** (string) property to be optional in [CreateLink-beta](https://docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta) action on a [dri
Please refer to the method as [createLink], with a lowercase c and without beta in link text - the version is listed in the table already. Please make this update in all ChangeList entries.

2021-06-01 18:00 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [CreateLink-beta](https://docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta) method on a [listItem](https://docs.microsoft.com/en-us/gra
For the description, please update to "Added the [createLink] method to the [listItem] resource."

2021-06-02 18:47 UTC, k-tsoi commented on api-reference/beta/api/driveitem-createlink.md
> +|type|String|Optional.The password of the sharing link that is set by the creator.|
updated

2021-06-02 18:47 UTC, opbld32 commented
Docs Build status updates of commit _[593fe6a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/593fe6af27011d112c203a1ea0412b29800a6644)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106021846128868-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FejTiCAD0bX5PHBZGpDyoLhecVkvJ5bx%2Bvk6UtpWGRI%3D&st=2021-06-02T18%3A42%3A54Z&se=2021-07-03T18%3A47%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 18:48 UTC, k-tsoi commented on api-reference/beta/api/driveitem-createlink.md
> +| adminDefault   | Creates the admin-allowed default link to the DriveItem. Only available in OneDrive for Business and SharePoint. The policy is enforced for the organization by the admin |
updated

2021-06-02 18:49 UTC, k-tsoi commented on api-reference/beta/api/driveitem-createlink.md
> +| adminDefault   | Creates the admin-allowed default link to the DriveItem. Only available in OneDrive for Business and SharePoint. The policy is enforced for the organization by the admin |
@isvargasmsft does this make more sense, let me know if it should be reworked some more

2021-06-02 18:49 UTC, k-tsoi commented on api-reference/beta/api/driveitem-createlink.md
>  The following example requests a sharing link to be created for the DriveItem specified by {itemId} in the user's OneDrive.
changed header used and add example #

2021-06-02 18:51 UTC, k-tsoi commented on api-reference/beta/api/driveitem-createlink.md
> +* If both scope and type are not provided, a readily available link is provided based on the callers ability on the item and policy is enforced for the organization.
reworded, does the new scentence make sense?

2021-06-02 18:52 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +description: "You can use createLink action to share a ListItem via a sharing link."
noted, changed in the rest of the docs

2021-06-02 18:52 UTC, opbld34 commented
Docs Build status updates of commit _[bb91329](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb913296c9a0cd94f0cb8a4bb34cedfbc893154d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106021851045174-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C42QFaWxhlUzfrenT7UXHzvnh7uSvjR0x6Lmb6Yx6bw%3D&st=2021-06-02T18%3A47%3A24Z&se=2021-07-03T18%3A52%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 18:52 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +You can use **createLink** action to share a [ListItem](../resources/listitem.md) via a sharing link.
updated

2021-06-02 19:08 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +ListItem resources inherit sharing permissions from their ancestors.
"inherit" is the best word to be used in the scenario. 
Do you have any suggestions as to what should be used instead?

2021-06-02 19:09 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +|type|String|Optional.The password of the sharing link that is set by the creator.|
fixed

2021-06-02 19:09 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +| adminDefault   | Creates the admin-allowed default link to the ListItem. Only available in OneDrive for Business and SharePoint. The policy is enforced for the organization by the admin |
fixed

2021-06-02 19:09 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +The following example requests a sharing link to be created for the DriveItem specified by {itemId} in the user's OneDrive.
done

2021-06-02 19:12 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +* If both scope and type are not provided, a readily available link is provided based on the callers ability on the item and policy is enforced for the organization.
updated

2021-06-02 19:12 UTC, k-tsoi commented on changelog/Microsoft.FileServices.json
> +          "Description": "Changed **type** (string) property to be optional in [CreateLink-beta](https://docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta) action on a [dri
updated

2021-06-02 19:13 UTC, k-tsoi commented on changelog/Microsoft.FileServices.json
> +          "Target": "createLink, driveItem"
updated target to be driveItem and changeAPIName to be type (as the type parameter is being modified in this case)

2021-06-02 19:13 UTC, k-tsoi commented on changelog/Microsoft.FileServices.json
> +          "ChangedApiName": "listItem,createLink",
updated both changedAPIName and Target to be listItem

2021-06-02 19:14 UTC, k-tsoi commented on changelog/Microsoft.FileServices.json
> +          "Description": "Added the [CreateLink-beta](https://docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta) method on a [listItem](https://docs.microsoft.com/en-us/gra
modified

2021-06-02 19:14 UTC, k-tsoi commented on changelog/Microsoft.FileServices.json
> +    "WorkloadArea": "Files, Sites and lists",
separated out into 2 changelists

2021-06-03 02:42 UTC, Lauragra commented on api-reference/beta/api/driveitem-createlink.md
> +**Note:** The response object shown here might be shortened for readability.
Please add the ">" to format this as a note.

2021-06-03 02:47 UTC, Lauragra commented on api-reference/beta/api/driveitem-createlink.md
> +* If both scope and type are not provided, the link created will be determined based on the callers ability on the item and policy enforced for the organization that is determined by the administrato
Please clarify this sentence, it's currently a run-on. You can likely remove the "of the organization" phrase as that should be clear from the context. You'll want to form the possessive of callers; should be "caller's". Is "ability on the item" going to be clear, or would it be more clear to say "caller's permissions"?

2021-06-03 02:48 UTC, Lauragra commented on api-reference/beta/api/listitem-createlink.md
> +The **createLink** action can be used to create a sharing link for a [listItem](../resources/listitem.md).
API topics should begin with an imperative verb, so, revise the first sentence to be "Create a sharing link for a [listItem]."

2021-06-03 02:50 UTC, Lauragra commented on api-reference/beta/api/listitem-createlink.md
> +In the request body, supply JSON representation of the parameters.
Add the missing article "a" after "supply". For consistency/clarity, a better word choice than "supply" would be "provide".

2021-06-03 02:51 UTC, Lauragra commented on api-reference/beta/api/listitem-createlink.md
> +|type|String|Optional.Optional.The type of sharing link to create. |
Delete the second Optional. Also, for Description, please move Optional to the end so the description comes first. For values, please format them with tic marks (`).

2021-06-03 02:52 UTC, Lauragra commented on api-reference/beta/api/listitem-createlink.md
> +|expirationDateTime|DateTimeOffset|Optional. A String with format of yyyy-MM-ddTHH:mm:ssZ of DateTime indicates the expiration time of the permission.|
String should be lowercase in the description. It looks like there should be a period before the word indicates and that should be the start of a new sentence.

2021-06-03 02:52 UTC, Lauragra commented on api-reference/beta/api/listitem-createlink.md
> +| view           | Creates a read-only link to the Item.                                                                        |
Global: Please lowercase Item throughout the table, it's not a proper noun.

2021-06-03 02:53 UTC, Lauragra commented on api-reference/beta/api/listitem-createlink.md
> +If successful, this method returns a single [Permission](../resources/permission.md) resource in the response body that represents the requested sharing permissions.
Resource names are lower camel case; please lowercase Permission.

2021-06-03 02:54 UTC, Lauragra commented on api-reference/beta/api/listitem-createlink.md
> +# [HTTP](#tab/http)
Global: Remove this H1; it is added via our snippet automation process after we merge into main.

2021-06-03 02:54 UTC, Lauragra commented on api-reference/beta/api/listitem-createlink.md
> +**Note:** The response object shown here might be shortened for readability.
Please format with a ">" to make it a note.

2021-06-03 02:54 UTC, Lauragra commented on api-reference/beta/api/listitem-createlink.md
> +**Note:** Embed links are only supported for OneDrive personal.
Format with ">".

2021-06-03 15:55 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +# [HTTP](#tab/http)
Noted removed all "# [HTTP](#tab/http)" from documents

2021-06-03 15:55 UTC, k-tsoi commented on api-reference/beta/api/driveitem-createlink.md
> +**Note:** The response object shown here might be shortened for readability.
noted added ">" in front of all notes

2021-06-03 16:34 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +The **createLink** action can be used to create a sharing link for a [listItem](../resources/listitem.md).
noted, changed

2021-06-03 16:35 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +In the request body, supply JSON representation of the parameters.
modified

2021-06-03 16:44 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +| view           | Creates a read-only link to the Item.                                                                        |
changed Item to lowercase

2021-06-03 16:44 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +|expirationDateTime|DateTimeOffset|Optional. A String with format of yyyy-MM-ddTHH:mm:ssZ of DateTime indicates the expiration time of the permission.|
changed

2021-06-03 16:47 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +|type|String|Optional.Optional.The type of sharing link to create. |
noted updated

2021-06-03 16:47 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +If successful, this method returns a single [Permission](../resources/permission.md) resource in the response body that represents the requested sharing permissions.
updated resource names to lowercamelcase

2021-06-03 16:47 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +**Note:** The response object shown here might be shortened for readability.
modified

2021-06-03 16:47 UTC, k-tsoi commented on api-reference/beta/api/listitem-createlink.md
> +**Note:** Embed links are only supported for OneDrive personal.
updated

2021-06-03 19:14 UTC, k-tsoi commented on api-reference/beta/api/driveitem-createlink.md
> +* If both scope and type are not provided, the link created will be determined based on the callers ability on the item and policy enforced for the organization that is determined by the administrato
updated sentence, does it work better?

2021-06-03 23:13 UTC, opbld33 commented
Docs Build status updates of commit _[f42c3f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f42c3f87274b152d478408540d922129f7c6f1f4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106032312037721-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=t6Z65UmQfWKyKRhUm2jEiebO3yPVVYdPzUYtlWOcWUo%3D&st=2021-06-03T23%3A08%3A32Z&se=2021-07-04T23%3A13%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-04 15:28 UTC, opbld34 commented
Docs Build status updates of commit _[c6ae4cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c6ae4cb56351d9e84e4b388a46513090f9d706d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106041527149184-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Rj%2FL9Zxat94Zfys%2F59uw6pNqJyX8uTzKYkeyPD288wM%3D&st=2021-06-04T15%3A23%3A29Z&se=2021-07-05T15%3A28%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 17:27 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-createlink.md
>  POST /me/drive/items/{itemId}/createLink
Please use real looking IDs in the examples. By `sampleKeys` property I mean: 
sampleKeys: Specify this for example HTTP requests that include one or more ID values indexing into collections in the request query. This property is a collection of strings, each string representing an ID value in the example request. For more information about specifying real ID values in examples, see the section ID values in example requests.

Details here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor?anchor=json-element-descriptions

2021-06-07 17:28 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-createlink.md
>  ```http
Please use real looking IDs in the example here as well. It doesn't have to be a real ID, but one that looks like a real one.

2021-06-07 21:14 UTC, BarryShehadeh commented on api-reference/beta/api/driveitem-createlink.md
>  POST /me/drive/items/{itemId}/createLink
Hey @isvargasmsft, I work primarily in API Doctor development. 
We've never actually used sampleKeys, as I don't think API Doctor utilize them anymore.
Even in the Graph Doc Stub generator, I believe it still use sites/{siteId}
Is that a new requirement? And I'm wondering what's the reasoning behind it.

2021-06-08 20:03 UTC, isvargasmsft commented on api-reference/beta/api/driveitem-createlink.md
>  POST /me/drive/items/{itemId}/createLink
We try to use real looking IDs in the examples because it is easier for new developers to understand what they are looking for when searching for an ID. People rely on documentation mostly when they are learning, so we try to keep examples as clear and helpful as possible. 

The HTTP section already has the lines with placeholders so, we use examples to show how a real ID would look like. This is a recent discussion we had.

2021-06-08 23:02 UTC, opbld34 commented
Docs Build status updates of commit _[25aa691](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25aa6912b1818884d3acffbd567cbaa11c58397e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106082301069337-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mdw2Jq1sMnj250%2B0oXwocVhy4kPLIEalBp2sjBT4SpU%3D&st=2021-06-08T22%3A57%3A32Z&se=2021-07-09T23%3A02%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 23:04 UTC, k-tsoi commented on api-reference/beta/api/driveitem-createlink.md
>  POST /me/drive/items/{itemId}/createLink
@isvargasmsft I have updated the doc with sample IDs, is this correct?

2021-06-14 17:12 UTC, opbld31 commented
Docs Build status updates of commit _[3fb54d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fb54d58b4bb04301ecc4a15d0c6935871c73002)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106141710453991-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8mVLaSKNzwmSE299My5kr9Cgz%2BbWoTXGouxEI3wDXUU%3D&st=2021-06-14T17%3A07%3A19Z&se=2021-07-15T17%3A12%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 21:00 UTC, opbld30 commented
Docs Build status updates of commit _[0b341e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b341e11dd0e9088bbfbbf8b57fa89862faf8883)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106142059022240-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QtPUEKkK6qj7Vvax0vr4gP%2FSuKhlFbUXzaO1I%2BwX5yY%3D&st=2021-06-14T20%3A55%3A32Z&se=2021-07-15T21%3A00%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 22:12 UTC, isvargasmsft approved these changes

2021-06-15 03:02 UTC, opbld32 commented
Docs Build status updates of commit _[1e76c9e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e76c9e1823e5a68e78742d13fd3e0d1faae9669)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/driveitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/api/listitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/api/listitem-createlink.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/resources/listitem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-beta&branch=pr-en-us-10286) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/CreateLink/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106150301215779-10286%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FO9I0DsWcdD2Lk9aM%2BoHa0tpGhMeI%2BMgHWBEfqcio7E%3D&st=2021-06-15T02%3A57%3A51Z&se=2021-07-16T03%3A02%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 03:06 UTC, merged

2021-06-15 04:53 UTC, angelgolfer-ms commented on api-reference/beta/api/driveitem-createlink.md
> +| addressBar     | Creates the default link that is shown in the browser address bars for newly created files. Only available in OneDrive for Business and SharePoint. The organization admin configure
Lines 68-73:
@k-tsoi , @isvargasmsft , I see "DriveItem" (actually should have been "driveItem") was replaced by "Item" in this commit. Is there a resource named "Item"? Or were you using the term to generally refer to an item in a drive? If it's the latter, you should use lower case "item" as in natural language. For clarity, you should also have defined what an "item" is prior to this point, e.g., is it a file, folder, etc.

(I'm looking into this now because I have a PR that has merge conflicts I need to resolve in this same table.)

2021-06-15 17:37 UTC, angelgolfer-ms commented on api-reference/beta/api/driveitem-createlink.md
> +| addressBar     | Creates the default link that is shown in the browser address bars for newly created files. Only available in OneDrive for Business and SharePoint. The organization admin configure
driveItem is better defined and clearer, thanks, @k-tsoi !