Adding Notes and Description
microsoftgraph/microsoft-graph-docs pull request #10310
Opened 2020-10-15 20:32 UTC by luleonpla

2020-10-15 20:34 UTC, opbld32 commented
Docs Build status updates of commit _[0849c1e](https://github.com/luleonpla/microsoft-graph-docs/commits/0849c1eb888c9b2c9c86ba6a74e8ee601d83e2d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-10310) (graph-rest-beta) | [Details](#user-content-5a8b9c5d-60ad955c)
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/v1.0/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-10310) (>= graph-rest-1.0) | [Details](#user-content-d3291f5a-60ad955c)

<a id="5a8b9c5d-60ad955c"></a>
### [api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md)
 - **Line 85, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/onedrive/developer/file-handlers/?view=odsp-graph-online NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="d3291f5a-60ad955c"></a>
### [api-reference/v1.0/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/v1.0/resources/serviceprincipal.md)
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/onedrive/developer/file-handlers/?view=odsp-graph-online NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010152032355601-10310%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EjB3nVFnBF%2F%2FA7Q7Y8oseJFQwYJrpjEx24miEEC2yvs%3D&st=2020-10-15T20%3A29%3A04Z&se=2020-11-15T20%3A34%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-15 20:44 UTC, eketo-msft approved these changes

2020-10-16 16:11 UTC, luleonpla commented
@Lauragra I don't seem to have rights to change the label to "Content review". Or, I'm missing the option but can't find it. Can you point me to a doc?

2020-10-16 23:47 UTC, Lauragra requested changes
Please add a changelog entry for the new property. Do you need to update any response examples to show the new property?

2020-10-16 23:47 UTC, opbld30 commented
Docs Build status updates of commit _[19428df](https://github.com/luleonpla/microsoft-graph-docs/commits/19428df751dca330e2ab04ddd17817ac6eec4142)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-10310) (graph-rest-beta) | [Details](#user-content-5a8b9c5d-a27c2216)
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/v1.0/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-10310) (>= graph-rest-1.0) | [Details](#user-content-d3291f5a-a27c2216)

<a id="5a8b9c5d-a27c2216"></a>
### [api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md)
 - **Line 85, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/onedrive/developer/file-handlers/?view=odsp-graph-online NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="d3291f5a-a27c2216"></a>
### [api-reference/v1.0/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/v1.0/resources/serviceprincipal.md)
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/onedrive/developer/file-handlers/?view=odsp-graph-online NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010162346316168-10310%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=k3dMycMBiYbijVFiN9d8ABzL7xcp7LBzrbaKCqMXDFY%3D&st=2020-10-16T23%3A42%3A51Z&se=2020-11-16T23%3A47%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-16 23:49 UTC, opbld33 commented
Docs Build status updates of commit _[363b80a](https://github.com/luleonpla/microsoft-graph-docs/commits/363b80afef5ef87198d69bda1ea1c5164a01b42c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-10310) (graph-rest-beta) | [Details](#user-content-5a8b9c5d-b483b480)
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/v1.0/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-10310) (>= graph-rest-1.0) | [Details](#user-content-d3291f5a-b483b480)

<a id="5a8b9c5d-b483b480"></a>
### [api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md)
 - **Line 85, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/onedrive/developer/file-handlers/?view=odsp-graph-online NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="d3291f5a-b483b480"></a>
### [api-reference/v1.0/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/v1.0/resources/serviceprincipal.md)
 - **Line 73, Column 0**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/onedrive/developer/file-handlers/?view=odsp-graph-online NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010162347081869-10310%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=joLuzpROHDuhHOuxaMQvES1Tv0iv8ZDdk2JBjEBF1R4%3D&st=2020-10-16T23%3A44%3A15Z&se=2020-11-16T23%3A49%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 21:49 UTC, opbld32 commented
Docs Build status updates of commit _[363b80a](https://github.com/luleonpla/microsoft-graph-docs/commits/363b80afef5ef87198d69bda1ea1c5164a01b42c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-10310) (graph-rest-beta) | [Details](#user-content-5a8b9c5d-ef2a95fc)
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/v1.0/resources/serviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-10310) (>= graph-rest-1.0) | [Details](#user-content-d3291f5a-ef2a95fc)

<a id="5a8b9c5d-ef2a95fc"></a>
### [api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 85, Column 192**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online. Otherwise, remove the view parameter.`````

<a id="d3291f5a-ef2a95fc"></a>
### [api-reference/v1.0/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/v1.0/resources/serviceprincipal.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102172147497387-10310%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GfoDAXxxw1ujEnZc8zWxOWJ7O95ok%2BQ5czswXbvQen0%3D&st=2021-02-17T21%3A44%3A10Z&se=2021-03-20T21%3A49%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 22:19 UTC, opbld32 commented
Docs Build status updates of commit _[d1d4a7c](https://github.com/luleonpla/microsoft-graph-docs/commits/d1d4a7c100397284716e3bc881e1d315fb3b0f08)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-10310) (graph-rest-beta) | [Details](#user-content-5a8b9c5d-9bc420ee)
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/v1.0/resources/serviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-10310) (>= graph-rest-1.0) | [Details](#user-content-d3291f5a-9bc420ee)

<a id="5a8b9c5d-9bc420ee"></a>
### [api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 85, Column 192**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online. Otherwise, remove the view parameter.`````

<a id="d3291f5a-9bc420ee"></a>
### [api-reference/v1.0/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/v1.0/resources/serviceprincipal.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102172218099001-10310%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TMLQDEZTbeEuU1CYdZctC9rRD8PNFwj%2BI9kQOsbljkg%3D&st=2021-02-17T22%3A14%3A43Z&se=2021-03-20T22%3A19%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 22:36 UTC, opbld33 commented
Docs Build status updates of commit _[6990c50](https://github.com/luleonpla/microsoft-graph-docs/commits/6990c508d74cbea398b74ad75ae29bd264c51904)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-10310) (graph-rest-beta) | [Details](#user-content-5a8b9c5d-025fa4b4)
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/v1.0/resources/serviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-10310) (>= graph-rest-1.0) | [Details](#user-content-d3291f5a-025fa4b4)

<a id="5a8b9c5d-025fa4b4"></a>
### [api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 85, Column 192**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online. Otherwise, remove the view parameter.`````

<a id="d3291f5a-025fa4b4"></a>
### [api-reference/v1.0/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/v1.0/resources/serviceprincipal.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102172235192377-10310%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=h2D2jLhDPsh9fUo00%2FAQw%2FLRJvjQCcEQeAr9Nxqides%3D&st=2021-02-17T22%3A31%3A39Z&se=2021-03-20T22%3A36%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-04 16:06 UTC, opbld30 commented
Docs Build status updates of commit _[3849742](https://github.com/luleonpla/microsoft-graph-docs/commits/3849742a6ece75953d6768020875d08964834ae8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-10310) (graph-rest-beta) | [Details](#user-content-5a8b9c5d-8b1dea99)
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/v1.0/resources/serviceprincipal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-10310) (>= graph-rest-1.0) | [Details](#user-content-d3291f5a-8b1dea99)
[changelog/Microsoft.DirectoryServices.json](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="5a8b9c5d-8b1dea99"></a>
### [api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 85, Column 192**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online. Otherwise, remove the view parameter.`````

<a id="d3291f5a-8b1dea99"></a>
### [api-reference/v1.0/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/v1.0/resources/serviceprincipal.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103041604490089-10310%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UgXkO9AIbGduH2Gzp2oHvUT3CSywgsV5oliU2iQshTw%3D&st=2021-03-04T16%3A01%3A37Z&se=2021-04-04T16%3A06%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-04 16:22 UTC, luleonpla commented
@Lauragra @davidmu1 could you please re-review this PR. I have added the changelog file and added samples of the new property.

2021-03-05 19:56 UTC, Lauragra approved these changes

2021-03-05 19:57 UTC, opbld33 commented
Docs Build status updates of commit _[7d1578b](https://github.com/luleonpla/microsoft-graph-docs/commits/7d1578b979487ac00a36f9608861d563dfa20ddc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta&branch=pr-en-us-10310) (graph-rest-beta) | [Details](#user-content-5a8b9c5d-0c26daf2)
[api-reference/v1.0/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/v1.0/resources/serviceprincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0&branch=pr-en-us-10310) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="5a8b9c5d-0c26daf2"></a>
### [api-reference/beta/resources/serviceprincipal.md](https://github.com/luleonpla/microsoft-graph-docs/blob/addNotesDescription/api-reference/beta/resources/serviceprincipal.md)
 - **Line 85, Column 192**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /onedrive/developer/file-handlers/?view=odsp-graph-online. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103051955444851-10310%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4IgS6cXev4wdMV%2BYJMo3rz5rp6G2QL3LCMCvt236IFk%3D&st=2021-03-05T19%3A52%3A02Z&se=2021-04-05T19%3A57%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-09 02:22 UTC, merged