placeholder for graph document changes
microsoftgraph/microsoft-graph-docs pull request #10345
Opened 2020-10-20 00:29 UTC by frankpeng7

placeholder for graph document changes

2020-10-20 00:30 UTC, opbld34 commented
Docs Build status updates of commit _[b70911c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b70911c818358f817120a6853768fd231cc7781e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010200029350526-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rW9u0tDyo3Lu7SzST54GgLo21K7l43Z41egqq1wDMUA%3D&st=2020-10-20T00%3A25%3A52Z&se=2020-11-20T00%3A30%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 01:31 UTC, opbld33 commented
Docs Build status updates of commit _[1b10925](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b109256a4bd5a91e25bc9810a5187f27dcb0cf6)_: 

:clock10: **Pending**: waiting for processors ([12](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-04 01:32 UTC, opbld33 commented
Docs Build status updates of commit _[1b10925](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b109256a4bd5a91e25bc9810a5187f27dcb0cf6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012040130562780-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=l0LyIlUCHgMOm8SVdRXGCNRGJVu5H%2F4JQktsp%2BlorK8%3D&st=2020-12-04T01%3A27%3A11Z&se=2021-01-04T01%3A32%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 01:35 UTC, opbld30 commented
Docs Build status updates of commit _[623bc6e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/623bc6e1c3273140b52028ecf56e5f4bde91a592)_: 

:clock10: **Pending**: waiting for processors ([12](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-04 01:36 UTC, opbld30 commented
Docs Build status updates of commit _[623bc6e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/623bc6e1c3273140b52028ecf56e5f4bde91a592)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012040135363221-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=keTzTcedOXPQg0elqS1iN%2FxbKbAAOauSrj81BgAwqys%3D&st=2020-12-04T01%3A31%3A49Z&se=2021-01-04T01%3A36%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 05:28 UTC, jsandoval-msft commented on api-reference/beta/api/application-post-onlinemeetings.md
> +### Example 3: Create a broadcast meeting with a user token
we are supporting both user token and app token correct? Do we need an example for app token?

2020-12-07 05:46 UTC, jsandoval-msft reviewed
The permissions table indicates broadcast meeting creation is supported for app token. If this is correct, should we also add a code example for creating a broadcast meeting with app token?

2020-12-08 19:31 UTC, frankpeng7 commented on api-reference/beta/api/application-post-onlinemeetings.md
> +### Example 3: Create a broadcast meeting with a user token
App token cases will be on behalf of user which means the request/response is exactly the same. Any suggestion how should we add it?

2020-12-12 00:53 UTC, opbld30 commented
Docs Build status updates of commit _[6449ee5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6449ee572df7e3377a66c929b66e7652df014b5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012120051475364-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nz2bTiEgclKfdszXY9S8NVvyAYy7NHCBxHkgEMynJnM%3D&st=2020-12-12T00%3A48%3A00Z&se=2021-01-12T00%3A53%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-14 22:43 UTC, opbld31 commented
Docs Build status updates of commit _[3b3d38c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b3d38ca6f82b3ce43f514899165d6e5a55cad28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012142241231437-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jLT9DrDKaVpjOltDOOl8huW82PcKPbv0yHTYp%2Fdd%2Fhg%3D&st=2020-12-14T22%3A38%3A34Z&se=2021-01-14T22%3A43%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-14 23:09 UTC, opbld33 commented
Docs Build status updates of commit _[c823eb2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c823eb2b5b84ca4f47c97e9a0526c33040ba9db5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012142308301217-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=evx2gVY95KElLbRVdxukQN8h7zd5er4Z%2BSHGV4hNmzk%3D&st=2020-12-14T23%3A04%3A50Z&se=2021-01-14T23%3A09%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-14 23:33 UTC, opbld30 commented
Docs Build status updates of commit _[5d4d9af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d4d9af9e30b1620d03fb09fec63adfa9cf883b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012142332141455-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=34dIYNSOkkI%2F43PfvypTZjddpynVfSgDfT%2FFOY3a5%2Bc%3D&st=2020-12-14T23%3A28%3A25Z&se=2021-01-14T23%3A33%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-14 23:33 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +Retrieve the attendee report and recordings of a live event [onlineMeeting](../resources/onlinemeeting.md) object. Currently these two resources are exclusively available to live events.
@jsandoval-msft can you help with wording here?

2020-12-14 23:37 UTC, frankpeng7 commented on api-reference/beta/api/application-post-onlinemeetings.md
> +  "subject":"User Token Broadcast Meeting",
live event

2020-12-14 23:37 UTC, frankpeng7 commented on api-reference/beta/api/application-post-onlinemeetings.md
> +  "subject": "User Token Broadcast Meeting",
live event

2020-12-14 23:37 UTC, frankpeng7 commented on api-reference/beta/resources/broadcastSettings.md
> +Settings related to a broadcast meeting.
live event

2020-12-14 23:59 UTC, opbld34 commented
Docs Build status updates of commit _[8525886](https://github.com/microsoftgraph/microsoft-graph-docs/commits/852588687d03e1c5c944acdb69bd9169cfe4e3fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012142357552978-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FYZIGSrJGDe2KODdATo4mV8IhmphSLASzV0jw60b5Q8%3D&st=2020-12-14T23%3A54%3A23Z&se=2021-01-14T23%3A59%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 00:34 UTC, opbld30 commented
Docs Build status updates of commit _[a3a7bd5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a3a7bd584fa2d50f0ae11f5a1afa0606783f4a44)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/broadcastSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastSettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) | [Details](#user-content-14cb14a7-853fe8b5)
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |

<a id="14cb14a7-853fe8b5"></a>
### [api-reference/beta/resources/broadcastSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastSettings.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/set-teams-live-events-policies-using-powershell' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150033001222-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tg7SDp2nKe0YQM5jd6OusYpSUlfk5k6Q6XJY65nrviE%3D&st=2020-12-15T00%3A29%3A16Z&se=2021-01-15T00%3A34%3A16Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 00:37 UTC, frankpeng7 commented on api-reference/beta/api/application-post-onlinemeetings.md
> +> [broadcastSettings](../resources/broadcastSettings.md) for more details.
@jsandoval-msft please help with wording here

2020-12-15 00:38 UTC, frankpeng7 commented on api-reference/beta/resources/broadcastSettings.md
> +> and set **allowedAudience** to `everyone`. The request will go through and take effect.
@jsandoval-msft please help with wording here - this is the main one

2020-12-15 00:38 UTC, frankpeng7 commented on api-reference/beta/resources/onlinemeeting.md
> +
@jsandoval-msft please help with wording here

2020-12-15 00:44 UTC, opbld33 commented
Docs Build status updates of commit _[58f02fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58f02fd8fef8234df54f0a140fbe54f45c0e66d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150042255258-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mvtm1gDxiAP%2Bvz0p%2Fp6IJG9G%2F48XQQkaHkzqDqnP6%2F8%3D&st=2020-12-15T00%3A39%3A41Z&se=2021-01-15T00%3A44%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 04:57 UTC, opbld32 commented
Docs Build status updates of commit _[c58a5d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c58a5d5d217920cdadb966042ba0156390a258ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150455512443-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dm3tcA1QODSEUPEvkZhAs3QBpAkOo56bMe%2BKG40u3Us%3D&st=2020-12-15T04%3A52%3A03Z&se=2021-01-15T04%3A57%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 05:02 UTC, opbld34 commented
Docs Build status updates of commit _[fc85dfe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc85dfe5c323f2722ae4777cabf166d30424ac37)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150501210533-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=otK7QENcWWaDxEFHpMelhvAW9fK5QqaecnhMvR7Kfqg%3D&st=2020-12-15T04%3A57%3A48Z&se=2021-01-15T05%3A02%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 05:20 UTC, opbld30 commented
Docs Build status updates of commit _[3c39068](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c39068dc7f896fe03e7ccc67ccc51a78d97a501)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150518482827-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yn65kIYdV%2BsN0gfs35LCyFZWq%2FYbd%2FBbFuEUh0Op7zc%3D&st=2020-12-15T05%3A15%3A11Z&se=2021-01-15T05%3A20%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 05:21 UTC, jsandoval-msft approved these changes

2020-12-15 05:21 UTC, opbld31 commented
Docs Build status updates of commit _[32d90b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32d90b6dbc8e8ba872de898c09c5ac6fc30f2c36)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150520344593-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OPsewzjvpfQOpJvbbEItaPvXQaOyFkVGH3%2BpOdAg5oA%3D&st=2020-12-15T05%3A16%3A50Z&se=2021-01-15T05%3A21%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 01:36 UTC, opbld32 commented
Docs Build status updates of commit _[92152d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92152d56e43192a7ba36907364717ace2dccec8e)_: 

:clock10: **Pending**: waiting for processors ([8](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-16 01:37 UTC, opbld32 commented
Docs Build status updates of commit _[92152d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92152d56e43192a7ba36907364717ace2dccec8e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) | [Details](#user-content-de0bbbbb-32037f64)
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |

<a id="de0bbbbb-32037f64"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md)
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160136472418-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EiUY9tV1egmXrfoK29PMC4xHZH6j5wGRHek9H7SH%2FVg%3D&st=2020-12-16T01%3A32%3A58Z&se=2021-01-16T01%3A37%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 04:04 UTC, opbld31 commented
Docs Build status updates of commit _[3efe06c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3efe06c33c0bae176c1489743b7ba0d6f99f4f3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) | [Details](#user-content-de0bbbbb-743c7368)
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |

<a id="de0bbbbb-743c7368"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md)
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160403026355-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rpZFnfALvrqv%2BNYR8Du3Hf%2FLZ1ZnxLXutKxLKXYwW9g%3D&st=2020-12-16T03%3A59%3A15Z&se=2021-01-16T04%3A04%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 04:08 UTC, Lauragra commented on api-reference/beta/api/application-post-onlinemeetings.md
> +> [!IMPORTANT]
Why do we need a note stating that the API is in beta, when it's a beta topic and already has a beta disclaimer on it? Is broadcastSettings a property or a resource? Currently in the metadata it's defined as a property of the onlineMeeting resource.

2020-12-16 04:13 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +title: "Live event attendee report and recordings"
The file name and topic title for this topic is not consistent with our guidelines. Please see the following guidance and update accordingly: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming and https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title.

2020-12-16 04:16 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +Retrieve the attendee report and recordings of a live event [onlineMeeting](../resources/onlinemeeting.md) object. Currently these two resources are exclusively available to live events.
Please clarify the second sentence - what two resources are you referring to?

2020-12-16 04:20 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +Retrieve the attendee report and recordings of a live event [onlineMeeting](../resources/onlinemeeting.md) object. Currently these two resources are exclusively available to live events.
Is the definition of a live event onlineMeeting different than just an onlineMeeting?

2020-12-16 04:24 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +### Example 1: download attendee report
If there's only one example, you don't need to number it, just make the Request and Response headings H3s.

2020-12-16 04:26 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +# [HTTP](#tab/http)
When you add new API topics/examples, don't include the H1 snippet links. Those get added via the weekly automation after we merge into master.

2020-12-16 04:28 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +GET /users/{organizerId}/onlineMeetings/{meetingId}/attendeeReport
Based on this, should we have three separate API topics, Get attendeeReport, Get recording, Get alternativeRecording, that we surface under onlineMeeting?

2020-12-16 04:28 UTC, Lauragra commented on api-reference/beta/resources/broadcastsettings.md
> +title: "broadcastSettings resource type"
This is currently defined in the metadata as a property, not a resource.

2020-12-16 04:29 UTC, Lauragra commented on api-reference/beta/resources/broadcastsettings.md
> +Settings related to a live event.
Revise as "Represents settings related to an onlineMeeting." I assume that it's actually an online meeting and not a live event? Or, what is the difference?

2020-12-16 04:30 UTC, Lauragra commented on api-reference/beta/resources/broadcastsettings.md
> +> [!IMPORTANT]
This is a beta topic with a beta disclaimer, not I'm not sure that we need this note. If there are limitations, maybe just state them, but it should be clear that it's beta functionality.

2020-12-16 04:31 UTC, Lauragra commented on api-reference/beta/resources/broadcastsettings.md
> +> API does not validate live event settings that are managed by [policy](https://docs.microsoft.com/microsoftteams/teams-live-events/set-teams-live-events-policies-using-powershell).
Always refer to Graph as Microsoft Graph.

2020-12-16 04:34 UTC, Lauragra commented on api-reference/beta/resources/broadcastsettings.md
> +  "allowedAudience": "everyone | organization | roleIsAttendee | unknownFutureValue",
This should just be string here instead of listing the values.

2020-12-16 04:36 UTC, opbld30 commented
Docs Build status updates of commit _[863d8cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/863d8ccd2ca477f87fbe18e3b9bdbad2d6119831)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) | [Details](#user-content-de0bbbbb-4eb7cc32)
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |

<a id="de0bbbbb-4eb7cc32"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md)
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160435254764-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2p1preGCZGSvJq2xqfUJF2D9SuRG9BSWbeCV%2FZ173dY%3D&st=2020-12-16T04%3A31%3A37Z&se=2021-01-16T04%3A36%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 04:39 UTC, Lauragra commented on api-reference/beta/resources/onlinemeeting.md
> +> [!IMPORTANT]
I'm not sure that you need this note. In any event, it might be better to add the text to the Description, or at least have the asterisk show on the note so the reader can make the association. You have two IMPORTANTS in a row here so that will dilute the impact for the reader.

2020-12-16 04:39 UTC, Lauragra commented on api-reference/beta/resources/onlinemeeting.md
> +| broadcastSettings     | [broadcastSettings](broadcastSettings.md)     | Settings related to a live event*
According to the metadata, this property is of type broadcastMeetingSettings.

2020-12-16 04:41 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Live event attendee report and recordings
We will need to update this TOC entry; see my feedback about the topic title and whether this should be three separate operation topics?

2020-12-16 04:44 UTC, Lauragra commented on concepts/changelog.md
> +|Addition|beta|Added the **isBroadcast**, **broadcastSettings**, **attendeeReport**, **recording** and **alternativeRecording** property to the [onlineMeeting](/graph/api/resources/onlinemeeting?view
Please change "property" to "properties", and add a Changelist entry to the Skype.Caling.json file for the new changelog experience.

2020-12-16 04:45 UTC, Lauragra requested changes
Please see feedback in comments.

2020-12-18 19:35 UTC, frankpeng7 commented on api-reference/beta/api/application-post-onlinemeetings.md
> +> [!IMPORTANT]
Oh I actually just saw this. The word used to be "private preview" instead of "beta". I guess @jsandoval-msft changed it. @jsandoval-msft are you ok to remove this?

2020-12-18 23:19 UTC, frankpeng7 commented on api-reference/beta/resources/onlinemeeting.md
> +| broadcastSettings     | [broadcastSettings](broadcastSettings.md)     | Settings related to a live event*
Will update in next revision

2020-12-18 23:20 UTC, frankpeng7 commented on api-reference/beta/resources/broadcastsettings.md
> +Settings related to a live event.
live event can be considered as a kind of online meeting. The revised sentence would not be accurate since these settings only apply to live events

2020-12-18 23:31 UTC, frankpeng7 commented on api-reference/beta/resources/broadcastsettings.md
> +> [!IMPORTANT]
This is something really important that we want every customer who is using this to understand. Any recommendation to replace the "important" banner?

2020-12-18 23:32 UTC, frankpeng7 commented on api-reference/beta/resources/broadcastsettings.md
> +title: "broadcastSettings resource type"
What do you mean by "topic"? Are you suggesting renaming this to "broadcastMeetingSettings complex type"?

2020-12-18 23:35 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +Retrieve the attendee report and recordings of a live event [onlineMeeting](../resources/onlinemeeting.md) object. Currently these two resources are exclusively available to live events.
for the first question: attendee report and recordings; for the second - refer to my reply below
> live event can be considered as a kind of online meeting. In this way online meetings consist of 2 types of meetings: scheduled meetings and live events.

2020-12-18 23:38 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +GET /users/{organizerId}/onlineMeetings/{meetingId}/attendeeReport
The usage of them is exactly the same so looks redundant to create three.
FYI @elvinyang-msft who is the original author of onlinemeeting-live-event-attendee-report-recording.md

2020-12-18 23:42 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +### Example 1: download attendee report
I removed the number but kept "Request" and "Response" H4 since I would like to keep the title (download attendee report) so the title needs to be H3

FYI @elvinyang-msft (original author)

2020-12-18 23:42 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +# [HTTP](#tab/http)
Will remove in next revision

2020-12-18 23:46 UTC, frankpeng7 commented on concepts/changelog.md
> +|Addition|beta|Added the **isBroadcast**, **broadcastSettings**, **attendeeReport**, **recording** and **alternativeRecording** property to the [onlineMeeting](/graph/api/resources/onlinemeeting?view
Changed "property" to "properties". Is there any guidance/document about how to add an entry in the json file? I took a look and they don't seem to be added manually

2020-12-18 23:47 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +title: "Live event attendee report and recordings"
@elvinyang-msft (original author of this md) I'll leave this to you to make a decision/change

2020-12-18 23:48 UTC, frankpeng7 commented on api-reference/beta/toc.yml
> +        - name: Live event attendee report and recordings
Please see my reply about separating the topics; once we have an agreement I'll update this accordingly.

FYI @elvinyang-msft

2020-12-18 23:54 UTC, opbld33 commented
Docs Build status updates of commit _[03b3a41](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03b3a416fea4c2409cbf8e596897ddd93f965a13)_: 

:clock10: **Pending**: waiting for processors ([35](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 35 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-18 23:56 UTC, opbld32 commented
Docs Build status updates of commit _[03b3a41](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03b3a416fea4c2409cbf8e596897ddd93f965a13)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastMeetingSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastMeetingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012182354428365-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3CnLBuaoZpLwhp%2F%2ByzLAjxu5%2B%2BinwKa9QUBznRG9%2FxE%3D&st=2020-12-18T23%3A51%3A17Z&se=2021-01-18T23%3A56%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 03:04 UTC, Lauragra commented on api-reference/beta/api/application-post-onlinemeetings.md
> +> [!IMPORTANT]
The new broadcastMeetingSettings type is live in the metadata so it isn't hidden via exposure control. Is there an intention for the API to be available only to a select group of customers, or can anyone use it?

2020-12-19 03:05 UTC, opbld33 commented
Docs Build status updates of commit _[6d54ef4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d54ef4c8e492b467326799856f9f14685eb3d55)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-19 03:06 UTC, opbld31 commented
Docs Build status updates of commit _[6d54ef4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d54ef4c8e492b467326799856f9f14685eb3d55)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190305038346-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kIAZ%2BQDtQHF%2FPppjocH7RsFAF06FurLeY8c9%2BTWRvXo%3D&st=2020-12-19T03%3A01%3A28Z&se=2021-01-19T03%3A06%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 03:07 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +### Example: download attendee report
We only add the Example H3 here when there are multiple numbered examples in a topic. If you're only showing one example, remove this H3 and elevate Request and Response to the H3 level.

2020-12-19 03:09 UTC, Lauragra commented on concepts/changelog.md
> +|Addition|beta|Added the **isBroadcast**, **broadcastSettings**, **attendeeReport**, **recording** and **alternativeRecording** property to the [onlineMeeting](/graph/api/resources/onlinemeeting?view
Yes, see this in the CDK: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=guidelines-for-workload-changelog-json-files-only

2020-12-19 04:33 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +### Example: download attendee report
If we do that where should we put this line?

2021-01-04 22:16 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +### Example: download attendee report
If you think the example needs some context, you can have an introductory sentence: The following example shows a request to download an attendee report.

2021-01-07 19:52 UTC, elvinyang-msft commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +GET /users/{organizerId}/onlineMeetings/{meetingId}/attendeeReport
We'd like to list all supported resources of live event in one place, besides recording/alternative recording are really the same thing

2021-01-07 19:53 UTC, elvinyang-msft commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +title: "Live event attendee report and recordings"
That makes sense @frankpeng7 could you help to make the file name consistent with the title?

2021-01-07 19:57 UTC, elvinyang-msft commented on api-reference/beta/toc.yml
> +        - name: Live event attendee report and recordings
We'll keep one topic but @frankpeng7 please help to updated the file name accordingly as we'll change the file name for consistency with the title.

2021-01-08 01:26 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +title: "Live event attendee report and recordings"
Done

2021-01-08 01:31 UTC, opbld33 commented
Docs Build status updates of commit _[aa2f619](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa2f61916fe4371362695f40bb487a107695dd04)_: 

:clock10: **Pending**: waiting for processors ([7](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-08 01:31 UTC, opbld31 commented
Docs Build status updates of commit _[aa2f619](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa2f61916fe4371362695f40bb487a107695dd04)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-743af09d)

<a id="743af09d"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101080131180815-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=J2Nxt%2BQFRmRsRZ0S0rwly7NLbzKDFraKn73mMcArB1M%3D&st=2021-01-08T01%3A26%3A36Z&se=2021-02-08T01%3A31%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 01:32 UTC, opbld32 commented
Docs Build status updates of commit _[736ab9d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/736ab9d89483554a9f3a43a0c2a1fb497b6644d2)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-08 01:33 UTC, opbld33 commented
Docs Build status updates of commit _[736ab9d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/736ab9d89483554a9f3a43a0c2a1fb497b6644d2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6ee54958)

<a id="6ee54958"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101080132490418-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1j8cYg1A3euSn40MZxCY%2BYhycXvlrbThxE4xC0hKGfU%3D&st=2021-01-08T01%3A28%3A05Z&se=2021-02-08T01%3A33%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 01:49 UTC, opbld30 commented
Docs Build status updates of commit _[0ee6162](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ee6162517b9104a25275eb4cd684004426abf9a)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-08 01:50 UTC, opbld32 commented
Docs Build status updates of commit _[0ee6162](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ee6162517b9104a25275eb4cd684004426abf9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101080149507309-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aETL500uNl53zjlzWJ9SsSHrMJdJOxtlhiYkipr5NWY%3D&st=2021-01-08T01%3A45%3A58Z&se=2021-02-08T01%3A50%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 04:30 UTC, opbld34 commented
Docs Build status updates of commit _[bd26b7c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd26b7c735b6da684e0d267b89ccab378573179b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-921ec3d7)

<a id="921ec3d7"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101080430253481-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yi6x6vUoDEw6ES5CisoK1avDudoz4aBXnwmIpzJV2dU%3D&st=2021-01-08T04%3A25%3A42Z&se=2021-02-08T04%3A30%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 04:43 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +title: "Live event attendee report and recordings"
I can't see that the file name has been updated.

2021-01-08 04:44 UTC, Lauragra commented on api-reference/beta/api/onlinemeeting-live-event-attendee-report-recording.md
> +# [HTTP](#tab/http)
Unresolving this to make sure the snippets get removed.

2021-01-08 04:45 UTC, Lauragra commented on api-reference/beta/resources/broadcastsettings.md
> +> [!IMPORTANT]
I made a revision to the note text to remove the statement about it being a beta API.

2021-01-08 04:46 UTC, Lauragra requested changes
For this PR, we still need to address the single file covering multiple GET operations, and we still need an update the changelog JSON file. We also have a merge conflict on changelog.md. Within a week, we'll be deprecating that topic so depending on when we publish this PR, you can maybe just remove the entry.

2021-01-08 07:29 UTC, opbld32 commented
Docs Build status updates of commit _[1251789](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1251789a15f243dd7f0d92db116931cfd598fd56)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-33714cc3)

<a id="33714cc3"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101080729029459-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4Rb2r1ppdisI1kCgYdEf75mTF%2FyuVG3Ob2ITCcvcTHM%3D&st=2021-01-08T07%3A24%3A26Z&se=2021-02-08T07%3A29%3A26Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 07:33 UTC, opbld30 commented
Docs Build status updates of commit _[8acea47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8acea47aea853626cbd6c614d057bbd2a36dc2d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101080732368996-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=esqofFd3tB2tRJ71ntINEuRp5gpMhbbPVXlncwBFiuA%3D&st=2021-01-08T07%3A28%3A45Z&se=2021-02-08T07%3A33%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 07:37 UTC, frankpeng7 commented
Hi @Lauragra thanks for the feedback. 
1. changelog.md and changelog.json (I saw it was already called another name) have been updated.
2. For the single file covering multiple GET operations issue, can you kindly point out which guideline it's against? If there's documentation/guideline stating this is not allowed, we'd be happy to update it. FYI @elvinyang-msft

2021-01-08 12:17 UTC, opbld34 commented
Docs Build status updates of commit _[2e51e96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e51e960b12158defc8a4fab960aea63f3cfaefa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101081216207663-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=n4h5imBLf1KFp6o5Fc81A60E0Ll89ypWYiALH7vs39o%3D&st=2021-01-08T12%3A12%3A27Z&se=2021-02-08T12%3A17%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 13:15 UTC, millicentachieng commented on api-reference/beta/resources/broadcastmeetingsettings.md
> +  "@odata.type": "microsoft.graph.broadcastSettings"
Should this be `microsoft.graph.broadcastMeetingSettings`?

2021-01-08 17:19 UTC, Lauragra commented
> Hi @Lauragra thanks for the feedback.
> 
> 1. changelog.md and changelog.json (I saw it was already called another name) have been updated.
> 2. For the single file covering multiple GET operations issue, can you kindly point out which guideline it's against? If there's documentation/guideline stating this is not allowed, we'd be happy to update it. FYI @elvinyang-msft

Hi, yes, this our file naming guidelines topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming.

The relevant part is this: 
API (get) | Use resourcename-get.

This is also what the stub generator tool will generate. Because we're moving toward full topic generation in the future, we need to ensure that we follow the conventions that are enforced by the tool.

2021-01-08 18:52 UTC, opbld31 commented
Docs Build status updates of commit _[fa2e7c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa2e7c0667dba71695f97fb2a220fe20108135bb)_: 

:clock10: **Pending**: waiting for processors ([18](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 18 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-08 18:55 UTC, opbld34 commented
Docs Build status updates of commit _[fa2e7c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa2e7c0667dba71695f97fb2a220fe20108135bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/live-event-attendee-report-recording.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/live-event-attendee-report-recording.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/live-event-attendee-report-recording?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101081852045307-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=adny2CDkxSCpZ9C%2F3mJ%2FWS47m6yERNrML%2B7nQ3ab%2F8s%3D&st=2021-01-08T18%3A50%3A21Z&se=2021-02-08T18%3A55%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 18:58 UTC, frankpeng7 commented on api-reference/beta/resources/broadcastmeetingsettings.md
> +  "@odata.type": "microsoft.graph.broadcastSettings"
I've updated this but it didn't help with the apidoctor failure

2021-01-12 23:32 UTC, angelgolfer-ms commented on api-reference/beta/api/live-event-attendee-report-recording.md
> +> - Administrators must create an [application access policy](/graph/cloud-communication-online-meeting-application-access-policy) and grant it to a user, authorizing the app configured in the policy
Lines 28-30:
After you combine the content of this topic with the existing GET online meeting API topic, I'd suggest moving notes this to the top section, in that GET operation topic. This is a consistency issue - we train customers to look for atypical info they need to know about an API in the top section.

2021-01-12 23:33 UTC, angelgolfer-ms commented on api-reference/beta/api/live-event-attendee-report-recording.md
> +```http
Lines 35-37:
Since this syntax is typical of getting a specific property in a resource, I wouldn't suggest having these lines called out in the GET online meeting topic.

2021-01-12 23:34 UTC, angelgolfer-ms commented on api-reference/beta/api/live-event-attendee-report-recording.md
> +> **Notes:**
Lines 51-54:
I would suggest moving this info to the top as well, for the reason that we want customers to look for atypical info like this, about the usage of an API, in the top section.

2021-01-13 07:04 UTC, opbld30 commented
Docs Build status updates of commit _[70c52cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70c52ccde5c40f646acc20f7799a4fb333318680)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) | [Details](#user-content-de0bbbbb-921ad393)
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-921ad393"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md)
 - **Line 50, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 50, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101130702298505-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Bjvj2z%2FIlnnMExwJ6YjLgk1Ouw9Oaa0pc9DQYQ8lRDk%3D&st=2021-01-13T06%3A59%3A34Z&se=2021-02-13T07%3A04%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 07:06 UTC, opbld34 commented
Docs Build status updates of commit _[f556313](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f556313c060da8e0d29d4d21755188b0ade81575)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) | [Details](#user-content-de0bbbbb-a9d7f633)
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-a9d7f633"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md)
 - **Line 50, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 50, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101130703224222-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Xxg9UpMpMaWoRfOBhvu2oA1LGXgv3ZkGLe8eFGH1WyQ%3D&st=2021-01-13T07%3A01%3A31Z&se=2021-02-13T07%3A06%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 22:58 UTC, opbld33 commented
Docs Build status updates of commit _[8226f4c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8226f4c50c70d10b281cfd6def304a5d981a66c4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) | [Details](#user-content-de0bbbbb-82373a3b)
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-82373a3b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md)
 - **Line 50, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 50, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132257332630-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9yDFa%2FrmD8R26jjp29PU30VLZC%2F3MVSmAn7rWb2T6rM%3D&st=2021-01-13T22%3A53%3A58Z&se=2021-02-13T22%3A58%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 01:12 UTC, angelgolfer-ms commented on api-reference/beta/api/onlinemeeting-get.md
> +To get the specified onlineMeeting via meeting ID:
Lines 51-56:
Please move these lines up to  right after 43, as the basic scenario of getting the properties of an online meeting resource.

2021-01-14 01:16 UTC, angelgolfer-ms commented on api-reference/beta/api/onlinemeeting-get.md
> +To get the specified onlineMeeting via meeting ID:
With the above suggested move, please also reorder the examples and fix the corresponding link(s).

2021-01-14 01:37 UTC, angelgolfer-ms commented on api-reference/beta/api/onlinemeeting-get.md
> +To get the specified onlineMeeting via VideoTeleconferenceId:
Line 44 and 58:
Please use the camel case videoTeleconferenceId and joinWebUrl, and bold those terms, since you're referring to them as property names.

2021-01-14 01:44 UTC, angelgolfer-ms commented on api-reference/beta/api/onlinemeeting-get.md
Line 99:
Please correct the Response section. You can say:
If successful, this method returns a 200 OK response code.
If you're getting an online meeting based on meeting ID, **videoTeleconferenceId** or **joinWebUrl**, this method also returns an **onlineMeeting** object in the response body.
If you're getting the attendee report or recording of a live online meeting, this method also returns a `Location` header that indicate the URI to the attendee report or recording, respectively.

2021-01-14 01:51 UTC, angelgolfer-ms requested changes
Hi @frankpeng7 , that's a good job, thanks for incorporating the feedback about centralizing the docs for the few scenarios that use the GET onlinemeetings operation. I reviewed specifically the onlinemeeting-get.md topic. Please take a look at my comments.

2021-01-14 02:03 UTC, opbld31 commented
Docs Build status updates of commit _[f549392](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5493923b9e7163aa56a3346b826e19acc645332)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) | [Details](#user-content-de0bbbbb-2c3d736b)
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-2c3d736b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md)
 - **Line 50, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 50, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101140201012062-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1lGRhJAzsiBxXe392LR0iZ3XtVX%2B0%2Bpaet8Noq7su4A%3D&st=2021-01-14T01%3A57%3A53Z&se=2021-02-14T02%3A02%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 03:30 UTC, Lauragra approved these changes

2021-01-14 03:30 UTC, opbld31 commented
Docs Build status updates of commit _[395f0fb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/395f0fbef2f349a6936bd28bccb4ff42b622ea11)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) | [Details](#user-content-de0bbbbb-ff76502f)
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-ff76502f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md)
 - **Line 50, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 50, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101140329024640-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UDn%2BiXM1F0Ng7juYrmgFjZfL6rqDFrQB84kyEYTzb3w%3D&st=2021-01-14T03%3A25%3A11Z&se=2021-02-14T03%3A30%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 03:31 UTC, opbld32 commented
Docs Build status updates of commit _[a4bc0c3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a4bc0c3ff22e3a32501b2f51294a2d800f9028f3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) | [Details](#user-content-de0bbbbb-c1c3a41f)
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-c1c3a41f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md)
 - **Line 50, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 50, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101140329412353-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LarAY1vcB3GgRjf23sBoHaKuQtJWEi%2F4N%2Fge8VT7hNI%3D&st=2021-01-14T03%3A26%3A20Z&se=2021-02-14T03%3A31%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 03:34 UTC, opbld34 commented
Docs Build status updates of commit _[8e656b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e656b1b8fd1244560b2967d03f08b004ce6d2d4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10345) | [Details](#user-content-de0bbbbb-ffbe1de8)
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/broadcastmeetingsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/broadcastmeetingsettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/broadcastmeetingsettings?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-10345) (graph-rest-beta) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-10345) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-ffbe1de8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/support-live-event/concepts/changelog.md)
 - **Line 50, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 50, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101140333015806-10345%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=halunv52%2FQTEt7UtiqR1gQ7aaCsBr%2BWPwouMXjc4%2F0s%3D&st=2021-01-14T03%3A29%3A10Z&se=2021-02-14T03%3A34%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 03:37 UTC, merged

2021-01-14 04:51 UTC, jsandoval-msft commented on api-reference/beta/resources/broadcastmeetingsettings.md
> +> by setting **allowedAudience** to `everyone`.
This should probably say "..., but will be able to create a live event via Microsoft Graph with **allowedAudience** set to 'everyone'. "

2021-01-14 04:51 UTC, jsandoval-msft commented on api-reference/beta/api/onlinemeeting-get.md
> +```
This example stops at getting a URL for the report, and there is still the step of getting the actual content. When I make a GET request to this URL what type of content can I expect in the response? It would be nice to have a short description of what a developer can expect as the final step to retrieving the report.

2021-01-14 04:51 UTC, jsandoval-msft commented on api-reference/beta/api/onlinemeeting-get.md
> +Location: https://01-a-noam.dog.attend.teams.microsoft.com/broadcast/909c6581-5130-43e9-88f3-fcb3582cde37/dc17674c-81d9-4adb-bfb2-8f6a442e4622/19%3Ameeting_ZWE0YzQwMzItYjEyNi00NjJjLWE4MjYtOTUxYjE1NmF
This example stops at getting a URL for the recording, and there is still the step of getting the actual content. When I make a GET request to this URL what type of content can I expect in the response? It would be nice to have a short description of what a developer can expect as the final step to retrieving the recording.