ToU API updates for versioning
microsoftgraph/microsoft-graph-docs pull request #10340
Opened 2020-10-19 19:13 UTC by rajadineshmurugesan-microsoft

2020-10-19 19:15 UTC, opbld30 commented
Docs Build status updates of commit _[4633647](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/46336478358e2ee57cf55704d93638c01200adad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-2fe65d0f-70bd9bb1)
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="2fe65d0f-70bd9bb1"></a>
### [api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md)
 - **Line 7, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'rajadineshkumarmurugesan' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010191913370237-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3bzOl5YdaVb79T3GE81cJ1%2Boujg03JiTs4wcowF1W%2FI%3D&st=2020-10-19T19%3A10%3A01Z&se=2020-11-19T19%3A15%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-19 19:23 UTC, opbld34 commented
Docs Build status updates of commit _[730cad6](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/730cad60846815d05dc4c5fdbce23d7671bc1287)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010191921441702-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LfFMfxzii4Y7kAz2h4op4FT92UYon1gPHenMteY28C0%3D&st=2020-10-19T19%3A18%3A40Z&se=2020-11-19T19%3A23%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-19 19:33 UTC, opbld31 commented
Docs Build status updates of commit _[5f62d8c](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/5f62d8c56cd43dc7dc8728ef80f2593eb0835000)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010191932056002-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eCme0R8S2GDYIhaIpqhHJSk4gcNnmItDJN2dS%2Fx%2F3AY%3D&st=2020-10-19T19%3A28%3A28Z&se=2020-11-19T19%3A33%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-19 19:35 UTC, opbld34 commented
Docs Build status updates of commit _[1e15211](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/1e1521182f9c2b2ede804c8368f4291e675b024e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010191934028128-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lwER%2F9tlWF12MJPQ8GDNo7ExmqCM185JArqQK3%2F%2FMEU%3D&st=2020-10-19T19%3A30%3A55Z&se=2020-11-19T19%3A35%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-19 22:06 UTC, opbld32 commented
Docs Build status updates of commit _[83e46af](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/83e46afeae35599f5e2dea2c9df1d9258a29e87f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010192205095526-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=E%2FuqAxEPZmDsU7Kk%2BGsKCMPAMDVIX5xLz4S2SjfwRrw%3D&st=2020-10-19T22%3A01%3A31Z&se=2020-11-19T22%3A06%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-19 22:07 UTC, opbld33 commented
Docs Build status updates of commit _[2a1ed0e](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/2a1ed0e3839f0c636a4661942c1084d869f3675c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010192206207645-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SeXY3uDLwm6pLjnl0ZxRG0VfsA%2B2oXMPwihj81qOT1w%3D&st=2020-10-19T22%3A02%3A49Z&se=2020-11-19T22%3A07%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-19 22:14 UTC, opbld32 commented
Docs Build status updates of commit _[5a37d07](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/5a37d07aa60a6191154caa44258f363682e1998a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010192212017225-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4wQVFadlyTzB4L3wB6vQWSPDdgGTzOuxIdSLIGN6dVg%3D&st=2020-10-19T22%3A09%3A04Z&se=2020-11-19T22%3A14%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-19 23:26 UTC, opbld32 commented
Docs Build status updates of commit _[c9d2005](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/c9d20059f2d51fecbc934a20ca4d9c55ac4f1f16)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-19 23:27 UTC, opbld32 commented
Docs Build status updates of commit _[c9d2005](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/c9d20059f2d51fecbc934a20ca4d9c55ac4f1f16)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010192326048613-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HBWTw5QAO8AoaCqFIgeES0rfGfpck%2FYfMDsM0%2BN5Rcw%3D&st=2020-10-19T23%3A22%3A22Z&se=2020-11-19T23%3A27%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 17:33 UTC, opbld30 commented
Docs Build status updates of commit _[5b2d90c](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/5b2d90c75d1c970573a2f15682cf05a443058bb2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010201731463931-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rCgVrt6lBQAqNNajG91qwSTonBnfbDnGPy8VBM4Y5NE%3D&st=2020-10-20T17%3A28%3A07Z&se=2020-11-20T17%3A33%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 17:38 UTC, opbld32 commented
Docs Build status updates of commit _[e461103](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/e461103eaf58a9fda3cf9d7189af4fe8a61ad744)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010201736417206-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cG2CKBikPh1iFJ6hXOckBQJk%2BWVa%2FH2kf%2F2JvX0UoTs%3D&st=2020-10-20T17%3A33%3A03Z&se=2020-11-20T17%3A38%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 17:56 UTC, opbld34 commented
Docs Build status updates of commit _[1616b27](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/1616b2711e6eaf66f9a0ca3d9d7f12acf27621fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010201755023725-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=88W9ufD26r47Loq4IixwAaB%2BbnALTn5zOgAPAHBCDeM%3D&st=2020-10-20T17%3A51%3A16Z&se=2020-11-20T17%3A56%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 17:58 UTC, opbld31 commented
Docs Build status updates of commit _[5c78658](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/5c786584e9b356c20e2cc254438b7ce198a8e20d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010201756596348-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=v6EjckIItkVTdFhErBPjWvhGuZKGqNvHCsiDE7QrVj0%3D&st=2020-10-20T17%3A53%3A29Z&se=2020-11-20T17%3A58%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 18:13 UTC, opbld30 commented
Docs Build status updates of commit _[c02aa65](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/c02aa657292ec28e223a2cc32c2d48de854e8f95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010201812039802-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9sj2YIEUS8jUGH5mDg1839j7ovPsRfrBgFUm6r5dIJ8%3D&st=2020-10-20T18%3A08%3A24Z&se=2020-11-20T18%3A13%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 18:18 UTC, opbld34 commented
Docs Build status updates of commit _[821f216](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/821f216081fb9b1ea15e1a332ddceb21c3503a33)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010201817224791-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FiqXyeGJdh8O7UMfEhpGaqIxjbWJ3Yw8lO4QSai%2BMao%3D&st=2020-10-20T18%3A13%3A46Z&se=2020-11-20T18%3A18%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 18:23 UTC, opbld34 commented
Docs Build status updates of commit _[41a2ff2](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/41a2ff234935d4afc52eeb908f58f2326e26fee9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010201821364563-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=86CSG6nbE8eyP%2Bu9HENAhLBqiqDgpa8PIXq7ac%2FEFbs%3D&st=2020-10-20T18%3A18%3A04Z&se=2020-11-20T18%3A23%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 18:30 UTC, opbld30 commented
Docs Build status updates of commit _[3750997](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/3750997c921550f01af670331e0a0a9b89151b08)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010201828464744-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CCrlDlPPApp9FP8WczBmzoyRBGRZk71L2mIWNfpPspM%3D&st=2020-10-20T18%3A25%3A31Z&se=2020-11-20T18%3A30%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 19:34 UTC, opbld31 commented
Docs Build status updates of commit _[388f502](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/388f502c62fe3c7c4bdf9ae8227ceecc04139d6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010201933015075-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YUPueQc47Er3nO%2F3lg2k9Pr37SBZ8D5BObjbMqbL7yE%3D&st=2020-10-20T19%3A29%3A22Z&se=2020-11-20T19%3A34%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 19:48 UTC, opbld31 commented
Docs Build status updates of commit _[5f794d8](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/5f794d867716a672d90ebbe0c1b5c58306db61a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010201947139963-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LBVvbJqMvdoOZpr8%2B%2BipOzsCgGYtECWwR%2FMUUNzBEtM%3D&st=2020-10-20T19%3A43%3A32Z&se=2020-11-20T19%3A48%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 20:05 UTC, opbld34 commented
Docs Build status updates of commit _[ce04e94](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/ce04e94701dda70897d7b2cedbd9a46d849444c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202004158186-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oZyHqbF7hA8OdD3j5yIaC%2FNAlyDl0xlbgQCz62r6LeI%3D&st=2020-10-20T20%3A00%3A39Z&se=2020-11-20T20%3A05%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 20:16 UTC, opbld30 commented
Docs Build status updates of commit _[adbae28](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/adbae286ad5c4acd9eada919f80c8f4d487ed30b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202015268035-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MU2wrkwpSClfv6%2BiAM5w2ppjfq0d5vs72ox7Z%2BQz9ak%3D&st=2020-10-20T20%3A11%3A45Z&se=2020-11-20T20%3A16%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 20:25 UTC, opbld31 commented
Docs Build status updates of commit _[9653f84](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/9653f846c8b0884ce14c50404c05c2a88209c455)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202024280777-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RqNLICTql01H2fcYfKq0ME00WIpZ00VSlRmo%2FfCAfaA%3D&st=2020-10-20T20%3A20%3A48Z&se=2020-11-20T20%3A25%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 20:35 UTC, opbld32 commented
Docs Build status updates of commit _[c337b86](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/c337b86297c99771ebc8de17ac0eea0b4bdeb7ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202034274036-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4F1VgtkuQjNU9VzYprXFa%2FYCfaA5Ptx0m%2FoKFSpOZgg%3D&st=2020-10-20T20%3A30%3A47Z&se=2020-11-20T20%3A35%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 20:40 UTC, opbld30 commented
Docs Build status updates of commit _[ce279a2](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/ce279a2c1f6ce96629b1be4bc01fb205ac238e22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202039014173-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LF3inF%2F6IcEDziDGdq1eFBi%2BrS9WyazfD7cERKu97HU%3D&st=2020-10-20T20%3A35%3A25Z&se=2020-11-20T20%3A40%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 20:47 UTC, opbld30 commented
Docs Build status updates of commit _[294e735](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/294e735c722be642c0357c7a307e3446b097c35c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202045519574-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CZcF09yP2dALKqhDHrQ1qzv0WBYYCJex9iYlFYZWdzE%3D&st=2020-10-20T20%3A42%3A16Z&se=2020-11-20T20%3A47%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 20:54 UTC, opbld31 commented
Docs Build status updates of commit _[1875c17](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/1875c17978553e7e54828013045d6712eecbb4e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202052459145-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DF9D7MmSE%2BbY312UpgdeFCuLUybeEgPEtgldSSDGRgQ%3D&st=2020-10-20T20%3A49%3A26Z&se=2020-11-20T20%3A54%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 20:59 UTC, opbld33 commented
Docs Build status updates of commit _[46f3927](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/46f392797a2eda0ee43c0b75b3e73ac36109fc89)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202058228932-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FvS5ydR%2BvKrv5K4BF6Dg%2BAMRf1jqwLuudh8%2FIop33c8%3D&st=2020-10-20T20%3A54%3A51Z&se=2020-11-20T20%3A59%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 21:08 UTC, opbld34 commented
Docs Build status updates of commit _[afa64a1](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/afa64a1de4800d10c3b6b684df615a8ce788c630)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202107101971-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Jyyt55qXTYHOLlpDi7MKWeDkK4aoiII4fpKEN7Phuf8%3D&st=2020-10-20T21%3A03%3A29Z&se=2020-11-20T21%3A08%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 21:11 UTC, opbld32 commented
Docs Build status updates of commit _[52bb71a](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/52bb71ad06f0caff082f8c31e3662a5ab7d5160c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202110015694-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lzwTAv9A9d2PcbQFqXgfZx9jk5TqwYUaQNfFhRBo04M%3D&st=2020-10-20T21%3A06%3A21Z&se=2020-11-20T21%3A11%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 21:16 UTC, opbld32 commented
Docs Build status updates of commit _[57a8738](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/57a8738eb6f60a3f89da9f06e39b04c30598ac2d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202115341384-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iSuJ7TEvKHUEuvUfv1G5fnszqXvweRvGyUlfE1OkhAM%3D&st=2020-10-20T21%3A11%3A57Z&se=2020-11-20T21%3A16%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 21:22 UTC, opbld30 commented
Docs Build status updates of commit _[696fa25](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/696fa25c68d4d777c00efa2fede959d5caed5a28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementFileVersion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementFileVersion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202121219776-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Wy8RGKFUBESZXrZHnwStBW%2FZIsoNrUumfMrsZNaIezY%3D&st=2020-10-20T21%3A17%3A49Z&se=2020-11-20T21%3A22%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 21:25 UTC, opbld34 commented
Docs Build status updates of commit _[41e1ba2](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/41e1ba2521290f5097bdb01412a3e7dbf9e578d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementFileVersion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementFileVersion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-bb046a08-6e04498f)
[api-reference/beta/api/agreementFileVersion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementFileVersion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="bb046a08-6e04498f"></a>
### [api-reference/beta/api/agreementFileVersion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementFileVersion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementFileVersion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202124067259-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ps5f%2F8GZukrT23cJiJCd15Ag65ECvPTvmCbGkYxSdUI%3D&st=2020-10-20T21%3A20%3A24Z&se=2020-11-20T21%3A25%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 21:29 UTC, opbld32 commented
Docs Build status updates of commit _[f64ff53](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/f64ff538db36fa0516330d161b61805699b6802a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-8e019bb9-492de74a)
[api-reference/beta/api/agreementFileVersion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementFileVersion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="8e019bb9-492de74a"></a>
### [api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementfileversion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202128196995-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8CkU7vWOehUB9z0XDJQgoSO7%2BcI8OACXHOF%2BXqrbwqc%3D&st=2020-10-20T21%3A24%3A45Z&se=2020-11-20T21%3A29%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 21:31 UTC, opbld33 commented
Docs Build status updates of commit _[2bb3a20](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/2bb3a203e7bee0aee85e4b6c89aaa3a8b7e93a4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-8e019bb9-342f788f)
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="8e019bb9-342f788f"></a>
### [api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementfileversion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202128354560-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2agYVdfxEIgb2sc8vO4WTRrYrAUFmld7ANyzwnOZvIo%3D&st=2020-10-20T21%3A26%3A10Z&se=2020-11-20T21%3A31%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 21:46 UTC, opbld34 commented
Docs Build status updates of commit _[dcf48b0](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/dcf48b0ce57286f796ca3710c60f066c0a11fea0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-5b745571-4fe6e3a1)
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-8e019bb9-4fe6e3a1)
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="5b745571-4fe6e3a1"></a>
### [api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md)
 - **Line 43, Column 11**: **[Warning-file-not-found]** `````Invalid file link: 'agreementfiledata.md'.`````

<a id="8e019bb9-4fe6e3a1"></a>
### [api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementfileversion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202144526574-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Dq8rKKDTohVy8kHCrpfo%2BkwQ%2B0op0rzqT0bwtB3mqaM%3D&st=2020-10-20T21%3A41%3A13Z&se=2020-11-20T21%3A46%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 21:49 UTC, opbld31 commented
Docs Build status updates of commit _[9b588cf](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/9b588cfe5f52b639dce7d9b1ec31c1ecf98125c5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-5b745571-ed74fe39)
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-8e019bb9-ed74fe39)
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="5b745571-ed74fe39"></a>
### [api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md)
 - **Line 43, Column 11**: **[Warning-file-not-found]** `````Invalid file link: 'agreementfiledata.md'.`````

<a id="8e019bb9-ed74fe39"></a>
### [api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementfileversion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202147418785-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IzeuEMx9bvIpbMIc1OO1Q8HERVLg8WMGcUM9DmqT18k%3D&st=2020-10-20T21%3A43%3A59Z&se=2020-11-20T21%3A48%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 21:50 UTC, opbld33 commented
Docs Build status updates of commit _[5a51191](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/5a51191adccd78484309b49ebaaea64901fcf9ff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-5b745571-912677cb)
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-8e019bb9-912677cb)
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="5b745571-912677cb"></a>
### [api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md)
 - **Line 43, Column 11**: **[Warning-file-not-found]** `````Invalid file link: 'agreementfiledata.md'.`````

<a id="8e019bb9-912677cb"></a>
### [api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementfileversion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202148523254-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uwTYz9W9R27CukRVyl9LcXuKhPoOUYdgqJ93HPx%2FMYA%3D&st=2020-10-20T21%3A45%3A24Z&se=2020-11-20T21%3A50%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 21:52 UTC, opbld34 commented
Docs Build status updates of commit _[ec48b8e](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/ec48b8e328d24045d4aaf0ad94632cccdc903dfb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-5b745571-8361fc79)
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-8e019bb9-8361fc79)
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="5b745571-8361fc79"></a>
### [api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md)
 - **Line 43, Column 11**: **[Warning-file-not-found]** `````Invalid file link: 'agreementfiledata.md'.`````

<a id="8e019bb9-8361fc79"></a>
### [api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementfileversion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202151260694-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pdNV3xqRAkx7ihVA1zF8nZrllrIgBwCNYPGUXTQ9MC4%3D&st=2020-10-20T21%3A47%3A53Z&se=2020-11-20T21%3A52%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 21:54 UTC, opbld34 commented
Docs Build status updates of commit _[cacc9d4](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/cacc9d42627d929f43aaea3502d3c15aa2ba09fe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-5b745571-f7ddd97c)
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-8e019bb9-f7ddd97c)
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="5b745571-f7ddd97c"></a>
### [api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md)
 - **Line 43, Column 11**: **[Warning-file-not-found]** `````Invalid file link: 'agreementfiledata.md'.`````

<a id="8e019bb9-f7ddd97c"></a>
### [api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementfileversion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202152350918-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iBwZpTy7sR%2FLFbvSI5%2FqTJe4dz2SOnKmYKFRnCSfpxk%3D&st=2020-10-20T21%3A49%3A22Z&se=2020-11-20T21%3A54%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 21:56 UTC, opbld30 commented
Docs Build status updates of commit _[7cb6a6b](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/7cb6a6bb026081b86f6d4fe1fb948b82037ec5a6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-5b745571-6b45f363)
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-8e019bb9-6b45f363)
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="5b745571-6b45f363"></a>
### [api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md)
 - **Line 43, Column 11**: **[Warning-file-not-found]** `````Invalid file link: 'agreementfiledata.md'.`````

<a id="8e019bb9-6b45f363"></a>
### [api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementfileversion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202154533145-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kUfvg%2B9IvxiG2vmT2CBU37XvkncF5Gd44%2FeydIs7UHE%3D&st=2020-10-20T21%3A51%3A22Z&se=2020-11-20T21%3A56%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 21:57 UTC, opbld31 commented
Docs Build status updates of commit _[54af004](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/54af004f493c9749b58843d3332857e7f133e770)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-5b745571-fb7acf33)
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-8e019bb9-fb7acf33)
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="5b745571-fb7acf33"></a>
### [api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md)
 - **Line 43, Column 11**: **[Warning-file-not-found]** `````Invalid file link: 'agreementfiledata.md'.`````

<a id="8e019bb9-fb7acf33"></a>
### [api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementfileversion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202156243668-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Pmoe4i%2FF5IeNcHsKSHs3xC32UAcLkezIzqybJ2oTo4U%3D&st=2020-10-20T21%3A52%3A53Z&se=2020-11-20T21%3A57%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 22:02 UTC, opbld30 commented
Docs Build status updates of commit _[10b8567](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/10b85677aae697c5f7864e11f48db762d8c1030d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-5b745571-cc65bec9)
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-8e019bb9-cc65bec9)
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="5b745571-cc65bec9"></a>
### [api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md)
 - **Line 43, Column 11**: **[Warning-file-not-found]** `````Invalid file link: 'agreementfiledata.md'.`````

<a id="8e019bb9-cc65bec9"></a>
### [api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementfileversion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202201055352-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yMf2%2BwSoZd5AJBo4Ge946ZFNq0qlhvVyOspCNH1mWfc%3D&st=2020-10-20T21%3A57%3A24Z&se=2020-11-20T22%3A02%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 22:07 UTC, opbld34 commented
Docs Build status updates of commit _[105c413](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/105c413c65bd176b7cde55d42a62f0441b9c3bab)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-20 22:09 UTC, opbld30 commented
Docs Build status updates of commit _[105c413](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/105c413c65bd176b7cde55d42a62f0441b9c3bab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-5b745571-d809cc60)
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-8e019bb9-d809cc60)
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="5b745571-d809cc60"></a>
### [api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md)
 - **Line 43, Column 11**: **[Warning-file-not-found]** `````Invalid file link: 'agreementfiledata.md'.`````

<a id="8e019bb9-d809cc60"></a>
### [api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementfileversion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202207107562-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8x2WH7aYwYl1MBn%2FrMhcZHxrf3qYVVHHEpDic6%2BSgug%3D&st=2020-10-20T22%3A04%3A11Z&se=2020-11-20T22%3A09%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 22:18 UTC, opbld32 commented
Docs Build status updates of commit _[debdcc4](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/debdcc4f247d53c316bf561d90185c0521d70e41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-8e019bb9-1e5fde45)
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="8e019bb9-1e5fde45"></a>
### [api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementfileversion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202217369022-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=W%2BNjEu86SzaXysu%2FxLxfCrsTql9E6AKW3GhBUJlnq%2Fg%3D&st=2020-10-20T22%3A13%3A52Z&se=2020-11-20T22%3A18%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 22:20 UTC, opbld30 commented
Docs Build status updates of commit _[366b04d](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/366b04de91629ef0f7729f767f92624cb856c8c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-8e019bb9-28bcd799)
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="8e019bb9-28bcd799"></a>
### [api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementfileversion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202218359385-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=l0pqXL%2F1FlyRshrAaoNCvziSYsXrp%2Ff%2FFJhY37BUJxo%3D&st=2020-10-20T22%3A15%3A17Z&se=2020-11-20T22%3A20%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 22:21 UTC, opbld30 commented
Docs Build status updates of commit _[8a74a2f](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/8a74a2f457cc3c8dc999cf90c3a1d337df45ee25)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-8e019bb9-621d7abf)
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="8e019bb9-621d7abf"></a>
### [api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementfileversion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202219439060-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9W%2BhqGQGLFcRfgPaWSKOZVActFET1ZQFKcdZjw0wR6o%3D&st=2020-10-20T22%3A16%3A34Z&se=2020-11-20T22%3A21%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 22:23 UTC, opbld30 commented
Docs Build status updates of commit _[ad30663](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/ad30663a824799678cbb52ba0cf77566d20d0929)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) | [Details](#user-content-8e019bb9-12ee08c6)
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="8e019bb9-12ee08c6"></a>
### [api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get agreement' is duplicated with other articles: 'beta/api/agreementfileversion-get.md(10,1), beta/api/agreement-get.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202220429090-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qEevG2RqdPieNSp5Y9vmyXqjszyDtC9o8som0jwWrGM%3D&st=2020-10-20T22%3A18%3A00Z&se=2020-11-20T22%3A23%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 22:24 UTC, opbld32 commented
Docs Build status updates of commit _[2eb2d05](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/2eb2d0541b641c9e7a4f444d0f2a9d9018547da0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202222296337-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Z5vzDvXmVw4vGYuw4tww9qMdqPPUm27EYlhrdUfxNms%3D&st=2020-10-20T22%3A19%3A24Z&se=2020-11-20T22%3A24%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 22:44 UTC, opbld32 commented
Docs Build status updates of commit _[d019eeb](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/d019eeb2546385de1ca875a8e93567fc4780a1a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202243060246-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Bn0n4pOYLf6ncXyeLD%2BLchFzrIGFeBPSoGSd1Cclvgw%3D&st=2020-10-20T22%3A39%3A22Z&se=2020-11-20T22%3A44%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 22:45 UTC, opbld31 commented
Docs Build status updates of commit _[e64918c](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/e64918cdf327750a0690ea3bd71d7074bf4aafa5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202243366327-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1F2pTm1FUD%2F%2Fq%2Bznz5GSU%2BP%2FK5OEwACw1n30PbHZdeM%3D&st=2020-10-20T22%3A40%3A57Z&se=2020-11-20T22%3A45%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 22:57 UTC, opbld32 commented
Docs Build status updates of commit _[fcc37b0](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/fcc37b071434172bd9d8dfa63ae5c6bc2e8cd796)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementFileVersion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementFileVersion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202255448384-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NVjpa9840h7nKnxfsFsdb4BOjoTRPqqHjqtcr65bfdM%3D&st=2020-10-20T22%3A52%3A03Z&se=2020-11-20T22%3A57%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 23:03 UTC, opbld31 commented
Docs Build status updates of commit _[0f10109](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/0f10109eead0880f93f63b68cdbd11b23455a2e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202301550034-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PqkU2h7CQITUZYe4KjPelf2L3sn2QmhnnGlQTN3sOIM%3D&st=2020-10-20T22%3A58%3A19Z&se=2020-11-20T23%3A03%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 23:06 UTC, opbld34 commented
Docs Build status updates of commit _[fb65f22](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/fb65f22aa8e123158611292a15a1b05b2203a1b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010202305158783-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FZJAIlOy4uAht4DWqUKdjTWJKmC4oK4vUMg8m5B54zE%3D&st=2020-10-20T23%3A01%3A36Z&se=2020-11-20T23%3A06%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 01:02 UTC, opbld34 commented
Docs Build status updates of commit _[32e22f1](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/32e22f11d6d193eea5fc703e3fbda033e4680502)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010210101324061-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6NGbHUZeJl%2Bdqan1HCW31V65R%2B2PGRm1%2FpqkQLyNLrE%3D&st=2020-10-21T00%3A57%3A58Z&se=2020-11-21T01%3A02%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 01:04 UTC, opbld31 commented
Docs Build status updates of commit _[0a23635](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/0a23635bc3d5b4010ac81c44a2eada803c956ec8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010210102581238-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TbyYPfa9jRlKZtkYCaTB5l1hNE29efE00YHKj0RnhBw%3D&st=2020-10-21T00%3A59%3A20Z&se=2020-11-21T01%3A04%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 01:06 UTC, opbld30 commented
Docs Build status updates of commit _[b8cef02](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/b8cef02a00a3ced2c965e14b8ee560da48c0f2b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010210103331105-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mZrjbuyr%2BFzztq1MJ81DrON6g%2BZa5Url7v2f8IQcP8w%3D&st=2020-10-21T01%3A01%3A00Z&se=2020-11-21T01%3A06%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 01:10 UTC, opbld34 commented
Docs Build status updates of commit _[45ac38f](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/45ac38f9113e2ec1e568ab6c2ff0529d7fd17a09)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-post-agreementfilelocalizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-post-agreementfilelocalizations?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010210108371877-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oIbg2fRNSpRrG9qS6rCHMYWHbMxXcEtnQbQ7gaTlwME%3D&st=2020-10-21T01%3A05%3A06Z&se=2020-11-21T01%3A10%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 01:16 UTC, opbld34 commented
Docs Build status updates of commit _[cae1f43](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/cae1f438226166cf166603f7099f5daeb3234bac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfilelocalization-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/api/agreementfileversion-list.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfileversion-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfileversion-list?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010210115199007-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PECtldQJt58%2F1MDL%2FTXhTgxGNnZz%2F%2BuiuTI4fMV9gH4%3D&st=2020-10-21T01%3A11%3A43Z&se=2020-11-21T01%3A16%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 01:18 UTC, opbld34 commented
Docs Build status updates of commit _[4859084](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/48590848cefa8510ce6df4dc3c126a228fcfef8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010210115511020-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7a6Q0sR6n7sIMhvyUYX0hAEgGA5aNNCEpQeFWUkM5to%3D&st=2020-10-21T01%3A13%3A02Z&se=2020-11-21T01%3A18%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 16:26 UTC, opbld32 commented
Docs Build status updates of commit _[9b4f8a9](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/9b4f8a97670963cf202d23fb9ac1be07b8acd83c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010211625036600-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Vf14N5iRAWhZTR8wr3%2FqoZyftORLmeR4P0PpqaF%2FJc0%3D&st=2020-10-21T16%3A21%3A17Z&se=2020-11-21T16%3A26%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 16:35 UTC, opbld33 commented
Docs Build status updates of commit _[93662fc](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/93662fc5879d571b94020ef279ddc7faa260e27d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/agreementfilelocalization-get.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/api/agreementfilelocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/agreementfilelocalization-get?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010211633126985-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=I9zCag2TlKCvUzK3hzfp5zJEuT7zHkeDN%2BCPhuT5GiA%3D&st=2020-10-21T16%3A30%3A06Z&se=2020-11-21T16%3A35%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 17:20 UTC, opbld30 commented
Docs Build status updates of commit _[af564a4](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/af564a47aa9c9fdcef86dfd225f9ecc403c88f4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010211718072012-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GApgxbECY1ezMnLucE0QuiXXgpZFRmApI1VizDeL0b4%3D&st=2020-10-21T17%3A15%3A18Z&se=2020-11-21T17%3A20%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 17:23 UTC, opbld30 commented
Docs Build status updates of commit _[fd6a87b](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/fd6a87b36c505d963b0c2b476bc20b892f215e4f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010211721517218-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sxe7bN2UqofXiyoyCjAtTa6ET%2FPfQ%2FQ4D67X5sB13BI%3D&st=2020-10-21T17%3A18%3A19Z&se=2020-11-21T17%3A23%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 17:33 UTC, opbld31 commented
Docs Build status updates of commit _[0ddf82a](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/0ddf82a6c48fa142a8560ad54037a941bb0ac579)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010211731518036-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sTsImtsTAqxES%2B5VCApnkynvmkFjNOKARMj8kI8EUwI%3D&st=2020-10-21T17%3A28%3A21Z&se=2020-11-21T17%3A33%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 17:38 UTC, opbld31 commented
Docs Build status updates of commit _[0483207](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/04832074a3e85300fb4b07bd165169847c4e9a7c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010211736020860-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dUYyA%2BiVP%2FfdAcq63FR0SFyC6B7SsRt1TTRMFVohb2E%3D&st=2020-10-21T17%3A33%3A10Z&se=2020-11-21T17%3A38%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 17:53 UTC, opbld34 commented
Docs Build status updates of commit _[2726d7e](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/2726d7ec3efe40be57797037da7ecfcc6f69f81b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010211752228892-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=X1wMJ5DdDk79HhC%2FDiSVrlugCpuFItQpo%2FKKM7lW7sw%3D&st=2020-10-21T17%3A48%3A45Z&se=2020-11-21T17%3A53%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 18:01 UTC, opbld31 commented
Docs Build status updates of commit _[5007591](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/50075913f28d7810464f3762bab7a3497a23c657)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010211759007360-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YR7ewrZdKVtj8Q%2Fk01VGmLooBE958vUMjsRSL1EmcrM%3D&st=2020-10-21T17%3A56%3A11Z&se=2020-11-21T18%3A01%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-22 21:23 UTC, opbld33 commented
Docs Build status updates of commit _[6af4dc9](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/6af4dc9adb47553a904e21f1cd530c99cbb9d7a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010222121480728-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nw0MLDB8DLNCwUCSY4CoQi0RsQOKPWRjpCgz0%2B2mbGY%3D&st=2020-10-22T21%3A18%3A12Z&se=2020-11-22T21%3A23%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-22 21:28 UTC, opbld34 commented
Docs Build status updates of commit _[49c39e0](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/49c39e009acedbc312b5ffbf33bf3e2298f54146)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010222126557507-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Phw4kpDpAVhm19FRkVFBLliNiVRxWcOT7eW5%2Fuo%2F%2F2o%3D&st=2020-10-22T21%3A23%3A28Z&se=2020-11-22T21%3A28%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-22 21:35 UTC, opbld34 commented
Docs Build status updates of commit _[664479a](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/664479aa0ba5a63d67d099043bbf228d37358257)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010222133392463-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BELgKkBCApsP81JxfD7aZe3vgn68nTiC8pTVIjf5y%2Bo%3D&st=2020-10-22T21%3A30%3A13Z&se=2020-11-22T21%3A35%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-22 21:41 UTC, opbld30 commented
Docs Build status updates of commit _[ba52b21](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/ba52b21fdbdd764276fa5cb58d980bfc6465e182)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010222139577051-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NZV9iJWXaaVUDIlxkxgfXrJZkOZkrY%2FKjwFvOGwgPSw%3D&st=2020-10-22T21%3A36%3A22Z&se=2020-11-22T21%3A41%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-23 04:07 UTC, Lauragra commented
@rajadineshmurugesan-microsoft , please follow the get started steps to get set up as a contributor to the repo: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55085/Get-started-with-GitHub. Please also review the workflow topic and set labels on the PR as appropriate: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55055/Content-workflow.

2020-10-24 06:19 UTC, opbld34 commented
Docs Build status updates of commit _[87c4a9d](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/87c4a9dda0c1795cdbe783455775132ef0372122)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010240618033678-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=O0ESlP5Ye9Q7KV77LKOddCm3D3QvA20HZyKcJeEY%2B0k%3D&st=2020-10-24T06%3A14%3A32Z&se=2020-11-24T06%3A19%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 20:48 UTC, opbld33 commented
Docs Build status updates of commit _[cc08d23](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/cc08d23df3aca7ede97e5733035c0bf231d42bca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010282046456155-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8Ej%2FYt8zMuf4Vx7jyNTQ26R1NyhGPFkYOkTVFDO98Q4%3D&st=2020-10-28T20%3A43%3A14Z&se=2020-11-28T20%3A48%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-03 00:35 UTC, opbld34 commented
Docs Build status updates of commit _[d703d39](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/d703d3944e2b375d4932db2c879aa1c52464c838)_: 

:clock10: **Pending**: waiting for processors ([45](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 45 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-03 01:04 UTC, opbld32 commented
Docs Build status updates of commit _[d703d39](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/d703d3944e2b375d4932db2c879aa1c52464c838)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011030035224313-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BRrEuez5LHx28PIeFyxeACvSQpMwEt8FgEdtcISfAVA%3D&st=2020-11-03T00%3A59%3A14Z&se=2020-12-04T01%3A04%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-06 21:49 UTC, opbld31 commented
Docs Build status updates of commit _[db1505b](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/db1505bcec3a5bfa5c4eadb813cc365eed257d93)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011062148387263-10340%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8vLFPXaCs5flcGG8EpTXzVKkiqshpapu%2BbSsh4sE9x8%3D&st=2020-11-06T21%3A44%3A56Z&se=2020-12-07T21%3A49%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-09 19:31 UTC, opbld34 commented
Docs Build status updates of commit _[2f28b63](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/2f28b6397f0c584b17f2ee01df49f33812a316de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10340) | [Details](#user-content-075040e5-da958469)
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="075040e5-da958469"></a>
### [concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta`````
 - **Line 346, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 397, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta`````
 - **Line 435, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 635, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-1.0`````
 - **Line 635, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0`````
 - **Line 635, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/device?view=graph-rest-1.0`````
 - **Line 637, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/orgcontact?view=graph-rest-beta`````
 - **Line 637, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/schemaextension?view=graph-rest-beta`````
 - **Line 637, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta`````
 - **Line 765, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/drive-get-specialfolder?view=graph-rest-1.0`````
 - **Line 818, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta`````
 - **Line 818, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/administrativeunit?view=graph-rest-beta`````
 - **Line 1248, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1249, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-onlinemeetings?view=graph-rest-beta`````
 - **Line 1254, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1255, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1257, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1258, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1259, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-11-09 19:35 UTC, opbld33 commented
Docs Build status updates of commit _[b608b5f](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/b608b5f0583cb7e7263ed657b75870889bcd12a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10340) | [Details](#user-content-075040e5-a5475ca4)
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="075040e5-a5475ca4"></a>
### [concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta`````
 - **Line 346, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 397, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta`````
 - **Line 435, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 635, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-1.0`````
 - **Line 635, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0`````
 - **Line 635, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/device?view=graph-rest-1.0`````
 - **Line 637, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/orgcontact?view=graph-rest-beta`````
 - **Line 637, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/schemaextension?view=graph-rest-beta`````
 - **Line 637, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta`````
 - **Line 765, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/drive-get-specialfolder?view=graph-rest-1.0`````
 - **Line 818, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta`````
 - **Line 818, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/administrativeunit?view=graph-rest-beta`````
 - **Line 1248, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1249, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-onlinemeetings?view=graph-rest-beta`````
 - **Line 1254, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1255, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1257, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1258, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1259, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-11-09 19:50 UTC, opbld34 commented
Docs Build status updates of commit _[93822ad](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/93822add2ddf3c7b74c71ba68a24dff0252662fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10340) | [Details](#user-content-075040e5-b41082f8)
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="075040e5-b41082f8"></a>
### [concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta`````
 - **Line 346, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 397, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta`````
 - **Line 435, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 635, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-1.0`````
 - **Line 635, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0`````
 - **Line 635, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/device?view=graph-rest-1.0`````
 - **Line 637, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/orgcontact?view=graph-rest-beta`````
 - **Line 637, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/schemaextension?view=graph-rest-beta`````
 - **Line 637, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta`````
 - **Line 765, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/drive-get-specialfolder?view=graph-rest-1.0`````
 - **Line 818, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta`````
 - **Line 818, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/administrativeunit?view=graph-rest-beta`````
 - **Line 1248, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1249, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-onlinemeetings?view=graph-rest-beta`````
 - **Line 1254, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1255, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1257, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1258, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1259, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-11-12 22:41 UTC, raprakasMSFT commented on api-reference/beta/resources/agreement.md
>  |files|[agreementFileLocalization](agreementfilelocalization.md) collection| PDFs linked to this agreement. **Note:** This property is in the process of being deprecated. Usethe  **file** property in
please add a space between 'Use' and 'the'

2020-11-12 22:42 UTC, raprakasMSFT approved these changes
+1 pending comments

2020-11-12 22:46 UTC, opbld32 commented
Docs Build status updates of commit _[08ac806](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/08ac8062bab6e7344c004c6bd4f7e25495b13f5d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10340) | [Details](#user-content-075040e5-5f5f4307)
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="075040e5-5f5f4307"></a>
### [concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta`````
 - **Line 346, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 397, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta`````
 - **Line 435, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/device?view=graph-rest-1.0`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/orgcontact?view=graph-rest-beta`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/schemaextension?view=graph-rest-beta`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta`````
 - **Line 793, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/drive-get-specialfolder?view=graph-rest-1.0`````
 - **Line 846, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta`````
 - **Line 846, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/administrativeunit?view=graph-rest-beta`````
 - **Line 1276, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1277, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-onlinemeetings?view=graph-rest-beta`````
 - **Line 1282, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1283, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1285, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1286, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1287, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-11-12 22:48 UTC, opbld32 commented
Docs Build status updates of commit _[1ad3074](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/1ad30743efd6be4eaa8be1c894b07c04e7ec13fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10340) | [Details](#user-content-075040e5-5f3629e3)
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="075040e5-5f3629e3"></a>
### [concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta`````
 - **Line 346, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 397, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta`````
 - **Line 435, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/device?view=graph-rest-1.0`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/orgcontact?view=graph-rest-beta`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/schemaextension?view=graph-rest-beta`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta`````
 - **Line 793, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/drive-get-specialfolder?view=graph-rest-1.0`````
 - **Line 846, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta`````
 - **Line 846, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/administrativeunit?view=graph-rest-beta`````
 - **Line 1276, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1277, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-onlinemeetings?view=graph-rest-beta`````
 - **Line 1282, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1283, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1285, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1286, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1287, Column 1**: **[Suggestion-preserve-view-not-set]** `` [...]

2020-11-19 23:36 UTC, Lauragra commented on api-reference/beta/resources/agreement.md
> +|file/localizations/{localizationId}/versions|[agreementFileVersion](agreementfileversion.md) collection|The version history for the localized agreement file.|
I'm not sure about how we're referencing these relationship properties - this is not the standard structure. Where is the CSDL that shows this?

2020-11-19 23:37 UTC, Lauragra commented on concepts/permissions-reference.md
> +| App wants to create a group through AAD Graph | 	_Group.ReadWrite.All_ | Read and write all groups|
AAD -> Azure AD

2020-11-19 23:38 UTC, Lauragra commented on api-reference/beta/resources/agreementfileversion.md
> +<!--
Why are sections getting commented out in the file?

2020-11-19 23:38 UTC, Lauragra requested changes
This PR will require an update to the changlog MD and JSON files.

2020-11-23 23:19 UTC, rajadineshmurugesan-microsoft commented on api-reference/beta/resources/agreement.md
> +|file/localizations/{localizationId}/versions|[agreementFileVersion](agreementfileversion.md) collection|The version history for the localized agreement file.|
We are following the tenant branding pattern for 'localizations'. That's why it's not been shown as a relationship in the 'agreementFile' file. So, we wanted to explicitly mention this in here.

2020-11-23 23:21 UTC, rajadineshmurugesan-microsoft commented on concepts/permissions-reference.md
> +| App wants to create a group through AAD Graph | 	_Group.ReadWrite.All_ | Read and write all groups|
Oh. This wasn't our change. Nothing is changed here. I reverted some changes in this file, but still this is showing up.

2020-11-23 23:21 UTC, rajadineshmurugesan-microsoft commented on api-reference/beta/resources/agreementfileversion.md
> +<!--
Copy/Paste issue. Can remove it if needed.

2020-11-30 23:52 UTC, opbld34 commented
Docs Build status updates of commit _[2dc1d75](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/2dc1d753461d84be617fe17c847ee071bd03b7f6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10340) | [Details](#user-content-de0bbbbb-c9425e60)
[concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10340) | [Details](#user-content-075040e5-c9425e60)
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="de0bbbbb-c9425e60"></a>
### [concepts/changelog.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/changelog.md)
 - **Line 14, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Changelog for Microsoft Graph'.`````

<a id="075040e5-c9425e60"></a>
### [concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta`````
 - **Line 346, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 397, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta`````
 - **Line 435, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/device?view=graph-rest-1.0`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/orgcontact?view=graph-rest-beta`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/schemaextension?view=graph-rest-beta`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta`````
 - **Line 793, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/drive-get-specialfolder?view=graph-rest-1.0`````
 - **Line 846, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta`````
 - **Line 846, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/administrativeunit?view=graph-rest-beta`````
 - **Line 1276, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1277, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-onlinemeetings?view=graph-rest-beta`````
 - **Line 1282, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1283, Column 1**: **[Suggestion [...]

2020-11-30 23:58 UTC, opbld34 commented
Docs Build status updates of commit _[7762dbe](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/7762dbeeff6aa5b7df03095fabe13320f56a2677)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10340) | [Details](#user-content-de0bbbbb-5b5c63d3)
[concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10340) | [Details](#user-content-075040e5-5b5c63d3)
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |

<a id="de0bbbbb-5b5c63d3"></a>
### [concepts/changelog.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/changelog.md)
 - **Line 14, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Changelog for Microsoft Graph'.`````

<a id="075040e5-5b5c63d3"></a>
### [concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta`````
 - **Line 346, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 397, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta`````
 - **Line 435, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/device?view=graph-rest-1.0`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/orgcontact?view=graph-rest-beta`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/schemaextension?view=graph-rest-beta`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta`````
 - **Line 793, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/drive-get-specialfolder?view=graph-rest-1.0`````
 - **Line 846, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta`````
 - **Line 846, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/administrativeunit?view=graph-rest-beta`````
 - **Line 1276, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1277, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-onlinemeetings?view=graph-rest-beta`````
 - **Line 1282, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1283, Column 1**: **[Suggestion [...]

2020-12-01 00:01 UTC, rajadineshmurugesan-microsoft commented
Added the changelog

2020-12-01 17:58 UTC, opbld33 commented
Docs Build status updates of commit _[2fb6986](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/2fb69862b378d3d43945a405bf498ae3883e5d6f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10340) | [Details](#user-content-de0bbbbb-940b0403)
[concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10340) | [Details](#user-content-075040e5-940b0403)
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-940b0403"></a>
### [concepts/changelog.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/changelog.md)
 - **Line 14, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Changelog for Microsoft Graph'.`````
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participantInfo?view=graph-rest-beta`````

<a id="075040e5-940b0403"></a>
### [concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta`````
 - **Line 346, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 397, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta`````
 - **Line 435, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/device?view=graph-rest-1.0`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/orgcontact?view=graph-rest-beta`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/schemaextension?view=graph-rest-beta`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta`````
 - **Line 793, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/drive-get-specialfolder?view=graph-rest-1.0`````
 - **Line 846, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta`````
 - **Line 846, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/administrativeunit?view=graph-rest-beta`````
 - **Line 1276, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1277, Column 1**: **[Suggestion-preserve-view-no [...]

2020-12-01 20:24 UTC, opbld30 commented
Docs Build status updates of commit _[543aaf6](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/commits/543aaf66fc64707f7d24142c52143e4330521730)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10340) | [Details](#user-content-de0bbbbb-52555224)
[concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-10340) | [Details](#user-content-075040e5-52555224)
[api-reference/beta/resources/agreement.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfile.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfilelocalization.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfilelocalization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfilelocalization?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[api-reference/beta/resources/agreementfileversion.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/api-reference/beta/resources/agreementfileversion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreementfileversion?view=graph-rest-beta&branch=pr-en-us-10340) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-52555224"></a>
### [concepts/changelog.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/changelog.md)
 - **Line 14, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Changelog for Microsoft Graph'.`````
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participantInfo?view=graph-rest-beta`````

<a id="075040e5-52555224"></a>
### [concepts/permissions-reference.md](https://github.com/rajadineshmurugesan-microsoft/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta`````
 - **Line 346, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 397, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta`````
 - **Line 435, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/device?view=graph-rest-1.0`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/orgcontact?view=graph-rest-beta`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/schemaextension?view=graph-rest-beta`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta`````
 - **Line 793, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/drive-get-specialfolder?view=graph-rest-1.0`````
 - **Line 846, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/serviceprincipal?view=graph-rest-beta`````
 - **Line 846, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/administrativeunit?view=graph-rest-beta`````
 - **Line 1276, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/onlinemeeting-get?view=graph-rest-beta`````
 - **Line 1277, Column 1**: **[Suggestion-preserve-view-no [...]

2020-12-02 01:39 UTC, Lauragra approved these changes

2020-12-02 01:39 UTC, merged