Mentioning change notification in messaging docs
microsoftgraph/microsoft-graph-docs pull request #10344
Opened 2020-10-20 00:02 UTC by RamjotSingh

2020-10-20 00:03 UTC, opbld33 commented
Docs Build status updates of commit _[cc2679e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc2679eb1021e3e53de1a0c05615e842786e0a3f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-e3eec0c4-496e0eb4)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-9219d321-496e0eb4)
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-514b2e8b-496e0eb4)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-496e0eb4)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-97ee62ac-496e0eb4)

<a id="e3eec0c4-496e0eb4"></a>
### [api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md)
 - **Line 51, Column 49**: **[Warning-link-out-of-scope]** `````File '../concepts/webhooks-with-resource-data.md' referenced by link '../../../concepts/webhooks-with-resource-data.md' will not be built because it is not included in build scope.`````
 - **Line 53, Column 80**: **[Warning-file-not-found]** `````Invalid file link: 'team.md'.`````
 - **Line 54, Column 66**: **[Warning-file-not-found]** `````Invalid file link: 'chat.md'.`````
 - **Line 55, Column 110**: **[Warning-file-not-found]** `````Invalid file link: 'channel.md'.`````
 - **Line 55, Column 137**: **[Warning-file-not-found]** `````Invalid file link: 'team.md'.`````

<a id="9219d321-496e0eb4"></a>
### [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md)
 - **Line 55, Column 49**: **[Warning-link-out-of-scope]** `````File '../concepts/webhooks-with-resource-data.md' referenced by link '../../../concepts/webhooks-with-resource-data.md' will not be built because it is not included in build scope.`````
 - **Line 57, Column 80**: **[Warning-file-not-found]** `````Invalid file link: 'team.md'.`````
 - **Line 58, Column 110**: **[Warning-file-not-found]** `````Invalid file link: 'channel.md'.`````
 - **Line 58, Column 137**: **[Warning-file-not-found]** `````Invalid file link: 'team.md'.`````

<a id="514b2e8b-496e0eb4"></a>
### [api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md)
 - **Line 46, Column 86**: **[Warning-file-not-found]** `````Invalid file link: 'webhooks.md'.`````
 - **Line 48, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'subscription.md'.`````
 - **Line 50, Column 49**: **[Warning-link-out-of-scope]** `````File '../concepts/webhooks-with-resource-data.md' referenced by link '../../../concepts/webhooks-with-resource-data.md' will not be built because it is not included in build scope.`````
 - **Line 52, Column 66**: **[Warning-file-not-found]** `````Invalid file link: 'chat.md'.`````
 - **Line 53, Column 75**: **[Warning-file-not-found]** `````Invalid file link: 'chat.md'.`````

<a id="8f8d1d71-496e0eb4"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="97ee62ac-496e0eb4"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md)
 - **Line 52, Column 49**: **[Warning-link-out-of-scope]** `````File '../concepts/webhooks-with-resource-data.md' referenced by link '../../../concepts/webhooks-with-resource-data.md' will not be built because it is not included in build scope.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010200002030617-10344%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eZTOSv4FqmfhOL5t7bBaKcf%2BsmB60NLfk%2BfNIw17Ap4%3D&st=2020-10-19T23%3A58%3A19Z&se=2020-11-20T00%3A03%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;catego [...]

2020-10-20 00:08 UTC, opbld31 commented
Docs Build status updates of commit _[b3cb912](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3cb912ad932c2f98a7c16516f773f0366912fc2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-e3eec0c4-34f15117)
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-9219d321-34f15117)
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-514b2e8b-34f15117)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-34f15117)
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-97ee62ac-34f15117)

<a id="e3eec0c4-34f15117"></a>
### [api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md)
 - **Line 51, Column 49**: **[Warning-link-out-of-scope]** `````File '../concepts/webhooks-with-resource-data.md' referenced by link '../../../concepts/webhooks-with-resource-data.md' will not be built because it is not included in build scope.`````

<a id="9219d321-34f15117"></a>
### [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md)
 - **Line 55, Column 49**: **[Warning-link-out-of-scope]** `````File '../concepts/webhooks-with-resource-data.md' referenced by link '../../../concepts/webhooks-with-resource-data.md' will not be built because it is not included in build scope.`````

<a id="514b2e8b-34f15117"></a>
### [api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md)
 - **Line 50, Column 49**: **[Warning-link-out-of-scope]** `````File '../concepts/webhooks-with-resource-data.md' referenced by link '../../../concepts/webhooks-with-resource-data.md' will not be built because it is not included in build scope.`````

<a id="8f8d1d71-34f15117"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="97ee62ac-34f15117"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md)
 - **Line 52, Column 49**: **[Warning-link-out-of-scope]** `````File '../concepts/webhooks-with-resource-data.md' referenced by link '../../../concepts/webhooks-with-resource-data.md' will not be built because it is not included in build scope.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010200007060955-10344%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PLIKs8vT48GSLXt3mCv1VQIFhUUVXpxwl6QjbV1ImAI%3D&st=2020-10-20T00%3A03%3A30Z&se=2020-11-20T00%3A08%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 00:13 UTC, opbld30 commented
Docs Build status updates of commit _[7bd5191](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7bd51918105c3f24bf8ce175205b5d238cb63a9b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-cf6894fd)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |

<a id="8f8d1d71-cf6894fd"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010200012115803-10344%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GE9n6hWn1GzwT628C81EbvNOEMYIsPb8lluaFsGnVDA%3D&st=2020-10-20T00%3A08%3A44Z&se=2020-11-20T00%3A13%3A44Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 00:39 UTC, opbld32 commented
Docs Build status updates of commit _[89bfb1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89bfb1ea4111b4f6299c76507e0b913c098b81e4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-de2b93cd)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |

<a id="8f8d1d71-de2b93cd"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010200038149007-10344%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fAf1IRDthTiCvWe16b7ScNOyaDpyP0RgfFx35VwuCpk%3D&st=2020-10-20T00%3A34%3A21Z&se=2020-11-20T00%3A39%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 12:10 UTC, baywet approved these changes

2020-10-22 00:04 UTC, laujan approved these changes

2020-11-06 12:20 UTC, opbld34 commented
Docs Build status updates of commit _[3339f31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3339f31483f9243bf5825cd5712a537f1d0e206f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-8791df0d)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-8791df0d)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) | [Details](#user-content-b329d26c-8791df0d)
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) | [Details](#user-content-cde80c3f-8791df0d)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |

<a id="8f8d1d71-8791df0d"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-8791df0d"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 84, Column 282**: **[Warning-file-not-found]** `````Invalid file link: 'teamwork-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/r [...]

2020-11-06 12:28 UTC, opbld30 commented
Docs Build status updates of commit _[b4eed17](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4eed17662e9a268a1d1ba64656df7b0dd5122d1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-6a8f21c0)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-6a8f21c0)
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) | [Details](#user-content-cde80c3f-6a8f21c0)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-6a8f21c0"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-6a8f21c0"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 84, Column 320**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`` [...]

2020-11-06 12:35 UTC, opbld31 commented
Docs Build status updates of commit _[516e877](https://github.com/microsoftgraph/microsoft-graph-docs/commits/516e877b8e809330a21a3078212b7ee6b2afc846)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-9c744e9e)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-9c744e9e)
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) | [Details](#user-content-cde80c3f-9c744e9e)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-9c744e9e"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-9c744e9e"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 84, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`` [...]

2020-11-06 13:01 UTC, opbld30 commented
Docs Build status updates of commit _[5d9786d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d9786d19e5795dfb02fea64feef75209e19923c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-0ba1635d)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-0ba1635d)
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) | [Details](#user-content-cde80c3f-0ba1635d)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-0ba1635d"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-0ba1635d"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0` [...]

2020-11-06 13:08 UTC, opbld31 commented
Docs Build status updates of commit _[affc05b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/affc05b95ed34577b88e9e5abe06374109aeabc9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-bbbaf818)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-bbbaf818)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-bbbaf818"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-bbbaf818"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 62, Column 1**: * [...]

2020-11-06 13:23 UTC, baywet requested changes

2020-11-06 13:23 UTC, baywet commented on api-reference/beta/api/channel-list-messagereplies.md
> +> This API supports subcribing to changes (creation, updation and deletion) using [Graph change notifications](../resources/webhooks.md). This allows callers to subscribe and get changes in realtime.
```suggestion
> This API supports subscribing to changes (create, update and delete) using [change notifications](../resources/webhooks.md). This allows callers to subscribe and get changes in real-time. Please refer to [chatMessage](../resources/chatMessage.md) documentation for more details.
```

2020-11-06 13:23 UTC, baywet commented on api-reference/beta/api/channel-list-messages.md
> +> This API supports subcribing to changes (creation, updation and deletion) using [Graph change notifications](../resources/webhooks.md). This allows callers to subscribe and get changes in realtime.
```suggestion
> This API supports subscribing to changes (create, update and delete) using [change notifications](../resources/webhooks.md). This allows callers to subscribe and get changes in real-time. Please refer to [chatMessage](../resources/chatMessage.md) documentation for more details.
```

2020-11-06 13:23 UTC, baywet commented on api-reference/beta/api/chat-list-message.md
> +> This API supports subcribing to changes (creation, updation and deletion) using [Graph change notifications](../resources/webhooks.md). This allows callers to subscribe and get changes in realtime.
```suggestion
> This API supports subscribing to changes (create, update and delete) using [change notifications](../resources/webhooks.md). This allows callers to subscribe and get changes in real-time. Please refer to [chatMessage](../resources/chatMessage.md) documentation for more details.
```

2020-11-06 13:23 UTC, baywet commented on api-reference/beta/resources/chatmessage.md
>  `chatMessage` supports subcribing to changes (creation, updation and deletion) using [Graph change notifications](webhooks.md). This allows callers to subscribe and get changes in realtime.
```suggestion
`chatMessage` supports subscribing to changes (create, update and delete) using [change notifications](webhooks.md). This allows callers to subscribe and get changes in real-time.
```

2020-11-06 13:23 UTC, baywet commented on concepts/teams-concept-overview.md
> +Microsoft Teams supports subscribing to changes (creation, updation or deletion) to messages in [channels](/graph/api/resources/channel?view=graph-rest-1.0) and [chats](/graph/api/resources/channel?v
```suggestion
Microsoft Teams supports subscribing to changes (create, update or delete) to messages in [channels](/graph/api/resources/channel?view=graph-rest-1.0) and [chats](/graph/api/resources/channel?view=graph-rest-beta) to allows apps to get near-instant updates. You can refer to [chatMessage subscription](teamwork-changenotifications-chatMessage) documentation on how to subscribe to changes.
```

2020-11-06 13:23 UTC, baywet commented on concepts/teams-changenotifications-chatMessage.md
> +# Get notifications for messages in Microsoft Teams channels and chats
I'm not sure I see the value of such a page. All the information provided here is already detailed with code samples and more in the concepts pages at the exception of the use of $search to filter down notifications.

2020-11-06 13:25 UTC, opbld33 commented
Docs Build status updates of commit _[277909e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/277909ed3141b6988d120ffb6b5e13b5408658b8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-20ce6285)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-20ce6285)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-20ce6285"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-20ce6285"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 62, Column 1**: * [...]

2020-11-06 13:32 UTC, RamjotSingh commented on concepts/teams-changenotifications-chatMessage.md
> +# Get notifications for messages in Microsoft Teams channels and chats
Their are a couple of things this page has which other page does not
1. Details about permissions
2. Which paths support resource data and which dont
3. Filtering support

Additionally, we are planning to add more filters (a few are being worked on right now) and their is no other place to add those. Adding them to change notification concept pages will significantly bloat the page while not really serving a lot of purpose for non-teams readers.

Additionally I am trying to set a pattern as we look to add more resources (teams, membership etc) into the change notification world as well where no such example document would exist.

2020-11-06 13:35 UTC, opbld31 commented
Docs Build status updates of commit _[5d013a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d013a031789ccd8e4103e813d3aab0a3276c487)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-bc5cadea)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-bc5cadea)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-bc5cadea"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-bc5cadea"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 62, Column 1**: * [...]

2020-11-06 13:37 UTC, opbld31 commented
Docs Build status updates of commit _[020f0c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/020f0c715437e02cbde54a9eba7d0b04a4c30e6a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-d085835b)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-d085835b)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-d085835b"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-d085835b"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 62, Column 1**: * [...]

2020-11-06 14:09 UTC, opbld32 commented
Docs Build status updates of commit _[72818a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/72818a50514205206ad75cbd8225a4faeba8a490)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-eb7fdbc8)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-eb7fdbc8)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-eb7fdbc8"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-eb7fdbc8"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 62, Column 1**: * [...]

2020-11-06 14:10 UTC, baywet commented on concepts/teams-changenotifications-chatMessage.md
> +# Get notifications for messages in Microsoft Teams channels and chats
Thanks for the additional information.
1. permissions details can be found on the subscription CRUD operations pages, [like this one](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http)
2. list of paths supporting resource data can be found [here](https://docs.microsoft.com/en-us/graph/webhooks-with-resource-data#supported-resources). We should probably transform that into a table so it's easier to scan.
3. A filtering support section should probably be added [here](https://docs.microsoft.com/en-us/graph/webhooks), or we should create a generic page for all resources. The reason why I'm saying that is because Outlook messages now also supports filtering, Outlook events will soon do as well, and there are plans to support it for identity objects.

My intent is not to block progress in the documentation, this is great additional information. Simply to structure it in a way it can be reused for other resources, it doesn't duplicate content and that it'll be easy to maintain. I personally spend a lot of time and energy improving these docs sections.
Besides the tweaks I identified in the previous paragraph, the only additional work would then be to point to those different sections from the resources pages.

2020-11-06 19:25 UTC, RamjotSingh commented on concepts/teams-changenotifications-chatMessage.md
> +# Get notifications for messages in Microsoft Teams channels and chats
That page actually is part of the problem. We have heard from multiple customers that they did not even know we supported this. And a single page is a cognitive overload and will get no better as we try to add more and more stuff.

I was looking at the delta documentation and the new way actually derives from that. There is a top level doc talking just about what delta is and what you can do

https://docs.microsoft.com/en-us/graph/delta-query-overview?context=graph%2Fapi%2F1.0&view=graph-rest-1.0

And then their are child docs talking about specific resources supporting delta for example https://docs.microsoft.com/en-us/graph/delta-query-groups?view=graph-rest-1.0

The advantage here is, if I just want to deal with a specific resource type I have a dedicated page with just that info instead of sifting through a giant page picking things which are valid to me.

Additionally, a single giant doc makes it hard to explain and handle specific things like which paths support resource data in which scenario and in which scenario they don't or explaining different filters etc.

Is it possible to merge all of this in a single doc? Sure, absolutely. But the reasoning for not merging would be the same reason we don't put all of teams APIs in a single page and split them up. Give people dedicated reference points to read things up instead of throwing a lot of info and letting them parse to figure out what is relevant and what is not.

2020-11-06 19:31 UTC, opbld33 commented
Docs Build status updates of commit _[24bd7a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24bd7a9806e3da9ea331e720261af270954f0736)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-1b6da9ef)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-1b6da9ef)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-1b6da9ef"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-1b6da9ef"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 62, Column 1**: * [...]

2020-11-10 04:08 UTC, Lauragra commented on api-reference/beta/api/channel-list-messagereplies.md
> +## Subscribe for changes
I thought that for now we aren't going to introduce a new H2 section in the API topics and rely on the note and link?

2020-11-10 04:12 UTC, opbld33 commented
Docs Build status updates of commit _[4e9db08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e9db0841be997d88f465ba1a19827cb20f513ed)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-4ac7aaea)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-4ac7aaea)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-4ac7aaea"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-4ac7aaea"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 62, Column 1**: * [...]

2020-11-10 06:51 UTC, RamjotSingh commented on api-reference/beta/api/channel-list-messagereplies.md
> +## Subscribe for changes
Uh, miss, will remove.

2020-11-10 06:52 UTC, RamjotSingh commented on api-reference/beta/api/channel-list-messagereplies.md
> +## Subscribe for changes
Done.

2020-11-10 06:53 UTC, opbld34 commented
Docs Build status updates of commit _[4c0de37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c0de37cfaa96260a59abb217ed47f6cdd4391f7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-2b968732)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-2b968732)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-2b968732"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-2b968732"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 62, Column 1**: * [...]

2020-11-10 23:45 UTC, Lauragra commented on api-reference/beta/api/channel-list-messagereplies.md
> +#### Example 1: Getting replies to a message in a channel using GET API
There's only one example now so you can remove this heading, and the Request and Response sections can be H3s (###).

2020-11-10 23:48 UTC, opbld32 commented
Docs Build status updates of commit _[1d63c5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d63c5da2b0add29350b4c532d187475ce4bc6b5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-5b23cbfa)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-5b23cbfa)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-5b23cbfa"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-5b23cbfa"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 62, Column 1**: * [...]

2020-11-10 23:49 UTC, opbld30 commented
Docs Build status updates of commit _[1f4c79b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f4c79b291c607817eaa6c3487004af970073063)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-faa5df91)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-faa5df91)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-faa5df91"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-faa5df91"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 62, Column 1**: * [...]

2020-11-10 23:51 UTC, opbld32 commented
Docs Build status updates of commit _[7fc3720](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7fc37206a5030a18c05dbe47de94dd120c312c9d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-388d0407)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-388d0407)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-388d0407"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-388d0407"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 62, Column 1**: * [...]

2020-11-10 23:52 UTC, Lauragra commented on api-reference/beta/api/subscription-post-subscriptions.md
> +|[Chat message](../resources/chatmessage.md) | `chats/{id}/messages`, `chats/getAllMessages`, `teams/{id}/channels/{id}/messages`, `teams/getAllMessages` |
Please verify whether the teams: getAllMessages function is going to be removed, per discussion on PR #10174.

2020-11-10 23:55 UTC, RamjotSingh commented on api-reference/beta/api/subscription-post-subscriptions.md
> +|[Chat message](../resources/chatmessage.md) | `chats/{id}/messages`, `chats/getAllMessages`, `teams/{id}/channels/{id}/messages`, `teams/getAllMessages` |
allMessages is going away, getAllMessages replaces it. Hence I removed references to allMessages. The support removal is still TBD since we have a bunch of partners using it.

2020-11-10 23:55 UTC, opbld31 commented
Docs Build status updates of commit _[0e08471](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e0847187f72185a2a1bc7b88a450c40358ebe32)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-765064d1)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-765064d1)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-765064d1"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-765064d1"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 62, Column 1**: * [...]

2020-11-10 23:57 UTC, Lauragra commented on concepts/toc.yml
> +              - name: Get notifications for chatMessages (example)
You'll want to add this to the same section in the beta and v1.0 TOC files as well; those include the Develop content from the concept TOC for ease of reference. Also, please update the TOC entry to be "Get notifications for chat messages".

2020-11-11 00:02 UTC, Lauragra commented on concepts/teams-changenotifications-chatMessage.md
> +---
Suggest simplifying the file name to something like teams-change-notifications, unless you think you would have separate topics for different Teams resources that support change notifications? Seems like you can cover in one topic. Also note that file names need to be all lower case. If you rename the file, you'll need to update the links.

2020-11-11 00:04 UTC, opbld33 commented
Docs Build status updates of commit _[949816b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/949816b943765d291ec8f7051e599216f59a54b4)_: 

:clock10: **Pending**: waiting for processors ([7](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-11 00:06 UTC, opbld31 commented
Docs Build status updates of commit _[949816b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/949816b943765d291ec8f7051e599216f59a54b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-6765dbed)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-6765dbed)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatMessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-6765dbed"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-6765dbed"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 62, Column 1**: * [...]

2020-11-11 00:06 UTC, Lauragra commented on concepts/teams-changenotifications-chatMessage.md
> +Change notifications enable you to listen to changes (create, update and delete) to [messages](/graph/api/resources/chatMessage?view=graph-rest-1.0&preserve-view=true) in [channel](/graph/api/resourc
Your PR only updates the beta topics; in this article, you're linking to v1.0 topics. Also, should you update the channel and chat resource topics with the note text/link as well?

2020-11-11 00:07 UTC, RamjotSingh commented on concepts/teams-changenotifications-chatMessage.md
> +---
you guessed the intention right. We plan to have atleast 7-8 more resources in change notifications soon. Hence the intention was to have one page per resource (or club them if they are small). 

I can however lower case the filename.

2020-11-11 19:06 UTC, opbld34 commented
Docs Build status updates of commit _[85b305d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85b305d657ed35abe864b5f9bbdf1f417134ccc7)_: 

:clock10: **Pending**: waiting for processors ([8](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-11 19:07 UTC, opbld32 commented
Docs Build status updates of commit _[85b305d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85b305d657ed35abe864b5f9bbdf1f417134ccc7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-9df48ee6)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-9df48ee6)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage_?branch=pr-en-us-10344) | [Details](#user-content-b329d26c-9df48ee6)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatmessage_.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatmessage_.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage_?branch=pr-en-us-10344) |

<a id="8f8d1d71-9df48ee6"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-9df48ee6"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest- [...]

2020-11-11 19:09 UTC, opbld34 commented
Docs Build status updates of commit _[4cbaa0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4cbaa0d06e8deb4cde63e14b1eb48884d73cc3ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-6434605b)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-6434605b)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-6434605b"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-6434605b"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 317**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatMessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 62, Column 1**: * [...]

2020-11-11 19:41 UTC, opbld30 commented
Docs Build status updates of commit _[21f5008](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21f5008c549c376a000d25fc4ae2feeac5ae6aaa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-516c0f46)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-516c0f46)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-516c0f46"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-516c0f46"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 297**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatmessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post-messages?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 62, Column 1**: * [...]

2020-11-12 03:56 UTC, opbld34 commented
Docs Build status updates of commit _[2147afe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2147afed27a327be0e74def43714cc187c4eba83)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-f9e4c33c)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-f9e4c33c)
[concepts/webhooks-with-resource-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/webhooks-with-resource-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-with-resource-data?branch=pr-en-us-10344) | [Details](#user-content-a0e47f16-f9e4c33c)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-f9e4c33c"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-f9e4c33c"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 297**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatmessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to [...]

2020-11-12 04:04 UTC, opbld31 commented
Docs Build status updates of commit _[ea71e6d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea71e6d39106c7befa66031dfe39a589029bd51b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-17520f0e)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-17520f0e)
[concepts/webhooks-with-resource-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/webhooks-with-resource-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-with-resource-data?branch=pr-en-us-10344) | [Details](#user-content-a0e47f16-17520f0e)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-17520f0e"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-17520f0e"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 297**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatmessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to [...]

2020-11-12 04:06 UTC, opbld34 commented
Docs Build status updates of commit _[091f480](https://github.com/microsoftgraph/microsoft-graph-docs/commits/091f480a87193f9f8b46519567db332d90760c07)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-12 04:07 UTC, opbld34 commented
Docs Build status updates of commit _[091f480](https://github.com/microsoftgraph/microsoft-graph-docs/commits/091f480a87193f9f8b46519567db332d90760c07)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-055d14e1)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-055d14e1)
[concepts/webhooks-with-resource-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/webhooks-with-resource-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-with-resource-data?branch=pr-en-us-10344) | [Details](#user-content-a0e47f16-055d14e1)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-055d14e1"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-055d14e1"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 297**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatmessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to [...]

2020-11-12 04:08 UTC, opbld32 commented
Docs Build status updates of commit _[b413f7d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b413f7daec18b9d904a04bac7cfdc2123abcc935)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-12 04:09 UTC, opbld31 commented
Docs Build status updates of commit _[b413f7d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b413f7daec18b9d904a04bac7cfdc2123abcc935)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-b61c48b5)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-b61c48b5)
[concepts/webhooks-with-resource-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/webhooks-with-resource-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-with-resource-data?branch=pr-en-us-10344) | [Details](#user-content-a0e47f16-b61c48b5)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-b61c48b5"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-b61c48b5"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 326**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatmessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to [...]

2020-11-12 04:11 UTC, opbld34 commented
Docs Build status updates of commit _[f7f75fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7f75fd75f115074ca1daf4b9e10e9df37b97d1e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) | [Details](#user-content-8f8d1d71-8ffb44bf)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10344) | [Details](#user-content-e5711e5f-8ffb44bf)
[concepts/webhooks-with-resource-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/webhooks-with-resource-data.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-with-resource-data?branch=pr-en-us-10344) | [Details](#user-content-a0e47f16-8ffb44bf)
[api-reference/beta/api/channel-list-messagereplies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messagereplies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/channel-list-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/api/chat-list-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/chat-list-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-message?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10344) (graph-rest-beta) |
[concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-changenotifications-chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage?branch=pr-en-us-10344) |

<a id="8f8d1d71-8ffb44bf"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e5711e5f-8ffb44bf"></a>
### [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ramjsing/master-AddingChangeNotificationDocs/concepts/teams-concept-overview.md)
 - **Line 104, Column 326**: **[Warning-file-not-found]** `````Invalid file link: 'teams-changenotifications-chatmessage'.`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-put-teams?view=graph-rest-1.0`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-members?view=graph-rest-1.0`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/channel-post?view=graph-rest-1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-post-events?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/team-archive?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/group-delete?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamstab?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/team?view=graph-rest-1.0`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/channel?view=graph-rest-1.0`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-add?view=graph-rest-1.0`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamstab-add?view=graph-rest-1.0`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to [...]

2020-11-12 04:14 UTC, Lauragra approved these changes

2020-11-12 04:22 UTC, merged