1242148-docs ga proactive messaging and installed apps
microsoftgraph/microsoft-graph-docs pull request #10368
Opened 2020-10-21 08:59 UTC by KirtiPereira

Promoted the 4 method beta files to v1.0 and updated the resource and toc files in v1.0.

2020-10-21 09:00 UTC, opbld31 commented
Docs Build status updates of commit _[4d9566e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d9566e39536abf65162661d4905e711fa7298b5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6971255e)

<a id="6971255e"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010210900047811-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vAPTAQdbZChM9I9rCkV5ERm5YZSfVciqv5UPB%2B%2BdSuw%3D&st=2020-10-21T08%3A55%3A31Z&se=2020-11-21T09%3A00%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 23:07 UTC, opbld30 commented
Docs Build status updates of commit _[49b8047](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49b80474cd0476d888b3fa913c69d2d30f0b9243)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-37db38c1-abc0bc43)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-abc0bc43)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="37db38c1-abc0bc43"></a>
### [api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md)
 - **Line 14, Column 61**: **[Warning-file-not-found]** `````Invalid file link: 'chat.md'.`````

<a id="de0bbbbb-abc0bc43"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 90, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '| Change type | Version   | Description                          |
| :-------------- | :------------ | :--------------------------------------- |
| Addition | v1.0 | Added List apps for user, Add app for user, Remove app for user, and Upgrade installed app for user methods to the teamsAppInstallation resource. |') are not allowed. You can only have one top-level heading.
`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateaccountsummary?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategorysummary?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to  [...]

2020-10-21 23:15 UTC, opbld30 commented
Docs Build status updates of commit _[edbae17](https://github.com/microsoftgraph/microsoft-graph-docs/commits/edbae1750365079038eff5634a34e7ff5dc38398)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-4e73d9b3)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-4e73d9b3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 90, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '| Change type | Version   | Description                          |
| :-------------- | :------------ | :--------------------------------------- |
| Addition | v1.0 | Added List apps for user, Add app for user, Remove app for user, and Upgrade installed app for user methods to the teamsAppInstallation resource. |') are not allowed. You can only have one top-level heading.
`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateaccountsummary?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategorysummary?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateconfiguration?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdate [...]

2020-10-21 23:26 UTC, laujan approved these changes

2020-10-22 03:28 UTC, Lauragra commented on api-reference/v1.0/api/user-add-teamsappinstallation.md
> +
Global: The request examples are missing.

2020-10-22 03:29 UTC, Lauragra commented on api-reference/v1.0/api/user-add-teamsappinstallation.md
> +# Install app for user
I realize that this is a copy of what's currently in beta, but in looking at this, I think the file name should be user-post-teamsappinstallation, and the title should be Create teamsAppInstallation.

2020-10-22 03:33 UTC, Lauragra commented on api-reference/v1.0/api/user-delete-teamsappinstallation.md
> +# Uninstall app for user
Delete teamsAppInstallation

2020-10-22 03:34 UTC, Lauragra commented on api-reference/v1.0/api/user-list-teamsappinstallation.md
> +title: "List apps installed for user"
List teamsAppInstallation

2020-10-22 03:35 UTC, Lauragra commented on api-reference/v1.0/api/user-upgrade-teamsappinstallation.md
> +# Upgrade installed app for user
The H1 should match the title, "teamsAppInstallation: upgrade".

2020-10-22 03:37 UTC, Lauragra commented on api-reference/v1.0/resources/teamsappinstallation.md
> +Represents a [teamsApp](teamsapp.md) installed in a [team](team.md), a [chat](/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true) (in beta), or the personal scope of a [user](user.md).
If chat doesn't apply to v1.0, remove from the content. You can mention it in the teamsAppInstallation topic in the /beta folder/beta TOC.

2020-10-22 03:38 UTC, opbld30 commented
Docs Build status updates of commit _[04abd93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04abd93e89255503eed1233c77bffd8e44d40f3e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-d8189f70)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-d8189f70"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 90, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '| Change type | Version   | Description                          |
| :-------------- | :------------ | :--------------------------------------- |
| Addition | v1.0 | Added List apps for user, Add app for user, Remove app for user, and Upgrade installed app for user methods to the teamsAppInstallation resource. |') are not allowed. You can only have one top-level heading.
`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-list?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-get?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-add?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-update?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/conversationmember-delete?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/conversationmember?view=graph-rest-beta`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/aaduserconversationmember?view=graph-rest-beta`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateaccountsummary?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdatecategorysummary?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateconfiguration?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdate [...]

2020-10-22 03:40 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +        - name: List apps for user
These should also be represented under Users in the v1.0 TOC, as per beta. Please add, and reconcile the TOC entries with the topic titles.

2020-10-22 03:40 UTC, Lauragra commented on api-reference/v1.0/toc.yml
>            href: api/teamsappinstallation-delete.md
Should we rename the "App" node to be called "Installed apps"?

2020-10-22 03:41 UTC, Lauragra requested changes
Please review and incorporate content review comments.

2020-10-22 04:33 UTC, opbld32 commented
Docs Build status updates of commit _[02c6edb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02c6edbb6ec12d84cf5681f9d09ee5e9b1fbdc7e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-be21cc30)

<a id="be21cc30"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010220432511651-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ASZwJoPyAWSVA3sdetub5zc4lovrIhI4Vo%2F8MPkEZ9s%3D&st=2020-10-22T04%3A28%3A18Z&se=2020-11-22T04%3A33%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-22 04:42 UTC, opbld34 commented
Docs Build status updates of commit _[c0a822a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0a822a0f60a85c96325b8c76dbe7c2435f21303)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9b6105e1)

<a id="9b6105e1"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010220441370769-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UamwicvQ9uPt%2B0AQR14kWOz41wGwgkipGmT%2FWx0Cb%2BA%3D&st=2020-10-22T04%3A37%3A02Z&se=2020-11-22T04%3A42%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-22 05:05 UTC, opbld32 commented
Docs Build status updates of commit _[5d753f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d753f6bdd8cfad0e20f3d2d95dc3c9fb20329d5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-900aa293)

<a id="900aa293"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010220505237833-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=v8S8ErFW2IDTBtHW2XJ6aosAzDVbch%2BcJmzumdD7Qdc%3D&st=2020-10-22T05%3A00%3A53Z&se=2020-11-22T05%3A05%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-22 05:12 UTC, opbld33 commented
Docs Build status updates of commit _[100f857](https://github.com/microsoftgraph/microsoft-graph-docs/commits/100f857371a0a90cccbf9f40118768a9a34dfe2e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fb68a573)

<a id="fb68a573"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010220512178975-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Jte%2Bps1OPvlcOOiPykRkzTWr7NNy00LzBQ8ZuTdBc6M%3D&st=2020-10-22T05%3A07%3A43Z&se=2020-11-22T05%3A12%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-22 06:11 UTC, opbld30 commented
Docs Build status updates of commit _[c890607](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c890607d1f01ea81a0f4e30b5b316bb3ecbee1de)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-66e78c7f)

<a id="66e78c7f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010220610371621-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2B%2BJ6a%2F8nxtarxYVfEqL6hcvHv2J7dJ0RNIn4oirwrY4%3D&st=2020-10-22T06%3A06%3A03Z&se=2020-11-22T06%3A11%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-22 06:42 UTC, opbld34 commented
Docs Build status updates of commit _[4e59fd6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e59fd65d3155fbbd3779cdf1d754489f3c56e3e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :x:Error | | [Details](#user-content-92e5a554-4c7ceffb)
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :x:Error | | [Details](#user-content-4ba39843-4c7ceffb)
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :x:Error | | [Details](#user-content-d80ab607-4c7ceffb)
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :x:Error | | [Details](#user-content-85164b13-4c7ceffb)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-4c7ceffb)

<a id="92e5a554-4c7ceffb"></a>
### [api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md)
 - **Line 70, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/user-add-teamsapp-csharp-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/user-add-teamsapp-javascript-snippets.md'.`````
 - **Line 76, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/user-add-teamsapp-objc-snippets.md'.`````

<a id="4ba39843-4c7ceffb"></a>
### [api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md)
 - **Line 61, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/user-delete-teamsapp-csharp-snippets.md'.`````
 - **Line 64, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/user-delete-teamsapp-javascript-snippets.md'.`````
 - **Line 67, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/user-delete-teamsapp-objc-snippets.md'.`````

<a id="d80ab607-4c7ceffb"></a>
### [api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md)
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/user-list-teamsapps-csharp-snippets.md'.`````
 - **Line 72, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/user-list-teamsapps-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/user-list-teamsapps-objc-snippets.md'.`````

<a id="85164b13-4c7ceffb"></a>
### [api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md)
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/user-upgrade-teamsapp-csharp-snippets.md'.`````
 - **Line 65, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/user-upgrade-teamsapp-javascript-snippets.md'.`````
 - **Line 68, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/user-upgrade-teamsapp-objc-snippets.md'.`````

<a id="de0bbbbb-4c7ceffb"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-10-22 07:04 UTC, opbld33 commented
Docs Build status updates of commit _[c045b47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c045b474eb5efb411fdb656ca4040e6b7816e09f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :x:Error | | [Details](#user-content-92e5a554-33349236)
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :x:Error | | [Details](#user-content-4ba39843-33349236)
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :x:Error | | [Details](#user-content-d80ab607-33349236)
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :x:Error | | [Details](#user-content-85164b13-33349236)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-33349236)

<a id="92e5a554-33349236"></a>
### [api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md)
 - **Line 70, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/user-add-teamsapp-csharp-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/user-add-teamsapp-javascript-snippets.md'.`````
 - **Line 76, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/user-add-teamsapp-objc-snippets.md'.`````

<a id="4ba39843-33349236"></a>
### [api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md)
 - **Line 61, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/user-delete-teamsapp-csharp-snippets.md'.`````
 - **Line 64, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/user-delete-teamsapp-javascript-snippets.md'.`````
 - **Line 67, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/user-delete-teamsapp-objc-snippets.md'.`````

<a id="d80ab607-33349236"></a>
### [api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md)
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/user-list-teamsapps-csharp-snippets.md'.`````
 - **Line 72, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/user-list-teamsapps-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/user-list-teamsapps-objc-snippets.md'.`````

<a id="85164b13-33349236"></a>
### [api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md)
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/user-upgrade-teamsapp-csharp-snippets.md'.`````
 - **Line 65, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/user-upgrade-teamsapp-javascript-snippets.md'.`````
 - **Line 68, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/user-upgrade-teamsapp-objc-snippets.md'.`````

<a id="de0bbbbb-33349236"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-10-22 07:09 UTC, opbld32 commented
Docs Build status updates of commit _[1383aa4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1383aa414d7b6197f28b718c2534a3d9cbe694ae)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :x:Error | | [Details](#user-content-4ba39843-a493db9c)
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :x:Error | | [Details](#user-content-d80ab607-a493db9c)
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :x:Error | | [Details](#user-content-85164b13-a493db9c)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-a493db9c)

<a id="4ba39843-a493db9c"></a>
### [api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md)
 - **Line 61, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/user-delete-teamsapp-csharp-snippets.md'.`````
 - **Line 64, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/user-delete-teamsapp-javascript-snippets.md'.`````
 - **Line 67, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/user-delete-teamsapp-objc-snippets.md'.`````

<a id="d80ab607-a493db9c"></a>
### [api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md)
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/user-list-teamsapps-csharp-snippets.md'.`````
 - **Line 72, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/user-list-teamsapps-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/user-list-teamsapps-objc-snippets.md'.`````

<a id="85164b13-a493db9c"></a>
### [api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md)
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/user-upgrade-teamsapp-csharp-snippets.md'.`````
 - **Line 65, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/user-upgrade-teamsapp-javascript-snippets.md'.`````
 - **Line 68, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/user-upgrade-teamsapp-objc-snippets.md'.`````

<a id="de0bbbbb-a493db9c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob [...]

2020-10-22 07:10 UTC, opbld34 commented
Docs Build status updates of commit _[00e9178](https://github.com/microsoftgraph/microsoft-graph-docs/commits/00e91782b62b0f13203ed8a9d135ad3e0a308237)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :x:Error | | [Details](#user-content-4ba39843-896c285d)
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :x:Error | | [Details](#user-content-d80ab607-896c285d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-896c285d)

<a id="4ba39843-896c285d"></a>
### [api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md)
 - **Line 61, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/user-delete-teamsapp-csharp-snippets.md'.`````
 - **Line 64, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/user-delete-teamsapp-javascript-snippets.md'.`````
 - **Line 67, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/user-delete-teamsapp-objc-snippets.md'.`````

<a id="d80ab607-896c285d"></a>
### [api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md)
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/user-list-teamsapps-csharp-snippets.md'.`````
 - **Line 72, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/user-list-teamsapps-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/user-list-teamsapps-objc-snippets.md'.`````

<a id="de0bbbbb-896c285d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-v [...]

2020-10-22 07:12 UTC, opbld32 commented
Docs Build status updates of commit _[a6a45d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a6a45d1671d84f92b64407daf6270beb30d0558c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :x:Error | | [Details](#user-content-4ba39843-4c25b270)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-4c25b270)

<a id="4ba39843-4c25b270"></a>
### [api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md)
 - **Line 61, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/user-delete-teamsapp-csharp-snippets.md'.`````
 - **Line 64, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/user-delete-teamsapp-javascript-snippets.md'.`````
 - **Line 67, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/user-delete-teamsapp-objc-snippets.md'.`````

<a id="de0bbbbb-4c25b270"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjobstatus?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-no [...]

2020-10-22 07:14 UTC, opbld33 commented
Docs Build status updates of commit _[eb24ea8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb24ea8179cc7de6d71d1f66b73c5f796048f0f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-8d3c96dd)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-8d3c96dd"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spec [...]

2020-10-22 07:22 UTC, opbld31 commented
Docs Build status updates of commit _[f3cf66c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3cf66cb51f49e6f9d8692f676fc2d2b2659cbf3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-b7b3a383)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-b7b3a383"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spec [...]

2020-10-22 07:24 UTC, opbld31 commented
Docs Build status updates of commit _[f8614bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8614bcbd1d3bbaea4def53c7fb085663730cf84)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-17b92afb)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-17b92afb"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spec [...]

2020-10-22 07:26 UTC, opbld30 commented
Docs Build status updates of commit _[a415f3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a415f3a2ee1655fde1c0a766c8f1a074ddcb776e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-b7e40098)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-b7e40098"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spec [...]

2020-10-22 07:28 UTC, opbld34 commented
Docs Build status updates of commit _[378cf04](https://github.com/microsoftgraph/microsoft-graph-docs/commits/378cf04d08de12de697bc9cc33c696dbd17f5e77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-3adf28fc)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-3adf28fc"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spec [...]

2020-10-22 07:39 UTC, opbld32 commented
Docs Build status updates of commit _[6d097c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6d097c675de383a9f0675190bd0734848cb43691)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-d685b32f)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-d685b32f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spec [...]

2020-10-22 07:45 UTC, KirtiPereira commented on api-reference/v1.0/api/user-add-teamsappinstallation.md
> +# Install app for user
@laujan - request you to please confirm about the changes to the file name and the title. Will need to update the TOC and Change Log accordingly.

2020-10-22 08:29 UTC, opbld34 commented
Docs Build status updates of commit _[8a55eb0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a55eb020e46ec24f71622723cc8054fb157f600)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-a723c715)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-a723c715"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spec [...]

2020-10-22 08:32 UTC, opbld32 commented
Docs Build status updates of commit _[3521834](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35218342c22a79610959a01149e8b23d6bb758d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-6f1c105e)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-6f1c105e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spec [...]

2020-10-22 08:34 UTC, opbld31 commented
Docs Build status updates of commit _[aba2096](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aba20966000b340f9990d2e7dc9f6ed4235466a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-69c0e928)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-69c0e928"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 41, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 43, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a spec [...]

2020-10-24 03:25 UTC, AkJo commented on api-reference/v1.0/api/user-add-teamsappinstallation.md
> +# Install app for user
@Lauragra , the type teamsAppInstallation can appear in different scenarios, and the each one of those scenarios should have a dedicated page for it.

As of today, a teamsAppInstallation can be in the context of a user, or of a team, or of a chat. Each one of these will have a different API and permission set.

In the current case, 
/users/id/teamwork/installedApps pertains to teams app installed in the personal scope of a user. This API should have its dedicated file titled 'user-add-teamsappinstallation.md' or 'userteamwork-add-teamsappinstallation.md'.

Soon separate files for 
/teams/id/installedApps
and /chats/id/installedApps with the names 'user-add-teamsappinstallation.md' and 'chat-add-teamsappinstallation.md' will come.

2020-10-24 03:27 UTC, AkJo commented on api-reference/v1.0/api/user-add-teamsappinstallation.md
> +|Delegated (work or school account) | TeamsAppInstallation.ReadWriteForUser |
TeamsAppInstallation.ReadWriteSelfForUser, TeamsAppInstallation.ReadWriteForUser, TeamsAppInstallation.ReadWrite

2020-10-24 03:27 UTC, AkJo commented on api-reference/v1.0/api/user-add-teamsappinstallation.md
> +|Application | TeamsAppInstallation.ReadWriteForUser.All |
TeamsAppInstallation.ReadWriteSelfForUser.All, TeamsAppInstallation.ReadWriteForUser.All, TeamsAppInstallation.ReadWrite.All

2020-10-24 03:29 UTC, AkJo commented on api-reference/v1.0/api/user-delete-teamsappinstallation.md
> +|Delegated (work or school account) | TeamsAppInstallation.ReadWriteForUser |
TeamsAppInstallation.ReadWriteSelfForUser, TeamsAppInstallation.ReadWriteForUser, TeamsAppInstallation.ReadWrite

2020-10-24 03:29 UTC, AkJo commented on api-reference/v1.0/api/user-delete-teamsappinstallation.md
> +|Application | TeamsAppInstallation.ReadWriteForUser.All |
TeamsAppInstallation.ReadWriteSelfForUser.All, TeamsAppInstallation.ReadWriteForUser.All, TeamsAppInstallation.ReadWrite.All

2020-10-24 03:30 UTC, AkJo commented on api-reference/v1.0/api/user-list-teamsappinstallation.md
> +|Delegated (work or school account) | TeamsAppInstallation.ReadForUser, TeamsAppInstallation.ReadWriteForUser |
TeamsAppInstallation.ReadSelfForUser, TeamsAppInstallation.ReadForUser, TeamsAppInstallation.Read, TeamsAppInstallation.ReadWriteSelfForUser, TeamsAppInstallation.ReadWriteForUser, TeamsAppInstallation.ReadWrite

2020-10-24 03:31 UTC, AkJo commented on api-reference/v1.0/api/user-list-teamsappinstallation.md
> +|Application | TeamsAppInstallation.ReadForUser.All, TeamsAppInstallation.ReadWriteForUser.All |
TeamsAppInstallation.ReadSelfForUser.All, TeamsAppInstallation.ReadForUser.All, TeamsAppInstallation.Read.All,TeamsAppInstallation.ReadWriteSelfForUser.All, TeamsAppInstallation.ReadWriteForUser.All, TeamsAppInstallation.ReadWrite.All

2020-10-24 03:34 UTC, AkJo commented on api-reference/v1.0/api/user-upgrade-teamsappinstallation.md
> +|Delegated (work or school account) | TeamsAppInstallation.ReadWriteForUser |
TeamsAppInstallation.ReadWriteSelfForUser, TeamsAppInstallation.ReadWriteForUser, TeamsAppInstallation.ReadWrite

2020-10-24 03:34 UTC, AkJo commented on api-reference/v1.0/api/user-upgrade-teamsappinstallation.md
> +|Application | TeamsAppInstallation.ReadWriteForUser.All |
TeamsAppInstallation.ReadWriteSelfForUser.All, TeamsAppInstallation.ReadWriteForUser.All, TeamsAppInstallation.ReadWrite.All

2020-10-24 03:37 UTC, AkJo commented on api-reference/v1.0/toc.yml
>            href: api/teamsappinstallation-delete.md
You could...

The "teamsApp"s are represented by the "App catalog" node.

2020-10-24 03:41 UTC, AkJo commented on api-reference/v1.0/toc.yml
> +        - name: List apps for user
@Lauragra , this is functionality specific to Teams which is denoted by the node Teamwork. There is no 'User' node under teamwork as of today.

If by your comment, you meant adding something like below, then yes, please go for it.
![image](https://user-images.githubusercontent.com/25969716/97067208-0e937f80-1570-11eb-8d6a-9f5607755927.png)

2020-10-24 03:51 UTC, AkJo commented on api-reference/v1.0/resources/teamsappinstallation.md
> +| id                  | string   | A unique ID (not the team's app ID). |
not the Teams app ID 


The term 'Teams' over here implies the name of the product.

2020-10-24 04:04 UTC, AkJo commented on api-reference/v1.0/toc.yml
> +        - name: Add app for user
Also, neither of these should appear in the TOC, please remove them:

![image](https://user-images.githubusercontent.com/25969716/97067563-4cde6e00-1573-11eb-88aa-cf24939df41a.png)

2020-10-24 04:30 UTC, AkJo commented on api-reference/v1.0/api/user-add-teamsappinstallation.md
> +title: "Create teamsAppInstallation"
Create userScopeTeamsAppInstallation

2020-10-27 05:38 UTC, opbld34 commented
Docs Build status updates of commit _[e44b8bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e44b8bd183875aec1ab15c7acc43d6aa79edb364)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-02830898)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-02830898"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific v [...]

2020-10-27 05:39 UTC, opbld31 commented
Docs Build status updates of commit _[2087424](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20874247ef54e441a6ee84462a3534b340f53232)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-36f6b368)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-36f6b368"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific v [...]

2020-10-27 05:44 UTC, opbld30 commented
Docs Build status updates of commit _[697c0b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/697c0b2a7cc71ac1891f6ec746a620b761d275d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-dfff2bfa)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-dfff2bfa"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific v [...]

2020-10-27 05:53 UTC, opbld31 commented
Docs Build status updates of commit _[a689f65](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a689f652f46a85ff1604e179f24fe92fa1cad2fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-db22d8dd)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-db22d8dd"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific v [...]

2020-10-27 06:07 UTC, opbld33 commented
Docs Build status updates of commit _[3f13dec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f13dec1fc2a91be8ac4f0152a9fba51c8480893)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-b5e6569c)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-b5e6569c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific v [...]

2020-10-27 06:49 UTC, KirtiPereira commented on api-reference/v1.0/resources/teamsappinstallation.md
> +Represents a [teamsApp](teamsapp.md) installed in a [team](team.md), a [chat](/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true) (in beta), or the personal scope of a [user](user.md).
@AkJo @laujan - please let me know if we remove the mention of chat and the link to the chat.md file in v1.0 of teamsappinstallation.md?
 Or
 Do we port the chat.md file to v1.0?

2020-10-27 07:30 UTC, AkJo commented on api-reference/v1.0/resources/teamsappinstallation.md
> +| id                  | string   | A unique ID (not the teams appID). |
Please capitalize "Teams" when it is referring to the product 'Teams' and not as a plural of 'team'.

2020-10-27 07:42 UTC, AkJo commented on api-reference/v1.0/resources/teamsappinstallation.md
> -description: "A teamsApp installed in a team. "
Please add a new file for the resource userScopeTeamsAppInstallation.md

Represents a teamsApp installed in the personal scope of a user.


Please refer to the definition of the userScopeTeamsAppInstallation in https://graph.microsoft.com/$metadata

2020-10-27 08:33 UTC, opbld34 commented
Docs Build status updates of commit _[407bdd7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/407bdd7966e2fe3c08809af3f6b2ff5413111150)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-97ecd330)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-97ecd330"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific v [...]

2020-10-27 09:16 UTC, opbld33 commented
Docs Build status updates of commit _[e521698](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e521698836c60e454a6e7ade9bff1201fb4cbfbb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-bba6757f)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-bba6757f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to  [...]

2020-10-27 14:36 UTC, opbld30 commented
Docs Build status updates of commit _[6f23f46](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f23f462b2d21bf5c268d53cc1442071bad5eab2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-78117950)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-78117950)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-78117950"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````
 - **Line 21, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list-message.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get-message.md'.`````

<a id="de0bbbbb-78117950"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a [...]

2020-10-27 14:43 UTC, opbld32 commented
Docs Build status updates of commit _[eafcae4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eafcae49dfefb4e3e0ac21584d192fa0ba948ac5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-6a09a372)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-6a09a372)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-6a09a372"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````
 - **Line 21, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list-message.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get-message.md'.`````

<a id="de0bbbbb-6a09a372"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a [...]

2020-10-27 15:47 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +        - name: List apps for user
@AkJo , yes, this is what I meant. There is also a Teamwork node in the beta TOC under Users, where these methods are also surfaced.

2020-10-27 15:50 UTC, Lauragra commented on api-reference/v1.0/api/user-add-teamsappinstallation.md
> +# Install app for user
@AkJo , that is more clear, thanks.

2020-10-28 04:37 UTC, opbld31 commented
Docs Build status updates of commit _[a8de7c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8de7c27186605aa3516b16a66b831de9935a18e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b5580f38)

<a id="b5580f38"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280437095403-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=t7lgky4Jzmsq0tB8G7o397DcqLG40cbB68ISClxwwvQ%3D&st=2020-10-28T04%3A32%3A41Z&se=2020-11-28T04%3A37%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 06:26 UTC, opbld33 commented
Docs Build status updates of commit _[fc7f461](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc7f461a221cbef9e73a42428ccbd944ef7d9ae4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-93c0d40c)

<a id="93c0d40c"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280625339482-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GRVZE5yjAWcTVbhjDP%2BiQeO0DpX6Se2FwVmk%2BG4pjQ0%3D&st=2020-10-28T06%3A21%3A32Z&se=2020-11-28T06%3A26%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 07:12 UTC, opbld33 commented
Docs Build status updates of commit _[3f3bdc0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f3bdc0ca4d60f4b631761d3973f8e1620f1ea57)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ff00b771)

<a id="ff00b771"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280712201794-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Yv3dEcIcoAIOqRdPMedIJ9Azc8KPoYlcKi6ufRthEb4%3D&st=2020-10-28T07%3A07%3A46Z&se=2020-11-28T07%3A12%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 07:15 UTC, opbld31 commented
Docs Build status updates of commit _[c36b4ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c36b4aefa8dcbee866af8cb9166edb766e51cdfd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9330a4f4)

<a id="9330a4f4"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280714391908-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6KtBKGRuPhtF%2FMC0%2FVsYWPhnV9PNLSYjirDLFy1DZM4%3D&st=2020-10-28T07%3A10%3A04Z&se=2020-11-28T07%3A15%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 07:31 UTC, opbld31 commented
Docs Build status updates of commit _[de8b2e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de8b2e0b146aeef4e2ea0f1ca3f49b34041230eb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-780ec025)

<a id="780ec025"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280731054191-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=j4GQnFLmv%2BiT8VSeHT9A3uJdDqCfnhhjjtu8p%2Bh3pc0%3D&st=2020-10-28T07%3A26%3A30Z&se=2020-11-28T07%3A31%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 07:42 UTC, opbld32 commented
Docs Build status updates of commit _[857d406](https://github.com/microsoftgraph/microsoft-graph-docs/commits/857d406f9a47896183232874261e2f2c2b43d514)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1de58af3)

<a id="1de58af3"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280741121776-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0wsjKHDH89e%2BGU9dLTgasfCOVvtBpoVBdi0a4eeGtNE%3D&st=2020-10-28T07%3A37%3A09Z&se=2020-11-28T07%3A42%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 08:00 UTC, opbld33 commented
Docs Build status updates of commit _[46ae177](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46ae1777a5d14fcbcc1902b82ebb74bb52d069bb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a27e89cb)

<a id="a27e89cb"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280800102394-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VkvRusdNq%2FPBlyPhy7ir4bT1kyDB7%2Fc7bO5y3zVxfE8%3D&st=2020-10-28T07%3A55%3A41Z&se=2020-11-28T08%3A00%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 08:08 UTC, opbld32 commented
Docs Build status updates of commit _[b494e9d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b494e9d5bab8e0ce9094d7f96a5b76a6ef7bf7c1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5c51486c)

<a id="5c51486c"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280808199900-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tbSHkLK8mKdU2HguDEqfRKxDZGhOaeEjW69Gu%2Bq%2Fp%2BI%3D&st=2020-10-28T08%3A03%3A44Z&se=2020-11-28T08%3A08%3A44Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 08:29 UTC, opbld30 commented
Docs Build status updates of commit _[bf51a67](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf51a67af1913bd708fa26640e39097153980a34)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-362c6405)

<a id="362c6405"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280829120843-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=388zYiE72zvJmQkoAizZolvdk1i0hcBuhNZAbiWN2RM%3D&st=2020-10-28T08%3A24%3A40Z&se=2020-11-28T08%3A29%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 08:31 UTC, opbld33 commented
Docs Build status updates of commit _[180421d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/180421d9be505c68790074e8f3d839a85ac1a555)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-956944d9)

<a id="956944d9"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280831173727-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YiHD3dz%2FqaKdjfeR8dBb5ptPbdXsec3uCpZQkVZJezQ%3D&st=2020-10-28T08%3A26%3A44Z&se=2020-11-28T08%3A31%3A44Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 08:42 UTC, opbld31 commented
Docs Build status updates of commit _[ab6d69e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab6d69e9d94b7fbed53c6469e9404d0c2fed490a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d7d943d6)

<a id="d7d943d6"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280841415755-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TSSYOdo4jkCmu3sWktHxsBBc0EQ5C84F2G8qsP07qF0%3D&st=2020-10-28T08%3A37%3A07Z&se=2020-11-28T08%3A42%3A07Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 08:45 UTC, opbld32 commented
Docs Build status updates of commit _[fdc14bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fdc14bc19f5b276890dfe4f21d241f50dae9a359)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0897f1d2)

<a id="0897f1d2"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280844336261-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=k5lTV2vtQWpihyuElzAae29jIMdzz0lnBi1wlgQP1zw%3D&st=2020-10-28T08%3A40%3A02Z&se=2020-11-28T08%3A45%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 08:46 UTC, opbld32 commented
Docs Build status updates of commit _[6b4c8c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b4c8c62bcab6339306debe4de87eece50ad8a9e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d3fa5997)

<a id="d3fa5997"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280845564055-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FPK1AxX9VMNTIIkHuT7btd8aFOhYqVsDHozKNNsb%2FWI%3D&st=2020-10-28T08%3A41%3A30Z&se=2020-11-28T08%3A46%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-28 09:02 UTC, opbld30 commented
Docs Build status updates of commit _[f184889](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f18488969bea6814d39d6d87d802221331613cd6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-8d541a2f)
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-d06ba04e-8d541a2f)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-8d541a2f)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-chat-userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-8d541a2f"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````
 - **Line 21, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list-message.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get-message.md'.`````
 - **Line 26, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/user-userScopeTeamsAppInstallation.md'.`````

<a id="d06ba04e-8d541a2f"></a>
### [api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md)
 - **Line 15, Column 25**: **[Warning-file-not-found]** `````Invalid file link: 'teamAppInstallation.md'.`````

<a id="de0bbbbb-8d541a2f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`` [...]

2020-10-28 09:37 UTC, opbld31 commented
Docs Build status updates of commit _[161f19f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/161f19f02940031e9c01e1efb729452df79e48a4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-26a6f327)
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-d06ba04e-26a6f327)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-26a6f327)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-chat-userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-26a6f327"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````
 - **Line 21, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list-message.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get-message.md'.`````

<a id="d06ba04e-26a6f327"></a>
### [api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md)
 - **Line 15, Column 25**: **[Warning-file-not-found]** `````Invalid file link: 'teamAppInstallation.md'.`````

<a id="de0bbbbb-26a6f327"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &pr [...]

2020-10-28 10:41 UTC, opbld31 commented
Docs Build status updates of commit _[a8ec100](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8ec100b0b07343c9d3627744ff883acf3deba40)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-505da9b1)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-505da9b1)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-chat-userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-505da9b1"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````
 - **Line 21, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list-message.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get-message.md'.`````

<a id="de0bbbbb-505da9b1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specifi [...]

2020-10-29 10:12 UTC, AkJo commented on api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md
> +  "@odata.type": "microsoft.graph.teamsAppInstallation",
microsoft.graph.chat


This request is a get on the chat property of the userScopeTeamsAppInstallation. It will return a chat resource.

2020-10-29 10:13 UTC, AkJo commented on api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md
> +This method supports the $filter, $select, and $expand [OData query parameters](/graph/query-parameters) to help customize the response.
Only $select is supported for this API.

2020-10-29 10:15 UTC, AkJo commented on api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md
> +If successful, this method returns a `200 OK` response code and a collection of [teamsAppInstallation](../resources/teamsappinstallation.md) objects in the response body.
response code and an instance of [chat](...resources/chat.md) object in the response body

2020-10-29 10:17 UTC, AkJo commented on api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md
> +  ]
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#chats/$entity",
    "id": "19:ce7b15c2978041fda1e4e3623aa8faed@thread.v2",
    "topic": null,
    "createdDateTime": "2020-10-07T21:42:04.447Z",
    "lastUpdatedDateTime": "2020-10-28T12:49:19.233Z"
}

2020-10-29 10:20 UTC, AkJo commented on api-reference/v1.0/resources/teamsappinstallation.md
> +|[Remove app for user](../api/user-delete-teamsappinstallation.md) | None | Removes (uninstalls) an app in the personal scope of a user. |
from

2020-10-29 10:22 UTC, AkJo commented on api-reference/v1.0/resources/userScopeTeamsAppInstallation.md
> +Represents a [teamsApp](teamsapp.md) installed in a [team](team.md), a [chat](chat.md), or the personal scope of a [user](user.md). Any bots that are part of the app will become part of any team, cha
Please remove.


"Represents a [teamsApp](teamsapp.md) installed in the personal scope of a [user](user.md)"

FYI: UserScopeTeamsAppInstallation pertains to app installation only in personal scope. It is a special derivative of teamsAppInstallation. Please remove references to team scope or chat scope from the description.

2020-10-29 10:22 UTC, AkJo commented on api-reference/v1.0/resources/userScopeTeamsAppInstallation.md
> +|[List apps installed in team](../api/teamsappinstallation-list.md) | [teamsAppInstallation](teamsappinstallation.md) | Lists apps installed in a team.|
As explained above, please remove.

2020-10-29 10:23 UTC, AkJo commented on api-reference/v1.0/resources/userScopeTeamsAppInstallation.md
> +|[List chat between user and Teams app](../api/user-chat-userScopeTeamsAppInstallation.md) | [chat](chat.md) | Lists one-on-one chat between the user and Teams app. |
you can remove the term 'Teams', since all apps are considered Teams apps in this document.

2020-10-29 10:27 UTC, AkJo commented on api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md
> +doc_type: "apiPageType"
Please rename file to userscopeteamsappinstallation-get-chat.md

2020-10-29 10:28 UTC, AkJo commented on api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md
> +Retrieve the [chat](../resources/chat.md) of the specified [user](../resources/user.md).
Retrieve the [chat](../resources/chat.md) between a specified [user](../resources/user.md) and Teams app (../resources/teamsapp.md).

2020-10-29 10:32 UTC, AkJo commented on api-reference/v1.0/api/user-delete-teamsappinstallation.md
> +title: "Delete teamsAppInstallation"
We are missing one more page and the corresponding entry in the TOC.

We have covered:
List, delete, add, upgrade so far. We are missing GET.

"Get app for user"

The page will cover documentation for the GET /users/{user-id}/teamwork/installedApps/{app-installation-id} API. 
The content will be pretty much identical for what you have in the LIST document, except for you are querying for a single element in the collection rather than the entire collection.

2020-10-29 10:37 UTC, AkJo commented on api-reference/v1.0/resources/chat.md
> +|[List messages in a chat](../api/chat-list-message.md)  | [chatMessage](../resources/chatmessage.md) | Get messages in a 1:1 or group chat. | Delegated and application* |
Apparently, we have not GAed, these, please remove them.

2020-10-29 10:37 UTC, AkJo commented on api-reference/v1.0/resources/chat.md
> +|[Get message in chat](../api/chat-get-message.md)  | [chatMessage](../resources/chatmessage.md) | Get a single message in a chat. | Delegated and application* |
Apparently, we have not GAed, these, please remove them.

2020-10-29 10:38 UTC, AkJo commented on api-reference/v1.0/resources/chat.md
> +| topic| String|  (Optional) Subject or topic for the chat. Only available for group chats.|
We have not GAed these properties yet, apart from 'id'. Please remove the rest.

2020-10-29 10:39 UTC, AkJo commented on api-reference/v1.0/resources/chat.md
> +| members | [conversationMember](conversationmember.md) collection | A collection of all people in the chat. Nullable. |
We have not GAed these either. Please remove.

2020-10-29 10:39 UTC, AkJo commented on api-reference/v1.0/resources/chat.md
> +  "topic": "string",
Please update for the example to have only id property for now.

2020-10-29 10:40 UTC, AkJo commented on api-reference/v1.0/resources/teamsappinstallation.md
> +Represents a [teamsApp](teamsapp.md) installed in a [team](team.md), a [chat](chat.md), or the personal scope of a [user](user.md). Any bots that are part of the app will become part of any team, cha
Please remove a [chat](chat.md). That has not been release to v1 yet.

2020-10-29 10:41 UTC, AkJo commented on api-reference/v1.0/resources/teamsappinstallation.md
> +Represents a [teamsApp](teamsapp.md) installed in a [team](team.md), a [chat](chat.md), or the personal scope of a [user](user.md). Any bots that are part of the app will become part of any team, cha
By the way, I am using the terms V1 and GAed interchangeably in my comments.

2020-10-29 10:42 UTC, AkJo commented on api-reference/v1.0/resources/teamsappinstallation.md
> +|[Add app to team](../api/teamsappinstallation-add.md) | None | Adds (installs) an app to a team.|
Please add one entry for 

Get app installed in team. 

This should point to a page that documents 
GET /teams/id/installedApps/id

2020-10-29 10:42 UTC, AkJo commented on api-reference/v1.0/resources/teamsappinstallation.md
> +|[Add app for user](../api/user-add-teamsappinstallation.md) | None | Adds (installs) an app in the personal scope of a user. |
Please add one entry for 

Get app installed for user. 

This should point to a page that documents 
GET users/id/teamwork/installedApps/id

2020-10-29 10:43 UTC, AkJo commented on api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md
> +  ]
Please ignore this comment. The properties that I showed here for illustration purpose have not been release to V1 yet.

2020-10-29 11:31 UTC, AkJo commented on api-reference/v1.0/toc.yml
> -          href: api/conversationmember-delete.md
Regarding these entries that you are deleting, can you please rename the method files and move them under the "channel" node.

 name: List members
          href: api/channel-list-members.md
        - name: Get member
          href: api/channel-get-member.md
        - name: Add member
          href: api/channel-add-member.md
        - name: Update member
          href: api/channel-update-member.md
        - name: Delete member
          href: api/channel-delete-member.md

2020-10-29 14:03 UTC, opbld31 commented
Docs Build status updates of commit _[ab43db5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab43db549a2c6113da68fd577f5f16a5ddaa233d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-80a661ef)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-80a661ef)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-chat-userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-80a661ef"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````
 - **Line 21, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list-message.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get-message.md'.`````

<a id="de0bbbbb-80a661ef"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specifi [...]

2020-10-29 14:07 UTC, opbld30 commented
Docs Build status updates of commit _[eca6fcc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eca6fccd61ebe2a804bcd96372bb3c8f88b95555)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-9bda8f9d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-9bda8f9d)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-chat-userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-9bda8f9d"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````
 - **Line 21, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list-message.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get-message.md'.`````

<a id="de0bbbbb-9bda8f9d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specifi [...]

2020-10-29 14:18 UTC, opbld34 commented
Docs Build status updates of commit _[dce9be7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dce9be71317147825cc86819e3f4bafb06832a3b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-5165fc69)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-5165fc69)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-chat-userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-5165fc69"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````
 - **Line 21, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list-message.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get-message.md'.`````

<a id="de0bbbbb-5165fc69"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specifi [...]

2020-10-29 14:22 UTC, opbld32 commented
Docs Build status updates of commit _[576951e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/576951e9b6033c5e9b245954ef9f3f59244666ed)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-81a84ce6)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-81a84ce6)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-chat-userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-81a84ce6"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````
 - **Line 21, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get.md'.`````
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list-message.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-get-message.md'.`````

<a id="de0bbbbb-81a84ce6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specifi [...]

2020-10-29 14:31 UTC, opbld32 commented
Docs Build status updates of commit _[af1d1c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af1d1c6f4e090b4d1d7936e186165e4ee80ecefa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-21979f56)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-21979f56)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-chat-userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-chat-userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-21979f56"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````

<a id="de0bbbbb-21979f56"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Li [...]

2020-10-29 14:50 UTC, opbld33 commented
Docs Build status updates of commit _[42a21db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42a21db6740d10918dee13566201268c60417384)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-e53f43e7)
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-d06ba04e-e53f43e7)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-e53f43e7)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-e53f43e7)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-e53f43e7"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````
 - **Line 21, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/user-chat-userScopeTeamsAppInstallation.md'.`````

<a id="d06ba04e-e53f43e7"></a>
### [api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md)
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/user-chat-userScopeTeamsAppInstallation.md'.`````

<a id="77cfd98e-e53f43e7"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4935, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/user-chat-userScopeTeamsAppInstallation.md'.`````
 - **Line 4978, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/user-chat-userScopeTeamsAppInstallation.md'.`````

<a id="de0bbbbb-e53f43e7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Co [...]

2020-10-29 14:52 UTC, opbld31 commented
Docs Build status updates of commit _[c55b364](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c55b364986031fe57aa21f5f17b4722a7402aa86)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-70cf0450)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-70cf0450)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-70cf0450)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-70cf0450"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````
 - **Line 21, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/user-chat-userScopeTeamsAppInstallation.md'.`````

<a id="77cfd98e-70cf0450"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4935, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/user-chat-userScopeTeamsAppInstallation.md'.`````
 - **Line 4978, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/user-chat-userScopeTeamsAppInstallation.md'.`````

<a id="de0bbbbb-70cf0450"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Colu [...]

2020-10-29 14:54 UTC, opbld34 commented
Docs Build status updates of commit _[8d2a20f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d2a20f51c07a78e7488cb6e58a4b4421d2d4f05)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-e254efd5)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-e254efd5)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-e254efd5)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-e254efd5"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````

<a id="77cfd98e-e254efd5"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4935, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/user-chat-userScopeTeamsAppInstallation.md'.`````
 - **Line 4978, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/user-chat-userScopeTeamsAppInstallation.md'.`````

<a id="de0bbbbb-e254efd5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL [...]

2020-10-29 14:56 UTC, opbld34 commented
Docs Build status updates of commit _[d01a915](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d01a9150af9962bb595d3893cefed88bef80b95f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-b9a465a2)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-b9a465a2)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-b9a465a2"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````

<a id="de0bbbbb-b9a465a2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line  [...]

2020-10-29 15:21 UTC, opbld33 commented
Docs Build status updates of commit _[308be60](https://github.com/microsoftgraph/microsoft-graph-docs/commits/308be603093b0196ef85783ffebb21e9330933b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-6978abd3)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-6978abd3)
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-6978abd3"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````

<a id="de0bbbbb-6978abd3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: * [...]

2020-10-29 15:41 UTC, opbld32 commented
Docs Build status updates of commit _[dedb3f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dedb3f185ec343f76426f0b22536a249b5002f29)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-8d28fdf8)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-8d28fdf8)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-8d28fdf8"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````

<a id="de0bbbbb-8d28fdf8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you m [...]

2020-10-29 15:46 UTC, opbld34 commented
Docs Build status updates of commit _[51e6409](https://github.com/microsoftgraph/microsoft-graph-docs/commits/51e6409606d5840f6869b6621aa1509ecd404515)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-513869b4)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-513869b4)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-513869b4"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````

<a id="de0bbbbb-513869b4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you m [...]

2020-10-29 15:55 UTC, opbld32 commented
Docs Build status updates of commit _[0ecb6a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ecb6a20c573cca10882bc01b2a289e6a5e96c54)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-40c49f3d)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-40c49f3d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-40c49f3d)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-40c49f3d"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````

<a id="77cfd98e-40c49f3d"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4932, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4934, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4936, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4940, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````

<a id="de0bbbbb-40c49f3d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific vers [...]

2020-10-29 15:59 UTC, opbld30 commented
Docs Build status updates of commit _[26dab5e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26dab5ece2975f37b8f5b47ecf1d0e2289dd6698)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-785bae00)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-785bae00)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-785bae00)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-785bae00"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````

<a id="77cfd98e-785bae00"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4932, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4934, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4936, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4940, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````

<a id="de0bbbbb-785bae00"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific vers [...]

2020-10-29 16:07 UTC, opbld32 commented
Docs Build status updates of commit _[a0b7633](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0b7633d2c438a6730a65df41f99f89b12cfc70d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-8c7a9883)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-8c7a9883)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-8c7a9883)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-8c7a9883"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````

<a id="77cfd98e-8c7a9883"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4932, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4934, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4936, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4940, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````

<a id="de0bbbbb-8c7a9883"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific vers [...]

2020-10-29 16:08 UTC, opbld30 commented
Docs Build status updates of commit _[1293a21](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1293a21dc2e23a8749b136a41aa75b3d97db7550)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-9737ce74)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-9737ce74)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-9737ce74)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-9737ce74"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````

<a id="77cfd98e-9737ce74"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4932, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4934, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4936, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4940, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````

<a id="de0bbbbb-9737ce74"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific vers [...]

2020-10-30 07:27 UTC, opbld30 commented
Docs Build status updates of commit _[ebbc969](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ebbc9690c2204238ec7508f733ca6800ffa06f9d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-4563842d)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-4563842d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-4563842d)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-4563842d"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````

<a id="77cfd98e-4563842d"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4932, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4934, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4936, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4940, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````

<a id="de0bbbbb-4563842d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific vers [...]

2020-10-30 07:29 UTC, opbld32 commented
Docs Build status updates of commit _[0ab3965](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ab3965006f13d9be64d24061b4950fb2a8a0bd2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c5a6391-e7bdf144)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-e7bdf144)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-e7bdf144)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="0c5a6391-e7bdf144"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````

<a id="77cfd98e-e7bdf144"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4932, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4934, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4936, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4940, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````

<a id="de0bbbbb-e7bdf144"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific vers [...]

2020-10-30 07:40 UTC, opbld31 commented
Docs Build status updates of commit _[a95d261](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a95d261cb8c19bdddc570465d288da400bdf0df8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-74c22847)
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :warning:Warning | | [Details](#user-content-0c5a6391-74c22847)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-74c22847)

<a id="77cfd98e-74c22847"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4946, Column 8**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="0c5a6391-74c22847"></a>
### [api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md)
 - **Line 20, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/chat-list.md'.`````

<a id="de0bbbbb-74c22847"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preser [...]

2020-10-30 07:44 UTC, opbld33 commented
Docs Build status updates of commit _[496803a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/496803a90f9997ff3db20dd537fb1d504a9980ec)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-023adb3d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-023adb3d)

<a id="77cfd98e-023adb3d"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4946, Column 8**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="de0bbbbb-023adb3d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph- [...]

2020-10-30 07:50 UTC, opbld30 commented
Docs Build status updates of commit _[c0b781f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0b781f7e20d5378f8ca0d24def5c1ad029aa546)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-06c3544a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-06c3544a)

<a id="77cfd98e-06c3544a"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4946, Column 8**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="de0bbbbb-06c3544a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph- [...]

2020-10-30 08:00 UTC, opbld30 commented
Docs Build status updates of commit _[08c5bed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08c5bedd6898c05f85f2d1e0cc555578278cff1f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-885a0f7e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-885a0f7e)

<a id="77cfd98e-885a0f7e"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4947, Column 15**: **[Error-yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

<a id="de0bbbbb-885a0f7e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=gra [...]

2020-10-30 08:10 UTC, opbld33 commented
Docs Build status updates of commit _[1ef89f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ef89f7a581845f899cfa6d88c9739ff09c2138b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-7c93ea1e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-7c93ea1e)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-7c93ea1e"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4932, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4934, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4936, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4940, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````

<a id="de0bbbbb-7c93ea1e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-no [...]

2020-10-30 08:27 UTC, opbld34 commented
Docs Build status updates of commit _[56bfe22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56bfe220ea50021e11e7caa546c4edc1a65b510e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-5ec96d8c)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-5ec96d8c)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-5ec96d8c"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4932, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4934, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4936, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4940, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````

<a id="de0bbbbb-5ec96d8c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-no [...]

2020-10-30 08:29 UTC, opbld30 commented
Docs Build status updates of commit _[0e84731](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e84731ec236694bfcf19e012c25c1759fd8e198)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-cb3224d6)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-cb3224d6)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-cb3224d6"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4932, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4934, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4936, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4940, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````

<a id="de0bbbbb-cb3224d6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-no [...]

2020-10-30 08:34 UTC, opbld34 commented
Docs Build status updates of commit _[b887a22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b887a22406f47396ed07e0481efcf98916e19467)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-caade597)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-caade597)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-caade597"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4932, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4934, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4936, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4940, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````

<a id="de0bbbbb-caade597"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-no [...]

2020-10-30 08:36 UTC, opbld31 commented
Docs Build status updates of commit _[5b70256](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b70256fc697fc2a27be592f7e9a837744ab7b66)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-76344099)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-76344099)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-76344099"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4932, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4934, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4936, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4940, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````

<a id="de0bbbbb-76344099"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-no [...]

2020-10-30 08:40 UTC, opbld34 commented
Docs Build status updates of commit _[edf0fce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/edf0fce7f131d1e281b94eecad6b1b163ad64d66)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-5dfcd054)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-5dfcd054)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-5dfcd054"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4932, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4934, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4936, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4940, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````

<a id="de0bbbbb-5dfcd054"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-no [...]

2020-10-30 08:50 UTC, opbld33 commented
Docs Build status updates of commit _[4c56cbe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c56cbebe8ef402045764e8b7e9aadeb9e27ef85)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-8494308b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-8494308b)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-8494308b"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4932, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4934, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4936, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4940, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````

<a id="de0bbbbb-8494308b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-no [...]

2020-11-02 06:27 UTC, opbld30 commented
Docs Build status updates of commit _[2f22779](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2f2277925ebe65323b580873e53dcb5713a3d353)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-e07ad1a8)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-e07ad1a8)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-e07ad1a8"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4932, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4934, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4936, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4940, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````

<a id="de0bbbbb-e07ad1a8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true  [...]

2020-11-03 04:02 UTC, opbld31 commented
Docs Build status updates of commit _[5f0fa2c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f0fa2c1a3c24daab8d82eea4540b0856899943d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-47a9e60d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-47a9e60d)

<a id="77cfd98e-47a9e60d"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4981, Column 6**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="de0bbbbb-47a9e60d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If s [...]

2020-11-03 04:13 UTC, opbld33 commented
Docs Build status updates of commit _[13c3070](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13c3070be0e24bfb829a0c2ce1a93068df8b66be)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-223827c2)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | | [Details](#user-content-de0bbbbb-223827c2)

<a id="77cfd98e-223827c2"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4982, Column 6**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="de0bbbbb-223827c2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If s [...]

2020-11-03 04:22 UTC, opbld31 commented
Docs Build status updates of commit _[34a8c95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34a8c9515f95c8154567bf715994a3ed5d79904a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-0bbe77fe)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-0bbe77fe)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-0bbe77fe"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-message.md'.`````
 - **Line 4942, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4944, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4946, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4950, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-0bbe77fe"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tr [...]

2020-11-04 10:12 UTC, AkJo commented on api-reference/v1.0/api/teamsappinstallation-get.md
> +|Delegated (work or school account) | TeamsAppInstallation.ReadForTeam, TeamsAppInstallation.ReadWriteForTeam, Group.Read.All, Group.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All |
Please add one more permission. 

TeamsAppInstallation.ReadWriteSelfForTeam

2020-11-04 10:12 UTC, AkJo commented on api-reference/v1.0/api/teamsappinstallation-get.md
> +|Application | TeamsAppInstallation.ReadForTeam.All, TeamsAppInstallation.ReadWriteForTeam.All, Group.Read.All, Group.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All |
TeamsAppInstallation.ReadWriteSelfForTeam.All

2020-11-04 10:15 UTC, AkJo commented on api-reference/v1.0/api/user-get-teamsappinstallation.md
> +|Delegated (work or school account) | TeamsAppInstallation.ReadSelfForUser, TeamsAppInstallation.ReadForUser, TeamsAppInstallation.Read, TeamsAppInstallation.ReadWriteSelfForUser, TeamsAppInstallatio
Please remove TeamsAppInstallation.ReadSelfForUser

2020-11-04 10:15 UTC, AkJo commented on api-reference/v1.0/api/user-get-teamsappinstallation.md
> +|Application | TeamsAppInstallation.ReadSelfForUser.All, TeamsAppInstallation.ReadForUser.All, TeamsAppInstallation.Read.All,TeamsAppInstallation.ReadWriteSelfForUser.All, TeamsAppInstallation.ReadWr
Please remove TeamsAppInstallation.ReadSelfForUser.All

2020-11-04 10:16 UTC, AkJo commented on api-reference/v1.0/api/user-list-teamsappinstallation.md
> +|Delegated (work or school account) | TeamsAppInstallation.ReadSelfForUser, TeamsAppInstallation.ReadForUser, TeamsAppInstallation.Read, TeamsAppInstallation.ReadWriteSelfForUser, TeamsAppInstallatio
Please remove TeamsAppInstallation.ReadSelfForUser

2020-11-04 10:16 UTC, AkJo commented on api-reference/v1.0/api/user-list-teamsappinstallation.md
> +|Application | TeamsAppInstallation.ReadSelfForUser.All, TeamsAppInstallation.ReadForUser.All, TeamsAppInstallation.Read.All,TeamsAppInstallation.ReadWriteSelfForUser.All, TeamsAppInstallation.ReadWr
Please remove TeamsAppInstallation.ReadSelfForUser.All

2020-11-04 10:16 UTC, AkJo commented on api-reference/v1.0/api/user-list-teamsappinstallation.md
> +|Application | TeamsAppInstallation.ReadSelfForUser.All, TeamsAppInstallation.ReadForUser.All, TeamsAppInstallation.Read.All,TeamsAppInstallation.ReadWriteSelfForUser.All, TeamsAppInstallation.ReadWr
Basically, there is no ReadOnly version of the 'Self' permissions.

2020-11-04 10:17 UTC, AkJo commented on api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md
> +|:--------------------|:---------------------------------------------------------|
Please remove.

2020-11-04 10:17 UTC, AkJo commented on api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md
> +|Application | TeamsAppInstallation.ReadSelfForUser.All, TeamsAppInstallation.ReadForUser.All, TeamsAppInstallation.Read.All,TeamsAppInstallation.ReadWriteSelfForUser.All, TeamsAppInstallation.ReadWr
Please remove.

2020-11-04 10:18 UTC, AkJo commented on api-reference/v1.0/resources/chat.md
> +|[Get chat between user and app](../api/userscopeteamsappinstallation-get-chat.md) | [userScopeTeamsAppInstallation](userScopeTeamsAppInstallation.md)| Get one-on-one chat between user and the app |
The return type is a chat.

[chat](chat.md)

2020-11-04 10:19 UTC, AkJo commented on api-reference/v1.0/resources/teamsappinstallation.md
> +|[Get installed app in team](../api/teamsappinstallation-get.md) | [teamsAppInstallation](teamsappinstallation.md) | Lists apps installed in a team.|
Get app installed in a team

2020-11-04 10:20 UTC, AkJo commented on api-reference/v1.0/resources/teamsappinstallation.md
> +|[List apps installed in team](../api/teamsappinstallation-list.md) | [teamsAppInstallation](teamsappinstallation.md) | Lists apps installed in a team.|
This returns a collection. Dont you have a notation for representing a collection.

I think it is 
[teamsAppInstallation](teamsappinstallation.md)collection

2020-11-04 10:20 UTC, AkJo commented on api-reference/v1.0/resources/teamsappinstallation.md
> +|[Get installed app for user](../api/user-get-teamsappinstallation.md)| [teamAppInstallation](teamsappinstallation.md) | Lists the specified app installed in the personal scope of a user. |
Gets the

2020-11-04 10:23 UTC, AkJo commented on api-reference/v1.0/resources/userScopeTeamsAppInstallation.md
> +|[Get installed app for user](../api/user-get-teamsappinstallation.md)| [teamAppInstallation](teamsappinstallation.md) | Lists the specified app installed in the personal scope of a user. |
Gets the

2020-11-04 11:06 UTC, opbld31 commented
Docs Build status updates of commit _[2e0dd4e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e0dd4ed2395f50a6a3c3cb3b4cacadb0a17c9c9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-5aa68ce7)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-5aa68ce7)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-5aa68ce7"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-message.md'.`````
 - **Line 4942, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4944, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4946, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4950, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-5aa68ce7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tr [...]

2020-11-04 11:07 UTC, opbld31 commented
Docs Build status updates of commit _[299630e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/299630ed34d339614d5629d5d2d41b5e7f1df555)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-2037ae95)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-2037ae95)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-2037ae95"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-message.md'.`````
 - **Line 4942, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4944, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4946, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4950, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-2037ae95"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tr [...]

2020-11-04 11:08 UTC, opbld34 commented
Docs Build status updates of commit _[aef3e79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aef3e79f73aae8be92a0d4bd38f1ceb6e2cd7c26)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-bc043335)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-bc043335)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-bc043335"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-message.md'.`````
 - **Line 4942, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4944, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4946, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4950, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-bc043335"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tr [...]

2020-11-04 11:13 UTC, opbld31 commented
Docs Build status updates of commit _[111a358](https://github.com/microsoftgraph/microsoft-graph-docs/commits/111a358cb110244e8814488e61d20d0315a7a30f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-4df84469)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-4df84469)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-4df84469"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-message.md'.`````
 - **Line 4942, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4944, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4946, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4950, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-4df84469"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tr [...]

2020-11-04 11:15 UTC, opbld33 commented
Docs Build status updates of commit _[2cf2e49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2cf2e499128b1d98e651e2824cad0c8d14d6d127)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-484a5863)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-484a5863)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-484a5863"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-message.md'.`````
 - **Line 4942, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4944, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4946, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4950, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-484a5863"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tr [...]

2020-11-04 11:21 UTC, opbld34 commented
Docs Build status updates of commit _[9492ff2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9492ff2e07be578665bed888dcfb55656a9b41e6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-8847cd60)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-8847cd60)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-8847cd60"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-message.md'.`````
 - **Line 4942, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4944, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4946, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4950, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-8847cd60"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tr [...]

2020-11-04 11:27 UTC, opbld32 commented
Docs Build status updates of commit _[fae7295](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fae72957622d540f9d794f47599590232ebdc728)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-86262791)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-86262791)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-86262791"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-message.md'.`````
 - **Line 4942, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4944, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4946, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4950, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-86262791"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tr [...]

2020-11-04 13:12 UTC, AkJo commented on api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md
> +{
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#chats/$entity",
    "id": "19:0de69e5e-2da8-4cf2-821f-5e6585b2c65b_f32b83bb-4fc8-4db7-b7f5-76cdbbb8aa1c@unq.gbl.spaces"
}

2020-11-04 13:12 UTC, AkJo commented on api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md
> +  "isCollection": true
false


This API returns a single element - not a collection.

2020-11-04 13:16 UTC, AkJo approved these changes

2020-11-04 13:57 UTC, opbld34 commented
Docs Build status updates of commit _[2327ab9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2327ab9c41f66718665546d2cae6a0f675176920)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-d2ab0e7e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-d2ab0e7e)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-d2ab0e7e"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-message.md'.`````
 - **Line 4942, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4944, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4946, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4950, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-d2ab0e7e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tr [...]

2020-11-04 14:50 UTC, opbld34 commented
Docs Build status updates of commit _[4492a1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4492a1c8526c923c4d6114eac26c0709ea7ad92f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-0d0c94db)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-0d0c94db)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-0d0c94db"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-message.md'.`````
 - **Line 4942, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4944, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4946, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4950, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-0d0c94db"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tr [...]

2020-11-05 20:10 UTC, opbld33 commented
Docs Build status updates of commit _[5572796](https://github.com/microsoftgraph/microsoft-graph-docs/commits/55727960d6e8c5f82a58c51ca7829133465d7b79)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-4e4223ac)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-4e4223ac)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-4e4223ac"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4938, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-post-message.md'.`````
 - **Line 4942, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-list-members.md'.`````
 - **Line 4944, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-get-member.md'.`````
 - **Line 4946, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-add-member.md'.`````
 - **Line 4948, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-update-member.md'.`````
 - **Line 4950, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/channel-delete-member.md'.`````
 - **Line 4971, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-4e4223ac"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=tr [...]

2020-11-05 20:21 UTC, opbld32 commented
Docs Build status updates of commit _[d583aef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d583aef04eaedf52ac2b4688964da3d83a930fa6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-fe2e4c04)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-fe2e4c04"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 30, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-pr [...]

2020-11-05 20:29 UTC, laujan commented
Hi @Lauragra. This PR is ready-to-merge. 🙂

2020-11-06 02:18 UTC, Lauragra commented on api-reference/v1.0/api/teamsappinstallation-get.md
> +# Get installed app in team
This operation topic doesn't exist in the /beta folder. Did this API release to beta before going to v1.0? Please add the missing /beta topic for it.

2020-11-06 02:19 UTC, opbld33 commented
Docs Build status updates of commit _[0d75ad3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d75ad39c68d92e2be2440707fdfc32dac220c2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-b3d15488)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-b3d15488"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]**  [...]

2020-11-06 02:22 UTC, opbld33 commented
Docs Build status updates of commit _[7c7748a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c7748a5f8ee253518ad1c02f3d107977821ead4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-ed1f5c5c)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-ed1f5c5c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]**  [...]

2020-11-06 04:03 UTC, opbld31 commented
Docs Build status updates of commit _[c06187f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c06187f65fb1e1aae71e971a1e8dcd597a0cdd77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-f2f5d16b)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-f2f5d16b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]**  [...]

2020-11-06 04:05 UTC, opbld31 commented
Docs Build status updates of commit _[020cdf9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/020cdf9bc7f8cc64a55f61e6ea894bb502b1df7d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-61d89904)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userScopeTeamsAppInstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userScopeTeamsAppInstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-61d89904"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userScopeTeamsAppInstallation?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Col [...]

2020-11-06 04:06 UTC, Lauragra commented on api-reference/v1.0/api/user-get-teamsappinstallation.md
> +title: "Get a teamsAppInstallation"
The title in the metadata should match the H1 title.

2020-11-06 04:06 UTC, Lauragra commented on api-reference/v1.0/api/user-get-teamsappinstallation.md
> +title: "Get a teamsAppInstallation"
This file doesn't exist in beta - same question regarding whether we missed documenting in /beta; please add the missing file.

2020-11-06 04:07 UTC, opbld32 commented
Docs Build status updates of commit _[8093457](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80934575d92166fd48048b1cdce38eeb75136c04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-f46adaaf)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-f46adaaf"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userScopeTeamsAppInstallation?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Col [...]

2020-11-06 04:09 UTC, opbld31 commented
Docs Build status updates of commit _[a017990](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a017990727838fba92722162d47fc3a491ea32b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-e78654ba)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-e78654ba"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userScopeTeamsAppInstallation?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Col [...]

2020-11-06 04:12 UTC, Lauragra commented on api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md
> +title: "List userScopeTeamsAppInstallation"
It doesn't appear that we have documented the userScopeTeamsAppInstallation entity and associated operations for beta. Please add those topics. Also, for this topic, the file name is get, but the title is List. Please update.

2020-11-06 04:17 UTC, Lauragra commented on api-reference/v1.0/api/user-delete-teamsappinstallation.md
> +title: "Delete teamsAppInstallation"
The title and the H1 heading need to match.

2020-11-06 04:18 UTC, Lauragra commented on api-reference/v1.0/api/user-list-teamsappinstallation.md
> +    "value": [
Is this Response example identical to the one shown in the GET topic? Is there a difference between doing a GET and LIST operation in terms of what is returned?

2020-11-06 04:23 UTC, opbld33 commented
Docs Build status updates of commit _[61ac4f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61ac4f96808a1b6bea3db21ad77f0652e5908d4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-5fdd81c1)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-5fdd81c1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userScopeTeamsAppInstallation?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Col [...]

2020-11-06 04:27 UTC, Lauragra commented on api-reference/v1.0/resources/chat.md
> +|  Method       |  Return Type  | Description| Permissions |
Please remove the Permissions column from the table. We document permissions in the API topics.

2020-11-06 04:29 UTC, Lauragra commented on api-reference/v1.0/resources/userscopeteamsappinstallation.md
> +|[Gets the installed app for user](../api/user-get-teamsappinstallation.md)| [teamAppInstallation](teamsappinstallation.md) | List the specified app installed in the personal scope of a user. |
Should the description be Get instead of List?

2020-11-06 04:29 UTC, opbld32 commented
Docs Build status updates of commit _[6aa4a03](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6aa4a03552d30c587257d715ac54ccc5efa279f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-4e4bed48)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-4e4bed48"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userScopeTeamsAppInstallation?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Col [...]

2020-11-06 04:30 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | v1.0 | Added [Get the installed app in team](/graph/api/teamsappinstallation-get?view=graph-rest-v1.0), [List apps for user](/graph/api/user-list-teamsappinstallation?view=graph-rest-v1.
Please add a new Changelist entry to the Microsoft.Teams.Core.json file to list the changes as well.

2020-11-06 04:30 UTC, Lauragra requested changes
Please review and respond to feedback. Please ensure that entities that you are documenting for v1.0 are also documented in beta.

New files created in v1.0 and have also been documented in beta.

2020-11-06 09:03 UTC, AkJo commented on api-reference/v1.0/api/user-get-teamsappinstallation.md
> +title: "Get a teamsAppInstallation"
You are right. @KirtiPereira, for all the files that are being introduced, please check that there are corresponding files and entries in the toc in /beta. If any is missing, then please make those additions/edits as well as part of this PR.

In some cases, you might find that the file exists with identical, but it has a different name. Please rename that file in beta based on the naming scheme in this PR.

2020-11-06 09:04 UTC, AkJo commented on api-reference/v1.0/api/user-list-teamsappinstallation.md
> +    "value": [
LIST topic will always return a collection and (potentially) support filtering.
GET topic will always return a singular element, (and of course, not support filtering).

2020-11-06 09:06 UTC, AkJo commented on api-reference/v1.0/api/user-get-teamsappinstallation.md
> +This method supports the `$filter`, `$select`, and `$expand` [OData query parameters](/graph/query-parameters) to help customize the response.
The GET on a singular element such as this:
GET /users/{id}/teamwork/**installedApps/{id}**

will never support filtering. 

Filtering is supported on only those APIs that return a collection.

2020-11-06 09:08 UTC, AkJo commented on api-reference/v1.0/api/user-get-teamsappinstallation.md
> +{
This API does not return a collection.

The correct response would be:
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#teams('5b649834-7412-4cce-9e69-176e95a394f5')/installedApps(teamsAppDefinition())/$entity",
    "id": "NWI2NDk4MzQtNzQxMi00Y2NlLTllNjktMTc2ZTk1YTM5NGY1IyNhNmI2MzM2NS0zMWE0LTRmNDMtOTJlYy03MTBiNzE1NTdhZjk=",
    "teamsAppDefinition": {
        "id": "YTZiNjMzNjUtMzFhNC00ZjQzLTkyZWMtNzEwYjcxNTU3YWY5IyMwLjk=",
        "teamsAppId": "a6b63365-31a4-4f43-92ec-710b71557af9",
        "displayName": "Power Apps",
        "version": "0.9"
    }
}

2020-11-06 09:09 UTC, AkJo commented on api-reference/v1.0/api/user-get-teamsappinstallation.md
> +GET https://graph.microsoft.com/v1.0/users/{id}/teamwork/installedApps/{id}?$expand=teamsAppDefinition
https://graph.microsoft.com/v1.0/users/5b649834-7412-4cce-9e69-176e95a394f5/teamwork/installedApps/NWI2NDk4MzQtNzQxMi00Y2NlLTllNjktMTc2ZTk1YTM5NGY1IyNhNmI2MzM2NS0zMWE0LTRmNDMtOTJlYy03MTBiNzE1NTdhZjk=?$expand=teamsAppDefinition

Please use this as sample request. It is more illustrative.

2020-11-06 09:26 UTC, AkJo commented on api-reference/v1.0/toc.yml
> -        - name: Get member
Please undo these deletes for now. The PR that is supposed to reintroduce the fixed entries might not go in around the same time, and I am concerned that users will lose a handle to these documents in the interim period

2020-11-06 09:26 UTC, AkJo commented on api-reference/v1.0/toc.yml
> -        - name: Send message
Please undo these deletes for now. The PR that is supposed to reintroduce the fixed entries might not go in around the same time, and I am concerned that users will lose a handle to these documents in the interim period

2020-11-06 10:04 UTC, opbld31 commented
Docs Build status updates of commit _[7d534e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d534e7e42cb3de931b68eb8cda98dd971569a4c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-d769eef3)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-d769eef3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userScopeTeamsAppInstallation?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Col [...]

2020-11-06 10:18 UTC, opbld31 commented
Docs Build status updates of commit _[8773d61](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8773d6142332f9f0974460fc92d544e76962113a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-ac9061d5)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-ac9061d5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userScopeTeamsAppInstallation?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Col [...]

2020-11-06 10:31 UTC, opbld32 commented
Docs Build status updates of commit _[641e678](https://github.com/microsoftgraph/microsoft-graph-docs/commits/641e6780a65b4e15892e5a35d6fbf113e9afa363)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-728f5c36)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-728f5c36"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userScopeTeamsAppInstallation?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Col [...]

2020-11-06 10:37 UTC, opbld33 commented
Docs Build status updates of commit _[a4e15e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a4e15e13b9d832f775ea17c5c1790e84ae4f733b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-966bffba)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-966bffba"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userScopeTeamsAppInstallation?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Col [...]

2020-11-06 10:55 UTC, opbld31 commented
Docs Build status updates of commit _[1a79d4a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a79d4ae27a4ca1c8ddf128892702bcea245477c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-a9eba0a0)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-a9eba0a0"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userScopeTeamsAppInstallation?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Col [...]

2020-11-06 11:09 UTC, opbld32 commented
Docs Build status updates of commit _[242ce89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/242ce892e863565649b42edc87629d1c9460e514)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-7e38f9c0)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-7e38f9c0"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userScopeTeamsAppInstallation?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Col [...]

2020-11-06 11:41 UTC, opbld34 commented
Docs Build status updates of commit _[ec80877](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec808779c4da16a7a6cf8566db3907f3d177b6d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-e784ccc7)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-e784ccc7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userScopeTeamsAppInstallation?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 38, Col [...]

2020-11-06 12:01 UTC, opbld34 commented
Docs Build status updates of commit _[70fffda](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70fffda62f401874b2c964d173e6ef9e151c900d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-5c3082c9)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-5c3082c9)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-5c3082c9"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4957, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-5c3082c9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-11-06 12:03 UTC, opbld31 commented
Docs Build status updates of commit _[1c291df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c291df365701dccb832b9c92ef8590757ff0861)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-622b1d2d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-622b1d2d)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-622b1d2d"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4957, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-622b1d2d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-11-06 12:16 UTC, opbld33 commented
Docs Build status updates of commit _[6a6e068](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a6e06864b217931de5977c54ffaeb02373d8a0a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-50b1c28f)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-50b1c28f)
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-50b1c28f"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4957, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-50b1c28f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-v1.0`````
 - **Line 29, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, a [...]

2020-11-06 12:33 UTC, opbld34 commented
Docs Build status updates of commit _[bef1633](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bef16339464e5659ea497e88bd9ecec0bed3a0ee)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-60770de8)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-60770de8)
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-60770de8"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4957, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-60770de8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-11-06 12:38 UTC, opbld34 commented
Docs Build status updates of commit _[a46a9c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a46a9c945fe0644cc9f986718ac9776d477ed559)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-b863e6b2)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-b863e6b2)
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-b863e6b2"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4957, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-b863e6b2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-11-06 12:45 UTC, opbld34 commented
Docs Build status updates of commit _[bc21840](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc2184002f417d913b2496023b01c3403f0f952c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-2d8b6c69)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-2d8b6c69)
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-2d8b6c69"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4957, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-2d8b6c69"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-11-06 12:46 UTC, opbld32 commented
Docs Build status updates of commit _[d1982f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1982f93ad8f73a1c19b72dc74f984b2caeb836b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-b2a88c88)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-b2a88c88)
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-b2a88c88"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4957, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-b2a88c88"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-upgrade-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api [...]

2020-11-06 13:06 UTC, opbld30 commented
Docs Build status updates of commit _[277b96e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/277b96e9e6c8436116e0907c7b160c3eb5a02be4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-27ea56f0)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-27ea56f0)
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-27ea56f0"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4957, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-27ea56f0"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-add-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-delete-te [...]

2020-11-06 13:10 UTC, opbld33 commented
Docs Build status updates of commit _[34f865f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34f865f200cc8805cb258db143590cd95c837300)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-fd11d812)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-fd11d812)
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-fd11d812"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4957, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-fd11d812"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teamsappinstallati [...]

2020-11-06 13:39 UTC, opbld32 commented
Docs Build status updates of commit _[64ec411](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64ec41181402b70bf755fc9966ad0d1c557d4bd3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-66932c83)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-66932c83)
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="77cfd98e-66932c83"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml)
 - **Line 4957, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

<a id="de0bbbbb-66932c83"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-se [...]

2020-11-06 13:59 UTC, opbld32 commented
Docs Build status updates of commit _[080cc37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/080cc37632547ab9e7bbc631570e375eb1ab0b98)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-9d90c97f)
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-9d90c97f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/user-get-teams [...]

2020-11-06 14:16 UTC, opbld33 commented
Docs Build status updates of commit _[40a7536](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40a7536e96c350cf07f277ded4eacd7dc57887c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-3baa91bc)
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-3baa91bc"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-vie [...]

2020-11-06 14:25 UTC, opbld33 commented
Docs Build status updates of commit _[b27a3a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b27a3a306d1193e4a3284f6828b8181ec177cfb3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-c5756558)
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-c5756558"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 27, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsappinstallation-get?view=graph-rest-v1.0`````
 - **Line 28, Column 1**: **[Suggestion-preserve-vie [...]

2020-11-06 14:30 UTC, opbld31 commented
Docs Build status updates of commit _[65c31f0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65c31f09e22fec10678b5e5e0267f61aa493d620)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-158b78a2-b55e9c51)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-b55e9c51)
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="158b78a2-b55e9c51"></a>
### [api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md)
 - **Line 23, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamsappinstallation-get.md'.`````

<a id="de0bbbbb-b55e9c51"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/ [...]

2020-11-06 14:34 UTC, opbld31 commented
Docs Build status updates of commit _[12f7fbf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12f7fbfc1f581f4dc3ca9d13ed9c1e553b08923d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-158b78a2-6f9a8a68)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-00685cff-6f9a8a68)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-6f9a8a68)
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="158b78a2-6f9a8a68"></a>
### [api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md)
 - **Line 23, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamsappinstallation-get.md'.`````

<a id="00685cff-6f9a8a68"></a>
### [api-reference/beta/toc.ym [...]

2020-11-06 14:42 UTC, opbld32 commented
Docs Build status updates of commit _[1cb6d5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1cb6d5f3a2c8af4f765ac562a136df31ee25bddf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-158b78a2-23d494db)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-00685cff-23d494db)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-23d494db)
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="158b78a2-23d494db"></a>
### [api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md)
 - **Line 23, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/teamsappinstallation-get.md'.`````

<a id="00685cff-23d494db"></a>
### [api-reference/beta/toc.ym [...]

2020-11-06 14:48 UTC, opbld34 commented
Docs Build status updates of commit _[6291bc6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6291bc69f30dfb87685359e882f2ffd79a3516be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-c542f85e)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-c542f85e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-06 15:31 UTC, opbld32 commented
Docs Build status updates of commit _[9d2f1e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d2f1e39991765c5f31156960f5c5cc56c22e846)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-b7c4a6a3)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-b7c4a6a3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-06 15:47 UTC, KirtiPereira commented on concepts/changelog.md
> +| Addition | v1.0 | Added [Get the installed app in team](/graph/api/teamsappinstallation-get?view=graph-rest-v1.0), [List apps for user](/graph/api/user-list-teamsappinstallation?view=graph-rest-v1.
Hi @Lauragra - Needed some help as I would be entering details to the Microsoft.Teams.Core.json file for the first time.
Will it work if I copy-paste the previous entry and then make modifications to the details? Also, am not sure how to get the "Id" value.

Have resolved rest of the comments. Just this one is pending.

2020-11-06 19:45 UTC, AkJo commented on api-reference/beta/toc.yml
> +        - name: Get chat memberGet chat between user and app
What's happening here?

2020-11-06 19:47 UTC, AkJo commented on api-reference/v1.0/resources/userscopeteamsappinstallation.md
> +|[Get apps installed for user](../api/user-list-teamsappinstallation.md)| [teamsAppInstallation](teamsappinstallation.md) collection | List apps installed in the personal scope of a user. |
userScopeTeamsAppInstallation

2020-11-06 19:47 UTC, AkJo commented on api-reference/v1.0/resources/userscopeteamsappinstallation.md
> +|[Get apps installed for user](../api/user-list-teamsappinstallation.md)| [teamsAppInstallation](teamsappinstallation.md) collection | List apps installed in the personal scope of a user. |
userscopeteamsappInstallation

2020-11-06 19:48 UTC, AkJo commented on api-reference/v1.0/resources/userscopeteamsappinstallation.md
> +|[Gets the installed app for user](../api/user-get-teamsappinstallation.md)| [teamAppInstallation](teamsappinstallation.md) | List the specified app installed in the personal scope of a user. |
[userScopeTeamAppInstallation](userscopeteamsappinstallation.md)

2020-11-06 19:49 UTC, AkJo commented on api-reference/beta/resources/teamsappinstallation.md
> +|[Get apps installed for user](../api/user-list-teamsappinstallation.md) | [teamsAppInstallation](teamsappinstallation.md) collection | Lists apps installed in the personal scope of a user.|
[userScopeTeamAppInstallation](userscopeteamsappinstallation.md)

2020-11-06 19:49 UTC, AkJo commented on api-reference/beta/resources/teamsappinstallation.md
> +|[Get apps installed for user](../api/user-list-teamsappinstallation.md) | [teamsAppInstallation](teamsappinstallation.md) collection | Lists apps installed in the personal scope of a user.|
[userScopeTeamAppInstallation](userscopeteamsappinstallation.md)

2020-11-06 19:50 UTC, AkJo commented on api-reference/beta/resources/teamsappinstallation.md
> +|[Get apps installed for user](../api/user-list-teamsappinstallation.md) | [teamsAppInstallation](teamsappinstallation.md) collection | Lists apps installed in the personal scope of a user.|
'List' is fine.  
You list when return a collection, and use 'get' while returning a single element.

2020-11-06 20:00 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | v1.0 | Added [Get the installed app in team](/graph/api/teamsappinstallation-get?view=graph-rest-v1.0), [Get apps for user](/graph/api/user-list-teamsappinstallation?view=graph-rest-v1.0
@KirtiPereira , you can copy an existing Changelist entry and then update the values. For the ID, just use an online GUID generator and copy the GUID.

2020-11-09 04:07 UTC, opbld34 commented
Docs Build status updates of commit _[2766c22](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2766c22912068f55950781f882032ba3a0558bfe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-907ac764)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-907ac764"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-09 04:28 UTC, opbld31 commented
Docs Build status updates of commit _[d85f0a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d85f0a421423eaf5c4413831562fe2937952cfe9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-e36a384d)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-e36a384d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-09 04:29 UTC, opbld30 commented
Docs Build status updates of commit _[922de13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/922de1390d31d68546f30f806737284ce32fe832)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-b9e61535)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-b9e61535"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-09 05:04 UTC, opbld33 commented
Docs Build status updates of commit _[d50c214](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d50c2144c253dbdc31f0284d17a1419da02ea7df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-1e5257fd)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-1e5257fd"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-09 05:06 UTC, opbld33 commented
Docs Build status updates of commit _[7e20a0f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e20a0f2c4a6d7420462a03018bb9b2eb72eba92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-1e0daddd)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-1e0daddd"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-09 05:08 UTC, opbld31 commented
Docs Build status updates of commit _[38200b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/38200b5d956df071f08a6150e187ec0ff4145b93)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-388ef561)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-388ef561"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-09 05:14 UTC, opbld31 commented
Docs Build status updates of commit _[6fffe1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6fffe1c3ed760116f5b2eaf3a2b10789a997fba0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-2ed10772)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-2ed10772"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-09 05:17 UTC, opbld30 commented
Docs Build status updates of commit _[eab4565](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eab4565b1e0ab9e8ff5c95052293ab8956081b34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-bc4347d7)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-bc4347d7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-09 06:07 UTC, opbld32 commented
Docs Build status updates of commit _[76569ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/76569ffc982ed59593e31b5ce8b6fd30cca6e42c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-cbee8d21)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-cbee8d21"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-09 06:12 UTC, opbld34 commented
Docs Build status updates of commit _[2e3cfe3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e3cfe36df39dcdac70858beda66ec03900e5d26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-7809b521)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-7809b521"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-09 06:13 UTC, opbld30 commented
Docs Build status updates of commit _[26914c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26914c24a2389d362f79d1290199554580e9e7d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-b23966b7)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-b23966b7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-09 06:16 UTC, opbld32 commented
Docs Build status updates of commit _[7d2bf15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d2bf15c57e2deb04f3b2939f27b7a94f87de543)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-6707a364)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-6707a364"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-09 07:11 UTC, opbld34 commented
Docs Build status updates of commit _[1d3644f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d3644f57fba0a660dd1e373a30c204e5975ce1f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-68b36fbd)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |

<a id="de0bbbbb-68b36fbd"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-09 07:22 UTC, opbld31 commented
Docs Build status updates of commit _[d33fa59](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d33fa5985d936e31cafd398b97330c15a0dc7dd8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-eca2c85f)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Do [...]

2020-11-09 07:40 UTC, opbld31 commented
Docs Build status updates of commit _[b51acba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b51acba79a36e53eea20bc151aab9463a74c7452)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-2b67497e)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Do [...]

2020-11-09 14:19 UTC, opbld31 commented
Docs Build status updates of commit _[d8bfa1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8bfa1e057517adab6a8ef86323625a2cd75b478)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-17191807)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Do [...]

2020-11-10 09:41 UTC, opbld31 commented
Docs Build status updates of commit _[412e675](https://github.com/microsoftgraph/microsoft-graph-docs/commits/412e675fb88e4bc70cb2b437e151313eebcfe39e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-0f8fb202)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Do [...]

2020-11-10 23:46 UTC, laujan commented
Hi @Lauragra. This PR has been approved and is ready-to-merge (I hope). 🙂

2020-11-11 05:26 UTC, opbld32 commented
Docs Build status updates of commit _[240dbc9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/240dbc9c31d7cad3511d57e04783a1a62cb54954)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-cda1df45)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Do [...]

2020-11-11 05:41 UTC, Lauragra commented
@laujan , @KirtiPereira , we need to address the remaining comment about surfacing the user-specific API topics under Users/Teamwork in the TOC. They can be in both locations, but since we have separate files for the user-specific APIs, they should be in the Users node. For the IDs in the JSON file, just use an online GUID generator and use that ID for all the items in the changelist (not sure if I answered that question).

2020-11-11 08:20 UTC, opbld33 commented
Docs Build status updates of commit _[f35ee65](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f35ee65702146dc52d9bdac92b69836794c9fa86)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-d3b8b6bd)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Do [...]

2020-11-11 08:28 UTC, opbld33 commented
Docs Build status updates of commit _[f13ff5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f13ff5c88a9d7e7f4cadf96db03e800f6ed823b2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-425dfc02)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Do [...]

2020-11-11 08:36 UTC, opbld33 commented
Docs Build status updates of commit _[64c10e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64c10e2122c4edaa82086e62009f12efb85c2d65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-120f69ab)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Do [...]

2020-11-12 10:38 UTC, opbld32 commented
Docs Build status updates of commit _[f2c22a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2c22a23d57415d5079e47a2412cf3dbc61f953b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b7a4e5ba)

<a id="b7a4e5ba"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121038009118-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=McaRAMTeGJYW7R%2FehnNScusN9Hxw3ORb3ZNKR5mhXLA%3D&st=2020-11-12T10%3A33%3A21Z&se=2020-12-13T10%3A38%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 13:05 UTC, opbld34 commented
Docs Build status updates of commit _[3d07cd9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d07cd9b1205c3cb4369d08aa97db7cfe6523579)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b2091a6e)

<a id="b2091a6e"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121303576165-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lZ4%2BD6xkvw%2BR8NKaX2Ym8Eb9jmvrcefjH0VU4UX5qa8%3D&st=2020-11-12T13%3A00%3A01Z&se=2020-12-13T13%3A05%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 13:30 UTC, opbld33 commented
Docs Build status updates of commit _[6ba65e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6ba65e462c0ec97a9cc04e44340866da03a7edb8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e794de72)

<a id="e794de72"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121330264164-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Hhhptr%2F85zVA7tIUWWtmeexaB46%2B54f86bd5rooQ%2Fmk%3D&st=2020-11-12T13%3A25%3A49Z&se=2020-12-13T13%3A30%3A49Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 04:20 UTC, Lauragra commented
> @laujan , @KirtiPereira , we need to address the remaining comment about surfacing the user-specific API topics under Users/Teamwork in the TOC. They can be in both locations, but since we have separate files for the user-specific APIs, they should be in the Users node. For the IDs in the JSON file, just use an online GUID generator and use that ID for all the items in the changelist (not sure if I answered that question).
> 
> @laujan, @Lauragra, I have updated the TOCs, v1.0 and beta. I have also added the entries to the JSON file. Hope it is now ready to be merged. :)

One more thing - we have a merge conflict with the changelog. Please reference the instructions that Angela emailed about how to resolve the conflict. We did this to remove the long list of Warning we were getting on PRs. Thanks.

2020-11-13 04:38 UTC, opbld30 commented
Docs Build status updates of commit _[f78b8a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f78b8a9dbe52f311e8a720219eb45f122fe91f61)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1601466a)

<a id="1601466a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011130437428925-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PKn9z1WU2xHwYMa0ErbgbvO84sE8TRt3XIOfsD0dYCo%3D&st=2020-11-13T04%3A33%3A10Z&se=2020-12-14T04%3A38%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 04:38 UTC, opbld33 commented
Docs Build status updates of commit _[03d5028](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03d502826624c63bb70d92f6217f8545b830d7d7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-009c14dc)

<a id="009c14dc"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011130438214133-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HtK7L5S36vPU5Ld5Nu5wzOzRMSsQ43w%2FM6kdzS1d4JM%3D&st=2020-11-13T04%3A33%3A42Z&se=2020-12-14T04%3A38%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 15:25 UTC, opbld33 commented
Docs Build status updates of commit _[949fe23](https://github.com/microsoftgraph/microsoft-graph-docs/commits/949fe23f8a7f25feabd61a8dd623904bd79a55a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-79ccefb9)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Do [...]

2020-11-17 03:39 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | v1.0 | Added [Get the installed app in team](/graph/api/teamsappinstallation-get?view=graph-rest-v1.0), [List apps for user](/graph/api/user-list-teamsappinstallation?view=graph-rest-v1.
Please add `&preserve-view=true` to all the links to remove the warnings on the PR.

2020-11-17 03:42 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: List apps in team
For the user-based operations that we're surfacing under Users/Teamwork, we should also update the user.md file to add a Teamwork row in the Methods table and list the applicable methods.

2020-11-17 04:53 UTC, opbld34 commented
Docs Build status updates of commit _[90af0d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/90af0d63c03cf75d6b1ef02c70a8dedd743c10bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-fe86f5ce)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Do [...]

2020-11-17 04:56 UTC, opbld32 commented
Docs Build status updates of commit _[9f4b415](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f4b415d92700f54b0b24ed7d7f146c7b99f6821)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6f302778-edaf544b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-edaf544b)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-p [...]

2020-11-17 05:15 UTC, opbld33 commented
Docs Build status updates of commit _[916bb8c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/916bb8ce542ab0c3e4bd6b291ab3b42cbd09bcbf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6f302778-ac012770)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-ac012770)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-p [...]

2020-11-17 08:19 UTC, opbld30 commented
Docs Build status updates of commit _[2899708](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2899708e1ef3d3e711e0ea1ef047eb62d6b3d368)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6f302778-9438cd32)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/ [...]

2020-11-17 08:53 UTC, opbld33 commented
Docs Build status updates of commit _[9cefd87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9cefd87b65b15405eb02bff913faa3a975025b66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6f302778-e4d22163)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/ [...]

2020-11-17 19:04 UTC, laujan commented
Hi @Lauragra. Can this be merged today?

2020-11-17 19:28 UTC, Lauragra commented
> Hi @Lauragra. Can this be merged today?

@laujan , no, unfortunately the PR is not quite correct/accurate yet. I will leave comments.

2020-11-17 19:37 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: List apps in team
I don't know why these app-related methods are included in the User/Teamwork node. The method topics that include `user` in the syntax need to be surfaced here and listed in the user.md file Methods table. How are these APIs relevant to the user? Please clarify.

2020-11-17 19:43 UTC, Lauragra commented
@KirtiPereira , @laujan , please make sure that the User section of the TOC is useful/relevant and ensure that the methods listed in the User resource topic are accurate.

2020-11-18 03:51 UTC, opbld34 commented
Docs Build status updates of commit _[510abb0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/510abb0e212e2b20d6848157efbb112be518cae8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a92df879)

<a id="a92df879"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011180351111935-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qu%2BVbczQQdu6J7AP7qtyvLgIoX1rdWhRkdFFR9F1aWs%3D&st=2020-11-18T03%3A46%3A41Z&se=2020-12-19T03%3A51%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 03:53 UTC, opbld31 commented
Docs Build status updates of commit _[7b60727](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b6072718575075fe275ade78b5b3f853ecdc332)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f5ea55f1)

<a id="f5ea55f1"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011180352444821-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6P9bMkWlqihZ9%2B6GnIC17hXd8GOCe3fWuoXTdxnifvI%3D&st=2020-11-18T03%3A48%3A10Z&se=2020-12-19T03%3A53%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 07:19 UTC, opbld31 commented
Docs Build status updates of commit _[390deba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/390debaa287409533034571c080465a10e755779)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2c1abf96)

<a id="2c1abf96"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011180719107730-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YeH1ktgPEOCdbz1fDH4An4WKyrgbl1un53F6iJSpm44%3D&st=2020-11-18T07%3A14%3A39Z&se=2020-12-19T07%3A19%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 08:54 UTC, opbld30 commented
Docs Build status updates of commit _[c3d1cdc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c3d1cdc834518ad1f779f52af79583c653007182)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6f302778-3472f348)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-3472f348)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-p [...]

2020-11-18 09:35 UTC, opbld30 commented
Docs Build status updates of commit _[92eeabd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92eeabdec6d6fecc43ef0300ec0a72a232f0ed8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6f302778-996dfa01)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/ [...]

2020-11-18 10:39 UTC, opbld33 commented
Docs Build status updates of commit _[084d0cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/084d0cd9417885c71f5f829f0ca927ce11b6b21b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6f302778-98b5028a)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/ [...]

2020-11-18 10:41 UTC, opbld33 commented
Docs Build status updates of commit _[56cc05b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56cc05b91dbf439ab0a687ff425dc8f23b46490c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6f302778-d6a0fc72)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/ [...]

2020-11-19 06:22 UTC, opbld32 commented
Docs Build status updates of commit _[88bde04](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88bde04aa50c318dfc78372919f96742f188b677)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6f302778-809d547c)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-809d547c)
[api-reference/beta/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/teamsappinstallation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/teamsappinstallation-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsappinstallation-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-add-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-delete-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-delete-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-delete-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-get-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-get-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-list-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-upgrade-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/user-upgrade-teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-upgrade-teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-p [...]

2020-11-21 03:08 UTC, AkJo commented on concepts/changelog.md
> -|Addition|beta|Added [create](/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&preserve-view=true), [delete](/graph/api/accessreviewscheduledefinition-delete?view=graph-rest-beta
Please ensure that in the final files that are put in, all these changes dont show up. 

At times, you will need to selectively copy-paste individual items from the autogenerated stubs.

2020-11-21 03:09 UTC, AkJo commented on api-reference/beta/api/teamsappinstallation-get.md
> +title: "Get installed app in team"
In light of the explanation I posted, this file will become

userteamwork-get-installedapps.md

2020-11-21 03:10 UTC, AkJo commented on api-reference/beta/api/user-get-teamsappinstallation.md
> +---
userteamwork-get-installedapps.md

2020-11-21 03:10 UTC, AkJo commented on api-reference/beta/api/user-get-teamsappinstallation.md
> +GET https://graph.microsoft.com/beta/users/{id}/teamwork/installedApps/{id}
Please use illustrative values in both the request and response examples.

2020-11-21 03:11 UTC, AkJo commented on api-reference/beta/api/userscopeteamsappinstallation-get-chat.md
> +GET https://graph.microsoft.com/beta/users/{id}/teamwork/installedApps/{id}/chat
Please use illustrative values here and in other files.

2020-11-21 03:14 UTC, AkJo commented on api-reference/beta/toc.yml
>            href: api/user-add-teamsappinstallation.md
Please rename this file to 

userteamwork-add-installedapps.md

2020-11-21 03:15 UTC, AkJo commented on api-reference/beta/toc.yml
>            href: api/user-list-teamsappinstallation.md
userteamwork-list-installedapps.md

2020-11-21 03:16 UTC, AkJo commented on api-reference/beta/toc.yml
> +          href: api/user-get-teamsappinstallation.md
Please rename this reference and the corresponding filename to
userteamwork-get-installedapps.md

2020-11-21 03:21 UTC, AkJo commented on api-reference/beta/toc.yml
>            href: api/user-upgrade-teamsappinstallation.md
Please rename this reference and the corresponding filename to
userteamwork-upgrade-installedApps.md

2020-11-21 03:21 UTC, AkJo commented on api-reference/beta/toc.yml
>            href: api/user-delete-teamsappinstallation.md
Please rename this reference and the corresponding filename to
userteamwork-delete-installedApps.md

Make the change in both beta and v1.

2020-11-21 03:23 UTC, AkJo commented on api-reference/beta/toc.yml
> +          href: api/teamsappinstallation-get.md
Please rename this reference and the corresponding filename to
team-get-installedapps.md

Make the change in both beta and v1.

2020-11-21 03:24 UTC, AkJo commented on api-reference/beta/toc.yml
>            href: api/teamsappinstallation-list.md
Please rename this reference and the corresponding filename to
team-list-installedapps.md

Make the change in both beta and v1.

2020-11-21 03:25 UTC, AkJo commented on api-reference/beta/toc.yml
>            href: api/teamsappinstallation-add.md
Please rename this reference and the corresponding filename to
team-add-installedapps.md

Make the change in both beta and v1.

2020-11-21 03:25 UTC, AkJo commented on api-reference/beta/toc.yml
>            href: api/teamsappinstallation-upgrade.md
Please rename this reference and the corresponding filename to
team-upgrade-installedapps.md

Make the change in both beta and v1.

2020-11-21 03:26 UTC, AkJo commented on api-reference/beta/toc.yml
>            href: api/user-list-teamsappinstallation.md
Please rename this reference and the corresponding filename to
userteamwork-list-installedapps.md

Make the change in both beta and v1.

2020-11-21 03:26 UTC, AkJo commented on api-reference/beta/toc.yml
> +          href: api/user-get-teamsappinstallation.md
Please rename this reference and the corresponding filename to
userteamwork-get-installedapps.md

Make the change in both beta and v1.

2020-11-23 13:27 UTC, opbld34 commented
Docs Build status updates of commit _[9e1ddc2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e1ddc2c0efc33a4994a1369186021595ee81e0b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b9bb8ef1)

<a id="b9bb8ef1"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011231325513198-10368%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Wbps6XHo7mpzOKru%2FFDELpPBZR%2FUuBUfSgndKOufI4Q%3D&st=2020-11-23T13%3A22%3A07Z&se=2020-12-24T13%3A27%3A07Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-23 15:07 UTC, KirtiPereira commented on api-reference/beta/api/userscopeteamsappinstallation-get-chat.md
> +GET https://graph.microsoft.com/beta/users/{id}/teamwork/installedApps/{id}/chat
Hi @AkJo - sharing a scenario related to information for illustrative examples.
The beta (reference file - userteamwork-add-installedapps.md) file does not have an actual code in its request body. In such scenario, who will be assist us in getting the actual values? Please advise. Have also shared the query on the Teams channel.
![image](https://user-images.githubusercontent.com/70375155/99977894-40943d80-2dcb-11eb-9662-f521087bab78.png)

2020-11-23 15:13 UTC, opbld33 commented
Docs Build status updates of commit _[3b01c20](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b01c2033553f5beec2bed2d8e1d4063ed859c93)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-8fa18829-0090e26a)
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-1eb09cd3-0090e26a)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-00685cff-0090e26a)
[api-reference/beta/api/educationalactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/educationalactivity-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-e82c98d3-0090e26a)
[api-reference/beta/api/educationalactivity-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/educationalactivity-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-591908b5-0090e26a)
[api-reference/beta/api/ediscoverycase-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-0cf87949-0090e26a)
[api-reference/beta/api/ediscoverycase-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-6bb5760f-0090e26a)
[api-reference/beta/api/ediscoverycase-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-list?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-686f0a31-0090e26a)
[api-reference/beta/api/ediscoverycase-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-07b05d2b-0090e26a)
[api-reference/v1.0/api/driveitem-restore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/driveitem-restore.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-restore?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6b881ac2-0090e26a)
[api-reference/beta/api/educationalactivity-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/educationalactivity-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-c8045151-0090e26a)
[api-reference/beta/api/ediscoverycase-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-post?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-f03fc281-0090e26a)
[api-reference/beta/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-a1580d42-0090e26a)
[api-reference/beta/api/itememail-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/itememail-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itememail-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-c226f87f-0090e26a)
[api-reference/beta/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/opentypeextension-post-opentypeextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-58f4f899-0090e26a)
[api-reference/beta/api/personanniversary-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/personanniversary-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/personanniversary-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-c59257ba-0090e26a)
[api-reference/v1.0/api/opentypeextension-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/opentypeextension-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-0c321835-0090e26a)
[api-reference/beta/api/personannotation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/personannotation-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/personannotation-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-3dec620d-0090e26a)
[api-reference/v1.0/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-grap [...]

2020-11-23 15:38 UTC, opbld31 commented
Docs Build status updates of commit _[a420d2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a420d2bfb910e18e7e0bebeea0198b737df94853)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-00685cff-316e82a3)
[api-reference/beta/api/ediscoverycase-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-0cf87949-316e82a3)
[api-reference/v1.0/api/driveitem-restore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/driveitem-restore.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-restore?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6b881ac2-316e82a3)
[api-reference/beta/api/ediscoverycase-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-list?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-686f0a31-316e82a3)
[api-reference/beta/api/educationalactivity-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/educationalactivity-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-591908b5-316e82a3)
[api-reference/beta/api/ediscoverycase-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-post?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-f03fc281-316e82a3)
[api-reference/beta/api/educationalactivity-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/educationalactivity-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-c8045151-316e82a3)
[api-reference/beta/api/ediscoverycase-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-07b05d2b-316e82a3)
[api-reference/beta/api/educationalactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/educationalactivity-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-e82c98d3-316e82a3)
[api-reference/beta/api/ediscoverycase-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-6bb5760f-316e82a3)
[api-reference/beta/api/itememail-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/itememail-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itememail-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-c226f87f-316e82a3)
[api-reference/beta/api/profile-list-names.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/profile-list-names.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profile-list-names?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-6ca69c4c-316e82a3)
[api-reference/beta/api/profile-list-educationalactivities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/profile-list-educationalactivities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profile-list-educationalactivities?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-65936f61-316e82a3)
[api-reference/beta/api/reviewset-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/reviewset-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reviewset-list?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-d8aefba9-316e82a3)
[api-reference/beta/api/profile-list-skills.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/profile-list-skills.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profile-list-skills?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-b102097b-316e82a3)
[api-reference/beta/api/profile-list-languages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/profile-list-languages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profile-list-languages?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-282683b3-316e82a3)
[api-reference/beta/api/itememail-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/itememail-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itememail-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-5646d896-316e82a3)
[api-reference/beta/api/itememail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/itememail-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itememail-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-0f0b99f0-316e82a3)
[api-reference/beta/api/itemphone-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/itemphone-delete.md) | :warning:Warning | [View] [...]

2020-11-23 15:49 UTC, opbld30 commented
Docs Build status updates of commit _[3524902](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35249025e0b92e3b2b3d0a1e45b6b0b448fa4369)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-00685cff-577d9815)
[api-reference/beta/api/ediscoverycase-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-6bb5760f-577d9815)
[api-reference/beta/api/educationalactivity-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/educationalactivity-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-c8045151-577d9815)
[api-reference/beta/api/ediscoverycase-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-0cf87949-577d9815)
[api-reference/beta/api/educationalactivity-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/educationalactivity-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-591908b5-577d9815)
[api-reference/beta/api/ediscoverycase-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-list?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-686f0a31-577d9815)
[api-reference/beta/api/ediscoverycase-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-post?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-f03fc281-577d9815)
[api-reference/beta/api/ediscoverycase-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-07b05d2b-577d9815)
[api-reference/beta/api/educationalactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/educationalactivity-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-e82c98d3-577d9815)
[api-reference/beta/api/schemaextension-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/schemaextension-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-list?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-4b5fe64a-577d9815)
[api-reference/beta/api/profile-list-anniversaries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/profile-list-anniversaries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profile-list-anniversaries?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-883905e1-577d9815)
[api-reference/beta/api/itempublication-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/itempublication-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itempublication-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-fa65ab22-577d9815)
[api-reference/beta/api/profile-post-responsibilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/profile-post-responsibilities.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profile-post-responsibilities?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-2baca794-577d9815)
[api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/opentypeextension-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-6851a216-577d9815)
[api-reference/v1.0/api/schemaextension-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/schemaextension-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-list?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-c4b1ebb5-577d9815)
[api-reference/beta/api/schemaextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/schemaextension-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-c4adad6c-577d9815)
[api-reference/v1.0/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/opentypeextension-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-9243f0eb-577d9815)
[api-reference/v1.0/api/schemaextension-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/schemaextension-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-delete?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-3e8b662b-577d9815)
[api-reference/beta/api/personwebsite-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs [...]

2020-11-23 15:53 UTC, opbld30 commented
Docs Build status updates of commit _[486d4ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/486d4ca0b7fcee60d7d3846ddbd9efcad7b2b369)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-00685cff-e69516c1)
[api-reference/beta/api/educationalactivity-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/educationalactivity-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-591908b5-e69516c1)
[api-reference/beta/api/educationalactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/educationalactivity-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-e82c98d3-e69516c1)
[api-reference/beta/api/educationalactivity-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/educationalactivity-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-c8045151-e69516c1)
[api-reference/beta/api/ediscoverycase-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-0cf87949-e69516c1)
[api-reference/beta/api/ediscoverycase-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-list?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-686f0a31-e69516c1)
[api-reference/v1.0/api/driveitem-restore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/driveitem-restore.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-restore?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6b881ac2-e69516c1)
[api-reference/beta/api/ediscoverycase-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-6bb5760f-e69516c1)
[api-reference/beta/api/ediscoverycase-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-07b05d2b-e69516c1)
[api-reference/beta/api/ediscoverycase-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-post?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-f03fc281-e69516c1)
[api-reference/beta/api/profile-post-websites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/profile-post-websites.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profile-post-websites?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-3d60f692-e69516c1)
[api-reference/beta/api/profilecardproperty-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/profilecardproperty-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profilecardproperty-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-fc2a5579-e69516c1)
[api-reference/beta/api/itempublication-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/itempublication-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itempublication-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-fa65ab22-e69516c1)
[api-reference/beta/api/personcertification-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/personcertification-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/personcertification-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-66bf0cd5-e69516c1)
[api-reference/beta/api/itemaddress-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/itemaddress-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itemaddress-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-e30157c7-e69516c1)
[api-reference/beta/api/profile-post-patents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/profile-post-patents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profile-post-patents?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-b0c80f15-e69516c1)
[api-reference/beta/api/projectparticipation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/projectparticipation-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/projectparticipation-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-4860db35-e69516c1)
[api-reference/beta/api/profile-list-languages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/profile-list-languages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profile-list-languages?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-282683b3-e69516c1)
[api-reference/beta/api/personannotation-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installed [...]

2020-11-23 16:01 UTC, opbld32 commented
Docs Build status updates of commit _[cc184a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc184a045df20008a9b5f66258904be258597fc1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-00685cff-9ad88892)
[api-reference/beta/api/ediscoverycase-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-post?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-f03fc281-9ad88892)
[api-reference/beta/api/educationalactivity-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/educationalactivity-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-591908b5-9ad88892)
[api-reference/beta/api/educationalactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/educationalactivity-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-e82c98d3-9ad88892)
[api-reference/beta/api/ediscoverycase-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-6bb5760f-9ad88892)
[api-reference/beta/api/ediscoverycase-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-list?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-686f0a31-9ad88892)
[api-reference/v1.0/api/driveitem-restore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/driveitem-restore.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-restore?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6b881ac2-9ad88892)
[api-reference/beta/api/ediscoverycase-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-07b05d2b-9ad88892)
[api-reference/beta/api/educationalactivity-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/educationalactivity-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-c8045151-9ad88892)
[api-reference/beta/api/ediscoverycase-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/ediscoverycase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-0cf87949-9ad88892)
[api-reference/beta/api/itememail-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/itememail-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itememail-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-0f0b99f0-9ad88892)
[api-reference/beta/api/itememail-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/itememail-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itememail-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-c226f87f-9ad88892)
[api-reference/beta/api/languageproficiency-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/languageproficiency-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/languageproficiency-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-c3b5b781-9ad88892)
[api-reference/beta/api/languageproficiency-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/languageproficiency-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/languageproficiency-get?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-97109511-9ad88892)
[api-reference/beta/api/profile-list-phones.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/profile-list-phones.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profile-list-phones?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-203517f2-9ad88892)
[api-reference/beta/api/personannotation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/personannotation-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/personannotation-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-3dec620d-9ad88892)
[api-reference/beta/api/itemaddress-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/itemaddress-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itemaddress-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-e30157c7-9ad88892)
[api-reference/beta/api/personanniversary-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/personanniversary-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/personanniversary-update?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-2070f4ae-9ad88892)
[api-reference/beta/api/profile-list-certifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/profile [...]

2020-11-25 00:00 UTC, laujan commented
Hi @Lauragra. This PR is ready-to-merge.

2020-11-27 10:27 UTC, opbld30 commented
Docs Build status updates of commit _[d70c1e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d70c1e0c146f5b8a16a242c996696dec2e9f61d3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-00685cff-9423324f)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6f302778-9423324f)
[api-reference/beta/api/team-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/team-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-add-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-add-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-add-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-upgrade-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-upgrade-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-upgrade-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/team-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/team-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-add-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-add-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-add-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-delete-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-get-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?vie [...]

2020-11-27 11:17 UTC, opbld31 commented
Docs Build status updates of commit _[7fa131a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7fa131a9c82289109c4a2e53a8f946571d482e24)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-00685cff-a21e1a25)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6f302778-a21e1a25)
[api-reference/beta/api/team-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/team-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-add-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-add-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-add-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-upgrade-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-upgrade-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-upgrade-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/team-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/team-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-add-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-add-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-add-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-delete-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-get-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?vie [...]

2020-11-27 11:29 UTC, opbld32 commented
Docs Build status updates of commit _[599263a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/599263a234cf2a427b01d8ed9d4925c44bb22dab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6f302778-a35be55b)
[api-reference/beta/api/team-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/team-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-add-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-add-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-add-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-upgrade-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-upgrade-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-upgrade-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/team-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/team-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-add-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-add-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-add-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-delete-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-get-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?view=graph-rest-1.0&branch=p [...]

2020-11-30 22:40 UTC, laujan commented
Hi @Lauragra. This PR is ready-to-merge.  🤞

2020-12-01 05:39 UTC, opbld30 commented
Docs Build status updates of commit _[db0f4fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db0f4fe577a9293d092be0247f8e5b71c67ba53d)_: 

:clock10: **Pending**: waiting for processors ([8](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-01 05:40 UTC, opbld30 commented
Docs Build status updates of commit _[db0f4fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db0f4fe577a9293d092be0247f8e5b71c67ba53d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6f302778-d73ce392)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-d73ce392)
[api-reference/beta/api/team-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/team-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-add-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-add-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-add-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-upgrade-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-upgrade-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-upgrade-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/team-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/team-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-add-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-add-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-add-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-delete-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-get-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-list-installedapps.md](https://g [...]

2020-12-01 05:56 UTC, opbld32 commented
Docs Build status updates of commit _[4ee3ec0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ee3ec085244aac580ea5180e31a2e2832a9d0ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6f302778-ff941670)
[api-reference/beta/api/team-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/team-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-add-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-add-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-add-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-upgrade-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-upgrade-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-upgrade-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/team-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/team-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-add-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-add-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-add-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-delete-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-get-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?view=graph-rest-1.0&branch=p [...]

2020-12-01 22:37 UTC, laujan commented
Hi @Lauragra. This PR is ready-to-merge.

2020-12-03 03:11 UTC, laujan commented
Hi @Lauragra is PR this ready-to-merge?

2020-12-03 03:11 UTC, laujan commented
Hi @Lauragra is PR this ready-to-merge?

2020-12-03 03:11 UTC, laujan commented
Hi @Lauragra is PRthis ready-to-merge?

2020-12-03 03:42 UTC, Lauragra approved these changes

2020-12-03 03:43 UTC, opbld33 commented
Docs Build status updates of commit _[eda2058](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eda2058a7a8b0c1e1ae1e881dfbc791d69b4dfc8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10368) | [Details](#user-content-de0bbbbb-eed49e7f)
[concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/concepts/delta-query-messages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-messages?branch=pr-en-us-10368) | [Details](#user-content-c9976108-eed49e7f)
[api-reference/beta/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/accesspackage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) | [Details](#user-content-3cb7c294-eed49e7f)
[api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/resources/user.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) | [Details](#user-content-6f302778-eed49e7f)
[api-reference/beta/api/team-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/team-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-add-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-add-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-add-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-upgrade-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/api/userteamwork-upgrade-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-upgrade-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/resources/userscopeteamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/resources/userscopeteamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userscopeteamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-beta&branch=pr-en-us-10368) (graph-rest-beta) |
[api-reference/v1.0/api/team-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/team-get-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userscopeteamsappinstallation-get-chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-add-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messaging-and-installedApps/api-reference/v1.0/api/userteamwork-add-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-add-installedapps?view=graph-rest-1.0&branch=pr-en-us-10368) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/1242148-Docs]-GA-proactive-messa [...]

2020-12-03 03:48 UTC, merged