bugfix/lifecycle-notifications-adjustments
microsoftgraph/microsoft-graph-docs pull request #10399
Opened 2020-10-23 12:17 UTC by baywet

2020-10-23 12:19 UTC, opbld34 commented
Docs Build status updates of commit _[af4a48d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af4a48dbdca227e8eb1bb372b3c7caf5ff36066d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bugfix/lifecycle-notifications-adjustments/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10399) | [Details](#user-content-de0bbbbb-9c4cc0ab)
[concepts/webhooks-lifecycle.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bugfix/lifecycle-notifications-adjustments/concepts/webhooks-lifecycle.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-lifecycle?branch=pr-en-us-10399) | [Details](#user-content-c9e53fdc-9c4cc0ab)

<a id="de0bbbbb-9c4cc0ab"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bugfix/lifecycle-notifications-adjustments/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjobstatus?view=graph-rest-beta`````
 - **Line 63, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjobstatus?view=graph-rest-beta`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph-rest-beta`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateaccountsummary?view= [...]

2020-10-23 23:09 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Addition | v1.0 | Added [lifecycle notifications](./webhooks-lifecycle.md) for personal [chatMessage][/graph/api/resources/chatmessage?view=graph-rest-1.0], [contact][/graph/api/resources/contact?v
@baywet , does chatMessage in beta support lifecycle notifications as well? 
If so, is beta support also new?
If beta support is new, then we should add that as a separate table row for the beta version.

2020-10-23 23:10 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Addition | v1.0 | Added [lifecycle notifications](./webhooks-lifecycle.md) for personal [chatMessage][/graph/api/resources/chatmessage?view=graph-rest-1.0], [contact][/graph/api/resources/contact?v
Also, the links are not properly formatted with curly brackets, please fix.

2020-10-23 23:12 UTC, angelgolfer-ms commented on concepts/webhooks-lifecycle.md
> +Lifecycle notifications are emitted for subscriptions created on these resource types:
Line 30:
Please replace "emitted" by "supported", to use a more commonly used term, per Microsoft Voice: https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=29173

2020-10-23 23:14 UTC, angelgolfer-ms requested changes
@baywet , thank you so much for patching up with this PR!
Just three minor comments, please take a look. 
Apart from those issues, the PR looks good to be merged.

2020-10-24 01:29 UTC, opbld33 commented
Docs Build status updates of commit _[a0c24f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0c24f69afaeba7526d25b3aa35f5b31d3db1eee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bugfix/lifecycle-notifications-adjustments/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10399) | [Details](#user-content-de0bbbbb-e5237af2)
[concepts/webhooks-lifecycle.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bugfix/lifecycle-notifications-adjustments/concepts/webhooks-lifecycle.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-lifecycle?branch=pr-en-us-10399) | [Details](#user-content-c9e53fdc-e5237af2)

<a id="de0bbbbb-e5237af2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bugfix/lifecycle-notifications-adjustments/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjobstatus?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjobstatus?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-devices-devicecustomattributeshellscript?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfig-macossoftwareupdateaccountsummary?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfi [...]

2020-10-24 02:14 UTC, opbld34 commented
Docs Build status updates of commit _[2e126fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e126facae854c6950675af4ada7e4c8a7f9278d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bugfix/lifecycle-notifications-adjustments/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10399) | [Details](#user-content-de0bbbbb-586b0832)
[concepts/webhooks-lifecycle.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bugfix/lifecycle-notifications-adjustments/concepts/webhooks-lifecycle.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-lifecycle?branch=pr-en-us-10399) | [Details](#user-content-c9e53fdc-586b0832)

<a id="de0bbbbb-586b0832"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bugfix/lifecycle-notifications-adjustments/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjobstatus?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you m [...]

2020-10-24 02:16 UTC, opbld30 commented
Docs Build status updates of commit _[dcb1ad8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dcb1ad882bbc56acdeaa5fe59dbc5b05faf7cbcf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bugfix/lifecycle-notifications-adjustments/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10399) | [Details](#user-content-de0bbbbb-838291db)
[concepts/webhooks-lifecycle.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bugfix/lifecycle-notifications-adjustments/concepts/webhooks-lifecycle.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-lifecycle?branch=pr-en-us-10399) | [Details](#user-content-c9e53fdc-838291db)

<a id="de0bbbbb-838291db"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bugfix/lifecycle-notifications-adjustments/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjobstatus?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you m [...]

2020-10-24 02:19 UTC, Lauragra approved these changes

2020-10-26 12:10 UTC, baywet commented on concepts/changelog.md
> +| Addition | v1.0 | Added [lifecycle notifications](./webhooks-lifecycle.md) for personal [chatMessage][/graph/api/resources/chatmessage?view=graph-rest-1.0], [contact][/graph/api/resources/contact?v
@Lauragra thanks for fixing the links.
@angelgolfer-ms thanks for the feedback. lifecycle notifications has been in beta for chatMessages, events, messages and contacts for almost a year now. There should have been a changelog entry created by Peter back then. The only changes we're introducing at this point is the GA of that capability on those resources.

2020-10-26 12:10 UTC, baywet commented on concepts/webhooks-lifecycle.md
> +Lifecycle notifications are emitted for subscriptions created on these resource types:
@Lauragra thanks for making the change!

2020-10-26 12:13 UTC, opbld32 commented
Docs Build status updates of commit _[d8b8d1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8b8d1dc732adba5bd8149f5f8df49ad0357382a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bugfix/lifecycle-notifications-adjustments/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10399) | [Details](#user-content-de0bbbbb-8d41cb8a)
[concepts/webhooks-lifecycle.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bugfix/lifecycle-notifications-adjustments/concepts/webhooks-lifecycle.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks-lifecycle?branch=pr-en-us-10399) | [Details](#user-content-c9e53fdc-8d41cb8a)

<a id="de0bbbbb-8d41cb8a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bugfix/lifecycle-notifications-adjustments/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/fido2AuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethod?view=graph-rest-beta`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printdocument?view=graph-rest-beta`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-restorefactorydefaults?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-start?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 52, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-cancel?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printercapabilities?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printerstatus?view=graph-rest-beta`````
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjobstatus?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you m [...]

2020-10-27 00:20 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Addition | v1.0 | Added [lifecycle notifications](./webhooks-lifecycle.md) for personal [chatMessage][/graph/api/resources/chatmessage?view=graph-rest-1.0], [contact][/graph/api/resources/contact?v
Ok, I see where our disconnect is - I searched the changelog, it only mentions in Dec. 2019, chatMessage started supporting notifications with resource data. There's no separate mention of lifecycle notifications for chatMessage.

2020-10-27 00:21 UTC, angelgolfer-ms approved these changes
Thanks for doc updates and clarification.

2020-10-27 01:07 UTC, merged