Add CloudPC documentation
microsoftgraph/microsoft-graph-docs pull request #10412
Opened 2020-10-24 12:39 UTC by AshleyYangSZ

Add CloudPC API and resource doc with the generated files.

2020-10-24 12:40 UTC, opbld34 commented
Docs Build status updates of commit _[bed17bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bed17bf5b46daab26c49b401c5d5c07bfc7734ee)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f7484e15)

<a id="f7484e15"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010241239452188-10412%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3EAT2pqiwOG5dXbOuZCJhfcBOo0tO29Rg67fKkdrX5Q%3D&st=2020-10-24T12%3A35%3A13Z&se=2020-11-24T12%3A40%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-26 07:37 UTC, opbld34 commented
Docs Build status updates of commit _[c0e627c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0e627ca9dac2208ece7beae2e4c827ce5f470ef)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-f7e6a331)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-f7e6a331)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-f7e6a331)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-f7e6a331)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-f7e6a331)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-f7e6a331)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-f7e6a331)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-f7e6a331)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-f7e6a331)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-f7e6a331)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-f7e6a331)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-f7e6a331)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-f7e6a331)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-f7e6a331)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-f7e6a331)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-f7e6a331)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-40a3f613-f7e6a331)
[api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-referenc [...]

2020-10-26 07:42 UTC, opbld31 commented
Docs Build status updates of commit _[692c602](https://github.com/microsoftgraph/microsoft-graph-docs/commits/692c6021ac922f8ade83bb4d8931cd93d660e1f0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-4b137bc0)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-4b137bc0)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-4b137bc0)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-4b137bc0)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-4b137bc0)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-4b137bc0)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-4b137bc0)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-4b137bc0)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-4b137bc0)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-4b137bc0)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-4b137bc0)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-4b137bc0)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-4b137bc0)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-4b137bc0)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-4b137bc0)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-4b137bc0)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-40a3f613-4b137bc0)
[api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-referenc [...]

2020-10-26 09:23 UTC, opbld33 commented
Docs Build status updates of commit _[9fcf6f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9fcf6f931ed936b5581297f208a60e630a7978e3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-f4866c4a)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-f4866c4a)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-f4866c4a)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-f4866c4a)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-f4866c4a)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-f4866c4a)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-f4866c4a)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-f4866c4a)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-f4866c4a)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-f4866c4a)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-f4866c4a)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-f4866c4a)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-f4866c4a)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-f4866c4a)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-f4866c4a)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-f4866c4a)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-40a3f613-f4866c4a)
[api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-referenc [...]

2020-10-26 11:40 UTC, opbld31 commented
Docs Build status updates of commit _[04cd8ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04cd8ee47c1ca826afd1794b4f41ab615d6f82b8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-15332ba4)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-15332ba4)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-15332ba4)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-15332ba4)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-15332ba4)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-15332ba4)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-15332ba4)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-15332ba4)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-15332ba4)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-15332ba4)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-15332ba4)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-15332ba4)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-15332ba4)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-15332ba4)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-15332ba4)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-15332ba4)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-40a3f613-15332ba4)
[api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-referenc [...]

2020-10-26 12:48 UTC, opbld31 commented
Docs Build status updates of commit _[353bf24](https://github.com/microsoftgraph/microsoft-graph-docs/commits/353bf24300a52b305bc746caae4ce982a9768073)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-4247ad22)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-4247ad22)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-4247ad22)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-4247ad22)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-4247ad22)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-4247ad22)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-4247ad22)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-4247ad22)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-4247ad22)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-4247ad22)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-4247ad22)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-4247ad22)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-4247ad22)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-4247ad22)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-4247ad22)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-4247ad22)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-40a3f613-4247ad22)
[api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-referenc [...]

2020-10-26 14:18 UTC, opbld31 commented
Docs Build status updates of commit _[6782061](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67820617656a196450e4ffc9cf1b0f282b947f39)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-ead00f15)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-ead00f15)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-ead00f15)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-ead00f15)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-ead00f15)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-ead00f15)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-ead00f15)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-ead00f15)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-ead00f15)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-ead00f15)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-ead00f15)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-ead00f15)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-ead00f15)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-ead00f15)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-ead00f15)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-ead00f15)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-40a3f613-ead00f15)
[api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-referenc [...]

2020-10-26 15:02 UTC, opbld34 commented
Docs Build status updates of commit _[191a37b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/191a37b08e50d7491fd0dc01a58c7b7a4c468e67)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-fee309fa)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-fee309fa)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-fee309fa)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-fee309fa)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-fee309fa)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-fee309fa)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-fee309fa)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-fee309fa)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-fee309fa)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-fee309fa)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-fee309fa)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-fee309fa)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-fee309fa)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-fee309fa)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-fee309fa)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-fee309fa)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-40a3f613-fee309fa)
[api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-referenc [...]

2020-10-26 15:29 UTC, wandeg commented on api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md
> +        "@odata.type": "microsoft.graph.cloudPcManagementAssignmentTarget
I believe there should be a comma and quotes at the end of this line
```suggestion
        "@odata.type": "microsoft.graph.cloudPcManagementAssignmentTarget",
```

2020-10-27 05:54 UTC, opbld34 commented
Docs Build status updates of commit _[e2aeb14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2aeb14fa2856c2df8a18607fcd2d6b5c5265487)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-3bed1338)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-3bed1338)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-3bed1338)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-3bed1338)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-3bed1338)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-3bed1338)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-3bed1338)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-3bed1338)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-3bed1338)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-3bed1338)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-3bed1338)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-3bed1338)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-3bed1338)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-3bed1338)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-3bed1338)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-3bed1338)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-40a3f613-3bed1338)
[api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-referenc [...]

2020-10-28 02:47 UTC, opbld34 commented
Docs Build status updates of commit _[0331f14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0331f14333a10466e115ecb2e8d58c5fc828166f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-e4de0444)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-e4de0444)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-e4de0444)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-e4de0444)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-e4de0444)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-e4de0444)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-e4de0444)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-e4de0444)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-e4de0444)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-e4de0444)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-e4de0444)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-e4de0444)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-e4de0444)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-e4de0444)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-e4de0444)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-e4de0444)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-40a3f613-e4de0444)
[api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-referenc [...]

2020-10-28 02:52 UTC, opbld32 commented
Docs Build status updates of commit _[8412e0a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8412e0ad3669e9786097cd8189ec67b2de8617ad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-cfc641c7)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-cfc641c7)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-cfc641c7)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-cfc641c7)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-cfc641c7)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-cfc641c7)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-cfc641c7)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-cfc641c7)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-cfc641c7)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-cfc641c7)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-cfc641c7)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-cfc641c7)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-cfc641c7)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-cfc641c7)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-cfc641c7)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-cfc641c7)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-post-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-40a3f613-cfc641c7)
[api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-referenc [...]

2020-11-02 09:00 UTC, opbld31 commented
Docs Build status updates of commit _[6a6d3c3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a6d3c3b42c48f5a9fd3ef131ecaa9ae50b7494a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-7369a0a9)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-7369a0a9)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-7369a0a9)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-7369a0a9)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-7369a0a9)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-7369a0a9)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-7369a0a9)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-7369a0a9)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-7369a0a9)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-7369a0a9)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-7369a0a9)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-7369a0a9)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-7369a0a9)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-7369a0a9)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-7369a0a9)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-7369a0a9)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-7369a0a9)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) |  [...]

2020-11-02 09:27 UTC, opbld34 commented
Docs Build status updates of commit _[513aaa0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/513aaa021d4048614b39f2e336ebc8f081af5e22)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-884078c6)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-884078c6)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-884078c6)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-884078c6)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-884078c6)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-884078c6)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-884078c6)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-884078c6)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-884078c6)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-884078c6)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-884078c6)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-884078c6)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-884078c6)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-884078c6)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-884078c6)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-884078c6)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-884078c6)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) |  [...]

2020-11-04 08:52 UTC, opbld34 commented
Docs Build status updates of commit _[9bb6d88](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9bb6d88920418f903dde03cc3bb62ee4e40a7fcb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-ab3b4783)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-ab3b4783)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-ab3b4783)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-ab3b4783)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-ab3b4783)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-ab3b4783)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-ab3b4783)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-ab3b4783)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-ab3b4783)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-ab3b4783)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-ab3b4783)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-ab3b4783)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-ab3b4783)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-ab3b4783)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-ab3b4783)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-ab3b4783)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-ab3b4783)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) |  [...]

2020-11-04 08:52 UTC, timefrozen19 commented on api-reference/beta/resources/cloudpc.md
> +|id|String|The Cloud PC ID|
Missing period.

2020-11-04 08:57 UTC, timefrozen19 commented on api-reference/beta/api/virtualendpoint-list-cloudpcs.md
> +      "managedDeviceName": " Managed Device Name value",
Extra space before "Managed"

2020-11-04 08:59 UTC, opbld30 commented
Docs Build status updates of commit _[c2821e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2821e5832f5723b417ef5eab20f7764c3dc3d00)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-e7df2398)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-e7df2398)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-e7df2398)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-e7df2398)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-e7df2398)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-e7df2398)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-e7df2398)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-e7df2398)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-e7df2398)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-e7df2398)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-e7df2398)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-e7df2398)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-e7df2398)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-e7df2398)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-e7df2398)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-e7df2398)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-e7df2398)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) |  [...]

2020-11-04 09:00 UTC, timefrozen19 commented on api-reference/beta/api/virtualendpoint-get-cloudpc.md
> +    "code": "internalServerError",
Let us use sample words instead of "internalServerError", "There was an internal server error. Please contact IT support." here, because I don't think current values are accurate.

2020-11-04 09:02 UTC, timefrozen19 commented on api-reference/beta/api/virtualendpoint-get-cloudpc.md
> +          "value": "52367774-cfb7-4e9c-ab51-1b864c31ffff"
Same here. These values are not accurate. Let us remove it for now.

2020-11-04 09:04 UTC, timefrozen19 commented on api-reference/beta/toc.yml
> +      - name: Virtual endpoint(preview)
Add a space before "(".

2020-11-04 14:03 UTC, opbld31 commented
Docs Build status updates of commit _[cacaef0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cacaef0133a8a8ebe60e82aa56d8cd034095c634)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-9b252917)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | | [Details](#user-content-0d1a35ef-9b252917)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | | [Details](#user-content-2a246ca2-9b252917)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | | [Details](#user-content-496333a2-9b252917)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | | [Details](#user-content-3e95c694-9b252917)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | | [Details](#user-content-77423598-9b252917)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | | [Details](#user-content-ef3e614b-9b252917)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | | [Details](#user-content-4407d1a0-9b252917)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | | [Details](#user-content-183283a3-9b252917)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | | [Details](#user-content-1d895120-9b252917)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | | [Details](#user-content-36e0608e-9b252917)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | | [Details](#user-content-dddbfd97-9b252917)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | | [Details](#user-content-e2430f62-9b252917)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | | [Details](#user-content-9290d014-9b252917)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | | [Details](#user-content-ab8d5133-9b252917)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | | [Details](#user-content-44ba799e-9b252917)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | | [Details](#user-content-9cfcf849-9b252917)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | | [Details](#user-content-9d118271-9b252917)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | | [Details](#user-content-40a3f613-9b252917)
[api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md) | :warning:Warning | | [Details](#user-content-488039d2-9b252917)
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :warning:Warning | | [Details](#user-content-92cf7d9d-9b252917)
[api-reference/beta/api/virtualendpoint-update-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-update-onpremisesconnections.md) | :warning:Warning | | [Details](#user-content-ec6c617a-9b252917)
[api-reference/beta/api/virtualendpoint-update-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-update-provisioningpolicies.md) | :warning:Warning | | [Details](#user-content-9deaa9f3-9b252917)
[api-reference/beta/api/virtualendpoint-update-selfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-update-selfservicesettings.md) | :warning:Warning | | [Details](#user-content-4aefeda0-9b252917)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/resources/cloudpc.md) | :warning:Warning | | [Details](#user-content-5b691f94-9b252917)
[api-reference/beta/resources/cloudpcStatusDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/resources/cloudpcStatusDetails.md) | :warning:Warning | | [Details](#user-content-62a13824-9b252917)
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/resources/cloudpcdeviceimage.md) | :warning:Warning | | [Details](#user-content-e7e31ea0-9b252917)
[api-reference/beta/resources/cloudpcdeviceimagestatus.md](ht [...]

2020-11-04 14:07 UTC, opbld32 commented
Docs Build status updates of commit _[2e42c30](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e42c30534e9efe551a6e5ca99b4daafc553c351)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-16e2acf4)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-16e2acf4)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-16e2acf4)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-16e2acf4)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-16e2acf4)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-16e2acf4)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-16e2acf4)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-16e2acf4)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-16e2acf4)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-16e2acf4)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-16e2acf4)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-16e2acf4)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-16e2acf4)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-16e2acf4)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-16e2acf4)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-16e2acf4)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-16e2acf4)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) |  [...]

2020-11-04 14:15 UTC, opbld34 commented
Docs Build status updates of commit _[b6abac1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b6abac1cc8f67da237063bf2ae3205dbf433f084)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-3c52976b)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-3c52976b)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-3c52976b)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-3c52976b)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-3c52976b)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-3c52976b)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-3c52976b)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-3c52976b)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-3c52976b)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-3c52976b)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-3c52976b)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-3c52976b)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-3c52976b)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-3c52976b)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-3c52976b)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-3c52976b)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-3c52976b)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) |  [...]

2020-11-04 14:24 UTC, opbld34 commented
Docs Build status updates of commit _[50330c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50330c6a83173ae95d82531a5f6450b815acb695)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-cfc2646c)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-cfc2646c)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-cfc2646c)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-cfc2646c)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-cfc2646c)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-cfc2646c)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-cfc2646c)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-cfc2646c)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-cfc2646c)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-cfc2646c)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-cfc2646c)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-cfc2646c)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-cfc2646c)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-cfc2646c)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-cfc2646c)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-cfc2646c)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-cfc2646c)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) |  [...]

2020-11-04 14:31 UTC, opbld33 commented
Docs Build status updates of commit _[6770056](https://github.com/microsoftgraph/microsoft-graph-docs/commits/677005678353b7fd589250aa11fc908a8b807276)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-070c8a6a)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-070c8a6a)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-070c8a6a)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-070c8a6a)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-070c8a6a)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-070c8a6a)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-070c8a6a)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-070c8a6a)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-070c8a6a)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-070c8a6a)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-070c8a6a)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-070c8a6a)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-070c8a6a)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-070c8a6a)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-070c8a6a)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-070c8a6a)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-070c8a6a)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) |  [...]

2020-11-04 15:10 UTC, opbld33 commented
Docs Build status updates of commit _[6f35405](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f3540503e5332a454178ad49da5f61fbb08b1d2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-2b0a3233)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-2b0a3233)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-2b0a3233)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-2b0a3233)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-2b0a3233)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-2b0a3233)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-2b0a3233)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-2b0a3233)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-2b0a3233)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-2b0a3233)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-2b0a3233)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-2b0a3233)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-2b0a3233)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-2b0a3233)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-2b0a3233)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-2b0a3233)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-2b0a3233)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) |  [...]

2020-11-05 10:58 UTC, timefrozen19 commented on api-reference/beta/resources/virtualendpoint.md
> +|[Reprovision CloudPC](../api/cloudpc-reprovision.md)|None|Reprovision a specific Cloud PC.|
This action is bound to CloudPC, not virtualEndpoint.

2020-11-05 10:58 UTC, timefrozen19 commented on api-reference/beta/resources/virtualendpoint.md
> +|[Reprovision CloudPC](../api/cloudpc-reprovision.md)|None|Reprovision a specific Cloud PC.|
Let's remove it.

2020-11-05 11:33 UTC, opbld33 commented
Docs Build status updates of commit _[4600ac8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4600ac8e4a930dc93135c78de39b8c14c8ec6f24)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-446fc69e)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-446fc69e)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-446fc69e)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-446fc69e)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-446fc69e)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-446fc69e)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-446fc69e)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-446fc69e)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-446fc69e)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-446fc69e)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-446fc69e)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-446fc69e)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-446fc69e)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-446fc69e)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-446fc69e)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-446fc69e)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-446fc69e)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) |  [...]

2020-11-06 01:33 UTC, opbld31 commented
Docs Build status updates of commit _[4269e3b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4269e3b5ba08571eff24a70435c9a6117520865c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-006ae037)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-006ae037)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-006ae037)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-006ae037)
[api-reference/beta/api/virtualendpoint-delete-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-77423598-006ae037)
[api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ef3e614b-006ae037)
[api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-delete-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-delete-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-4407d1a0-006ae037)
[api-reference/beta/api/virtualendpoint-get-cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpc?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-183283a3-006ae037)
[api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-1d895120-006ae037)
[api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-36e0608e-006ae037)
[api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcprovisioningpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dddbfd97-006ae037)
[api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-get-cloudpcselfservicesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-get-cloudpcselfservicesettings?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-e2430f62-006ae037)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-006ae037)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-006ae037)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-006ae037)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-006ae037)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-006ae037)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) |  [...]

2020-11-06 09:10 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md
> +
Lines 43-45:
@AshleyYangSZ , @wandeg , @Lauragra , I looked more carefully what section, if any, is supposed to be at this location.
Based on its location (after "Request headers") and the boilerplate text ("do not supply a request body for this method"), this section should be a "Request body" section. So, please change line 43 to "Request body".

getSourceImages is indeed defined to be a function in the CSDL. On the other hand, if a function doesn't have any function parameters, we don't document a separate section that's titled "Function parameters". If, on the other hand, this function has parameters, then create an H2 section titled "Function parameters" and document the parameters under that section.

Please see this topic for more info: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55072/Parameters

2020-11-06 09:45 UTC, opbld32 commented
Docs Build status updates of commit _[a007fb1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a007fb10c89193a242650cc05cbf0a9fbe9a2b88)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-32be999e)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-32be999e)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-32be999e)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-32be999e)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-32be999e)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-32be999e)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-32be999e)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-32be999e)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-32be999e)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-32be999e)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-32be999e)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-32be999e)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-32be999e)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-32be999e)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-32be999e)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-32be999e)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-32be999e)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-32be999e)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-g [...]

2020-11-06 10:02 UTC, opbld30 commented
Docs Build status updates of commit _[a1f709f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a1f709fbe9d2b1c52949c93b29829c573e316543)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-90a6a32a)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-90a6a32a)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-90a6a32a)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-90a6a32a)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-90a6a32a)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-90a6a32a)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-90a6a32a)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-90a6a32a)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-90a6a32a)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-90a6a32a)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-90a6a32a)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-90a6a32a)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-90a6a32a)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-90a6a32a)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-90a6a32a)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-90a6a32a)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-90a6a32a)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-90a6a32a)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-g [...]

2020-11-06 12:35 UTC, opbld31 commented
Docs Build status updates of commit _[b24b354](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b24b354a08b94bc40f42c22e21c2fbb3186dfa19)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-e0187da8)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-e0187da8)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-e0187da8)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-e0187da8)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-e0187da8)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-e0187da8)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-e0187da8)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-e0187da8)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-e0187da8)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-e0187da8)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-e0187da8)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-e0187da8)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-e0187da8)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-e0187da8)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-e0187da8)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-e0187da8)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-e0187da8)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-e0187da8)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-g [...]

2020-11-06 12:36 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md
> +
Done.

2020-11-06 13:36 UTC, opbld32 commented
Docs Build status updates of commit _[58eb6a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58eb6a5f4d24603539d65bb3d73221659fb8bf1f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-8d03c28a)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-8d03c28a)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-8d03c28a)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-8d03c28a)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-8d03c28a)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-8d03c28a)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-8d03c28a)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-8d03c28a)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-8d03c28a)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-8d03c28a)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-8d03c28a)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-8d03c28a)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-8d03c28a)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-8d03c28a)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-8d03c28a)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-8d03c28a)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-8d03c28a)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-8d03c28a)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-g [...]

2020-11-06 14:10 UTC, opbld34 commented
Docs Build status updates of commit _[cbc4a58](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cbc4a58655f9317201ab501e03606b7a659d81b0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-99a22456)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-99a22456)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-99a22456)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-99a22456)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-99a22456)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-99a22456)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-99a22456)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-99a22456)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-99a22456)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-99a22456)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-99a22456)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-99a22456)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-99a22456)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-99a22456)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-99a22456)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-99a22456)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-99a22456)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-99a22456)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-g [...]

2020-11-06 14:20 UTC, opbld33 commented
Docs Build status updates of commit _[c9ae047](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9ae047986a2f756bf565305e6502de5182cb7fd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-386eb5bb)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-386eb5bb)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-386eb5bb)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-386eb5bb)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-386eb5bb)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-386eb5bb)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-386eb5bb)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-386eb5bb)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-386eb5bb)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-386eb5bb)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-386eb5bb)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-386eb5bb)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-386eb5bb)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-386eb5bb)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-386eb5bb)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-386eb5bb)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-386eb5bb)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-386eb5bb)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-g [...]

2020-11-06 17:53 UTC, opbld32 commented
Docs Build status updates of commit _[7c52b25](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c52b251448662323503b7caaab5c9ec6dd41ba5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-6593a9f7)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-6593a9f7)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-6593a9f7)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-6593a9f7)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-6593a9f7)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-6593a9f7)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-6593a9f7)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-6593a9f7)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-6593a9f7)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-6593a9f7)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-6593a9f7)
[api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-post-assignments.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-post-assignments?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-3e95c694-6593a9f7)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-6593a9f7)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-6593a9f7)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-6593a9f7)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-6593a9f7)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-6593a9f7)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-6593a9f7)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-g [...]

2020-11-06 18:17 UTC, opbld31 commented
Docs Build status updates of commit _[a519b01](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a519b01b7f4c8d2d80ae77edd9bbcfd649dcb865)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-5e55eea7)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-5e55eea7)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-5e55eea7)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-5e55eea7)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-5e55eea7)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-5e55eea7)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-5e55eea7)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-5e55eea7)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-5e55eea7)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dba05553-5e55eea7)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-5e55eea7)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-5e55eea7)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-5e55eea7)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-5e55eea7)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-5e55eea7)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-5e55eea7)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-5e55eea7)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-5e55eea7)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jama [...]

2020-11-09 02:41 UTC, opbld34 commented
Docs Build status updates of commit _[2fc328d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2fc328dc5906c35edb088793c990eb7c21188eb7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-97dea3ae)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-97dea3ae)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-97dea3ae)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-97dea3ae)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-97dea3ae)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-97dea3ae)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-97dea3ae)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-97dea3ae)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-97dea3ae)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dba05553-97dea3ae)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-97dea3ae)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-97dea3ae)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-97dea3ae)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-97dea3ae)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-97dea3ae)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-97dea3ae)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-97dea3ae)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-97dea3ae)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jama [...]

2020-11-09 21:30 UTC, angelgolfer-ms commented on api-reference/beta/resources/enums.md
> +
@AshleyYangSZ , thanks for snapping back to guidance and moving the enum definitions to enums.md.
AFAIK, for Microsoft Graph developer customers, what matters when they use an enum is referring to the string-type member names, the mapping of the string-type member name with the numerical value is transparent to the developer customer. From that perspective, we decided early on to remove all numerical definitions for enum members in the docs. Perhaps that matters to our internal implementation of an enum, but not to customers.

Can you please remove the "Value" columns in these few tables (lines 1430-1493)? Thanks.

2020-11-10 05:13 UTC, AshleyYangSZ commented on api-reference/beta/resources/enums.md
> +
Thanks @angelgolfer-ms I saw some enum member add value and description as well, and some of our enum values are not 1,2,3... as usual, but it's 199, 299 like 'cloudPcOnPremisesConnectionHealthCheckErrorType' and 'cloudPcOnPremisesConnectionStatus' enum. Is there any need to keep the value for these 2 enum?

2020-11-11 02:16 UTC, AshleyYangSZ commented on api-reference/beta/resources/enums.md
> +
Already removed.

2020-11-11 05:06 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-update.md
> +
For update and delete of this entity, your api.md file says "Once the on-premises connection health check is passed, it cannot be edited or deleted." 
Does that still apply? If so, you should add this info as a separate paragraph after line 15 to state this.

FYI in general, any extra conceptual type relevant info that applies to an entity, complex type, method, can go to the top of the reference topic, after the summary description (first sentence). More info about this is here, under step #2: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55084/Create-new-documentation?anchor=author-content

2020-11-11 05:10 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-delete.md
> +Delete a specific [cloudPcOnPremisesConnection](../resources/cloudpconpremisesconnection.md) object. When you delete a connection, permissions to the service are removed from the specified Azure reso
Line 14:
Please separate the second sentence (and thereafter) from the first sentence in a new paragraph.

Also add another paragraph if the following is applicable:
For update and delete of this entity, your api.md file says "Once the on-premises connection health check is passed, it cannot be edited or deleted."

To be more helpful, I would suggest saying:
"Once the on-premises connection passes health check, which is indicated by the **healthCheckStatus** property, you cannot delete it".

2020-11-11 07:19 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +Represents a defined collection of Azure resource information that can be used to establish on-premises network connectivity for Cloud PCs.
Line 14 and GLOBAL: 
Please remember to capitalize a name only if it is an officially branded name. 
In line 14, please use lower case "cloud PC". "PC" is a generally recognized as an acronym for personal computer, so that's fine. More info about capitalization here:
https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25357

"GLOBAL" means please apply the guideline whenever you're doing Microsoft Graph docs or blog posts, etc.

2020-11-11 07:27 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-delete.md
> +Delete a specific [cloudPcOnPremisesConnection](../resources/cloudpconpremisesconnection.md) object. When you delete a connection, permissions to the service are removed from the specified Azure reso
You can move the last sentence and rewrite it as the next paragraph:
"You cannot delete a connection when it's in use, as indicated by the **inUse** property."

2020-11-11 07:36 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-delete.md
> +# Delete onPremisesConnections
Line 10 + GLOBAL:
Unlike the TOC title, the topic title of an API topic should reflect the actual name of the API/resource where possible (i.e., actual name is not exceptionally long that makes parsing the title as a glance impossible).
Guideline: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55080/ToC-and-topic-title

Using this topic as an example, the topic title should be "Delete cloudPcOnPremisesConnection".

Reminder: Please do the similar to other topics in this PR. I would not necessarily be commenting on the topic titles anymore.

2020-11-11 07:38 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +# Get onPremisesConnections
Line 10:
"Get cloudPcOnPremisesConnection"

2020-11-11 07:39 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-update.md
> +# Update onPremisesConnections
Line 10:
"Update cloudPcOnPremisesConnection"

2020-11-11 07:54 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Line 40:
Your api.md file says this operation supports $select and $filter. Does it support other OData system query options as well? If it doesn't, you should replace the first sentence to say specifically the GET operation (this topic, single instance) supports $select.

2020-11-11 07:55 UTC, angelgolfer-ms commented on api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Line 39:
Your api.md file says this resource supports $select and $filter. Does it support other OData system query options as well? If it doesn't, you should replace the first sentence to say specifically this operation supports $filter and $select.

2020-11-11 08:02 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +|healthCheckStatusDetails|[cloudPcOnPremisesConnectionStatusDetails](../resources/cloudpconpremisesconnectionstatusdetails.md)|The details of the connection's health checks and the corresponding resu
Line 43:
Your api.md file says this property "healthCheckStatusDetails is only returned by Select query".
If that's true, please add a sentence to the description, before "Read-only.":
"Returned only on $select."

I think that should be sufficient, since this is the only property returned on $select, and you already include that property in the JSON below, as a value for optionalProperties. 

More info here FYI in general, if you have more such properties like properties for the group entity: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55056/Default-properties

2020-11-11 08:08 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +author: "jiajyang"
Line 4:
BTW, I just noticed, is this name "jiajyang" the same person as "AshleyYangSZ"? Even if it's the same person, then are both names configured to associate with Microsoft (as described here: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55085/Get-started-with-GitHub?anchor=get-started-steps)?

2020-11-11 08:17 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +GET /deviceManagement/virtualEndpoint/onPremisesConnections/{id}?$select=id,displayName,subscriptionId,subscriptionName,adDomainName,adDomainUsername,organizationalUnit,virtualNetworkId,subnetId,heal
Line 35:
2 questions for @AshleyYangSZ , 
(a) Did the stub topic generator generate this syntax line, or did you manually add this line?
(b) Is there a specific reason for this line, to show that the GET operation supports $select for all its properties? 
(c) Among all the properties, it's only healthCheckStatusDetails that requires $select on a GET operation, right?

If (b) AND (c) are true:

- It's not typical that we add a separate syntax line and include all the properties for the $select query parameter. Please delete that line 35.
- Instead, if you update the "Optional query parameters" section per my comment below, that would be consistent with how the Graph APIs generally document the similar kind of support.

2020-11-11 08:21 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +
Since there are two examples in this section, before each example, please add a level 3 heading like "Example 1", bump down the next levels like make the next "Request" a level 4 heading and not a level 3. and the same with the next "Response" section.
You can see how examples in an API topic are organized with their section headings: https://docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&tabs=http#examples

2020-11-11 08:26 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +### Request
For this second example, would you want to show a $select with only the healthCheckStatusDetails property?

In either case, please follow the example in my last comment, and make it clear in the example title what each of the 2 examples in this topic shows.

BTW, you can also add a link from the description of the healthCheckStatusDetails property in the parent resource topic, cloudpconpremisesconnection.md, to point to this example.

2020-11-11 08:38 UTC, angelgolfer-ms commented on api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
> +|id|String|Unique identifier for the on-premises connection. Read-only.|
Line 52:
Please delete this line. id is read-only, you don't get to specify it in the request body for "create", right?

2020-11-11 08:39 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-update.md
> +|id|String|Unique identifier for the on-premises connection. Read-only.|
Line 52:
Please delete this line. id is read-only, you can't modify it in an "update" operation, right?

2020-11-11 08:40 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-update.md
> +PATCH https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/onPremisesConnections
Line 77:
Did you leave out an id value at the end of the example request?

2020-11-11 08:49 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md
> +# CloudPcOnPremisesConnection-RunHealthChecks
Line 10:
The topic title should be "cloudPcOnPremisesConnection: runHealthChecks"
Can you confirm if the topic was generated with the above title, or with the title shown in line 10?

2020-11-11 08:50 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md
> +Run health checks on the [cloudPcOnPremisesConnection](../resources/cloudpconpremisesconnection.md) object.
Line 14:
Can you elaborate on what actually gets done when calling runHealthChecks?
For example, does it do anything to the healthCheckStatus and healthCheckStatusDetails properties?

2020-11-11 08:57 UTC, angelgolfer-ms requested changes
@AshleyYangSZ , I only reviewed the topics for cloudPcOnPremisesConnection resource, its CRUD operations, and the runHealthCheck action.
Please take a look at my comments, let me know if you have questions (or reply to my questions), and apply the same recommendations and guidelines to the comment topics and other topics in this PR.

2020-11-11 12:42 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-update.md
> +
Yes you're right, already updated.

2020-11-11 12:42 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-delete.md
> +Delete a specific [cloudPcOnPremisesConnection](../resources/cloudpconpremisesconnection.md) object. When you delete a connection, permissions to the service are removed from the specified Azure reso
Good suggestion, added.

2020-11-11 12:44 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-delete.md
> +# Delete onPremisesConnections
I already changed. But a little question, this title is generated by the tool, is this a tool's bug?

2020-11-11 12:44 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +# Get onPremisesConnections
Done.

2020-11-11 12:45 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Specified with new change.

2020-11-11 12:45 UTC, AshleyYangSZ commented on api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Same as above, updated with new change.

2020-11-11 12:45 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +|healthCheckStatusDetails|[cloudPcOnPremisesConnectionStatusDetails](../resources/cloudpconpremisesconnectionstatusdetails.md)|The details of the connection's health checks and the corresponding resu
Added as your suggested.

2020-11-11 12:49 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +author: "jiajyang"
AshleyYangSZ is a newly created Github account, and I already associated it with my Microsoft account. 'jiajyang' is my Microsoft alias.  
A question: what should we put here as author? My Microsoft alias or our group alias?

2020-11-11 12:51 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +GET /deviceManagement/virtualEndpoint/onPremisesConnections/{id}?$select=id,displayName,subscriptionId,subscriptionName,adDomainName,adDomainUsername,organizationalUnit,virtualNetworkId,subnetId,heal
Yes,  you're right. I manually added it. We add another syntax line hope to tell customer that they can use $selected to get more properties like healthCheckStatusDetails. Already removed.

2020-11-11 12:51 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +
Added.

2020-11-11 12:51 UTC, AshleyYangSZ commented on api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
> +|id|String|Unique identifier for the on-premises connection. Read-only.|
Good catch. Removed.

2020-11-11 12:52 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-update.md
> +|id|String|Unique identifier for the on-premises connection. Read-only.|
Done.

2020-11-11 12:52 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-update.md
> +PATCH https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/onPremisesConnections
Yes, I really missed. Thanks.

2020-11-11 12:53 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md
> +Run health checks on the [cloudPcOnPremisesConnection](../resources/cloudpconpremisesconnection.md) object.
I added some description.

2020-11-11 12:54 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md
> +# CloudPcOnPremisesConnection-RunHealthChecks
I checked the tool generated title is "cloudPcOnPremisesConnection: runHealthChecks". Already changed.

2020-11-11 12:55 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +### Request
Added. Hope you can check it again.

2020-11-11 12:55 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-update.md
> +# Update onPremisesConnections
Done.

2020-11-11 12:58 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +Represents a defined collection of Azure resource information that can be used to establish on-premises network connectivity for Cloud PCs.
Since we used 'Cloud PC; for about half year in our daily developing life, I already regarded it as a brand name although it is not then I didn't catch this point. Already changed.

2020-11-12 02:50 UTC, opbld30 commented
Docs Build status updates of commit _[2f77e64](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2f77e6494b6fcce98a9d616aed1c9e55a4d39928)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-0c48eeb3)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-0c48eeb3)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-0c48eeb3)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-0c48eeb3)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-0c48eeb3)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-0c48eeb3)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-0c48eeb3)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-0c48eeb3)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-0c48eeb3)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dba05553-0c48eeb3)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-0c48eeb3)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-0c48eeb3)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-0c48eeb3)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-0c48eeb3)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-0c48eeb3)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-0c48eeb3)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-0c48eeb3)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-0c48eeb3)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jama [...]

2020-11-12 04:17 UTC, AshleyYangSZ commented
> @AshleyYangSZ , I only reviewed the topics for cloudPcOnPremisesConnection resource, its CRUD operations, and the runHealthCheck action.
> Please take a look at my comments, let me know if you have questions (or reply to my questions), and apply the same recommendations and guidelines to the comment topics and other topics in this PR.

Thanks @angelgolfer-ms, I already checked other topics and made some change to them. Could you help review others and change-log as well? I'm afraid I may miss some details.

2020-11-12 13:21 UTC, opbld30 commented
Docs Build status updates of commit _[eb0ed1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb0ed1d01ea0ef7da9c919e0c6cc08fa317d1c03)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-924b87fa)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-924b87fa)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-924b87fa)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-924b87fa)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-924b87fa)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-924b87fa)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-924b87fa)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-924b87fa)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-924b87fa)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dba05553-924b87fa)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-924b87fa)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-924b87fa)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-924b87fa)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-924b87fa)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-924b87fa)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-924b87fa)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-924b87fa)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-924b87fa)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jama [...]

2020-11-13 02:59 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +author: "jiajyang"
@AshleyYangSZ , please use your GitHub name.
In general, because the Github repo is public, we try not to expose our coworkers' info (e.g., name and corporate email alias) and instead, address them by their GitHub names.
Also, in general, we encourage a team to use the same GitHub name for all their conceptual and reference topics in the docs. The "author" field is more like a contact person for the team; the field is not necessarily the person who initially created a topic. That person would receive email notifications when customers open GitHub issues or create PRs that require review. Preferably that person is relatively stable on the team and does not get reassigned every half a year to another project. Often times when people move on to another project, nobody follows up with reassigning the "author" field, and quickly we lose that connection with customers.

2020-11-13 03:06 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-delete.md
> +# Delete onPremisesConnections
Yes, that would be a bug in the generator, especially if the original filename generated was cloudPcOnPremisesConnection-delete.md and the topic title was "Delete onPremisesConnections".

Do you recall if the originally generated topic had such filename and topic title?

2020-11-14 14:37 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-delete.md
> +# Delete onPremisesConnections
Yes, the tool generated two set of CRUD api you can see [here](https://github.com/microsoftgraph/microsoft-graph-docs/tree/2020-11-03-jiajyang-update/doc-stubs/api), I selected file name start up with "virtualEnpoint" set like virtualendpoint-delete-onpremisesconnections.md. So the topic name is "Delete onpremisesconnections.md"

2020-11-16 11:42 UTC, opbld33 commented
Docs Build status updates of commit _[c111687](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1116875538201eaa1882ca890d58080c37eae3e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-e29e9413)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-e29e9413)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-e29e9413)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-e29e9413)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-e29e9413)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-e29e9413)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-e29e9413)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-e29e9413)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-e29e9413)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dba05553-e29e9413)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-e29e9413)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-e29e9413)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-e29e9413)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-e29e9413)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-e29e9413)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-e29e9413)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-e29e9413)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-e29e9413)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jama [...]

2020-11-17 07:17 UTC, AshleyYangSZ commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +author: "jiajyang"
Already updated and replaced it with “AshleyYangSZ“。

2020-11-17 09:09 UTC, angelgolfer-ms commented on api-reference/beta/resources/virtualendpoint.md
> +|[Get effective permission](../api/virtualendpoint-geteffectivepermissions.md)|String collection|View the effective permissions of the currently authenticated user.|
After line 20:
For consistency, the Methods table of an entity should include the "list" and "create" operations associated with each of the nav properties of that entity. 
You can see profile.md as an example - that entity has a large number of nav properties, each of which supports a "list" and "create" topic. So the profile entity Methods table includes the "list" and "create" topics for each of the nav properties.

2020-11-17 09:10 UTC, angelgolfer-ms commented on api-reference/beta/resources/virtualendpoint.md
> +|[Get effective permission](../api/virtualendpoint-geteffectivepermissions.md)|String collection|View the effective permissions of the currently authenticated user.|
When you add the table rows, please make sure to use the topic title and description of the corresponding topic.

2020-11-17 09:11 UTC, angelgolfer-ms commented on api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md
> +# List cloudPcOnPremisesConnections
Line 10 + GLOBAL:
The "list" operation topic title should follow this pattern: "List {nav property name}". Please see this topic, the "API" row in the table: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55080/ToC-and-topic-title

So for this topic, the topic title should be "List onPremisesConnections".

2020-11-17 09:14 UTC, angelgolfer-ms commented on api-reference/beta/api/virtualendpoint-list-deviceimages.md
> +# List cloudPcDeviceImages
Line 10:
The topic title should follow the pattern "List {nav property name}", as described in this CDK topic: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55080/ToC-and-topic-title
We can't just pluralize the resource name "cloudPcDeviceImage". That term is not a natural language term.

In this case, the topic title should be "List deviceImages".

2020-11-17 09:16 UTC, angelgolfer-ms commented on api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md
> +# List cloudPcProvisioningPolicies
Line 10:
The topic title should be "List provisioningPolicies", following the pattern "List {nav property name}" as described in https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55080/ToC-and-topic-title

2020-11-17 09:17 UTC, angelgolfer-ms commented on api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
> +# Create cloudPcOnPremisesConnections
Line 10:
The topic title should be "Create cloudPcOnPremisesConnection", without the 's' at the end.
The resource name is cloudPcOnPremisesConnection.

2020-11-17 09:19 UTC, angelgolfer-ms commented on api-reference/beta/api/virtualendpoint-post-deviceimages.md
> +# Create cloudPcDeviceImages
Line 10:
The topic title should be "Create cloudPcDeviceImage" without the 's' in the end. The pattern is "Create {resource name}", and in this case the resource name is cloudPcDeviceImage.
See this CDK topic: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55080/ToC-and-topic-title

2020-11-17 09:21 UTC, angelgolfer-ms commented on api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md
> +# Create cloudPcProvisioningPolicies
Line 10:
The topic title should be "Create cloudPcProvisioningPolicy", singular, following the name of the resource.
The pattern is "Create {resource name}", as described in this CDK topic: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55080/ToC-and-topic-title

2020-11-17 09:41 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-delete.md
> +Once the on-premises connection passes health check, which is indicated by the `healthCheckStatus` property, you cannot delete it.
Lines 18 and 19:
Let's make the two sentences parallel in structure. Can you please change the first sentence to:
"You cannot delete an on-premises connection once it passes health check, which is indicated by the `healthCheckStatus` property."
Add a newline after this, before starting the next sentence, so that they don't appear to be in the same paragraph.
Then add the word "either" to the next sentence, as in:
"You cannot delete a connection when it's in use either, as indicated by the `inUse` property."

2020-11-17 09:44 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md
> +This will trigger a new health check for this [cloudPcOnPremisesConnection](../resources/cloudpconpremisesconnection.md) object and change the healthCheckStatus and [healthCheckStatusDetails](../reso
Line 15:
Please first add a newline to make this start in a new paragraph. Right now the sentences in line 14 and in line 15 are displayed in the same paragraph.
The first sentence "Run health checks on the [cloudPcOnPremisesConnection](../resources/cloudpconpremisesconnection.md) object." is a summary description, which should always be in its own paragraph.

2020-11-17 09:47 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md
> +This will trigger a new health check for this [cloudPcOnPremisesConnection](../resources/cloudpconpremisesconnection.md) object and change the healthCheckStatus and [healthCheckStatusDetails](../reso
Then for line 15, please rephrase slightly:
"This triggers a new health check for this cloudPcOnPremisesConnection object, and updates the healthCheckStatus and healthCheckStatusDetails properties."

2020-11-17 09:53 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +### Example 1
Whenever there's more than one example, it's helpful to provide some description to each example. If the description is simple, you can add it as part of the example title (line 57 in this case). Otherwise, summarize it in the example title, and then add another paragraph after line 57, in this case.
Line 57:
You can say "Example 1: Get the default properties of an on-premises connection"

2020-11-17 09:55 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpconpremisesconnection-get.md
> +
Line 104:
Following the example title for example 1, in this example, please add to line 104:
"Example 2: Get the selected properties of an on-premises connection, including healthCheckStatusDetails

2020-11-17 09:59 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpcdeviceimage-get.md
> +# Get cloudPcDeviceImages
Line 10:
Please change the title to "Get cloudPcDeviceImage". The topic title pattern is "Get {resource name}".

2020-11-17 10:03 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md
> +Get [cloudPcSourceDeviceImage](../resources/cloudpcsourcedeviceimage.md) objects. View a list of all managed image resources from you Azure subscriptions. These source images can be uploaded and used
Line 14:
Please change the second sentence:
"View a list of all the managed image resources from your Azure Active Directory subscriptions."

2020-11-17 10:08 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpc-get.md
> +# Get cloudPCs
Line 10:
This topic gets a single instance, so the topic title should be "Get cloudPC". That follows the topic title pattern "Get {resource name}". See https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55080/ToC-and-topic-title.

2020-11-17 10:10 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpc.md
> +Cloud managed virtual desktops.
Line 14:
Can you make the description to apply to one virtual desktop, like:
"Represents a cloud-managed virtual desktop."

2020-11-17 10:18 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpcprovisioningpolicy-get.md
> +### Example 1
Line 57: 
Please provide a short summary to add to the example title, since there are 2 examples in this topic.
For example:
"Example 1: Get the specified provisioning policy"

2020-11-17 10:21 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpcprovisioningpolicy-get.md
> +### Example 2
Line 99:
"Example 2:  Get the properties of the specified provisioning policy and expand on the assignments"

2020-11-17 10:27 UTC, angelgolfer-ms commented on api-reference/beta/api/cloudpcprovisioningpolicy-assign.md
> +|target|[cloudPcManagementAssignmentTarget](../resources/cloudpcmanagementassignmenttarget.md)|The assignment target for the provisioning policy. Currently, the only target supported for this policy
Line 53:
Please simplify the second sentence in the description:
"Currently, the only target supported is a user group."

2020-11-17 10:34 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Cloud PC provisioning policy assignment
Lines 9229-9237:
I'd suggest removing these lines from the TOC. 
Let customers get to these topics from inter-topic linking.

2020-11-17 10:39 UTC, angelgolfer-ms commented on api-reference/beta/resources/virtualendpoint.md
> +The virtualEndpoint resource represents a container for cloud PC management functionality.
@AshleyYangSZ , where did we put the couple of sentences that your PM provided for the little bit of conceptual information for this feature:
"Cloud PC APIs can be used to provision and manage virtual desktops for all employees. Use these in conjunction with Intune Graph APIs to manage physical and virtual endpoints."

2020-11-17 10:56 UTC, angelgolfer-ms commented on api-reference/beta/resources/virtualendpoint.md
> +The virtualEndpoint resource represents a container for cloud PC management functionality.
After line 14:
Perhaps we can add a new paragraph (remember, add a newline, then add the first sentence of the next paragraph) here. Change the sentences slightly, as follows. Note the link to the Intune API.
```
The virtualEndpoint resource represents a container for APIs to manage cloud PC.

The cloud PC API can be used to provision and manage virtual desktops for employees in an organization. Use the API in conjunction with the [Intune API](intune-graph-overview.md) to manage physical and virtual endpoints.
```

2020-11-17 10:59 UTC, angelgolfer-ms commented on api-reference/beta/resources/virtualendpoint.md
> +The virtualEndpoint resource represents a container for cloud PC management functionality.
Then we can make this virtualendpoint.md topic as the first topic under "Cloud PC (preview)", and as a peer of the other 4 node topics you currently have - "Cloud PC", "Cloud PC device image", "Cloud PC on-premises connection", "Cloud PC provisioning policy".
Let's try the TOC title should be "Virtual endpoint", and see what the experience is like.

2020-11-17 11:02 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
>      - name: Education
Lines 9238-9239:
Move these lines up to go after line 9176. The "Virtual endpoint" node would become a peer of the other 4 nodes under line 9175 "Cloud PC (preview)".

2020-11-17 11:03 UTC, angelgolfer-ms requested changes
Hi @AshleyYangSZ , a few more comments, and some suggestions for the TOC. Please take a look.

2020-11-18 11:41 UTC, AshleyYangSZ commented on api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
> +# Create cloudPcOnPremisesConnections
This is generated by the tool. Is this a known issue?

2020-11-18 11:43 UTC, AshleyYangSZ commented on api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
> +# Create cloudPcOnPremisesConnections
And changed the title, do we need to change the file name to 'virtualendpoint-post-onpremisesconnection.md' without the 's'?

2020-11-18 12:00 UTC, AshleyYangSZ commented on api-reference/beta/toc.yml
> +        - name: Cloud PC provisioning policy assignment
How about 'Reprovision' (line 9184), 'Get source images' (line 9197), 'Run health checks'  (line 9212)? Do we need to remove them as well? @angelgolfer-ms

2020-11-18 12:13 UTC, opbld32 commented
Docs Build status updates of commit _[8963294](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8963294cbb9d0b53e03649066779d48cbd46bf69)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bd0c386b)

<a id="bd0c386b"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011181212414855-10412%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6mQCm1zP99BYzP2kHBzVsNIyyYDKI5nfvssGpTP644I%3D&st=2020-11-18T12%3A07%3A59Z&se=2020-12-19T12%3A12%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 12:21 UTC, opbld34 commented
Docs Build status updates of commit _[4c86267](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c86267954445e70382781b3637d68167e559d6c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-e7fcf41b)
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | | [Details](#user-content-05abcc44-e7fcf41b)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | | [Details](#user-content-0d1a35ef-e7fcf41b)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | | [Details](#user-content-dbd6a2cf-e7fcf41b)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | | [Details](#user-content-607d042d-e7fcf41b)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | | [Details](#user-content-2a246ca2-e7fcf41b)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | | [Details](#user-content-b58c4631-e7fcf41b)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | | [Details](#user-content-bc9bce1c-e7fcf41b)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | | [Details](#user-content-496333a2-e7fcf41b)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | | [Details](#user-content-b29ee0f7-e7fcf41b)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | | [Details](#user-content-dba05553-e7fcf41b)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | | [Details](#user-content-bc8757d1-e7fcf41b)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | | [Details](#user-content-117b7a2d-e7fcf41b)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | | [Details](#user-content-5e600f2f-e7fcf41b)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | | [Details](#user-content-9290d014-e7fcf41b)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | | [Details](#user-content-ab8d5133-e7fcf41b)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | | [Details](#user-content-44ba799e-e7fcf41b)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | | [Details](#user-content-9cfcf849-e7fcf41b)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | | [Details](#user-content-9d118271-e7fcf41b)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | | [Details](#user-content-40a3f613-e7fcf41b)
[api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md) | :warning:Warning | | [Details](#user-content-488039d2-e7fcf41b)
[api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-post-provisioningpolicies.md) | :warning:Warning | | [Details](#user-content-92cf7d9d-e7fcf41b)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/resources/cloudpc.md) | :warning:Warning | | [Details](#user-content-5b691f94-e7fcf41b)
[api-reference/beta/resources/cloudpcStatusDetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/resources/cloudpcStatusDetails.md) | :warning:Warning | | [Details](#user-content-62a13824-e7fcf41b)
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/resources/cloudpcdeviceimage.md) | :warning:Warning | | [Details](#user-content-e7e31ea0-e7fcf41b)
[api-reference/beta/resources/cloudpcmanagementassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/resources/cloudpcmanagementassignmenttarget.md) | :warning:Warning | | [Details](#user-content-1d835b6d-e7fcf41b)
[api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/resources/cloudpcmanagementgroupassignmenttarget.md) | :warning:Warning | | [Details](#user-content-7d26a4e1-e7fcf41b)
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/resources/cloudpconpremisesconnection.md) | :warning:Warning | | [Details](#user-content-d71ffbf9-e7fcf41b)
[api-reference/beta/resources/cloudpconpremisesco [...]

2020-11-18 12:32 UTC, opbld33 commented
Docs Build status updates of commit _[0763b18](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0763b18662460610daec27675edbb38662149011)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-f8ed5960)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-f8ed5960)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-f8ed5960)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-f8ed5960)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-f8ed5960)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-f8ed5960)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-f8ed5960)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-f8ed5960)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-f8ed5960)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dba05553-f8ed5960)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-f8ed5960)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-f8ed5960)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-f8ed5960)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-f8ed5960)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-f8ed5960)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-f8ed5960)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-f8ed5960)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-f8ed5960)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jama [...]

2020-11-20 05:07 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +|[Get cloudPcSourceDeviceImage](../api/cloudpcdeviceimage-getsourceimages.md)|[cloudPcSourceDeviceImage](../resources/cloudpcsourcedeviceimage.md) collection|Get [cloudPcSourceDeviceImage](../resourc
Line 24:
The first column (Method column) should say simply "getSourceImages", which is the name of the function.

2020-11-20 05:08 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Cloud PC provisioning policy assignment
The 3 methods are where they should be in the TOC.
BTW I just noticed getSourceImages is not defined in the CSDL that you had pointed me to (https://microsoftgraph.visualstudio.com/onboarding/_git/AGS-OnboardingAutomationPipeline?path=%2FMicrosoft.CloudManagedDesktop.csdl&version=GBschemas%2Fprd%2Fstagingbeta).
Was that function added later?

2020-11-20 05:13 UTC, angelgolfer-ms commented on api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
> +# Create cloudPcOnPremisesConnections
The filename as is is correct, using the nav property name at the end (onpremisesconnections).
The filename pattern is {parent resource name}-post-{nav property name}.md.

<EntityType Name="virtualEndpoint" ags:IsMaster="true" >
    <Key>
        <PropertyRef Name="id"/>
    </Key>
    <Property Name="id" Type="Edm.String" Nullable="false"/>
    <NavigationProperty Name="deviceImages" Type="Collection(microsoft.graph.cloudPcDeviceImage)" ContainsTarget="true" />
    <NavigationProperty Name="onPremisesConnections" Type="Collection(microsoft.graph.cloudPcOnPremisesConnection)" ContainsTarget="true" />
    <NavigationProperty Name="cloudPCs" Type="Collection(microsoft.graph.cloudPC)" ContainsTarget="true" />
    <NavigationProperty Name="provisioningPolicies" Type="Collection(microsoft.graph.cloudPcProvisioningPolicy)" ContainsTarget="true" />
    <NavigationProperty Name="selfServiceSettings" Type="microsoft.graph.cloupdPcSelfServiceSettings" ContainsTarget="true" />
</EntityType>

2020-11-20 05:15 UTC, angelgolfer-ms commented on api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
> +# Create cloudPcOnPremisesConnections
I think James has a tracking bug to fix the filename of the "create" operation topics, to use the resource name and not the nav property name.

2020-11-20 05:43 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Shared resources
After line 9283:
I think you left out the "list" and "get" operations applicable to cloudpcprovisioningpolicyassignment resource, as documented in your api.md file. I sent you a more detailed message on Teams about this.

2020-11-20 06:23 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +            href: api/cloudpcprovisioningpolicy-delete.md
After line 9280:
Please add the assign method to the TOC, under the cloudpcprovisionpolicy parent node.

2020-11-20 06:33 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Cloud PC provisioning policy assignment
For the lines to delete:  I mean deleting the "Shared resources" and "Cloud PC management assignment target" and "Cloud PC management group assignment target". These are just complex types. We typically don't include them in the TOC. Let customers get to them from linking from method and resource topics that use these types.

2020-11-20 06:38 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpcprovisioningpolicyassignment.md
> +|[Assign cloudPcProvisioningPolicy](../api/cloudpcprovisioningpolicy-assign.md)|[cloudPcProvisioningPolicyAssignment](../resources/cloudpcprovisioningpolicyassignment.md)|Assign [cloudPcProvisioningP
Line 20:
The Method column should just say "Assign".

2020-11-20 06:49 UTC, angelgolfer-ms commented on api-reference/beta/resources/virtualendpoint.md
> +|[Get effective permission](../api/virtualendpoint-geteffectivepermissions.md)|String collection|View the effective permissions of the currently authenticated user.|
@AshleyYangSZ , there must be a misunderstanding.
The Methods table has too many table rows now.
That table should include only lines 22, 23, 26, 28, 31, 33, 37, and 39.
That is, other than its own function getEffectivePermissions, for the methods related to each of the 4 nav properties, only include the "list" and "create" operations, if they are supported. Do not include the "get", "update", "delete" operations that apply to the type of any nav property.

2020-11-20 06:53 UTC, angelgolfer-ms commented on changelog/Microsoft.CloudManagedDesktop.json
> +        "WorkloadArea": "Cloud managed Desktop",
Line 134: 
I think this should say "Cloud PC".
Where does this phrase "Cloud managed Desktop" come from? Do you use it anywhere?

2020-11-20 06:53 UTC, angelgolfer-ms commented on concepts/changelog.md
> +### Devices and apps | Cloud managed Desktop
Line 16:
This should be "Devices and apps | Cloud PC".

2020-11-20 07:02 UTC, angelgolfer-ms commented on api-reference/beta/resources/virtualendpoint.md
> +The cloud PC API can be used to provision and manage virtual desktops for employees in an organization. Use the API in conjunction with the [Intune API](../resources/intune-graph-overview.md) to mana
Line 16:
Slight rephrase to use the imperative:
"Use the cloud PC API to provision and manage...in an organization. Use it in conjunction with the Intune API..."

2020-11-20 07:12 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Cloud PC
After line 9230:
Since virtualEndpoint has its own function getEffectivePermissions, please add  that as a child topic of the "Virtual endpoint" node in line 9229.
The TOC title should be "Get effective permissions".

2020-11-20 07:13 UTC, angelgolfer-ms commented on api-reference/beta/resources/virtualendpoint.md
> +|[Get effective permission](../api/virtualendpoint-geteffectivepermissions.md)|String collection|View the effective permissions of the currently authenticated user.|
Line 22:
Please change the Method column to read "Get effective permissions", plural "permissions".

2020-11-20 09:24 UTC, angelgolfer-ms commented on api-reference/beta/api/virtualendpoint-geteffectivepermissions.md
> +## Function parameters
Line 43:
This section header should say "Request body".

2020-11-20 14:09 UTC, AshleyYangSZ commented on api-reference/beta/toc.yml
> +        - name: Cloud PC provisioning policy assignment
> The 3 methods are where they should be in the TOC.
> BTW I just noticed getSourceImages is not defined in the CSDL that you had pointed me to (https://microsoftgraph.visualstudio.com/onboarding/_git/AGS-OnboardingAutomationPipeline?path=%2FMicrosoft.CloudManagedDesktop.csdl&version=GBschemas%2Fprd%2Fstagingbeta).
> Was that function added later?

getSourceImages is here in line: 172
https://microsoftgraph.visualstudio.com/onboarding/_git/AGS-OnboardingAutomationPipeline?path=%2FMicrosoft.CloudManagedDesktop.csdl&version=GBschemas%2Fprd%2Fstagingbeta&line=172&lineEnd=172&lineStartColumn=19&lineEndColumn=26&lineStyle=plain&_a=contents

2020-11-20 15:54 UTC, AshleyYangSZ commented on changelog/Microsoft.CloudManagedDesktop.json
> +        "WorkloadArea": "Cloud managed Desktop",
Cloud managed desktop is our workload name in AGS MGraph schema. But I think cloud PC is better as well.

2020-11-20 16:05 UTC, AshleyYangSZ commented on api-reference/beta/api/virtualendpoint-post-onpremisesconnections.md
> +# Create cloudPcOnPremisesConnections
Good to know! Thanks.

2020-11-20 16:13 UTC, opbld31 commented
Docs Build status updates of commit _[366ddae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/366ddaeba295b1ee8bbc1e626647c55fe8b3c08f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-d6be7c8f)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-d6be7c8f)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-d6be7c8f)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-d6be7c8f)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-d6be7c8f)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-d6be7c8f)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-d6be7c8f)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-d6be7c8f)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-d6be7c8f)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dba05553-d6be7c8f)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-d6be7c8f)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-d6be7c8f)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-d6be7c8f)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-d6be7c8f)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-d6be7c8f)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-d6be7c8f)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-d6be7c8f)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-d6be7c8f)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jama [...]

2020-11-21 09:35 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpcprovisioningpolicyassignment.md
> +|Method|Return type|Description|
@AshleyYangSZ , I just noticed there's only 1 assign action in your CSDL, and its binding parameter is of cloudPcProvisioningPolicy type. (The confusion I just noticed came from searching within the display view of the CSDL in Azure DevOps. It's not exactly like web page search and my cursor needs to be in the CSDL view in order to search correctly. I wasn't able to search/view the definition of a few types...)
In that case, assign should be exposed only in the topic for cloudPcProvisioningPolicy, because that's the type of its binding parameter. the assign method shouldn't be listed as a method in the topic for cloudPcProvisioningPolicyAssignment.

On the other hand, if you recall, can you confirm if that was in the generated topic as well? If so, that's a bug to track.

2020-11-21 09:38 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpcprovisioningpolicyassignment.md
> +|Method|Return type|Description|
@AshleyYangSZ , for efficiency, I am going to delete the Methods table here.
I will also remove the TOC node for cloudPcProvisioningPolicyAssignment, because it doesn't have any operations or methods.
We don't list any action (or function, for that matter) based on the type of its parameter(s).

2020-11-21 09:59 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +|[Assign provisioningPolicy](../api/cloudpcprovisioningpolicy-assign.md)|[cloudPcProvisioningPolicyAssignment](../resources/cloudpcprovisioningpolicyassignment.md)|Assign a [cloudPcProvisioningPolicy
Line 25:
@AshleyYangSZ , I just noticed another cause of confusion around the "assign" method is this table lists a return type, and the one assign method I see in the CSDL is an action that doesn't have a return type:

 <Action Name="assign" IsBound="true">
    <Parameter Name="bindingParameter" Type="microsoft.graph.cloudPcProvisioningPolicy"/>
    <Parameter Name="assignments" Type="Collection(microsoft.graph.cloudPcProvisioningPolicyAssignment)" />
  </Action>

Since it's now apparent to me that there's only 1 assign method, and it's an action (specified in the above CSDL) without a return type, I will change the Return type column to "None".

Please try to recall or verify if line 25 was generated as is with this error in the Return type column. If that was the case, we'll have to track a bug for it.

2020-11-21 10:23 UTC, opbld33 commented
Docs Build status updates of commit _[e335e95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e335e9511c45cbf44a1924c1dc5f7bd456a8b497)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-80229488)

<a id="80229488"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011211022467370-10412%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SpixWRaalqY3ak7aS4yL9Nm7wScmESzSmM8PZPF1tYk%3D&st=2020-11-21T10%3A18%3A17Z&se=2020-12-22T10%3A23%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 10:42 UTC, opbld32 commented
Docs Build status updates of commit _[8d10a1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d10a1b2bcf2763629f778cc16b7d3290c415b39)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-d397fc17)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-d397fc17)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-d397fc17)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-d397fc17)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-d397fc17)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-d397fc17)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-d397fc17)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-d397fc17)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-d397fc17)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dba05553-d397fc17)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-d397fc17)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-d397fc17)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-d397fc17)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-d397fc17)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-d397fc17)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-d397fc17)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-d397fc17)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-d397fc17)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jama [...]

2020-11-21 10:44 UTC, opbld34 commented
Docs Build status updates of commit _[99ff7ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/99ff7ac5dc00d91e06c74a5cbe880c7cc3379d76)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-fd098ea5)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-fd098ea5)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-fd098ea5)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-fd098ea5)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-fd098ea5)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-fd098ea5)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-fd098ea5)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-fd098ea5)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-fd098ea5)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dba05553-fd098ea5)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-fd098ea5)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-fd098ea5)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-fd098ea5)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-fd098ea5)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-fd098ea5)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-fd098ea5)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-fd098ea5)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-fd098ea5)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jama [...]

2020-11-21 10:54 UTC, opbld30 commented
Docs Build status updates of commit _[3712dc6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3712dc68a182d24c2136bad45b772195ba0e8962)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-f3d5fb04)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-f3d5fb04)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-f3d5fb04)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-f3d5fb04)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-f3d5fb04)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-f3d5fb04)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-f3d5fb04)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-f3d5fb04)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-f3d5fb04)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dba05553-f3d5fb04)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-f3d5fb04)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-f3d5fb04)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-f3d5fb04)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-f3d5fb04)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-f3d5fb04)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-f3d5fb04)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-f3d5fb04)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-f3d5fb04)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jama [...]

2020-11-21 10:59 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Cloud PC provisioning policy assignment
Yes, I just found out in Azure DevOps (where your CSDL is stored), the cursor has to be on the same right side pane in order to do a ctrl-F search properly. I don't quite get that, maybe it's a bug in ADO.

2020-11-21 11:04 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +        - name: Shared resources
@AshleyYangSZ , it was my oversight/confusion yesterday. As I commented somewhere else today as well, I had thought there were 2 assign methods. I verified there is only one and its binding parameter is of type cloudpcprovisioningpolicy. So the assign method should not be listed after line 9283 as suggested above. I went ahead and removed it just now, together with the "Cloud PC provisioning policy assignment" node (lines 9281-9283).

2020-11-21 11:05 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +            href: api/cloudpcprovisioningpolicy-delete.md
The above comment is correct. Thanks for implementing it.

2020-11-21 11:06 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpcprovisioningpolicyassignment.md
> +|[Assign cloudPcProvisioningPolicy](../api/cloudpcprovisioningpolicy-assign.md)|[cloudPcProvisioningPolicyAssignment](../resources/cloudpcprovisioningpolicyassignment.md)|Assign [cloudPcProvisioningP
Update: it was my confusion yesterday, the assign method should not be included in the Methods table of cloudPcProvisioningPolicyAssignment. I removed the Methods table there, since that's the only table row.

2020-11-21 11:09 UTC, angelgolfer-ms commented on changelog/Microsoft.CloudManagedDesktop.json
> +        "WorkloadArea": "Cloud managed Desktop",
Hm, did James generate this changelog json for you?
If so, perhaps we should keep the workloadarea attribute to whatever he generated it as. let me change it back.

2020-11-21 11:12 UTC, angelgolfer-ms commented on concepts/changelog.md
> +### Devices and apps | Cloud managed Desktop
This change is appropriate. Thanks for implementing it.

2020-11-21 11:20 UTC, angelgolfer-ms commented on api-reference/beta/resources/virtualendpoint.md
> +|Method|Return type|Description|
@AshleyYangSZ , I am sure I entered a comment yesterday, perhaps twice, that the Methods table should only include the "list" and "create" operations for the type of each of the nav properties, if those operations are actually supported.
Hm. I am going ahead to delete the other "get", "update", and "delete" operations that don't apply to the parent resource here, virtualendpoint.

2020-11-21 11:26 UTC, angelgolfer-ms commented on api-reference/beta/resources/virtualendpoint.md
> +|Method|Return type|Description|
Also, in the Methods table, the "list" operations do not reflect the correct topic titles. Remember - "list" operation topics use the topic title "List {nav property name}".

2020-11-21 11:29 UTC, angelgolfer-ms commented on api-reference/beta/resources/virtualendpoint.md
> +|Method|Return type|Description|
One of the "create" topic in the Methods table doesn't reflect the correct topic title either. I made the fix.

2020-11-21 11:32 UTC, opbld33 commented
Docs Build status updates of commit _[0d06ab2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d06ab2e69acce6cd8109c3427ae1faaa194df17)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-a6c94ca0)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-a6c94ca0)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-a6c94ca0)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-a6c94ca0)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-a6c94ca0)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-a6c94ca0)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-a6c94ca0)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-a6c94ca0)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-a6c94ca0)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dba05553-a6c94ca0)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-a6c94ca0)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-a6c94ca0)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-a6c94ca0)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-a6c94ca0)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-a6c94ca0)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-a6c94ca0)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-a6c94ca0)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-a6c94ca0)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jama [...]

2020-11-21 11:39 UTC, angelgolfer-ms commented on api-reference/beta/resources/virtualendpoint.md
> +|Method|Return type|Description|
One more reminder: In the Methods table of the parent resource, as well as the corresponding operations topics, it's helpful if the descriptions do not use the generic generated descriptions.
Developers don't read the docs carefully, some only would skim the resource topics, so it would be helpful for them that the parent resource topics contain helpful descriptions for the operations, methods, properties, nav properties, etc.

2020-11-21 11:45 UTC, opbld31 commented
Docs Build status updates of commit _[a94d989](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a94d989bb480c9675ed6fa3a55c30869c0c063be)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-30a043a5)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-30a043a5)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-30a043a5)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-30a043a5)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-30a043a5)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-30a043a5)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-30a043a5)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-30a043a5)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-30a043a5)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dba05553-30a043a5)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-30a043a5)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-30a043a5)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-30a043a5)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-30a043a5)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-30a043a5)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-30a043a5)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-30a043a5)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-30a043a5)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jama [...]

2020-11-21 11:57 UTC, angelgolfer-ms commented on api-reference/beta/resources/virtualendpoint.md
> +|Method|Return type|Description|
Oh, I just notice not just virtualEndpoint, but the other 4 entities that have operations also have Method tables showing the incorrect topic titles for most of the CRUD operations :-(
Ok, I am going to fix them too, so that we can publish.
Please remember for the future, in case James hasn't fixed the generator by the time you open the next PR.

2020-11-21 12:07 UTC, opbld33 commented
Docs Build status updates of commit _[193b3c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/193b3c8f67f78dc3e97fdfb8676ef7d7a0d349d8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-05abcc44-5557df51)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-0d1a35ef-5557df51)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-5557df51)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-607d042d-5557df51)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-2a246ca2-5557df51)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b58c4631-5557df51)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc9bce1c-5557df51)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-496333a2-5557df51)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-b29ee0f7-5557df51)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-dba05553-5557df51)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-bc8757d1-5557df51)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-117b7a2d-5557df51)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-5e600f2f-5557df51)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9290d014-5557df51)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-ab8d5133-5557df51)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-44ba799e-5557df51)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9cfcf849-5557df51)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jamaring-test/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10412) (graph-rest-beta) | [Details](#user-content-9d118271-5557df51)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-10-22-jama [...]

2020-11-21 12:14 UTC, merged

2020-11-21 12:16 UTC, angelgolfer-ms reviewed
Made some more fixes directly in the PR. Left a few comments for @AshleyYangSZ  to follow up. Published the PR as the product team had a commitment made before we started reviewing this debut PR.

2020-11-30 11:48 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpcprovisioningpolicy.md
> +|[Assign provisioningPolicy](../api/cloudpcprovisioningpolicy-assign.md)|[cloudPcProvisioningPolicyAssignment](../resources/cloudpcprovisioningpolicyassignment.md)|Assign a [cloudPcProvisioningPolicy
@angelgolfer-ms I confirmed it's not generated, it may be a mistake made by me.

2020-11-30 12:04 UTC, AshleyYangSZ commented on changelog/Microsoft.CloudManagedDesktop.json
> +        "WorkloadArea": "Cloud managed Desktop",
@angelgolfer-ms You're right, it's "Cloud managed Desktop" in the generated changlelog json.