Updates MGT React getting started
microsoftgraph/microsoft-graph-docs pull request #10424
Opened 2020-10-26 12:21 UTC by waldekmastykarz

Related to https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/711

Updated Microsoft Graph Toolkit React docs to remove irrelevant pieces and include a step-by-step getting started walkthrough.

@nmetulev I included the auth piece for now in the doc. If we find a way to centralize it to simplify maintenance, we can replace it with a reference.

2020-10-26 12:22 UTC, opbld32 commented
Docs Build status updates of commit _[bbc9386](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/bbc9386c2451df4a15312d9a97cc7bf095216dfe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-6f29ff40)
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-implicitgrant.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-implicitgrant.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-menu-authentication.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-menu-authentication.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-newreg-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-newreg-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-newreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-newreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-menu-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-menu-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-menu-add.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-menu-add.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-base-react-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-base-react-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-signin-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-signin-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-6f29ff40"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 116, Column 198**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-mgt-react' in 'toolkit/get-started/use-toolkit-with-react.md'.`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010261221147187-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vzEfIoj2pUNNILUqTB5qMxhvUDmQ%2F1E7IcNplOPndYk%3D&st=2020-10-26T12%3A17%3A51Z&se=2020-11-26T12%3A22%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-27 08:12 UTC, opbld33 commented
Docs Build status updates of commit _[fe69b39](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/fe69b39d351c0f57d89e7846ceaf537fca74fbca)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) | [Details](#user-content-f81256c4-180717d1)
[includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/includes/aad-app-registration-spa.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) | [Details](#user-content-4a95fac2-180717d1)
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-180717d1)
[concepts/toolkit/images/mgt-base-react-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-base-react-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-signin-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-signin-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[images/mgt-azure-add-appreg-copyappid.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/images/mgt-azure-add-appreg-copyappid.png) | :white_check_mark:Succeeded | |
[images/mgt-azure-add-appreg-implicitgrant.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/images/mgt-azure-add-appreg-implicitgrant.png) | :white_check_mark:Succeeded | |
[images/mgt-azure-add-appreg-menu-authentication.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/images/mgt-azure-add-appreg-menu-authentication.png) | :white_check_mark:Succeeded | |
[images/mgt-azure-add-appreg-newreg-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/images/mgt-azure-add-appreg-newreg-button.png) | :white_check_mark:Succeeded | |
[images/mgt-azure-add-appreg-newreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/images/mgt-azure-add-appreg-newreg.png) | :white_check_mark:Succeeded | |
[images/mgt-azure-add-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/images/mgt-azure-add-appreg.png) | :white_check_mark:Succeeded | |
[images/mgt-azure-add-menu-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/images/mgt-azure-add-menu-appreg.png) | :white_check_mark:Succeeded | |
[images/mgt-azure-menu-add.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/images/mgt-azure-menu-add.png) | :white_check_mark:Succeeded | |

<a id="f81256c4-180717d1"></a>
### [concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md)
 - **Line 66, Column 4**: **[Warning-file-not-found]** `````Invalid file link: '../images/mgt-azure-add-appreg-copyappid.png'.`````

<a id="4a95fac2-180717d1"></a>
### [includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/includes/aad-app-registration-spa.md)
 - **Line 15, Column 4**: **[Warning-link-out-of-scope]** `````File '../images/mgt-azure-menu-add.png' referenced by link '../images/mgt-azure-menu-add.png' will not be built because it is not included in build scope.`````
 - **Line 17, Column 4**: **[Warning-link-out-of-scope]** `````File '../images/mgt-azure-add-menu-appreg.png' referenced by link '../images/mgt-azure-add-menu-appreg.png' will not be built because it is not included in build scope.`````
 - **Line 19, Column 4**: **[Warning-link-out-of-scope]** `````File '../images/mgt-azure-add-appreg-newreg-button.png' referenced by link '../images/mgt-azure-add-appreg-newreg-button.png' will not be built because it is not included in build scope.`````
 - **Line 24, Column 4**: **[Warning-link-out-of-scope]** `````File '../images/mgt-azure-add-appreg-newreg.png' referenced by link '../images/mgt-azure-add-appreg-newreg.png' will not be built because it is not included in build scope.`````
 - **Line 31, Column 4**: **[Warning-link-out-of-scope]** `````File '../images/mgt-azure-add-appreg.png' referenced by link '../images/mgt-azure-add-appreg.png' will not be built because it is not included in build scope.`````
 - **Line 33, Column 4**: **[Warning-link-out-of-scope]** `````File '../images/mgt-azure-add-appreg-menu-authentication.png' referenced by link '../images/mgt-azure-add-appreg-menu-authentication.png' will not be built because it is not included in build scope.`````
 - **Line 35, Column 4**: **[Warning-link-out-of-scope]** `````File '../images/mgt-azure-add-appreg-implicitgrant.png' referenced by link '../images/mgt-azure-add-appreg-implicitgrant.png' will not be built because it is not included in build scope.`````

<a id="48910927-180717d1"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 116, Column 198**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-mgt-react' in 'toolkit/get-started/use-toolkit-with-react.md'.`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010270810418158-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PqzYMUyfu9%2FtPYOcsZe6ZLeorPD9KMXcZaq8L%2B25moU%3D&st=2020-10-27T08%3A07%3A13Z&se=2020-11-27T08%3A12%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build  [...]

2020-10-27 08:35 UTC, opbld33 commented
Docs Build status updates of commit _[f6db830](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/f6db8304b74f64b3399b80899ac092a74101b31a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) | [Details](#user-content-f81256c4-db4b5964)
[includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/includes/aad-app-registration-spa.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) | [Details](#user-content-4a95fac2-db4b5964)
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-db4b5964)
[concepts/toolkit/images/mgt-base-react-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-base-react-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-signin-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-signin-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[includes/media/aad-app-registration-spa/mgt-azure-add-appreg-copyappid.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/includes/media/aad-app-registration-spa/mgt-azure-add-appreg-copyappid.png) | :white_check_mark:Succeeded | |
[includes/media/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/includes/media/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png) | :white_check_mark:Succeeded | |
[includes/media/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/includes/media/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png) | :white_check_mark:Succeeded | |
[includes/media/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/includes/media/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png) | :white_check_mark:Succeeded | |
[includes/media/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/includes/media/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png) | :white_check_mark:Succeeded | |
[includes/media/aad-app-registration-spa/mgt-azure-add-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/includes/media/aad-app-registration-spa/mgt-azure-add-appreg.png) | :white_check_mark:Succeeded | |
[includes/media/aad-app-registration-spa/mgt-azure-add-menu-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/includes/media/aad-app-registration-spa/mgt-azure-add-menu-appreg.png) | :white_check_mark:Succeeded | |
[includes/media/aad-app-registration-spa/mgt-azure-menu-add.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/includes/media/aad-app-registration-spa/mgt-azure-menu-add.png) | :white_check_mark:Succeeded | |

<a id="f81256c4-db4b5964"></a>
### [concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md)
 - **Line 66, Column 4**: **[Warning-file-not-found]** `````Invalid file link: '../images/mgt-azure-add-appreg-copyappid.png'.`````

<a id="4a95fac2-db4b5964"></a>
### [includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/includes/aad-app-registration-spa.md)
 - **Line 15, Column 4**: **[Warning-link-out-of-scope]** `````File '../includes/media/aad-app-registration-spa/mgt-azure-menu-add.png' referenced by link './media/aad-app-registration-spa/mgt-azure-menu-add.png' will not be built because it is not included in build scope.`````
 - **Line 17, Column 4**: **[Warning-link-out-of-scope]** `````File '../includes/media/aad-app-registration-spa/mgt-azure-add-menu-appreg.png' referenced by link './media/aad-app-registration-spa/mgt-azure-add-menu-appreg.png' will not be built because it is not included in build scope.`````
 - **Line 19, Column 4**: **[Warning-link-out-of-scope]** `````File '../includes/media/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png' referenced by link './media/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png' will not be built because it is not included in build scope.`````
 - **Line 24, Column 4**: **[Warning-link-out-of-scope]** `````File '../includes/media/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png' referenced by link './media/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png' will not be built because it is not included in build scope.`````
 - **Line 31, Column 4**: **[Warning-link-out-of-scope]** `````File '../includes/media/aad-app-registration-spa/mgt-azure-add-appreg.png' referenced by link './media/aad-app-registration-spa/mgt-azure-add-appreg.png' will not be built because it is not included in build scope.`````
 - **Line 33, Column 4**: **[Warning-link-out-of-scope]** `````File '../includes/media/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png' referenced by link './media/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png' will not be built because it is not included in build scope.`````
 - **Line 35, Column 4**: **[Warning-link-out-of-scope]** `````File '../includes/media/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png' referenced by link './media/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png' will not be built because it is not included in build scope.`````

<a id="48910927-db4b5964"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 116, Column 198**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#using-mgt-react' in 'toolkit/get-started/use-toolkit-with-react.md'.`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

For more details, please refer to the [build re [...]

2020-10-27 09:30 UTC, opbld30 commented
Docs Build status updates of commit _[d0319ea](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/d0319ead5dd4fcda8e12dacc2ef53e0213396873)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-0312cabd)
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-base-react-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-base-react-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-signin-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-signin-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/media/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/media/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/media/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/media/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/media/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/media/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/media/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/media/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/media/aad-app-registration-spa/mgt-azure-add-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/media/aad-app-registration-spa/mgt-azure-add-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/media/aad-app-registration-spa/mgt-azure-add-menu-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/media/aad-app-registration-spa/mgt-azure-add-menu-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/media/aad-app-registration-spa/mgt-azure-menu-add.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/media/aad-app-registration-spa/mgt-azure-menu-add.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-0312cabd"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010270928106231-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SkAo3EHYmPbCgCX19ZAA49iU1k%2BuY5Ddrix6N4DhyjM%3D&st=2020-10-27T09%3A25%3A11Z&se=2020-11-27T09%3A30%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-27 18:24 UTC, nmetulev commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +1. In the code editor open the **src/App.tsx** file, and modify its contents to the following:
I recommend adding the Provider initialization code in the index.tsx file since it's a one time initialization. Adding it in the functional component will cause the code to run every time the component re-renders.

2020-10-27 18:24 UTC, nmetulev commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +          clientId: 'd7cb93c9-9097-4e38-8f06-7c0088ac3318'
Consider changing the clientId value to something like `[REPLACE_WITH_CLIENTID]` to make it a bit more clear that it needs to be replaced

2020-10-27 18:24 UTC, nmetulev commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +1. Go back to the browser where your React app is running. You should now see a **Sign In** button
Consider adding a note that the code above also adds the `Login` component from the toolkit, which will render a sign in button

2020-10-28 07:33 UTC, waldekmastykarz commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +          clientId: 'd7cb93c9-9097-4e38-8f06-7c0088ac3318'
I see this being used and I must admit that it often confuses me because I don't know if the whole value is a placeholder  or if the value should be put between brackets. This is why I prefer to specify the value directly to make it clear what format it's expected in.

2020-10-28 07:53 UTC, waldekmastykarz commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +1. In the code editor open the **src/App.tsx** file, and modify its contents to the following:
As soon as I move Provider initialization code to index.tsx, I'm getting the following error:

> Unhandled Rejection (Error): invalid key: msal.d7cb93c9-9097-4e38-8f06-7c0088ac3318.acquireTokenAccount|OTM2MGQ0ZDgtMzg0Yi00NGYxLWFlNmQtNTcyZjM2NjQzMzU4.ZjczMjIzODAtZjIwMy00MmZmLTkzZTgtNjZlMjY2ZjZkMmU0|a071d43a-952d-49ba-befb-a05ffc650514, The cached token key is not a valid JSON and cannot be parsed

The only way I can get it to work is to:
1. Launch the app
1. Login
1. Error
1. Clear local storage
1. Refresh page

I've compared it to your starter app and I'm not seeing any differences but perhaps I'm missing something trivial

2020-10-28 08:41 UTC, opbld30 commented
Docs Build status updates of commit _[a2ca81b](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/a2ca81b72c62239967994f68af68040e8b17d90e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) | [Details](#user-content-ec93b1b5-115094ef)
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) | [Details](#user-content-da4b186c-115094ef)
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-115094ef)
[concepts/toc.yml](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/overview.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-base-react-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-base-react-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-signin-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-signin-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="ec93b1b5-115094ef"></a>
### [concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md)
 - **Line 5, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'wmastyka' is not a valid GitHub ID.`````

<a id="da4b186c-115094ef"></a>
### [concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md)
 - **Line 13, Column 25**: **[Warning-file-not-found]** `````Invalid file link: './add-aad-app-registration.md'.`````

<a id="48910927-115094ef"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

For more details, please refer to the [build report](https://opbu [...]

2020-10-28 09:52 UTC, opbld33 commented
Docs Build status updates of commit _[9643e0b](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/9643e0bf44c65e46834cc411015cfe88111203d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-96ad2317)
[concepts/toc.yml](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/overview.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-base-react-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-base-react-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-signin-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-signin-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-96ad2317"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010280950519889-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=L3lxIjv1X03Cv%2B0rH6JgPBBEF9ZWZOVML40a4sqUpa4%3D&st=2020-10-28T09%3A47%3A11Z&se=2020-11-28T09%3A52%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review. [...]

2020-10-28 15:56 UTC, elisenyang requested changes
Thanks so much for your help improving this guide! I just left a few comments.

2020-10-28 15:56 UTC, elisenyang commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +      ```tsx
Thoughts on breaking this up into smaller bits of code to make it easier to digest? For example: import components, initialize provider, and add components

2020-10-28 15:56 UTC, elisenyang commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +    ```tsx
Here as well. Consider breaking this up into smaller steps

2020-10-28 20:28 UTC, nmetulev commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +          clientId: 'd7cb93c9-9097-4e38-8f06-7c0088ac3318'
Good point, what about just adding the text without the brackets:

`clientId: 'REPLACE_WITH_CLIENTID'`

2020-10-28 20:39 UTC, nmetulev commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +1. In the code editor open the **src/App.tsx** file, and modify its contents to the following:
Looks like this is a recent bug in the latest msal 1.x update: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2492. I think you are safe to ignore (assuming this will get fixed by the msal team)

2020-10-28 20:41 UTC, opbld34 commented
Docs Build status updates of commit _[2e4728c](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/2e4728cdf52874efd6876903c139005843bfb6d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-d0306969)
[concepts/toc.yml](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/overview.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-base-react-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-base-react-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-signin-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-signin-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-d0306969"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010282039297306-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kI8iiJKPGcKZ3bimcv8xBO32CJA%2BXjxHIAu%2BlCk19TQ%3D&st=2020-10-28T20%3A36%3A08Z&se=2020-11-28T20%3A41%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://revie [...]

2020-10-29 07:44 UTC, waldekmastykarz commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +To follow the steps below, you'll need a development machine with [Node.js](https://nodejs.org) and an account with Microsoft Azure. You can [get one for free](https://azure.microsoft.com/free/https:
Ah, seems like I made a typo pasting it. Good catch! Sorry

2020-10-29 07:46 UTC, waldekmastykarz commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +      ```tsx
The trouble is that breaking it into smaller chunks makes it really hard to follow which code snippet should go where in the app. If we're to break up, we'd need to repeat the whole `App.tsx` each time. Since the code snippet isn't that large, I decided to include it just once. Ideally, we could clarify it by referring to line numbers but I don't think there is a way to show them, is there?

2020-10-29 07:54 UTC, waldekmastykarz commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +1. In the code editor open the **src/App.tsx** file, and modify its contents to the following:
_safe to ignore_ as in we keep Provider initialization in `index.tsx` and folks might get this error when running the sample too, or we keep provider initialization in `App.tsx` for now so that folks can build a working app and we'll update the sample and doc when the issue is fixed?

2020-10-29 08:00 UTC, opbld30 commented
Docs Build status updates of commit _[14be728](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/14be72822d0c6c75c51b24e8b0625b941c85b95e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-b29b8336)
[concepts/toc.yml](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/overview.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-base-react-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-base-react-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-signin-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-signin-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-b29b8336"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010290759261054-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bOMgtPGEPkEpprZ2J%2F%2FpwAv8hNKeX2uFEZcsdOWnL14%3D&st=2020-10-29T07%3A55%3A46Z&se=2020-11-29T08%3A00%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://revie [...]

2020-11-03 15:07 UTC, beth-panx approved these changes
Minor things I noticed. Looks great! Thank you for updating the docs 👍🏼

2020-11-03 15:07 UTC, beth-panx commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +
Should we link to the providers section from here?

2020-11-03 16:12 UTC, nmetulev commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +1. In the code editor open the **src/App.tsx** file, and modify its contents to the following:
Looks like this was fixed in the latest [msal update](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2510) - do you mind trying it out again by making sure the latest msal get's pulled from npm?

2020-11-03 16:14 UTC, waldekmastykarz commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +[!INCLUDE [AAD with implicit flow app registration](../includes/aad-app-registration-spa.md)]
This is a special syntax that will embed the steps on AAD as a part of the article rather than it being just a link that requires the reader to head off to a different place, complete the steps there and get back to the article.

2020-11-03 16:14 UTC, waldekmastykarz commented on concepts/toolkit/get-started/add-aad-app-registration.md
> +1. For the type of supported account types, select `Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)`
Good idea. Let me see if I can find a resource that explains it

2020-11-03 16:15 UTC, waldekmastykarz commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +   ![Application ID copied from the app registration overview page in the Azure Portal](../images/mgt-azure-add-appreg-copyappid.png)
I'm using an MOD tenant that will self-destruct in a bit so no issue 😎

2020-11-03 16:15 UTC, waldekmastykarz commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +
Good idea! We can add a link to `other providers`.

2020-11-03 16:47 UTC, beth-panx commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +[!INCLUDE [AAD with implicit flow app registration](../includes/aad-app-registration-spa.md)]
Gotcha!

2020-11-03 17:00 UTC, opbld32 commented
Docs Build status updates of commit _[be9186c](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/be9186ca193f56824c865116edb5fe9e08f46750)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-7f4dfbea)
[concepts/toc.yml](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/overview.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-base-react-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-base-react-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-signin-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-signin-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-7f4dfbea"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011031658415657-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fq1Clvi%2BIpIeWIlEndChM1FLvUsGAGyS6X77raxvzWQ%3D&st=2020-11-03T16%3A55%3A00Z&se=2020-12-04T17%3A00%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.d [...]

2020-11-03 17:03 UTC, elisenyang approved these changes

2020-11-03 17:03 UTC, elisenyang commented on concepts/toolkit/get-started/add-aad-app-registration.md
> +1. In the **Redirect URI** field, in the dropdown select `Web` and in the URL field enter `https://localhost:3000`
I think this should be more general since not everyone will use something different. Something like "enter the URL at which you will be hosting your app (for example: https://localhost:3000/"

2020-11-04 06:57 UTC, waldekmastykarz commented on concepts/toolkit/get-started/add-aad-app-registration.md
> +1. In the **Redirect URI** field, in the dropdown select `Web` and in the URL field enter `https://localhost:3000`
This URL comes from the React tools, so if you follow these steps to the letter, this will be your URL.

2020-11-04 07:11 UTC, waldekmastykarz commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +1. In the code editor open the **src/App.tsx** file, and modify its contents to the following:
It's working. I noticed though, that after moving Provider initialization to `index.tsx`, listening to Provider state change in `App.tsx` was no longer working. Instead, I had to use the `useIsSignedIn` function from your repo https://github.com/nmetulev/graph-react-starter/blob/87d6828d847c6ec98c72fdf70627a145ae5ed6f3/src/mgt.ts#L6

2020-11-04 08:20 UTC, waldekmastykarz commented on concepts/toolkit/get-started/add-aad-app-registration.md
> +1. For the type of supported account types, select `Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)`
Link added

2020-11-04 08:21 UTC, waldekmastykarz commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +
Link added

2020-11-04 08:26 UTC, opbld31 commented
Docs Build status updates of commit _[05ec4e2](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/05ec4e24cb05374609c7d26bb24abcf7633d88d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-820e6943)
[concepts/toc.yml](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/overview.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-base-react-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-base-react-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-signin-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-signin-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-820e6943"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011040824240551-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=shHhTP8RUs8FFj1WPxV77DXjG8DN%2B9aiTphfoP%2BzXTo%3D&st=2020-11-04T08%3A21%3A21Z&se=2020-12-05T08%3A26%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review [...]

2020-11-04 18:15 UTC, elisenyang commented on concepts/toolkit/get-started/add-aad-app-registration.md
> +1. In the **Redirect URI** field, in the dropdown select `Web` and in the URL field enter `https://localhost:3000`
I think it would be great if we can reference this app registration page in other guides too, not just the React one! Developers may have different URL in those cases

2020-11-05 16:17 UTC, nmetulev approved these changes

2020-11-05 16:20 UTC, opbld31 commented
Docs Build status updates of commit _[6258a04](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/6258a04c03c3dcad7fd62cd1984bc540a2efe335)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-6c3dfc2b)
[concepts/toc.yml](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/overview.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-base-react-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-base-react-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-signin-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-signin-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-6c3dfc2b"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011051619439429-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Fh1nwqx5pxJ2HyC85k5nHLn9k43D2W%2BThEwEMEJSINw%3D&st=2020-11-05T16%3A15%3A55Z&se=2020-12-06T16%3A20%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.d [...]

2020-11-07 01:04 UTC, opbld34 commented
Docs Build status updates of commit _[a8b6aa8](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/a8b6aa8106a03a6a92bb324ec3638f57383d5668)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-78c01185)
[concepts/toc.yml](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/overview.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-base-react-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-base-react-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-signin-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-signin-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-78c01185"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011070103386379-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=n4K%2FI1LATsu9B76zeTtKAruCPf1FnDdporetrCG6cU8%3D&st=2020-11-07T00%3A59%3A48Z&se=2020-12-08T01%3A04%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.d [...]

2020-11-07 01:06 UTC, opbld34 commented
Docs Build status updates of commit _[e19b421](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/e19b421e8b48f5e589075b28e827ed462e576d98)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-ce82eb27)
[concepts/toc.yml](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/overview.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-base-react-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-base-react-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-signin-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-signin-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-ce82eb27"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011070104433947-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2B63RWmG0VpKnltM5kpSVd42dpsTk3IH8dTi%2F13IgRsk%3D&st=2020-11-07T01%3A01%3A08Z&se=2020-12-08T01%3A06%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review [...]

2020-11-07 01:33 UTC, opbld33 commented
Docs Build status updates of commit _[b8c6bcc](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/b8c6bcc9c6d85a70d41f40090388eb0c6f9cf6c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-ff426202)
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) | [Details](#user-content-f81256c4-ff426202)
[concepts/toc.yml](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/overview.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-base-react-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-base-react-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-signin-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-signin-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-ff426202"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

<a id="f81256c4-ff426202"></a>
### [concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md)
 - **Line 180, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/overview?toc=.%2Fref%2Ftoc.json&view=graph-rest-1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011070132132084-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=15YSK1zBwhY4RIqRCMCE7wThpKrYl8vRHyQ50FimhPQ%3D&st=2020-11-07T01%3A28%3A25Z&se=2020-12-08T01%3A33%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the [...]

2020-11-07 01:34 UTC, opbld33 commented
Docs Build status updates of commit _[ab780b4](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/ab780b40628086f4415e8922c1db54e2433222fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-871c47c5)
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) | [Details](#user-content-f81256c4-871c47c5)
[concepts/toc.yml](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/overview.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-implicitgrant.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-menu-authentication.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg-newreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-add-menu-appreg.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/aad-app-registration-spa/mgt-azure-menu-add.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-azure-add-appreg-copyappid.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-base-react-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-base-react-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-signin-button.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-signin-button.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-871c47c5"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

<a id="f81256c4-871c47c5"></a>
### [concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md)
 - **Line 180, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/overview?toc=.%2Fref%2Ftoc.json&view=graph-rest-1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011070133081432-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=78zHsHvyq5FruGLNbTdMKQfGtGcz1fLlGUvQBL80EDE%3D&st=2020-11-07T01%3A29%3A46Z&se=2020-12-08T01%3A34%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the [...]

2020-11-07 01:44 UTC, Lauragra commented on concepts/toolkit/get-started/add-aad-app-registration.md
> +   ![The 'Azure Active Directory' menu option highlighted in the Azure Portal](../images/aad-app-registration-spa/mgt-azure-menu-add.png)
All the images in this article are gigantic and they also contain a lot of non-localizable text: https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424. Unless the UI is difficult to follow for some reason, I recommend that you simply remove these screenshots.

2020-11-07 01:50 UTC, Lauragra commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +![Newly created React app running in the browser](../images/mgt-base-react-app.png)
Is this image really adding anything? It's also pretty big on the page.

2020-11-07 01:51 UTC, Lauragra commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +![Finished app](../images/mgt-finished-app.png)
Suggest removing from here since we show the same image at the end of the article.

2020-11-07 01:52 UTC, Lauragra commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +   ![Application ID copied from the app registration overview page in the Azure Portal](../images/mgt-azure-add-appreg-copyappid.png)
You can crop this image to only show the important part. Images with lots of English text can't be localized, and the content also isn't accessible to a screen reader. Try to avoid showing too much text in images.

2020-11-07 01:53 UTC, Lauragra commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +   ![React app showing the Sign In button](../images/mgt-react-signin-button.png)
This image includes a lot of blank white space; please crop.

2020-11-07 01:53 UTC, Lauragra commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +  ![React app showing user info retrieved from Microsoft 365 using Microsoft Graph Toolkit](../images/mgt-react-userinfo.png).
This image can also be reduced.

2020-11-07 01:54 UTC, Lauragra commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +![Person's calendar displayed using Microsoft Graph Toolkit](../images/mgt-finished-app.png)
This is another occurrence of the same image. Let's show it only once in the article; probably at the end is fine.

2020-11-07 01:55 UTC, Lauragra requested changes
Please see comments regarding the use of the images in the articles.

2020-11-09 12:37 UTC, waldekmastykarz commented on concepts/toolkit/get-started/add-aad-app-registration.md
> +   ![The 'Azure Active Directory' menu option highlighted in the Azure Portal](../images/aad-app-registration-spa/mgt-azure-menu-add.png)
My idea was to help people unfamiliar with Azure orient themselves in the UI. You make a very good point though with regards to localization, I'll remove them.

2020-11-09 12:43 UTC, waldekmastykarz commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +![Newly created React app running in the browser](../images/mgt-base-react-app.png)
My idea was to help people ensure that we're starting from the same point. I'll remove it.

2020-11-09 12:46 UTC, waldekmastykarz commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +   ![Application ID copied from the app registration overview page in the Azure Portal](../images/mgt-azure-add-appreg-copyappid.png)
My idea was to include just enough of the image to help people unfamiliar with Azure orient themselves in the UI. You make a good point about the amount of English text in the UI. I'm afraid though, that if we crop the image too much, its point will be lost and it will be even harder for people to find where in the UI they should be. Let's remove the image altogether.

2020-11-09 12:48 UTC, waldekmastykarz commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +   ![React app showing the Sign In button](../images/mgt-react-signin-button.png)
I'll remove the image altogether, as cropping it too much will remove some of the context (URL, browser window) with which the image will lose its value.

2020-11-09 12:59 UTC, waldekmastykarz commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +  ![React app showing user info retrieved from Microsoft 365 using Microsoft Graph Toolkit](../images/mgt-react-userinfo.png).
Cropped

2020-11-09 12:59 UTC, waldekmastykarz commented on concepts/toolkit/get-started/use-toolkit-with-react.md
> +![Person's calendar displayed using Microsoft Graph Toolkit](../images/mgt-finished-app.png)
Removed

2020-11-09 13:01 UTC, waldekmastykarz commented
Thank you for your feedback @Lauragra. I've just submitted a set of changes following your feedback.

2020-11-09 13:03 UTC, opbld31 commented
Docs Build status updates of commit _[1b56414](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/1b564149aa6620d921e2a777938d92910b0e9a46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-c78ccc4f)
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) | [Details](#user-content-f81256c4-c78ccc4f)
[concepts/toc.yml](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/overview.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-c78ccc4f"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

<a id="f81256c4-c78ccc4f"></a>
### [concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md)
 - **Line 172, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/overview?toc=.%2Fref%2Ftoc.json&view=graph-rest-1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011091301078247-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2B3wdlEhoAZ6wBUOT8NNiQcFSMIV1SNnkSw2Z%2BGpOPBU%3D&st=2020-11-09T12%3A58%3A12Z&se=2020-12-10T13%3A03%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 02:37 UTC, opbld30 commented
Docs Build status updates of commit _[0e79610](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/0e79610554d9dd492b5783c6bfdea5b6724563e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-5af1416c)
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) | [Details](#user-content-f81256c4-5af1416c)
[concepts/toc.yml](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/overview.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-5af1416c"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

<a id="f81256c4-5af1416c"></a>
### [concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md)
 - **Line 170, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/overview?toc=.%2Fref%2Ftoc.json&view=graph-rest-1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011100236286084-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iDANIFb2SqbE9VxPkuUqhZf9fYHiFmoVODSPmsvyVJU%3D&st=2020-11-10T02%3A32%3A49Z&se=2020-12-11T02%3A37%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 02:42 UTC, opbld32 commented
Docs Build status updates of commit _[696e79a](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/696e79ab97405579324fefc66af7141a3fc56eb9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-17256b5f)
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) | [Details](#user-content-f81256c4-17256b5f)
[concepts/toc.yml](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/overview.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-17256b5f"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

<a id="f81256c4-17256b5f"></a>
### [concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md)
 - **Line 170, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/overview?toc=.%2Fref%2Ftoc.json&view=graph-rest-1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011100240526352-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ugAzHlisADcDREUAmkIkTF6BkjlnkoHgqVzkdSqQAhA%3D&st=2020-11-10T02%3A37%3A13Z&se=2020-12-11T02%3A42%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 02:43 UTC, opbld33 commented
Docs Build status updates of commit _[9b37f34](https://github.com/waldekmastykarz/microsoft-graph-docs/commits/9b37f3460b61f5693ec1de562844feac34a4c154)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10424) | [Details](#user-content-48910927-8369b147)
[concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) | [Details](#user-content-f81256c4-8369b147)
[concepts/toc.yml](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/add-aad-app-registration.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/add-aad-app-registration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/add-aad-app-registration?branch=pr-en-us-10424) |
[concepts/toolkit/get-started/overview.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/overview?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-finished-app.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-finished-app.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/images/mgt-react-userinfo.png](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/images/mgt-react-userinfo.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |
[concepts/toolkit/includes/aad-app-registration-spa.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/includes/aad-app-registration-spa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react?branch=pr-en-us-10424) |

<a id="48910927-8369b147"></a>
### [concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md)
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest`````

<a id="f81256c4-8369b147"></a>
### [concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/waldekmastykarz/microsoft-graph-docs/blob/mgt-react/concepts/toolkit/get-started/use-toolkit-with-react.md)
 - **Line 170, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/overview?toc=.%2Fref%2Ftoc.json&view=graph-rest-1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011100241504945-10424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ohIEC2SAsz1PLVK%2BRXtfVVd8c3Mk0Q3%2BV9KPhE56ivg%3D&st=2020-11-10T02%3A38%3A37Z&se=2020-12-11T02%3A43%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 02:45 UTC, merged