2020 09 30 question
microsoftgraph/microsoft-graph-docs pull request #10432
Opened 2020-10-26 22:05 UTC by hanki-microsoft

Adding API Beta docs for ELM question and answers feature

2020-10-26 22:07 UTC, opbld32 commented
Docs Build status updates of commit _[19cbb03](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19cbb034e239df354aec80f49872852e07d24834)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-1ffd2acc-12f27ad0)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-12f27ad0)
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[doc-stubs/api/accesspackage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/doc-stubs/api/accesspackage-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accesspackage-delete-accesspackageassignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/doc-stubs/api/accesspackage-delete-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accesspackage-delete-accesspackagecatalog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/doc-stubs/api/accesspackage-delete-accesspackagecatalog.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accesspackage-delete-accesspackageresourcerolescopes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/doc-stubs/api/accesspackage-delete-accesspackageresourcerolescopes.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/doc-stubs/api/accesspackage-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accesspackage-get-accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/doc-stubs/api/accesspackage-get-accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accesspackage-get-accesspackageresourcerolescope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/doc-stubs/api/accesspackage-get-accesspackageresourcerolescope.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accesspackage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/doc-stubs/api/accesspackage-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accesspackage-list-accesspackageassignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/doc-stubs/api/accesspackage-list-accesspackageassignmentpolicies.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accesspackage-list-accesspackagecatalog.md](https://github [...]

2020-10-27 01:51 UTC, Lauragra commented
@hanki-microsoft , your PR include 377 files. We limit PRs to 100 files maximum to better facilitate reviews. If you need to update this many files, please batch in separate PRs.

2020-10-27 18:11 UTC, davidmu1 reviewed
Please remove the docstubs files from the PR.

2020-10-27 18:30 UTC, opbld30 commented
Docs Build status updates of commit _[34f647f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34f647f0c24eb832fab89c9e4fa0e3aac028d5a9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-1ffd2acc-016b19a7)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-016b19a7)
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="1ffd2acc-016b19a7"></a>
### [api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/accesspackagelocalizedcontent.md(3,14)', 'beta/resources/accesspackagelocalizedtext.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="21430181-016b19a7"></a>
### [api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS pr [...]

2020-10-27 20:59 UTC, opbld32 commented
Docs Build status updates of commit _[950c78c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/950c78c966bb45346ae53140d00bbc22dcc9b6ef)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-1ffd2acc-fc01e3f1)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-fc01e3f1)
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="1ffd2acc-fc01e3f1"></a>
### [api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/accesspackagelocalizedcontent.md(3,14)', 'beta/resources/accesspackagelocalizedtext.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="21430181-fc01e3f1"></a>
### [api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS pr [...]

2020-10-27 21:04 UTC, opbld33 commented
Docs Build status updates of commit _[163ec15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/163ec15d64e2da83ef0049c6431d443721688d11)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-1ffd2acc-d64e1879)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-d64e1879)
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="1ffd2acc-d64e1879"></a>
### [api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/accesspackagelocalizedcontent.md(3,14)', 'beta/resources/accesspackagelocalizedtext.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="21430181-d64e1879"></a>
### [api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS pr [...]

2020-10-28 18:17 UTC, opbld32 commented
Docs Build status updates of commit _[b8c76aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8c76aa441ae5fec22bf4eb42c48c699beddd66b)_: 

:clock10: **Pending**: waiting for processors ([21](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 21 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-28 18:19 UTC, opbld30 commented
Docs Build status updates of commit _[b8c76aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8c76aa441ae5fec22bf4eb42c48c699beddd66b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-1ffd2acc-6d7e7547)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-6d7e7547)
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="1ffd2acc-6d7e7547"></a>
### [api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/accesspackagelocalizedcontent.md(3,14)', 'beta/resources/accesspackagelocalizedtext.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="21430181-6d7e7547"></a>
### [api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS pr [...]

2020-10-28 18:19 UTC, opbld31 commented
Docs Build status updates of commit _[0043cfd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0043cfd4374967e73e2b74987da97ee62dc01e0b)_: 

:clock10: **Pending**: waiting for processors ([28](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 28 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-28 18:20 UTC, opbld33 commented
Docs Build status updates of commit _[0928d59](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0928d594c03292f8e31879f8120539ae566cad13)_: 

:clock10: **Pending**: waiting for processors ([28](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 28 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-28 18:21 UTC, opbld34 commented
Docs Build status updates of commit _[0043cfd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0043cfd4374967e73e2b74987da97ee62dc01e0b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-1ffd2acc-9491ef71)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-9491ef71)
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="1ffd2acc-9491ef71"></a>
### [api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/accesspackagelocalizedcontent.md(3,14)', 'beta/resources/accesspackagelocalizedtext.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="21430181-9491ef71"></a>
### [api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS pr [...]

2020-10-28 18:23 UTC, opbld33 commented
Docs Build status updates of commit _[0928d59](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0928d594c03292f8e31879f8120539ae566cad13)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-1ffd2acc-58aca78d)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-58aca78d)
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="1ffd2acc-58aca78d"></a>
### [api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/accesspackagelocalizedcontent.md(3,14)', 'beta/resources/accesspackagelocalizedtext.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="21430181-58aca78d"></a>
### [api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS pr [...]

2020-11-09 16:25 UTC, markwahl-msft requested changes
Looks like some of the localized docs are still in progres.

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-post.md
> +        "allowedRequestors": [{
if the scope is all existing connected orgs then why are there group members called out?  this is not clear to me.

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-post.md
> +    "accessReviewSettings": {
could we shorten the example by having fewer things in it?  e.g., if this is an example of questions do we need to have multi-stage approval and access reviews in this as well?

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-post.md
> +            "defaultText": "why do you need access to this package?",
how is this question different from the 'business justification' field we already have?

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-post.md
> +[!INCLUDE [sample-code](../includes/snippets/csharp/create-accesspackageassignmentpolicy-from-accesspackageassignmentpolicies-csharp-snippets.md)]
could you check that these examples for C#, JavaScript and Objective C exist, and show the questions above?  I saw the previous text say "Example 3" so not sure that these snippets are for the 3rd example and not some other example in this doc.

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +        "answeredQuestion": {
why does the caller need to send all of this? doesn't Azure AD already have all of the questoins?  cant it just send an indication of which question its answering and the answer?

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +                "defaultText": "what state are you from?",
don't questions have some kind of unique identifier?  E.g., if someone changes the text for just minor spelling or phrasing edits like "What state are you signing in from?" then it wouldn't match any more.

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +# [C#](#tab/csharp)
and these examples already exist?? with the questions and answers?

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackageanswerstring.md
> +|value|String|**TODO: Add Description**|
update needed

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackagelocalizedcontent.md
> +description: "**TODO: Add Description**"
update needed

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackagelocalizedcontent.md
> +ms.prod: "**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**"
update needed

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackagelocalizedcontent.md
> +|defaultText|String|**TODO: Add Description**|
I think this article needs some edits.

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackagelocalizedtext.md
> +author: "**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**"
I think this article needs some edits.

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackagemultiplechoicequestion.md
> +description: "Child of accessPackageQuestion that has multiple choice as the question's answer format"
Suggest say subtype or subclass rather than child.

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackagequestion.md
> +Used for the `accessPackageQuestion` property of an [access package assignment policy](accesspackageassignmentpolicy.md).
might want to mention the subtypes of this, like multiple choice question.

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +        "@odata.type": "#microsoft.graph.accessPackageAnswerString",
i don't see the "id". could the requestor just send the question ID and their answer?

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-post.md
> +Questions configured in an assignment policy will be asked to requestors in scope of the policy. Their answers will be shown to their approvers.
Does the client set the id of each question or does the service include the id in its response?

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-post.md
> +        "isRequired": false,
where is the "id" field?

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-post.md
> +        "isRequired": false,
this needs an id as well.

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-update.md
> +    "questions": [{
does the client need to send all the questions?  if so, do they send the "id" field from before? otherwise how does the service know if it's the same question or not?

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-update.md
> +                    "text": "Arizona?",
why does Arizona have a question character?

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-update.md
> +            "actualValue": "Arizona",
might improve the example for the actualValue to be the two-letter code AZ CA OH etc so that it is clear why the actualvalue and displayValue can sometimes be different

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +                "defaultText": "what state are you from?",
Need to have just the value and the "id" rather than the list of choices, the client shouldn't need to echo this back to the service.

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +            "isRequired": false,
where is the id for the question?

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackageanswer.md
> +|answeredQuestion|[accessPackageQuestion](../resources/accesspackagequestion.md)|The question the answer is for.|
need to say which parameters of the question are required.  E.g., is just the 'id' sufficient?

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackageanswer.md
> +The complex type of a requestor's provided answer to an [accessPackageQuestion](../resources/accesspackagequestion.md). These answers will be stored on an [accessPackageAssignmentRequest](../resource
should say that the actual answer value is in a subtype of this class.

2020-11-09 16:25 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackageanswerchoice.md
> +|actualValue|String|The values that are stored. Only relevant when different from the display value.|
by 'relevant' does this mean that the client doesn't need to send it? if the client sends both which one is authoritative?

2020-11-17 00:45 UTC, hanki-microsoft commented on api-reference/beta/api/accesspackageassignmentpolicy-post.md
> +Questions configured in an assignment policy will be asked to requestors in scope of the policy. Their answers will be shown to their approvers.
Question IDs are read-only. They are included in the response by default. - Will add to docs

2020-11-17 01:01 UTC, hanki-microsoft commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +        "answeredQuestion": {
Question text can change over time, so we need to keep track of the text at the time the question was answered for auditing purposes.

2020-11-17 01:09 UTC, hanki-microsoft commented on api-reference/beta/resources/accesspackagemultiplechoicequestion.md
> +description: "Child of accessPackageQuestion that has multiple choice as the question's answer format"
Edited

2020-11-17 01:10 UTC, opbld32 commented
Docs Build status updates of commit _[b603a7d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b603a7de5f0641597bf11e49b32e292d7f212aaa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-2004b604-264304c0)
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-5961d7dc-264304c0)
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-1ffd2acc-264304c0)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-264304c0)
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="2004b604-264304c0"></a>
### [api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md)
 - **Line 285, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="5961d7dc-264304c0"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md)
 - **Line 136, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="1ffd2acc-264304c0"></a>
### [api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/a [...]

2020-11-17 01:28 UTC, opbld32 commented
Docs Build status updates of commit _[d84efc6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d84efc6b8c96f31fcb19881db49b99be2bca65d8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-2004b604-1e286628)
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-5961d7dc-1e286628)
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-1ffd2acc-1e286628)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-1e286628)
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="2004b604-1e286628"></a>
### [api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md)
 - **Line 285, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="5961d7dc-1e286628"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md)
 - **Line 136, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="1ffd2acc-1e286628"></a>
### [api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/a [...]

2020-11-17 01:35 UTC, opbld34 commented
Docs Build status updates of commit _[9097d56](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9097d5664023bb18576834a5867865606c099af4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-2004b604-4555ea82)
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-5961d7dc-4555ea82)
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-1ffd2acc-4555ea82)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-4555ea82)
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="2004b604-4555ea82"></a>
### [api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md)
 - **Line 285, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="5961d7dc-4555ea82"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md)
 - **Line 136, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="1ffd2acc-4555ea82"></a>
### [api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/a [...]

2020-11-17 01:38 UTC, hanki-microsoft commented on api-reference/beta/resources/accesspackageanswerstring.md
> +|value|String|**TODO: Add Description**|
updated

2020-11-17 01:40 UTC, opbld33 commented
Docs Build status updates of commit _[3cb8d3a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3cb8d3a6aca1c57d7d3ddd06a773b1bf906910b2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-2004b604-5d58684d)
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-5961d7dc-5d58684d)
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-1ffd2acc-5d58684d)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-5d58684d)
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="2004b604-5d58684d"></a>
### [api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md)
 - **Line 285, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="5961d7dc-5d58684d"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md)
 - **Line 136, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="1ffd2acc-5d58684d"></a>
### [api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/a [...]

2020-11-17 01:43 UTC, hanki-microsoft commented on api-reference/beta/api/accesspackageassignmentpolicy-post.md
> +[!INCLUDE [sample-code](../includes/snippets/csharp/create-accesspackageassignmentpolicy-from-accesspackageassignmentpolicies-csharp-snippets.md)]
@davidmu1 did I configure the C#, JavaScript and Objective C examples incorrectly?

2020-11-17 01:44 UTC, opbld34 commented
Docs Build status updates of commit _[07caab0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/07caab077761d3357881466513085255761205c5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-2004b604-2c56387f)
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-5961d7dc-2c56387f)
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-1ffd2acc-2c56387f)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-2c56387f)
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="2004b604-2c56387f"></a>
### [api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md)
 - **Line 285, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="5961d7dc-2c56387f"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md)
 - **Line 136, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="1ffd2acc-2c56387f"></a>
### [api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/a [...]

2020-11-18 01:28 UTC, opbld31 commented
Docs Build status updates of commit _[eab0edd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eab0edd201fd5f749720eaf7e3f14ded2838adc2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-2004b604-28e3c64d)
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-5961d7dc-28e3c64d)
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-1ffd2acc-28e3c64d)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-28e3c64d)
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="2004b604-28e3c64d"></a>
### [api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md)
 - **Line 285, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="5961d7dc-28e3c64d"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md)
 - **Line 136, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="1ffd2acc-28e3c64d"></a>
### [api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/a [...]

2020-11-18 01:32 UTC, opbld33 commented
Docs Build status updates of commit _[9a234be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a234be09580efd486cf4a83a65a4f85dac63d6c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-2004b604-e75f3bab)
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-5961d7dc-e75f3bab)
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-1ffd2acc-e75f3bab)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-e75f3bab)
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="2004b604-e75f3bab"></a>
### [api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md)
 - **Line 285, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="5961d7dc-e75f3bab"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md)
 - **Line 136, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="1ffd2acc-e75f3bab"></a>
### [api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/a [...]

2020-11-18 01:33 UTC, opbld34 commented
Docs Build status updates of commit _[dbf2aa8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dbf2aa87742f31b591e2a0f16d225669995d0ffd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-2004b604-6f818c76)
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-5961d7dc-6f818c76)
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-1ffd2acc-6f818c76)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-6f818c76)
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="2004b604-6f818c76"></a>
### [api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md)
 - **Line 285, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="5961d7dc-6f818c76"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md)
 - **Line 136, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="1ffd2acc-6f818c76"></a>
### [api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/a [...]

2020-11-18 01:52 UTC, opbld33 commented
Docs Build status updates of commit _[1ebb7d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ebb7d9ed9a1697e82455dab42c8ceb173fec665)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-2004b604-b5a3bfc5)
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-5961d7dc-b5a3bfc5)
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-21430181-b5a3bfc5)
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="2004b604-b5a3bfc5"></a>
### [api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md)
 - **Line 285, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="5961d7dc-b5a3bfc5"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md)
 - **Line 136, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="21430181-b5a3bfc5"></a>
### [api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011180151259310-10432%5 [...]

2020-11-18 02:00 UTC, opbld33 commented
Docs Build status updates of commit _[657d18c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/657d18c6b911d706dba0dfdd45adacb9e397f473)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-2004b604-745ef46c)
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-5961d7dc-745ef46c)
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="2004b604-745ef46c"></a>
### [api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md)
 - **Line 285, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="5961d7dc-745ef46c"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md)
 - **Line 136, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011180158399007-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=b0as3RWba829AduS4VWBY2JXH8qnd55VLK8p%2B0LQwYQ%3D&st=2020-11-18T01%3A55%3A04Z&se=2020-12-19T02%3A00%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated [...]

2020-11-18 19:44 UTC, opbld34 commented
Docs Build status updates of commit _[26bb2e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26bb2e9a76896327a17460d21a7eb39eafe7f6f4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-2004b604-583971d9)
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-5961d7dc-583971d9)
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="2004b604-583971d9"></a>
### [api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md)
 - **Line 285, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

<a id="5961d7dc-583971d9"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md)
 - **Line 136, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011181942330844-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ik10auo5e8IN7bYrhVYSpDrJncFI30bziDXHsz%2F%2B4g8%3D&st=2020-11-18T19%3A39%3A04Z&se=2020-12-19T19%3A44%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelat [...]

2020-11-19 19:52 UTC, opbld30 commented
Docs Build status updates of commit _[10a325f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/10a325f4d2da4751e4c10077705ad62e5283b15a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) | [Details](#user-content-5961d7dc-13e4f838)
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="5961d7dc-13e4f838"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md)
 - **Line 136, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011191950329535-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z11Nz28RKpPZAUBqt0ltE4otzFShNU4v%2BmULUj%2FRDDY%3D&st=2020-11-19T19%3A47%3A06Z&se=2020-12-20T19%3A52%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://re [...]

2020-11-19 19:54 UTC, opbld31 commented
Docs Build status updates of commit _[f0f1409](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f0f1409f81efc9eca92749b50d4e15adea953502)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011191952577335-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oaKykFr6Bgv%2B7U5a5galjssPlbHmVUtvb6NdwLGUnTA%3D&st=2020-11-19T19%3A49%3A16Z&se=2020-12-20T19%3A54%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-19 19:56 UTC, opbld34 commented
Docs Build status updates of commit _[c1649ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c1649ae0b1205edd59c16cdbe7d408c0fd524dd4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011191955171014-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VgS1CwLFGO5urfRAdUJLdzWwX0pkQm0ZRCZ8kB60mGY%3D&st=2020-11-19T19%3A51%3A38Z&se=2020-12-20T19%3A56%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 17:51 UTC, opbld34 commented
Docs Build status updates of commit _[dacfa2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dacfa2beffe22b2ae2831e4301f2a48ff75bfb67)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011201749585681-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6KhpeFeFYqr95XBJlFhzz%2FU6krzbisatN0FA510uS4g%3D&st=2020-11-20T17%3A46%3A26Z&se=2020-12-21T17%3A51%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 17:57 UTC, opbld32 commented
Docs Build status updates of commit _[3d4d6d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d4d6d3327db64b023244d22b8b935278d369178)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011201756164129-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=R9vh%2BEjUvB1rNf6BWxWJeoL1RGi4Rrkz6tG0211RuqY%3D&st=2020-11-20T17%3A52%3A37Z&se=2020-12-21T17%3A57%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 18:02 UTC, opbld32 commented
Docs Build status updates of commit _[05bf309](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05bf3099916aca439a32699f1b44327a6bbc1b0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011201801122864-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AkSms%2FaoGq3fSfHdxXfC3umi5w0%2BYpCXTdTmlkNtjhY%3D&st=2020-11-20T17%3A57%3A35Z&se=2020-12-21T18%3A02%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 18:03 UTC, hanki-microsoft commented
@markwahl-msft  @davidmu1  Ronak and I made edits to all of your comments.

2020-11-30 17:15 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +            "id" : "AA615EE9-D9D8-4C03-BE91-BEE37106DEDA"
@hanki-microsoft  there is a missing comma

2020-11-30 17:17 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-post.md
> +        "allowedRequestors": [{
This doesn't look like a likely combination in requestor settings, since the connected org subjects won't be in groups before they are added to the directory.  Was this generated by or editable like this in the portal?

2020-11-30 17:19 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-update.md
> +    "questions": [{
please clarify in the text above this JSON whether this example is adding a new question to the list of questions, or updating an existing question

2020-11-30 17:20 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-update.md
> +                    "text": "Arizona?",
please remove the question mark character from the text Arizona? --> Arizona

2020-11-30 17:21 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +        "answeredQuestion": {
but that is the service's responsibility, not the client's responsibility.  when the client send back ID A71... and answer "Arizona" then the service knows that the question text was "What state are you from" the client doesn't need to send all of that text since the service already has it.

2020-11-30 17:21 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +                "defaultText": "what state are you from?",
see previous comment- the client should not need to send this in the assignmentrequest

2020-12-01 00:12 UTC, opbld33 commented
Docs Build status updates of commit _[ea634a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea634a23f8444551f453ba712c01ebf84bc72e00)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012010011041741-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JqkNuFPQi9DFYjtKHIIt%2BWoecyKuKBi90qTs6BiduRw%3D&st=2020-12-01T00%3A07%3A40Z&se=2021-01-01T00%3A12%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-01 00:16 UTC, opbld33 commented
Docs Build status updates of commit _[95dc6f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/95dc6f91dd3daf4fa9d2cc3b23b1adf50a81dc53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012010015205645-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C1o%2FSe%2B%2BGWPLBsstcmIfHKCITpJePh%2F68ULYiJFNmY8%3D&st=2020-12-01T00%3A11%3A57Z&se=2021-01-01T00%3A16%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-01 00:22 UTC, opbld33 commented
Docs Build status updates of commit _[a242d4b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a242d4b840f2e03998b27dda9cccde7b04e8249f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012010020409345-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=D%2F5cG7NFPud5l46kXM2d5Nd%2BI5DXXgdkx05zQjgVHoM%3D&st=2020-12-01T00%3A17%3A35Z&se=2021-01-01T00%3A22%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-01 00:40 UTC, opbld30 commented
Docs Build status updates of commit _[d9f0bb7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9f0bb76f5b748152ace658185692db5b66e2b19)_: 

:clock10: **Pending**: waiting for processors ([26](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 26 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-01 00:42 UTC, opbld30 commented
Docs Build status updates of commit _[d9f0bb7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9f0bb76f5b748152ace658185692db5b66e2b19)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012010040497277-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VedfvxKx6zRYCgNws4wZt4w5vxGGFChdd1GzEcg%2FsQY%3D&st=2020-12-01T00%3A37%3A11Z&se=2021-01-01T00%3A42%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 21:38 UTC, hanki-microsoft commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +            "id" : "AA615EE9-D9D8-4C03-BE91-BEE37106DEDA"
We removed the extra question info below this "id" so the comma is no longer needed

2020-12-04 21:41 UTC, hanki-microsoft commented on api-reference/beta/api/accesspackageassignmentpolicy-post.md
> +        "allowedRequestors": [{
@markwahl-msft we removed the allowed requestors section with the groups

2020-12-04 21:45 UTC, hanki-microsoft commented on api-reference/beta/api/accesspackageassignmentpolicy-post.md
> +        "allowedRequestors": [{
@markwahl-msft  we removed the allowed requestors section with the groups

2020-12-04 21:45 UTC, hanki-microsoft commented on api-reference/beta/api/accesspackageassignmentpolicy-update.md
> +    "questions": [{
Specified in the text that we removed a question in the policy update.

2020-12-04 21:46 UTC, opbld31 commented
Docs Build status updates of commit _[463b229](https://github.com/microsoftgraph/microsoft-graph-docs/commits/463b2298060c39699bb673fd5ad09c9d534c0afe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012042145133342-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bZhuelnRtYg5yopuzC6MY6kbTycBzJPff5uBuNK7pgQ%3D&st=2020-12-04T21%3A41%3A41Z&se=2021-01-04T21%3A46%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 21:47 UTC, hanki-microsoft commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +        "answeredQuestion": {
Updated in the Question branch

2020-12-04 21:47 UTC, hanki-microsoft commented on api-reference/beta/api/accesspackageassignmentpolicy-post.md
> +            "defaultText": "why do you need access to this package?",
Changed text

2020-12-04 22:16 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-post.md
> +        "allowedRequestors": [{
i'm still seeing it below

2020-12-04 22:16 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentpolicy-post.md
> +[!INCLUDE [sample-code](../includes/snippets/csharp/create-accesspackageassignmentpolicy-from-accesspackageassignmentpolicies-csharp-snippets.md)]
if this is a *new* article you should not have that sectoin.  they will get auto-generated for you and that section added later by someone else.

2020-12-05 00:41 UTC, markwahl-msft approved these changes

2020-12-07 19:14 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +### Example 1: Admin requests a direct assignment for a user.
Periods aren't needed in headings.

2020-12-07 19:17 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageanswerchoice.md
> +|Property|Type|Description|Required|Read-only|
```suggestion
|Property|Type|Description|
```

Whether the property is required or not should be in the description, not a table column.

2020-12-07 19:18 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageanswerstring.md
> +|answeredQuestion|[accessPackageQuestion](../resources/accesspackagequestion.md)|Question the answer is for. Inherited from [accessPackageAnswer](../resources/accesspackageanswer.md)|
This description is a little awkward. Maybe: The question that applies the the answer.

2020-12-07 19:20 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageassignmentpolicy.md
> +|questions|[accessPackageQuestion](accesspackagequestion.md) collection|Questions that are asked to requestor.|
```suggestion
|questions|[accessPackageQuestion](accesspackagequestion.md) collection|Questions that are asked of requestor.|
```

2020-12-07 19:25 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageassignmentrequest.md
> +|answers|[accessPackageAnswer](accesspackageanswer.md) collection|Answers provided by the requestor to [accessPackageQuestions](accesspackagequestion.md) asked of them at the time of request|
```suggestion
|answers|[accessPackageAnswer](accesspackageanswer.md) collection|Answers provided by the requestor to [accessPackageQuestions](accesspackagequestion.md) asked of them at the time of request.|
```

2020-12-07 19:26 UTC, davidmu1 commented on api-reference/beta/resources/accesspackagelocalizedcontent.md
> +|Property|Type|Description|Required|Read-only|
```suggestion
|Property|Type|Description|
```

2020-12-07 19:27 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageanswerchoice.md
> +|:---|:---|:---|:---|:---|
```suggestion
|:---|:---|:---|
```

2020-12-07 19:29 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageanswerchoice.md
> +|actualValue|String|The actual value of the selected choice. This is typically a string value which is understable by applications.|Yes|No|
```suggestion
|actualValue|String|The actual value of the selected choice. This is typically a string value which is understandable by applications. Required. |
```

It is assumed that a property can be written to unless stated as Read only.

2020-12-07 19:29 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageanswerchoice.md
> +|displayValue|[accessPackageLocalizedContent](../resources/accesspackagelocalizedcontent.md)|The localized display values shown to the requestor and approvers.|Yes|No|
```suggestion
|displayValue|[accessPackageLocalizedContent](../resources/accesspackagelocalizedcontent.md)|The localized display values shown to the requestor and approvers. Required.
```

2020-12-07 19:31 UTC, hanki-microsoft commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +### Example 1: Admin requests a direct assignment for a user.
Removed periods

2020-12-07 19:31 UTC, opbld31 commented
Docs Build status updates of commit _[0a6d087](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a6d087012c9616db33a294164273e14ceb00775)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071930199140-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=g5LY%2BBy6c1UEBNZ7%2F%2BY98FHDsgcBuxFj6K%2F94xyWE5o%3D&st=2020-12-07T19%3A26%3A54Z&se=2021-01-07T19%3A31%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 19:32 UTC, davidmu1 commented on api-reference/beta/resources/accesspackagelocalizedcontent.md
> +|:---|:---|:---|:---|:---|
```suggestion
|:---|:---|:---|
```

2020-12-07 19:33 UTC, davidmu1 commented on api-reference/beta/resources/accesspackagelocalizedcontent.md
> +|defaultText|String|The fallback string, which is used when a requested localization is not available.|Yes|No|
```suggestion
|defaultText|String|The fallback string, which is used when a requested localization is not available. Required.
```

2020-12-07 19:34 UTC, davidmu1 commented on api-reference/beta/resources/accesspackagelocalizedcontent.md
> +|localizedTexts|[accessPackageLocalizedText](../resources/accesspackagelocalizedtext.md) collection|Content represented in a format for a specific locale.|No|No|
```suggestion
|localizedTexts|[accessPackageLocalizedText](../resources/accesspackagelocalizedtext.md) collection|Content represented in a format for a specific locale. |
```

It is assumed that a property is not required unless explicitly stated.

2020-12-07 19:34 UTC, hanki-microsoft commented on api-reference/beta/resources/accesspackageanswerstring.md
> +|answeredQuestion|[accessPackageQuestion](../resources/accesspackagequestion.md)|Question the answer is for. Inherited from [accessPackageAnswer](../resources/accesspackageanswer.md)|
Edited description

2020-12-07 19:34 UTC, davidmu1 commented on api-reference/beta/resources/accesspackagelocalizedtext.md
> +|Property|Type|Description|Required|Read-only|
```suggestion
|Property|Type|Description|
```

2020-12-07 19:35 UTC, davidmu1 commented on api-reference/beta/resources/accesspackagelocalizedtext.md
> +|:---|:---|:---|:---|:---|
```suggestion
|:---|:---|:---|
```

2020-12-07 19:35 UTC, davidmu1 commented on api-reference/beta/resources/accesspackagelocalizedtext.md
> +|languageCode|String|The ISO code for the intended language.|Yes|No|
```suggestion
|languageCode|String|The ISO code for the intended language. Required. |
```

2020-12-07 19:35 UTC, opbld30 commented
Docs Build status updates of commit _[dcd6caa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dcd6caadf2338b34e0d5ae027c16d4f165fc5850)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071934280806-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=URBOosZViX3SAOJLWqMLaDs3Gy30ljdAIsVaYyaJ4jQ%3D&st=2020-12-07T19%3A30%3A53Z&se=2021-01-07T19%3A35%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 19:36 UTC, davidmu1 commented on api-reference/beta/resources/accesspackagelocalizedtext.md
> +|text|String|The text in the specific language|Yes|No|
```suggestion
|text|String|The text in the specific language. Required. |
```

2020-12-07 19:38 UTC, davidmu1 commented on api-reference/beta/resources/accesspackagemultiplechoicequestion.md
> +A child of `accessPackageQuestion` which presents multiple answer options a requestor must choose an answer from.
```suggestion
A child of `accessPackageQuestion` that presents multiple options that the requestor must choose an answer from.
```

2020-12-07 19:43 UTC, opbld32 commented
Docs Build status updates of commit _[f03b4e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f03b4e3cc6110387827ae68d71aafcf2ebd7c3f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071941518565-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YuNsCCCwN%2BdVTPl9itw9UPGVvSS01qTNxFKmnD5n9io%3D&st=2020-12-07T19%3A38%3A15Z&se=2021-01-07T19%3A43%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 19:44 UTC, opbld30 commented
Docs Build status updates of commit _[a467aab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a467aab3b11e505bcf8c38a4c1813d99c6aafceb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071942403415-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9y5FYP%2FhoRGlDnoFh4xMUkp7JmkaGxueGfhIMul2POQ%3D&st=2020-12-07T19%3A39%3A43Z&se=2021-01-07T19%3A44%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 19:47 UTC, opbld31 commented
Docs Build status updates of commit _[25809ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25809ee865deeffd77fea211b3e391bd93604635)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071943504936-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NZkQjxgxDuFBtOhMQmizxL5Ie3Ff2Vg9qbjKJ2FfNo0%3D&st=2020-12-07T19%3A42%3A46Z&se=2021-01-07T19%3A47%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 19:49 UTC, opbld33 commented
Docs Build status updates of commit _[325a8ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/325a8adbbf1c1d707bac9e040f05442e7040d142)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071945467693-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Tw7ke0Iu2IByYvi2%2BgcaL0L9Izj1AS7PHNFqstCfOZ0%3D&st=2020-12-07T19%3A44%3A24Z&se=2021-01-07T19%3A49%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 19:50 UTC, opbld34 commented
Docs Build status updates of commit _[0a5b9c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a5b9c257d88aceda979db269e9decd7ea2671d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071946132219-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KQQNLCMQqeQNJ8I6r3mVyu9GSLJTwOrGkHsKBlPxWJ0%3D&st=2020-12-07T19%3A45%3A53Z&se=2021-01-07T19%3A50%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 19:52 UTC, opbld31 commented
Docs Build status updates of commit _[40477f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40477f56a2dee867821e489da7295bd99621d478)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071950136753-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3RCU4eZYZrPa4DrZSs0ReprcvVyY%2B8S3doMLSHwP9XQ%3D&st=2020-12-07T19%3A47%3A34Z&se=2021-01-07T19%3A52%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 19:54 UTC, opbld30 commented
Docs Build status updates of commit _[e43a45a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e43a45a4c2c6247b62e9185693899b75da6da0ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071951343515-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zPtD6PF2OyBn9UYk1YxgXNBC%2BTf9XGGEthS7PTtpM5g%3D&st=2020-12-07T19%3A49%3A32Z&se=2021-01-07T19%3A54%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 19:55 UTC, opbld32 commented
Docs Build status updates of commit _[25809ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25809ee865deeffd77fea211b3e391bd93604635)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071943396005-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=h5j%2FUymjUcIgYr63ILHD7tPSp1GUqfxOmVTwPvegLZQ%3D&st=2020-12-07T19%3A50%3A57Z&se=2021-01-07T19%3A55%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 23:59 UTC, opbld33 commented
Docs Build status updates of commit _[4b1cb0a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b1cb0a779f12fc86446b726248bcad025eebcac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10432) | [Details](#user-content-de0bbbbb-2c7e5727)
[api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswer?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerchoice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerchoice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerchoice?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageanswerstring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageanswerstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageanswerstring?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentpolicy?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagelocalizedtext.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagelocalizedtext.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagelocalizedtext?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagemultiplechoicequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagemultiplechoicequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagemultiplechoicequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagequestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagequestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagequestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/accesspackagetextinputquestion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/accesspackagetextinputquestion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackagetextinputquestion?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-10432) (graph-rest-beta) |

<a id="de0bbbbb-2c7e5727"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-09-30-Question/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012072358194555-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VOLfccXwYnxE2poXZsmUHR8iKiwcL5uukJVINysd03U%3D&st=2020-12-07T23%3A54%3A40Z&se=2021-01-07T23%3A59%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 00:01 UTC, opbld31 commented
Docs Build status updates of commit _[d5e610b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5e610b73517970c6a1c7db5d8cc57b40e7a2414)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9e452cd6)

<a id="9e452cd6"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080000228776-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=imrtJEl19nA2W3ScoKODbCwq957y9SVgT3omrUvmF%2FE%3D&st=2020-12-07T23%3A56%3A01Z&se=2021-01-08T00%3A01%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 00:48 UTC, opbld32 commented
Docs Build status updates of commit _[514272b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/514272b6f690c025d05d3e7972371dc804435c44)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0d13235d)

<a id="0d13235d"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080048127731-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tjR6bnZF9HFMQRMB%2F3e32Ys%2BwDuwSZ6JZVnsCNvMOME%3D&st=2020-12-08T00%3A43%3A43Z&se=2021-01-08T00%3A48%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 19:00 UTC, opbld30 commented
Docs Build status updates of commit _[a7f62e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a7f62e81d45570273a1c8c4c056a46530037e5cf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c1aedc77)

<a id="c1aedc77"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012091859442716-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YFQddh6vJrSeBuoM2xzk0s9ev0CQyH9u8h9D73qGmjc%3D&st=2020-12-09T18%3A55%3A06Z&se=2021-01-09T19%3A00%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 19:10 UTC, opbld33 commented
Docs Build status updates of commit _[2c15e6d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c15e6ddebb506e86c0dffbc0402e29749c13a17)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bd5fb877)

<a id="bd5fb877"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012091909401286-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Tp7J9522Tq6jfmXP6wiSVD3GrNT5zTNnCBbRhyEHxzE%3D&st=2020-12-09T19%3A05%3A05Z&se=2021-01-09T19%3A10%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 20:00 UTC, opbld31 commented
Docs Build status updates of commit _[9c3374e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c3374eb88db4b4f59feab7c50574af838ec8a40)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-47b6b0b1)

<a id="47b6b0b1"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012091959562566-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VsifOPPTc%2BFOJqwOWN0Po7O3ef9YTvOykKCC3py%2Fqjs%3D&st=2020-12-09T19%3A55%3A19Z&se=2021-01-09T20%3A00%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 20:57 UTC, opbld31 commented
Docs Build status updates of commit _[69e5968](https://github.com/microsoftgraph/microsoft-graph-docs/commits/69e5968d3734098845fba712a5defd7b69b55996)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9fa3b4ea)

<a id="9fa3b4ea"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012092057021481-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KKeXNvh5zXZ2xVaOypAvtT%2FsIS6L8IfcMevQbQi93sU%3D&st=2020-12-09T20%3A52%3A22Z&se=2021-01-09T20%3A57%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 20:59 UTC, opbld30 commented
Docs Build status updates of commit _[5ffc500](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5ffc5007093cc9fc6d9d5f22a0d1710a94cfa196)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-25cd1126)

<a id="25cd1126"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012092059221687-10432%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9LyhGz6zqfM2VRpJq2f5o7i8qPdpbc%2BDOXVXB5k4b1o%3D&st=2020-12-09T20%3A54%3A47Z&se=2021-01-09T20%3A59%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-15 15:01 UTC, closed without merging