Update throttling.md
microsoftgraph/microsoft-graph-docs pull request #10430
Opened 2020-10-26 18:29 UTC by lbrenne

Updated Limits for Assignments Service API

2020-10-26 18:30 UTC, opbld33 commented
Docs Build status updates of commit _[b74f63d](https://github.com/lbrenne/microsoft-graph-docs/commits/b74f63d08cd86ff08e2627e6ffd1b5a184df0f49)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-10430) | [Details](#user-content-c38f2dd7-2eddb2a0)

<a id="c38f2dd7-2eddb2a0"></a>
### [concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md)
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online`````
 - **Line 123, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalitem?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilephoto?view=graph-rest-1.0`````
 - **Line 470, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationassignment?view=graph-rest-beta`````
 - **Line 471, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationsubmission?view=graph-rest-beta`````
 - **Line 472, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationresource?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010261829269260-10430%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P8ZEDvf3RnUIlhwIDfja9rstc0HSToOdEfUtmEsuPYM%3D&st=2020-10-26T18%3A25%3A46Z&se=2020-11-26T18%3A30%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-27 01:49 UTC, opbld30 commented
Docs Build status updates of commit _[145ee9d](https://github.com/lbrenne/microsoft-graph-docs/commits/145ee9d7b839c4536d53754c0c4484485f3c16af)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-10430) | [Details](#user-content-c38f2dd7-a83c7452)

<a id="c38f2dd7-a83c7452"></a>
### [concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md)
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online`````
 - **Line 123, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalitem?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilephoto?view=graph-rest-1.0`````
 - **Line 470, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationassignment?view=graph-rest-beta`````
 - **Line 471, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationsubmission?view=graph-rest-beta`````
 - **Line 472, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationresource?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010270148022276-10430%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HdMegTmxUVKTGOurghp37ITh%2FA%2Bb17vZhUsLS3wQF0s%3D&st=2020-10-27T01%3A44%3A26Z&se=2020-11-27T01%3A49%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-27 12:48 UTC, baywet requested changes
@Lauragra thanks for adding me as a reviewer.

@lbrenne thanks for providing that additional information. I left a few comment for you to address.

2020-10-27 12:48 UTC, baywet commented on concepts/throttling.md
> +[educationResourc](/graph/api/resources/educationresource?view=graph-rest-beta)
```suggestion
[educationResource](/graph/api/resources/educationresource?view=graph-rest-beta)
```

2020-10-27 12:48 UTC, baywet commented on concepts/throttling.md
> +| Any         | 5K per 10 sec   | 15K per request per 10 sec |
```suggestion
| Any         | 5000 requests per 10 seconds   | 15 000 requests per 10 seconds |
```

2020-10-27 12:48 UTC, baywet commented on concepts/throttling.md
> +The following limits apply to requests on the assignment service beta API:
Add a section title

2020-10-27 12:48 UTC, baywet commented on concepts/throttling.md
> +
your changes need to be outside of the `<!-- { "blockType": "throttlinggenstart" } -->` tags as this section is generated automatically and will be overwritten.

2020-10-27 15:54 UTC, opbld32 commented
Docs Build status updates of commit _[84b0e23](https://github.com/lbrenne/microsoft-graph-docs/commits/84b0e23caebe968dfcefbe0f1e418db15b30b439)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-10430) | [Details](#user-content-c38f2dd7-fd177f27)

<a id="c38f2dd7-fd177f27"></a>
### [concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md)
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online`````
 - **Line 123, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalitem?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilephoto?view=graph-rest-1.0`````
 - **Line 470, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationassignment?view=graph-rest-beta`````
 - **Line 471, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationsubmission?view=graph-rest-beta`````
 - **Line 472, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationresource?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010271552485353-10430%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sNEvnUqkuPuOEavvAijvAyqJpcbetwqC%2BqlAUTBVyhM%3D&st=2020-10-27T15%3A49%3A08Z&se=2020-11-27T15%3A54%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-27 15:55 UTC, opbld32 commented
Docs Build status updates of commit _[036ba1c](https://github.com/lbrenne/microsoft-graph-docs/commits/036ba1c7e10cf499d45e47d4a1909efd5db57cd0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-10430) | [Details](#user-content-c38f2dd7-21693f49)

<a id="c38f2dd7-21693f49"></a>
### [concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md)
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online`````
 - **Line 123, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalitem?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilephoto?view=graph-rest-1.0`````
 - **Line 470, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationassignment?view=graph-rest-beta`````
 - **Line 471, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationsubmission?view=graph-rest-beta`````
 - **Line 472, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationresource?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010271553019798-10430%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MZz7wdCJFURNwgsu7e%2FvbShYGw32GhLBpx7X1%2FwfOMk%3D&st=2020-10-27T15%3A50%3A33Z&se=2020-11-27T15%3A55%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-27 16:10 UTC, opbld34 commented
Docs Build status updates of commit _[9e1d2a6](https://github.com/lbrenne/microsoft-graph-docs/commits/9e1d2a630a7f90ef16f6a9c6186e4efcd5fac7ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-10430) | [Details](#user-content-c38f2dd7-835f8b98)

<a id="c38f2dd7-835f8b98"></a>
### [concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md)
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online`````
 - **Line 123, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalitem?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilephoto?view=graph-rest-1.0`````
 - **Line 471, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationassignment?view=graph-rest-beta`````
 - **Line 472, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationsubmission?view=graph-rest-beta`````
 - **Line 473, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationresource?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010271608391748-10430%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iwfInQIUr27VD7KytvHNQ%2B%2BEr7ueNoqIjp5kinDTSTk%3D&st=2020-10-27T16%3A05%3A00Z&se=2020-11-27T16%3A10%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-27 17:18 UTC, baywet requested changes
thanks for making the updates, a few more comments. And the whole section still needs to be moved outside of the auto-generation tags

2020-10-27 17:18 UTC, baywet commented on concepts/throttling.md
> +| GET MeAssignment)  | 50 per 10 sec | 150 per 10 sec |
```suggestion
| GET MeAssignment  | 50 requests per 10 seconds | 150 requests per 10 seconds |  
```
The API path doesn't look right `MeAssignement`, could it be `me/assignments` or something else?

2020-10-27 17:18 UTC, baywet commented on concepts/throttling.md
> +The following limits apply to requests on the assignment service beta API:
```suggestion

The following limits apply to requests on the assignment service beta API:
```

2020-10-27 17:20 UTC, opbld30 commented
Docs Build status updates of commit _[445db21](https://github.com/lbrenne/microsoft-graph-docs/commits/445db2102387f6e38e1b51e8a0125ade07d4dd93)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-10430) | [Details](#user-content-c38f2dd7-813e4469)

<a id="c38f2dd7-813e4469"></a>
### [concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md)
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online`````
 - **Line 123, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalitem?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilephoto?view=graph-rest-1.0`````
 - **Line 471, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationassignment?view=graph-rest-beta`````
 - **Line 472, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationsubmission?view=graph-rest-beta`````
 - **Line 473, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationresource?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202010271719077620-10430%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nSdGKpPi0%2FkdAD8kFgNGvCB6w9QdSVhZwMexFlOhXJA%3D&st=2020-10-27T17%3A15%3A24Z&se=2020-11-27T17%3A20%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-05 17:38 UTC, davidmu1 approved these changes
I don't have anything to add that Laura hasn't already said.

2020-12-01 17:32 UTC, opbld32 commented
Docs Build status updates of commit _[09ee59a](https://github.com/lbrenne/microsoft-graph-docs/commits/09ee59a7a6514014331c42ba8b16a8cbdf136a17)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-10430) | [Details](#user-content-c38f2dd7-7c943601)

<a id="c38f2dd7-7c943601"></a>
### [concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md)
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online`````
 - **Line 123, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalitem?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilephoto?view=graph-rest-1.0`````
 - **Line 513, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationassignment?view=graph-rest-beta`````
 - **Line 514, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationsubmission?view=graph-rest-beta`````
 - **Line 515, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationresource?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012011730210006-10430%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VyCM9xjLPsQIo3o7hEvc3QfyHqSMQ46MVDgkLDcWm0s%3D&st=2020-12-01T17%3A27%3A34Z&se=2021-01-01T17%3A32%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-01 19:48 UTC, baywet requested changes

2020-12-01 19:48 UTC, baywet commented on concepts/throttling.md
> +
```suggestion
```

2020-12-01 19:48 UTC, baywet commented on concepts/throttling.md
> +
```suggestion
```

2020-12-01 19:48 UTC, baywet approved these changes

2020-12-01 19:49 UTC, opbld34 commented
Docs Build status updates of commit _[640c675](https://github.com/lbrenne/microsoft-graph-docs/commits/640c675bbe0c2ec7dcaf09c85d53a3f2bf981979)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-10430) | [Details](#user-content-c38f2dd7-3ad765b6)

<a id="c38f2dd7-3ad765b6"></a>
### [concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md)
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online`````
 - **Line 123, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalitem?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilephoto?view=graph-rest-1.0`````
 - **Line 511, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationassignment?view=graph-rest-beta`````
 - **Line 512, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationsubmission?view=graph-rest-beta`````
 - **Line 513, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationresource?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012011948428240-10430%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UfAIZtTl%2BNFrfayGIhJuat43pXqrh%2BGiZTkKPGeHkUg%3D&st=2020-12-01T19%3A44%3A56Z&se=2021-01-01T19%3A49%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-01 19:50 UTC, baywet requested changes

2020-12-01 19:50 UTC, baywet commented on concepts/throttling.md
> +The following limits apply to requests on the assignment service beta API:
```suggestion

The following limits apply to requests on the assignment service beta API:
```

2020-12-01 19:50 UTC, baywet commented on concepts/throttling.md
> +| GET me/Assignment)  | 50 requests per 10 seconds | 150 requests per 10 seconds |
```suggestion
| GET me/Assignment  | 50 requests per 10 seconds | 150 requests per 10 seconds |  
```

2020-12-01 19:51 UTC, baywet approved these changes

2020-12-01 19:52 UTC, opbld32 commented
Docs Build status updates of commit _[04b5cfc](https://github.com/lbrenne/microsoft-graph-docs/commits/04b5cfc7f879340090510fc9f9906700388f7b1b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-10430) | [Details](#user-content-c38f2dd7-5fef4fa5)

<a id="c38f2dd7-5fef4fa5"></a>
### [concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md)
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online`````
 - **Line 123, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalitem?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilephoto?view=graph-rest-1.0`````
 - **Line 512, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationassignment?view=graph-rest-beta`````
 - **Line 513, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationsubmission?view=graph-rest-beta`````
 - **Line 514, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationresource?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012011950440567-10430%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=otnBaL%2BcbyBYvyMQUyhDTg19HV%2F8jRVyT7hhOx%2B7UIs%3D&st=2020-12-01T19%3A47%3A40Z&se=2021-01-01T19%3A52%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-01 19:55 UTC, baywet commented
@lbrenne Thanks for making the changes. I've tagged the pull request to be merged.

2020-12-01 19:56 UTC, opbld31 commented
Docs Build status updates of commit _[dc8b006](https://github.com/lbrenne/microsoft-graph-docs/commits/dc8b0065f0d7520612b5d92bf1c41143263e68b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-10430) | [Details](#user-content-c38f2dd7-e34b0278)

<a id="c38f2dd7-e34b0278"></a>
### [concepts/throttling.md](https://github.com/lbrenne/microsoft-graph-docs/blob/patch-1/concepts/throttling.md)
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online`````
 - **Line 123, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalitem?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilephoto?view=graph-rest-1.0`````
 - **Line 512, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationassignment?view=graph-rest-beta`````
 - **Line 513, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationsubmission?view=graph-rest-beta`````
 - **Line 514, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationresource?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012011955192870-10430%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tqlcSvOhl548WIcX5uazFGWEirpz0RzQGmdhJcoiVWg%3D&st=2020-12-01T19%3A51%3A26Z&se=2021-01-01T19%3A56%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-02 03:06 UTC, merged