Add print task definition resource to graph webhook docs
microsoftgraph/microsoft-graph-docs pull request #10477
Opened 2020-10-29 19:14 UTC by jahsu-MSFT

2020-10-29 19:15 UTC, opbld30 commented
Docs Build status updates of commit _[270d2d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/270d2d0fca8587459dc2d445ff55899e89297521)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-69825fde-6b02fca1)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-8f8d1d71-6b02fca1)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-a8c89eee-6b02fca1)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-409b84f8-6b02fca1)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-6e0d0a83-6b02fca1)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10477) | [Details](#user-content-de0bbbbb-6b02fca1)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10477) | [Details](#user-content-8c54aee1-6b02fca1)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) |

<a id="69825fde-6b02fca1"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-6b02fca1"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-6b02fca1"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-6b02fca1"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-6b02fca1"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="de0bbbbb-6b02fca1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to  [...]

2020-10-29 19:16 UTC, baywet commented on api-reference/beta/api/subscription-delete.md
> +|[printTaskDefinition](../resources/printtaskdefinition.md) | Not supported | Not supported | PrintTaskDefinition.ReadWrite.All |
can you move this line so objects read in alphabetical order please?

2020-10-29 19:47 UTC, opbld30 commented
Docs Build status updates of commit _[6b0be37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b0be37b33f65cc8add05f344f9034d68195ce01)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-69825fde-9df3517b)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-8f8d1d71-9df3517b)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-a8c89eee-9df3517b)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-409b84f8-9df3517b)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-6e0d0a83-9df3517b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10477) | [Details](#user-content-de0bbbbb-9df3517b)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10477) | [Details](#user-content-8c54aee1-9df3517b)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) |

<a id="69825fde-9df3517b"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-9df3517b"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-9df3517b"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-9df3517b"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-9df3517b"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="de0bbbbb-9df3517b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to  [...]

2020-10-29 20:08 UTC, baywet approved these changes

2020-10-29 20:27 UTC, jahsu-MSFT commented
Please don't merge this PR yet until the end of next week when all the updates are deployed.

2020-10-29 20:44 UTC, baywet commented
I don't have merge permissions on this repo :)
I've added the "do not merge" tag. Once you're ready to merge, remove that tag and add the "ready to merge" one instead.

2020-10-29 20:46 UTC, jahsu-MSFT commented
> I don't have merge permissions on this repo :)
> I've added the "do not merge" tag. Once you're ready to merge, remove that tag and add the "ready to merge" one instead.

Wasn't aware of this tag. That sounds great. Thanks!

2020-10-29 23:44 UTC, Lauragra commented
@jahsu-MSFT , please set the ***ready to merge** label on the PR when you're ready.

2020-10-30 03:03 UTC, jahsu-MSFT commented
> @jahsu-MSFT , please set the ***ready to merge** label on the PR when you're ready.

Will do! Thanks for the note.

2020-10-30 16:11 UTC, baywet requested changes
I just noticed you forgot to fill in the max expiration time https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-type

2020-10-30 16:15 UTC, jahsu-MSFT commented
> I just noticed you forgot to fill in the max expiration time https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-type

@baywet Thought I did. It's in the subscription.md file right? | Print **printTaskDefinition** | 4230 minutes (under 3 days)    |

2020-10-30 16:48 UTC, baywet commented
@jahsu-MSFT right, sorry I missed it cross checking with the checklist

2020-10-30 16:48 UTC, baywet approved these changes

2020-11-02 03:18 UTC, andrewchoi5 approved these changes

2020-11-05 12:53 UTC, opbld32 commented
Docs Build status updates of commit _[f92cba2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f92cba2bad0297867d1a8b1fac083a8ebb597138)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-69825fde-100955f6)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-8f8d1d71-100955f6)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-a8c89eee-100955f6)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-409b84f8-100955f6)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-6e0d0a83-100955f6)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10477) | [Details](#user-content-de0bbbbb-100955f6)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10477) | [Details](#user-content-8c54aee1-100955f6)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) |

<a id="69825fde-100955f6"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-100955f6"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-100955f6"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-100955f6"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-100955f6"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="de0bbbbb-100955f6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to  [...]

2020-11-05 16:36 UTC, jahsu-MSFT commented
@baywet Thanks for fixing the conflicts! @Lauragra The latest changes are deployed to prod and this PR is now ready to be merged in. 
Thanks,

2020-11-05 19:51 UTC, opbld31 commented
Docs Build status updates of commit _[062286e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/062286e58521a4efad5acd2e012232b3e6247bd2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-69825fde-f74f8a23)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-8f8d1d71-f74f8a23)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-a8c89eee-f74f8a23)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-409b84f8-f74f8a23)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-6e0d0a83-f74f8a23)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10477) | [Details](#user-content-de0bbbbb-f74f8a23)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10477) | [Details](#user-content-8c54aee1-f74f8a23)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="69825fde-f74f8a23"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-f74f8a23"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-f74f8a23"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-f74f8a23"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-f74f8a23"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="de0bbbbb-f74f8a23"></a>
### [concepts/ch [...]

2020-11-05 20:08 UTC, opbld32 commented
Docs Build status updates of commit _[8a81f40](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a81f40e296b13bde83f662a5426ad5649fbff9a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-69825fde-5ba8cd0a)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-8f8d1d71-5ba8cd0a)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-a8c89eee-5ba8cd0a)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-409b84f8-5ba8cd0a)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-6e0d0a83-5ba8cd0a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10477) | [Details](#user-content-de0bbbbb-5ba8cd0a)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10477) | [Details](#user-content-8c54aee1-5ba8cd0a)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="69825fde-5ba8cd0a"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-5ba8cd0a"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-5ba8cd0a"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-5ba8cd0a"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-5ba8cd0a"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="de0bbbbb-5ba8cd0a"></a>
### [concepts/ch [...]

2020-11-05 22:26 UTC, opbld34 commented
Docs Build status updates of commit _[229cb5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/229cb5a1bc6ce726c47207d28a1132fe1372a54d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-69825fde-ff8702f2)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-8f8d1d71-ff8702f2)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-a8c89eee-ff8702f2)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-409b84f8-ff8702f2)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-6e0d0a83-ff8702f2)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10477) | [Details](#user-content-de0bbbbb-ff8702f2)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10477) | [Details](#user-content-8c54aee1-ff8702f2)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="69825fde-ff8702f2"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-ff8702f2"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-ff8702f2"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-ff8702f2"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-ff8702f2"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="de0bbbbb-ff8702f2"></a>
### [concepts/ch [...]

2020-11-05 22:29 UTC, opbld30 commented
Docs Build status updates of commit _[07d9d1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/07d9d1be0df6e4647ac3b150056a1befdef3ebd3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-69825fde-c6ab9b12)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-8f8d1d71-c6ab9b12)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-a8c89eee-c6ab9b12)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-409b84f8-c6ab9b12)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-6e0d0a83-c6ab9b12)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10477) | [Details](#user-content-de0bbbbb-c6ab9b12)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10477) | [Details](#user-content-8c54aee1-c6ab9b12)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="69825fde-c6ab9b12"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-c6ab9b12"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-c6ab9b12"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-c6ab9b12"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-c6ab9b12"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="de0bbbbb-c6ab9b12"></a>
### [concepts/ch [...]

2020-11-05 22:30 UTC, opbld32 commented
Docs Build status updates of commit _[887ff23](https://github.com/microsoftgraph/microsoft-graph-docs/commits/887ff2357bbf4769c38445ff8494f6712a82a16d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-69825fde-d34a7a75)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-8f8d1d71-d34a7a75)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-a8c89eee-d34a7a75)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-409b84f8-d34a7a75)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-6e0d0a83-d34a7a75)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10477) | [Details](#user-content-de0bbbbb-d34a7a75)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10477) | [Details](#user-content-8c54aee1-d34a7a75)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="69825fde-d34a7a75"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-d34a7a75"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-d34a7a75"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-d34a7a75"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-d34a7a75"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="de0bbbbb-d34a7a75"></a>
### [concepts/ch [...]

2020-11-05 22:31 UTC, Lauragra approved these changes

2020-11-05 22:31 UTC, opbld33 commented
Docs Build status updates of commit _[56b3f57](https://github.com/microsoftgraph/microsoft-graph-docs/commits/56b3f5756ecd4973ee398882d30ae98ba2b90781)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-69825fde-817cf0f0)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-8f8d1d71-817cf0f0)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-a8c89eee-817cf0f0)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-409b84f8-817cf0f0)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) | [Details](#user-content-6e0d0a83-817cf0f0)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10477) | [Details](#user-content-de0bbbbb-817cf0f0)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10477) | [Details](#user-content-8c54aee1-817cf0f0)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10477) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="69825fde-817cf0f0"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-817cf0f0"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-817cf0f0"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-817cf0f0"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-817cf0f0"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-printTaskDefinition-resource-to-webhook-notification/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="de0bbbbb-817cf0f0"></a>
### [concepts/ch [...]

2020-11-05 22:34 UTC, merged