update docs related to GET / chats and chatType enum
microsoftgraph/microsoft-graph-docs pull request #10526
Opened 2020-11-04 00:55 UTC by bhartono

update docs related to GET / chats and chatType enum

2020-11-04 00:56 UTC, opbld34 commented
Docs Build status updates of commit _[7dfbde8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7dfbde8fbe847c2a622258c5f9ef805c9813578d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10526) | [Details](#user-content-de0bbbbb-03f2037b)
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/api-reference/beta/api/chat-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10526) (graph-rest-beta) | [Details](#user-content-84894718-03f2037b)
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/api-reference/beta/api/user-list-chats.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-chats?view=graph-rest-beta&branch=pr-en-us-10526) (graph-rest-beta) | [Details](#user-content-4823f9d1-03f2037b)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10526) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10526) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10526) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-03f2037b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/concepts/changelog.md)
 - **Line 22, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specif [...]

2020-11-04 00:59 UTC, AkJo commented on api-reference/beta/resources/enums.md
> +
Please add another column and call out what these values mean.

2020-11-04 01:05 UTC, opbld31 commented
Docs Build status updates of commit _[62a4dc3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62a4dc3434a25c60ec9f0ac1b795307234d30006)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10526) | [Details](#user-content-de0bbbbb-7f37e015)
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/api-reference/beta/api/chat-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10526) (graph-rest-beta) | [Details](#user-content-84894718-7f37e015)
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/api-reference/beta/api/user-list-chats.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-chats?view=graph-rest-beta&branch=pr-en-us-10526) (graph-rest-beta) | [Details](#user-content-4823f9d1-7f37e015)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10526) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10526) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10526) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-7f37e015"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/concepts/changelog.md)
 - **Line 22, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specif [...]

2020-11-04 01:12 UTC, opbld32 commented
Docs Build status updates of commit _[000d8fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/000d8fe8258d12c287f299404691696b3b5ca174)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10526) | [Details](#user-content-de0bbbbb-888a419b)
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/api-reference/beta/api/chat-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10526) (graph-rest-beta) | [Details](#user-content-84894718-888a419b)
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/api-reference/beta/api/user-list-chats.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-chats?view=graph-rest-beta&branch=pr-en-us-10526) (graph-rest-beta) | [Details](#user-content-4823f9d1-888a419b)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10526) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10526) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10526) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-888a419b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatType/concepts/changelog.md)
 - **Line 22, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-v1.0`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 31, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/message?view=graph-rest-1.0`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/meetingParticipantInfo?view=graph-rest-beta`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyprinter-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getprinterarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyprinter.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printusagesummarybyuser-get.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getuserarchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reports-getgrouparchivedprintjobs.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-dailyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 53, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/reportroot-list-monthlyprintusagesummariesbyuser.md?view=graph-rest-beta`````
 - **Line 54, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printdocument-createuploadsession?view=graph-rest-beta`````
 - **Line 57, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specif [...]

2020-11-04 23:00 UTC, RamjotSingh requested changes

2020-12-04 01:16 UTC, bhartono commented on api-reference/beta/resources/chat.md
>  | lastUpdatedDateTime| dateTimeOffset|  Date and time at which the chat was renamed or membership changed. lastUpdatedDateTime is not updated when a message is sent to the chat. Read-only.|
removed

2020-12-04 01:19 UTC, bhartono commented on api-reference/beta/resources/enums.md
> +|unknownFutureValue  | 3     | A sentinel member.                                                                                                                                           |
removed

2021-02-03 21:22 UTC, closed without merging