added transitive managers operation
microsoftgraph/microsoft-graph-docs pull request #10528
Opened 2020-11-04 01:44 UTC by Licantrop0

2020-11-04 01:45 UTC, opbld34 commented
Docs Build status updates of commit _[3337dd1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3337dd17b72e190742f8264c94e0890bcea3d988)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Licantrop0/transitiveManagers/api-reference/v1.0/api/user-list-manager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&branch=pr-en-us-10528) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011040144051311-10528%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HGJjHlqoOisBoTv%2B7%2FPMMegdOWrFJgRBnFFMAGJkggY%3D&st=2020-11-04T01%3A40%3A14Z&se=2020-12-05T01%3A45%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-04 01:47 UTC, opbld33 commented
Docs Build status updates of commit _[fbb82d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fbb82d927384f28a10b2ef8ec2bf5fdee7757cab)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Licantrop0/transitiveManagers/api-reference/v1.0/api/user-list-manager.md) | :x:Error | | [Details](#user-content-6bd82562-6078a13e)

<a id="6bd82562-6078a13e"></a>
### [api-reference/v1.0/api/user-list-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Licantrop0/transitiveManagers/api-reference/v1.0/api/user-list-manager.md)
 - **Line 134, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-transitive-manager-csharp-snippets.md'.`````
 - **Line 138, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-transitive-manager-javascript-snippets.md'.`````
 - **Line 142, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-transitive-manager-objc-snippets.md'.`````
 - **Line 146, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-transitive-manager-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011040146134558-10528%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7UIlNTbNsNqvFn6p37c9RQbX9bKrnIoixbCyRfRKBSo%3D&st=2020-11-04T01%3A42%3A12Z&se=2020-12-05T01%3A47%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-05 01:56 UTC, Lauragra commented on api-reference/v1.0/api/user-list-manager.md
> +GET /me?$expand=manager($levels=max)
The title and file name of this operation is List, but the operation is a GET. Should we update the title/file name?

2020-11-05 02:04 UTC, Lauragra commented on api-reference/v1.0/api/user-list-manager.md
> +GET /users/{id | userPrincipalName}/?$expand=manager($levels=max)
For the expand scenarios, you might want a separate HTTP block that you introduce to explain that that syntax expands the manager's chain.

2020-11-05 02:08 UTC, Lauragra commented on api-reference/v1.0/api/user-list-manager.md
> +- `?$expand=manager($levels=max)` QueryString parameter
This is a little bit confusing; it appears to be saying that the expanding the manager requires the expand manager parameter? Do you mean something like "If your request includes the `$expand` parameter to get the manager's chain, you must also include the following:" Then also show an example of the full $expand parameter syntax.

2020-11-05 02:11 UTC, Lauragra commented on api-reference/v1.0/api/user-list-manager.md
> +##### Get Manager Request
When we include multiple examples, we make each example an H3 (###) and we preface with Example 1:, Example 2: and so on. The Request and Response headers are H4s (####).

2020-11-05 02:12 UTC, Lauragra commented on api-reference/v1.0/api/user-list-manager.md
> +| ConsistencyLevel | eventual. Needed only for `$expand` with `$levels=max` |
Revised the description as: 'Eventual. Required when the request includes the `expand` parameter."

2020-11-05 02:14 UTC, Lauragra commented on api-reference/v1.0/api/user-list-manager.md
> +##### Get Transitive Managers Request
For the H3 here, suggest: "Example 2: Get manager chain up to the root level".

2020-11-05 02:15 UTC, Lauragra commented on api-reference/v1.0/api/user-list-manager.md
> +GET https://graph.microsoft.com/v1.0/me?$expand=manager($levels=max;$select=id,displayName)&$select=id,displayName&$count=true
This example doesn't show the ConsistencyLevel header.

2020-11-05 02:15 UTC, Lauragra commented on api-reference/v1.0/api/user-list-manager.md
> +# [C#](#tab/csharp)
Remove the snippet links; for new requests, the snippets will get created via the snippet generation automation. Also remove the HTTP H1.

2020-11-05 02:16 UTC, Lauragra requested changes
Please see editorial comments. Also, we'll need to make the same updates to the beta version of this topic.

2020-11-05 17:39 UTC, davidmu1 reviewed
I don't have anything to add in addition to what Laura has pointed out.

2020-11-09 22:59 UTC, opbld34 commented
Docs Build status updates of commit _[2ccf2a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ccf2a30b1664609789853637738c107aad31edb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Licantrop0/transitiveManagers/api-reference/v1.0/api/user-list-manager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&branch=pr-en-us-10528) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011092257519052-10528%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U9KHVdLxYc6fWv4q4ZT5U9ZmjN%2FpNyJcyrS2X%2B0Rmf8%3D&st=2020-11-09T22%3A54%3A16Z&se=2020-12-10T22%3A59%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 02:29 UTC, Lauragra commented on api-reference/v1.0/api/user-list-manager.md
> +Returns the user or organizational contact assigned as the user's manager. Optionally, you can expand the manager's chain up to the root node.
This PR updates the v1.0 version of the topic. Please apply the same updates to the beta version of the topic as well.

2020-11-10 02:29 UTC, Lauragra requested changes
We need to make the same updates to the beta topic.

2020-11-10 02:29 UTC, opbld32 commented
Docs Build status updates of commit _[b80978b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b80978bad3fa2b27c7e20478df00ca77d23d32a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/user-list-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Licantrop0/transitiveManagers/api-reference/v1.0/api/user-list-manager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&branch=pr-en-us-10528) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011100228351147-10528%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Kvokgkeu6qbaKZfl0WeRhOPVfPcM9vw9meKolLf1EhI%3D&st=2020-11-10T02%3A24%3A45Z&se=2020-12-11T02%3A29%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-11 23:46 UTC, opbld31 commented
Docs Build status updates of commit _[9613ca6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9613ca6af88930e0b4e8f0ad84cfd65502e69a2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Licantrop0/transitiveManagers/api-reference/beta/api/user-list-manager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-beta&branch=pr-en-us-10528) (graph-rest-beta) |
[api-reference/v1.0/api/user-list-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Licantrop0/transitiveManagers/api-reference/v1.0/api/user-list-manager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&branch=pr-en-us-10528) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011112345402845-10528%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Fb5C3BWjaHTbNlaVd98bctVlBtZwGhx3JOc1ieNy3E8%3D&st=2020-11-11T23%3A41%3A57Z&se=2020-12-12T23%3A46%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-11 23:51 UTC, opbld34 commented
Docs Build status updates of commit _[c28a85e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c28a85e184f60add42e227b9c77569ae4a6154a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Licantrop0/transitiveManagers/api-reference/beta/api/user-list-manager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-beta&branch=pr-en-us-10528) (graph-rest-beta) |
[api-reference/v1.0/api/user-list-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Licantrop0/transitiveManagers/api-reference/v1.0/api/user-list-manager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&branch=pr-en-us-10528) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011112349460979-10528%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FJw%2F3JqcDDM3Vkbgu3WFYVQQYMo%2By1jK40DR8Drv6uc%3D&st=2020-11-11T23%3A46%3A01Z&se=2020-12-12T23%3A51%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 22:12 UTC, opbld31 commented
Docs Build status updates of commit _[e4e2422](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4e2422125734359889b6ebdb43af0253ebcb5aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Licantrop0/transitiveManagers/api-reference/beta/api/user-list-manager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-beta&branch=pr-en-us-10528) (graph-rest-beta) |
[api-reference/v1.0/api/user-list-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Licantrop0/transitiveManagers/api-reference/v1.0/api/user-list-manager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&branch=pr-en-us-10528) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011132210419266-10528%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nF8GFuYiMiB4T9ikw%2BXZQuwMLCDmdCvTu1G7cmI%2FNnQ%3D&st=2020-11-13T22%3A07%3A00Z&se=2020-12-14T22%3A12%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 22:12 UTC, Lauragra approved these changes

2020-11-13 22:16 UTC, Lauragra commented
@Licantrop0 , please address the API Doctor errors:
Error: get_manager:
      Missing properties: response was missing these required properties: aboutMe, accountEnabled, ageGroup, assignedLicenses, assignedPlans, birthday, businessPhones, city, companyName, consentProvidedForMinor, country, createdDateTime, creationType, department, employeeHireDate, employeeId, employeeOrgData, employeeType, faxNumber, givenName, hireDate, identities, imAddresses, interests, isResourceAccount, legalAgeGroupClassification, licenseAssignmentStates, lastPasswordChangeDateTime, mailboxSettings, mailNickname, mobilePhone, mySite, officeLocation, onPremisesDistinguishedName, onPremisesDomainName, onPremisesExtensionAttributes, onPremisesImmutableId, onPremisesLastSyncDateTime, onPremisesProvisioningErrors, onPremisesSamAccountName, onPremisesSecurityIdentifier, onPremisesSyncEnabled, onPremisesUserPrincipalName, otherMails, passwordPolicies, passwordProfile, pastProjects, postalCode, preferredLanguage, preferredName, provisionedPlans, proxyAddresses, responsibilities, schools, showInAddressList, signInSessionsValidFromDateTime, skills, state, streetAddress, surname, usageLocation, userType, drives, inferenceClassification, outlook

  Error: get_transitive_managers:
      Missing properties: response was missing these required properties: aboutMe, accountEnabled, ageGroup, assignedLicenses, assignedPlans, birthday, businessPhones, city, companyName, consentProvidedForMinor, country, createdDateTime, creationType, department, employeeHireDate, employeeId, employeeOrgData, employeeType, faxNumber, givenName, hireDate, identities, imAddresses, interests, isResourceAccount, jobTitle, legalAgeGroupClassification, licenseAssignmentStates, lastPasswordChangeDateTime, mail, mailboxSettings, mailNickname, mobilePhone, mySite, officeLocation, onPremisesDistinguishedName, onPremisesDomainName, onPremisesExtensionAttributes, onPremisesImmutableId, onPremisesLastSyncDateTime, onPremisesProvisioningErrors, onPremisesSamAccountName, onPremisesSecurityIdentifier, onPremisesSyncEnabled, onPremisesUserPrincipalName, otherMails, passwordPolicies, passwordProfile, pastProjects, postalCode, preferredLanguage, preferredName, provisionedPlans, proxyAddresses, responsibilities, schools, showInAddressList, signInSessionsValidFromDateTime, skills, state, streetAddress, surname, usageLocation, userPrincipalName, userType, drives, inferenceClassification, outlook

2020-11-16 18:40 UTC, finsharp commented on api-reference/beta/api/user-list-manager.md
> +  "truncated": false,
@Licantrop0 This response is marked as ` "truncated": false` yet from the json object below, its truncated. Was your intention to put a truncated response object?

2020-11-16 18:40 UTC, finsharp commented on api-reference/beta/api/user-list-manager.md
> +  "truncated": false,
@Licantrop0 Similar to the above comment on response truncation.

2020-11-16 19:02 UTC, opbld30 commented
Docs Build status updates of commit _[b7a61f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b7a61f34d13973b289ab8cea6ce0509b99d1291a)_: 

:clock10: **Pending**: waiting for processors ([23](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 23 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-16 19:08 UTC, opbld31 commented
Docs Build status updates of commit _[b7a61f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b7a61f34d13973b289ab8cea6ce0509b99d1291a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/user-list-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Licantrop0/transitiveManagers/api-reference/beta/api/user-list-manager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-beta&branch=pr-en-us-10528) (graph-rest-beta) |
[api-reference/v1.0/api/user-list-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Licantrop0/transitiveManagers/api-reference/v1.0/api/user-list-manager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&branch=pr-en-us-10528) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011161902141073-10528%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=L5mb7dGJCZfp%2BHS0tSXFJ4T5073iEcxOPigSlBDhclc%3D&st=2020-11-16T19%3A03%3A22Z&se=2020-12-17T19%3A08%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 19:12 UTC, merged