Mgt/localization + right-to-left
microsoftgraph/microsoft-graph-docs pull request #10569
Opened 2020-11-06 19:22 UTC by vogtn

Documentation for the Microsoft Graph Toolkit "Localization" section. 

includes: 

-Localization implementation and use
-Right-to-left implementation and use

2020-11-06 19:23 UTC, opbld33 commented
Docs Build status updates of commit _[3e0367b](https://github.com/vogtn/microsoft-graph-docs/commits/3e0367b6b1bfa05a94f9898ea1313a82c5daf11d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/localization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) | [Details](#user-content-b101a270-1a580256)

<a id="b101a270-1a580256"></a>
### [concepts/toolkit/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/localization.md)
 - **Line 100, Column 1**: **[Warning-file-not-found]** `````Invalid file link: './images/rightToLeft.png'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011061922274091-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pQDw2vWXh4MEIougid8UsUcAWdyI8MYuHQt9Ls6YYgI%3D&st=2020-11-06T19%3A18%3A37Z&se=2020-12-07T19%3A23%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-06 19:25 UTC, opbld31 commented
Docs Build status updates of commit _[392aa31](https://github.com/vogtn/microsoft-graph-docs/commits/392aa31ebd9bb72519ea82604e45e3bdf734f064)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/images/rightToLeft.png](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/images/rightToLeft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |
[concepts/toolkit/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011061924128394-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hl39e04Y3FHnKMGcf09g2yXhxuoEWfl%2B2cEYUVx8C84%3D&st=2020-11-06T19%3A20%3A29Z&se=2020-12-07T19%3A25%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 05:28 UTC, nmetulev requested changes
Right to Left should be part of a separate page - it does different than localization

Make sure to add the new pages in the TOC so they show up in the navigation

2020-11-13 05:28 UTC, nmetulev commented on concepts/toolkit/localization.md
> +
Move this down after the example on how localization works and lead in with an overview of Localization and why it's important.

2020-11-13 05:28 UTC, nmetulev commented on concepts/toolkit/localization.md
> +  import { LocalizationHelper } from "./packages/mgt/dist/es6/index.js";
Think about how an external developer would import the toolkit, not how we import it for testing

```suggestion
  import { LocalizationHelper } from "@microsoft/mgt";
```

2020-11-13 05:28 UTC, nmetulev commented on concepts/toolkit/localization.md
> +<script type="module">
I think you can remove the script tags, they don't add anything to the example

2020-11-16 22:13 UTC, opbld30 commented
Docs Build status updates of commit _[9465394](https://github.com/vogtn/microsoft-graph-docs/commits/94653949ffa319859c2f4db1cc1e8221a935f7e0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a4e2f1b0)

<a id="a4e2f1b0"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011162212361867-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gTuTmZd6n2RHnGqJvMiUWIUQa9oXHZKpoUydB38vTSo%3D&st=2020-11-16T22%3A07%3A59Z&se=2020-12-17T22%3A12%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 22:13 UTC, vogtn commented on concepts/toolkit/localization.md
> +<script type="module">
Removed:
9465394

Only thing, it removes some of the highlighting on the object inside the code block.

2020-11-16 22:13 UTC, vogtn commented on concepts/toolkit/localization.md
> +  import { LocalizationHelper } from "./packages/mgt/dist/es6/index.js";
Good point, updated: 

9465394

2020-11-16 22:16 UTC, opbld30 commented
Docs Build status updates of commit _[0a72a86](https://github.com/vogtn/microsoft-graph-docs/commits/0a72a865f601832dbdd5298f3324eed8ba1a47f0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) | [Details](#user-content-348d3da9-8eff84d7)
[concepts/toc.yml](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |
[concepts/toolkit/images/rightToLeft.png](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/images/rightToLeft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) |
[concepts/toolkit/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |

<a id="348d3da9-8eff84d7"></a>
### [concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011162215077364-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7dPRM4FUkk9CgKMzq0GEGGoKJYLu4IOj6kNLh9WVzbk%3D&st=2020-11-16T22%3A11%3A24Z&se=2020-12-17T22%3A16%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 22:16 UTC, vogtn commented on concepts/toolkit/localization.md
> +
Wrote a short intro here:
9465394

I tried to base it on this context:
https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/localization

2020-11-17 17:42 UTC, nmetulev requested changes

2020-11-17 17:42 UTC, nmetulev commented on concepts/toolkit/localization.md
> +To access the LocalizationHelper you must import the module from the package and utilze the `string` property.
```suggestion
## Use LocalizationHelper to add localized strings

All strings in the toolkit are not localized, but you can provide your own localized strings and manage different languages through the same process you use for localizing your app. To facilitate localization, the toolkit exposes the `LocalizationHelper` static class:
```

2020-11-17 17:42 UTC, nmetulev commented on concepts/toolkit/localization.md
> +# Localizing the Microsoft Graph Toolkit
```suggestion
# Localizing the Microsoft Graph Toolkit Components
```

2020-11-17 17:42 UTC, nmetulev commented on concepts/toolkit/localization.md
> +## Localizating components in the Microsoft Graph Toolkit
Instead of this section, what if we list all strings for all components. For examples

## Strings

### Agenda

```ts
{
  "key": "value",
  "key": "value
}
```

### People Picker

```ts
{
  "key": "value",
  "key": "value
}
```

2020-11-17 17:42 UTC, nmetulev commented on concepts/toolkit/localization.md
> +title: "Localizing the Microsoft Graph Toolkit"
```suggestion
title: "Localizing the Microsoft Graph Toolkit Components"
```

2020-11-17 17:42 UTC, nmetulev commented on concepts/toolkit/localization.md
> +description: "Use LocalizationHelper to translate component strings"
```suggestion
description: "Use LocalizationHelper to localize Microsoft Graph Toolkit Components"
```

2020-11-17 17:42 UTC, nmetulev commented on concepts/toolkit/localization.md
> +The Microsoft Graph Toolkit components can localize designated strings so the user-interface reflects the desiered linguistic experience.
```suggestion
The Microsoft Graph Toolkit components can be localized so the user-interface reflects the desired linguistic experience.
```

2020-11-17 17:42 UTC, nmetulev commented on concepts/toolkit/right-to-left.md
> +
This is an internal implementation of `ltr` and I don't think it's necessary. I think you can just explain that the developer will need to set the direction on the `body` or `html` element, and the components will pick it up. This doc doesn't need to be long.

2020-11-17 17:42 UTC, nmetulev commented on concepts/toolkit/right-to-left.md
> +description: "Use LocalizationHelper to change direction"
```suggestion
description: "Right-to-left (rtl) support in the Microsoft Graph Toolkit components"
```

2020-11-17 17:42 UTC, nmetulev commented on concepts/toolkit/right-to-left.md
> +title: "Right-To-Left Support with the Microsoft Graph Toolkit"
```suggestion
title: "Right-to-left (rtl) support with the Microsoft Graph Toolkit"
```

2020-11-17 17:42 UTC, nmetulev commented on concepts/toolkit/right-to-left.md
> +## Right to Left
```suggestion
## Display Microsoft Graph Toolkit components right-to-left (rtl)
```

2020-11-17 22:08 UTC, opbld30 commented
Docs Build status updates of commit _[3e0686d](https://github.com/vogtn/microsoft-graph-docs/commits/3e0686d648116a8d34f03438e49cac63a47836f9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) | [Details](#user-content-348d3da9-96af54c3)
[concepts/toc.yml](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |
[concepts/toolkit/images/rightToLeft.png](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/images/rightToLeft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) |
[concepts/toolkit/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |

<a id="348d3da9-96af54c3"></a>
### [concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172207143149-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BenXI51kfYZ96WtRXkcOipM4gtO%2FUcIY8NXBCxws8as%3D&st=2020-11-17T22%3A03%3A29Z&se=2020-12-18T22%3A08%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 22:09 UTC, opbld31 commented
Docs Build status updates of commit _[1081971](https://github.com/vogtn/microsoft-graph-docs/commits/108197152dbe95209812a57214417c4c28bfbb14)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) | [Details](#user-content-348d3da9-f5d9af99)
[concepts/toc.yml](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |
[concepts/toolkit/images/rightToLeft.png](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/images/rightToLeft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) |
[concepts/toolkit/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |

<a id="348d3da9-f5d9af99"></a>
### [concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172207389717-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fRAZ9dQQRSeGKaJcTWhKShd4pv%2Fgw679%2FQXZ4QWcXpM%3D&st=2020-11-17T22%3A04%3A49Z&se=2020-12-18T22%3A09%3A49Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 22:22 UTC, vogtn commented on concepts/toolkit/localization.md
> +## Localizating components in the Microsoft Graph Toolkit
Thanks great suggestion!

2020-11-17 22:22 UTC, opbld33 commented
Docs Build status updates of commit _[57194b2](https://github.com/vogtn/microsoft-graph-docs/commits/57194b2c3aa2abe2c4f6f30bb887afe3870e640f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) | [Details](#user-content-348d3da9-ffda73a7)
[concepts/toc.yml](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |
[concepts/toolkit/images/rightToLeft.png](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/images/rightToLeft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) |
[concepts/toolkit/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |

<a id="348d3da9-ffda73a7"></a>
### [concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172221003927-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DBqcrkysW1TW%2BQ98yA8VyvqxL8ygq7v8aB5B0mqftVY%3D&st=2020-11-17T22%3A17%3A30Z&se=2020-12-18T22%3A22%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 22:23 UTC, opbld32 commented
Docs Build status updates of commit _[1aa8309](https://github.com/vogtn/microsoft-graph-docs/commits/1aa8309f11ae820c88b1ec746ae29bf55df19c24)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) | [Details](#user-content-348d3da9-a4de2c7a)
[concepts/toc.yml](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |
[concepts/toolkit/images/rightToLeft.png](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/images/rightToLeft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) |
[concepts/toolkit/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |

<a id="348d3da9-a4de2c7a"></a>
### [concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172222203939-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FvdgKmt5q1NAhAsFpdOIO%2F0Pu04VPvdcQ9TC1iMZisA%3D&st=2020-11-17T22%3A18%3A52Z&se=2020-12-18T22%3A23%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 22:25 UTC, opbld32 commented
Docs Build status updates of commit _[ec6f11a](https://github.com/vogtn/microsoft-graph-docs/commits/ec6f11ad5e4796f3b8a5528e3299be39cd2d7d53)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) | [Details](#user-content-348d3da9-5cd9a2dd)
[concepts/toc.yml](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |
[concepts/toolkit/images/rightToLeft.png](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/images/rightToLeft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) |
[concepts/toolkit/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |

<a id="348d3da9-5cd9a2dd"></a>
### [concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172224165019-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=A2WgGvMeNvKbGHZwf0AFQGHT3yWzZwo0HQJdtoiDicA%3D&st=2020-11-17T22%3A20%3A41Z&se=2020-12-18T22%3A25%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 22:34 UTC, opbld31 commented
Docs Build status updates of commit _[7c6eca5](https://github.com/vogtn/microsoft-graph-docs/commits/7c6eca51467c8f18403fbd3456a2c0891aa8a17d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) | [Details](#user-content-348d3da9-5228c2ce)
[concepts/toc.yml](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |
[concepts/toolkit/images/rightToLeft.png](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/images/rightToLeft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) |
[concepts/toolkit/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |

<a id="348d3da9-5228c2ce"></a>
### [concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172233172849-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CGURp66k3ym%2FNo3HsIHiMX7vE5s%2B9skppJM453P%2Bpug%3D&st=2020-11-17T22%3A29%3A31Z&se=2020-12-18T22%3A34%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 16:29 UTC, opbld33 commented
Docs Build status updates of commit _[b90196e](https://github.com/vogtn/microsoft-graph-docs/commits/b90196e3f3c913eee58730aec97d8884fc25f05c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) | [Details](#user-content-348d3da9-ee4847de)
[concepts/toc.yml](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |
[concepts/toolkit/images/rightToLeft.png](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/images/rightToLeft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) |
[concepts/toolkit/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |

<a id="348d3da9-ee4847de"></a>
### [concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011201628384044-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rrXc7RO8tVYNUfSTTbhFhATSOB1zcxMpLn7JpBdGPoc%3D&st=2020-11-20T16%3A24%3A55Z&se=2020-12-21T16%3A29%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 16:30 UTC, vogtn commented on concepts/toolkit/localization.md
> +## Localizating components in the Microsoft Graph Toolkit
Updated with the current available strings, will add the person-card strings in a future PR: 

f87c41a

2020-11-20 16:30 UTC, vogtn commented on concepts/toolkit/right-to-left.md
> +
shortened up:

f87c41a

2020-11-20 16:31 UTC, opbld30 commented
Docs Build status updates of commit _[d74ae55](https://github.com/vogtn/microsoft-graph-docs/commits/d74ae55fd9ec150f031a1be082cc79493c5b1636)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) | [Details](#user-content-348d3da9-be4bc8b8)
[concepts/toc.yml](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |
[concepts/toolkit/images/rightToLeft.png](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/images/rightToLeft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) |
[concepts/toolkit/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |

<a id="348d3da9-be4bc8b8"></a>
### [concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011201629174090-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NbqQra%2F4BMIG9A%2B5Uxzp1EG7N%2FmT6c0FXDrDpzZ0Y1E%3D&st=2020-11-20T16%3A26%3A29Z&se=2020-12-21T16%3A31%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 16:33 UTC, opbld31 commented
Docs Build status updates of commit _[bff1f9e](https://github.com/vogtn/microsoft-graph-docs/commits/bff1f9e5993eac6560850b57994a9c616ce3896d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |
[concepts/toolkit/images/rightToLeft.png](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/images/rightToLeft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) |
[concepts/toolkit/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |
[concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011201632078250-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YHa1eBHhTQGSoRKB3YoVZQDMytqGeY20JvFCYHph058%3D&st=2020-11-20T16%3A28%3A28Z&se=2020-12-21T16%3A33%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-02 21:52 UTC, opbld33 commented
Docs Build status updates of commit _[ad73870](https://github.com/vogtn/microsoft-graph-docs/commits/ad73870af86dbcef909e3423cb8bca496a3faa32)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |
[concepts/toolkit/images/rightToLeft.png](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/images/rightToLeft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) |
[concepts/toolkit/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/localization?branch=pr-en-us-10569) |
[concepts/toolkit/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/right-to-left.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/right-to-left?branch=pr-en-us-10569) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012022151165248-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8%2Bswj45CjSHqdh4YCacIrYA5MO8emifa0dKQbGYZlDM%3D&st=2020-12-02T21%3A47%3A37Z&se=2021-01-02T21%3A52%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-02 22:01 UTC, opbld32 commented
Docs Build status updates of commit _[dc67cb3](https://github.com/vogtn/microsoft-graph-docs/commits/dc67cb3813ebe251d4c09bcd335382c386feaf5e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/localization?branch=pr-en-us-10569) | [Details](#user-content-b329d26c-26b9f3e9)
[concepts/toolkit/customize-components/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/customize-components/localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/localization?branch=pr-en-us-10569) |
[concepts/toolkit/customize-components/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/customize-components/right-to-left.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/right-to-left?branch=pr-en-us-10569) |
[concepts/toolkit/images/rightToLeft.png](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/images/rightToLeft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/right-to-left?branch=pr-en-us-10569) |

<a id="b329d26c-26b9f3e9"></a>
### [concepts/toc.yml](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toc.yml)
 - **Line 611, Column 23**: **[Warning-file-not-found]** `````Invalid file link: 'toolkit/localization.md'.`````
 - **Line 613, Column 23**: **[Warning-file-not-found]** `````Invalid file link: 'toolkit/right-to-left.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012022200393327-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HT3NvexWgIHpoqO6KkR07nQverc7pAlKFgfCUEXWwaM%3D&st=2020-12-02T21%3A56%3A53Z&se=2021-01-02T22%3A01%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-02 22:14 UTC, opbld30 commented
Docs Build status updates of commit _[62083d5](https://github.com/vogtn/microsoft-graph-docs/commits/62083d5c62e9cb776954c00fc83144d7dc9d890d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/localization?branch=pr-en-us-10569) |
[concepts/toolkit/customize-components/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/customize-components/localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/localization?branch=pr-en-us-10569) |
[concepts/toolkit/customize-components/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/customize-components/right-to-left.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/right-to-left?branch=pr-en-us-10569) |
[concepts/toolkit/images/rightToLeft.png](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/images/rightToLeft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/right-to-left?branch=pr-en-us-10569) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012022211595117-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C7MzFlUkDZlpihX3t6Ij8ZCkS7o%2BxsLU%2Bpgnxp05xY0%3D&st=2020-12-02T22%3A09%3A05Z&se=2021-01-02T22%3A14%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-03 01:29 UTC, nmetulev commented on concepts/toolkit/customize-components/localization.md
> +example:
```suggestion
All strings in the toolkit are not localized, but you can provide your own localized strings and manage different languages through the same process you use for localizing your app. To facilitate localization, the toolkit exposes the `LocalizationHelper` static class.

This is an example of localizing several components:
```

2020-12-03 01:29 UTC, nmetulev commented on concepts/toolkit/customize-components/localization.md
> +
```suggestion

When the `strings` property is assigned, all components will automatically pick up the new strings and re-render, allowing you to change strings dynamically. 

The strings can be set at a global level or per component (with the `_components:` property).
```

2020-12-03 01:29 UTC, nmetulev commented on concepts/toolkit/customize-components/localization.md
> +    tasks: {
Use quotes for consistency with others

```suggestion
    "tasks": {
```

2020-12-03 01:29 UTC, nmetulev commented on concepts/toolkit/customize-components/localization.md
> +    login: {
Use quotes for consistency with others

```suggestion
    "login": {
```

2020-12-03 01:29 UTC, nmetulev commented on concepts/toc.yml
> +
```suggestion
```

2020-12-03 01:29 UTC, nmetulev commented on concepts/toolkit/customize-components/right-to-left.md
> +Implementation relies on the usage of the `dir` attribute which must be implemented in the document structure [w3 spec standard](https://www.w3.org/International/questions/qa-bidi-css-markup#detail),
```suggestion
To change the direction of all components on the page, set the `dir` attribute on the document `html` or `body` tag to `rtl`, as shown in these examples:
```

2020-12-03 01:30 UTC, nmetulev approved these changes

2020-12-03 01:32 UTC, opbld31 commented
Docs Build status updates of commit _[bdb8473](https://github.com/vogtn/microsoft-graph-docs/commits/bdb8473c8b663b40d8167216951b126e2cdefcd2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/localization?branch=pr-en-us-10569) |
[concepts/toolkit/customize-components/localization.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/customize-components/localization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/localization?branch=pr-en-us-10569) |
[concepts/toolkit/customize-components/right-to-left.md](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/customize-components/right-to-left.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/right-to-left?branch=pr-en-us-10569) |
[concepts/toolkit/images/rightToLeft.png](https://github.com/vogtn/microsoft-graph-docs/blob/mgt/localization/concepts/toolkit/images/rightToLeft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/customize-components/right-to-left?branch=pr-en-us-10569) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012030130439115-10569%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FMCOomUMtLnlgbmXjCkzC6alO1lo6c%2BOdkB%2BiPZNsdU%3D&st=2020-12-03T01%3A27%3A48Z&se=2021-01-03T01%3A32%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-03 01:33 UTC, merged