Onboarding to webhooks for To Do apis
microsoftgraph/microsoft-graph-docs pull request #10583
Opened 2020-11-09 11:56 UTC by bgaonkar

Onboarding to webhooks for To Do apis

2020-11-09 11:58 UTC, opbld32 commented
Docs Build status updates of commit _[71e58de](https://github.com/microsoftgraph/microsoft-graph-docs/commits/71e58deb93b19efd8bb674194081fb58c9d81c4c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-69825fde-85d87a48)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8f8d1d71-85d87a48)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-a8c89eee-85d87a48)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-409b84f8-85d87a48)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |

<a id="69825fde-85d87a48"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-85d87a48"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-85d87a48"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-85d87a48"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011091156114503-10583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AKa3lt%2FDq8c4yUp5LGLdZdOJ0pfNaYpHAplmUDgZ0mI%3D&st=2020-11-09T11%3A53%3A23Z&se=2020-12-10T11%3A58%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-11 06:33 UTC, opbld30 commented
Docs Build status updates of commit _[1ed0f63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ed0f63e7fb8c5f79ea5a7e49bb910e6431c0ceb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-69825fde-fe140ee1)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8f8d1d71-fe140ee1)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-a8c89eee-fe140ee1)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-409b84f8-fe140ee1)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10583) | [Details](#user-content-de0bbbbb-fe140ee1)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10583) | [Details](#user-content-8c54aee1-fe140ee1)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |

<a id="69825fde-fe140ee1"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-fe140ee1"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-fe140ee1"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-fe140ee1"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="de0bbbbb-fe140ee1"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printtaskdefinition?view=graph-rest-beta`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 28, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/chatmessage?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/contact?view=graph-rest-1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &prese [...]

2020-11-20 08:11 UTC, angelgolfer-ms commented on concepts/webhooks.md
> +- ToDo Task [todoTask]
Line 44:
Please use just "todoTask" and link to that resource topic the same way. Other combinations repeat the term "to do", can appear confusing.

2020-11-20 08:48 UTC, angelgolfer-ms commented on concepts/webhooks.md
> +Or to the tasks in user's To Do list:
Line 66:
Please add the article 'a' before "user's To Do list".

2020-11-20 09:00 UTC, angelgolfer-ms commented on concepts/webhooks.md
> +- ToDo Task [todoTask]
Please append "(preview)" to "todoTask", like in line 42.

2020-11-20 09:33 UTC, angelgolfer-ms commented on concepts/webhooks.md
>  You can create a subscription to a specific Outlook folder such as the Inbox:
Please also update the todotask.md topic in beta, and add a sentence between the 2 bullet points before the "Methods" section:
"Subscribing to change notifications." and link "change notifications" to /graph/webhooks.
You can please take a look at user.md how this is like.

2020-11-20 09:39 UTC, angelgolfer-ms commented on concepts/webhooks.md
>  You can create a subscription to a specific Outlook folder such as the Inbox:
And please also update the API overview for change notifications in the beta endpoint:
"https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10583"

2020-11-20 09:46 UTC, angelgolfer-ms requested changes
Thank you for the PR, please see my comments.
After you incorporate the feedback, your PR should be ready for publishing.

2020-11-20 10:41 UTC, opbld30 commented
Docs Build status updates of commit _[8c3cd3e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c3cd3e28a4ae640737f95f9150dc87e9d7776eb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6c8361ce)

<a id="6c8361ce"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011201041182167-10583%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=K1dFnNj91CsXwHfOYZ3YSciPQMaIuXrMjAVRe2pY3Es%3D&st=2020-11-20T10%3A36%3A39Z&se=2020-12-21T10%3A41%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 11:17 UTC, opbld34 commented
Docs Build status updates of commit _[d1b68d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1b68d4fb3868f42995f45eec61e41240fd301a0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-69825fde-4dc8b3d4)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8f8d1d71-4dc8b3d4)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-a8c89eee-4dc8b3d4)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-409b84f8-4dc8b3d4)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-6e0d0a83-4dc8b3d4)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10583) | [Details](#user-content-de0bbbbb-4dc8b3d4)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10583) | [Details](#user-content-8c54aee1-4dc8b3d4)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |

<a id="69825fde-4dc8b3d4"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-4dc8b3d4"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-4dc8b3d4"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-4dc8b3d4"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-4dc8b3d4"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="de0bbbbb-4dc8b3d4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? [...]

2020-11-20 23:30 UTC, opbld34 commented
Docs Build status updates of commit _[a5edea5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5edea53c61ca1aa3f69b64ea52072ac4de78fc2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-69825fde-068f9518)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8f8d1d71-068f9518)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-a8c89eee-068f9518)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-409b84f8-068f9518)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-6e0d0a83-068f9518)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10583) | [Details](#user-content-de0bbbbb-068f9518)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10583) | [Details](#user-content-8c54aee1-068f9518)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |

<a id="69825fde-068f9518"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-068f9518"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-068f9518"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-068f9518"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-068f9518"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="de0bbbbb-068f9518"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? [...]

2020-11-20 23:35 UTC, Lauragra requested changes
Please add an update to the JSON changelog file as well. If you want to take care of some of the warnings on this PR, you can add the ms.prod value "change-notifications" to the YAML headers for the subscription-related files.

2020-11-23 06:57 UTC, angelgolfer-ms commented on concepts/webhooks.md
> +- ToDo Task [todoTask]
Thanks for adding the "(preview)".
FYI I reorganized that bullet list to put some order that makes sense to customers.

2020-11-23 07:06 UTC, angelgolfer-ms commented on concepts/webhooks.md
>  You can create a subscription to a specific Outlook folder such as the Inbox:
FYI I swapped the order of the 2 bullet points "Subscribing to change notifications" and "Using delta query..." for consistency, and because customers can use change notifications to get notified of changes, and then use delta query to get the corresponding changes.

2020-11-23 07:07 UTC, angelgolfer-ms commented on concepts/webhooks.md
>  You can create a subscription to a specific Outlook folder such as the Inbox:
FYI, I also reordered the rows in the table in webhooks.md in the beta section to put some order there as well.

2020-11-23 07:13 UTC, angelgolfer-ms commented on concepts/webhooks.md
>  You can create a subscription to a specific Outlook folder such as the Inbox:
BTW, in both the bullet list and table that list all the resources that support change notifications, I changed your item to simply "todoTask" (per my earlier comments) because the name is clear enough which service (To Do) that resource belongs to. And the name also identifies it refers to a task resource. Using something like "To Do todoTask" or "task todoTask" is awkward and repeating what's already obvious in the resource name "todoTask".

2020-11-23 08:28 UTC, opbld32 commented
Docs Build status updates of commit _[a21e877](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a21e87747455a984e8bc9db4e77e437a5016e8c4)_: 

:clock10: **Pending**: waiting for processors ([21](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 21 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-23 08:29 UTC, opbld32 commented
Docs Build status updates of commit _[eac80eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eac80eb4c357e95212b2e516a50cfd6ff2675f78)_: 

:clock10: **Pending**: waiting for processors ([45](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 45 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-23 08:43 UTC, opbld34 commented
Docs Build status updates of commit _[a21e877](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a21e87747455a984e8bc9db4e77e437a5016e8c4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-69825fde-9123f421)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8f8d1d71-9123f421)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-a8c89eee-9123f421)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-409b84f8-9123f421)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-6e0d0a83-9123f421)
[api-reference/v1.0/api/driveitem-restore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/v1.0/api/driveitem-restore.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-restore?view=graph-rest-1.0&branch=pr-en-us-10583) (>= graph-rest-1.0) | [Details](#user-content-6b881ac2-9123f421)
[api-reference/beta/api/ediscoverycase-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/ediscoverycase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-6bb5760f-9123f421)
[api-reference/beta/api/ediscoverycase-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/ediscoverycase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-07b05d2b-9123f421)
[api-reference/beta/api/educationalactivity-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/educationalactivity-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-e82c98d3-9123f421)
[api-reference/beta/api/ediscoverycase-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/ediscoverycase-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-0cf87949-9123f421)
[api-reference/beta/api/educationalactivity-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/educationalactivity-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-c8045151-9123f421)
[api-reference/beta/api/ediscoverycase-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/ediscoverycase-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-post?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-f03fc281-9123f421)
[api-reference/beta/api/ediscoverycase-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/ediscoverycase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/ediscoverycase-list?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-686f0a31-9123f421)
[api-reference/beta/api/educationalactivity-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/educationalactivity-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationalactivity-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-591908b5-9123f421)
[api-reference/beta/api/itempublication-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/itempublication-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itempublication-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8ea2bf1f-9123f421)
[api-reference/beta/api/itemaddress-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/itemaddress-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itemaddress-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8d8a622b-9123f421)
[api-reference/beta/api/itemphone-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/itemphone-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/itemphone-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-dfe231d1-9123f421)
[api-reference/beta/api/profile-list-phones.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/profile-list-phones.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profile-list-phones?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-203517f2-9123f421)
[api-reference/beta/api/profile-list-interests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/profile-list-interests.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profile-list-interests?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-52a444df-9123f421)
[api-reference/beta/api [...]

2020-11-23 11:04 UTC, angelgolfer-ms approved these changes
FYI I wrapped up by updating a few things so to complete the review process. Please follow up on the changelog json as Laura had requested and for which I emailed a few suggestions.

2020-12-02 05:46 UTC, opbld34 commented
Docs Build status updates of commit _[8418dfa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8418dfac805ea9fb14d1904c1adf143b9f76dfe4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-69825fde-0f9782ed)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8f8d1d71-0f9782ed)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-a8c89eee-0f9782ed)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-409b84f8-0f9782ed)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-6e0d0a83-0f9782ed)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10583) | [Details](#user-content-de0bbbbb-0f9782ed)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10583) | [Details](#user-content-8c54aee1-0f9782ed)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |

<a id="69825fde-0f9782ed"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-0f9782ed"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-0f9782ed"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-0f9782ed"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-0f9782ed"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the fol [...]

2020-12-03 04:27 UTC, opbld31 commented
Docs Build status updates of commit _[d2edee8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2edee88cc0357f3bbb6db1320330502ddaf0b48)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-69825fde-6f7539ae)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8f8d1d71-6f7539ae)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-a8c89eee-6f7539ae)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-409b84f8-6f7539ae)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-6e0d0a83-6f7539ae)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10583) | [Details](#user-content-de0bbbbb-6f7539ae)
[concepts/office365-groups-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/office365-groups-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/office365-groups-concept-overview?branch=pr-en-us-10583) | [Details](#user-content-7250074a-6f7539ae)
[api-reference/beta/api/accesspackageassignmentpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/accesspackageassignmentpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-2bfae0cd-6f7539ae)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10583) |

<a id="69825fde-6f7539ae"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-6f7539ae"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-6f7539ae"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-6f7539ae"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following at [...]

2020-12-03 04:28 UTC, opbld30 commented
Docs Build status updates of commit _[cb6bdf7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb6bdf7edab15ff6a4f65bc6e32b853cd8804529)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-69825fde-f41edef6)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8f8d1d71-f41edef6)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-a8c89eee-f41edef6)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-409b84f8-f41edef6)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-6e0d0a83-f41edef6)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10583) | [Details](#user-content-de0bbbbb-f41edef6)
[concepts/outlook-calendar-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/outlook-calendar-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-calendar-concept-overview?branch=pr-en-us-10583) | [Details](#user-content-71f3e544-f41edef6)
[api-reference/beta/api/accesspackage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/accesspackage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-3cb7c294-f41edef6)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10583) |

<a id="69825fde-f41edef6"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-f41edef6"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-f41edef6"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-f41edef6"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. U [...]

2020-12-03 04:30 UTC, opbld31 commented
Docs Build status updates of commit _[2673bda](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2673bdae61de6e9bc365b2de8d8f7365be39db4e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-69825fde-90c41c52)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8f8d1d71-90c41c52)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-a8c89eee-90c41c52)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-409b84f8-90c41c52)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-6e0d0a83-90c41c52)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10583) | [Details](#user-content-de0bbbbb-90c41c52)
[concepts/outlook-get-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/outlook-get-mime-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/outlook-get-mime-message?branch=pr-en-us-10583) | [Details](#user-content-bbe67ef5-90c41c52)
[api-reference/v1.0/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/v1.0/overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0&branch=pr-en-us-10583) (>= graph-rest-1.0) | [Details](#user-content-874903dd-90c41c52)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10583) |

<a id="69825fde-90c41c52"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-90c41c52"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-90c41c52"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-90c41c52"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.` [...]

2020-12-03 04:44 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | beta | Added [todoTask](/graph/api/resources/todoTask?view=graph-rest-beta) to the resources supported for [change notifications](/graph/webhooks).|
Please move the changelog entry to December.

2020-12-03 04:57 UTC, opbld30 commented
Docs Build status updates of commit _[c931a57](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c931a571016e4cc333ea181d183a87d5819ad049)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-69825fde-ac5ec6a4)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8f8d1d71-ac5ec6a4)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-a8c89eee-ac5ec6a4)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-409b84f8-ac5ec6a4)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-6e0d0a83-ac5ec6a4)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10583) | [Details](#user-content-de0bbbbb-ac5ec6a4)
[api-reference/beta/api/accessreview-addreviewer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/accessreview-addreviewer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreview-addreviewer?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-c0bf2c74-ac5ec6a4)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10583) |

<a id="69825fde-ac5ec6a4"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-ac5ec6a4"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-ac5ec6a4"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-ac5ec6a4"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-ac5ec6a4"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://r [...]

2020-12-03 05:46 UTC, opbld34 commented
Docs Build status updates of commit _[e70f812](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e70f81209c7f0982049c3421c8a82a9f06cbf9f8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-69825fde-77228e3c)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8f8d1d71-77228e3c)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-a8c89eee-77228e3c)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-409b84f8-77228e3c)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-6e0d0a83-77228e3c)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10583) | [Details](#user-content-de0bbbbb-77228e3c)
[concepts/education-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/education-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/education-concept-overview?branch=pr-en-us-10583) | [Details](#user-content-25b91334-77228e3c)
[api-reference/beta/api/accesspackage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/accesspackage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-post?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-495f5252-77228e3c)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10583) |

<a id="69825fde-77228e3c"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-77228e3c"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-77228e3c"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-77228e3c"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise p [...]

2020-12-04 02:20 UTC, Lauragra commented on concepts/changelog.md
> +### Change notifications
Please resolve the merge conflict on the changelog and please ensure that the entries are alphabetical by month, so this entry should come first in the changelog alphabetically.

2020-12-04 19:00 UTC, opbld34 commented
Docs Build status updates of commit _[933aa56](https://github.com/microsoftgraph/microsoft-graph-docs/commits/933aa5652a8642968cd84169c9f3919c4828f52c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-69825fde-694f8b19)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8f8d1d71-694f8b19)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-a8c89eee-694f8b19)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-409b84f8-694f8b19)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-6e0d0a83-694f8b19)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10583) | [Details](#user-content-de0bbbbb-694f8b19)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10583) | [Details](#user-content-8c54aee1-694f8b19)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |

<a id="69825fde-694f8b19"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-694f8b19"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-694f8b19"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-694f8b19"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-694f8b19"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the fol [...]

2020-12-04 19:02 UTC, avijityadav commented on concepts/changelog.md
> +### Change notifications
fixed.

2020-12-07 17:21 UTC, opbld34 commented
Docs Build status updates of commit _[f18490b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f18490be726d2bc6159aeab7362fdd9a46d57bf7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-69825fde-a10da61a)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8f8d1d71-a10da61a)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-a8c89eee-a10da61a)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-409b84f8-a10da61a)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-6e0d0a83-a10da61a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10583) | [Details](#user-content-de0bbbbb-a10da61a)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10583) | [Details](#user-content-8c54aee1-a10da61a)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |

<a id="69825fde-a10da61a"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-a10da61a"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-a10da61a"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-a10da61a"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-a10da61a"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the fol [...]

2020-12-07 17:46 UTC, opbld33 commented
Docs Build status updates of commit _[9f8731b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f8731badaf3d27a67f80604eea79341910470ff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-69825fde-54f60e8e)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8f8d1d71-54f60e8e)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-a8c89eee-54f60e8e)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-409b84f8-54f60e8e)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-6e0d0a83-54f60e8e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10583) | [Details](#user-content-de0bbbbb-54f60e8e)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10583) | [Details](#user-content-8c54aee1-54f60e8e)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |

<a id="69825fde-54f60e8e"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-54f60e8e"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-54f60e8e"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-54f60e8e"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-54f60e8e"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the fol [...]

2020-12-07 17:50 UTC, opbld30 commented
Docs Build status updates of commit _[22653a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22653a4e8c101566ee2df1f2383083ab84f9e3f9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-69825fde-b75d2707)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-8f8d1d71-b75d2707)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-a8c89eee-b75d2707)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-409b84f8-b75d2707)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) | [Details](#user-content-6e0d0a83-b75d2707)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10583) | [Details](#user-content-de0bbbbb-b75d2707)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-10583) | [Details](#user-content-8c54aee1-b75d2707)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[api-reference/beta/resources/todotask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/todotask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-beta&branch=pr-en-us-10583) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.Todo.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/changelog/Microsoft.Todo.json) | :white_check_mark:Succeeded | |

<a id="69825fde-b75d2707"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-b75d2707"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-b75d2707"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-b75d2707"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6e0d0a83-b75d2707"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/bgaonkar/Add_webhooks_documentation/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the fol [...]

2020-12-07 18:41 UTC, Lauragra approved these changes

2020-12-07 18:42 UTC, merged