Add email OTP to auth methods policy config
microsoftgraph/microsoft-graph-docs pull request #10599
Opened 2020-11-10 02:37 UTC by mmcla

Adding email OTP to the authentication methods configuration

2020-11-10 02:38 UTC, opbld34 commented
Docs Build status updates of commit _[bf313bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf313bf21d5d1f324170d360aaea72ae55e96033)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[doc-stubs/api/authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodconfiguration-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodconfiguration-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodconfiguration-post-authenticationmethodconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodconfiguration-post-authenticationmethodconfigurations.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodspolicy-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodspolicy-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodspolicy-delete-authenticationmethodconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodspolicy-delete-authenticationmethodconfigurations.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodspolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodspolicy-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodspolicy-get-authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodspolicy-get-authenticationmethodconfiguration.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodspolicy-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodspolicy-list-authenticationmethodconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodspolicy-list-authenticationmethodconfigurations.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodspolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodspolicy-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodspolicy-post-authenticationmethodconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodspolicy-post-authenticationmethodconfigurations.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodspolicy-update-authenticationmethodconfigurations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodspolicy-update-authenticationmethodconfigurations.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodspolicy-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodtarget-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodtarget-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodtarget-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodtarget-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodtarget-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodtarget-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodtarget-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodtarget-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/authenticationmethodtarget-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/authenticationmethodtarget-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/emailauthenticationmethodconfiguration-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/emailauthenticationmethodconfiguration-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/emailauthenticationmethodconfiguration-delete-includetargets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stubs/api/emailauthenticationmethodconfiguration-delete-includetargets.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/doc-stu [...]

2020-11-10 02:39 UTC, opbld33 commented
Docs Build status updates of commit _[9a4a0eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a4a0eb8e5e209cd54cf8a7c7887cfdc2f9173d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011100237417250-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=h%2BO2M9j3PVe1qfgzXpG5d8HozJ2HhjNoRe9wm%2Bpl1kE%3D&st=2020-11-10T02%3A34%3A39Z&se=2020-12-11T02%3A39%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 02:44 UTC, opbld33 commented
Docs Build status updates of commit _[35e97eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35e97eb030cf94fa249411c9de63b73c77bd718e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011100243174082-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9BKAmZnDE6cloE6axB0XoIm49XW7H1opy9xJTq9j3ls%3D&st=2020-11-10T02%3A39%3A23Z&se=2020-12-11T02%3A44%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 07:59 UTC, andres-canello commented on api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md
> +For delegated scenarios, the administrator needs one of the following [roles](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles):
Only Global Admins can do this right now. I have another PR waiting to make these changes to the live docs. The working I used is: 

For delegated scenarios, the administrator needs the following [role](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles):

* Global admin

2020-11-10 08:00 UTC, andres-canello commented on api-reference/beta/api/emailauthenticationmethodconfiguration-get.md
> +For delegated scenarios the administrator needs one of the following [roles](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles):
Same comment about GA.

2020-11-10 08:03 UTC, andres-canello commented on api-reference/beta/api/emailauthenticationmethodconfiguration-update.md
> +For delegated scenarios, the administrator needs one of the following [roles](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles):
Same comment about GA.

2020-11-10 08:08 UTC, andres-canello commented on api-reference/beta/resources/emailauthenticationmethodconfiguration.md
> +|allowExternalIdToUseEmailOtp|externalEmailOtpState|Determines whether email OTP is usable by external users for authentication. Possible values are: `default`, `enabled`, `disabled`, `unknownFutureV
I think we need to explain what the "default" state means.

2020-11-10 08:11 UTC, andres-canello reviewed
Left a few notes.  I think you are missing the entry in the changelog.

2020-11-11 02:53 UTC, opbld33 commented
Docs Build status updates of commit _[89707bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89707bf7f26f75b993fd3c4d66ec831691cbba98)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-11 02:55 UTC, Lauragra commented on api-reference/beta/api/emailauthenticationmethodconfiguration-get.md
> +GET https://graph.microsoft.com/beta/policies/authenticationMethodsPolicy/authenticationMethodConfiguration/email
In this section we don't show the full URL, we do that in the example. Just show the syntax here.

2020-11-11 02:55 UTC, opbld31 commented
Docs Build status updates of commit _[89707bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89707bf7f26f75b993fd3c4d66ec831691cbba98)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011110253550088-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AC8lVxL0icOKPXzCS3XnD6L7oK4YA5j29CNZy7kSkfM%3D&st=2020-11-11T02%3A50%3A07Z&se=2020-12-12T02%3A55%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-11 02:56 UTC, Lauragra commented on api-reference/beta/api/emailauthenticationmethodconfiguration-get.md
> +Read the properties and relationships of the [emailAuthenticationMethodConfiguration](../resources/emailauthenticationmethodconfiguration.md) object, which represents the email OTP [authentication me
Is OTP an acronym that will be familiar to readers? Generally we spell out acronyms on first mention.

2020-11-11 02:56 UTC, opbld30 commented
Docs Build status updates of commit _[b676553](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b676553fef57f95c8b0faa1543c6345d1d1441c8)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-11 02:58 UTC, opbld33 commented
Docs Build status updates of commit _[b676553](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b676553fef57f95c8b0faa1543c6345d1d1441c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011110256456886-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cQi6JEVY302pzFnNA3CW9IEDfCS0Ujomi4vpQpmIjk8%3D&st=2020-11-11T02%3A53%3A01Z&se=2020-12-12T02%3A58%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-11 02:58 UTC, opbld33 commented
Docs Build status updates of commit _[493b2ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/493b2eaf70c66d1e97cbce3bb537034a10f09a58)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-11 02:59 UTC, opbld30 commented
Docs Build status updates of commit _[493b2ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/493b2eaf70c66d1e97cbce3bb537034a10f09a58)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011110258122593-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qdn2UDIyzCJrHI5hz8wFxKX%2BLWtht%2BdCPqAhkruHHXM%3D&st=2020-11-11T02%3A54%3A18Z&se=2020-12-12T02%3A59%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-11 03:00 UTC, Lauragra commented on api-reference/beta/resources/emailauthenticationmethodconfiguration.md
> +|[Get emailAuthenticationMethodConfiguration](../api/emailauthenticationmethodconfiguration-get.md)|[emailAuthenticationMethodConfiguration](../resources/emailauthenticationmethodconfiguration.md)|Re
Remove the links from the Description column.

2020-11-11 03:01 UTC, opbld32 commented
Docs Build status updates of commit _[bd1b030](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd1b0304f4e17531a4011102b4cabbe304857b6d)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-11 03:03 UTC, opbld30 commented
Docs Build status updates of commit _[bd1b030](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd1b0304f4e17531a4011102b4cabbe304857b6d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011110301486872-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qG3bU9hnVZ3KIcbhy%2FFU2ctGlKEQfPBMjK96qClQKQo%3D&st=2020-11-11T02%3A57%3A59Z&se=2020-12-12T03%3A02%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-11 03:03 UTC, Lauragra requested changes
Please incorporate comments and please add an update to the changelog.md file and the DirectoryServices.json changelog file for the new APIs.

2020-11-12 17:02 UTC, mmcla commented on api-reference/beta/api/emailauthenticationmethodconfiguration-get.md
> +GET https://graph.microsoft.com/beta/policies/authenticationMethodsPolicy/authenticationMethodConfiguration/email
Ok, I'm pretty sure these were added by the Graph team's autogenerator tool, probably worth checking to see if that's something they're introducing.

2020-11-12 17:05 UTC, mmcla commented on api-reference/beta/api/emailauthenticationmethodconfiguration-update.md
> +For delegated scenarios, the administrator needs one of the following [roles](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles):
Fixed

2020-11-12 17:06 UTC, mmcla commented on api-reference/beta/resources/emailauthenticationmethodconfiguration.md
> +|[Get emailAuthenticationMethodConfiguration](../api/emailauthenticationmethodconfiguration-get.md)|[emailAuthenticationMethodConfiguration](../resources/emailauthenticationmethodconfiguration.md)|Re
Fixed

2020-11-12 17:20 UTC, opbld32 commented
Docs Build status updates of commit _[f44f6f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f44f6f9d84d4f151bb94baa95f3f3ab130e2e41f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121719147074-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=d0%2FZy3WYzjBc5r6RMqpKrQglWqIqHC%2BsfDjwaGx6uls%3D&st=2020-11-12T17%3A15%3A32Z&se=2020-12-13T17%3A20%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 17:31 UTC, opbld30 commented
Docs Build status updates of commit _[f497985](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4979852116607e6733ec60303595ee676e0376d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10599) | [Details](#user-content-de0bbbbb-da7c3f49)
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |

<a id="de0bbbbb-da7c3f49"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md)
 - **Line 18, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121729568709-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2dN27QAfBNtSEBTV2pGE9Juni%2BNAB6GjNj4kE6vsqoM%3D&st=2020-11-12T17%3A26%3A15Z&se=2020-12-13T17%3A31%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 17:39 UTC, davidmu1 approved these changes
Other than the current requested changes and the API Doctor errors, it looks good to me.

2020-11-12 17:44 UTC, opbld33 commented
Docs Build status updates of commit _[35e39b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35e39b94d64148f9068801361bfaf0845af220b1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1f9c96f7)

<a id="1f9c96f7"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121743595110-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PXZ1P%2FhbkxXQgmDZR%2FxSR81dF5K7pZuOZnLplbrBfRc%3D&st=2020-11-12T17%3A39%3A27Z&se=2020-12-13T17%3A44%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 17:45 UTC, mmcla commented
> Please incorporate comments and please add an update to the changelog.md file and the DirectoryServices.json changelog file for the new APIs.

@Lauragra I added the changelog entries and updated all of the changes you requested.

Everything is done except for one suggested change from Andres, which I'm waiting on a sentence from a colleague.

2020-11-12 18:14 UTC, opbld32 commented
Docs Build status updates of commit _[3dbcdc7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3dbcdc7624f1bbe2122743dfbcc8830915abb34a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a16abe68)

<a id="a16abe68"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121813552576-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aAvvLwW1G2c%2F2uXRjYXigXri4wkwvin%2BvEuXSE%2Fok6o%3D&st=2020-11-12T18%3A09%3A13Z&se=2020-12-13T18%3A14%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-15 23:11 UTC, Lauragra approved these changes

2020-11-18 14:14 UTC, andrewchoi5 approved these changes

2020-12-07 22:48 UTC, opbld32 commented
Docs Build status updates of commit _[5da6160](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5da61601b69e898640eef007a4b5725644a9bf4f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10599) | [Details](#user-content-de0bbbbb-a9b371a2)
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-a9b371a2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012072246587352-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Fe1AcnHieFp8UT2HJGoh%2BiqTkFi9GBP%2BQ%2Fr2HuZvqPw%3D&st=2020-12-07T22%3A43%3A17Z&se=2021-01-07T22%3A48%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 23:18 UTC, opbld31 commented
Docs Build status updates of commit _[e5738a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e5738a356395743e6c3ae5940a9feae25f17a01f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10599) | [Details](#user-content-de0bbbbb-c889be9a)
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-c889be9a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012072316556695-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OwhMbkfrdDpwXmjXBP4HK8wXO5PeqRG37yPjx8sU9uY%3D&st=2020-12-07T23%3A13%3A26Z&se=2021-01-07T23%3A18%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 23:23 UTC, opbld32 commented
Docs Build status updates of commit _[85989c2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/85989c25825c57792935b6f5ad06e1d9acf8d41b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10599) | [Details](#user-content-de0bbbbb-644f94b2)
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-644f94b2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012072322125468-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P%2FaeHhnMAXoHmR0gUaRWUyIpTAiPCkCZgxWYkxD5i4w%3D&st=2020-12-07T23%3A18%3A33Z&se=2021-01-07T23%3A23%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 23:39 UTC, opbld30 commented
Docs Build status updates of commit _[9eee5a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9eee5a0f90d19dcab231fde017ffde40e3db5d72)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10599) | [Details](#user-content-de0bbbbb-e92ffc90)
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-e92ffc90"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012072337487448-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KoHUuXTLuAnW6CaFguo1ppWUIAB0g8nQSAuIeNHt1G8%3D&st=2020-12-07T23%3A34%3A01Z&se=2021-01-07T23%3A39%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 01:45 UTC, opbld33 commented
Docs Build status updates of commit _[1d45b16](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d45b168fae5b52e50af1710bef4f711ca965d2b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10599) | [Details](#user-content-de0bbbbb-607eb40f)
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-607eb40f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080143525911-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gDNXN3FwOESlYHVSA3smY9z7HDw%2FOPlbDIqtjjYOxR4%3D&st=2020-12-08T01%3A40%3A10Z&se=2021-01-08T01%3A45%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 03:38 UTC, opbld34 commented
Docs Build status updates of commit _[b857c84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b857c8415a266c304c4f1416b5fd2bec2b915d4c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10599) | [Details](#user-content-de0bbbbb-fae9a465)
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-fae9a465"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100337053854-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6NMcWUUFesp8ld5%2FlP%2Bq%2BxrHwmQzjRmr8EaN2HNLoGs%3D&st=2020-12-10T03%3A33%3A27Z&se=2021-01-10T03%3A38%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 03:40 UTC, opbld30 commented
Docs Build status updates of commit _[e4cb90f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4cb90f5e835707ae5e1485c15691c2e3bff0042)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10599) | [Details](#user-content-de0bbbbb-57ffc3be)
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-57ffc3be"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100337324878-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cIkyTPEojh9KIzlJSQTJ49NaS2EMdyaI7qrQVFH1uTI%3D&st=2020-12-10T03%3A35%3A18Z&se=2021-01-10T03%3A40%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 03:42 UTC, opbld34 commented
Docs Build status updates of commit _[a33fd6d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a33fd6d3acd0ac85142cb07aff29d032e020e798)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10599) | [Details](#user-content-de0bbbbb-657f295e)
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10599) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-657f295e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-09-authmethods_policy_emailOtp/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 50, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100341337854-10599%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uxOs1kzJ7GRPEQUTtorjT4CnFjmAD4FpVJpibLev4qk%3D&st=2020-12-10T03%3A37%3A57Z&se=2021-01-10T03%3A42%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 03:54 UTC, merged