Update Microsoft Search Doc to 1.0
microsoftgraph/microsoft-graph-docs pull request #10608
Opened 2020-11-10 09:34 UTC by lanhongvp

Update Microsoft Search Doc to 1.0

2020-11-10 09:35 UTC, opbld30 commented
Docs Build status updates of commit _[55f0560](https://github.com/microsoftgraph/microsoft-graph-docs/commits/55f0560f521de4d9c24042d5b63232a943defd8c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-b0d8e80c)
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/search-query-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/csharp/search-query-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/search-query-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/javascript/search-query-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhitscontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhitscontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhitscontainer?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquery?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquerystring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquerystring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquerystring?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |

<a id="77cfd98e-b0d8e80c"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/toc.yml)
 - **Line 4974, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011100934216645-10608%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nY%2FYq8h9pkmV5wjIuRVJj5z5ebz1gQuPZ2qvc3oaB7Y%3D&st=2020-11-10T09%3A30%3A33Z&se=2020-12-11T09%3A35%3A33Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/Genera [...]

2020-11-13 02:29 UTC, opbld31 commented
Docs Build status updates of commit _[f718e6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f718e6b79aa6b29290f2b70298ca4686191df0ef)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-72a194c8)
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/search-query-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/csharp/search-query-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/search-query-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/javascript/search-query-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhitscontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhitscontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhitscontainer?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquery?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquerystring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquerystring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquerystring?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |

<a id="77cfd98e-72a194c8"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/toc.yml)
 - **Line 4974, Column 17**: **[Warning-file-not-found]** `````Invalid file link: 'api/chatmessage-post.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011130228257373-10608%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7tejfgTnKsfLMbx9KBOjygDEVIXerAPXSjjBWDsBVeQ%3D&st=2020-11-13T02%3A24%3A33Z&se=2020-12-14T02%3A29%3A33Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General? [...]

2020-11-13 02:52 UTC, opbld33 commented
Docs Build status updates of commit _[4919653](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4919653aeaa1526477f84cdbf924c2f8fcf6b050)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-53d9b6d8)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) | [Details](#user-content-de0bbbbb-53d9b6d8)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/search-query-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/csharp/search-query-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/search-query-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/javascript/search-query-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhitscontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhitscontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhitscontainer?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquery?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquerystring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquerystring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquerystring?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-10608) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-10608) |
[concepts/search-concept-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-events?branch=pr-en-us-10608) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-10608) |
[concepts/search-concept-sort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-sort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-sort?branch=pr-en-us-10608) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) |
[concepts/whats-new-overview.md](h [...]

2020-11-13 03:04 UTC, nmoreau approved these changes
This is great !

2020-11-13 03:05 UTC, opbld30 commented
Docs Build status updates of commit _[207361b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/207361b2e68b8c43f20b9534503f15d56dbbad98)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) | [Details](#user-content-77cfd98e-8ce1e858)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) | [Details](#user-content-de0bbbbb-8ce1e858)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/search-query-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/csharp/search-query-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/search-query-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/javascript/search-query-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhitscontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhitscontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhitscontainer?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquery?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquerystring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquerystring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquerystring?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-10608) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-10608) |
[concepts/search-concept-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-events?branch=pr-en-us-10608) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-10608) |
[concepts/search-concept-sort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-sort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-sort?branch=pr-en-us-10608) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) |
[concepts/whats-new-overview.md](h [...]

2020-11-13 05:30 UTC, opbld32 commented
Docs Build status updates of commit _[7109103](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7109103936ba712e8b974d4a2b60d224f8dbf2e1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8f74a765)

<a id="8f74a765"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011130529468858-10608%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XhitlQQRCEI6cX9fgZb6kmBKCI36dt13Reu9Abjq7ZQ%3D&st=2020-11-13T05%3A25%3A02Z&se=2020-12-14T05%3A30%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 05:49 UTC, opbld34 commented
Docs Build status updates of commit _[e0db789](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e0db789cd0c26d590b78bf379a924e5f59b3d4c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) | [Details](#user-content-de0bbbbb-9591b023)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/search-query-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/csharp/search-query-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/search-query-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/javascript/search-query-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhitscontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhitscontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhitscontainer?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquery?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquerystring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquerystring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquerystring?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-10608) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-10608) |
[concepts/search-concept-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-events?branch=pr-en-us-10608) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-10608) |
[concepts/search-concept-sort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-sort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-sort?branch=pr-en-us-10608) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Sea [...]

2020-11-18 10:29 UTC, angelgolfer-ms commented on changelog/Microsoft.MicrosoftSearch.json
> +            "WorkloadArea": "People and workplace intelligence",
Lines 74-75:
They don't look right. Please fix these lines.

2020-11-18 10:35 UTC, angelgolfer-ms commented on concepts/toc.yml
>          items:
Other than the conceptual TOC, can you also update search-concept-overview.md? Please fix the following:
(1) Remove "(preview)" from the topic title.
(2) Change all the links that point to the search API reference topics in beta to just dropping the ?view query parameter in the link. That would link to the v1 version of the corresponding reference topic. (Remember, the connectors are still in beta only, so don't change those links yet.)

2020-11-18 11:08 UTC, angelgolfer-ms commented on api-reference/v1.0/api/search-query.md
> +
Line 59: Please delete.
Lines 87-99: Please delete.
Please also delete the 3 files you included in this PR that are for the c-sharp, javascript, objective C snippets.

In general, please leave out lines that support the tabbed experience for language-specific snippets. There is a snippet generation tool that runs every week and detects what REST examples have been added or modified, and automatically inserts the appropriate tabs and snippet lines.
Info here: You can please take a look at this CDK topic, to help make sure you catch all the areas to update:
https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55086/Promote-beta-documentation-to-GA

2020-11-18 11:12 UTC, angelgolfer-ms requested changes
@lanhongvp , thanks for the PR. I haven't finished reviewing all the topics. I only covered a few concept topics, and haven't looked at the reference topics yet.
On the other hand, I noticed a few issues that you can fix and apply to one or more topics in this PR. Please do so and I'll continue my review later tomorrow.

2020-11-20 00:55 UTC, angelgolfer-ms commented on concepts/search-concept-custom-types.md
> +# Use the Microsoft Search API to search custom types imported using Microsoft Graph connectors (beta)
Line 9:
Please use "(preview)", not "(beta)".

2020-11-20 00:58 UTC, opbld31 commented
Docs Build status updates of commit _[8fe3c99](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8fe3c99ab2888547114fca74a7a4fe57234a7402)_: 

:clock10: **Pending**: waiting for processors ([10](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-20 01:03 UTC, opbld34 commented
Docs Build status updates of commit _[8fe3c99](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8fe3c99ab2888547114fca74a7a4fe57234a7402)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) | [Details](#user-content-de0bbbbb-a34a9bcc)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhitscontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhitscontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhitscontainer?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquery?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquerystring.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquerystring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquerystring?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-10608) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-10608) |
[concepts/search-concept-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-events?branch=pr-en-us-10608) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-10608) |
[concepts/search-concept-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-messages?branch=pr-en-us-10608) |
[concepts/search-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-10608) |
[concepts/search-concept-sort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-sort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-sort?branch=pr-en-us-10608) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs [...]

2020-11-20 01:03 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +    - name: Search
Line 11954:
Since connectors are not GA-ing yet, when you remove "(preview)" from 11941, please append "(preview)" to that "Index" node label.

2020-11-20 01:07 UTC, angelgolfer-ms commented on concepts/toc.yml
>          items:
Unresolving this comment to remind @lanhongvp about points (1) and (2).

(1) applies to search-concept-overview.md.
(2) applies to search-concept-overview.md and other search API conceptual and reference topics that point to the query API.

2020-11-20 01:09 UTC, angelgolfer-ms commented on concepts/toc.yml
>              href: search-concept-overview.md
In line 332 below:
Please append a "(preview)" to the TOC label "Index", since they haven't GA'd yet.

2020-11-20 01:31 UTC, angelgolfer-ms commented on includes/search-schema-updated.md
> +> The search API schema has changed in the beta version with some properties in a search request and response renamed or removed. See more details about the deprecation. Examples in this topic show t
Line 11:
Can you put the link back to the second sentence, "See more details about the deprecation"?

2020-11-20 01:40 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/search-api-overview.md
> +description: "Using the search API, apps can search Microsoft 365 data in the context of the authenticated user"
In the BETA VERSION of search-api-overview.md, line 164:
Please add to the first part of the first sentence :
"**In the beta version,** properties used in a search request have been renamed or removed..."

2020-11-20 02:02 UTC, angelgolfer-ms commented on concepts/search-concept-sort.md
> +# Sort search results (beta)
Line 9:
Is this feature remaining in beta only?
If so, please replace "(beta)" by "(preview)".

2020-11-20 02:03 UTC, angelgolfer-ms commented on concepts/search-concept-sort.md
Line 136:
In the second example request of this topic, please provide the full query URL including the domain and version.

2020-11-20 02:04 UTC, angelgolfer-ms commented on concepts/search-concept-aggregation.md
> +# Refine search results using aggregations (beta)
Line 9:
Is this feature remaining in beta only?
If so, please replace "(beta)" by "(preview)".

2020-11-20 02:07 UTC, angelgolfer-ms commented on concepts/search-concept-aggregation.md
Line 215
In the third example request of this topic, please provide the full query URL including the domain and version.

2020-11-20 03:19 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/searchquerystring.md
> +---
This section says searchQueryString is being deprecated. No other v1.0 files depends on /links to this resource either (which should be the case).
Can you please delete the v1.0 version of searchquerystring.md?

2020-11-20 03:48 UTC, angelgolfer-ms commented on api-reference/v1.0/api/search-query.md
> +        "externalItem"
Lines 67, 70:
Maybe we should show a different example here in a v1.0 topic?
Since connectors are not GA-ing yet, the externalItem resource shouldn't be accessible on v1. I'd expect this method on the v1.0 endpoint would return only resources on the v1.0 endpoint?

2020-11-20 03:53 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/searchrequest.md
> +|entityTypes|entityType collection| One or more types of resources expected in the response. Possible values are: `list`, `site`, `listItem`, `message`, `event`, `drive`, `driveItem`, `externalItem`.
Line 28:
Since this is a v1.0 resource, the entityTypes property should have possible values / types that are also available in v1.0?
I don't have access to your v1.0 CSDL, but I'd imagine externalItem would not be available in v1.0 yet, as it's part of the index API which isn't GA-ing yet?

2020-11-20 04:10 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/search-api-overview.md
> +|[Search across Graph connectors](/graph/search-concept-custom-types)| **contentSources** |
Line 31:
Do you want to either exclude this line about connectors?
Or mark the first column "(preview)"?

Technically, because this is a version-specific topic, the practice is to include only features/API that are available in v1.0. Usability surveys we did before indicate customers prefer to see only content that applies to them.

2020-11-20 04:12 UTC, angelgolfer-ms requested changes
Hi @lanhongvp , please see the latest comments from me.

2020-11-20 04:27 UTC, lanhongvp commented on concepts/search-concept-sort.md
> +# Sort search results (beta)
Yes, this feature is still beta, let me do the fix

2020-11-20 05:43 UTC, lanhongvp commented on api-reference/v1.0/resources/searchrequest.md
> +|entityTypes|entityType collection| One or more types of resources expected in the response. Possible values are: `list`, `site`, `listItem`, `message`, `event`, `drive`, `driveItem`, `externalItem`.
Sure, let me remove the connector part.

2020-11-20 05:58 UTC, lanhongvp commented on concepts/toc.yml
>          items:
Done the rest file about search*.md

2020-11-20 06:03 UTC, opbld33 commented
Docs Build status updates of commit _[edaf138](https://github.com/microsoftgraph/microsoft-graph-docs/commits/edaf138ebd77d94fd9eb69fadd41e509731b2abc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) | [Details](#user-content-de0bbbbb-6526dd75)
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhitscontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhitscontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhitscontainer?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquery?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-10608) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-10608) |
[concepts/search-concept-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-events?branch=pr-en-us-10608) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-10608) |
[concepts/search-concept-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-messages?branch=pr-en-us-10608) |
[concepts/search-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-10608) |
[concepts/search-concept-sort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-sort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-sort?branch=pr-en-us-10608) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://revie [...]

2020-11-21 04:53 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/search-api-overview.md
> +description: "Using the search API, apps can search Microsoft 365 data in the context of the authenticated user"
Thanks for incorporating the last request!
Just adding a note for ourselves why it's necessary to do that:
Even though the topic search-api-overview.md in the beta folder should be understood to be applicable just to the beta version, that particular section in line 164 is linked to from a boilerplate in the includes file search-schema-updated.md. That boilerplate is included in conceptual topics that are version agnostic generally, and, has a link to this section in line 164. When customers click from a conceptual topic to line 164 in this beta topic, we can't expect customers would notice that the section (line 164) is in a topic in the beta version. The customer may have very well been reading the concept topic assuming the content is generally applicable.

2020-11-21 05:06 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/searchrequest.md
> +|entityTypes|entityType collection| One or more types of resources expected in the response. Possible values are: `list`, `site`, `listItem`, `message`, `event`, `drive`, `driveItem`, `externalItem`.
@lanhongvp , thanks for fixing line 28, the entityTypes possible values.
I have a question about line 26, the contentSources property: is that property a no-op, not used/useful, in v1 when connectors are not in v1?

2020-11-21 05:15 UTC, opbld31 commented
Docs Build status updates of commit _[faebe68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/faebe68f757a8b07f69764bad54ea133ec7498a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhitscontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhitscontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhitscontainer?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquery?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-10608) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-10608) |
[concepts/search-concept-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-events?branch=pr-en-us-10608) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-10608) |
[concepts/search-concept-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-messages?branch=pr-en-us-10608) |
[concepts/search-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-10608) |
[concepts/search-concept-sort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-sort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-sort?branch=pr-en-us-10608) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph [...]

2020-11-21 05:48 UTC, opbld30 commented
Docs Build status updates of commit _[73d4e8c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73d4e8cfbe12f33b98ffb8ae0d84fdac5257b57a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhitscontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhitscontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhitscontainer?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquery?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-10608) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-10608) |
[concepts/search-concept-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-events?branch=pr-en-us-10608) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-10608) |
[concepts/search-concept-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-messages?branch=pr-en-us-10608) |
[concepts/search-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-10608) |
[concepts/search-concept-sort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-sort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-sort?branch=pr-en-us-10608) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph [...]

2020-11-21 05:50 UTC, opbld30 commented
Docs Build status updates of commit _[eba920f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eba920fc97c0efafb78d3558efc4abeb49b44e6e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhitscontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhitscontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhitscontainer?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquery?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-10608) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-10608) |
[concepts/search-concept-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-events?branch=pr-en-us-10608) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-10608) |
[concepts/search-concept-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-messages?branch=pr-en-us-10608) |
[concepts/search-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-10608) |
[concepts/search-concept-sort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-sort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-sort?branch=pr-en-us-10608) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph [...]

2020-11-21 06:05 UTC, opbld34 commented
Docs Build status updates of commit _[d4658a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d4658a40d25085b828c532f60f10cdf72ac1efe1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhitscontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhitscontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhitscontainer?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquery?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-10608) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-10608) |
[concepts/search-concept-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-events?branch=pr-en-us-10608) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-10608) |
[concepts/search-concept-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-messages?branch=pr-en-us-10608) |
[concepts/search-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-10608) |
[concepts/search-concept-sort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-sort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-sort?branch=pr-en-us-10608) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph [...]

2020-11-21 06:49 UTC, opbld33 commented
Docs Build status updates of commit _[3499c57](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3499c5764965191e457c355ce3814a78eb946e7d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-10608) (graph-rest-beta) |
[api-reference/v1.0/api/search-query.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/api/search-query.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/includes/snippets/objc/search-query-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/search.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchentity?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhit?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchhitscontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchhitscontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchhitscontainer?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchquery?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/searchresponse.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/resources/searchresponse.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchresponse?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&branch=pr-en-us-10608) (>= graph-rest-1.0) |
[changelog/Microsoft.MicrosoftSearch.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/changelog/Microsoft.MicrosoftSearch.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-10608) |
[concepts/search-concept-custom-types.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-10608) |
[concepts/search-concept-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-events?branch=pr-en-us-10608) |
[concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-files?branch=pr-en-us-10608) |
[concepts/search-concept-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-messages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-messages?branch=pr-en-us-10608) |
[concepts/search-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-overview?branch=pr-en-us-10608) |
[concepts/search-concept-sort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/search-concept-sort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-sort?branch=pr-en-us-10608) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10608) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-Microsoft-Search-API-v1.0-ship/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph [...]

2020-11-21 07:18 UTC, merged

2020-11-21 07:19 UTC, angelgolfer-ms reviewed
Made last fixes, published the docs.