Update usersettings.md
microsoftgraph/microsoft-graph-docs pull request #10614
Opened 2020-11-10 14:43 UTC by elmakhmu

adding new itemInsightsEnabled param to user object

2020-11-10 14:45 UTC, opbld30 commented
Docs Build status updates of commit _[cfcb99d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cfcb99d988857f3f14078b79f20b0607d5e2bbbf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-5/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-10614) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011101444000707-10614%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=evyNog0N15E5Gp1oYcd9BoWmunX%2FCc2LOgrXiWN050U%3D&st=2020-11-10T14%3A40%3A09Z&se=2020-12-11T14%3A45%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 14:48 UTC, opbld30 commented
Docs Build status updates of commit _[b56481e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b56481e8146203029d45e4a2a3a36f9bba70d71f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/usersettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-5/api-reference/beta/api/usersettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-get?view=graph-rest-beta&branch=pr-en-us-10614) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-5/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-10614) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011101447324216-10614%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JpXsxXKtuPYV9gb3y6rtXAUzqzh4KP77zQwlF7nypS0%3D&st=2020-11-10T14%3A43%3A45Z&se=2020-12-11T14%3A48%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 14:50 UTC, opbld32 commented
Docs Build status updates of commit _[35a9558](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35a955841653f5387b5e03df479428f61ca9d156)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/usersettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-5/api-reference/beta/api/usersettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-get?view=graph-rest-beta&branch=pr-en-us-10614) (graph-rest-beta) |
[api-reference/beta/api/usersettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-5/api-reference/beta/api/usersettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-update?view=graph-rest-beta&branch=pr-en-us-10614) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-5/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-10614) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011101449056999-10614%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f37vA4KWZODgAEzn8oqcve6C4RCVVANnKWgDHDIX4uo%3D&st=2020-11-10T14%3A45%3A13Z&se=2020-12-11T14%3A50%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 20:25 UTC, opbld32 commented
Docs Build status updates of commit _[663bed9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/663bed9fb0e7caa8f3487324324e791679413257)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/usersettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-5/api-reference/beta/api/usersettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-get?view=graph-rest-beta&branch=pr-en-us-10614) (graph-rest-beta) |
[api-reference/beta/api/usersettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-5/api-reference/beta/api/usersettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-update?view=graph-rest-beta&branch=pr-en-us-10614) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-5/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-10614) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011102024236070-10614%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ReOte6ScWBoTSXlDIG39z0Bu6zV997J2ClRUflq%2F9RA%3D&st=2020-11-10T20%3A20%3A35Z&se=2020-12-11T20%3A25%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-11 04:05 UTC, Lauragra requested changes
Please include an update to the changelog.md and JSON files to mention the addition of the new property.

2021-01-11 08:19 UTC, elmakhmu commented
this issue will be merged soon. please, do not close or delete.

2021-02-03 20:40 UTC, elmakhmu commented
can be deleted, since we changed API shape and it requires new docs changing, which is happening in separate PR

2021-02-03 20:40 UTC, closed without merging