update provider docs
microsoftgraph/microsoft-graph-docs pull request #10645
Opened 2020-11-11 22:42 UTC by elisenyang

2020-11-11 22:43 UTC, opbld32 commented
Docs Build status updates of commit _[e10072f](https://github.com/elisenyang/microsoft-graph-docs/commits/e10072fe2333ca29c16df62534074680af43acec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011112242427771-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fyCmIXRegustnJeNRdJ%2B5SK%2B24HqYtm615zPZsJlJNg%3D&st=2020-11-11T22%3A38%3A55Z&se=2020-12-12T22%3A43%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-11 22:49 UTC, opbld32 commented
Docs Build status updates of commit _[d01f1bd](https://github.com/elisenyang/microsoft-graph-docs/commits/d01f1bda5e96e6413833d52964ccaf98836401d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011112248424105-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CFAZIIyEN2KODIE%2BW09ZNtBIUCbqeIdRxXpRJGElpI0%3D&st=2020-11-11T22%3A44%3A51Z&se=2020-12-12T22%3A49%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-11 23:25 UTC, opbld34 commented
Docs Build status updates of commit _[fcb8594](https://github.com/elisenyang/microsoft-graph-docs/commits/fcb8594c5a686041b29c13923762e61151bdc746)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011112324413722-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9ZW12X39Yvt9wvQ%2Fd4ysfjEEXvE4mpCcp8QNnp0f3Qk%3D&st=2020-11-11T23%3A20%3A56Z&se=2020-12-12T23%3A25%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 03:59 UTC, nmetulev requested changes

2020-11-12 03:59 UTC, nmetulev commented on concepts/toolkit/providers.md
> +|[Msal](./providers/msal.md)|Uses MSAL.js to sign in users and acquire tokens to use with Microsoft Graph.|
```suggestion
|[Msal](./providers/msal.md)|Uses MSAL.js to sign in users and acquire tokens to use with Microsoft Graph in a web application.|
```

2020-11-12 03:59 UTC, nmetulev commented on concepts/toolkit/providers.md
>  Providers.globalProvider = new MsalProvider({
```suggestion
import {Providers, MsalProvider } from "@microsoft/mgt";
Providers.globalProvider = new MsalProvider({
```

2020-11-12 03:59 UTC, nmetulev commented on concepts/toolkit/providers.md
> +  clientId: '[YOUR_CLIENT_ID]'
```suggestion
  clientId: 'YOUR_CLIENT_ID'
```

2020-11-12 03:59 UTC, nmetulev commented on concepts/toolkit/providers.md
> +You can also use the component version of the provider directly in your HTML. Behind the scenees, a new provider is initialized and set as the global provider. The following example shows how to use
```suggestion
You can also use the component version of the provider directly in your HTML. Behind the scenes, a new provider is initialized and set as the global provider. The following example shows how to use the MsalProvider.
```

2020-11-12 03:59 UTC, nmetulev commented on concepts/toolkit/providers.md
> +<mgt-msal-provider client-id="[YOUR_CLIENT_ID]"></mgt-msal-provider>
```suggestion
<mgt-msal-provider client-id="YOUR_CLIENT_ID"></mgt-msal-provider>
```

2020-11-12 03:59 UTC, nmetulev commented on concepts/toolkit/providers.md
> +- `getAccessToken({'scopes': scopes[]}) : Promise<string>`
`getAccessToken` is a method on the provider itself, not the Providers namespace. What do you think about adding a section above the 'Providers namespace' section:

## Getting an access token

Each provider exposes a function called `getAccessToken` that can retreive the current access token or retreive a new access token for provided scopes. For example

```tsx
import {Providers} from "@microsoft/mgt";

// assuming a provider has been initialized prior to this

if (Providers.globalProvider.state === ProviderState.SignedIn) {
  const token = Provider.globalProvider.getAccessToken({scopes: ['User.Read']})
}
```

The `getAccessToken` method accepts one optional parameter with a list of scopes. If a provider does not support incremental consent, the parameter will not have an effect.

2020-11-12 03:59 UTC, nmetulev commented on concepts/toolkit/providers.md
> +- `getAccessToken({'scopes': scopes[]}) : Promise<string>`
Also consider adding a section prior to this on checking whether the provider is signed in, and move the section on calling the graph above as well.

2020-11-12 03:59 UTC, nmetulev commented on concepts/toolkit/providers.md
> +The Microsoft Graph Toolkit providers enable your application to authenticate with and access Microsoft Graph to retreive the data to be rendered in the components. Each provider encapsulates and pro
```suggestion
The Microsoft Graph Toolkit providers enable your application to authenticate with Microsoft Identity and access Microsoft Graph in only few lines of code. Each provider handles user authentication and acquiring the access tokens to call Microsoft Graph APIs, so that you don't have to write this code yourself. 

You can use the providers on their own, without components, to quickly implement authentication for your app and make calls to Microsoft Graph via the JavaScript client SDK.

The providers are required when using the Microsoft Graph Toolkit components as the components use them to access Microsoft Graph. If you already have your own authentication and simply want to use the components, you can use a [custom provider](./providers/custom.md) instead.
```

2020-11-12 17:57 UTC, opbld31 commented
Docs Build status updates of commit _[e9de602](https://github.com/elisenyang/microsoft-graph-docs/commits/e9de60233898c55a1df624d503655cff31522154)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121756247346-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=F4gZDM6%2BKtc9kTlL3e5LfpuMbLqdZ55IaBzfM72NvK4%3D&st=2020-11-12T17%3A52%3A40Z&se=2020-12-13T17%3A57%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 17:58 UTC, opbld34 commented
Docs Build status updates of commit _[1c75c7b](https://github.com/elisenyang/microsoft-graph-docs/commits/1c75c7b49e6f3212e8cabe1800dabec49e99ab9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121757402334-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BGZJ6A19H%2BrTYON2GWTwOpQexhqQLU9pazgA8ys4lPU%3D&st=2020-11-12T17%3A53%3A52Z&se=2020-12-13T17%3A58%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 18:00 UTC, opbld31 commented
Docs Build status updates of commit _[945dc7a](https://github.com/elisenyang/microsoft-graph-docs/commits/945dc7ad1a1095605bdd0e8166e5732c62de800d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121758436608-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iKMNIV4dhp9N49GiiPpTrKK25ip9rAQ7ZmU8tIz2AY4%3D&st=2020-11-12T17%3A55%3A23Z&se=2020-12-13T18%3A00%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 18:51 UTC, opbld31 commented
Docs Build status updates of commit _[3c04528](https://github.com/elisenyang/microsoft-graph-docs/commits/3c04528bde8ec956d3899d89f83d05aed867ff20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121850079308-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ASMS9wXfEcXcsO%2FLwcmjTslw2aAUQKOlKUsCzlIYsy8%3D&st=2020-11-12T18%3A46%3A21Z&se=2020-12-13T18%3A51%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 18:54 UTC, elisenyang commented on concepts/toolkit/providers.md
> +- `getAccessToken({'scopes': scopes[]}) : Promise<string>`
Added this section and rearranged the other ones

2020-11-13 05:06 UTC, opbld30 commented
Docs Build status updates of commit _[3cbeb1a](https://github.com/elisenyang/microsoft-graph-docs/commits/3cbeb1a6816b9f22d6b9d2605192271e8a055aab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011130505063783-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7XwHeQ99gKaRgdvtjz4%2Bv6DzMHc9wcRQsnBit1TCcLg%3D&st=2020-11-13T05%3A01%3A17Z&se=2020-12-14T05%3A06%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 05:15 UTC, nmetulev reviewed
I love it.

Apologies for not suggesting it before, but what do you think about also adding a section on signing in and signing out through the providers. If using the login component, the component handles that. But if not using the login component, some providers (like msal and teams) provide the `login` and `logout` methods.

2020-11-13 05:15 UTC, nmetulev commented on concepts/toolkit/providers.md
> +if (Providers.globalProvider.state == ProviderState.SignedIn) {
```suggestion
if (Providers.globalProvider.state === ProviderState.SignedIn) {
```

2020-11-13 05:15 UTC, nmetulev commented on concepts/toolkit/providers.md
> +if (Providers.globalProvider.state == ProviderState.SignedIn) {
```suggestion
if (Providers.globalProvider.state === ProviderState.SignedIn) {
```

2020-11-13 05:15 UTC, nmetulev commented on concepts/toolkit/providers.md
> +## Providers namespace
I really like this flow of all the different sections with examples. I think we can remove this entire `Providers namespace` section and replace it with a section on getting notified when the provider state changed via the `onProviderUpdated` function. It can go right under the `Provider State` section.

Setting the globalProvider is already covered in the above sections so I think it can be safely removed.

2020-11-13 18:42 UTC, opbld32 commented
Docs Build status updates of commit _[7229e17](https://github.com/elisenyang/microsoft-graph-docs/commits/7229e17a783b5ad001dd56230a382b0080864fbb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011131841372020-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XRj1HQBc2sZ8bMX0wldMftlZhIdyPi3J1sBu9gJOWks%3D&st=2020-11-13T18%3A37%3A54Z&se=2020-12-14T18%3A42%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 18:44 UTC, opbld33 commented
Docs Build status updates of commit _[08de048](https://github.com/elisenyang/microsoft-graph-docs/commits/08de0484f46531b96c7991a5059f5785f4dfc747)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011131841500291-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DvewR%2BBHokQvXIT4fRF2ujlEKGGezrgBuqF3kwERLpo%3D&st=2020-11-13T18%3A39%3A11Z&se=2020-12-14T18%3A44%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 19:39 UTC, elisenyang commented on concepts/toolkit/providers.md
> +## Providers namespace
Do you have an example of `onProviderUpdated` I can add?

2020-11-13 20:06 UTC, opbld34 commented
Docs Build status updates of commit _[230a54c](https://github.com/elisenyang/microsoft-graph-docs/commits/230a54c282ae89485984c849f39bc6ea7f13d47f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) | [Details](#user-content-2eb55627-d5d63607)
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |

<a id="2eb55627-d5d63607"></a>
### [concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md)
 - **Line 49, Column 78**: **[Warning-file-not-found]** `````Invalid file link: '../get-started/aad-aad-app-registration.md'.`````
 - **Line 162, Column 96**: **[Warning-file-not-found]** `````Invalid file link: '../components/login.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011132005007669-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=blZyVOc%2BbDD016ZRMfn%2BsBDpdBG6D4AYHprj6o1VrW8%3D&st=2020-11-13T20%3A01%3A12Z&se=2020-12-14T20%3A06%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 20:11 UTC, opbld31 commented
Docs Build status updates of commit _[4590730](https://github.com/elisenyang/microsoft-graph-docs/commits/4590730cf0a4092ea97e23c7bb6a76070764744f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) | [Details](#user-content-2eb55627-c89c3339)
[concepts/toolkit/providers/msal.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/msal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-10645) | [Details](#user-content-569ba26a-c89c3339)
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |

<a id="2eb55627-c89c3339"></a>
### [concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md)
 - **Line 49, Column 78**: **[Warning-file-not-found]** `````Invalid file link: '../get-started/aad-aad-app-registration.md'.`````
 - **Line 162, Column 96**: **[Warning-file-not-found]** `````Invalid file link: '../components/login.md'.`````

<a id="569ba26a-c89c3339"></a>
### [concepts/toolkit/providers/msal.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/msal.md)
 - **Line 70, Column 67**: **[Warning-file-not-found]** `````Invalid file link: '../get-started/aad-aad-app-registration.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011132009460324-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ia83xdHCCPoxDEk7KfNvNE3yWgak4zG3P0ZWLit6nhg%3D&st=2020-11-13T20%3A05%3A59Z&se=2020-12-14T20%3A10%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 21:37 UTC, opbld34 commented
Docs Build status updates of commit _[3f6c97b](https://github.com/elisenyang/microsoft-graph-docs/commits/3f6c97b3e7b23458812210499b3ba39d57d5712c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) | [Details](#user-content-2eb55627-afb88997)
[concepts/toolkit/providers/msal.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/msal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-10645) | [Details](#user-content-569ba26a-afb88997)
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |

<a id="2eb55627-afb88997"></a>
### [concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md)
 - **Line 49, Column 78**: **[Warning-file-not-found]** `````Invalid file link: '../get-started/aad-aad-app-registration.md'.`````
 - **Line 164, Column 96**: **[Warning-file-not-found]** `````Invalid file link: '../components/login.md'.`````

<a id="569ba26a-afb88997"></a>
### [concepts/toolkit/providers/msal.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/msal.md)
 - **Line 70, Column 67**: **[Warning-file-not-found]** `````Invalid file link: '../get-started/aad-aad-app-registration.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011132136232053-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q7FcZd%2B9NN4VgNYZL0H8nV7ugAPWiSqOfJKoaxUKSAU%3D&st=2020-11-13T21%3A32%3A42Z&se=2020-12-14T21%3A37%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 21:39 UTC, elisenyang commented on concepts/toolkit/providers.md
> +## Providers namespace
I added 2 more sections - user login/logout and permission scopes

2020-11-13 21:40 UTC, opbld31 commented
Docs Build status updates of commit _[32afa65](https://github.com/elisenyang/microsoft-graph-docs/commits/32afa65a5c93aa8252525d53b7af97bf68c24d5b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |
[concepts/toolkit/providers/msal.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-10645) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011132139174542-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=R3LL3q0%2F%2FvLmP6h41yyuTHd6%2BSrNtleCxW6XHOuXqyQ%3D&st=2020-11-13T21%3A35%3A31Z&se=2020-12-14T21%3A40%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 23:24 UTC, nmetulev commented on concepts/toolkit/providers.md
> + In scenarios where you want to implement this yourself, rather than using the Toolkit's Login component, you can do so by using the `login` and `logout` methods.
```suggestion
 In scenarios where you want to implement this yourself, rather than using the Toolkit's Login component, you can do so by using the `login` and `logout` methods of the provider.
```

2020-11-13 23:25 UTC, opbld33 commented
Docs Build status updates of commit _[f9e62e4](https://github.com/elisenyang/microsoft-graph-docs/commits/f9e62e46561742fce3dee83747ca448b9d61a161)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |
[concepts/toolkit/providers/msal.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-10645) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011132324363623-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sBW8E0k91lLZ1W6gkqwl%2BzTSbsz0HpN3%2BJC4JebEz8s%3D&st=2020-11-13T23%3A20%3A56Z&se=2020-12-14T23%3A25%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 23:31 UTC, nmetulev commented on concepts/toolkit/providers.md
> +## Providers namespace
Yeah, I think this might be a good example:

```ts
import { Providers, ProviderState } from "@microsoft/mgt";

const providerStateChanged = () => {
  if (Providers.globalProvider.state === ProviderState.SignedIn) {
    // user is now signed in
  }
}

// register a callback for when the state changes
Providers.onProviderUpdated(providerStateChanged);

// remove callback if necessary
Providers.removeProviderUpdatedListener(providerStateChanged);
```

2020-11-13 23:33 UTC, opbld32 commented
Docs Build status updates of commit _[11b4d51](https://github.com/elisenyang/microsoft-graph-docs/commits/11b4d5117d39113a846e9764e8de5030857d2056)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |
[concepts/toolkit/providers/msal.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-10645) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011132331532451-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5zaErPsaTQUkAdGyGwCy6FYjC%2FkuQklyRxjzUJ3KD6o%3D&st=2020-11-13T23%3A28%3A02Z&se=2020-12-14T23%3A33%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 20:58 UTC, opbld32 commented
Docs Build status updates of commit _[77c86e2](https://github.com/elisenyang/microsoft-graph-docs/commits/77c86e25b13dcf9dd1afc755c5b603556f949c11)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/sharepoint.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/sharepoint?branch=pr-en-us-10645) | [Details](#user-content-4dd96c28-c3fdfb51)
[concepts/toolkit/providers/teams.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-10645) | [Details](#user-content-ee8dfa19-c3fdfb51)
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |
[concepts/toolkit/providers/msal.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-10645) |

<a id="4dd96c28-c3fdfb51"></a>
### [concepts/toolkit/providers/sharepoint.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/sharepoint.md)
 - **Line 44, Column 93**: **[Warning-file-not-found]** `````Invalid file link: '../get-started/build-a-sharepoing-web-part.md'.`````

<a id="ee8dfa19-c3fdfb51"></a>
### [concepts/toolkit/providers/teams.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/teams.md)
 - **Line 18, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest#using-the-sdk`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011162057275891-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fMvsa1%2BUd3HznoXa62bHOAc67%2FYC%2FPplMwfsiBEG%2FXA%3D&st=2020-11-16T20%3A53%3A41Z&se=2020-12-17T20%3A58%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 21:04 UTC, opbld30 commented
Docs Build status updates of commit _[128b958](https://github.com/elisenyang/microsoft-graph-docs/commits/128b958482c5a52f15dc81950f0fbce64d54580c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/teams.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-10645) | [Details](#user-content-ee8dfa19-750939f2)
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |
[concepts/toolkit/providers/msal.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-10645) |
[concepts/toolkit/providers/sharepoint.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/sharepoint?branch=pr-en-us-10645) |

<a id="ee8dfa19-750939f2"></a>
### [concepts/toolkit/providers/teams.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/teams.md)
 - **Line 18, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest#using-the-sdk`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011162103268659-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bRg7dBHHdtOO8ivtCZgUbCxMEZwhvrvwjqO7Q0f8o14%3D&st=2020-11-16T20%3A59%3A42Z&se=2020-12-17T21%3A04%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 21:57 UTC, nmetulev approved these changes

2020-11-16 21:57 UTC, opbld34 commented
Docs Build status updates of commit _[0bb8900](https://github.com/elisenyang/microsoft-graph-docs/commits/0bb8900d155f9604b6ce3bad516d0c3370854636)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/teams.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-10645) | [Details](#user-content-ee8dfa19-88a5ea86)
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |
[concepts/toolkit/providers/msal.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-10645) |
[concepts/toolkit/providers/sharepoint.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/sharepoint?branch=pr-en-us-10645) |

<a id="ee8dfa19-88a5ea86"></a>
### [concepts/toolkit/providers/teams.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/teams.md)
 - **Line 18, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest#using-the-sdk`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011162156312092-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zMT1jRlNpbEFupZSb8dAqnxsN2oA1LV400eXsm7NOL8%3D&st=2020-11-16T21%3A52%3A44Z&se=2020-12-17T21%3A57%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 03:00 UTC, opbld30 commented
Docs Build status updates of commit _[087c933](https://github.com/elisenyang/microsoft-graph-docs/commits/087c9335cfa0df3bd6a2ead0d5649a68f59b087b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/teams.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-10645) | [Details](#user-content-ee8dfa19-1f80682a)
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |
[concepts/toolkit/providers/msal.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-10645) |
[concepts/toolkit/providers/sharepoint.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/sharepoint?branch=pr-en-us-10645) |

<a id="ee8dfa19-1f80682a"></a>
### [concepts/toolkit/providers/teams.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/teams.md)
 - **Line 18, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest#using-the-sdk`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011170258595553-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Np%2FSpeARvkLzw%2Bkb9MDhm7CxmRZqPhX4ktaqFexBzTA%3D&st=2020-11-17T02%3A55%3A24Z&se=2020-12-18T03%3A00%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 03:02 UTC, opbld34 commented
Docs Build status updates of commit _[18f9eed](https://github.com/elisenyang/microsoft-graph-docs/commits/18f9eede8bd5fca8b75bb518f1aec5052b39d053)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/teams.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-10645) | [Details](#user-content-ee8dfa19-babb764f)
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |
[concepts/toolkit/providers/msal.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-10645) |
[concepts/toolkit/providers/sharepoint.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/sharepoint?branch=pr-en-us-10645) |

<a id="ee8dfa19-babb764f"></a>
### [concepts/toolkit/providers/teams.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/teams.md)
 - **Line 18, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest#using-the-sdk`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011170300015302-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ybOfelh2WQLiKoZFYTXCJXdFpcDOvarV5oUskG1%2F0Zs%3D&st=2020-11-17T02%3A57%3A09Z&se=2020-12-18T03%3A02%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 03:11 UTC, Lauragra approved these changes

2020-11-17 03:11 UTC, opbld34 commented
Docs Build status updates of commit _[7c953b7](https://github.com/elisenyang/microsoft-graph-docs/commits/7c953b76bd5212b9a2595ba62b7933469ce207de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/teams.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-10645) | [Details](#user-content-ee8dfa19-55ff0cf6)
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |
[concepts/toolkit/providers/msal.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-10645) |
[concepts/toolkit/providers/sharepoint.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/sharepoint?branch=pr-en-us-10645) |

<a id="ee8dfa19-55ff0cf6"></a>
### [concepts/toolkit/providers/teams.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/teams.md)
 - **Line 18, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest#using-the-sdk`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011170310255221-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GzXPiOv5vArlcRblro%2F6NVz3a9Q8DTyThHcBvzK6ohY%3D&st=2020-11-17T03%3A06%3A51Z&se=2020-12-18T03%3A11%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 03:14 UTC, opbld33 commented
Docs Build status updates of commit _[d8cdb6b](https://github.com/elisenyang/microsoft-graph-docs/commits/d8cdb6bb4ad282fdcd5d07c654424cffada6fcb4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/teams.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-10645) | [Details](#user-content-ee8dfa19-90c6cc76)
[concepts/toolkit/providers.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers?branch=pr-en-us-10645) |
[concepts/toolkit/providers/custom.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/custom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/custom?branch=pr-en-us-10645) |
[concepts/toolkit/providers/msal.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/msal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/msal?branch=pr-en-us-10645) |
[concepts/toolkit/providers/sharepoint.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/sharepoint?branch=pr-en-us-10645) |

<a id="ee8dfa19-90c6cc76"></a>
### [concepts/toolkit/providers/teams.md](https://github.com/elisenyang/microsoft-graph-docs/blob/elisenyang/mgt-providers-update/concepts/toolkit/providers/teams.md)
 - **Line 18, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /javascript/api/overview/msteams-client?view=msteams-client-js-latest#using-the-sdk`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011170311255325-10645%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YnpnuDJpjZKDR%2FlGfAGmhwGERldNXVB8MaB36AaGsyc%3D&st=2020-11-17T03%3A08%3A59Z&se=2020-12-18T03%3A13%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 03:16 UTC, merged