Various fixes (deployments, orgcontacts...)
microsoftgraph/microsoft-graph-docs pull request #10653
Opened 2020-11-12 13:20 UTC by dkershaw10

2020-11-12 13:21 UTC, opbld30 commented
Docs Build status updates of commit _[91b43b8](https://github.com/dkershaw10/microsoft-graph-docs/commits/91b43b8889569c469ff8b35b40b33f95fa9d83d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-10653) | [Details](#user-content-783b5ae8-eb21dddf)
[concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-10653) | [Details](#user-content-78a1a6da-eb21dddf)
[.unotes/unotes_meta.json](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/.unotes/unotes_meta.json) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/orgcontact.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[concepts/.unotes/unotes_meta.json](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/.unotes/unotes_meta.json) | :white_check_mark:Succeeded | |

<a id="783b5ae8-eb21dddf"></a>
### [concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md)
 - **Line 14, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/organizationsettings?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/organizationsettings-post-profilecardproperties?view=graph-rest-beta`````
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 104, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 162, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/profilecardproperty-get?view=graph-rest-beta`````

<a id="78a1a6da-eb21dddf"></a>
### [concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: ./data-connect-concept-overview.md?view=graph-rest-1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121320129282-10653%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KgnPvf2bAxuIzBV%2F5BITSrNmkOr4PgKKRs240iJI4iI%3D&st=2020-11-12T13%3A16%3A23Z&se=2020-12-13T13%3A21%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 13:22 UTC, opbld31 commented
Docs Build status updates of commit _[fc7c7bb](https://github.com/dkershaw10/microsoft-graph-docs/commits/fc7c7bb9cf3fdbfdb55cd4bf1452c4cf9494773e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-10653) | [Details](#user-content-783b5ae8-9d4e9f07)
[concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-10653) | [Details](#user-content-78a1a6da-9d4e9f07)
[api-reference/beta/resources/orgcontact.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |

<a id="783b5ae8-9d4e9f07"></a>
### [concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md)
 - **Line 14, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/organizationsettings?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/organizationsettings-post-profilecardproperties?view=graph-rest-beta`````
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 104, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 162, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/profilecardproperty-get?view=graph-rest-beta`````

<a id="78a1a6da-9d4e9f07"></a>
### [concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: ./data-connect-concept-overview.md?view=graph-rest-1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121320545574-10653%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NT3hGwTcHH%2FF9vmS5aHperaJdw3gk9CDpa%2Brv%2FhNy0w%3D&st=2020-11-12T13%3A17%3A35Z&se=2020-12-13T13%3A22%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 14:13 UTC, opbld32 commented
Docs Build status updates of commit _[61e0b8a](https://github.com/dkershaw10/microsoft-graph-docs/commits/61e0b8aaa00a146a4b8b0d7693bf30f56ba19cd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-10653) | [Details](#user-content-783b5ae8-e0ef0ba1)
[concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-10653) | [Details](#user-content-78a1a6da-e0ef0ba1)
[.gitignore](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/.gitignore) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/orgcontact.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |

<a id="783b5ae8-e0ef0ba1"></a>
### [concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md)
 - **Line 14, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/organizationsettings?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/organizationsettings-post-profilecardproperties?view=graph-rest-beta`````
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 104, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 162, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/profilecardproperty-get?view=graph-rest-beta`````

<a id="78a1a6da-e0ef0ba1"></a>
### [concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: ./data-connect-concept-overview.md?view=graph-rest-1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121412332754-10653%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Z6%2Bz26iYqIU5uA0LC2gaKBjmYetM6gZc3ZWZqiSv%2F7Q%3D&st=2020-11-12T14%3A08%3A40Z&se=2020-12-13T14%3A13%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 14:55 UTC, opbld30 commented
Docs Build status updates of commit _[b1e67db](https://github.com/dkershaw10/microsoft-graph-docs/commits/b1e67dba3e97bb074d56bf8c46012ab8f36b1ced)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-10653) | [Details](#user-content-783b5ae8-8d870965)
[concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-10653) | [Details](#user-content-78a1a6da-8d870965)
[.gitignore](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/.gitignore) | :white_check_mark:Succeeded | |
[api-reference/beta/api/orgcontact-delta.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-get.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-list.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |

<a id="783b5ae8-8d870965"></a>
### [concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md)
 - **Line 14, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/organizationsettings?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/organizationsettings-post-profilecardproperties?view=graph-rest-beta`````
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 104, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 162, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/profilecardproperty-get?view=graph-rest-beta`````

<a id="78a1a6da-8d870965"></a>
### [concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: ./data-connect-concept-overview.md?view=graph-rest-1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121453506002-10653%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FU5BD6m7ZFQ6OR1NthsJjMnYinoirkusGuYiLrETlZI%3D&st=2020-11-12T14%3A50%3A02Z&se=2020-12-13T14%3A55%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 14:57 UTC, opbld33 commented
Docs Build status updates of commit _[270fd1c](https://github.com/dkershaw10/microsoft-graph-docs/commits/270fd1c59e7919e829405cfab115645dfe4e1252)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-planning-checklist?branch=pr-en-us-10653) | [Details](#user-content-d4ea4bdf-60704ed4)
[concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-10653) | [Details](#user-content-783b5ae8-60704ed4)
[concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-10653) | [Details](#user-content-78a1a6da-60704ed4)
[.gitignore](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/.gitignore) | :white_check_mark:Succeeded | |
[api-reference/beta/api/orgcontact-delta.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-get.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-list.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |

<a id="d4ea4bdf-60704ed4"></a>
### [concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'azure-active-directory'.`````

<a id="783b5ae8-60704ed4"></a>
### [concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md)
 - **Line 14, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/organizationsettings?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/organizationsettings-post-profilecardproperties?view=graph-rest-beta`````
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 104, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 162, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/profilecardproperty-get?view=graph-rest-beta`````

<a id="78a1a6da-60704ed4"></a>
### [concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: ./data-connect-concept-overview.md?view=graph-rest-1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121455572258-10653%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yYm3FoHaf%2FzqzqXDgvzclmfvRnCtRC7M5rmMaLjzIjM%3D&st=2020-11-12T14%3A52%3A11Z&se=2020-12-13T14%3A57%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths a [...]

2020-11-12 15:34 UTC, opbld33 commented
Docs Build status updates of commit _[a1bae8d](https://github.com/dkershaw10/microsoft-graph-docs/commits/a1bae8d01acc4d811780b019d5df3dcd979a849f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-planning-checklist?branch=pr-en-us-10653) | [Details](#user-content-d4ea4bdf-1d71c1ad)
[concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-10653) | [Details](#user-content-783b5ae8-1d71c1ad)
[concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-10653) | [Details](#user-content-78a1a6da-1d71c1ad)
[.gitignore](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/.gitignore) | :white_check_mark:Succeeded | |
[api-reference/beta/api/orgcontact-delta.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-get.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-list.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |

<a id="d4ea4bdf-1d71c1ad"></a>
### [concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'azure-active-directory'.`````

<a id="783b5ae8-1d71c1ad"></a>
### [concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md)
 - **Line 14, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/organizationsettings?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/organizationsettings-post-profilecardproperties?view=graph-rest-beta`````
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 104, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 162, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/profilecardproperty-get?view=graph-rest-beta`````

<a id="78a1a6da-1d71c1ad"></a>
### [concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: ./data-connect-concept-overview.md?view=graph-rest-1.0`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011121532576661-10653%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WejeJPj01gEJHJf5Mm3LEUDVi9Mv3EfjaYDgZQTaBfk%3D&st=2020-11-12T15%3A29%3A57Z&se=2020-12-13T15%3A34%3A57Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are [...]

2020-11-12 17:34 UTC, davidmu1 approved these changes

2020-11-13 14:58 UTC, opbld32 commented
Docs Build status updates of commit _[f337f63](https://github.com/dkershaw10/microsoft-graph-docs/commits/f337f6397df279f52a49546823c3dca995b2f724)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-planning-checklist?branch=pr-en-us-10653) | [Details](#user-content-d4ea4bdf-bd5b0e79)
[concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-10653) | [Details](#user-content-783b5ae8-bd5b0e79)
[concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-10653) | [Details](#user-content-78a1a6da-bd5b0e79)
[.gitignore](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/.gitignore) | :white_check_mark:Succeeded | |
[api-reference/beta/api/orgcontact-delta.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-get.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-list.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/v1.0/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[concepts/known-issues.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10653) |

<a id="d4ea4bdf-bd5b0e79"></a>
### [concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'azure-active-directory'.`````

<a id="783b5ae8-bd5b0e79"></a>
### [concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md)
 - **Line 14, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/organizationsettings?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/organizationsettings-post-profilecardproperties?view=graph-rest-beta`````
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 104, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 158, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did y [...]

2020-11-16 21:42 UTC, opbld31 commented
Docs Build status updates of commit _[5ba23c1](https://github.com/dkershaw10/microsoft-graph-docs/commits/5ba23c15c863d4e463b98b798de02dc152a0a7b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-planning-checklist?branch=pr-en-us-10653) | [Details](#user-content-d4ea4bdf-ae19365a)
[concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-10653) | [Details](#user-content-783b5ae8-ae19365a)
[concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-10653) | [Details](#user-content-78a1a6da-ae19365a)
[.gitignore](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/.gitignore) | :white_check_mark:Succeeded | |
[api-reference/beta/api/orgcontact-delta.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-get.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-list.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/user-revokesigninsessions.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/user-revokesigninsessions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/v1.0/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-revokesigninsessions.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/api/user-revokesigninsessions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[concepts/known-issues.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10653) |

<a id="d4ea4bdf-ae19365a"></a>
### [concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'azure-active-directory'.`````

<a id="783b5ae8-ae19365a"></a>
### [concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md)
 - **Line 14, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/organizationsettings?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/organizationsettings-post-profilecardproperties?view=graph-rest-beta`````
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve [...]

2020-11-16 22:32 UTC, eketo approved these changes
Approved the orgContact changes.

2020-11-16 22:34 UTC, eketo-msft commented
> Approved the orgContact changes.

Woops, wrong Github account.

2020-11-17 01:05 UTC, opbld31 commented
Docs Build status updates of commit _[041ba2f](https://github.com/dkershaw10/microsoft-graph-docs/commits/041ba2f419fba40b2482d276ced1b5f8cb7bcfff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-planning-checklist?branch=pr-en-us-10653) | [Details](#user-content-d4ea4bdf-fb9f98a6)
[concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-10653) | [Details](#user-content-783b5ae8-fb9f98a6)
[concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-10653) | [Details](#user-content-78a1a6da-fb9f98a6)
[.gitignore](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/.gitignore) | :white_check_mark:Succeeded | |
[api-reference/beta/api/orgcontact-delta.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-get.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-list.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/user-revokesigninsessions.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/user-revokesigninsessions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/v1.0/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-revokesigninsessions.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/api/user-revokesigninsessions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[concepts/known-issues.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10653) |

<a id="d4ea4bdf-fb9f98a6"></a>
### [concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'azure-active-directory'.`````

<a id="783b5ae8-fb9f98a6"></a>
### [concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md)
 - **Line 14, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/organizationsettings?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/organizationsettings-post-profilecardproperties?view=graph-rest-beta`````
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve [...]

2020-11-17 01:10 UTC, Lauragra commented on api-reference/beta/api/schemaextension-update.md
> +> When using Graph Explorer to update a schemaExtension, you'll need to specify the **owner** property in the PATCH request body. For more information, see the [Extensions](/graph/known-issues#extens
@bettirosengugi , is Graph Explorer supported for use in production environments? I'm not sure if we should be conveying this in the documentation.

2020-11-17 01:12 UTC, Lauragra commented on api-reference/beta/resources/schemaextension.md
> +|owner|String| The `appId` of the application that is the owner of the schema extension. This property can be supplied on creation, to set the owner.  If not supplied, then the calling application's
I'm not sure if our docs should be implying that Graph Explorer is an approved tool for production use vs. a learning tool for trying APIs in sandbox environments.

2020-11-17 01:13 UTC, Lauragra commented on api-reference/v1.0/api/schemaextension-update.md
> +> [!NOTE]
Same question applies here.

2020-11-17 01:14 UTC, Lauragra commented on api-reference/v1.0/resources/schemaextension.md
> +|owner|String|The `appId` of the application that is the owner of the schema extension. This property can be supplied on creation, to set the owner.  If not supplied, then the calling application's `
Same comment as per the beta topic.

2020-11-17 01:16 UTC, opbld33 commented
Docs Build status updates of commit _[76fd712](https://github.com/dkershaw10/microsoft-graph-docs/commits/76fd71224ceeaf4a4705b6160e587879822a0e80)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-planning-checklist?branch=pr-en-us-10653) | [Details](#user-content-d4ea4bdf-eceea6de)
[concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-10653) | [Details](#user-content-783b5ae8-eceea6de)
[concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-10653) | [Details](#user-content-78a1a6da-eceea6de)
[.gitignore](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/.gitignore) | :white_check_mark:Succeeded | |
[api-reference/beta/api/orgcontact-delta.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-get.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-list.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/user-revokesigninsessions.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/user-revokesigninsessions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/v1.0/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-revokesigninsessions.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/api/user-revokesigninsessions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[concepts/known-issues.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10653) |

<a id="d4ea4bdf-eceea6de"></a>
### [concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'azure-active-directory'.`````

<a id="783b5ae8-eceea6de"></a>
### [concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md)
 - **Line 14, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/organizationsettings?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/organizationsettings-post-profilecardproperties?view=graph-rest-beta`````
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve [...]

2020-11-17 01:22 UTC, opbld32 commented
Docs Build status updates of commit _[ad77298](https://github.com/dkershaw10/microsoft-graph-docs/commits/ad772985050f0b20b832d1efd00009d73c25b1e3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-planning-checklist?branch=pr-en-us-10653) | [Details](#user-content-d4ea4bdf-0745bd89)
[concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-10653) | [Details](#user-content-783b5ae8-0745bd89)
[concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-10653) | [Details](#user-content-78a1a6da-0745bd89)
[.gitignore](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/.gitignore) | :white_check_mark:Succeeded | |
[api-reference/beta/api/orgcontact-delta.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-get.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-list.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/user-revokesigninsessions.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/user-revokesigninsessions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/v1.0/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-revokesigninsessions.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/api/user-revokesigninsessions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[concepts/known-issues.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10653) |

<a id="d4ea4bdf-0745bd89"></a>
### [concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'azure-active-directory'.`````

<a id="783b5ae8-0745bd89"></a>
### [concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md)
 - **Line 14, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/organizationsettings?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/organizationsettings-post-profilecardproperties?view=graph-rest-beta`````
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve [...]

2020-11-17 02:33 UTC, Lauragra commented on concepts/known-issues.md
> +When using `PATCH` to update a schemaExtension using Graph Explorer, you must specify the **owner** property and set it to its current `appid` value (which will need to be an `appId` of an applicatio
Same question re: Graph Explorer.

2020-11-17 02:35 UTC, Lauragra requested changes
I would like us to clarify whether we recommend Graph Explorer as a tool for use in production environments. I was under the impression that we don't. Let's let Bettirose confirm.

2020-11-17 13:05 UTC, dkershaw10 commented on api-reference/beta/resources/schemaextension.md
> +|owner|String| The `appId` of the application that is the owner of the schema extension. This property can be supplied on creation, to set the owner.  If not supplied, then the calling application's
Will fix the repeated sentence.  Thanks.
Customers keep asking this question, which is why I've added this info.  Until we add a capability in the Azure Portal to edit schema extension definitions, GE would be the only way to do this without creating your own custom app.  You could also use PowerShell I suppose.  Again - how is this different from any other client application call Microsoft Graph?  Why are we making a distinction here?  The customer can choose what client apps they use for whatever purpose suits them.  If not GE, then don't grant it the permissions it needs to access Graph (or schema extension), or disable it for your tenant.

Also why does this language (as opposed to other places we mention Graph Explorer) suggest production usage here?

2020-11-17 13:07 UTC, dkershaw10 commented on concepts/known-issues.md
> +When using `PATCH` to update a schemaExtension using Graph Explorer, you must specify the **owner** property and set it to its current `appid` value (which will need to be an `appId` of an applicatio
Actually this doesn't just need to be Graph Explorer.  This could apply to any app (like PowerShell too).

2020-11-17 13:13 UTC, opbld32 commented
Docs Build status updates of commit _[a907132](https://github.com/dkershaw10/microsoft-graph-docs/commits/a9071327e3d02dbe07666b61bdd82bb0fe5a8c41)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-planning-checklist?branch=pr-en-us-10653) | [Details](#user-content-d4ea4bdf-30407778)
[concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-10653) | [Details](#user-content-783b5ae8-30407778)
[concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-10653) | [Details](#user-content-78a1a6da-30407778)
[.gitignore](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/.gitignore) | :white_check_mark:Succeeded | |
[api-reference/beta/api/orgcontact-delta.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-get.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-list.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/user-revokesigninsessions.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/user-revokesigninsessions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/v1.0/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-revokesigninsessions.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/api/user-revokesigninsessions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[concepts/known-issues.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10653) |

<a id="d4ea4bdf-30407778"></a>
### [concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'azure-active-directory'.`````

<a id="783b5ae8-30407778"></a>
### [concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md)
 - **Line 14, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/organizationsettings?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/organizationsettings-post-profilecardproperties?view=graph-rest-beta`````
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve [...]

2020-11-17 14:23 UTC, dkershaw10 commented on api-reference/beta/resources/schemaextension.md
> +|owner|String| The `appId` of the application that is the owner of the schema extension. This property can be supplied on creation, to set the owner.  If not supplied, then the calling application's
Fixed repeated sentence

2020-11-18 04:10 UTC, angelgolfer-ms commented on api-reference/beta/api/orgcontact-update.md
> +#####equest
Line 65: Typo here, please fix.

2020-11-18 05:37 UTC, angelgolfer-ms commented on api-reference/beta/api/schemaextension-update.md
>  > [!NOTE]
Hi @dkershaw10 ,
Can I make an unsolicited contribution? I found the messaging around "own" and "owner" a bit confusing, and further compounded by what owner can be set to. Since we can't change the owner property name or its behavior, let's try to document it more clearly.
I'd suggest moving the content for the two notes back to the top before the "Permissions" section, because there's already a paragraph about who can update an extension: "Only the app that created a schema extension..."

I'll just present the entire section, so you can see the flow is clearer:

```
Update properties in the definition of the specified [schemaExtension](../resources/schemaextension.md).

The update applies to all the resources that are included in the **targetTypes** property of the extension. These resources are among the [supporting resource types](/graph/extensibility-overview#supported-resources).

Only the app that created a schema extension (owner app) can make additive updates to the extension when the extension is in the **InDevelopment** or **Available** status. That means the app cannot remove custom properties or target resource types from the definition. The app can, however, change the description of the extension.

For delegated flow, the signed-in user can update a schema extension as long as the **owner** property of the extension is set to the **appId** of an application the signed-in user owns. That application can be the one that initially created the extension, or some other application owned by the signed-in user. 

This criteria for the **owner** property allows a signed-in user to make updates through other applications they don't own, such as Microsoft Graph Explorer. When using Graph Explorer to update a **schemaExtension** resource, include the **owner** property in the PATCH request body. For more information, see the [Extensions](/graph/known-issues#extensions) section in [Known issues with Microsoft Graph](/graph/known-issues).
```

2020-11-18 06:08 UTC, angelgolfer-ms reviewed
@dkershaw10 , please take a look at a comment I made here: https://github.com/microsoftgraph/microsoft-graph-docs/pull/10653/files#r525826261
I hope that would make the term "own", and setting the owner property a bit clearer.

2020-11-18 14:21 UTC, dkershaw10 commented on api-reference/beta/api/orgcontact-update.md
> +#####equest
I'll make the change but it's pretty pointless.  I'm removing this topic from the TOC and the resource topic as updates to this object are not permitted.

2020-11-18 14:24 UTC, opbld32 commented
Docs Build status updates of commit _[2f02a0e](https://github.com/dkershaw10/microsoft-graph-docs/commits/2f02a0efc0d341e060266b7daabbd71a67d606f2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-planning-checklist?branch=pr-en-us-10653) | [Details](#user-content-d4ea4bdf-1b292fe0)
[concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-10653) | [Details](#user-content-783b5ae8-1b292fe0)
[concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-10653) | [Details](#user-content-78a1a6da-1b292fe0)
[.gitignore](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/.gitignore) | :white_check_mark:Succeeded | |
[api-reference/beta/api/orgcontact-delta.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-get.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-list.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/user-revokesigninsessions.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/user-revokesigninsessions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/v1.0/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-revokesigninsessions.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/api/user-revokesigninsessions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[concepts/known-issues.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10653) |

<a id="d4ea4bdf-1b292fe0"></a>
### [concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'azure-active-directory'.`````

<a id="783b5ae8-1b292fe0"></a>
### [concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md)
 - **Line 14, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/organizationsettings?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/organizationsettings-post-profilecardproperties?view=graph-rest-beta`````
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve [...]

2020-11-18 14:25 UTC, dkershaw10 commented on api-reference/beta/api/schemaextension-update.md
>  > [!NOTE]
@angelgolfer-ms  Updates made.  Thanks for the feedback

2020-11-18 14:26 UTC, dkershaw10 commented on api-reference/beta/api/orgcontact-update.md
> +#####equest
Fixed

2020-11-18 14:29 UTC, dkershaw10 commented on api-reference/beta/resources/schemaextension.md
> +|owner|String| The `appId` of the application that is the owner of the schema extension. This property can be supplied on creation, to set the owner.  If not supplied, then the calling application's
@Lauragra - I don't think use of GE against production environments is an issue.  It's just like any other client app that needs to be approved.  No matter what you say here, that choice is up to admins.
That said - can you clarify exactly what it is about the language used that suggests "Graph Explorer is an approved tool for production use vs. a learning tool for trying APIs in sandbox environments"?
cc: @bettirosengugi

2020-11-18 17:13 UTC, bettirosengugi commented
> I would like us to clarify whether we recommend Graph Explorer as a tool for use in production environments. I was under the impression that we don't. Let's let Bettirose confirm.

Graph Explorer can be used for both prod and demo accounts

2020-11-18 17:15 UTC, bettirosengugi commented on api-reference/beta/resources/schemaextension.md
> +|owner|String| The `appId` of the application that is the owner of the schema extension. This property can be supplied on creation, to set the owner.  If not supplied, then the calling application's
Graph Explorer can be used for both prod and demo accounts depending on the type of user, learners use the demo accounts while expert developers use it with their prod accounts to experiment.

2020-11-19 05:10 UTC, opbld34 commented
Docs Build status updates of commit _[1ee2cef](https://github.com/dkershaw10/microsoft-graph-docs/commits/1ee2cef9ada3ef0239f062ae1076077b6c126856)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-planning-checklist?branch=pr-en-us-10653) | [Details](#user-content-d4ea4bdf-5ab1f70d)
[concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/add-properties-profilecard?branch=pr-en-us-10653) | [Details](#user-content-783b5ae8-5ab1f70d)
[concepts/deployments.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/deployments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/deployments?branch=pr-en-us-10653) | [Details](#user-content-78a1a6da-5ab1f70d)
[.gitignore](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/.gitignore) | :white_check_mark:Succeeded | |
[api-reference/beta/api/orgcontact-delta.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-delta.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-get.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-get?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-list.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/orgcontact-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/orgcontact-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/api/user-revokesigninsessions.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/api/user-revokesigninsessions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/orgcontact-delta?view=graph-rest-beta&branch=pr-en-us-10653) (graph-rest-beta) |
[api-reference/v1.0/api/schemaextension-update.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/api/schemaextension-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[api-reference/v1.0/api/user-revokesigninsessions.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/api/user-revokesigninsessions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/schemaextension.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/api-reference/v1.0/resources/schemaextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/schemaextension?view=graph-rest-1.0&branch=pr-en-us-10653) (>= graph-rest-1.0) |
[concepts/known-issues.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10653) |

<a id="d4ea4bdf-5ab1f70d"></a>
### [concepts/migrate-azure-ad-graph-planning-checklist.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/migrate-azure-ad-graph-planning-checklist.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'azure-active-directory'.`````

<a id="783b5ae8-5ab1f70d"></a>
### [concepts/add-properties-profilecard.md](https://github.com/dkershaw10/microsoft-graph-docs/blob/dkershaw10-newFixes/concepts/add-properties-profilecard.md)
 - **Line 14, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilecardproperty?view=graph-rest-beta`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/organizationsettings?view=graph-rest-beta`````
 - **Line 51, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Example''. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onpremisesextensionattributes?view=graph-rest-beta`````
 - **Line 78, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/organizationsettings-post-profilecardproperties?view=graph-rest-beta`````
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve [...]

2020-11-19 05:24 UTC, merged