Added documentation for hide attendees property in v1.0
microsoftgraph/microsoft-graph-docs pull request #10693
Opened 2020-11-16 09:48 UTC by grjsrinivas

@angelgolfer-ms Please review the PR for Documentation of hideAttendees in Graph v1.0

2020-11-16 09:49 UTC, opbld31 commented
Docs Build status updates of commit _[5713755](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5713755ebfbb46e5e732dca2d77f8a278078a747)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-53380360)
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-53380360)
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-00e7caeb-53380360)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10693) | [Details](#user-content-de0bbbbb-53380360)
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |

<a id="2f98de3e-53380360"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de5a61a4-53380360"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="00e7caeb-53380360"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-53380360"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/event?view=graph-rest-1.0`````
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011160948432237-10693%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9AsPp2b5OlzIej8xDyY0v1wpDi%2BCvBNg6bJqSEq0laM%3D&st=2020-11-16T09%3A44%3A55Z&se=2020-12-17T09%3A49%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 09:56 UTC, opbld30 commented
Docs Build status updates of commit _[bb7ae93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb7ae9350d538fca03c41b8114fb21191ff2714f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-a090b7b9)
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-a090b7b9)
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-00e7caeb-a090b7b9)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10693) | [Details](#user-content-de0bbbbb-a090b7b9)
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |

<a id="2f98de3e-a090b7b9"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de5a61a4-a090b7b9"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="00e7caeb-a090b7b9"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-a090b7b9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md)
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011160955454311-10693%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ydFOZx3I4CxiRfQwMeDNol%2FtpsDqGIm4%2FFFQ4BAFinU%3D&st=2020-11-16T09%3A51%3A55Z&se=2020-12-17T09%3A56%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 02:41 UTC, opbld30 commented
Docs Build status updates of commit _[1da0540](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1da05402f967c08fc020ba87bc0ebb9cf69523c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-4dee647d)
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-4dee647d)
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-00e7caeb-4dee647d)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10693) | [Details](#user-content-de0bbbbb-4dee647d)
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |

<a id="2f98de3e-4dee647d"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de5a61a4-4dee647d"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="00e7caeb-4dee647d"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-4dee647d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md)
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011170240278014-10693%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8o92IxWQleHdewFeDYM8NWT35IEK%2FozIxzspRnbV9Wo%3D&st=2020-11-17T02%3A36%3A53Z&se=2020-12-18T02%3A41%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 02:43 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | v1.0 | Added the **hideAttendees** property to the [event](/graph/api/resources/event?view=graph-rest-1.0&preserve-view=true) entity.
Please also add a changelist item to the Microsoft.Exchange.json file for the filterable changelog.

2020-11-17 02:44 UTC, Lauragra requested changes
We need an update to the JSON file for the changelog with this PR.

2020-11-17 07:54 UTC, angelgolfer-ms commented on api-reference/v1.0/api/calendar-post-events.md
>      "hasAttachments": false,
Aside from updating calendar-post-events.md, please update user-post-events.md.
Also, please document the similar for beta.

2020-11-17 07:56 UTC, angelgolfer-ms commented on api-reference/v1.0/api/event-update.md
> +Here is an example of the response.
Line 138:
Please keep the boilerplate sentence "Note: The response object shown here may be truncated for brevity."

2020-11-17 08:12 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/event.md
> +|hideAttendees|Boolean|When set to true, the tracking list is hidden from meeting attendees. Each attendee only sees themselves in the meeting invite and meeting tracking list.|
Line 72:
I think you mean the "Tracking" tab is still there but shows only the user specified in the query URL, is that right?
If that's the case, then please rephrase:
"When set to true, each attendee only sees themselves in the meeting invite and meeting tracking list."

2020-11-17 08:15 UTC, angelgolfer-ms commented on api-reference/v1.0/api/event-update.md
> +|hideAttendees|Boolean|When set to `true`, the tracking list is hidden from meeting attendees. Each attendee only sees themselves in the meeting invite and meeting tracking list.|
Line 61: 
Per my comment in event.md, please change the description to:
"When set to true, each attendee only sees themselves in the meeting request and meeting **Tracking** list."

Please note I changed to "meeting request" for consistency with terminology in the docs. I also bolded "Tracking" as I am referring to the Tracking tab in the UI and am applying the corresponding styling.

2020-11-17 08:18 UTC, angelgolfer-ms requested changes
Hi @grjsrinivas , thank you for submitting the PR.
Please see my comments. Please also document the similar for the beta version.

2020-11-17 16:45 UTC, opbld33 commented
Docs Build status updates of commit _[c38edc7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c38edc748fbd4e59e77d6508c937d670bdaf736f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6e524d86)

<a id="6e524d86"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011171644586332-10693%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LjrFA4kO7wM%2FKHWC%2BfnP5Atop33A05jJbV%2FphGussBo%3D&st=2020-11-17T16%3A40%3A19Z&se=2020-12-18T16%3A45%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 16:51 UTC, Lauragra commented on changelog/Microsoft.Exchange.json
> +      "CreatedDateTime": "2020-11-01T00:00:00",
Please set the date to 11-17. The date should not be set to the first of the month because in our time zone, it will show as having shipping in October instead of November.

2020-11-17 16:53 UTC, grjsrinivas commented on concepts/changelog.md
> +| Addition | v1.0 | Added the **hideAttendees** property to the [event](/graph/api/resources/event?view=graph-rest-1.0&preserve-view=true) entity.
Done.

2020-11-17 16:54 UTC, opbld31 commented
Docs Build status updates of commit _[a633685](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a63368564cdce25dfb7955cae1aad9899579c0a6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-371cf5d1)

<a id="371cf5d1"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011171653523622-10693%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OB6eQYJQ6hdOOVoc0pFiuATx61WPcoYdcGscAmMZfT8%3D&st=2020-11-17T16%3A49%3A13Z&se=2020-12-18T16%3A54%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 16:54 UTC, grjsrinivas commented on changelog/Microsoft.Exchange.json
> +      "CreatedDateTime": "2020-11-01T00:00:00",
Done

2020-11-17 17:02 UTC, opbld33 commented
Docs Build status updates of commit _[66d2369](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66d2369c2668a91671059514948a7e86901b938d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-463f2514)
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-463f2514)
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-00e7caeb-463f2514)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10693) | [Details](#user-content-de0bbbbb-463f2514)
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="2f98de3e-463f2514"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de5a61a4-463f2514"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="00e7caeb-463f2514"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-463f2514"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md)
 - **Line 32, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011171700372283-10693%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8%2Fu%2FUQlhYFGjaE7jeqHOV3GPXW3RhVkNUcBdQvaI31o%3D&st=2020-11-17T16%3A57%3A07Z&se=2020-12-18T17%3A02%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 09:10 UTC, angelgolfer-ms commented on api-reference/v1.0/api/event-update.md
> +>**Note:** Note: The response object shown here may be truncated for brevity.
Line 138-140:
@grjsrinivas , the double "Note" in line 140 is not something we do. Can you please put the two sentences back in the same line, as in the original? We don't need the third sentence though. Thanks.

2020-11-18 09:10 UTC, angelgolfer-ms commented on api-reference/v1.0/api/event-update.md
> +Here is an example of the response.
@grjsrinivas , we can leave out the last sentence "All of the properties will be returned from an actual call." please.

2020-11-18 09:15 UTC, angelgolfer-ms requested changes
@grjsrinivas , thanks for incorporating yesterday's feedback. Just one editorial comment from me. After you incorporate that one, I think this PR is good to be published.
Please follow the workflow in this [topic](https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55089/Sync-schema-with-doc) and set the PR to Ready to merge when the API and CSDL are available to customers.

2020-11-18 09:32 UTC, angelgolfer-ms commented on api-reference/v1.0/api/event-get.md
> +    "hideAttendees": false,
BTW, just noticed you haven't updated the example request. Can you include the hideAttendees property in the $select query parameter? Otherwise the response wouldn't include that property, right?

2020-11-18 09:32 UTC, angelgolfer-ms requested changes
Added one more comment in event-get.md, total 2 comments from today. Please take a look.

2020-11-18 09:41 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/event.md
> +|hideAttendees|Boolean|When set to `true`, each attendee only sees themselves in the meeting request and meeting **Tracking** list.|
Line 72:
In the description, perhaps you can add "Default is `true`.", if that's the case?

2020-11-18 09:41 UTC, angelgolfer-ms commented on api-reference/v1.0/api/event-update.md
>  |importance|String|The importance of the event. The possible values are: `low`, `normal`, `high`.|
Line 61:
In the description, perhaps you can add "Default is `true`.", if that's the case?

2020-11-18 10:49 UTC, grjsrinivas commented on api-reference/v1.0/api/event-update.md
>  |importance|String|The importance of the event. The possible values are: `low`, `normal`, `high`.|
The default is false which will be similar to the existing behaviour.

2020-11-18 11:37 UTC, grjsrinivas commented on api-reference/v1.0/api/event-update.md
> +>**Note:** Note: The response object shown here may be truncated for brevity.
Done

2020-11-18 11:37 UTC, grjsrinivas commented on api-reference/v1.0/resources/event.md
> +|hideAttendees|Boolean|When set to `true`, each attendee only sees themselves in the meeting request and meeting **Tracking** list.|
The default is false which will be similar to the existing behaviour.

2020-11-18 11:37 UTC, grjsrinivas commented on api-reference/v1.0/api/event-get.md
> +    "hideAttendees": false,
Thanks for pointing out. Have corrected it.

2020-11-18 11:38 UTC, opbld34 commented
Docs Build status updates of commit _[8090af3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8090af392a0470495311351d228a7b0bf7c91ef5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-3a189ce2)
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-3a189ce2)
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-00e7caeb-3a189ce2)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10693) | [Details](#user-content-de0bbbbb-3a189ce2)
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="2f98de3e-3a189ce2"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de5a61a4-3a189ce2"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="00e7caeb-3a189ce2"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-3a189ce2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md)
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-onboarding-devicecomanagementauthorityconfiguration?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationcategory?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingcollectiondefinition?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingdefinition?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicy?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicyassignment?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsetting?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettingdefinition?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did y [...]

2020-11-18 11:48 UTC, opbld30 commented
Docs Build status updates of commit _[5ee7387](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5ee7387461e7ceb56ccd20d3e272156fb2e162ed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-9e398443)
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-9e398443)
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-00e7caeb-9e398443)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10693) | [Details](#user-content-de0bbbbb-9e398443)
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="2f98de3e-9e398443"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de5a61a4-9e398443"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="00e7caeb-9e398443"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-9e398443"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md)
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-onboarding-devicecomanagementauthorityconfiguration?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationcategory?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingcollectiondefinition?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingdefinition?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicy?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicyassignment?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsetting?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsettingdefinition?view=graph-rest-beta`````
 - **Line 55, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did y [...]

2020-12-03 07:50 UTC, angelgolfer-ms commented on api-reference/v1.0/api/event-get.md
> +    "hideAttendees": false,
@grjsrinivas , this is what I see on your staging site for the first example request, without including hideAttendees in the query parameter $select (https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10693&tabs=http#request-1):

GET https://graph.microsoft.com/v1.0/me/events/AAMkAGIAAAoZDOFAAA=?$select=subject,body,bodyPreview,organizer,attendees,start,end,location 

Can you actually include hideAttendees in the $select query paramter?

2020-12-03 07:52 UTC, angelgolfer-ms commented on api-reference/v1.0/api/event-get.md
> +    "hideAttendees": false,
Ok, for something straight-forward as such, to cut the back and forth, FYI I am going to add hideAttendees in the $select query parameter.

2020-12-03 07:54 UTC, angelgolfer-ms commented on api-reference/v1.0/api/event-update.md
>  |importance|String|The importance of the event. The possible values are: `low`, `normal`, `high`.|
Yeah, so it would be helpful to state that the default is false then.
FYI I added that to line 61, to cut the back and forth.

2020-12-03 07:55 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/event.md
> +|hideAttendees|Boolean|When set to `true`, each attendee only sees themselves in the meeting request and meeting **Tracking** list.|
FYI I added "Default is false."

2020-12-03 07:57 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.json
> +      "CreatedDateTime": "2020-11-17T00:00:00",
Line 17:
Please update the date to be in December, otherwise this will come out confusing to customers.

2020-12-03 07:58 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Addition | v1.0 | Added the **hideAttendees** property to the [event](/graph/api/resources/event?view=graph-rest-1.0&preserve-view=true) entity.
Please move the changelog item in changelog.md to go under December.

2020-12-03 08:03 UTC, angelgolfer-ms requested changes
Hi @grjsrinivas , FYI I applied a couple of the fixes directly to your PR. Please see my comments to date the changelog json and changelog MD files as December.

2020-12-03 08:06 UTC, opbld34 commented
Docs Build status updates of commit _[b297203](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b297203e90d2cbae0c3c4b5a3ce12e0d4e7cce5d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10693) | [Details](#user-content-de0bbbbb-0429b755)
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-0429b755)
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-0429b755)
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-00e7caeb-0429b755)
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-0429b755"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md)
 - **Line 14, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Changelog for Microsoft Graph'.`````

<a id="2f98de3e-0429b755"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de5a61a4-0429b755"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="00e7caeb-0429b755"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012030804390690-10693%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LZoZFHYNhHipHp%2Brw%2FG3uhCVXrN1oLfjY0ik6%2B1pQao%3D&st=2020-12-03T08%3A01%3A39Z&se=2021-01-03T08%3A06%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47" [...]

2020-12-03 08:08 UTC, opbld34 commented
Docs Build status updates of commit _[394642e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/394642e67ae6200648b8ae24a87c66c0e2262950)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10693) | [Details](#user-content-de0bbbbb-8e0d4e46)
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-8e0d4e46)
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-8e0d4e46)
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-00e7caeb-8e0d4e46)
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-8e0d4e46"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md)
 - **Line 14, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Changelog for Microsoft Graph'.`````

<a id="2f98de3e-8e0d4e46"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de5a61a4-8e0d4e46"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="00e7caeb-8e0d4e46"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012030804478098-10693%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p7wBpAyWeJzFBLc%2BiYuO7V6mXSi1aJBfp%2Bg9h%2BufxHs%3D&st=2020-12-03T08%3A03%3A38Z&se=2021-01-03T08%3A08%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47" [...]

2020-12-17 05:55 UTC, opbld32 commented
Docs Build status updates of commit _[3d40d2a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d40d2a262df1d7969d37d41cce561996d0a4436)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-e79ff911)
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-e79ff911)
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-00e7caeb-e79ff911)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10693) | [Details](#user-content-de0bbbbb-e79ff911)
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="2f98de3e-e79ff911"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset.`````

<a id="de5a61a4-e79ff911"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset.`````

<a id="00e7caeb-e79ff911"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset.`````

<a id="de0bbbbb-e79ff911"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 79, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 150, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 151, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 151, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 152, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 152, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170553534887-10693%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yBRvfA6qN5vQc69G6AGLQcJ2k20jUFrWEOw1nEmyQ7o%3D&st=2020-12-17T05%3A50%3A11Z&se=2021-01-17T05%3A55%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build rep [...]

2020-12-17 05:59 UTC, opbld32 commented
Docs Build status updates of commit _[1c3d106](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c3d1062fdde2510842410b81c0bedc8e433dd56)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10693) | [Details](#user-content-de0bbbbb-30940cfa)
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-30940cfa)
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-30940cfa)
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-00e7caeb-30940cfa)
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-30940cfa"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md)
 - **Line 107, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 85, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 154, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 155, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 155, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 156, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

<a id="2f98de3e-30940cfa"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset.`````

<a id="de5a61a4-30940cfa"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset.`````

<a id="00e7caeb-30940cfa"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod [...]

2020-12-17 06:01 UTC, Bhupesh12Hub commented on changelog/Microsoft.Exchange.json
> +      "CreatedDateTime": "2020-11-17T00:00:00",
Done.

2020-12-17 06:04 UTC, Bhupesh12Hub commented
@angelgolfer-ms, i have incorporated the all feedback comments.
This PR is good to publish.
@Lauragra @Harini84

2020-12-18 05:09 UTC, Harini84 commented
> @angelgolfer-ms, i have incorporated the all feedback comments.
> This PR is good to publish.
> @Lauragra @Harini84

@Bhupesh12Hub 
Please re-request for review and set the label to 'readytomerge'.

![image](https://user-images.githubusercontent.com/59600764/102577024-2412c900-411d-11eb-8373-bf7c41bdfc8f.png

2020-12-18 08:54 UTC, angelgolfer-ms approved these changes
Looks good!

2020-12-19 01:29 UTC, opbld31 commented
Docs Build status updates of commit _[0398c6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0398c6b1c422d7e49414d96b8053765ed7f44b9e)_: 

:clock10: **Pending**: waiting for processors ([26](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 26 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-19 01:29 UTC, opbld34 commented
Docs Build status updates of commit _[0398c6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0398c6b1c422d7e49414d96b8053765ed7f44b9e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-61b54155)

<a id="61b54155"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190128591383-10693%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yAMNZs9xYPsxz3jGYgKBZPD6JEuGoCrQ1I4NLgJg0Ms%3D&st=2020-12-19T01%3A24%3A20Z&se=2021-01-19T01%3A29%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 01:30 UTC, opbld30 commented
Docs Build status updates of commit _[09c982d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09c982d7ac25b73391877b6eb07f53fd3b9f0841)_: 

:clock10: **Pending**: waiting for processors ([26](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 26 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-19 01:30 UTC, opbld33 commented
Docs Build status updates of commit _[cfd7393](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cfd7393efd3354d47d65e65604770e2d3bdc5aa5)_: 

:clock10: **Pending**: waiting for processors ([24](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 24 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-19 01:31 UTC, opbld30 commented
Docs Build status updates of commit _[09c982d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09c982d7ac25b73391877b6eb07f53fd3b9f0841)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-51f380a6)
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-51f380a6)
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-00e7caeb-51f380a6)
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10693) |

<a id="2f98de3e-51f380a6"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset.`````

<a id="de5a61a4-51f380a6"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset.`````

<a id="00e7caeb-51f380a6"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190130239430-10693%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BjXtDq1bRS3xZ3HYaMsp6%2Fl%2FCkKdBSIfgDBikuKW3to%3D&st=2020-12-19T01%3A26%3A32Z&se=2021-01-19T01%3A31%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 01:32 UTC, opbld30 commented
Docs Build status updates of commit _[cfd7393](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cfd7393efd3354d47d65e65604770e2d3bdc5aa5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-d59b6408)
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-d59b6408)
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-00e7caeb-d59b6408)
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="2f98de3e-d59b6408"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset.`````

<a id="de5a61a4-d59b6408"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset.`````

<a id="00e7caeb-d59b6408"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190130336083-10693%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hlvsdCtaSDa7EletWxNOz8ctWVnm%2B0Q8UkWwktSJYCI%3D&st=2020-12-19T01%3A27%3A51Z&se=2021-01-19T01%3A32%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 01:43 UTC, opbld30 commented
Docs Build status updates of commit _[c6c0739](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c6c0739f48710410af5ea3a75a8164cb99d8f83c)_: 

:clock10: **Pending**: waiting for processors ([20](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 20 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-19 01:45 UTC, opbld34 commented
Docs Build status updates of commit _[c6c0739](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c6c0739f48710410af5ea3a75a8164cb99d8f83c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-2f98de3e-59c8218f)
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-59c8218f)
[api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) | [Details](#user-content-00e7caeb-59c8218f)
[api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/user-post-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10693) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10693) |

<a id="2f98de3e-59c8218f"></a>
### [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/calendar-post-events.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Create event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/calendar-post-events.md(2,8), v1.0/api/group-post-events.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Create event' is duplicated with other articles: 'v1.0/api/calendar-post-events.md(10,1), v1.0/api/group-post-events.md(10,1)'. First level headings must be unique within a docset.`````

<a id="de5a61a4-59c8218f"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset.`````

<a id="00e7caeb-59c8218f"></a>
### [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/hideAttendees/v1.0/api-reference/v1.0/api/event-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-update.md(2,8), v1.0/api/group-update-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Update event' is duplicated with other articles: 'v1.0/api/event-update.md(10,1), v1.0/api/group-update-event.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012190143453481-10693%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kQziGHvwFkIW9Q2jUWQKLY%2B9RmTSJnbStffP8bZ6F2Q%3D&st=2020-12-19T01%3A39%3A59Z&se=2021-01-19T01%3A44%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-19 01:50 UTC, merged

2020-12-19 01:52 UTC, angelgolfer-ms commented
> Looks good!
> However, @Bhupesh12Hub , our Github bot just slapped a "conflicting" label on your changelog.md file.
> Please resolve the conflict(s) in that file.

@Bhupesh12Hub , since you haven't responded and today is the last day to publish this year, FYI I went ahead to fix the changelog, so to merge this PR to master.

2020-12-28 06:11 UTC, grjsrinivas commented
Thanks for actively reviewing and closing this @angelgolfer-ms